### ISSUE TITLE
Vue simplifiée / généalogie non affichée

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#1]
Généalogie pas passée dans la vue simplifiée (bien dans la vue par défaut)

**Comment by vbombaerts** [comment]
Pas résolu. Fonction du type de métadonnées. 
OK pour MD d'application (hierarchy level non spécifié)
Sans objet pour les MD de service
KO pour métadonnées de données (lié au profil wallon ??)

![image 656](https://f.cloud.github.com/assets/6093597/1851329/3a28d9f8-76e7-11e3-829c-152dd08eaadd.png)

**Comment by vbombaerts** [comment]
Note : dans Metawal 2, lors de la validation des fiches de données, j'ai systématiquement une erreur indiquant que la généalogie n'est pas renseignée alors qu'elle est complétée. L'erreur est peut-être liée à ça.

**Comment by vbombaerts** [comment]
La généalogie est aussi manquante dans la vue "impression"

**Comment by fxprunayre** [comment]
Vérifier dans la fiche la présence de l'attribut gco:isoType :

Par exemple, pour PICC, la fiche en démo a 

```
<gmd:lineage>
<rw:LI_Lineage>
<gmd:statement>
<gco:CharacterString>S
```

et devrait être 

```
<gmd:lineage>
    <rw:LI_Lineage gco:isoType="gmd:LI_Lineage">
        <gmd:statement>
```

Ouvrir la fiche en édition va corriger ce pb automatiquement. Sauvegarder et c'est ok en consultation et impression.

A priori, lors de la migration tous les attribus isoType sont ajoutés (cf. https://github.com/spacebelGIS/metawal-core-geonetwork/blob/metawal-develop/web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139.rw/process/metawal-schema-updates.xsl#L38)

Idem lors de la sauvegarde d'une fiche https://github.com/spacebelGIS/metawal-core-geonetwork/blob/metawal-develop/web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139.rw/update-fixed-info.xsl#L46

Il faut donc savoir comment a été importée la fiche ? Normalement une fois que metawal2 ne sera plus en ligne, nous ne devrions plus rencontrer ce genre de pb.

> Note : dans Metawal 2, lors de la validation des fiches de données, j'ai systématiquement une erreur indiquant que la généalogie n'est pas renseignée alors qu'elle est complétée. L'erreur est peut-être liée à ça.

La validation c'est un autre pb. Cf #97
