### ISSUE TITLE
Console admin / statut / statut - compteurs

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#100]
C'est joli, mais j'ai besoin d'un guide d'interprétation de l'information. Qu'est-ce que ça signifie ? Quelles actions dois-je prendre si c'est dans le rouge ?
![image 626](https://f.cloud.github.com/assets/6093597/1663766/3648ec42-5c1b-11e3-83e9-66caa20876dc.png)

**Comment by fxprunayre** [comment]
> Qu'est-ce que ça signifie ? 

Entre le catalogue et la base de données il y a un pool de connexion.
La taille du pool est 30 connexions.
dbPoolActive = 3 - il y a 3 connexions active
dbPoolIdle = 8 - il y a 8 connexions latentes

cf. http://geonetwork-opensource.org/manuals/trunk/fra/users/admin/advanced/advanced/index.html#pool-de-connexions

> Quelles actions dois-je prendre si c'est dans le rouge ?

Relancer le serveur s'il ne répond plus. Mais normalement ca veut juste dire qu'il y a bcp d'utilisateur.
