### ISSUE TITLE
La fiche descriptive s'ouvre dans le coin supérieur droit...

### ISSUE THREAD

**Issue by metawal** [SPW-DIG/metawal-core-geonetwork#102]
... ce serait plus esthétique si elle s'ouvrait au centre de l'écran.

**Comment by fxprunayre** [comment]
Ajout d'un lien sur la page wiki discussion ergonomie https://github.com/spacebelGIS/metawal-core-geonetwork/wiki/Ergonomie-et-design-des-interfaces-Metawal

**Comment by fxprunayre** [comment]
V4, plein écran sans popup
