### ISSUE TITLE
Console admin / statut / statistiques

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#103]
Les graphiques : un coup ils sont là, un coup pas...

**Comment by fxprunayre** [comment]
Merci de préciser un peu plus pour aider à réproduire : 
- la page : est-ce stat sur recherche, sur contenu ?
- quel graphique ? tous ou un en particulier ?
- la plateforme : a priori test SPW
- le navigateur, la version du navigateur
- éventuellement des erreurs JS ? des erreurs de requête (dans la console du navigateur - si ca vous parle) ?

**Comment by fxprunayre** [comment]
http://metawal4.test.wallonie.be/geonetwork/srv/fre/statistics-content-metadata?_content_type=json?by=category&isTemplate=n retourne

```
{
error: {
message: "org.hibernate.exception.SQLGrammarException: could not extract ResultSet",
class: "PersistenceException",
stack: {
at: "jeeves.config.springutil.JeevesDelegatingFilterProxy JeevesDelegatingFilterProxy.java line 64 #doFilter"
},
request: { }
}
}
```

Semble ok dans GN3. En lien avec Oracle ?

**Comment by fxprunayre** [comment]
Code erreur Oracle retourné http://www.dba-oracle.com/t_ora_00979_not_a_group_by_expression.htm
Requête = 

```
select 
  group1_.id as col_0_0_, count(metadata0_.id) as col_1_0_, group1_.id as id1_5_, 
  group1_.description as description2_5_, group1_.email as email3_5_, 
  group1_.logo as logo4_5_, group1_.name as name5_5_, 
  group1_.referrer as referrer6_5_, group1_.website as website7_5_ 
from metawal2.Metadata metadata0_, metawal2.Groups group1_ 
where metadata0_.groupOwner=group1_.id 
group by group1_.id;
```

**Comment by davinciagf** [comment]
Cette requête ne passe pas via SQLdevelopper (Oracle). 
Par contre, la requête suivante passe:
select group1_.id as col_0_0_, count(metadata0_.id) as col_1_0_, group1_.id as id1_5_, group1_.description as description2_5_, group1_.email as email3_5_, group1_.logo as logo4_5_, group1_.name as name5_5_, group1_.referrer as referrer6_5_, group1_.website as website7_5_ from metawal2.Metadata metadata0_, metawal2.Groups group1_ where metadata0_.groupOwner=group1_.id group by group1_.id,group1_.description,group1_.email,group1_.logo,group1_.name,group1_.referrer,group1_.website;

**Comment by davinciagf** [comment]
Problème lié à spring et la gestion des requêtes sous Oracle (besoin de rajouter les éléments du group by) 
Résolution via passage sous Postgres

**Comment by fxprunayre** [comment]
Migration to ES, see https://github.com/geonetwork/core-geonetwork/pull/2023

**Comment by vbombaerts** [comment]
@fxprunayre 
Stats et proxy, stats et redirection : comment ça va fonctionner ? les services CSW sont derrière http://geoservices3.wallonie.be/metawal/csw (csw-inspire). Les requêtes qui ne sont pas faites directement à http://metawal.wallonie.be seront-elles traitées ?

**Comment by fxprunayre** [comment]
Oui, elles arrivent toutes dans GeoNetwork et sont loguées. Avec les tableaux de bords sur Apache, on pourra les distinguer pour savoir quelles adresses sont utilisées.

**Comment by vbombaerts** [comment]
c'était un problème oracle + nouveau DAOBS
