### ISSUE TITLE
Chargement des imagettes

### ISSUE THREAD

**Issue by geologiewallonie** [SPW-DIG/metawal-core-geonetwork#105]
- L'upload ne fonctionne pas.
- Le lien vers une URL affiche une erreur.
  ![5](https://f.cloud.github.com/assets/6093460/1664001/dc79f55c-5c20-11e3-8e36-5589b9e45aa8.JPG)

**Comment by geologiewallonie** [comment]
Idem pour la liaison vers des services parents !

**Comment by fxprunayre** [comment]
>  Idem pour la liaison vers des services parents !

cf #88 

Ce ticket ne concerne que les imagettes.

**Comment by fxprunayre** [comment]
Vérifier que dans Admin > settings, "automatic fix" soit actif.
