### ISSUE TITLE
console admin / gérer les utilisateurs - réinitialiser le mdp

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#106]
Ajouter la possibilité pour l'admin de réinitialiser le mdp d'un utilisateur.

**Comment by fxprunayre** [comment]
Contournement : Le lien est accessible à partir d'ici http://metawal3.test.wallonie.be/geonetwork/srv/fre/catalog.signin (rappel par email)

**Comment by vbombaerts** [comment]
Ne fonctionne pas à travers la nouvelle interface d'admin.
Si je vais sur gérer les utilisateurs, que je choisis un utilisateur et que je clique sur Changer le mot de passe --> rien ne se passe. J'ai juste une infobulle avec le message  cantDeleteUserHavingRecords
Si j'essaie de créer un utilisateur (ne fonctionne pas, voir autre ticket) et que je retourne sur l'utilisateur duquel je veux changer le mot de passe, alors les champs relatifs au mdp s'affichent et je peux en modifier les valeurs. Par contre, je ne sais pas si les valeurs sont effectivement changées.

**Comment by fxprunayre** [comment]
Même pb que #110 . Problème de déploiement. La version debug marche bien http://metawal.spacebel.be/geonetwork/srv/fre/admin.console?debug#/organization/users

Testé sur: plateforme démo / Chrome & FF

**Comment by vbombaerts** [comment]
Fonctionne au poil !
