### ISSUE TITLE
Fiche descriptive : rassembler "Contacts" et "Contacts pour les métadonnées"

### ISSUE THREAD

**Issue by metawal** [SPW-DIG/metawal-core-geonetwork#107]
Voir screenshot :
![screenshot8](https://f.cloud.github.com/assets/6093485/1664127/5cf289f0-5c22-11e3-949f-88b055b10bc9.jpg)

**Comment by fxprunayre** [comment]
A priori non, le nom "point de contact" correspond au rôle.
