### ISSUE TITLE
Fiche descriptive : liens sur fond orange peu clairs

### ISSUE THREAD

**Issue by metawal** [SPW-DIG/metawal-core-geonetwork#108]
Voir screenshot :
![screenshot10](https://f.cloud.github.com/assets/6093485/1664286/c83ac5cc-5c24-11e3-9438-7f853e762b7d.jpg)

Il faudrait mieux labelliser ces champs. Par exemple : Voir la donnée, Télécharger la donnée, Service web, Métadonnée des services associées, etc.

**Comment by fxprunayre** [comment]
A préciser dans les discussions sur l'ergonomie (ou discussion sur le WP profil).

**Comment by fxprunayre** [comment]
Fait en v4.
