### ISSUE TITLE
Admin / Ajouter transfert de privilèges

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#110]

**Comment by fxprunayre** [comment]
Sur réouverture d'un ticket, ce pourrait être bien de préciser la raison, sur quel environnement a été fait le test, ...

De mon côté:
- en local : ok
- en démo : 
  - http://metawal.spacebel.be/geonetwork/srv/fre/admin.console? nok
  - http://metawal.spacebel.be/geonetwork/srv/fre/admin.console?debug#/tools ok en mode debug

Il doit donc y a voir un pb de build au déploiement ?

**Comment by fxprunayre** [comment]
La version minifié sur le serveur de démo n'est pas la bonne http://metawal.spacebel.be/geonetwork/catalog/lib/gn_admin.min.js . Y'a t-il eu pb de build ? J'ai mis la version minifiée (https://github.com/spacebelGIS/metawal-core-geonetwork/commit/8d389cba381381202e78c4643422e467fef40923) mais nous ne devrions pas.

**Comment by davinciagf** [comment]
Non le build était réalisé avec succès à chaque fois.

**Comment by vbombaerts** [comment]
Le transfert de privilèges ne se fait plus que d'un utilisateur à l'autre. La possibilité de transférer les privilèges en fonction de la fiche de métadonnée n'est plus possible (ou je ne l'ai pas trouvé). Cette fonction est nécessaire car on a régulièrement des éditeurs qui éditent des fiches pour le compte d'autres qui n'ont pas le temps de le faire. La propriété de la fiche est ensuite transférée, mais pas pour l'entièreté des fiches.
cf. fonction de Metawal 2
![image 679](https://f.cloud.github.com/assets/6093597/1889074/eedb1056-7a15-11e3-9e79-19b18c4a5317.png)

**Comment by vbombaerts** [comment]
Sorry, j'avais pas vu que la fonction existe toujours 
![image 684](https://f.cloud.github.com/assets/6093597/1889391/ba4dbfa0-7a1a-11e3-91e5-c6ab7532ae6a.png)
