### ISSUE TITLE
Ajouter lien vers le wiki et vers l'aide générale de geonetwork

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#112]
Il me semble qu'il serait pertinent d'avoir ces deux liens dans le chapeau.
Ce n'était pas possible dans l'ancien metawal et on s'était dit, me semble t il, qu'on le ferait dans celui-ci.

**Comment by fxprunayre** [comment]
A préciser:
- Quel est le lien du wiki ?
- pour GN: geonetwork-opensource.org/manuals/trunk/fra/users/index.html
- a quel endroit sont mis les liens ?

**Comment by vbombaerts** [comment]
Le contenu du wiki a été reversé dans l'aide. Il ne semble pas pertinent de mettre un lien vers l'aide GN
