### ISSUE TITLE
Renommer 'mes métadonnées'

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#113]
'Mes métadonnées' semble renvoyer les métadonnées du/des groupes auxquels j'appartiens, et non mes métadonnées à moi. Est-ce bien le cas?
Si oui et que cela est le comportement attendu, ne faudrait-il pas renommer 'Mes métadonnées' en 'Les métadonnées de mon groupe'? Et peut-être ajouter un 'vrai' 'Mes métadonnées'?
Si non, faire en conséquence.

**Comment by vbombaerts** [comment]
Dans Metawal 2 "Mes métadonnées" fait référence aux métadonnées pour lesquelles tu as un droit d'édition. Dans Metawal 3, je ne vois pas à quoi elles se réfèrent. Si c'est le même comportement que dans Metawal 2, et donc lié à l'édition, il me semblerait logique que l'entrée soit liée à la rubrique "encodage"

**Comment by fxprunayre** [comment]
"Mes métadonnées" dans GeoNetwork correspond aux fiches de l'utilisateur c'est donc différent de metawal 2.
Correction du nom du critère de recherche.
