### ISSUE TITLE
Sign out => anglais

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#114]
Se déconnecter fait passer toute l'interface en anglais. Elle devrait rester dans la langue (ou pour nous être en Français).

**Comment by fxprunayre** [comment]
Non reproductible en local et en test.

Test fait:
- http://metawal.spacebel.be/geonetwork/srv/eng/search?
- connexion
- sign out
- = la page est en anglais

Testé sous Chrome et FF.

@davinciagf , je te laisse tester sur la plateforme de test (après redéploiement) et passer en validation.

**Comment by davinciagf** [comment]
Non reproduit sur l'env. de test
