### ISSUE TITLE
Activer la gestion de l'état => brouillon

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#115]
L'activation de la gestion de l'état (actions, autres actions) ne donne plus d'erreur, mais elle indique alors que l'état est passé à brouillon, même quand on le fait plusieurs fois.
Comment désactiver? Comment passer aux autres stades? Je pensais que c'était là.

**Comment by fxprunayre** [comment]
Cf. 
- https://github.com/geonetwork/core-geonetwork/issues/185
- http://geonetwork-opensource.org/manuals/trunk/fra/users/editor/metadata_status/index.html

1) Par défaut, il n'y a pas d'état. 
2) Activer = passe à l'état brouillon
3) Modification via le menu > Action > Autres actions > Changer l'état

Ce sera vu plus en détail dans le WP sur le workflow. Je ferme le ticket.

**Comment by vbombaerts** [comment]
L'activation de la gestion de l'état sur une fiche pour laquelle j'ai des droits d'édition mais dont je ne suis pas propriétaire renvoie une erreur. Il faudrait envoyer un message un peu plus user-friendly ou désactiver l'option d'activation d'état dans les actions.
Après fermeture de la fenêtre d'erreur, l'interface est toute chamboulée.
![image 645](https://f.cloud.github.com/assets/6093597/1791538/7d349a8a-698f-11e3-85b2-76dd0cade402.png)
![image 646](https://f.cloud.github.com/assets/6093597/1791543/8b036a24-698f-11e3-808e-96b8b9ef9a9a.png)

**Comment by fxprunayre** [comment]
Pour pouvoir reproduire convenablement le use case, il faudrait a minima : le numéro de la fiche et l'utilsateur utilisé. Merci.
