### ISSUE TITLE
console admin / gérer les utilisateurs - Enregistrer

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#116]
Ce bouton ne sert manifestement pas à enregistrer !!
Si j'ajoute une info de l'utilisateur (adresse par exemple) puis que je passe directement à un autre utilisateur, quand je reviens sur le premier l'adresse apparait.
Si je change l'adresse, que je clique sur enregistrer, la fiche utilisateur se ferme sans enregistrer les modifications.
Plus fort : si je change des infos utilisateurs, que je passe à un autre utilisateur, que je reviens sur l'utilisateur les infos nouvelles apparaissent. Quand je clique sur enregistrer, la fiche se ferme et les nouvelles infos ont disparu !!

**Comment by fxprunayre** [comment]
En effet, coquille lors du report de correction avec un merge depuis GeoNetwork. 

Pour information, il nous faudra minimiser les modifications sur la partie admin en Janvier (ie. correction des pbs bloquants uniquement comme celui ci) car il y a de nombreuses améliorations côté GN. Par ailleurs, nous sommes en train de mettre un framework de test automatique de l'interface (http://www.youtube.com/watch?v=eh9Plb817YE) - en commançant par l'admin. A planifier un merge GeoNetwork suite au déploiement en production (courant février).
