### ISSUE TITLE
Résultats - incohérence des liens de visualisation des données

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#117]
Le problème concerne les liens mentionnant les services de visualisation des données.
- Dans la vue "vignettes", ils sont derrière une petite icone carte sous la vignette et s'ouvrent dans un nouvel onglet.
  ![image 632](https://f.cloud.github.com/assets/6093597/1782465/37a899a8-68ae-11e3-99cb-23f376ae14ee.png)
- Dans la vue "résumé", ils sont derrière les "liens" et font atterrir sur la page de définition du service
  ![image 633](https://f.cloud.github.com/assets/6093597/1782488/8b5d3bd0-68ae-11e3-89a7-1d8c360cbe56.png)
- Quand on sélectionne une ou plusieurs fiches et qu'on choisit d'ajouter les couches de la sélection à la carte, il ne se passe rien (de visible) 
  ![image 634](https://f.cloud.github.com/assets/6093597/1782495/d1f6bbc0-68ae-11e3-8430-27b047e61310.png)

Il serait utile d'harmoniser les comportements. Proposition : 
- vue "vignettes" : rien ne change
- vue "résumé" : rien ne change pour les liens, mais on ajoute l'icone carte avec le même comportement que dans la vue vignettes
- action sur la sélection : ajouter tous les services à WalOnMap à travers un "AGSDynURL"

--> Voir avec une coordination plus poussée avec WalOnMap

**Comment by fxprunayre** [comment]
> vue "vignettes" : rien ne change

Ok

> vue "résumé" : rien ne change pour les liens, mais on ajoute l'icone carte avec le même comportement que dans la vue vignettes

Fait.

> action sur la sélection : ajouter tous les services à WalOnMap à travers un "AGSDynURL"

Evolutions (demande un service spécifique côté serveur). Création d'un autre ticket si besoin. Valider si possible dans Walonmap la méthode pour passer n couples couche/url.
