### ISSUE TITLE
Alignement des titres dans les dernières publications

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#118]
Problème d'alignement du titre dans les dernières publications. C'est pas joli.
![image 635](https://f.cloud.github.com/assets/6093597/1782720/cc8a3fb2-68b4-11e3-9134-1c7dee67e065.png)

**Comment by fxprunayre** [comment]
GN fix https://github.com/geonetwork/core-geonetwork/commit/2ee6c4a2eec037e3fdf1e3f672b2747f818ea7c1

**Comment by vbombaerts** [comment]
Nickel. Merci
