### ISSUE TITLE
Interface : Boite de recherche générale

### ISSUE THREAD

**Issue by FBELSSPW** [SPW-DIG/metawal-core-geonetwork#12]
La boite de recherche générale n'est pas clairement identifiable. Il faudrait la séparer des autres éléments

**Comment by fxprunayre** [comment]
Cf https://github.com/spacebelGIS/metawal-core-geonetwork/wiki/Ergonomie-et-design-des-interfaces-Metawal

**Comment by fxprunayre** [comment]
Fait en v4
