### ISSUE TITLE
Charte graphique - Favicon

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#121]
En l'absence de stratégie de communication spécifique, le coq wallon doit être utilisé comme favicon du site.
Ce favicon est téléchargeable sur http://chartegraphique.wallonie.be/

**Comment by fxprunayre** [comment]
option 1: A priori configurable depuis l'admin > logo

option 2: Sinon, nous devons également pouvoir supprimer favicon et le serveur apache devrait s'occuper de fournir la favicon à utiliser (ca dépend de la conf sur l'infra SPW).

@davinciagf Je te laisse tester sur la plateforme de test SPW

**Comment by fxprunayre** [comment]
Option 2 a priori possible via http://geoportail.wallonie.be/favicon.ico si on a http://metawal.wallonie.be/favicon.ico

**Comment by fxprunayre** [comment]
Copier http://geoportail.wallonie.be/favicon.ico dans le répertoire racine du apache du server de test et metawal.wallonie.be.

**Comment by vbombaerts** [comment]
Favicon OK dans la barre d'adresse mais pas de favicon dans les onglets. Même problème sur le géoportail.
