### ISSUE TITLE
Interface de recherche - résultats - nombre de fiches sélectionnées

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#122]
Je sélectionne des fiches. Ensuite je retourne à la page d'accueil et effectue une nouvelle recherche. Le nombre de fiches sélectionnées ne change pas alors que je n'en n'ai plus aucune qui est sélectionnée.
![image 641](https://f.cloud.github.com/assets/6093597/1783087/dc91f7bc-68bc-11e3-887a-dbf83ddd4bf4.png)

**Comment by fxprunayre** [comment]
Non, la sélection est persistante à travers les recherches, les résultats de n recherches peuvent être combinés. Si il y a des éléments sélectionnés dans les recherches précédentes, la case à cocher sera activée. Pour vider, la sélection, cliquer sur sélection > aucun
