### ISSUE TITLE
Fonctionnalité disparue : afficher la sélection

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#123]
Dans Metawal 2, quand on sélectionne des fiches on a la possibilité de n'afficher que celles qui sont sélectionnées. Cette fonctionnalité n'existe plus dans Metawal 3. Est-il possible de la rétablir ?
![image 642](https://f.cloud.github.com/assets/6093597/1783098/246758e8-68bd-11e3-9c75-39ce6376185e.png)

**Comment by fxprunayre** [comment]
> Est-il possible de la rétablir ?

Non prévu. A discuter pour les versions à venir.

**Comment by vbombaerts** [comment]
Lié à la notion de panier. En discussion à l'IFREMER.

**Comment by fxprunayre** [comment]
cf #256 

Panier exemple de sextant http://sextant.ifremer.fr/geonetwork/srv/fre/catalog.search
