### ISSUE TITLE
console admin / paramètres / paramètre répété + problème d'alignement

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#125]
Voir screenshots

![image 650](https://f.cloud.github.com/assets/6093597/1792106/2f1aacb8-6999-11e3-9af7-3871db018d48.png)

![image 651](https://f.cloud.github.com/assets/6093597/1792119/6b82eb16-6999-11e3-8a46-0dc1c7656714.png)

**Comment by fxprunayre** [comment]
Corrigé dans GN/develop et donc metawal-4.x. On ferme ?

**Comment by vbombaerts** [comment]
pas résolu en env de test, mais pas critique donc je laisse fermé
![2016-02-02 11_08_41-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/12746223/cd97a240-c99d-11e5-900a-c5f0bbcbaf99.png)
![2016-02-02 11_08_56-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/12746224/cda6f77c-c99d-11e5-93a6-4ce769d5205a.png)
![2016-02-02 11_09_23-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/12746227/cf2d3f84-c99d-11e5-92d5-edd03a7717c3.png)
