### ISSUE TITLE
console admin / paramètres / erreur quand on modifie les paramètres liés à l'index

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#126]
Voir screenshot

![image 652](https://f.cloud.github.com/assets/6093597/1792127/994e3532-6999-11e3-96d0-0809931488bf.png)

**Comment by fxprunayre** [comment]
Non bloquant pour l'application et comme indiqué les paramètres sont bien sauvés.

**Comment by fxprunayre** [comment]
Corrigé dans GN/develop et donc metawal-4.x. On ferme ?
