### ISSUE TITLE
Interface d'édition / supprimer une ressource associée ne fonctionne pas

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#128]
Dans les liens rapides à droite de l'interface d'édition, cliquer sur supprimer (une ressource associée) n'a aucun effet, même après avoir rechargé les ressources associées ou sauvé la fiche de métadonnées

![image 653](https://f.cloud.github.com/assets/6093597/1851047/63413192-76e1-11e3-9de5-ecf99e8a6c59.png)

**Comment by fxprunayre** [comment]
A retester

**Comment by vbombaerts** [comment]
Pas réussi à répliquer.
