### ISSUE TITLE
Interface d'édition / ressource associée / les accents ne passent pas

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#129]
Un site web avec caractère accentué, encodé via le "quick link" ressource associée --> l'accent ne passe pas.

![image 654](https://f.cloud.github.com/assets/6093597/1851078/27482abe-76e2-11e3-8629-632ac2ba0953.png)
![image 655](https://f.cloud.github.com/assets/6093597/1851081/3c3122fa-76e2-11e3-9b6f-576c717cdd01.png)

**Comment by fxprunayre** [comment]
Pb encoding JBoss probablement à tester.

**Comment by davinciagf** [comment]
La création d'une nouvelle MTD inclus la prise en charge des accents

**Comment by vbombaerts** [comment]
Ne fonctionne toujours pas.
OK quand on sélectionne un service en faisant une recherche dans le catalogue. KO quand on encode directement l'URL d'une ressource associée.
Quand on va chercher un service, si les layers comportent des accents ils ne passent pas.
![image 687](https://f.cloud.github.com/assets/6093597/1910222/9d149504-7d11-11e3-85c0-ce254ecd68d9.png)
![image 691](https://f.cloud.github.com/assets/6093597/1910224/9fbf0ffa-7d11-11e3-83ff-5e8e98aacade.png)
![image 688](https://f.cloud.github.com/assets/6093597/1910227/a51a85a6-7d11-11e3-9d55-08fbf5dcb718.png)
![image 692](https://f.cloud.github.com/assets/6093597/1910228/a7562528-7d11-11e3-8c64-87edaf0189dc.png)

**Comment by fxprunayre** [comment]
GetCapabilities ok : http://geoservices.wallonie.be/arcgis/services/SOL_SOUS_SOL/CARTE_GEOLOGIQUE_SIMPLE/MapServer/wmsServer?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0

GetCapabilities via proxy GN serveur de démo : nok

http://metawal.spacebel.be/geonetwork/proxy?url=http%3A%2F%2Fgeoservices.wallonie.be%2Farcgis%2Fservices%2FSOL_SOUS_SOL%2FCARTE_GEOLOGIQUE_SIMPLE%2FMapServer%2FwmsServer%3FSERVICE%3DWMS%26REQUEST%3DGetCapabilities%26VERSION%3D1.3.0

GetCapabilities via proxy GN (serveur local): ok

http://localhost:8080/geonetwork/proxy?url=http%3A%2F%2Fgeoservices.wallonie.be%2Farcgis%2Fservices%2FSOL_SOUS_SOL%2FCARTE_GEOLOGIQUE_SIMPLE%2FMapServer%2FwmsServer%3FSERVICE%3DWMS%26REQUEST%3DGetCapabilities%26VERSION%3D1.3.0

**Comment by fxprunayre** [comment]
En l'occurence lors de la sélection d'une couche, seul le nom de la couche est ajouté à la fiche et il comporte rarement des accents (dans l'exemple, 0, 1, 2, 3). 

Je ne reproduis toujours pas.

**Comment by vbombaerts** [comment]
Pas réussi à reproduire.
