### ISSUE TITLE
Fenêtre de connexion : "mot de passé oublié" et "pas encore inscrit ?"

### ISSUE THREAD

**Issue by metawal** [SPW-DIG/metawal-core-geonetwork#13]
Dans le fenêtre de connexion, il faudrait ajouter deux liens :
- que faire si on a oublié son mot de passe ? (équivalent du lien "Mot de passe oublié ?" sur le Géoportail)
- que faire si on n'a pas de mot de passe ? (équivalent du lien "Pas encore inscrit ?" sur le Géoportail)

**Comment by davinciagf** [comment]
Introduction d'un texte expliquant la procédure de récupération de son mot de passe en cas d'oubli (ref géoportail) et désactivation de la fonctionnalité de récupération.

**Comment by davinciagf** [comment]
doublon (#132)
