### ISSUE TITLE
Harmonisation de la définition des MD de géodonnée, de géoservice et d'application cartographique

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#130]
Plusieurs endroits font référence à ces trois catégories, mais elles ne sont pas identifiées correctement.
- dans la recherche - Type de ressource (on a uniquement Géodonnées et Géoservices. Il faut ajouter Applications géographiques)
  ![image 657](https://f.cloud.github.com/assets/6093597/1858741/2b253e94-7794-11e3-99f7-975730718a9e.png)
- dans les facettes : type de ressource : dans les services on retrouve à la fois de services et des applications ; le type application n'apparait pas dans les choix pour la valeur de la facette
  ![image 658](https://f.cloud.github.com/assets/6093597/1858742/3bda2dd0-7794-11e3-88a6-0a03165a4eba.png)
- dans l'interface d'admin / statistiques : on retrouve les 3 mais le nombre de fiches ne correspond pas.
  ![image 659](https://f.cloud.github.com/assets/6093597/1858747/47caab7e-7794-11e3-9a77-adc460422abf.png)
  ![image 660](https://f.cloud.github.com/assets/6093597/1858748/4bee6d62-7794-11e3-80bb-66462ac51e44.png)

Actuellement, les fiches "v2" sont différenciables sur base de la valeur du hierarchylevel et/ou du hierarchylevelname
- géodonnée : hyerarchylevel = dataset
- géoservice : hyerarchylevelname = Service (ou service)
- application cartogrpahique : hyerarchylevelname = Application (ou application)

Lors du passage à la v3.0, les nouvelles conventions seront d'usage :
- géodonnée : hyerarchylevel = dataset
- géoservice : hyerarchylevel = service
- application cartogrpahique : hyerarchylevel = application

La migration à la v3 nécessitera-t-elle de modifier la valeur du hierarchylevel des fiches d'application ?

**Comment by fxprunayre** [comment]
Ajouter migration hierarchylevelname > hyerarchylevel application
https://github.com/spacebelGIS/metawal-core-geonetwork/blob/metawal-develop/web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139.rw/process/metawal-schema-updates.xsl#L52

**Comment by fxprunayre** [comment]
> La migration à la v3 nécessitera-t-elle de modifier la valeur du hierarchylevel des fiches d'application ?

Oui. Fait dans 4ee500f. Migration de base à retester avec lancement du processus https://github.com/spacebelGIS/metawal-core-geonetwork/blob/metawal-develop/web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139.rw/process/metawal-schema-updates.xsl

**Comment by vbombaerts** [comment]
Le critère de recherche "Applications" renvoie bien les applications.
Le critère de recherche "Géoservices" renvoie les services ET les applications. Les applications sont actuellement basées sur un template "ISO 19119" ce qui est peut-être à l'origine de la confusion.

**Comment by fxprunayre** [comment]
A vérifier après migration.

**Comment by vbombaerts** [comment]
Vérification après migration : OK
![2016-02-02 11_04_41-](https://cloud.githubusercontent.com/assets/6093597/12746016/dbe3c5a0-c99c-11e5-840b-1248c36dc5a1.png)
![2016-02-02 11_03_47-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/12746018/de014718-c99c-11e5-8fa5-4a93864c7103.png)
![2016-02-02 11_04_08-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/12746020/df7a210a-c99c-11e5-9cf7-eaeb1579a4e1.png)
