### ISSUE TITLE
console admin / gestion des annuaires / impossible d'ajouter des annuaires

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#133]
J'ai copié collé un fragment de xml et j'ai obtenu le message "Echec"
![image 662](https://f.cloud.github.com/assets/6093597/1859936/91ae9c34-77ab-11e3-91a5-ab0c3f25d255.png)

**Comment by fxprunayre** [comment]
http://geonetwork-opensource.org/manuals/trunk/fra/users/admin/contacts/index.html

**Comment by fxprunayre** [comment]
Un exemple de contact pour test https://github.com/spacebelGIS/metawal-core-geonetwork/commit/f2f5df94ab9bc5144a30be2f2792616ba302441b

C'est fonctionnel. A tester.

Les modifs faites pour gérer les subtemplates pour un élément étendu par un profil ISO ne seront pas reportées dans GeoNetwork car le gestion des subtemplates a changé - indexation & lien avec le nouvel éditeur différents. A étudier dans le travail à venir sur la prochaine version de l'ISO.
