### ISSUE TITLE
Supprimer des fiches de métadonnées ne recharge pas la page des résultats

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#135]
Après suppression de fiches de métadonnées par lot (sélectionner plusieurs fiches, autres actions, supprimer), la page de résultats ne se recharge pas. Les fiches supprimées sont toujours listées et il est possible d'interagir avec, par exemple choisir Actions/éditer --> évidemment après il y a un message d'erreur.

==> quand on supprimer, recharger la page des résultats pour faire disparaître les fiches supprimées.

**Comment by fxprunayre** [comment]
Désactiver mode Lucene NRT
