### ISSUE TITLE
Fenêtre d'association de ressources - perte d'espace

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#136]
Grand espace blanc inutile dans le bas de la fenêtre pour trouver une ressource à associer
![image 666](https://f.cloud.github.com/assets/6093597/1887303/522b5114-79fa-11e3-858e-9e31b36e6021.png)

**Comment by vbombaerts** [comment]
Nouvelle version de cet outil dans la nouvelle interface. Captures d'écran suivront

**Comment by fxprunayre** [comment]
Cf. capture d'écran https://github.com/geonetwork/core-geonetwork/wiki/Refactoring-editor#relation-panel quand elles seront faites.
