### ISSUE TITLE
Ressources associées / Associer un jeu de données

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#138]
Erreur quand on veut associer un jeu de données. Les autres associations fonctionnent.
![image 668](https://f.cloud.github.com/assets/6093597/1887504/aa7de6de-79fe-11e3-9403-6ac469abcae2.png)
![image 667](https://f.cloud.github.com/assets/6093597/1887506/acff2508-79fe-11e3-9ebb-871295d9fbc6.png)

**Comment by fxprunayre** [comment]
Pour ajouter un jeux de données, il faut être dans une fiche de service.

**Comment by vbombaerts** [comment]
A l'avenir, il faudra peut-être griser la ligne pour montrer que la fonction n'est pas accessible sur un template de données.
