### ISSUE TITLE
Consultation / vue avancée / onglets sans information

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#139]
Une mention de type "Pas d'information disponible" ou "Non renseigné" serait bienvenue pour les onglets n'ayant pas de contenu, histoire qu'on ne pense pas qu'il s'agit d'un bug.
![image 676](https://f.cloud.github.com/assets/6093597/1888573/4c0edb74-7a0f-11e3-8576-42317e0ea060.png)

**Comment by fxprunayre** [comment]
Fait dans GN3. Je ferme

**Comment by davinciagf** [comment]
En consultation, le système ne reprend que les élements et sections complétés. 
Nok en test est-il lié au problème d'affichage des vues en consultation #304?

**Comment by vbombaerts** [comment]
On va dire que oui...
(je ne me rappelle plus, c'était sur la version d'il y a 3 mois)

**Comment by davinciagf** [comment]
Il faudra néanmoins avoir un look and feel se rapprochant de celui du géoportail pour présenter les MTD

**Comment by vbombaerts** [comment]
oui. Mais je ne pense pas que ca rentre dans le cadre de ce ticket.
