### ISSUE TITLE
Bouton "actions" avec menu déroulant

### ISSUE THREAD

**Issue by geologiewallonie** [SPW-DIG/metawal-core-geonetwork#14]
Le terme actions qui s'affiche après une donnée n'est pas parlant. Il faut privilégier un bouton avec une flèche vers le bas annonçant le menu déroulant.

**Comment by fxprunayre** [comment]
Le menu action est accessible à plusieurs endroits:
- actions à côté du titre
- clic droit sur une fiche
- toolbar de la fiche en consultation

**Comment by fxprunayre** [comment]
Fait en v4.
