### ISSUE TITLE
Mes métadonnées et type d'affichage des résultats

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#140]
Quel que soit le choix de l'affichage de la liste des résultats (compact, vignettes ou complet), cliquer sur mes métadonnées renvoie les résultats au format complet et ouvre les critères avancés de recherche. Il faudrait garder l'interface telle quelle et juste changer les résultats affichés.
![image 680](https://f.cloud.github.com/assets/6093597/1889191/c87afd34-7a17-11e3-9179-6e4f500dbe94.png)
![image 681](https://f.cloud.github.com/assets/6093597/1889200/cba78144-7a17-11e3-8406-1bcea9bca889.png)

**Comment by fxprunayre** [comment]
Evolution : ajouter la capacité à conserver la dernière vue activée dans le cookie du navigateur.
