### ISSUE TITLE
Interface admin/utilisateurs/emplacement du bouton "créer..."

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#147]
Le bouton créer un utilisateur devrait être relocalisé en haut de la liste (alternativement en haut et en bas). Il n'est pas pratique en bas : il faut scroller jusqu'en bas pour le trouver, puis rescroller jusqu'en haut pour remplir les infos nouvel utilisateur.

**Comment by fxprunayre** [comment]
See https://github.com/geonetwork/core-geonetwork/issues/404

**Comment by fxprunayre** [comment]
Corrigé par #148. On ferme ?
