### ISSUE TITLE
Interface / adaptation du design (header, footer + un peu de CSS)

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#148]
Les boites empiètent sur le pied de page. Ex : liste des utilisateurs.

![image 708](https://f.cloud.github.com/assets/6093597/2274436/5f605a7c-9f1c-11e3-92f3-1cc40e9c1524.png)

![image 709](https://f.cloud.github.com/assets/6093597/2274452/8d4bc2e6-9f1c-11e3-86c2-bc7b531b8f61.png)

**Comment by fxprunayre** [comment]
Cf. https://github.com/geonetwork/core-geonetwork/pull/627 "Client side paging is added to harvesters, groups, users, thesaurus, categories to avoid long list and having the create action at the bottom of the list."

![Alt text](https://cloud.githubusercontent.com/assets/1701393/4116538/5527ddb6-3286-11e4-9d73-02bbe59e4785.png)

**Comment by vbombaerts** [comment]
Footer absent des interfaces d'édition et d'admin (et donc forcément problème résolu !)
Si l'aide pour l'édition est accessible par ailleurs, ça ne me tracasse pas plus que ça ;-)
cf #307
