### ISSUE TITLE
Améliorer la gestion des ressources en ligne sans protocole

### ISSUE THREAD

**Issue by metawaltest** [SPW-DIG/metawal-core-geonetwork#15]
Pas de lien direct vers les applications sur la fiche de métadonnée

**Comment by mawibrin** [comment]
En fait est dans la vue dite par défaut (qui n'est pas là par défaut...), dans distri => très loin et pas visible
Devrait se trouver dans la vue simple (qui est par défaut)!
Dans la vue simple on trouve un lien vers la MD de l'application. Les gens cherchent plus un accès direct sans doute => mettre les deux là.

**Comment by fxprunayre** [comment]
Possible de fournir un uuid de fiche ?

**Comment by metawaltest** [comment]
Identifiant unique 38c2a87e-d38a-4359-9899-9d4a6b9f0c2a

**Comment by fxprunayre** [comment]
Le lien ne s'affiche pas dans la vue simplifié car il n'y a pas de protocol

```
<gmd:onLine>
<gmd:CI_OnlineResource>
<gmd:linkage>
<gmd:URL>http://cartopro3.wallonie.be/CIGALE/viewer.htm?APPNAME=CNSW</gmd:URL>
</gmd:linkage>
<gmd:name>
<gco:CharacterString>Application - La Carte Numérique des Sols de Wallonie (CIGALE)</gco:CharacterString>
</gmd:name>
<gmd:description>
<gco:CharacterString>Application CIGALE internet dédiée à la consultation de la Carte Numérique des Sols de Wallonie (CNSW)</gco:CharacterString>
</gmd:description>
</gmd:CI_OnlineResource>
</gmd:onLine>
```

A traiter comme des liens web.

A faire pour #153

**Comment by fxprunayre** [comment]
![image](https://cloud.githubusercontent.com/assets/1701393/7611659/1dad4890-f986-11e4-9f4a-b21130e8811a.png)

Ca semble ok en v4.

http://metawal4.test.wallonie.be/geonetwork/srv/eng/catalog.search#/metadata/38c2a87e-d38a-4359-9899-9d4a6b9f0c2a

**Comment by fxprunayre** [comment]
Cf. #17
