### ISSUE TITLE
Créer une page de test pour la garde DTIC

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#151]
Metawal est placé dans l'environnement DTIC. Les administrateurs au DTIC ont besoin de pouvoir appeler une page de test, accessible sans login pour valider que Metawal fonctionne bien. Il faut deux versions de cette page : une page qui renvoie uniquement "OK" et une page verbeuse.

**Comment by fxprunayre** [comment]
Page de surveillance :
- http://localhost:8080/geonetwork/criticalhealthcheck
  - HTTP Status code = 200 : Application ok
  - HTTP Status code != 200 (ie. 500) : Application ko (relancer l'application)

![image](https://cloud.githubusercontent.com/assets/1701393/2535478/e8054742-b58e-11e3-9f00-9e9ed639bb22.png)

Autres pages de surveillance :
- http://localhost:8080/geonetwork/monitor/healthcheck : Informations détaillées sur les principaux services de l'application
- http://localhost:8080/geonetwork/monitor/metrics?pretty=true : Métriques détaillées sur la JVM, les services internes

Pour accèder aux services de validation :
- Option 1 : utiliser un compte (eg. créer un compte "monitor") de l'application et réaliser une basic authentification (BA) HTTP
- Option 2 : ouvrir ces services en accès public (pas forcément recommandé)

Exemple de connexion utilisant wget avec BA :

```
wget --http-user=monitor --http-password=aaaaaa http://localhost:8080/geonetwork/criticalhealthcheck
--2014-03-27 10:19:33--  http://localhost:8080/geonetwork/criticalhealthcheck
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... 200 OK
Length: 191 [application/json]
Saving to: ‘criticalhealthcheck’

100%[================================>] 191         --.-K/s   in 0s      

2014-03-27 10:19:33 (3,93 MB/s) - ‘criticalhealthcheck’ saved [191/191]

```

**Comment by vbombaerts** [comment]
Ne correspond pas aux exigences du DTIC.

**Comment by fxprunayre** [comment]
Changement d'accès dans https://github.com/spacebelGIS/metawal-core-geonetwork/blob/master/web/src/main/webapp/WEB-INF/config-security-mapping.xml#L14

**Comment by fxprunayre** [comment]
Donc voilà, un service "conforme aux exigences du DTIC"

http://localhost:8080/geonetwork/healthcheckfordummies
- HTTP Status code = 200 (dans tous les cas)
- Retourne le texte "OK" si tous les tests de http://localhost:8080/geonetwork/criticalhealthcheck sont OK
- Retourne le texte "KO" si ce n'est pas le cas.

A déployer et tester.

**Comment by vbombaerts** [comment]
Validé par EFO
