### ISSUE TITLE
Annuaire - impossible de gérer les privilèges

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#152]
Quand je duplique une entrée de l'annuaire je peux choisir à quel groupe je l'assigne. Par contre impossible de changer les privilèges après coup. (il ne se passe rien quand je clique sur le bouton)
![image 716](https://f.cloud.github.com/assets/6093597/2523916/738e9ece-b4d8-11e3-8a84-43478fe463c0.png)

**Comment by fxprunayre** [comment]
Ca ne doit pas empêcher leur utilisation dans l'éditeur ?

**Comment by vbombaerts** [comment]
Si, l'annuaire n'est disponible qu'en fonction des privilèges (instance en valid)

**Comment by fxprunayre** [comment]
A redéployer.
