### ISSUE TITLE
ISO19115-1:2014

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#153]
### Question
- Quelles suggestions migrer ?
  cf. https://github.com/geonetwork/core-geonetwork/tree/develop/schemas/iso19139/src/main/plugin/iso19139/process
### Record migration

Méthode de migration:
- Sauvegarder la base !
- Se connecter en Admin
- Rechercher toutes les fiches à traiter (eg. schema iso19139.rw) http://localhost:8080/geonetwork/srv/eng/q?_schema=iso19139.rw&_isTemplate=y or n&summaryOnly=true
- Selectionner tout http://localhost:8080/geonetwork/srv/eng/metadata.select?selected=add-all
- Exécuter http://localhost:8080/geonetwork/srv/eng/md.processing.batch?process=rwto19139
- Exécuter
  http://localhost:8080/geonetwork/srv/eng/md.processing.batch?process=19139to19115-3
- Progress report http://localhost:8080/geonetwork/srv/eng/md.processing.batch.report
- Attendre la fin
- TODO: Traiter les fiches iso19139
- En base de donnée

```
UPDATE metadata SET schemaid = 'iso19115-3' WHERE schemaid = 'iso19139.rw';
```
- Vérifier la migration

```
select * from metadata where data like '%rw:%'
```
- Dans l'administration du catalogue, réindexer le contenu.
### Schematron for dataset, service, application
- Règles ISO - en cours https://github.com/ISO-TC211/XML/pull/47
- Règles SPW
## Reference documents:
- Schema plugin documentation http://geonetwork-opensource.org/manuals/trunk/eng/developer/schemaPlugins/index.html
- Schema plugin repository https://github.com/geonetwork/schema-plugins/tree/develop/iso19115-3
- ISO19115-1:2014 http://www.iso.org/iso/catalogue_detail.htm?csnumber=53798
- Related GeoNetwork work:
  - The schema plugin - See https://github.com/geonetwork/schema-plugins/tree/develop/iso19115-3
  - Add ISOPlugin interface to be able to customize basic type - See https://github.com/geonetwork/core-geonetwork/pull/746
  - Schematron using diagnostics - See https://github.com/geonetwork/core-geonetwork/issues/788 
  - More pluggable schema plugin - See https://github.com/geonetwork/core-geonetwork/wiki/Proposal:-Schema-plugin-improvement
  - CSW / Pluggable output schema - See https://github.com/geonetwork/core-geonetwork/pull/1280
- Related TC211 work:
  - https://github.com/ISO-TC211/XML/pull/47

**Comment by fxprunayre** [comment]
Problème du traitement à cause d'Oracle too many open cursors https://docs.oracle.com/cd/E40329_01/admin.1112/e27149/cursor.htm#OMADM5352

```

java.sql.SQLException: ORA-01000: maximum open cursors exceeded
ORA-01000: maximum open cursors exceeded

    oracle.jdbc.driver.SQLStateMapping.newSQLException(SQLStateMapping.java:70)
    oracle.jdbc.driver.DatabaseError.newSQLException(DatabaseError.java:133)
    oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:206)
    oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:455)
    oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:406)
    oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
    oracle.jdbc.driver.T4C8TTILob.receiveReply(T4C8TTILob.java:903)
    oracle.jdbc.driver.T4C8TTILob.getChunkSize(T4C8TTILob.
```

On ne peut pas augmenter côté Oracle a priori. Du coup traitement par lot, par année sauf pour 2014 et 2012 à faire par mois (misère !) de création via :
- recherche http://metawal.wallonie.be/geonetwork/srv/fre/q?fast=index&_createDate=2013*&_schema=iso19139.rw&_isTemplate=y%20or%20n&summaryOnly=true
- et ensuite, sélection, traitement.

**Comment by fxprunayre** [comment]
Migrer les annuaires ISO19139

**Comment by vbombaerts** [comment]
Thésaurus de mots-clé libres à ne pas écraser #290

**Comment by vbombaerts** [comment]
Qu'est-ce que je dois valider exactement sur ce ticket ?

**Comment by fxprunayre** [comment]
De mon point de vue on peut le considérer fermer maintenant étant donnée qu'on a une procédure de migration ok, un import/export, édition, consultation opérationnels. On aura d'autres tickets plus spécifiques pour traiter les nouveaux pb.

**Comment by vbombaerts** [comment]
Ca marche
