### ISSUE TITLE
Migration - URL des vignettes

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#154]
Dans la v3 de Metawal, je souhaite que les URL des vignettes soient encodées "en dur". C'est déjà le cas pour les fiches créées directement dans Metawal 3 (exemple Pléiades), mais pas pour celle importées de Metawal 2 (exemple : bords de routes en fauchage tardif). Est-il possible d'inclure cela dans le script de migration.
![image 718](https://cloud.githubusercontent.com/assets/6093597/2801228/94421ef2-cc7f-11e3-9d23-c116f9a6d839.png)

**Comment by fxprunayre** [comment]
Ajouter les URL complètes (eg. https://github.com/spacebelGIS/metawal-core-geonetwork/blob/metawal-develop/web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/set-thumbnail.xsl#L127) à la migration XSL https://github.com/spacebelGIS/metawal-core-geonetwork/blob/metawal-develop/web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139.rw/process/metawal-schema-updates.xsl

Dans la mise à jour:
- mettre les URL complète
- corriger les datetime
- supprimer les petites cf. #68 "A planifier, mise à jour en batch des fiches pour n'avoir plus qu'un aperçu ?"
- côté serveur, supprimer les fichiers dans le répertoire data

**Comment by fxprunayre** [comment]
A tester
Méthode de migration:
- Sauvegarder la base !
- Se connecter en Admin
- Rechercher toutes les fiches à traiter (eg. schema iso19139.rw) http://localhost:8080/geonetwork/srv/eng/q?_schema=iso19139.rw&_isTemplate=y or n&summaryOnly=true
- Selectionner tout http://localhost:8080/geonetwork/srv/eng/metadata.select?selected=add-all
- Exécuter http://localhost:8080/geonetwork/srv/eng/md.processing.batch?process=metawal-misc-fix
  - ou http://localhost:8080/geonetwork/srv/eng/md.processing.batch?process=metawal-misc-fix&prefix=http://metawal.spacebel.be/geonetwork/srv/fre/resources.get pour personnaliser le prefix de l'url
- Progress report http://localhost:8080/geonetwork/srv/eng/md.processing.batch.report
- Attendre la fin

**Comment by vbombaerts** [comment]
Les imagettes n'apparaissent pas. Leur adresse ne contient pas l'uuid de la fiche. Elles pointent par ailleurs sur metawal en prod (mais peut-être est-ce voulu ?). 

``` xml
<gmd:graphicOverview xmlns:srv="http://www.isotc211.org/2005/srv">
   <gmd:MD_BrowseGraphic>
        <gmd:fileName>
                <gco:CharacterString>http://metawal.wallonie.be/geonetwork/srv/fre/resources.get?uuid=&fname=Ahrem.png</gco:CharacterString>
        </gmd:fileName>
   </gmd:MD_BrowseGraphic>
</gmd:graphicOverview>
```

Les petites vignettes ont bien été supprimées. Je ne sais pas si c'est lié, mais la liste des résultats arrive bcp plus lentement (on voit les images qui mettent des plombes à arriver, comme au bon vieux temps). Je retesterai demain dans d'autres conditions. A suivre...

**Comment by fxprunayre** [comment]
Corrigé. Migration à réappliquer.

**Comment by vbombaerts** [comment]
Créer un listing des images trop lourdes

**Comment by vbombaerts** [comment]
Les vignettes sont présentes. Je ne ferme pas parce que je suis étonné que l'adresse des vignettes soit celle de metawal-prod et pas celle de metawal-test. Du coup, elles ne sont pas toutes récupérées (certaines ont été changées en prod, d'autres n'ont été créées qu'en test). 
Néanmoins, j'imagine que le script fera l'affaire en prod.
