### ISSUE TITLE
Vignette par défaut

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#155]
Dans Metawal 2, lorsqu'aucune vignette n'est chargée, une vignette par défaut "no preview" apparait. Ce n'est pas le cas dans Metawal 3. Est-il possible de rétablir cette fonction ?
Question liée : faut-il prévoir dans le modèle de saisie une vignette par défaut "no preview" qui serait supprimée automatiquement / à supprimer manuellement dès lors qu'une vignette est chargée par le rédacteur ?

Metawal 2
![image 720](https://cloud.githubusercontent.com/assets/6093597/2801377/4a697260-cc81-11e3-8bfa-67d36e156c77.png)

Metawal 3
![image 719](https://cloud.githubusercontent.com/assets/6093597/2801353/19057d4a-cc81-11e3-9abf-b1b918494d5d.png)

**Comment by vbombaerts** [comment]
Suite à la mise en valid de l'appli de ce 04/07, le problème n'est toujours pas résolu.

**Comment by fxprunayre** [comment]
Ca semble ok en prod non ? on ferme ?

**Comment by vbombaerts** [comment]
A centrer

**Comment by vbombaerts** [comment]
On va plus chipoter sur le centrage haut/bas... C'est bon comme ça.
