### ISSUE TITLE
Connexion - <Enter> = Se connecter

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#156]
Dans l'écran de login, peut-on faire en sorte qu'appuyer sur <Enter> déclenche l'action "Se connecter" plutôt qu'être obliger de cliquer sur "Se connecter"
![image 721](https://cloud.githubusercontent.com/assets/6093597/2828926/130523a0-cf9c-11e3-8ef0-150b0d96316f.png)

**Comment by davinciagf** [comment]
Sera mis en place à la prochaine version
