### ISSUE TITLE
Traduction des thématiques ISO

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#157]
En consultation, les thèmes ISO ne sont pas traduits en français. (en édition ils le sont)
![image 727](https://cloud.githubusercontent.com/assets/6093597/2944658/1de5bcb8-d9d7-11e3-8451-616f580c6705.png)

**Comment by fxprunayre** [comment]
Cf. https://github.com/geonetwork/core-geonetwork/issues/698

**Comment by fxprunayre** [comment]
Corrigé dans GN/stable-develop > GN/develop > metawal-4.x + cherry-pick dans metawal-develop
