### ISSUE TITLE
Choix des contraintes sur la ressource

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#158]
Dans le choix du type de contrainte, ne pas proposer les contraintes légales avec attribut RW.
![image 733](https://cloud.githubusercontent.com/assets/6093597/3012121/421cbad8-df35-11e3-8cfd-1e9d1509a622.png)

**Comment by fxprunayre** [comment]
On supprime du schéma XSD ? et on corrige les fiches qui l'utilisent ?

**Comment by fxprunayre** [comment]
A faire : Supprimer LIGNE 125 - 147 dans https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-develop/web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139.rw/schema/extensions/rwExtensions.xsd#L125.

Pour tester: relancer le catlaogue, recréer une fiche, la liste ne devrait plus le proposer.
