### ISSUE TITLE
Edition - Vue par défaut - Pas possible d'ajouter des thématiques ISO

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#159]
Quand j'édite une fiche, dans la vue par défaut, je ne peux pas ajouter ou supprimer des thématiques ISO, alors que c'est possible pour d'autres éléments. (pas de + ni de -)
Est-il possible de laisser obligatoirement une entrée et d'avoir la possibilité d'en ajouter ou d'en supprimer d'autres ?

![image 734](https://cloud.githubusercontent.com/assets/6093597/3051732/ff6319c2-e190-11e3-85e1-d162032c7791.png)

**Comment by fxprunayre** [comment]
A traiter dans l'éditeur de la v4

**Comment by fxprunayre** [comment]
Dispo en ISO19115-3 avec l'utilisation des flatModExceptions (https://github.com/metadata101/iso19115-3/blob/develop/src/main/plugin/iso19115-3/layout/config-editor.xml#L328)

![image](https://cloud.githubusercontent.com/assets/1701393/7611497/26a36e94-f985-11e4-861f-ff11b7d7f06a.png)

**Comment by vbombaerts** [comment]
Pas trouvé l'élement en vue simple ni en vue géoportail.

**Comment by fxprunayre** [comment]
En vue simple ok a priori.

![image](https://cloud.githubusercontent.com/assets/1701393/12894576/d1e4ebd8-ce97-11e5-8676-fcc8daafec48.png)

En vue Geoportail - en effet nous n'avions pas mis le champ. Ajouté avant les thèmes INSPIRE - Ca convient ?

![image](https://cloud.githubusercontent.com/assets/1701393/12894586/e705fc6e-ce97-11e5-9b20-8629e4707a15.png)

Donc même s'il n'y a pas de topic category dans la fiche, le bouton pour en ajouter un sera là.

**Comment by vbombaerts** [comment]
Ca fonctionne mais pourquoi "catégorie ISO" devient "thématique" quand on ajoute une thématique ??
Je propose "Thématique ISO" ou Thème ISO.
Egalement, du point de vue de l'utilisateur, c'est particulier que la présentation soit différente entre les thèmes du géoportail, les thèmes INSPIRE et les thèmes ISO. Est-il possible d'harmoniser la présentation ?

**Comment by davinciagf** [comment]
La présentation est différente selon le thesaurus (classique ou hiérarchique).

**Comment by vbombaerts** [comment]
J'ai bien compris. C'est pas possible d'harmoniser ?

**Comment by fxprunayre** [comment]
> J'ai bien compris. C'est pas possible d'harmoniser ?

On pourrait imaginer faire un composant JS avec zone de texte avec autocompletion pour tous les champs de type codelist. Les problèmes/difficultés:
- sans doute les performances car ca va alourdir l'éditeur car le composant actuelle est un simple champ HTML de type select géré directement par le navigateur
- il faut gérer les codeslits à cardinalité 1 ou n et donc utiliser le mode XML au lieu du mode clé/valeur

Donc pas impossible, mais pas trivial et avec quelques inconvénients probables (c'est pour ça qu'on l'a passé en 4.1).
