### ISSUE TITLE
Mise à jour des fichiers d'aide

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#161]
Mettre à jours les fichiers d'aide spécifiques pour la Wallonie.

**Comment by vbombaerts** [comment]
Première mise à jour. Pas encore fini. ed76b5abfbbe69ca876554fdbe9285aef337d184

**Comment by vbombaerts** [comment]
Dans le catalogue, j'ai des fiches qui sont en rw:MD_Metadata et d'autres en gmd:MD_Metadata.
Pour le moment, l'aide "Metawal" s'affiche pour les rw:MD_Metadata mais pas pour les gmd:MD_Metadata. Comment faire pour que l'aide soit valable dans les deux cas ?
- dédouble l'aide ?
- transformer toutes les fiches <rw> en <gmd>
- autre ?

**Comment by fxprunayre** [comment]
> Comment faire pour que l'aide soit valable dans les deux cas ?
> dédouble l'aide ?

C'est sans doute le plus simple. Reporter le contenu de l'aide des éléments rw:\* dans les fichiers iso19139/loc/fre/labels.xml pour leur équivalent.

> transformer toutes les fiches en

Ce serait possible, mais certaines fiches sont issues du moissonnage non ? donc on peut difficilement les convertir je pense.

> autre ?

Pas d'autre option je pense.

**Comment by vbombaerts** [comment]
Pour bien comprendre : 
Quand je modifie l'aide, je dois faire les changements dans deux fichiers :
- iso19139/loc/fre/labels.xml pour tous les changements sauf ceux typiques du profil wallon
- iso19139.rw/loc/fre/labels.xml pour les changements qui impliquent les élements rw:*, càd les éléments typiques du profil wallon + ceux pour lesquels j'utilise le "context" pour les préciser.

Pour le moment, j'ai tout modifié dans iso19139.rw/loc/fre/labels.xml ...

**Comment by fxprunayre** [comment]
Quand une fiche est importée, il y a détection du schéma. Soit iso19139.rw soit iso19139 (fonction de l'élément racine).

Le fichier iso19139.rw/loc/fre/labels.xml surcharge les libellés de iso19139/loc/fre/labels.xml pour les fiches ayant un schéma iso19139.rw (il est en complément de iso19139/loc/fre/labels.xml).

Les fiches en iso19139 n'utilisent que le fichier iso19139/loc/fre/labels.xml

**Comment by vbombaerts** [comment]
J'ai fait les modifs. J'espère ne pas m'être planté
ed7f7450dde349ad8df0917a436b03648ddcf9d9
a4ec8ddb221b59855b24ce159d3102e297f30aba
