### ISSUE TITLE
Ajouter un thésaurus technique - Mots-clés InfraSIG

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#162]
Pour avoir rapidement un critère pour les points d'accès virtuels et différencier clairement les fiches de métadonnées, un thésaurus technique doit être créé. Il contiendra des entrées telles que : 
- open data
- Monitoring INSPIRE

**Comment by vbombaerts** [comment]
Je l'ai mis ici, est-ce le bon endroit ? 9356f8743a4f8c1ed754be552aa1d7c9b26efb67

**Comment by davinciagf** [comment]
oui
