### ISSUE TITLE
Edition - Vue par défaut - modifications de présentation

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#163]
Je souhaiterais quelques modifications de présentation dans la vue par défaut par exemple au niveau des dates de référence, des identifiants...
Plusieurs type de changement ont été identifiés :
- le regroupement d'éléments en-dessous de l'élément hiérarchique supérieur. (exemples des dates et de l'identifiant de la ressource sous forme RS_identifier)
- la possibilité d'ajouter/supprimer et de changer l'ordre des éléments de même type (exemples de la thématique ISO, et des dates)

Dates
--> regroupement des sous-éléments sous l'élément, comme en vue par onglets
![image 749](https://cloud.githubusercontent.com/assets/6093597/3413305/2d9ac804-fe0a-11e3-914a-d80de3539342.png)
![image 751](https://cloud.githubusercontent.com/assets/6093597/3413332/78daad7a-fe0a-11e3-96a3-83ceba6bf03c.png)

![image 750](https://cloud.githubusercontent.com/assets/6093597/3413318/4e26c168-fe0a-11e3-8702-a732fc54ea63.png)
--> possibilité d'ajouter/supprimer et modifier l'ordre, comme en vue par onglets
![image 751](https://cloud.githubusercontent.com/assets/6093597/3413333/81750f0c-fe0a-11e3-9b57-b960adae3461.png)

Thématique ISO
--> #159 

Identifiant de la ressource
--> regroupement
![image 753](https://cloud.githubusercontent.com/assets/6093597/3413405/2e1365ba-fe0b-11e3-8dde-3089927668cc.png)
![image 752](https://cloud.githubusercontent.com/assets/6093597/3413408/3360e31c-fe0b-11e3-9b69-b055ad3b1d85.png)

**Comment by vbombaerts** [comment]
Contraintes sur la ressource :
placer l'élément uselimitation en fin de bloc (pour tous les types de contraintes)
![image 758](https://cloud.githubusercontent.com/assets/6093597/3497387/372da2cc-05eb-11e4-97e7-55bcf151e09a.png)

**Comment by fxprunayre** [comment]
Dans la vue par défaut de GN, ce n'est pas configurable. Les informations de cette vue sont celles du document XML dans l'ordre (à  l'exception du bloc metadata affiché à la fin). A voir si fait dans le nouvel éditeur.

**Comment by vbombaerts** [comment]
a voir dans la saisie ISO19115-3 cf #153

**Comment by fxprunayre** [comment]
TODO:
- grouper date / type de date
- regroupement sur la vue simple

Ensuite cf. Wizard

**Comment by fxprunayre** [comment]
> grouper date / type de date

Cf. https://github.com/metadata101/iso19115-3/issues/8

**Comment by fxprunayre** [comment]
Vue simple possibilité d'ajouter n topic catégorie.

Pour les autres points: cf discussion éditeur

**Comment by fxprunayre** [comment]
La suite est faite dans #253

**Comment by vbombaerts** [comment]
Voir #253 
Je ferme celui-ci
