### ISSUE TITLE
Thésaurus - Informations automatiques sur le thésaurus

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#165]
Les informations remplies automatiquement à propos du thésaurus sont erronées.
Par exemple, pour les thèmes INSPIRE, on a 

```
<gmd:thesaurusName>
    <gmd:CI_Citation>
        <gmd:title>
            <gco:CharacterString>INSPIRE themes</gco:CharacterString>
        </gmd:title>
        <gmd:date>
            <gmd:CI_Date>
                <gmd:date>
                    <gco:Date>2009-09-22</gco:Date>
                </gmd:date>
                <gmd:dateType>
                    <gmd:CI_DateTypeCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/Codelist/ML_gmxCodelists.xml#CI_DateTypeCode" codeListValue="publication"/>
                </gmd:dateType>
            </gmd:CI_Date>
        </gmd:date>
    ...
```

Les valeurs que je trouve sur le site du GEMET http://www.eionet.europa.eu/gemet/inspire_themes?langcode=fr sont
Nom : GEMET - INSPIRE themes, version 1.0
Date de publication : 2008-06-01

Pour le thèmes du géoportail, ça devrait être :
    Titre : Thèmes du géoportail wallon, version 1.0
    Date : 2012-02-03
    Type de date : Création

et on a

```
<gco:CharacterString>Thèmes du géoportail wallon</gco:CharacterString>
<gco:Date>2012-06-19</gco:Date>
codeListValue="publication
```

Même problème pour le GEMET ??
On en est maintenant à la v3.1 du GEMET

**Comment by fxprunayre** [comment]
> Même problème pour le GEMET ??
> On en est maintenant à la v3.1 du GEMET

Il faudrait mettre à jour le thésaurus d'origine 
https://github.com/geonetwork/util-gemet/blob/master/thesauri/gemet-theme.rdf
actuellement en version 2.4 je pense.

Pour la mise à jour des fiches soit via XSL sinon via SQL :

```
UPDATE metadata SET data = replace(data, '<gco:CharacterString>Thèmes du géoportail wallon</gco:CharacterString>', '<gco:CharacterString>Thèmes du géoportail wallon, version 1.0</gco:CharacterString>');

-- Marche sous postgresql mais ca marchait pas sous Oracle 9. Ca a peut être changé.
```

**Comment by vbombaerts** [comment]
OK pour les infos thésaurus dans les nouvelles fiches.
La mise à jour des infos thésaurus dans les fiches existantes n'a pas été faite (en env. de test).

**Comment by vbombaerts** [comment]
Changement effectué. Reste le problème #175

**Comment by fxprunayre** [comment]
Thésaurus GEMET mis à jour.

Configuration Facette configurée pour analyser les mots clés existant dans Gemet

![image](https://cloud.githubusercontent.com/assets/1701393/11744812/c2bcda06-a013-11e5-9797-a0f7a1fc21a6.png)

Saisie avec navigation possible (suite au développement https://github.com/geonetwork/core-geonetwork/wiki/2014AngularEditorSkosThesaurusBrowser fait dans GN3.0.3)

![image](https://cloud.githubusercontent.com/assets/1701393/11744954/c0f77fd6-a014-11e5-9c61-e230f46cc1ef.png)

**Comment by vbombaerts** [comment]
OK, mais pq ne pas en avoir profité pour mettre à jour la version du GEMET vers 3.1 plutôt que 2.4
Egalement, remarques sur ergonomie (mais je ne retrouve pas la référence du ticket..WTF?!?)
![2016-03-02 16_10_31-microsoft powerpoint - presentation1](https://cloud.githubusercontent.com/assets/6093597/13644349/9aed8946-e625-11e5-91f3-ac00188bfc6c.png)

**Comment by fxprunayre** [comment]
> ne retrouve pas la référence du ticket..WTF?!?)

#278

**Comment by fxprunayre** [comment]
TODO: GEMET vers 3.1

**Comment by fxprunayre** [comment]
Cf. https://github.com/geonetwork/util-gemet/issues/2

**Comment by fxprunayre** [comment]
A redéployer. Il faudra mettre à jour le fichier gemet.rdf.

**Comment by vbombaerts** [comment]
Le numéro de version n'est toujours pas indiqué pour les thèmes du GP et pour le GEMET. OK pour INSPIRE.
![2017-03-22 10_57_10-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/24192249/97912bd4-0eee-11e7-8f19-147c6d11cc06.png)
![2017-03-22 10_57_38-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/24192257/9db7efde-0eee-11e7-90e8-44bc7b03d438.png)

**Comment by vbombaerts** [comment]
On laisse tomber pour le moment. On réouvrira plus tard si nécessaire.
