### ISSUE TITLE
Visualisation des fiches - restreint

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#167]
La définition de la valeur de (accès) "restreint" en visualisation n'est ps adaptée au contexte wallon.
![image 762](https://cloud.githubusercontent.com/assets/6093597/3599136/5ddb58d6-0ceb-11e4-8536-69ee16e28e3b.png)

**Comment by vbombaerts** [comment]
Quel fichier modifier pour adapter les valeurs aux contexte wallon ?

**Comment by davinciagf** [comment]
web\src\main\webapp\WEB-INF\data\config\schema_plugins\iso19139\loc\fre\codelists.xml

**Comment by vbombaerts** [comment]
https://github.com/SPW-DIG/metawal-core-geonetwork/commit/843b4b95a3f633f5c22a2096f9ad7f5b969476dd
