### ISSUE TITLE
Bouton géopublication

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#169]
Inutile dans le contexte de Metawal (pour le moment, mais ça donne des idées...). A supprimer/cacher.
![image 763](https://cloud.githubusercontent.com/assets/6093597/3600206/321d381c-0cf6-11e4-8d78-2489df67cfff.png)

**Comment by fxprunayre** [comment]
Sans objet dans metawal-4.x car le bouton n'apparaît que si des serveurs de publication sont configurés dans l'admin.
