### ISSUE TITLE
Boutons share de la page d'accueil : modifier contenu

### ISSUE THREAD

**Issue by metawal** [SPW-DIG/metawal-core-geonetwork#17]
Le boutons share (Twitter, Facebook, etc.) de la page d'accueil pointent vers la page "Retrouvez-nous sur les médias sociaux" du site www.wallonie.be.

Il faudrait harmoniser leur fonctionnement avec le Géoportail.

Dans le Géoportail, ces boutons permettent de partager la page en cours via les réseaux sociaux.

**Comment by fxprunayre** [comment]
En lien avec https://github.com/geonetwork/core-geonetwork/issues/1160

**Comment by davinciagf** [comment]
Les liens sociaux au niveau du footer pointent sur l'url de la page visionnée (ex: visualisation de la recherche, visualation d'une fiche, catalogue en générale)

**Comment by vbombaerts** [comment]
Si la recherche inclut un mot-clé, celui-ci n'est pas pris en compte dans le lien
![2016-03-09 18_06_13-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/13643538/b05dca1a-e621-11e5-9a8e-426fae3c0d47.png)
![2016-03-09 18_07_19-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/13643577/dcc7e180-e621-11e5-8db1-174d14d3238e.png)
![2016-03-09 18_09_39-home - message html](https://cloud.githubusercontent.com/assets/6093597/13643640/21ce13d0-e622-11e5-88be-df8aabdf2a65.png)
![2016-03-09 18_10_10-partager un lien sur twitter](https://cloud.githubusercontent.com/assets/6093597/13643673/3b275594-e622-11e5-80e1-6da456112f03.png)

J'ai pas testé les autres...

**Comment by davinciagf** [comment]
Erreur liée à l'élément séparateur des diffrents paramètres du mailto "&". Exemple: 
mailto:?subject=Home&body=http://localhost:8080/geonetwork/srv/fre/catalog.search%23/search?resultType=details&from=1&to=20&sortBy=relevance&fast=index&_content_type=json&any=sol

L'élément séparateur se retouve au niveau du body. Le contenu de l'url n'est donc pas pris au complet dans le corps du mail. Correction pour prendre l'url en entier.
