### ISSUE TITLE
IE 11 et impression

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#170]
L'impression de la fiche sous IE 11 avec pdf creator pose un problème sur le positionnement de la carte qui se superpose au texte

**Comment by fxprunayre** [comment]
Dans GN3, on imagine utiliser des "formatters" https://github.com/geonetwork/core-geonetwork/wiki/Schema-Formatters-and-Metadata-Views pour simplifier la mise en place de vue de consultation. Cela devrait simplifier ce type de chose (même si le problème vient plus du navigateur incapable de placer correctement les div de la carte dynamique OpenLayers au bon endroit dans l'impression PDF).

**Comment by fxprunayre** [comment]
eg. http://metawal4.test.wallonie.be/geonetwork/srv/fre/md.format.pdf?xsl=xsl-view&view=advanced&uuid=0f475c62-c913-4dd9-a61a-ae7ff523c066 (pas terrible pour la carte)

**Comment by vbombaerts** [comment]
OK
