### ISSUE TITLE
Editeur - Extent - Liste des entités administratives

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#172]
Petites corrections à apporter dans la liste des entités administratives :
- Ajouter "Commune de" ou "Commune d'" devant le nom des communes
- Ajouter les autres niveaux administratifs : provinces ("Province de") et région wallonne
- Limiter les coordonnées en WGS84 à 2 décimales
  ![image 786](https://cloud.githubusercontent.com/assets/6093597/4333427/258f0676-3fe0-11e4-91a7-1f0315011530.png)

**Comment by fxprunayre** [comment]
J'imagine qu'en plus de la "Petites corrections" il faut corriger les valeurs correspondantes dans les fiches existantes ?

**Comment by vbombaerts** [comment]
Pour le moment, la plupart des fiches sont sur l'extent "Région wallonne", donc il n'y a pas ou peu de corrections à apporter dans les fiches.

**Comment by vbombaerts** [comment]
Mettre à jour le fichier rdf uniquement

**Comment by vbombaerts** [comment]
- Ajouter les autres niveaux administratifs : provinces ("Province de") et région wallonne
- Limiter les coordonnées en WGS84 à 2 décimales
- Changer le nom du thésaurus en Entités administratives
- Utiliser ce thésaurus pour le calcul de l'extent spatial

**Comment by vbombaerts** [comment]
Est-il possible de trier sur base des numéros INS qui sont utilisés dans la balise rdf:about ?

**Comment by vbombaerts** [comment]
Super ! Est-ce que tu sais pourquoi ça apparait dans l'ordre voulu dans le cadre de l'étendue géographique mais pas dans les mots-clés ??

**Comment by vbombaerts** [comment]
La liste a disparu. Le thésaurus n'est plus dans la liste des thésaurus.

**Comment by vbombaerts** [comment]
La limitation à deux décimales des coordonnées des bounding box en WGS 84 n'est pas effective ==> arrondir à l'inférieur pour ouest et sud, au supérieur pour nord et est. Pour la RW, utiliser les valeurs 
ouest : 2,75 / nord : 50,85 / est : 6,50 / sud : 49,45
