### ISSUE TITLE
Thésaurus - anciens vs nouveaux

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#175]
Dans la version 3.0 de Metawal, les thésaurus font référence à un identifiant, ce qui n'était pas le cas précédemment. Je ne sais pas si c'est lié, mais quand on édite une fiche créée dans une version antérieure, les mots-clés issus de thésaurus ne prennent pas la forme spécifique des mots-clés liés à un thésaurus. Faut-il modifier les fiches existantes pour intégrer cet identifiant? 

![image 804](https://cloud.githubusercontent.com/assets/6093597/5230147/f085787e-7721-11e4-87dd-d65eb6d4ed73.png)

**Comment by fxprunayre** [comment]
C'est en effet lié. Cependant, s'il n'y a pas d'identifiant pour le thésaurus, une correspondance est faite sur le titre (cf. https://github.com/spacebelGIS/metawal-core-geonetwork/blob/metawal-develop/web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/present/metadata-edit.xsl#L1329). A vérifier le titre dans le thésaurus et dans le "old way" et voir pouquoi ca ne fonctionne pas.

**Comment by vbombaerts** [comment]
Il y a en effet un mismatch sur les noms des thésauri 
voir #165

**Comment by fxprunayre** [comment]
On pourrait faire un test du type contains au lieu d'un "="
https://github.com/spacebelGIS/metawal-core-geonetwork/blob/metawal-develop/web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/present/metadata-edit.xsl#L1331 mais bof.

Ce serait sans doute préférable de corriger les fiches existantes et le titre du thésaurus thème INSPIRE - cf #165.

**Comment by fxprunayre** [comment]
Mise à jour des noms des thésaurus dans le process XSL qui fait la mise à jour des fiches cf. #154

**Comment by vbombaerts** [comment]
Résolu pour INSPIRE et pour les thèmes du GEMET, mais pas pour les thèmes du géoportail. Le nom du thésaurus a été changé, mais l'affichage spécifique ne se fait pas.
