### ISSUE TITLE
Recherche avancée  - INSPIRE

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#176]
Interface de recherche : les champs spécifiques à la recherche INSPIRE ont disparu.
![image 807](https://cloud.githubusercontent.com/assets/6093597/5243847/2e41fd3a-7949-11e4-8ba7-ab68698ebd58.png)

**Comment by fxprunayre** [comment]
Vérifier dans l'admin > configuration du système > INSPIRE: 
- activer au moins l'option INSPIRE
- et l'option formulaire de recherche INSPIRE pour la demande en question

**Comment by vbombaerts** [comment]
OK pour l'activation de l'option. En env. de test, la recherche par ce canal ne renvoie aucun résultat. En env. de prod, pas de problème.
