### ISSUE TITLE
Recherche avancée  - Etat de la fiche

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#177]
Remplacer le libellé "Changer l'état" par "Etat de la fiche" + problème des caractères spéciaux

![image 808](https://cloud.githubusercontent.com/assets/6093597/5243904/cf1cbf74-7949-11e4-9518-7ac9cbcb69fe.png)

**Comment by fxprunayre** [comment]
Voir https://github.com/spacebelGIS/metawal-core-geonetwork/blob/master/web-client/src/main/resources/apps/js/GeoNetwork/lib/GeoNetwork/util/SearchFormTools.js#L1017 et la traduction associée https://github.com/spacebelGIS/metawal-core-geonetwork/blob/metawal-develop/web-client/src/main/resources/apps/js/GeoNetwork/lib/GeoNetwork/lang/fr.js#L288
