### ISSUE TITLE
Etat de la métadonnée - problème caractères spéciaux

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#178]
![image 809](https://cloud.githubusercontent.com/assets/6093597/5243945/3ba42218-794a-11e4-9e21-3521a8d65f7b.png)

**Comment by fxprunayre** [comment]
reproduis en local. A corriger

**Comment by davinciagf** [comment]
Erreur d'encodage au niveau de la DB. 
SQL correctif (à commiter):
UPDATE statusvaluesdes SET label = 'Validé' WHERE langid ='fre' and iddes=2; 
UPDATE statusvaluesdes SET label = 'Retiré' WHERE langid ='fre' and iddes=3; 
UPDATE statusvaluesdes SET label = 'Rejeté' WHERE langid ='fre' and iddes=5;
