### ISSUE TITLE
Boutons share de la page d'accueil : ouvrir dans un nouvel onglet/nouvelle fenêtre

### ISSUE THREAD

**Issue by metawal** [SPW-DIG/metawal-core-geonetwork#18]

**Comment by vbombaerts** [comment]
Le comportement par défaut des liens qui mènent vers des sites externe doit être d'ouvrir dans un autre onglet.

**Comment by davinciagf** [comment]
Comportement par défaut des liens - nouvel onglet pour le footer et le header
