### ISSUE TITLE
Processus de commande standard

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#180]
Pour l'elément processus de commande standard --> pas de proposition : laisser une boite de texte classique
![image 812](https://cloud.githubusercontent.com/assets/6093597/5247545/aa93bcfa-7973-11e4-95e1-a8404e2a45d1.png)

**Comment by fxprunayre** [comment]
A priori la liste de suggestions a été supprimée là https://github.com/spacebelGIS/metawal-core-geonetwork/commit/a4ec8ddb221b59855b24ce159d3102e297f30aba#diff-56f8512c62d1830040f8563da846b01cL514.

A tester sur démo.

**Comment by davinciagf** [comment]
Test en local sans erreur - A déployer en envir. de test
