### ISSUE TITLE
Compatibilité INSPIRE (M2.2)

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#183]
## GetCapabilities
- section INSPIRE
  - thème : ajouter la version, mettre les 34 (liste à valider par Vincent)
  - supprimer langue : pt, es 
  - eg. http://sdi.eea.europa.eu/catalogue/srv/eng/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetCapabilities
- corriger port manquant f. http://metawal.wallonie.be/geonetwork/srv/fre/csw?SERVICE=CSW&REQUEST=GetCapabilities&VERSION=2.0.2

A tester dans metawal-devleop et corriger (cf. GN)
https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-develop/web/src/main/webapp/xml/csw/capabilities_inspire.xml
## CSW INSPIRE

Créer un service virtuel avec mot clé = "Reporting INSPIRE"

**Comment by davinciagf** [comment]
A jouer au niveau de la DB pour limiter le nombre de langues dispo (eng,fre,dut,ger).

UPDATE languages SET  ISINSPIRE = 'n' WHERE id='es';
UPDATE languages SET  ISINSPIRE = 'n' WHERE id='pt'; 

Modifier les id de la table (deux caractères vers trois caractères également)  (a reporter vers GN)

**Comment by davinciagf** [comment]
Il est important de compléter les paramètres du CSW afin que celui-ci soit valide (voir administration/paramètres/csw). 
Qq remarques:
1. Contact (ne pas oublier de compléter les références de l'adresse physique au niveau de l'utilisateur qui est désigné comme contact)
2. Information sur le service - compléter les différents champs pour les différentes langues (eng,fre,dut,ger)

Une note spécifique sera prochainement fournie dns le cadre du M2.2. cette note reprendra la validation et les paramètres à introduire pour fournir un CSW valide + lien avec le  #203

**Comment by vbombaerts** [comment]
Voici le rapport de validation par le validateur du géoportail INSPIRE
 http://inspire-geoportal.ec.europa.eu/resources/sandbox/INSPIRE-ab08dd3c-9d8a-11e4-8889-52540004b857_20150116-151922/services/1/resourceLocator1/discovery/services/1/ 

Je remarque que je n'ai pas renseigné les conditions d'accès et d'utilisation et les limites d'accès public.
Je remarque aussi une erreur dans l'adresse deux derniers resource locator : le caractère ':' est inséré entre wallonie.be et /geonetwork, comme s'il manquait l'information sur le port.

Comment corriger ces erreurs ?

**Comment by davinciagf** [comment]
Vérifier la visibilité des infos dans le formulaire de saisie (titre, résumé) pour les différentes langues. Les données semblent présentes mais non visibles

**Comment by vbombaerts** [comment]
Rapport ici : http://inspire-geoportal.ec.europa.eu/resources/sandbox/INSPIRE-395b3f7c-e934-11e4-a2c7-52540004b857_20150422-231203/services/1/resourceReport/ 
Il reste quelques erreurs et remarques à vérifier, mais dans l'ensemble c'est OK.
