### ISSUE TITLE
Changement d'interface de visualisation à partir de la gestion des utilisateurs

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#186]
Quand on visualise une fiche appartenant à un utilisateur à partir du panneau de configuration - gestion des utilisateurs, la fiche est visualisée dans l'interface par défaut de GN et pas dans l'interface Metawal. De plus, elle est en anglais.

![image 816](https://cloud.githubusercontent.com/assets/6093597/5402481/533f06a2-8185-11e4-8fe0-2133358d5c85.png)

![image 817](https://cloud.githubusercontent.com/assets/6093597/5402483/5a5262cc-8185-11e4-903b-7b44ddbaf365.png)

**Comment by fxprunayre** [comment]
Doublon avec #146. Je ferme.
