### ISSUE TITLE
Attribution des fiches aux groupes

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#187]
J'ai un problème notamment avec la fiche http://metawal.wallonie.be/geonetwork/srv/fre/search?uuid=78bebbe4-dffd-431a-83d2-3460c40b92ff
Cette fiche appartient à un utilisateur du groupe DGO3. Cet utilisateur n'est éditeur que pour ce groupe. Pourtant, une recherche avancée spécifiant que la fiche doit appartenir au groupe DGO3 ne remonte pas la fiche. Y a-t-il une explication ?

**Comment by fxprunayre** [comment]
Oui, le critère groupe dans le formulaire avancé est le groupe dans laquelle la fiche a été créée et non le groupe dans laquelle la fiche est publiée. 

Cependant dans GeoNetwork, ces points ont été modifiés (à la demande de l'ifremer) pour justement: 
- rechercher les fiches par groupe de publication et non groupe d'appartenance (ajout d'un champ dans l'index) et 
- permettre de modifier le groupe dans laquelle la fiche a été créée (via le nouvel éditeur)

**Comment by vbombaerts** [comment]
OK, on attend le nouvel éditeur.
