### ISSUE TITLE
Modification des informations du compte utilisateur

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#189]
Quand on se connecte pour modifier des informations utilisateur, on a accès aux champs permettant de modifier le niveau du profil (les droits). On a aussi accès à la liste des autres utilisateurs (du groupe). Après avoir modifié le niveau de profil et enregistré, on n'a plus aucun accès aux infos utilisateur.

**Comment by fxprunayre** [comment]
A améliorer:
- si admin on peut tout faire
- si reviewer et useradmin on peut gérer les groupes (mais pas l'option est administrateur)
- si editor et registereduser on ne peut pas modifier les groupes.
