### ISSUE TITLE
Compte utilisateur : modification du mot de passe

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#190]
Lorsqu'on accède aux infos utilisateur, il n'est pas possible de modifier son mot de passe. Peut-on ajouter cette fonctionnalité ? (je connais mon mot de passe, mais je veux le changer)

**Comment by fxprunayre** [comment]
Cf. https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-develop/web-ui/src/main/resources/catalog/templates/admin/usergroup/users.html#L36

**Comment by vbombaerts** [comment]
Serait-il possible de supprimer/remplacer le commentaire contextuel qui apparaît et qui fait un peu peur (on n'a pas trop envie de supprimer l'utilisateur). Il apparait quand on passe la souris sur n'importe lequel des 3 boutons
![image 832](https://cloud.githubusercontent.com/assets/6093597/5760854/b24f8abe-9cd7-11e4-8d6e-50dfafdbdb0b.png)
