### ISSUE TITLE
Une aide métadonnées indépendante de l'application Metawal

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#191]
L'idée est de remplacer le wiki métadonnées par un site d'aide équivalent puisant son contenu dans les fichiers d'aide de Metawal. L'objectif est de fournir des instructions/bonnes pratiques unifiées pour les utilisateurs, qu'ils utilisent Metawal ou non, et de fournir une documentation relative aux métadonnées et au profil wallon. Tout ceci en évitant de disperser l'information. L'accès à ce site doit pouvoir se faire sans login Metawal.

TODO (à compléter/modifier):
- Définir le contenu et le design du site d'aide en ligne
- Re-définir la structure du fichier d'aide XML pour ajouter les éléments manquants (sans tout casser de la structure actuelle qui doit rester bonne pour l'aide Metawal)
- Développer les feuilles de styles et les routines de transformation
- Créer le contenu
- Trouver où placer le nouveau site, "à côté" de Metawal.

Exemple de design et contenu actuel du wiki  :
![image 821](https://cloud.githubusercontent.com/assets/6093597/5485337/23f554a4-869a-11e4-8204-a08cce8de42c.png)
![image 822](https://cloud.githubusercontent.com/assets/6093597/5485370/80603024-869a-11e4-9784-fa9efd7dfba0.png)
![image 823](https://cloud.githubusercontent.com/assets/6093597/5485371/86734bcc-869a-11e4-8f7c-a4b29934ed6a.png)

**Comment by fxprunayre** [comment]
- labels.xml : définir ce qui manque 
  - ordre http://geoportail.wallonie.be/files/docs/Metawal/Aide_metadonnees_geo.pdf
  - section
  - classer des sections help (cf. attribut for) : aide pour la "norme", pour l'appli, exemple, contre exemple, bonne pratique
- ajouter la doc des standards dans les annexes de la doc de l'application (build)

**Comment by davinciagf** [comment]
voir #307
