### ISSUE TITLE
Mécanismes de mise à jour parents-enfants

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#192]
Ces mécanismes sont-ils toujours disponibles ? Comment ?

**Comment by fxprunayre** [comment]
Hum, plus trop. Dans l'interface ExtJS (ie. éditeur de metawal3) il devrait y'avoir un bouton dans le panneau des relations - la fonctionnalité semble avoir été branchée rapidement (cf. https://github.com/geonetwork/core-geonetwork/blob/develop/web-client/src/main/resources/apps/js/GeoNetwork/lib/GeoNetwork/widgets/editor/LinkedMetadataPanel.js#L309). Dans l'éditeur AngularJS (v4), ce n'est pas disponible.

Côté serveur, cependant rien n'a été supprimé donc nous pourrions imaginer un "revival" plus complet.

Historique:
- demandé dans le cadre de GéoSource y'a 5 ans http://trac.osgeo.org/geonetwork/wiki/UpdateChildren
- applicable uniquement aux fiches ISO19139 (cf. https://github.com/geonetwork/core-geonetwork/blob/develop/schemas/iso19139/src/main/plugin/iso19139/update-child-from-parent-info.xsl)
- lors de la refonte de l'éditeur avec Angular, nous nous étions posé la question de l'utilité avec @taffoureau ... a priori peu d'usage même si la fonction semble parfois pratique. Ca mériterait sans doute d'être bien testé.

**Comment by fxprunayre** [comment]
Cf. #257
