### ISSUE TITLE
Touche Escape pour fermer la fiche

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#193]
Est-il possible de prévoir un mécanisme empêchant de fermer directement une fiche quand on appuie sur la touche "Escape" ? Souvent, en édition, lorsque je souhaite refermer une liste déroulante j'appuie sur escape. Cela a pour effet très désagréable de fermer la fiche en cours d'édition (et toutes ses modifications) ;-)
Alternatives :
- réserver esc pour fermer les dropdown lists
- quand une dropdown list est ouverte, il est nécessaire d'appuyer 2 fois sur esc pour fermer la fiche (1. fermeture de la liste ; 2. fermeture de la fiche)
- quand on appuie sur esc, il y a demande de confirmation de fermeture de la fiche

**Comment by fxprunayre** [comment]
Je propose de voir ça ultérieurement en 3.2 voir en 4 vue la refonte en cours de l'intrerface.

**Comment by fxprunayre** [comment]
Je propose de fermer car sans objet en v4 étant donnée qu'il n'y a plus de popup ?

**Comment by vbombaerts** [comment]
Ça marche.
