### ISSUE TITLE
Validation - voir uniquement les erreurs

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#194]
Est-il possible de rétablir cette fonctionnalité bien pratique sur base d'un mécanisme plus simple que l'affichage et le tri des informations de validation, type cas à cocher/décocher ?

**Comment by fxprunayre** [comment]
C'est le fonctionnement par défaut dans metawal 4 https://github.com/geonetwork/core-geonetwork/wiki/Refactoring-editor#validation-report

Faut-il prévoir une évol dans la branche v3 ?

**Comment by vbombaerts** [comment]
Si ce n'est pas trop lourd comme travail, ce serait bienvenu.

**Comment by vbombaerts** [comment]
Disponible en v4
