### ISSUE TITLE
Erreur de validation pour les documents chargés dans Metawal

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#195]
Quand on charge un document dans Metawal via le panneau de droite, le code XML généré se présente comme suit :

``` xml
<gmd:onLine>
    <gmd:CI_OnlineResource>
        <gmd:linkage>
            <gmd:URL>http://metawal.wallonie.be/geonetwork/srv/fre/resources.get?uuid=6f924476-d62c-4f1c-bc9a-03e1d9f06424&amp;fname=Attributs_Mailles2.docx&amp;access=private</gmd:URL>
        </gmd:linkage>
        <gmd:protocol>
            <gco:CharacterString>WWW:DOWNLOAD-1.0-http--download</gco:CharacterString>
        </gmd:protocol>
        <gmd:name>
            <gmx:MimeFileType xmlns:gmx="http://www.isotc211.org/2005/gmx" type="application/vnd.openxmlformats-officedocument.wordprocessingml.document">Attributs_Mailles2.docx</gmx:MimeFileType>
        </gmd:name>
        <gmd:description>
            <gco:CharacterString>Attributs_Mailles2.docx</gco:CharacterString>
        </gmd:description>
    </gmd:CI_OnlineResource>
</gmd:onLine>
```

Cela cause une erreur de validation. Le type attendu pour le `<gmd:name>` étant `<gco:characterstring>`

Exemple : http://metawal.wallonie.be/geonetwork/srv/fre/search?uuid=6f924476-d62c-4f1c-bc9a-03e1d9f06424

**Comment by fxprunayre** [comment]
La fiche XML inclue une référence vers un schéma XSD spécifique http://www.isotc211.org/2005/gmd/gmd.xsd cf. l'élément racine

```
<gmd:MD_Metadata xmlns:gco="http://www.isotc211.org/2005/gco" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xmlns:gts="http://www.isotc211.org/2005/gts" 
  xmlns:gml="http://www.opengis.net/gml" 
  xmlns:gmd="http://www.isotc211.org/2005/gmd" 
  xsi:schemaLocation="http://www.isotc211.org/2005/gmd http://www.isotc211.org/2005/gmd/gmd.xsd">
```

Le schéma gmd.xsd publié par l'ISO ne contient pas de référence à gmx.xsd (ce qui est normal - on peut utiliser l'un sans l'autre). Par contre, le schéma ISO19139 pour le catalogue inclu les namespaces gmd, srv et gmx (cf. https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-develop/web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/schema.xsd#L8).

C'est ce schéma qui est utilisé pour la validation quand il n'y a pas de xsi:schemaLocation dans la fiche (ce qui est conseillé).

Solution: Supprimer xsi:schemaLocation de la fiche et laisser le catalogue valider la fiche avec le schéma local complet.

**Comment by vbombaerts** [comment]
Je suis pas très au clair avec cette histoire. Faudra qu'on en reparle...
