### ISSUE TITLE
Association de ressources, contenu du panneau des Ressources associées et de la vue simplifiée

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#197]
Quand on associe deux jeux de données, si le type d'initiative est absent ou n'est pas défini, la relation n'apparait pas dans le panneau des ressources associées.
![image 826](https://cloud.githubusercontent.com/assets/6093597/5646995/2278bcd6-9682-11e4-8633-3367078886ab.png)
Si le type d'initiative est spécifié, la relation apparait.
![image 825](https://cloud.githubusercontent.com/assets/6093597/5647005/37e75ce4-9682-11e4-8db0-533cbe1b05d5.png)
Comment l'élément est facultatif, la relation devrait apparaitre dans tous les cas.

**Comment by vbombaerts** [comment]
Même remarque pour la vue simplifiée. L'info devrait apparaitre même quand le type d'initiative n'est pas spécifié.

**Comment by fxprunayre** [comment]
A déployer et tester.

**Comment by fxprunayre** [comment]
Reporter dans GN3 (https://github.com/geonetwork/core-geonetwork/commit/dba936a3beab9222d432ee6c19b0107e807a363c)
