### ISSUE TITLE
Recherche INSPIRE - bug du mot-clé altitude

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#198]
Une recherche par thème INSPIRE sur base du thème Altitude ne renvoie pas les fiches qui renseignent ce mot-clé. D'autres thèmes ont été testés (zones de risque naturel, sols) et fonctionnent.
Ex de fiche : http://metawal.wallonie.be/geonetwork/srv/fre/search?uuid=03abb4c1-5f53-46bb-94fa-359f3912a041

**Comment by vbombaerts** [comment]
Le problème a été détecté en utilisant la dropdown box dans le recherche avancée.

**Comment by fxprunayre** [comment]
Corrigé par portage du fix depuis GN (https://github.com/geonetwork/core-geonetwork/issues/524). Il faut définitivement avoir une branche metawal que nous puissions aligner facilement sur GN (ce qui est le cas de la v4).

A déployer.

**Comment by vbombaerts** [comment]
Fiches trouvées.

**Comment by vbombaerts** [comment]
Même problème avec les services d'utilité publique et service publics.
- Une recherche INSPIRE avec ce thème ne donne aucun résultat.
- Ils n'apparaissent pas dans les facettes
  ![capture](https://cloud.githubusercontent.com/assets/6093597/7273322/dabab796-e8f2-11e4-8dfd-a614517cb86c.PNG)

**Comment by fxprunayre** [comment]
See https://github.com/geonetwork/core-geonetwork/issues/987

**Comment by fxprunayre** [comment]
Corrigé côté GN3/MW4 également.

**Comment by vbombaerts** [comment]
OK. Testé sur établissement pour ainés
