### ISSUE TITLE
La facette thèmes INSPIRE ne fonctionne pas

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#199]
Quand on sélectionne un thème INSPIRE via les facettes, on obtient aucun résultat.

**Comment by fxprunayre** [comment]
A déployer et tester. Problème de configuration inspireThemes au lieu de inspirethemes et également problème de sauvegarde dans l'administration.

**Comment by vbombaerts** [comment]
Je ne sais pas pourquoi, mais quand je suis loggé admin, j'ai droit aux thèmes dans les 3 langues nationales + l'anglais.

![image 835](https://cloud.githubusercontent.com/assets/6093597/5762256/390c153c-9ce1-11e4-90f6-3e43d4bb5014.png)

**Comment by fxprunayre** [comment]
Une des fiches à l'origine du pb http://metawal3.test.wallonie.be/geonetwork/srv/fre/search?uuid=bf431c9a-84a7-4de6-8b08-f7cbffb0ac39

Cette fiche est multilingue.

Les facettes n'ont pas vraiment de notion de langue ie. une facette = un champ de l'index (cf. https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-develop/web/src/main/webapp/WEB-INF/config-summary.xml#L22).

Dans le cas des thèmes INSPIRE, tous les mots clés correspondant sont indexés (cf. https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-develop/web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/index-fields.xsl#L237). Il y d'ailleurs une remarque sur les langues.

Dans le cas d'une fiche multilingue, une fiche de métadonnées = n documents dans des index différents (n = nombre de langue). On dispatch les mots en fonction des langues dans les différents index.

Donc pour la fiche bf431c9a-84a7-4de6-8b08-f7cbffb0ac39 on a 4 documents, un dans chacun des index FRE, DUT, GER, ENG avec un champ inspireTheme avec des valeurs différentes.

Les recherches sont faites sur les différents index, les facettes sont calculés sur les fiches retournées (potentiellement un mix de langue). D'où le pb car le document de l'index ENG est sans doute préféré.

2 options pour améliorer ça:
- option 1) Pour les thèmes INSPIRE, tout convertir dans une seule langue et créer un nouveau champ dans l'index (et traduire les facettes en fonction de la langue de la requête)
- option 2) Préférer les documents dans la langue de l'interface ie. si une fiche est dans l'index français et anglais et que la recherche est en français n'utiliser que l'index français. Le thème INSPIRE récupéré sera la version française (s'il est dans la fiche dans cette langue).

L'option 2 est disponible dans GN3/MW4 via l'admin.

L'option 1 est plus systématique (approche retenu pour le tableau de bord INSPIRE) mais demande un peu de travail.

On aborde ça en v4 ?

**Comment by vbombaerts** [comment]
OK pour v4

**Comment by fxprunayre** [comment]
Corrigé en v4. A déployer et tester je pense.

**Comment by vbombaerts** [comment]
Pas testable car facette non présente.

**Comment by vbombaerts** [comment]
J'ai activé des options (mais sont-ce les bonnes ?), reconstruit l'index et vidé le cache navigateur, mais les thèmes en langue étrangère sont toujours présents.

![2016-03-09 17_55_30-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/13643252/38026a72-e620-11e5-8228-50ca65f2bd21.png)

![2016-03-09 17_57_18-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/13643342/99d26ed2-e620-11e5-94ea-755f3cd47755.png)

![2016-03-09 18_12_40-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/13643769/a529c2f6-e622-11e5-8409-ee58e8fd4dc6.png)

**Comment by fxprunayre** [comment]
Corrigé. 

> J'ai activé des options (mais sont-ce les bonnes ?),

Ne pas activer la détection des langues et les options sur les langues - assez souvent ça apporte plus de pb que ca n'en corrige. 

J'ai également modifié l'ordre des facettes - thèmes geoportail en premier.

![image](https://cloud.githubusercontent.com/assets/1701393/14140114/62d9dda4-f677-11e5-8efb-ede5a7bf8b19.png)

A redéployer.

**Comment by vbombaerts** [comment]
OK.
