### ISSUE TITLE
Liste de mots-clés déroutante

### ISSUE THREAD

**Issue by geologiewallonie** [SPW-DIG/metawal-core-geonetwork#20]
Il faudrait ranger la liste des mots clés : Soit proposer des catégories de mots-clés, soit proposer plusieurs menus.

**Comment by fxprunayre** [comment]
Avec facette sur thème geoportail et theme INSPIRE, supprimer la facette sur les mots clés.

**Comment by davinciagf** [comment]
Suppression de la facette "mots-clés" via #292
