### ISSUE TITLE
Moissonnage - impossible de définir un filtre de recherche

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#200]
Impossible de définir un filtre de recherche pour un service CSW moissonné.

**Comment by vbombaerts** [comment]
Voir aussi #85

**Comment by fxprunayre** [comment]
En local, pas de soucis.

Quel est l'URL du CSW en question ?

Testé avec http://apps.titellus.net/geonetwork/srv/eng/csw sur metawal 3.

![image](https://cloud.githubusercontent.com/assets/1701393/5682356/a966a7e6-981f-11e4-95e0-ef5f0edcdd15.png)

**Comment by vbombaerts** [comment]
http://ccff02.minfin.fgov.be/geoportalext/csw/discovery
Requête Get Capabilities : http://ccff02.minfin.fgov.be/geoportalext/csw/discovery?Request=GetCapabilities&Service=CSW&Version=2.0.2

**Comment by fxprunayre** [comment]
L'erreur lors de la sauvegarde est:

```
<title>Error 400 Cannot build ServiceRequest
Cause : Error on line 1: The prefix "apiso" for element "apiso:Subject" is not bound.
Error : org.jdom.input.JDOMParseException
</title>
```

Test avec l'API REST ESRI http://ccff02.minfin.fgov.be/geoportalext/rest/find retourne access denied donc nous ne pouvons utiliser que le CSW.

**Comment by fxprunayre** [comment]
Fait côté MW 3. A reporter dans GN & MW4 En lien avec https://github.com/geonetwork/core-geonetwork/issues/548

**Comment by fxprunayre** [comment]
3h plus tard, appliqué dans GN stable-develop, GN develop & MW4.

**Comment by vbombaerts** [comment]
Désolé, ne fonctionne toujours pas, même avec Metawal...
![image 833](https://cloud.githubusercontent.com/assets/6093597/5762003/79902c9e-9cdf-11e4-8cf3-b9972700f659.png)
![image 834](https://cloud.githubusercontent.com/assets/6093597/5762067/c71cd91c-9cdf-11e4-9abe-a5dc251b6bd9.png)

**Comment by fxprunayre** [comment]
Je viens de tester sur metawal3.test et ça joue:

![image](https://cloud.githubusercontent.com/assets/1701393/5762460/8246587e-9ce2-11e4-944a-358d5a5813e6.png)

Donc sans doute un problème de cache du navigateur ?

Par contre, @davinciagf y'a un pb de déploiement car le fichier sous github :
https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-develop/web-ui/src/main/resources/catalog/js/admin/HarvestController.js#L407
est différent de celui déployé en test spacebel
http://metawal.spacebel.be/geonetwork/catalog/js/admin/HarvestController.js
par contre il est ok là
http://metawal3.test.wallonie.be/geonetwork/catalog/js/admin/HarvestController.js

**Comment by vbombaerts** [comment]
J'ai testé sur un PC qui n'a jamais été connecté à Metawal et j'ai le même résultat.

**Comment by davinciagf** [comment]
Le problème se rencontre sous FX et IE (v11 testée) mais pas sous Chrome et Safari. 
Le problème provient de l'utilisation de la fonction ''$xml.find('Constraint')'' sous FX et IE. En effet sous ces deux navigateurs, le préfixe doit être défini afin de rechercher l'élement "ows:Constraints". Le préfixe n'est pas nécessaire sous Chrome et Safari.
Introduction de la fonction suivante sous FX et IE: 
''$xml.find("ows\:Constraint")''

**Comment by vbombaerts** [comment]
Testé avec une valeur de filtre et ça marche.
