### ISSUE TITLE
Créer un noeud spécifique INSPIRE 

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#203]
Le noeud moissonne Metawal pour récupérer les fiches "in scope" et effectue une transformation pour placer les infos qui sont dans MD_LegalConstraints>accessConstraints+otherConstraints dans useLimitation.
Mapping exact à définir.

**Comment by fxprunayre** [comment]
Dans un premier temps, le CSW existant est utilisé (http://metawal.spacebel.be/geonetwork/srv/fre/csw).

Pour la v4, à mettre en place :
- un noeud spécifique est créé "inspire" (cf. https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.x/web/src/main/webapp/WEB-INF/config-node/srv.xml)
- une base de données spécifique est créée (à voir si une base H2 préconfigurée n'est pas suffisant ?) 
- ce noeud moissone le noeud par défaut ("srv") via CSW avec une transformation XSL s'occupant de la transformation des fiches à la sauce INSPIRE
- Le service CSW INSPIRE devient alors http://metawal.spacebel.be/geonetwork/inspire/fre/csw

**Comment by fxprunayre** [comment]
Cf. #260
