### ISSUE TITLE
Valider toute les fiches de la sélection

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#208]
Dans les actions possible sur un groupe de fiches sélectionnées, ajouter l'option "valider" (silencieusement). Cela permet d'utiliser ensuite sur ces fiches le critère de recherche valide/non-valide.

Fonctionnalité à mieux circonscrire et développer.

![image 836](https://cloud.githubusercontent.com/assets/6093597/5777006/da2a3914-9d8e-11e4-920c-3664ef1e789d.png)

**Comment by fxprunayre** [comment]
cf. #263
