### ISSUE TITLE
CSW virtuel - impossible de mettre à jour les infos

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#209]
Impossible de mettre à jour les infos du CSW virtuel une fois qu'il est enregistré. On est obligé de le supprimer et d'en créer un autre.

![image 837](https://cloud.githubusercontent.com/assets/6093597/5778047/7bdfdb02-9d98-11e4-9b7a-201a02f26e76.png)

**Comment by fxprunayre** [comment]
Testé aves succès ici http://metawal4.test.wallonie.be/geonetwork/srv/fre/admin.console#/settings/csw-virtual
