### ISSUE TITLE
Mentions légales, Vie privée, Médiateur, Accessibilité : pointer vers Géoportail ?

### ISSUE THREAD

**Issue by metawal** [SPW-DIG/metawal-core-geonetwork#21]
Actuellement, les liens "Mentions légales, Vie privée, Médiateur, Accessibilité" pointent vers http://www.wallonie.be. Il faudrait les faire pointer soit vers les pages du Géoportail, soit vers des pages propres.

**Comment by davinciagf** [comment]
A pointer sur le géoportail pour l'instant
