### ISSUE TITLE
Calcul automatique des emprises géographiques à partir des mots-clés

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#210]
Lorsqu'on active la suggestion automatique, les emprises s'ajoutent deux fois.

**Comment by vbombaerts** [comment]
Le problème de la double emprise est résolu. Par contre, pour les mots-clés qui contiennent des caractères spéciaux "Commune d'Anhée", "Province de Liège", "Région wallonne", les emprises ne sont pas ajoutées.

**Comment by vbombaerts** [comment]
Pour le moment, les caractères spéciaux ont été retirés du thésaurus. Une solution plus propre est à trouver avec le thésaurus accentué

**Comment by fxprunayre** [comment]
Comme metionné auparavant, a priori cela a été corrigé dans GN (https://github.com/geonetwork/core-geonetwork/commit/ff74e87583982fcdaace750e14a5e55230b7cdc3). Testé si le pb s'observe en v4. Et voir s'il faut reporter en 3.x.
