### ISSUE TITLE
Editeur - Extent -Limitation à deux décimales des coordonnées 

### ISSUE THREAD

**Issue by davinciagf** [SPW-DIG/metawal-core-geonetwork#213]
La limitation à deux décimales des coordonnées des bounding box en WGS 84 n'est pas effective ==> arrondir à l'inférieur pour ouest et sud, au supérieur pour nord et est. Pour la RW, utiliser les valeurs
ouest : 2,75 / nord : 50,85 / est : 6,50 / sud : 49,45 (voir #172)

**Comment by vbombaerts** [comment]
Quand je choisis une commune puis que je clique sur dessiner l'emprise, il ne se passe rien de visible. Quand j'enregistre la fiche, la commune choisie a disparu. Elle n'est pas ajoutée aux mots-clés.
![2016-03-09 16_49_14-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/13640961/08481d30-e617-11e5-97eb-25ed89529128.png)

**Comment by davinciagf** [comment]
Non reproduit en local pour l'extent. 
Paramétrage de la carte afin de visualiser les extent au niveau de l'admin ou via requête sql lors de la mise à jour de la DB).

Ajout des CRS et de la configuration de la map.

List CRS
[{"code":"EPSG:2154","value":"+proj=lcc +lat_1=49 +lat_2=44 +lat_0=46.5 +lon_0=3 +x_0=700000 +y_0=6600000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"},{"code":"EPSG:31370","value":"+proj=lcc +lat_1=51.16666723333333 +lat_2=49.8333339 +lat_0=90 +lon_0=4.367486666666666 +x_0=150000.013 +y_0=5400088.438 +ellps=intl +towgs84=106.869,-52.2978,103.724,-0.33657,0.456955,-1.84218,1 +units=m +no_defs"},{"code":"EPSG:3812","value":"+proj=lcc +lat_1=49.83333333333334 +lat_2=51.16666666666666 +lat_0=50.797815 +lon_0=4.359215833333333 +x_0=649328 +y_0=665262 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"}]

Config map
{"viewerMap":"../../map/config-viewer.xml","listOfServices":{"wms":[],"wmts":[]},"useOSM":true,"context":"","layer":{"url":"http://www2.demis.nl/mapserver/wms.asp?","layers":"Countries","version":"1.1.1"},"projection":"EPSG:3857","projectionList":[{"code":"EPSG:4326","label":"WGS84 (EPSG:4326)"},{"code":"EPSG:3857","label":"Google mercator (EPSG:3857)"},{"code":"EPSG:31370","label":"Lambert belge 72 (EPSG:31370)"},{"code":"EPSG:3812","label":"Lambert belge 2008 (EPSG:3812)"}]}

**Comment by vbombaerts** [comment]
La carte fonctionne, l'emprise est arrondie à deux décimales quand on utilise les valeurs prédéfinies --> Youpie !
Par contre :
- La description textuelle de l'étendue n'est pas écrite (quand on choisit un territoire prédéfini, la valeur doit être inscrite dans la description de l'étendue)
  ![2016-04-22 16_32_28-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/14744651/efb2c6b8-08a7-11e6-8952-b1aa49a0c16f.png)
- quand on dessine l'étendue manuellement, les coordonnées ne sont pas arrondies à deux décimales.

**Comment by davinciagf** [comment]
Question: faut-il arrondir également au niveau de la MTD (xml) ou simplement au niveau de la vue?

**Comment by vbombaerts** [comment]
Au niveau du XML
