### ISSUE TITLE
Restaurer les caractères spéciaux du thésaurus des entités administratives

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#215]

**Comment by fxprunayre** [comment]
Après correction #210

**Comment by fxprunayre** [comment]
Cf https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.x/web/src/main/webapp/WEB-INF/data/config/codelist/external/thesauri/place/metawal-communes.rdf

**Comment by davinciagf** [comment]
Rajouter le fichier metawal-entites_administratives au niveau du Gihub.
Mettre à jour le thesaurus (ajout des accents supprimés au niveau de METAWAL3).

**Comment by davinciagf** [comment]
voir #292
