### ISSUE TITLE
Fichier d'aide en ligne accessible depuis Metawal

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#216]
- Héberger les fichiers d'aide à priori sur le géoportail (il faut qu'on puisse facilement recharger les mises à jour de l'aide - aide succincte, aide complète, mapping du fichier Excel)
- Ajouter un lien dans l'application vers la page d'aide de Metawal

**Comment by vbombaerts** [comment]
En ligne sur le géoportail - http://geoportail.wallonie.be/home/infrasig/informations-sur-les-metadonnees.html 
La redirection depuis Metawal est reportée sur la 3.2. L'aide doit encore être modifiée.

**Comment by davinciagf** [comment]
L'aide a été intégrée via un icone qui renvoie vers l'aide en ligne sur le géoportail.
![image](https://cloud.githubusercontent.com/assets/576292/7512263/1f3ae1ce-f4ac-11e4-966b-0ead4d6756c6.png)

**Comment by davinciagf** [comment]
Introduit également au niveau de MW4

**Comment by vbombaerts** [comment]
Je voyais plutôt ça dans le footer. On peut l'ajouter là aussi ?

**Comment by davinciagf** [comment]
L'aide est également disponible depuis le footer

![footer aide](https://cloud.githubusercontent.com/assets/576292/7771519/3f8af340-0098-11e5-9de7-cd08cb64fbf2.PNG)

**Comment by vbombaerts** [comment]
Par défaut l'ouvrir dans un nouvel onglet

**Comment by davinciagf** [comment]
Intégrer dans #18
