### ISSUE TITLE
Mettre le service CSW derrière géoservices

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#218]
Tous les services, y compris les virtuels.

**Comment by vbombaerts** [comment]
Rediriger les URL’s du CSW (http://metawal.wallonie.be/geonetwork/srv/fre/csw? + méthodes) vers l’URL http://geoservices.wallonie.be/csw?

**Comment by fxprunayre** [comment]
C'est à faire côté serveur web hébergeant geoservices.wallonie.be. Contacter l'administrateur du serveur web. Selon l'application, il y a en général des modules pour ça, mod_rewrite, mod_proxy pour Apache.

**Comment by vbombaerts** [comment]
A ajouter dans le ticket lors de la demande de mise en prod : liste des services à rediriger
http://metawal.wallonie.be/geonetwork/srv/fre/csw
http://metawal.wallonie.be/geonetwork/srv/fre/csw-inspire
http://metawal.wallonie.be/geonetwork/srv/fre/csw-opendata

**Comment by vbombaerts** [comment]
http://geoservices.wallonie.be/metawal/csw?request=GetCapabilities&service=CSW&acceptVersions=2.0.2
http://geoservices.wallonie.be/metawal/csw-inspire?request=GetCapabilities&service=CSW&acceptVersions=2.0.2
http://geoservices.wallonie.be/metawal/csw-opendata?request=GetCapabilities&service=CSW&acceptVersions=2.0.2
