### ISSUE TITLE
Edition / Permettre le chargement de plusieurs vignettes

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#219]
Rétablir la fonctionnalité qui a été perdue dans la mise à jour 3.1

**Comment by vbombaerts** [comment]
C'est pour le moment possible en ajoutant un champ aperçu directement dans la fiche, puis en passant par le chargeur du panneau de droite. Il faudrait que ce soit directement accessible par le panneau de droite. Pour ne pas retarder le déploiement du correctif 3.1.2, je passe le ticket sur la 3.2.

**Comment by fxprunayre** [comment]
Problème pour les thumbnails via upload
- Java https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.x/core/src/main/java/org/fao/geonet/services/thumbnail/Set.java#L100
- XSL https://github.com/SPW-DIG/iso19115-3/blob/d83a41e4d4ad09ec42b1844cf49df0023d78f7db/src/main/plugin/iso19115-3/set-thumbnail.xsl

**Comment by vbombaerts** [comment]
Maintenant possible d'ajouter 2 imagettes, mais
- elles ne s'affichent pas
  ![2016-03-10 16_39_13-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/13674656/a576bb1c-e6de-11e5-95eb-4b6efabfd733.png)
- Pas possible de les charger par le bouton du formulaire (aucune action quand on clique)
  ![2016-03-10 16_39_47-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/13674678/b9f341c8-e6de-11e5-9cfb-3c989d0ebe28.png)

**Comment by davinciagf** [comment]
Lié à l'adresse qui se réfère à metawal.wallonie.be

http://metawal.wallonie.be/geonetwork/srv/api/metadata/ba5b82e7-18a1-4701-8acc-10e9b58a23b9/resources/....

A modifier

**Comment by vbombaerts** [comment]
Ce sont des images que j'ai chargées directement dans MW4...

**Comment by davinciagf** [comment]
A modifier au niveau code je voulais dire (vérifier la définition de la racine de l'url).
Problème qui se reproduit pour les download de fichier (rérérence sur metawal.wallonie.be et non sur l'instance en cours)

**Comment by davinciagf** [comment]
Les adresses seront maintnenat correctement enregistrées (pas les anciennes), il faut recharger les liens car modification au niveau de l'admin de la référence à l'hôte qui était erronnée (mais correcte pour metawal.wallonie.be).
![capture](https://cloud.githubusercontent.com/assets/576292/13700601/2674718e-e782-11e5-8675-d039d349e5a5.JPG)
