### ISSUE TITLE
Edition / Erreur lors de l'ouverture d'une fiche - undeclared prefix xsi

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#220]
Description du problème

```
l’AGDP concernant les parcelles cadastrales et les limites administratives.
1.       Je n’arrive pas à ajouter le point de moissonnage dans Metawal

2.       Comme il avait déjà été défini dans l’instance de test, j’ai récupéré les fiches et je les ai importées dans Metawal.

3.       Et là, impossible de les éditer : 
XPathException : Undeclared prefix xsi
```

Version affectée: 3.1 actuellement en prod

Non reproductible en recette.

**Comment by fxprunayre** [comment]
Problème reproduit en local & corrigé.

2 commentaires sur la fiche en question "Parcelles cadastrales CadGIS":
1) Utilisation des XLinks

La fiche contient un XLink pour associer un catalogue d'attributs :

```
<gmd:featureCatalogueCitation xmlns:xlink="http://www.w3.org/1999/xlink" uuidref="605be18e-b38c-4b9d-a509-d2d757fe3e20" xlink:href="http://10.11.8.119:8080/geonetwork/srv/en/csw?service=CSW&request=GetRecordById&version=2.0.2&outputSchema=http://www.isotc211.org/2005/gmd&elementSetName=full&id=605be18e-b38c-4b9d-a509-d2d757fe3e20"/>
```

Je pensais dans un premier temps que c'était l'origine du problème mais non.
D'une part l'URL 10.11.8.119 est incaccessible donc la résolution des XLinks ne fait rien dans ce cas.
D'autre part featureCatalogueCitation fait partie des exceptions pour la résolution (cf. https://github.com/geonetwork/core-geonetwork/blob/develop/core/src/main/java/jeeves/xlink/Processor.java#L395)

Cependant en recette, la résolution des XLinks était activée et pas en prod - ca peut être bien d'avoir la même chose des 2 côtés.

2) Le problème d'attributs xsi:*

Le problème est en lien avec la partie de la métadonnée relative aux thèmes INSPIRE en mode multilingue. J'ai pas vérifié en détail, mais le pb vient de cette section et de l'initialisation du widget de sélection des mots clés quand le thésaurus des thèmes est dispo.

Le problème : le namespace XSI n'était pas déclaré dans un XSL qui faisait une copie de tous les attributs d'un élément sans ce soucier de leur préfix.

En v4, a priori, pas de problème, par contre la saisie multilingue des mots clés n'est pas supportée. Ca se présente comme ça :

![image](https://cloud.githubusercontent.com/assets/1701393/6172102/1506e8e2-b2df-11e4-9103-f5934f6be484.png)

et ne perd pas d'information - ce qui est déjà bien !

Du coup:
- à voir pour quoi non reproduit en test
- et redéployer le correctif

**Comment by vbombaerts** [comment]
Fiche concernée : http://metawal.wallonie.be/geonetwork/srv/fre/search?uuid=ca230c6e-379d-41ab-8c68-8d29ce02bb24 
http://metawal3.valid.wallonie.be/geonetwork/srv/fre/search?uuid=ca230c6e-379d-41ab-8c68-8d29ce02bb24
