### ISSUE TITLE
Edition / Wizard

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#222]
Une idée qu'il serait utile de creuser. 
Pour le moment, quand on édite une nouvelle fiche de métadonnées, on doit choisir un template prédéfini.
Or, il existe beaucoup de cas de figures : type de ressource, INSPIRE ou pas, conditions d'accès et d'utilisation, distributeur, etc. Si on veut couvrir une majorité de ces cas de figure pour aider l'utilisateur, on doit déployer beaucoup de templates, qu'il faut ensuite maintenir. Pour l'utilisateur ce n'est pas facile de choisir le bon template.
L'idée serait de combiner un wizard à des sous-template qui permettraient de construire un template sur mesure. Je pense que l'idée du wizard n'est pas neuve. Par contre celle des sous-template l'est peut-être.
L'idée globale serait de poser des questions au rédacteur avant qu'il ne commence à éditer sa fiche. Les réponses serviraient à inclure ou pas des sous-template dans le template final. L'avantage est que le gestionnaire du catalogue devra maintenir moins de template et que le rédacteur sera guidé par les questions dans le choix/la construction du bon template.

**Comment by fxprunayre** [comment]
Actuellement le choix est:
- type de ressource + un modèle

Evolution:
- ajouter des choix intermédiaires à définir
