### ISSUE TITLE
Dupliquer une fiche ne change pas son identifiant

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#223]
Envir. : Metawal 3.1.1 en prod

Quand on duplique une fiche, un nouvel identifiant interne est créé, mais il n'est pas reporté dans la fiche xml au niveau du fileidentifier. Les documents annexes sont chargés avec l'identifiant interne en référence, mais l'adresse des fichiers dans le xml utilise l'identifiant de la fiche (qui n'a pas changé)
Le problème se manifeste par l'inacessibilité des documents annexes, comme par exemple la vignette.

![image 849](https://cloud.githubusercontent.com/assets/6093597/6284985/fe8cf584-b8f6-11e4-8e2a-f1fbd2dd53d3.png)

![image 850](https://cloud.githubusercontent.com/assets/6093597/6284997/2d93e748-b8f7-11e4-9f3a-9eee9e6174c6.png)

**Comment by fxprunayre** [comment]
> Envir. : Metawal 3.1.1 en prod
> Quand on duplique une fiche, un nouvel identifiant interne est créé, mais il n'est pas reporté dans la fiche xml au niveau du fileidentifier.

En test ce n'est pas le cas ? A priori, l'identifiant de la fiche dupliquée n'est pas le même que la source - je viens de tester.

> Les documents annexes sont chargés avec l'identifiant interne en référence, mais l'adresse des fichiers dans le xml utilise l'identifiant de la fiche (qui n'a pas changé)

Pour ce point, ce n'est pas forcément un bug, il duplique la fiche en l'état et en créé une nouvelle en changeant son identifiant. Le fait de changer les identifiants dans les URL eg. docs ajoutés ou les imagettes ne donnera pas de lien valide pour autant donc ce n'est pas une solution en tant que tel de mettre à jour les identifiants partout. Une option éventuelle serait de supprimer certaines informations lors de la duplication : URL des imagettes, URL des docs associés.

**Comment by vbombaerts** [comment]
En effet, le problème ne se présente pas en env. de test. mais est bien présent en prod.

Pour les docs associés, je parle des nouveaux doc que l'on charge, pas ceux qui existaient déjà avec la fiche originale.

**Comment by fxprunayre** [comment]
> Pour les docs associés, je parle des nouveaux doc que l'on charge, pas ceux qui existaient déjà avec la fiche originale.

Ok je comprends du coup le pb est lié au non changement de l'identifiant lors de la copie. @davinciagf  une idée de pourquoi la prod et test ne se comportent pas de la même manière ?

**Comment by vbombaerts** [comment]
voir un exemple ici http://metawal.wallonie.be/geonetwork/srv/fre/search?uuid=019b6a5a-e513-478d-8155-748001a3ede4 (non publié)

**Comment by vbombaerts** [comment]
Contournement en attendant une solution :
1. Dupliquer la fiche et changer le nom de la ressource (gmd:title). Enregistrer, fermer.
2. Ouvrir la fiche en visualisation. Dans le coin supérieur droit, cliquer sur l'icone "lien". L'uuid donné dans l'URL est le bon. Le copier
3. Ouvrir la fiche en édition, afficher le XML. Remplacer l'identifiant existant par le bon identifiant dans la balise gmd:identifier
4. Si nécessaire, corriger également l'adresse des vignettes (gmd:browsegraphic) et documents annexes chargés dans Metawal (<CI_onlineresource>). Effectuer pour cela une recherche sur le mauvais identifiant de la fiche.

**Comment by vbombaerts** [comment]
Un nouvel identifiant est créé pour la fiche mais l'info n'est pas mise à jour dans le xml
Ex : http://metawal3.valid.wallonie.be/geonetwork/srv/fre/search?uuid=c4a3d4e3-2963-4ba2-bdb9-0ca20ce124ce

**Comment by fxprunayre** [comment]
![image](https://cloud.githubusercontent.com/assets/1701393/7351182/0be2c77c-ed04-11e4-9bf7-5ab73a85c3d0.png)

Never disable ! We got it :)

**Comment by fxprunayre** [comment]
Je rends le message un peu plus inquiétant  ... https://github.com/geonetwork/core-geonetwork/commit/4d6426b2e91f64297a0380d2f6289700a82efae4

![image](https://cloud.githubusercontent.com/assets/1701393/7351437/740cf4ca-ed05-11e4-925a-4f6fdc727aef.png)

**Comment by vbombaerts** [comment]
Merci !
