### ISSUE TITLE
Mise à jour automatique de la date d'édition de la fiche de métadonnées ne se fait pas

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#224]
Détecté en prod, version 3.1.1
Pas de problème en test.

Je ne sais pas si c'est lié au problème de la mise à jour des id dans le XML. On a travaillé toute la journée sur les fiches "Relief de la Wallonie" et leur date de mise à jour est le 30/01

**Comment by fxprunayre** [comment]
On va mettre la test en prod non ? :)

**Comment by vbombaerts** [comment]
Pffffff ! ;-)

**Comment by vbombaerts** [comment]
La fiche remonte dans les dernières publications, mais le xml ne se met pas à jour.
Ex : http://metawal3.valid.wallonie.be/geonetwork/srv/fre/search?uuid=0e876367-6b73-447b-979d-70b31f2ad3ba

**Comment by davinciagf** [comment]
Voir  #223
