### ISSUE TITLE
Finalisation des traductions

### ISSUE THREAD

**Issue by davinciagf** [SPW-DIG/metawal-core-geonetwork#227]
Certains éléments sont encore manquants:
Example: 

```
mrd:MD_StandardOrderProcess, srv:ServiceStandard
mdb:resourceScope
mdb:name
mac:*
mrd:distributorContact
mrd:distributorFormat
mrd:distributionForm
mrd:distributionTransport
mrd:distributionOrder
dateTypeCode: inForce, deprecated
résolution - non traduit en français
mrc:...MI_coverage
gfc:identifier
gfc:desigantion
gfc:inheritenceRelated
mrc:MD_featureCatalogue
mrc:featureCatalogue
mdb:metadataStandard
```

Utilisation spécifique de la ressource: identified issues

**Comment by fxprunayre** [comment]
TODO:

```
gn-fn-metadata:getLabel | missing translation in schema iso19115-3 for mdq:value.
gn-fn-metadata:getLabel | missing translation in schema iso19115-3 for mdq:value.
gn-fn-metadata:getLabel | missing translation in schema iso19115-3 for mdq:valueUnit.
gn-fn-metadata:getLabel | missing translation in schema iso19115-3 for gml:BaseUnit.
gn-fn-metadata:getLabel | missing translation in schema iso19115-3 for gml:quantityType.
gn-fn-metadata:getLabel | missing translation in schema iso19115-3 for gml:quantityTypeReference.
gn-fn-metadata:getLabel | missing translation in schema iso19115-3 for gml:catalogSymbol.
gn-fn-metadata:getLabel | missing translation in schema iso19115-3 for gml:unitsSystem.
gn-fn-metadata:getLabel | missing translation in schema iso19115-3 for mdq:valueRecordType.
gn-fn-metadata:getLabel | missing translation in schema iso19115-3 for mdq:value.
gn-fn-metadata:getLabel | missing translation in schema iso19115-3 for mdq:value.
gn-fn-metadata:getLabel | missing translation in schema iso19115-3 for mdq:valueUnit.
gn-fn-metadata:getLabel | missing translation in schema iso19115-3 for gml:BaseUnit.
gn-fn-metadata:getLabel | missing translation in schema iso19115-3 for gml:quantityType.
gn-fn-metadata:getLabel | missing translation in schema iso19115-3 for gml:quantityTypeReference.
gn-fn-metadata:getLabel | missing translation in schema iso19115-3 for gml:catalogSymbol.
gn-fn-metadata:getLabel | missing translation in schema iso19115-3 for gml:unitsSystem.
gn-fn-metadata:getLabel | missing translation in schema iso19115-3 for mdq:valueRecordType.
DQ_EvaluationMethodTypeCode

```

**Comment by fxprunayre** [comment]
Fait pour 

```
gn-fn-metadata:getLabel | missing translation in schema iso19115-3 for mdq:value.
gn-fn-metadata:getLabel | missing translation in schema iso19115-3 for mdq:value.
gn-fn-metadata:getLabel | missing translation in schema iso19115-3 for mdq:valueUnit.
```

**Comment by fxprunayre** [comment]
Some more https://github.com/metadata101/iso19115-3/commit/3a7fd4b1e458583ea1a5d6c591fc0c0c0f05709f

**Comment by vbombaerts** [comment]
coquille : responsibilité
![2015-08-31 15_54_01-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/9580266/af30c65c-4ff8-11e5-8b0f-2e73097eed9a.png)

**Comment by fxprunayre** [comment]
> coquille : responsibilité

https://github.com/metadata101/iso19115-3/commit/fe3df5c0edaf4750296c101a8eb60f921092cce5

**Comment by vbombaerts** [comment]
En consultation, certaines options de vue ne sont pas traduites

![2016-02-03 09_21_15-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/12776605/a1829632-ca57-11e5-9361-9a99bafaf37f.png)

Sur la page de recherche, certaines facettes ne sont pas correctement libellées
![2016-02-03 09_25_50-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/12776658/2f8e2ad6-ca58-11e5-8e71-28e0dc3a5a36.png)

Dans l'admin, certains paramètres ne sont pas traduits (mais ça, OSEF :-) )
![2016-02-03 12_06_30-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/12780711/c56395ca-ca6f-11e5-800e-3d5a758a2791.png)
![2016-02-03 12_07_08-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/12780713/c6dd3f50-ca6f-11e5-8269-98a47aa8a22a.png)
![2016-02-03 12_07_57-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/12780715/c82e7950-ca6f-11e5-907b-5f7b3fbf377c.png)
![2016-02-03 12_08_21-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/12780716/c9913bfc-ca6f-11e5-8a15-ee0eb024ac18.png)
![2016-02-03 12_08_48-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/12780717/cb08ee9e-ca6f-11e5-8288-e84ecf505ce3.png)
![2016-02-03 12_09_15-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/12780718/cbfa8876-ca6f-11e5-987e-5cb274bebe9e.png)
![2016-02-03 12_10_04-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/12780719/cd6c845c-ca6f-11e5-83cd-6badaf6cf7b2.png)
![2016-02-03 12_10_46-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/12780721/cebb6bfc-ca6f-11e5-9b47-6b4c13f2133b.png)
![2016-02-03 12_11_29-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/12780722/cfe9ff0c-ca6f-11e5-882d-fa65653d2155.png)
![2016-02-03 12_12_23-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/12780725/d13052da-ca6f-11e5-9922-514b3dcd87fb.png)
![2016-02-03 12_12_49-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/12780726/d27b62c4-ca6f-11e5-800b-8fdcdc652dba.png)
![2016-02-03 12_13_22-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/12780728/d3fbf79e-ca6f-11e5-9f93-ba65e247a7e1.png)
![2016-02-03 12_14_08-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/12780729/d534412a-ca6f-11e5-9113-c9ffffb1c618.png)
![2016-02-03 12_14_30-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/12780731/d685aff0-ca6f-11e5-9ae2-fa048e34ed1d.png)

**Comment by vbombaerts** [comment]
Sur l'interface de recherche, les thèmes ISO ne sont pas traduits dans le tiptool des fiches
![2016-02-03 15_24_40-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/12784978/78f86312-ca8a-11e5-90a9-c9758ea37c54.png)

**Comment by fxprunayre** [comment]
Pour l'interface à faire dans https://www.transifex.com/geonetwork/core-geonetwork/translate
Pour les catégories, a priori plutôt dans l'indexation

**Comment by fxprunayre** [comment]
> Sur l'interface de recherche, les thèmes ISO ne sont pas traduits dans le tiptool des fiches

https://github.com/geonetwork/core-geonetwork/issues/1428

A déployer et tester.

**Comment by fxprunayre** [comment]
Quelques corrections & ajouts pour les services https://github.com/SPW-DIG/iso19115-3/commits/develop

**Comment by vbombaerts** [comment]
![2016-04-22 16_39_55-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/14745692/b94852aa-08ac-11e6-9408-0c3b6f9ee508.png)

**Comment by davinciagf** [comment]
Ajouter au niveau de en-search.json.
PR vers GN (https://github.com/geonetwork/core-geonetwork/pull/1602) + Transifex

**Comment by vbombaerts** [comment]
Message de récup du mot de passe pour un utilisateur LDAP : traduction manquante.

![2017-02-22 16_17_42-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/23217802/bea00edc-f91a-11e6-8fc9-bd82411427b7.png)

**Comment by vbombaerts** [comment]
Pas résolu mais on passera par une autre interface d'authentification dans la suite du projet, donc on laisse tomber.
