### ISSUE TITLE
Header : le coq doit pointer vers la page d'accueil de Metawal

### ISSUE THREAD

**Issue by metawal** [SPW-DIG/metawal-core-geonetwork#23]
...et pas vers la page d'accueil de http://www.wallonie.be/

**Comment by fxprunayre** [comment]
See https://github.com/spacebelGIS/metawal-core-geonetwork/commit/bcc0e4d59625867873e61ee2b725468d8a0e88bc

**Comment by vbombaerts** [comment]
Si nécessaire, le coq sans l'inscription Wallonie dessous peut être utilisé pour gagner quelques pixels en hauteur. Voir coq du site géoportail.
