### ISSUE TITLE
Fiche / Modèle de données / Reprise de l'existant

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#232]
Reprise manuelle des fiches existantes utilisant l'extension MW ?
A priori peu de fiche concernée.
- migration 19139.rw > 191139 / En lien avec #247 : a réinjecter après 
- migration 19139 > 19115-3 / mise à jour manuelle des fiches

**Comment by vbombaerts** [comment]
A ma connaissance juste les fiches géologie, donc oui, à la main.

**Comment by vbombaerts** [comment]
Rien trouvé dans les fiches géologie. Pas de migration nécessaire.
