### ISSUE TITLE
Ressource associée / Guide de saisie

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#233]
Préciser l'usage des agrégats pour les associations:
- série temporelle (series)
- série spatiale (series)
- collection thématique (isComposedOf)
- nouvelle version (revisionOf)

Cf. gdoc

**Comment by vbombaerts** [comment]
Swisstopo utilise largerWorkCitation pour les collections de données.
Faut-il aussi utiliser un lien d'agrégation pour les séries temporelles et spatiales, si les membres sont décrits ?

**Comment by fxprunayre** [comment]
A rediscuter

**Comment by vbombaerts** [comment]
cf tableau avec les relations entre les ressources
