### ISSUE TITLE
Fiche / Données wallonne

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#235]
Une “données officielles wallonne” est caractérisée par un mot clé “à préciser” + éventuellement une référence d’un texte légal
préciser la définition - source authentique, légale

**Comment by fxprunayre** [comment]
En lien avec #253

**Comment by vbombaerts** [comment]
Le ou les mots-clés "à préciser" iront dans le thésaurus InfraSIG cf #290 
Le texte légal peut être référencé dans additionalDocumentation de la section Identification
