### ISSUE TITLE
GéoPortail / Evaluation

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#236]
## Noter une fiche :

Service à utiliser 

```
http://localhost:8080/geonetwork/srv/fre/md.rate?_content_type=json&uuid=49373603-418d-451b-afb5-7badc8783a43&rating=2
```
## Récupérer la note

Via CSW, en utilisant results_with_summary

```
<?xml version="1.0"?>
<csw:GetRecords xmlns:csw="http://www.opengis.net/cat/csw/2.0.2"
    xmlns:gmd="http://www.isotc211.org/2005/gmd" service="CSW" version="2.0.2"
    resultType="results_with_summary">
    <csw:Query typeNames="gmd:MD_Metadata">
        <csw:Constraint version="1.1.0">
            <Filter xmlns="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml"/>
        </csw:Constraint>
    </csw:Query>
</csw:GetRecords>

```
## Evolutions

A faire:

En premier :
- Service de notation
  - Ajouter l'IP en paramètre (pour qu'une application tierce puisse noter)
- Service de récupération des notes 
  - Ajouter un service retournant pour une fiche les notes / nombre de note

Ensuite :
- Service de récupération des notes 
  - Ajouter la date de dernière notation dans metadatarating (db migration)
  - Paramètres
  - id(s)/uuid(s)
  - from/to
  - ip(s)

Exemple de réponse:

```
<metadataRating from="" to="">
  <metadata uuid="" nbOfEvaluation="30" firstEvaluation="" lastEvaluation="">
    <rate value="1" count="10"/>
    <rate value="2" count="10"/>
    <rate value="3" count="10"/>
    <rate value="4" count="0"/>
    <rate value="5" count="0"/>
 </metadata>
</metadataRating>
```

**Comment by vbombaerts** [comment]
PLus nécessaire car GP interfacé avec l'API.
