### ISSUE TITLE
Automatisation des processus de chargement des données dans InfraSIG avec FME

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#237]
"Une étape du processus est de mettre à jour la fiche de métadonnées (date de révision de la donnée et date de mise à jour de la fiche). Pouvez-vous aiguiller ?"

**Comment by fxprunayre** [comment]
2 options :
1) utiliser l'API de l'éditeur de métadonnée
2) utiliser le CSW-T

L'option 1 nécessite d'initialiser une session d'édition puis de manipuler la fiche en faisant attention à la version. Elle permet de faire un grand nombre de types de mise à jour (eg. doc XML, par ref, par xpath, ajout/suppression) mais reste assez complexe à utiliser dans une appli tierce.

L'option 2 a l'avantage de pouvoir faire en une requête :
- l'insert https://github.com/geonetwork/core-geonetwork/blob/develop/web/src/main/webapp/xml/csw/test/csw-TransactionInsert.xml
- l'update 
  - complet https://github.com/geonetwork/core-geonetwork/blob/develop/web/src/main/webapp/xml/csw/test/csw-TransactionUpdate.xml
  - par propriété https://github.com/geonetwork/core-geonetwork/blob/develop/web/src/main/webapp/xml/csw/test/csw-TransactionUpdateProperties.xml
  - par XPath (extension CSW spécifique GN) https://github.com/geonetwork/core-geonetwork/blob/develop/web/src/main/webapp/xml/csw/test/csw-TransactionUpdatePropertiesWithElement.xml
- la suppression https://github.com/geonetwork/core-geonetwork/blob/develop/web/src/main/webapp/xml/csw/test/csw-TransactionDelete.xml

Dans les 2 cas, il faut s'authentifier. Le plus simple étant pas Basic Authentication avec un compte du catalogue (ayant les droits d'édition sur les fiches).

J'opterai pour l'option 2 (Utilisée par Talend dans https://github.com/talend-spatial/workspace-metadata-crawler).

**Comment by vbombaerts** [comment]
Champs à mettre à jour :
- Date de mise à jour de la donnée : 

``` xml
*/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:citation/gmd:CI_Citation/gmd:date/gmd:CI_Date[gmd:dateType/gmd:CI_DateTypeCode/@codeListValue="revision"]/gmd:date/gco:Date
```
- Date de mise à jour de la métadonnée : 

``` xml
*/gmd:dateStamp/gco:DateTime
```
