### ISSUE TITLE
Ajout automatique conformité INSPIRE - modifications mineures

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#238]
- Le texte doit être ajouté dans la langue de la métadonnée.
- Pour passer la validateur, le texte doit être exactement celui qui se trouve dans http://inspire.ec.europa.eu/schemas/common/1.0/enums/
- La date doit aussi être adaptée

A part ça, c'est sacrément pratique...

**Comment by fxprunayre** [comment]
Evolutions. Cf. https://github.com/geonetwork/core-geonetwork/blob/develop/schemas/iso19139/src/main/plugin/iso19139/process/inspire-add-conformity.xsl#L27 à améliorer pour le multilingue et faire en ISO19115-3 ?

**Comment by vbombaerts** [comment]
Pour le texte et la date : 
A la ligne https://github.com/geonetwork/core-geonetwork/blob/develop/schemas/iso19139/src/main/plugin/iso19139/process/inspire-add-conformity.xsl#L36 "No 1089/2010" doit devenir "N o 1089/2010" et date="2010-10-23" doit devenir date="2010-12-08" pour passer le validateur.

**Comment by fxprunayre** [comment]
GN ref https://github.com/geonetwork/core-geonetwork/issues/992

**Comment by fxprunayre** [comment]
Pour MW3.2 https://github.com/SPW-DIG/metawal-core-geonetwork/commit/5f455fc8d90219e8ec7796a8ad21c15df85ad288

Pour MW4 - appliqué dans GN3.0.x mais ne sera disponible que pour iso19139. Pour ISO19115-3, il faudra discuter des processus à migrer.

**Comment by vbombaerts** [comment]
Pour les fiches en ISO 19139 : 
- quand on ajoute des mots-clés du thésaurus INSPIRE --> pas de suggestion d'ajouter la section conformité
- quand on ajoute manuellement les éléments de qualité pour renseigner la conformité INSPIRE --> pas de liste de suggestions

Pour une fiche ISO 19139.rw :
- suggestion OK quand ajout de mot-clé INSPIRE
- liste déroulante présente dans la section qualité, mais les suggestions sont en anglais et pas en français. ==> évaluation de conformité ne passe pas le validateur INSPIRE parce qu'elle doit être dans la langue de la MD

**Comment by fxprunayre** [comment]
Pour iso191319 
- activer la suggestion https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-develop/web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/suggest.xsl#L16
- liste des rapports qualités à vérifier https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-develop/web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/loc/fre/labels.xml#L3336

ISO19139.rw & iso19139, traduire Regulation:
- https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-develop/web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139.rw/loc/fre/labels.xml#L3336
- vérifier dans la suggestion https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-develop/web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139/process/inspire-add-conformity.xsl#L134 métadonnée en français = libellé en fr

ISO19115-3 : 
- ajouter le processus https://github.com/metadata101/iso19115-3/commit/d83a41e4d4ad09ec42b1844cf49df0023d78f7db
- ajouter les suggestions https://github.com/metadata101/iso19115-3/commit/73fbd3ea1800ca9f6695cdfa7b343caba5afcac5

**Comment by fxprunayre** [comment]
On aura besoin d'un fork de https://github.com/metadata101/iso19115-3 dans SPW pour activer les suggestions INSPIRE qui ne seront pas actives par défaut. Cf. https://github.com/SPW-DIG/iso19115-3

**Comment by vbombaerts** [comment]
Suggestions et liste déroulante revenues pour ISO 19139 -==> OK

Reste à corriger : tous les textes doivent être ajoutés dans la langue de la métadonnées (en français) par la suggestion (actuellement en anglais) :
- nom de la spécification : "Règlement (UE)..."
- explication : "Voir la spécification référencée"

**Comment by vbombaerts** [comment]
Désolé, ne passe toujours pas...

**Comment by davinciagf** [comment]
Vérifier la balise 
ISO19139 (template preferred)
gmd:language
    <gmd:LanguageCode codeList="http://www.loc.gov/standards/iso639-2/" codeListValue="eng"/>
/gmd:language

ISO19139 (template pour documenter)
gmd:language
    gco:CharacterStringfre/gco:CharacterString
/gmd:language

**Comment by vbombaerts** [comment]
Youpi ! Ca marche !

Par contre, ici, je vois qu'il est indiqué 'erro'. Est-ce une erreur ?
https://github.com/SPW-DIG/metawal-core-geonetwork/commit/cef502b90da1ec82b2f19b3f81fafcfc5ec43b9f#diff-22a934ff9f2440ed900651156041f238R142
