### ISSUE TITLE
parenthèses vides après les mots clés GEMET

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#24]

**Comment by fxprunayre** [comment]
A préciser : quelle fiche ?. Je ferme en attendant.

**Comment by vbombaerts** [comment]
Dans la fiche en consultation
Quand on n'a pas précisé le type de mot-clé.
Proposition : supprimer les parenthèses quand le type de mot-clé n'est pas précisé 
![image 649](https://f.cloud.github.com/assets/6093597/1792010/0047b01c-6998-11e3-9d7e-c71793632d4c.png)

**Comment by fxprunayre** [comment]
En l'occurence le type est défini mais vide
http://metawal.spacebel.be/geonetwork/srv/fre/search?uuid=5bb1c85c-abe1-46b3-9af6-489ab95cd0cb

```
<gmd:MD_Keywords>
<gmd:keyword>
<gco:CharacterString>ressources</gco:CharacterString>
</gmd:keyword>
<gmd:type>
<gmd:MD_KeywordTypeCode codeList="http://www.isotc211.org/2005/resources/codeList.xml#MD_KeywordTypeCode" codeListValue=""/>
</gmd:type>
```

Corrigé https://github.com/spacebelGIS/metawal-core-geonetwork/commit/8f62647b249de868893252167121314303acbcb2 (appliqué à GN).

A redéployer.
