### ISSUE TITLE
Annuaires - comportement des jumelles

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#240]
Le comportement des jumelles par défaut est d'ajouter un nouveau bloc (nouveau contact par ex). Il y a un recouvrement par rapport au bouton +
On pourrait aussi imaginer que les jumelles remplacent les informations du bloc auquel elles sont liées. 

A discuter.

**Comment by fxprunayre** [comment]
A tester dans le cadre de #253
