### ISSUE TITLE
Ajout Format de distribution

### ISSUE THREAD

**Issue by gdetry** [SPW-DIG/metawal-core-geonetwork#242]
Ajout des formats GeoJson et Json dans la liste déroulante des formats de distribution

**Comment by vbombaerts** [comment]
A indiquer selon convention :

| Présentation dans la liste | Encodage |
| --- | --- |
| JavaScript Object Notation (.json) | json (JavaScript Object Notation) |
| GeoJSON (.geojson) | geojson (GeoJSON) |

Insérer le GeoJSON dans la première partie (format géographique courant) et le JSON dans la deuxième (format moins courant)

**Comment by vbombaerts** [comment]
Erreur dans mes instructions. Voir mail envoyé à Arnaud.

**Comment by vbombaerts** [comment]
Ce n'est pas la liste de formats communiquée par mail qui apparait.
![2015-08-21 12_23_47-metawal - test _ test afac - iso 19139 dataset](https://cloud.githubusercontent.com/assets/6093597/9406308/aef10efa-47ff-11e5-8eea-8effa9beaf61.png)

**Comment by davinciagf** [comment]
Erreur de lecture du fichier labels.xml car erreur dans ce dernier (voir fcaff10)
