### ISSUE TITLE
Absence icone Jumelle pour import distributeur

### ISSUE THREAD

**Issue by gdetry** [SPW-DIG/metawal-core-geonetwork#243]
Lors de la création d'une nouvelle fiche de métadonnées pour un geodonnée, l'icône "jumelle", pour importer un contact depuis le thesaurus, est absente sous la section "Information sur la distribution" > distributeur

**Comment by vbombaerts** [comment]
Tu peux donner un lien vers une fiche où tu observes ce comportement STP ?

**Comment by gdetry** [comment]
Lors de la CREATION d'une NOUVELLE FICHE - Modèle de données vecteur - Schéma iso19139
- Comportement normal : dans la section "Identification" --> présence de l'icône Jumelle dans la dernière section de personnes liées à la ressource. Possibilité d'accès au thésaurus

![ok_1](https://cloud.githubusercontent.com/assets/12267969/8233080/8d1072ce-15d4-11e5-9e24-cdc250d50832.png)
- Comportement anormal : dans la section "distribution" --> pas d'icône jumelle et pas de possibilité d'accès au thésaurus

![pas_ok_1](https://cloud.githubusercontent.com/assets/12267969/8233089/ab07daba-15d4-11e5-80f2-6d69d683c27b.png)

Même comportement observé avec le dernier template de géodonnées [06/05/2015 - Template pour documenter...] - Iso19139

Lors de L'EDITION d'une FICHE EXISTANTE se trouvant dans un schéma Iso19139-RW (cas de la majorité des géodonnées dans Metawal), l'icône jumelle n'apparait pas - thesaurus basé sur Iso19139. Implique une migration des fiches de RW --> Iso19139.

**Comment by fxprunayre** [comment]
A priori bien configuré ici https://github.com/geonetwork/core-geonetwork/blob/develop/web/src/main/webapp/WEB-INF/config-gui.xml#L230

Ensuite https://github.com/geonetwork/core-geonetwork/blob/develop/web/src/main/webapp/xsl/metadata/layout.xsl#L722
