### ISSUE TITLE
Référence du nom d'un GeoService WMS dans fiche geodonnée

### ISSUE THREAD

**Issue by gdetry** [SPW-DIG/metawal-core-geonetwork#245]
A la suite du référencement d'une ressource en ligne de protocole OGC_WMS dans une fiche de géodonnée, on observe qu'en prévisualisation de cette fiche, la description renseignée pour le geoservice apparait au lieu de son nom. 

Les essais suivants ont été effectués 
- Référencement d'une ressource en ligne sans protocole > le nom du geoservice apparait (comportement OK - cf. PJ cas 1)
- Referencement d'une ressource en ligne avec mention du protocole ESRI-REST > le nom du geoservice apparait et tooltip reprenant la description est actif lors du survol de la souris (comportement OK - cf. PJ cas 2)
- Referencement d'une ressource en ligne avec mention du protocole OGC-WMS > la description du geoservice apparait et il n'y a aucun tooltip actif lors du survol de la souris (mauvais comportement - cf. PJ cas 3)

Par ailleurs, l'icone "Map" informant de l'existence du geoservice n'apparait pas dans le cas de la mention du protocole ESRI-Rest

![1_ref_geoservice_ss_protocole](https://cloud.githubusercontent.com/assets/12267969/7836275/56cfd0b2-047f-11e5-9f82-956d34626c9a.png)
![2_ref_geoservice_prot_esri](https://cloud.githubusercontent.com/assets/12267969/7836276/56d1fac2-047f-11e5-9abf-7dc451f156c8.png)
![3_ref_geoservice_prot_wms](https://cloud.githubusercontent.com/assets/12267969/7836277/56d5acb2-047f-11e5-9bd1-40596c57d7be.png)

**Comment by vbombaerts** [comment]
L'icone map n'est pas nécessaire. Qu'apporte-t-elle ?

**Comment by vbombaerts** [comment]
OK pour le tooltip. KO pour le nom. Dans la vue simplifiée, c'est le nom du WMS qui doit apparaitre et pas sa description (description en tooltip).
![image1439886356](https://cloud.githubusercontent.com/assets/6093597/9325652/384e3baa-4594-11e5-85e4-79e0840ae9d9.png)

**Comment by vbombaerts** [comment]
OK pour le nom et la description du service. Pour ce qui est de l'icone, cf discussion à propos du #248
