### ISSUE TITLE
Migration ISO19139.rw --> ISO 19139

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#247]
Les fiches de Metawal doivent être migrées en ISO 19139 pour faciliter la gestion du catalogue. Quelle procédure pour la migration de ces fiches ?

**Comment by vbombaerts** [comment]
J'ai testé ce qui est écrit au #153 sur une fiche ISO 19139.rw du catalogue en valid et j'obtiens

```
<response process="rwto19139" startDate="2015-06-18T16:59:20" reportDate="2015-06-18T16:59:20" running="false" totalRecords="1" processedRecords="1" nullRecords="0">
  <done>0</done>
  <notProcessFound>1</notProcessFound>
  <notOwner>0</notOwner>
  <notFound>0</notFound>
  <metadataErrorReport/>
</response>
```

Le fichier de transformation n'est pas accessible sur les serveurs de valid/prod ?
(l'envi de test dans les choux, comme d'hab'... :-1: )

**Comment by fxprunayre** [comment]
La procèdure de #153 s'applique à MW4 (pas MW3). Le processus n'est pas présent en 3 cf. https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.x/schemas/iso19139.rw/src/main/plugin/iso19139.rw/process/rwto19139.xsl

Convertir les fiches de iso19139.rw vers iso19139 n'est en soi pas compliqué mais supposerai aussi de migrer tout ce qui a été défini en plus dans le schéma RW (eg. aide, mise en page, indexation - à vérifier).

**Comment by fxprunayre** [comment]
Transfo ajoutée https://github.com/SPW-DIG/metawal-core-geonetwork/commit/02f39f0b26b13cd576fe0e76c849f586012295fb

**Comment by davinciagf** [comment]
Sauvegarde des fiches avec catalogue d'attributs cf. #232

# Manipulation pour la transformation:

## Au niveau du catalogue
1. Se connecter en Admin
2. Rechercher toutes les fiches à traiter (eg. schema iso19139.rw) 
   http://localhost:8080/geonetwork/srv/eng/q?_schema=iso19139.rw&_isTemplate=y or n&summaryOnly=true
3. Sélectionner tout
    http://localhost:8080/geonetwork/srv/eng/metadata.select?selected=add-all
4. Exécuter (ATTENDRE  la fin)
    http://localhost:8080/geonetwork/srv/eng/md.processing.batch?process=rwtoiso19139

Progress report
     http://localhost:8080/geonetwork/srv/eng/metadata.batch.processing.report

## Au niveau de la DB
1. Modifier le schemaid

```
    UPDATE metadata SET schemaid = 'iso19139' WHERE schemaid = 'iso19139.rw';
```

Attention vérifier que bien commiter (faire un commit !!!)  
2. Vérifier la migration

```
    select * from metadata where data like '%rw:%';
    select distinct(schemaid) from metadata;
```

## Au niveau de GN
1. Dans l'administration du catalogue, réindexer le contenu.
