### ISSUE TITLE
Comportement des raccourcis de visualisation rapide de ressources en ligne dans WalOnMap

### ISSUE THREAD

**Issue by gdetry** [SPW-DIG/metawal-core-geonetwork#248]
Il est question de(s) icônes "ajouter à la carte" présente(s) dans la page de résultat ou dans la fenêtre de consultation d'une ressource. 

![vue1](https://cloud.githubusercontent.com/assets/12267969/8248306/af7b6bf0-165d-11e5-8479-e0c9cef23815.png)

Leur disponibilité et comportement n'est pas systématique en fonction de la ressource en ligne documentée dans une fiche de géodonnée ou de géoservice
- Ressource en ligne ESRI/REST

Pour toute ressource en ligne débutant par l'URL "http://geoservices.wallonie.be/arcgis/rest" (taguée ou non par un protocole). L'icône s'ajoute dans la page de résultat de la ressource et permet la visualisation dans WalOnMap

![vue1_ok](https://cloud.githubusercontent.com/assets/12267969/8248420/248c8298-165f-11e5-94af-fefa08aaff9d.png)
- Pour toute ressource en ligne n'étant pas du type "http://geoservices.wallonie.be/arcgis/rest", l'icône n'apparait pas. Exemple : http://sig.issep.be/arcgis/rest. Il n'est donc pas possible de visualiser une ressource ESRI/REST extérieure aux géoservices internes.

![vue1_pasok](https://cloud.githubusercontent.com/assets/12267969/8248509/2d563ba2-1660-11e5-9042-75992ccb8a2c.png)

Aucune icône n'apparait dans la fenêtre de consultation de ressource, même si les ressources sont taguées ESRI/REST

![vue2_pasok](https://cloud.githubusercontent.com/assets/12267969/8248546/a7e3bec6-1660-11e5-9d50-64ddaddc3175.png)
- Ressource en ligne WMS
  L'icône (avec mention "visualiser") apparait uniquement lorsque la ressource en ligne est taguée (OGC:WMS), peut importe la valeur inscrite comme URL

![vue2](https://cloud.githubusercontent.com/assets/12267969/8248644/a26b26b8-1661-11e5-921c-d18e3bec96b0.png)

...et l'icône apparait dans la fenêtre de consultation de la ressource

![vue3](https://cloud.githubusercontent.com/assets/12267969/8248688/2427ea42-1662-11e5-8a13-f47ecbac2929.png)

Si on enlève le tag WMS, l'icône ne s'affiche plus.
- Concernant les raccourcis de type "liens" :

Un nouveau raccourci "liens" est ajouté par type de tag (sauf pour WMS où l'icône "carte" apparait). Exemple : référencement d'une ressource REST et vecteur = 2 raccourcis "liens";

Si la ressource n'est pas taguée, c'est un raccourci "liens + cadenas" qui apparait;

Si on respecte la bonne structure pour l'URL du service REST, on obtient l'icône "carte" + la mention "liens", contrairement au cas du WMS 

Finalement, il y a une répétition des raccourcis, qui engendre une confusion. L'objectif d'avoir une vue synoptique des ressources en ligne sans ouvrir la fiche n'est pas atteint.

![vue_general](https://cloud.githubusercontent.com/assets/12267969/8249101/036ec258-1667-11e5-8ef1-9ab744f6d2ac.png)

Exemple en test :  89ba184e-251a-4e64-b1cb-bd1954660147

**Comment by gdetry** [comment]
La fiche de géodonnées Sectorisation - secteur PARIS ( 6601d716-1a73-4e86-a610-d9ad2a328b4a) présente des ressources liées ESR/REST (URL conforme) et WMS mais aucune icône n'apparait

**Comment by davinciagf** [comment]
Vérifier si le comportement est ok (la redondance pour les geoservices a été supprimée)

**Comment by davinciagf** [comment]
Proposition de correction (à compléter au niveau des types de fichier à introduire via un boution lien):
text/plain, text/html, application/msword
- introduction pour les trois autres langues (visualisation REST, visualisation WMS)
  ![capture1](https://cloud.githubusercontent.com/assets/576292/9412671/5f0f05c6-482d-11e5-8fa3-7d26d02d1548.PNG)

A compléter sur base de la méthologie d'introduction des differents liens (protocole, url,...). Vérification des anciennes fiches et mise à jour sur base de la méthodologie.

**Comment by fxprunayre** [comment]
TODO 3 boutons possible:
- Visualiser REST
- Visualiser WMS
- Dropdown avec tous les autres liens de la fiche (avec ou sans protocol)

**Comment by vbombaerts** [comment]
Est-ce que c'est possible de faire une liste déroulante pour les liens dans tous les cas, même quand il n'y en n'a qu'un seul ? (pour avoir toujours le même comportement)

**Comment by davinciagf** [comment]
Faut-il le même comportement pour tous les types de liens: liens vers les WMS (affichage du WMS dans WalOnMap) et les Rest (affichage du WMS dans WalOnMap)? 
![capturelinks](https://cloud.githubusercontent.com/assets/576292/9616377/ffe411ca-50fd-11e5-913c-125fac9858a9.PNG)

**Comment by vbombaerts** [comment]
Pour des fiches avec des liens, plus rien n'apparait. Ex : Accidents de la circulation.

**Comment by vbombaerts** [comment]
Désolé, il y a encore des problèmes. Exemples :
- rien qui apparait alors que des services sont renseignés -  http://metawal3.test.wallonie.be/geonetwork/srv/fre/search?uuid=e9a46ea6-83f9-48db-9239-9a27f9938b0d
- derrière visualiser REST, c'est le résumé de l'application qui apparait - http://metawal3.test.wallonie.be/geonetwork/srv/fre/search?uuid=22335bed-e785-45b0-bae8-b47b4386b8b7
  (je n'ai pas testé plus avant)
