### ISSUE TITLE
Ouverture d'une ressource WMS dans WalOnMap

### ISSUE THREAD

**Issue by gdetry** [SPW-DIG/metawal-core-geonetwork#249]
Lors du clic sur le raccource "carte", les ressources en ligne taguée OGC:WMS ne s'affichent pas dans l'application WalOnMap, contrairement aux services REST. 

Problème lors du chargement du WMS dans le geoviewer. Lors du chargement depuis Metawal, l'URL est :
- http://geoportail.wallonie.be/walonmap/?wmlUrl=http%3A%2F%2Fgeoservices.wallonie.be%2Farcgis%2Frest%2Fservices%2FSOL_SOUS_SOL%2FERRUISSOL__CLASSES_PENTE%2FMapServer%2FWMSServer&layerName=Service%20de%20visualisation%20WMS&metadataUrl=http%3A%2F%2Fmetawal.wallonie.be%2Fgeonetwork%2Fsrv%2Ffre%2Fsearch%3Fuuid%3Da02fcb35-3bc7-4b22-a447-dc6bb438710a#BBOX=-2448.4512319025234,328281.3768944204,8589.083312166607,175541.50055033446

Elle devrait être du type : 
- #WMS=urlService|couche1,couche2 … (listeCouchesVisibles) 

Ex : http://geoportail.wallonie.be/WalOnMap/#WMS=http://geoservices.wallonie.be/arcgis/services/IMAGERIE/ORTHO_2012_2013/MapServer/WMSServer|0

**Comment by davinciagf** [comment]
Actuellement, l'utilisation du proxy du geoviewer de WalOnMap (http://geoservices.wallonie.be/geoviewer/proxy.jsp?) entraîne une erreur de type 500 avec des WMS. Cette erreur ne peut être résolue pour l'instant et sera analysé lors de la ré-écriture WalOnMap.

**Comment by davinciagf** [comment]
#372
