### ISSUE TITLE
Header : le titre du site doit pointer vers la page d'accueil de Metawal

### ISSUE THREAD

**Issue by metawal** [SPW-DIG/metawal-core-geonetwork#25]
Actuellement, lorsqu'on clique sur "Metawal - Catalogue pour l'information géographique de Wallonie", le message suivant apparait : "Not Found The requested URL /cms/home.html was not found on this server."

**Comment by davinciagf** [comment]
Le lien doit être réactivé

**Comment by fxprunayre** [comment]
Doublon #47
