### ISSUE TITLE
Problème d'intitulé des champs

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#251]
Sur une fiche en profil rw, le nom de certains champs est maintenant en anglais.
![2015-08-20 17_56_13-metawal - test _ test afac - iso 19139 rw dataset](https://cloud.githubusercontent.com/assets/6093597/9388333/0499e32c-4765-11e5-9e64-57d28e10d3ba.png)

**Comment by davinciagf** [comment]
Erreur de lecture du fichier labels.xml car erreur dans ce dernier (voir fcaff10)
