### ISSUE TITLE
Edition / Formulaire sur le modèle GéoPortail

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#253]
- cf. config-editor.xml
- #269
- En lien avec #260

**Comment by davinciagf** [comment]
Ajouter une fonctionnalité au niveau de l'onglet Contact permettant de définir plusieurs "types de contact" pour un contact afin de ne pas répéter l'action pour un contact ayant plusieurs casquettes.
Idée de visuelle
![screen shot 2015-10-30 at 11 35 36](https://cloud.githubusercontent.com/assets/576292/10845562/22264ddc-7f09-11e5-9781-d86e74166ab2.png)

**Comment by fxprunayre** [comment]
Revue faite de la première version https://github.com/SPW-DIG/iso19115-3/commits/4f5d36dc5d2ac2e8d8522e94b2efcd05cd67d722/src/main/plugin/iso19115-3/layout/config-editor.xml. 

A poursuivre et identifier les sections qui nécessitent des développements complémentaires. eg. les contacts. Créer des tickets spécifiques pour ça pour les identifier dans les estimations.

**Comment by fxprunayre** [comment]
Ajout de la possibilité de définir l'éditeur comme auteur/contact pour la resource ou la fiche
- https://github.com/geonetwork/core-geonetwork/issues/1362
- https://github.com/metadata101/iso19115-3/commit/29b5a68b48fad05772adf30a8975010e777f6325

**Comment by fxprunayre** [comment]
FYI, pour les fiches ISO19115-3 qui ont une référence à un service WFS et une couche dans ce service, il est possible de générer le catalogue d'attributs via les suggestions cf. https://github.com/metadata101/iso19115-3/issues/12
