### ISSUE TITLE
Import / XML ESRI ISO19139 conversion en ISO19115-3

### ISSUE THREAD

**Issue by davinciagf** [SPW-DIG/metawal-core-geonetwork#254]
Possibilité d'import pour le service REST et xml d'Esri (shp et fgdb ?)

**Comment by davinciagf** [comment]
## Contexte

L'application METAWAL devant avoir accès aux fichiers (shsp, fgdb) afin d'extraire l'information (via un outil d'extraction), il est peu pertinent d'uploader les fichiers (taille diverses) sur un espace accessible à l'application. Il paraît plus judicieux de travailler sur base des fichiers xml produit par ESRI et liés aux géoressources.

## Réalisation

Mise en oeuvre d'un job d'extraction sur base du xml et intégration des données au niveau d'un xml ISO19115-3.

## UX

Utilisation du service d'import actuel

## Process

Intégration du process de conversion et vérification sur base du xml produit par les logiciels ESRI (ISO19139 to ISO19115-3)

**Comment by fxprunayre** [comment]
A appliquer à GN quand ISO19115-3 sera dans GN.

**Comment by vbombaerts** [comment]
Fonctionne +/-. A analyser plus en profondeur mais pas maintenant.
