### ISSUE TITLE
Edition par lots

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#257]
Related work:
- search and replace
- transfert parent to child info

Cf. https://github.com/geonetwork/core-geonetwork/wiki/Proposal-Edit-A-Set-Of-Records

En lien avec #256 pour une sélection rapide d'un lot.

**Comment by vbombaerts** [comment]
Exemple d'use cases (sera complété au fur et à mesure)
- Création ou mise à jour d'une "famille" de fiches. Une famille, c'est par exemple un jeu de données (série thématique) qui contient plusieurs données. Dans ce cas, bcp d'informations sont communes : contacts, mots-clés, emprises, mode de distribution, généalogie, systèmes de référence...
- Lors de la publication d'un service ou d'une application, on veut ajouter une référence dans toutes les fiches de données qui sont servies via le service ou avec lesquelles il est possible d'interagir à travers l'application. 
- Pour classer des données (INSPIRE, opendata, etc), on veut ajouter un ou des mots-clés du thésaurus InfraSIG.
- Lors de la mise à jour d'une donnée qui fait partie d'un jeu de données, on veut adapter les dates de mise à jour dans les deux fiches.

La différence avec une édition en batch, c'est qu'on veut utiliser l'interface d'édition classique pour modifier/ajouter les infos. PQ ? Parce que c'est l'éditeur qui veut éditer par lot, pas le gestionnaire du catalogue. Il faut donc qu'il puisse la faire par son interface habituelle.

**Comment by vbombaerts** [comment]
- Etablir des liens entre fiches pour des ressources d'une même famille. Par exemple lier une série thématique à tous ses membres et lier les membres à la série et entre elles en une seule opération.

**Comment by fxprunayre** [comment]
Mergé dans GN. A améliorer en 4.1 si besoin.

**Comment by vbombaerts** [comment]
Améliorations à prévoir :
- [ ] Ajouter un mot clé provenant d'un thésaurus

**Comment by gdetry** [comment]
Ce ticket est plutôt lié à de l'édition en série. Un post plus global est ouvert #411 . Ce post peut être fermé
