### ISSUE TITLE
ISO19115-3 / Indexing / Application is not a service

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#259]
Visualiser les seules fiches des géoservices lors d'une recherche de géoservices (ne pas avoir les applications)

**Comment by fxprunayre** [comment]
![image](https://cloud.githubusercontent.com/assets/1701393/14141777/7e604bda-f681-11e5-8b06-b9f585f13935.png)

la facette sur les types ne propose pas service. La fiche est donc bien classée comme application uniquement.

**Comment by vbombaerts** [comment]
OK, par contre --> #323
