### ISSUE TITLE
Ajouter une balise spécifique pour informer de la visibilité de la géoressources via un service WalOnMap

### ISSUE THREAD

**Issue by davinciagf** [SPW-DIG/metawal-core-geonetwork#262]

**Comment by vbombaerts** [comment]
"En tant qu'éditeur, je voudrais utiliser Metawal pour spécifier que la donnée doit être visible dans WalOnMap." ou « En tant que gestionnaire de WalOnMap, je veux ajouter dynamiquement les services autorisés à WalOnMap »  ou " En tant qu'utilisateur du catalogue, je veux sélectionner uniquement parmi les données visibles sur WalOnMap" ?? Précisions demandées.

**Comment by spalmspw** [comment]
Ce point n'est plus à l'ordre du jour.
L'objectif était de pouvoir empêcher la visualisation d'un service dans WalOnMap => demande DGO3. 
Actuellement l'ensemble de leurs services internet sont diffusés en WMS et donc utilisables par n'importe quel client GIS

**Comment by vbombaerts** [comment]
Réglé via des keywords
