### ISSUE TITLE
Valider un lot

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#263]
- sélectionner des fiches
- valider l'ensemble
- menu ajouter dans action sur la sélection
- pour éditeur ou plus (rapport nb de fiches traitées, fiches non autorisées)
- editor board / icone de validation

PR dans GN

Après: cf: validateur INSPIRE.

**Comment by fxprunayre** [comment]
GN ref https://github.com/geonetwork/core-geonetwork/issues/1172

**Comment by fxprunayre** [comment]
Pour le rendu du niveau de validité je propose :
- de mettre en couleur (rouge = invalid, vert = valid, none = pas encore validé)
- dans la tooltip `"<type> (<validStatus>)"`

![image](https://cloud.githubusercontent.com/assets/1701393/9651341/b9f87c60-520f-11e5-8977-7e33f301d44f.png)

J'ai testé un pouce vers le haut/bas mais ca prend de la place sans grand intérêt je pense.

@vbombaerts Ca convient ?

**Comment by vbombaerts** [comment]
OK pour le code couleur. 

Par contre, il faudra s'entendre sur la signification de "valide", puisque même si la fiche est valide techniquement par rapport au schema et au schematron, il y a avant publication une validation du contenu. (mais ça, ça ne change pas par rapport à la situation actuelle)

**Comment by fxprunayre** [comment]
> il y a avant publication une validation du contenu. 

En effet, c'est différent. Pour ça, il faudrait utiliser le workflow et afficher l'état en plus pour distinguer les 2. Par exemple, sur la 2ème ligne mettre: "Auteur: Pierre, Etat: brouillon.", "Auteur: Ed, Etat: validée." ...

**Comment by vbombaerts** [comment]
OK. Bonne idée.

**Comment by fxprunayre** [comment]
Fait 
![image](https://cloud.githubusercontent.com/assets/1701393/9666996/942b5b8c-5279-11e5-80e3-66f9a298c1b5.png)

**Comment by fxprunayre** [comment]
PR appliquée à GN. GN mergé avec MW4. A tester.

**Comment by vbombaerts** [comment]
OK pour la validation par lot et la représentation de l'état de validité.
Mais c'est où qu'on indique les infos relatives au cycle de vie ?

**Comment by davinciagf** [comment]
Lorsque tu regardes une fiche (suite à une recherche) au niveau de la vue par défault, il y a à droite de la fenêtre quatre icones. Tu sélectionnes le 3ème et tu choisis d'activer le workflow. Ensuite, tu auras la possibilité de changer le statut de la fiche via la même procédure (mettre à jour l'état de la fiche).
![capture](https://cloud.githubusercontent.com/assets/576292/14823231/0d1d26c6-0bd2-11e6-993e-8e92ca0b98b7.JPG)

**Comment by vbombaerts** [comment]
OK. Merci.
