### ISSUE TITLE
Edition / Résumé / Saisie personnalisée

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#269]
Suivre les règles du guide de saisie avec l'accroche, ...
Ajouter un contrôle du nombre de caractères

Créer une directive qui s'applique à mri:abstract
https://github.com/SPW-DIG/iso19115-3/blob/d83a41e4d4ad09ec42b1844cf49df0023d78f7db/src/main/plugin/iso19115-3/layout/config-editor.xml#L77

Questions: est-ce qu'on gère un résumé multilingue ?

**Comment by vbombaerts** [comment]
Fonctionnalité OK, mais design à améliorer. Laisser plus de place dans les boites : 
- celle de l'accroche : assez pour voir +/- 200 caractères // 3 lignes
- celle du descriptif : 15/20 lignes
  ![2016-03-02 17_23_18-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/13466826/ee731f34-e09b-11e5-8f5b-111f7ba01cc2.png)
  ![2016-03-02 17_26_48-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/13466835/0144d62a-e09c-11e5-82d2-efd818368f05.png)

**Comment by davinciagf** [comment]
Mise en place d'un système de mise à jour de la hauteur du champs sur base du contenu de la zone de texte (scrollHeight)

**Comment by vbombaerts** [comment]
Chouette mais la taille de la zone d'accroche ne devrait pas diminuer quand on tape dans le descriptif. Elle constitue un indicateur du nombre de caractères qui convient pour l'accroche (+/- 160)

**Comment by vbombaerts** [comment]
Testé OK.
