### ISSUE TITLE
Connexion / Affichage des suggestions de nom d'utilisateur

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#27]
Les suggestions s'affichent à un endroit bizarre
On ne me suggère pas un nom d'utilisateur déjà utilisé plusieurs fois, mais on me propose des noms d'utilisateurs que je n'ai jamais utilisés
![image 614](https://f.cloud.github.com/assets/6093597/1662124/05bae13e-5bf8-11e3-8354-bbf483e4324d.png)

**Comment by fxprunayre** [comment]
A priori, c'est le navigateur qui propose cette liste. A voir si on peut la désactiver (si souhaitable) ?
