### ISSUE TITLE
ISO19115-3 / Ajout de la fiche en ISO19139 dans l'export

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#275]
Actuellement, seule la fiche au format ISO19115-3 est exportée en MEF. Un vieux GN moissonnant via le protocol GN ne pourra pas importer la fiche.

On améliore ?

**Comment by fxprunayre** [comment]
Cf. https://github.com/geonetwork/core-geonetwork/issues/1327

**Comment by vbombaerts** [comment]
J'ai importé dans MW4 test une fiche provenant de MW3 prod. Ensuite exporté en MEF et réimporté dans MW3 valid.
- Toutes les dates ont disparu (métadonnée, donnée, thésaurus, qualité)
- La vignette ne passe pas
- Au niveau des aggrégations, plusieurs infos ne passent pas.
- le type de représentation spatiale a disparu
- langue du jeu de données a disparu
- encoding du jeu de données a disparu
- problème de traduction dans l'intitulé du champ relatif à l'étendue temporelle - utilisation d'éléments différents ???
- qualité/ domaine d'applicabilité à disparu

**Comment by fxprunayre** [comment]
> J'ai importé dans MW4 test une fiche provenant de MW3 prod. Ensuite exporté en MEF et réimporté dans MW3 valid.

Avec conversion en 19115-3 ? ou autre chose (édition) ?
Preneur de l'UUID de la fiche pour reproduire le test.

**Comment by fxprunayre** [comment]
Test sur 9e8f77db-8ce9-464c-b28c-9ecb96a58a31

> Toutes les dates ont disparu (métadonnée, donnée, thésaurus, qualité)
- dateStamp cf. https://github.com/metadata101/iso19115-3/blob/develop/src/main/plugin/iso19115-3/convert/ISO19139/toISO19139.xsl#L182, issue ref: https://github.com/metadata101/iso19115-3/issues/21
- date des données, thésaurus : toutes les dates sont converties en DateTime `<gco:DateTime>2010-05-01T00:00:00</gco:DateTime>` mais elles sont bien là ? Il y a eu un changement sur la fin du schéma non pris en compte dans la transformation. Cf. https://github.com/metadata101/iso19115-3/issues/22

> La vignette ne passe pas 

De mon côté en sortie ISO19139, j'ai bien un élément graphicOverview. "ne passe pas" = absent ou pb d'URL ou autre ?

> le type de représentation spatiale a disparu
> langue du jeu de données a disparu
> encoding du jeu de données a disparu

Indeed, wrong namespace for spatialRep, late xsd change on language & encoding (cf. https://github.com/metadata101/iso19115-3/issues/23)

> Au niveau des aggrégations, plusieurs infos ne passent pas.

Pb selon l'encodage des codelists. cf 23

**Comment by vbombaerts** [comment]
--> Le passage de la prod à la test s'est fait avec conversion.

--> Vignette : problème d'URL - l'URL fait référence à /srv/api/metadata/ et je pense que ça n'existe pas dans Metawal prod

**Comment by fxprunayre** [comment]
> --> Le passage de la prod à la test s'est fait avec conversion.

Ok j'ai corrigé un certain nombre de pb, mais je voudrais l'UUID de la fiche utilisée pour reproduire tous les pb indiqués.

**Comment by vbombaerts** [comment]
Il y en a deux :
- http://metawal3.valid.wallonie.be/geonetwork/srv/fre/search?uuid=9c60e9ef-8e15-4a8c-b3de-22c0d1e221a3
- http://metawal3.valid.wallonie.be/geonetwork/srv/fre/search?uuid=33a6510a-3aae-4983-9ad1-b2d86141a8db

**Comment by fxprunayre** [comment]
Tous les pb corrigés. A redéployer, rejouer conversion 19139 > 19115-3 et tester.

**Comment by fxprunayre** [comment]
> La vignette ne passe pas

Les URL des documents associés en v4 ne seront pas retro-compatible en v3 du fait du changement d'API (ie. /api/records/uuid/attachments/filename). Donc en v3, l'URL pointera vers la v4.

**Comment by vbombaerts** [comment]
Autres tickets sur l'import. On ferme
