### ISSUE TITLE
Recherche / Indexer les contacts par rôle

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#276]
Pour créer des facettes plus spécifiques - à préciser

**Comment by fxprunayre** [comment]
Doublon avec #250

**Comment by vbombaerts** [comment]
L'objectif est de disposer d'un double filtre à la fois sur les contacts (sélectionnables en vue hiérarchique) et les rôles.
Ex : 
- toutes les fiches où la Direction de la coordination des données est indiquée en tant que gestionnaire ou distributeur
- toutes les fiches pour lesquelles le SPW est propriétaire

Par défaut, quand on fait une recherche hiérarchique sur les contacts, tous les rôles sont cochés. Possibilité de décocher certains rôles pour affiner la recherche.

**Comment by fxprunayre** [comment]
En v4, il n'y a pas de critère sur les contacts à proprement parler. A faire via les facettes sous forme d'arbre ?

```
SPW
  |- Gestionnaire
  |- Distributeur
UNEP
  |- Distributeur
```

Ou l'inverse organisme et ensuite role ?
