### ISSUE TITLE
Editeur / Thésaurus hierarchique

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#278]
https://github.com/geonetwork/core-geonetwork/wiki/2014AngularEditorSkosThesaurusBrowser

**Comment by fxprunayre** [comment]
Disponible en 4.0 Cf. https://github.com/geonetwork/core-geonetwork/pull/1336

**Comment by vbombaerts** [comment]
On doit un peut s'habituer à la navigation mais après c'est OK.

**Comment by vbombaerts** [comment]
Réflexion faite, est-ce qu'on ne pourrait pas indiquer "Concept actuel" avant le concept sélectionné et associer le + à ajouter comme mot-clé. Au-dessus des autres termes indiquer en texte les relations "Concepts plus précis", etc... . Mettre à gauche ou à droite le add (ajouter comme mot-clé) et sélectionner le concept quand on clique dessus (sans l'ajouter aux mots-clés). On peut garder les flèches, mais elles ne doivent pas être cliquables
J'ai essayé de dessiner çà +/-. Partie droite de l'image.
![2016-03-02 16_10_31-microsoft powerpoint - presentation1](https://cloud.githubusercontent.com/assets/6093597/13464415/6c5d1c48-e091-11e5-82c6-ae0b16fd6006.png)

**Comment by fxprunayre** [comment]
Cf. https://github.com/geonetwork/core-geonetwork/tree/develop/web-ui/src/main/resources/catalog/components/ng-skos

**Comment by vbombaerts** [comment]
Il manque

> sélectionner le concept quand on clique dessus (sans l'ajouter aux mots-clés)

Il n'est pas sélectionné comme concept principal mais est ajouté aux mots clés.
Les boules à gauche du mot-clé ne servent à rien si on peut sélectionner le concept en cliquant sur le mot-clé (à supprimer).

En bonus, si on pouvait présenter les concepts plus "en largeur" (sur 3 colonnes : parent, plus spécifique, associé) ce serait top. Là, il y a bcp d'espace perdu...
![2016-04-22 15_53_10-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/14743555/57ff5390-08a2-11e6-9d4a-7fcc29abd85c.png)

**Comment by davinciagf** [comment]
Fonctionnement:
Si on clique sur le nom du concept ce dernier s'ajoute à la liste.
Si on clique sur la boule on "déroule" le concept et ce dernier est sélectionné sans être ajouter à la liste.
Faudrait-il inverser (Si on clique sur le nom du concept, ce dernier se déroule et si on clique sur le bouton à gauche on ajoute ce concept à la liste des mots-clés)? Avis ou autre?

Je regarde pour la mise en colonne

**Comment by davinciagf** [comment]
Voici ce que cela pourrait donner pour la mise en colonne:
Pour les trois notions
![capture](https://cloud.githubusercontent.com/assets/576292/14787822/790d4b54-0b05-11e6-8aea-38dd9b95f565.JPG)
Format écran plus petit
![capture1](https://cloud.githubusercontent.com/assets/576292/14787823/7aef1b14-0b05-11e6-8a4d-84b5874506e8.JPG)
Format écran encore plus petit
![capture3](https://cloud.githubusercontent.com/assets/576292/14787826/7cb43934-0b05-11e6-8948-3ac8208e7341.JPG)
Si deux notions uniquement
![capture2](https://cloud.githubusercontent.com/assets/576292/14787853/97c41a8c-0b05-11e6-8070-2eaf63a5e64e.JPG)

**Comment by vbombaerts** [comment]
Trois colonnes = très bien

Quand on clique sur le mot, il est choisi comme concept mais pas ajouté aux mot-clés
Quand on clique sur le + (remplacer les boules par un +), il est ajouté aux mots-clés.

**Comment by davinciagf** [comment]
Nouvelle proposition relative au fonctionnement (cf suite à la remarque ci-dessus)
![capture1](https://cloud.githubusercontent.com/assets/576292/16684076/48683a8a-4503-11e6-9f13-9ebc30bc9a14.PNG)

PR vers GN ? @fxprunayre
