### ISSUE TITLE
Export / amélioration du nom de fichier

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#280]
Sur la fiche en visualisation, l'export xml par "clic droit > enregistrer sous" génère un fichier dont le nom est "xml.metadata.get". Il faut prévoir un nom plus explicite et l'extension xml.
![2015-08-31 14_59_26-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/9579253/7a545982-4ff1-11e5-9d05-8bfc077208d1.png)
![2015-08-31 15_02_15-saisissez le nom du fichier pour l enregistrement](https://cloud.githubusercontent.com/assets/6093597/9579259/7eb04c20-4ff1-11e5-96cf-2cfe0b7de2cd.png)

**Comment by fxprunayre** [comment]
Cf. https://github.com/geonetwork/core-geonetwork/issues/1508

**Comment by fxprunayre** [comment]
A redéployer. Le service (Jeeves) `xml.metadata.get` est conservé mais l'application dirige maintenant vers un nouveau service (Spring MVC) `/api/records/{{uuid}}` dans l'API GeoNetwork en cours de réalisation. Ce service définit le nom du fichier `{{uuid}}.xml` quand le navigateur sauvegarde le fichier.
