### ISSUE TITLE
Console / Reporting - Nouvelles fiches vs mise à jour

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#281]
Dans le système de reporting, prévoir de pouvoir distinguer entre les opération faites sur des nouvelles fiches vs celles effectuées sur des fiches déjà existantes. Par exemple, avoir un bilan des mouvements du catalogue (nb d'éditions, temps d'édition, nb d'utilisateurs ayant édité) qu'on puisse filtrer également sur ce critère. 
Probablement en lien avec l'espace d'édition parallèle ?

**Comment by gdetry** [comment]
Stat sur log Apache dans Kibana >> Config DAOBS (cf. ex. Sextant)

**Comment by stephyritz** [comment]
Je ne comprends pas vraiment la réponse car je ne connais pas les outils utilisés précédemment. Pas d'urgence à ce niveau là pour le moment. Je modifie le milestone.
