### ISSUE TITLE
Edition / conditions d'accès et d'utilisation

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#282]
L'idée est de générer la mention des conditions et d'utilisation en fonction d'une grille de questions-clés comme celles des nouvelles CGU CGA CPU et CPA. Exemple :
- tout le monde peut-il accéder à la donnée ?
- gratuitement ?
- autorisation de modifier ?
  *

**Comment by davinciagf** [comment]
Réflexion UX (https://github.com/SPW-DIG/Metawal-UX/issues/7)

**Comment by ADefays** [comment]
Voici le lien vers le prototype montrant ce widget:
http://ujxx53.axshare.com/#p=questionnaire_type_d_acce_s
