### ISSUE TITLE
Processus en batch

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#283]
En v4, plusieurs nouveaux processus en batch sont apparus, qui ne sont pour le moment pas dans la v3. Or, on va devoir sous peu effectuer plusieurs opérations de rechercher/remplacer sur plusieurs champs :
- langue de la métadonnées
- conditions d'accès et d'utilisation (nouvelles conditions)
- conformité INSPIRE : anglais --> français
- spécification des ressources en ligne

Est-il possible d'installer les processus en batch disponibles en v4 aussi en v3, au moins le chercher/remplacer ?

**Comment by fxprunayre** [comment]
Pour

> langue de la métadonnées

La migration vers l'ISO19115-3 corrigera le pb cf. https://github.com/SPW-DIG/iso19115-3/blob/a7488cd4602d94cc7b6bdf17c9fd8d497a5bcb92/src/main/plugin/iso19115-3/convert/ISO19139/mapping/core.xsl#L104

Pour 

> conditions d'accès et d'utilisation (nouvelles conditions)
> conformité INSPIRE : anglais --> français

recherche/remplacer peut sans doute convenir.

Pour

>  spécification des ressources en ligne

a priori non, car il faut ajouter des fonctions ? modifier des protocoles ?

> En v4, plusieurs nouveaux processus en batch sont apparus

A priori, il y en a plutôt moins pour l'ISO19115-3. Il faudrait lister ceux qu'il faut éventuellement traduire de ISO19139 vers ISO19115-3.

> Est-il possible d'installer les processus en batch disponibles en v4 aussi en v3, au moins le chercher/remplacer ?

A priori envisageable pour tous sauf le chercher/remplacer. En effet, le chercher/remplacer a des dépendances : 
- côté client avec tout le reste de l'admin
- côté server - service Java spécifique

Conclusion :
- Le plus simple en 3.2 serait de faire un processus qui s'occupe de faire les corrections et de le lancer manuellement
- Définir en v4, les processus à reporter vers ISO19115-3

**Comment by vbombaerts** [comment]
Plutôt que développer de nouveaux process, on va attendre la v4. 
Je ferme.
