### ISSUE TITLE
Mapping Metawal ISO 19139 / Géoportail

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#286]
- thésaurus InfraSIG : ajouter l'entrée "Ressource officielle wallonne"
- Adapter l'aide pour les éléments gmd:otherCitationDetails
- Nouvel élément : logo de la donnée : stocké dans /gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:citation/gmd:CI_Citation/gmd:otherCitationDetails --> transférer dans l'ISO 19115-3
- Adapter la liste des hierarchylevel

**Comment by fxprunayre** [comment]
> thésaurus InfraSIG : ajouter l'entrée "Ressource officielle wallonne"

Cf. https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.x/web/src/main/webapp/WEB-INF/data/config/codelist/external/thesauri/theme/infraSIG.rdf#L20 "Donnée officielle wallonne" 

> Adapter l'aide pour les éléments gmd:otherCitationDetails

Cf. https://github.com/SPW-DIG/iso19115-3/blob/c96f75401c3190f780a69a99502ea5a1c54d38e8/src/main/plugin/iso19115-3/loc/fre/labels.xml#L5951

TODO: A préciser ce qu'il faut mettre.

> Adapter la liste des hierarchylevel

Cf. https://github.com/SPW-DIG/iso19115-3/blob/c96f75401c3190f780a69a99502ea5a1c54d38e8/src/main/plugin/iso19115-3/loc/fre/codelists.xml#L1549

TODO: A préciser ce qu'il faut mettre.

>  Nouvel élément : logo de la donnée :

TODO: A traiter
