### ISSUE TITLE
Gérer les documents attachés

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#289]
Avoir la possibilité de gérer facilement les documents attachés à une fiche de métadonnées. Par exemple remplacer un document ou supprimer un document. Un cas typique est celui ou un document pdf remplace un document word. Ils n'ont pas le même nom. Pour le moment on supprime la référence au premier document dans la fiche et on charge l'autre document. Quand on télécharge le MEF, on a l'ancien document + le nouveau. Autre cas typique : des documents nommés en tenant compte d'un numéro de version.

**Comment by fxprunayre** [comment]
Partiellement traité dans https://github.com/geonetwork/core-geonetwork/pull/1385. Est-ce suffisant ?

**Comment by vbombaerts** [comment]
- [ ] Quand la fenêtre de chargement s'ouvre, elle ne doit pas préselectionner un type de document et surtout pas les filtrer dans la colonne de droite. Il faut être sur une mention neutre qui demande de choisir le type de ressource en ligne associée. Le contenu du dépôt ne se filtre que lorsque l'utilisateur a choisi un type de ressource.
![2018-01-25 10_48_58-](https://user-images.githubusercontent.com/6093597/35381825-ca3168a2-01bd-11e8-91d9-8bd82627d1e7.png)
- [ ] On doit pouvoir déposer un fichier dans toute la zone de dépôt de fichier, pas uniquement sur le bouton vert "Sélectionner un fichier"
- [ ] Détecter automatiquement le type de fichier et encoder la valeur correspondante dans la balise "applicationprofile". 
- [ ] Ajouter une entrée "Format du fichier" qui matche avec une codelist des applicationprofiles. Si le type de fichier est détecté, cette entrée s'auto-compète. Sinon, l'utilisateur peut la modifier.

Je trouve perturbant de pouvoir ajouter des sites web via l'outil qui ouvre le dépôt, mais 
- de ne pas les retrouver dans le dépôt
- de ne pas pouvoir les éditer ensuite
--> Pourrait-on faire apparaître les sites web, services, etc dans le dépôt ?

**Comment by fxprunayre** [comment]
> Quand la fenêtre de chargement s'ouvre, elle ne doit pas préselectionner un type de document et surtout pas les filtrer dans la colonne de droite. Il faut être sur une mention neutre qui demande de choisir le type de ressource en ligne associée. Le contenu du dépôt ne se filtre que lorsque l'utilisateur a choisi un type de ressource.

Le pb c'est que si on ne sélectionne ni imagette, ni fichier à uploader, le filestore de droite ne s'affichera pas. Ce qui donnerait quelquechose comme:

![image](https://user-images.githubusercontent.com/1701393/35847056-529cb2aa-0b19-11e8-8241-caecc611431b.png)

J'aurai tendance à proposer de garder l'interface tel qu'elle est et déplacer ce ticket pour la version 2018 et les travaux prévus sur ce composant ? @vbombaerts

**Comment by vbombaerts** [comment]
OK.
