### ISSUE TITLE
Header : tailles de polices différentes, ce n'est pas esthétique

### ISSUE THREAD

**Issue by metawal** [SPW-DIG/metawal-core-geonetwork#29]
Dans le header, le fait que "Metawal" soit écrit en plus grand que "Catalogue pour l'information géographique de Wallonie" n'est pas très joli.

**Comment by fxprunayre** [comment]
See https://github.com/spacebelGIS/metawal-core-geonetwork/commit/bcc0e4d59625867873e61ee2b725468d8a0e88bc
