### ISSUE TITLE
Thésaurus InfraSIG : ajouter l'entrée "Ressource officielle wallonne"

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#290]
Comme le thésaurus est externe, je ne peux pas l'éditer.
Si je veux télécharger le thésaurus InfraSIG existant, je ne peux pas.
Si je veux ajouter un nouveau thésaurus, je ne peux pas ajouter de mots-clés dedans.

**Comment by vbombaerts** [comment]
Autres mots-clés à ajouter :
• Ressource officielle 
• DGO3_BDREF
• DGO3_CIGALE
• BD_InfraSIG
• WalOnMap
• liste_CCPIE

D'autres suivront. Comment puis-je faire pour rendre ce thésaurus éditable dans MW ?

**Comment by fxprunayre** [comment]
- Mettre à jour https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.x/web/src/main/webapp/WEB-INF/data/config/codelist/external/thesauri/theme/infraSIG.rdf
- Le basculer dans local 
- Vérifier d'éventuelle références dans les fiches external.thesauri.theme.infraSIG et faire un replace en base si nécessaire ?
- en v3 ou uniquement en v4 ?

**Comment by vbombaerts** [comment]
J'en ai besoin rapidement. Ca va servir à créer des "tableaux de bord" ou à extraire spécifiquement certaines entrées du catalogue ==> v3.
Le workaround est de travailler avec des mots-clés libres.

**Comment by vbombaerts** [comment]
Finalement réussi à créer un thésaurus InfraSIG.rdf éditable. 
Il faudra ASAP fusionner les deux.

**Comment by davinciagf** [comment]
Mise à jour au niveau de Metawal3 (v3.2.1)

**Comment by davinciagf** [comment]
A modifier au niveau de MW4 en test et ne pas oublier de récupérer le fichier de MW3 lors du passage en prod!!

**Comment by vbombaerts** [comment]
Déployé en prod le 03/02/16
