### ISSUE TITLE
Thesaurus / Thème geoportail hierarchique

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#292]
- Modifier la structure du thésaurus actuel (supprimer les numéros et créer l'arbre)
  - eg. https://github.com/geonetwork/core-geonetwork/blob/3.0.x/web/src/main/webapp/WEB-INF/data/config/codelist/external/thesauri/place/regions.rdf#L16
  - topConcept à déclarer et arborescence
- Mettre à jour les fiches actuelles (SQL ou XSL ?)
- Configurer une facette sur ce champ.
  - créer la facette et la déclarer dans the summary https://github.com/geonetwork/core-geonetwork/blob/3.0.x/web/src/main/webapp/WEB-INF/config-summary.xml#L93
  - déclarer le classifier https://github.com/geonetwork/core-geonetwork/blob/3.0.x/web/src/main/webapp/WEB-INF/config-spring-geonetwork.xml#L129

cf. la doc ! http://geonetwork-opensource.org/manuals/trunk/eng/users/customizing-application/configuring-facetted-search.html

**Comment by davinciagf** [comment]
Autre actions:
- Vérifier thesaurus sur les limites administratives
- Ajout facette INSPIRE (à vérifier)
- Ajout facette GEMET
- Suppression facette mots-clés

**Comment by vbombaerts** [comment]
Est-il possible dès lors de supprimer les codes qui précèdent les termes du thésaurus ?
![2016-03-02 15_41_18-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/13463617/5db5a6f0-e08d-11e5-9d7b-266d88aaed04.png)

**Comment by davinciagf** [comment]
Suppression de l'ancien thesaurus qui écrasait le nouveau.
