### ISSUE TITLE
Gédonnée et série liées - mise à jour automatique de la date de mise à jour

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#293]
Lorsque la date de mise à jour d'une donnée faisant partie d'une série est mise à jour, on voudrait que la date de mise à jour de la série le soit automatiquement pour ne devoir éditer qu'une seule fiche. (surtout dans le cadre d'une édition qui ne passe pas par l'interface Metawal, mais par les services web)

**Comment by fxprunayre** [comment]
Questions:
- La date de mise à jour à modifier dans la série est la "revision" date de la métadonnée ou celle de la série ou les deux ?
- La valeur mise est la même que celle de la donnée en question ?
- Faut-il vérifier que la nouvelle date est plus récente que l'actuelle dans la série ?
- Est-ce qu'il faut avoir également les droits d'édition de la fiche de la série ? ou on ne fait pas de vérification ?

**Comment by vbombaerts** [comment]
- Les deux
- oui
- non (ne nous compliquons pas la vie)
- non, même si dans les faits ce sera probablement le cas.

Peut-on imaginer que ce soit automatique dans le cas de l'utilisation des services web et une suggestion lors d'une édition manuelle ?

**Comment by gdetry** [comment]
Process implémenté à partir de la DB CARTON. Lors MàJ Data >> FME déclenche une MàJ des dates de révision et des dates de publication des filles + série
