### ISSUE TITLE
Amélioration du message d'erreur lors de la récupération du mot de passe

### ISSUE THREAD

**Issue by davinciagf** [SPW-DIG/metawal-core-geonetwork#299]
![capture](https://cloud.githubusercontent.com/assets/576292/12671212/6ed3acc2-c66e-11e5-951d-7ead028525ea.PNG)

**Comment by davinciagf** [comment]
Vérifier la configuration du serveur SMTP (admin/param)
Vérifier le fonctionnement suite à cette mise à jour

**Comment by fxprunayre** [comment]
Nous pourrions peut être:
-  supprimer cette limitation ie. Tous utilisateurs peuvent rédemander un mot de passe
- ne pas afficher l'option si pas de serveur de mail

**Comment by vbombaerts** [comment]
1/ Tous les utilisateurs peuvent redemander un mot de passe. (au fait, lesquels ne peuvent pas pour le moment ??)
2/ Il faut que l'option soit active, mais la procédure est différente s'il s'agit d'un utilisateur LDAP ou pas.

**Comment by fxprunayre** [comment]
> au fait, lesquels ne peuvent pas pour le moment ??)

Cf. le message d'erreur "Only user with profile RegisterdUser".

> s'il s'agit d'un utilisateur LDAP

Quelle serait la procédure dans ce cas ? On envoie un mail comme quoi il faut contacter le LDAP HelpDESK  ?

**Comment by vbombaerts** [comment]
> >    au fait, lesquels ne peuvent pas pour le moment ??)
> 
> Cf. le message d'erreur "Only user with profile RegisterdUser".

C'est ce que je ne comprends pas. Y a-t-il des utilisateurs non-enregistrés qui ont un login ???

> > s'il s'agit d'un utilisateur LDAP
> 
> Quelle serait la procédure dans ce cas ? On envoie un mail comme quoi il faut contacter le LDAP HelpDESK ?

Si utilisateur LDAP, il faut 
1/ leur dire que c'est le mot de passe associé au compte ULIS qu'ils doivent utiliser
2/ s'ils ne s'en rappellent plus, leur dire de contacter le Helpdesk du DTIC. (En fonction de l'utilisateur, la procédure pour contacter le helpdesk du DTIC est différente, donc je ne prévoirais pas de mécanisme particulier dans Metawal)

Si utilisateur propre à Metawal, procédure classque de récupération de mdp.

**Comment by fxprunayre** [comment]
Cf. https://github.com/geonetwork/core-geonetwork/pull/1434

A faire côté Metawal: personnaliser les mails et message pour les users du LDAP.

**Comment by vbombaerts** [comment]
Repris du  geonetwork#1434
![2016-02-11 11_25_16-migrate password reminder create account to spring mvc by fxprunayre pull req](https://cloud.githubusercontent.com/assets/6093597/12974179/304fe800-d0b2-11e5-95de-b88ccfe03822.png)

Dans ces cas prévoir de prévenir l'admin pour qu'il prenne contact avec l'utilisateur et résolve le problème - le formulaire doit permettre à l'utilisateur d'encoder une adresse mail de contact.

**Comment by fxprunayre** [comment]
> Dans ces cas prévoir de prévenir l'admin pour qu'il prenne contact avec l'utilisateur et résolve le problème - le formulaire doit permettre à l'utilisateur d'encoder une adresse mail de contact.

Le formulaire de création de contact ou de création de compte ne permettent pas de créer un utilisateur sans email donc le cas ne devrait jamais se produire. Seul l'admin créé par défaut dans une install vide de GeoNetwork n'a pas d'email.

**Comment by davinciagf** [comment]
La configuration du serveur SMTP semble erronée.

**Comment by vbombaerts** [comment]
Il faut aussi prévoir le cas où la personne ne possède pas encore de compte --> Bouton sur lequel cliquer dans ce cas, genre "Vous n'avez pas encore de compte Metawal ?" --> indiquer la procédure pour en créer un : si LDAP : indiquer qu'il faut utiliser le login ULIS et que la demande d'activation a été transmise au gestionnaire de Metawal. Si autre : indiquer que le demande de création de compte a été transmise au gestionnaire de Metawal.

![2017-02-22 16_34_55-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/23218711/3552fbf0-f91d-11e6-94d0-837d907d8a64.png)

**Comment by vbombaerts** [comment]
Le cas où le login est oublié n'est pas couvert non plus. Prévoir de renvoyer le login par mail.

**Comment by vbombaerts** [comment]
Feedback sur la procédure de login.

1. L'utilisateur connait son username et son mdp ==> 
- procédure rapide : OK
- procédure complète : OK

2. L'utilisateur connait son username et pas son mdp ==>
- [ ] procédure rapide : pas possible de cliquer sur le bouton ==> bloqué. 
- [ ] Rien n'indique qu'il faut cliquer sur s'identifier et passer en procédure complète pour résoudre ce cas
- procédure complète : 
a) Si LDAP : OK, sauf que 
- [ ] le message apparait en anglais plutôt que dans la langue de l'interface. 
- [ ] Pour le message en français, coquilles à la ligne 42 : ULYS --> ULIS et réinitialiser --> réinitialisé et "ou contactez le helpdesk du DTIC" à supprimer. https://github.com/SPW-DIG/metawal-core-geonetwork/blob/994ac81be5d3674efe5a0b13d372b083cd3d235d/services/src/main/resources/org/fao/geonet/api/Messages_fre.properties#L42
b) Si pas LDAP : 
- [ ] le message est en anglais
- [ ] aucun message n'est envoyé

3. L'utilisateur encode un mauvais login et un mauvais mot de passe : 
- Procédure rapide : OK
- Procédure complète : OK

4. L'utilisateur encode un login qui n'existe pas pour récupérer son mot de passe : OK sauf que
- [ ] Le message est en anglais

5. L'utilisateur ne connait plus son login : KO
- [ ] procédure rapide : pas possible de cliquer sur le bouton ==> bloqué. 
- [ ] procédure complète : Aucun moyen de signaler qu'on ne connait plus son login

6. L'utilisateur n'a pas encore de login : KO
- [ ] procédure rapide : pas possible de cliquer sur le bouton ==> bloqué. 
- [ ] procédure complète : Aucun moyen de demander la création d'un login

**Comment by vbombaerts** [comment]
Priorité basse car les utilisateurs qui se connectent actuellement à Metawal sont peu nombreux et que la procédure de login va être revue dans le projet DIG-2017-m11/A/1
