### ISSUE TITLE
Carte / Pas de fond de carte

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#3]

**Comment by fxprunayre** [comment]
BTW http://geoservices.valid.wallonie.be/arcgis/services/DONNEES_BASE/FDP_LIGHT/MapServer/WMSServer?LAYERS=0%2C1%2C2&TRANSPARENT=false&VERSION=1.1.1&FORMAT=image%2Fpng&SERVICE=WMS&REQUEST=GetMap&STYLES=&SRS=EPSG%3A4326&BBOX=0.771484375,48.97216796875,8.728515625,52.02783203125&WIDTH=582&HEIGHT=223 still return errors.

**Comment by fxprunayre** [comment]
A retester

**Comment by vbombaerts** [comment]
Ne fonctionne toujours pas. Un problème de version du WMS ?
1.1.1 dans la requête
1.3.0 annoncé dans le get capabilities. Stéphane me confirme que les versions 1.1.1 n'ont pas été créées.

**Comment by davinciagf** [comment]
Le comportement est assez bizarre. Je n'arrive pas à me connecter au WMS (simple requête get capabilities) lorsque j'ai un accès distant sur l'environnement de test. Lorsque je coupe la connexion j'ai le WMS qui me répond bien.
En environnement local (sans avoir une connection vpn vers l'env. de test)  l'affichage est ok:
![capture](https://f.cloud.github.com/assets/576292/1781945/28f59be4-68a0-11e3-9bb9-2a9ac80dd584.PNG)

**Comment by vbombaerts** [comment]
Puisqu'on ne trouve pas de solution à ce problème, je propose qu'on laisse tomber le panneau de recherche géographique dans la version 3.0 de Metawal. La plupart des données concernent de toute façon l'entièreté du territoire wallon.

Dans une version ultérieure, on réhabilitera la recherche géographique dans les critères de recherche avancés (Quoi ? Où ? Quand ? Qui ?).

**Comment by fxprunayre** [comment]
Tester avec http://geoservices.valid.wallonie.be/arcgis/rest/services/DONNEES_BASE/FDP_LIGHT et http://geoservices.valid.wallonie.be/arcgis/rest/services/DONNEES_BASE/FOND_PLAN_CARTE_2012_v1_RW

**Comment by vbombaerts** [comment]
Finalement résolu. Merci !
