### ISSUE TITLE
Modification des règles de connexion à WalOnMap pour les WMS et service REST

### ISSUE THREAD

**Issue by davinciagf** [SPW-DIG/metawal-core-geonetwork#301]
**WMS**
http://geoportail.wallonie.be/walonmap/#WMS=http://geoservices.wallonie.be/arcgis/services/FAUNE_FLORE/AHREM/MapServer/WMSServer|0 
**REST**
http://geoportail.wallonie.be/walonmap/?agsDynUrls=http://geoservices.wallonie.be/arcgis/rest/services/IMAGERIE/ORTHO_2015/MapServer
(remplacement de agsDynUrls par ADU)

**Comment by vbombaerts** [comment]
GDE l'a fait à la main. A vérifier en BD.

**Comment by fxprunayre** [comment]
Cf. #372
