### ISSUE TITLE
La suppression d'une fiche réinitialise la recherche

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#303]
Dans l'interface de recherche.

**Comment by fxprunayre** [comment]
Cf. https://github.com/geonetwork/core-geonetwork/issues/1421

**Comment by fxprunayre** [comment]
La fiche supprimée peut parfois toujours être dans les résultats (cf. https://github.com/geonetwork/core-geonetwork/issues/759) - mais c'est un autre problème.

**Comment by davinciagf** [comment]
Solution provisoire - Mise en place d'un timeout qui relance la recherche après qq sec.
Autre solution - supprimer la(es) référence(s) au niveau de la liste des MTD de la recherche ($scope.searchResults.records) mais comment connaître les MTd sélectionner et envoyer au niveau du service md.delete.batch ?

**Comment by fxprunayre** [comment]
Si c'est vraiment gênant opter pour le timeout car ce ne sera pas trivial de faire une correction propre (et côté GN on a une préférence pour attendre le passage à Solr qui nous permettra simplement de résoudre le pb)

**Comment by vbombaerts** [comment]
Nickel
