### ISSUE TITLE
Erreur d'import de fiches

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#305]
Import de fiches de Metawal (ISO 19139) vers Metawal4 (ISO 19115-3).
Fiches multilingues moissonnées depuis le catalogue du cadastre.
Import d'un MEF contenant plusieurs fiches.
Conversion ISO19139 vers ISO19115-3 cochée.
Fiches en question : http://metawal.wallonie.be/geonetwork/srv/fre/search?s_search=&s_E_any=belgie&s_timeType=true&s_E_hitsperpage=20&hl=fre 
![2016-02-03 15_31_10-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/12785160/6b6c65bc-ca8b-11e5-93a2-4e98746f01d4.png)

**Comment by fxprunayre** [comment]
Est-ce que la fiche n'existe pas dans le catalogue ? tester avec "Générer un nouvel identifiant".

Sinon, il y a un pb de conversion pour les fiches multilingues (cf. https://github.com/metadata101/iso19115-3/issues/18) mais n'empêche pas l'import.

**Comment by fxprunayre** [comment]
Problème pour les fiches multilingues corrigé. A déployer & retester

**Comment by davinciagf** [comment]
Importation avec succès pour http://metawal.wallonie.be/geonetwork/srv/fre/search?uuid=b47f2ffd-ebc9-413c-903f-d83af520fcdb

**Comment by fxprunayre** [comment]
Cf. #347
