### ISSUE TITLE
Consultation - mots coupés

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#306]
Eviter les mots coupés ou les couper selon les règles du français ;-p http://bdl.oqlf.gouv.qc.ca/bdl/gabarit_bdl.asp?T1=c%C3%A9sure&T3.x=0&T3.y=0 
![2016-02-03 22_43_41-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/12798126/fcbbe0a6-cac7-11e5-8e13-e12990ce0266.png)

**Comment by fxprunayre** [comment]
Fixed in https://github.com/geonetwork/core-geonetwork/commit/4d15539bfb71f732dbce222d9509faba0e782b57
