### ISSUE TITLE
L'aide doit amener à une aide spécifique à Metawal

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#307]
Forme à définir. Une aide en pdf est existante sur le géoportail mais il faut la mettre à jour.
A discuter.
![2016-02-03 22_55_04-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/12798378/60d7e6e2-cac9-11e5-803a-fcf1bf9c9d71.png)

**Comment by fxprunayre** [comment]
Vous pensez qu'on ne peut vraiment pas arriver à utiliser/compléter http://geonetwork-opensource.org/manuals/trunk/eng/users/index.html ? Quand je vois le nombre de guides en PDF ou autre fait à droite à gauche par des stagiaires ou pas, je trouve ça un peu dommage. 

Pour l'ISO19115-3, je serai tenté de faire une doc spécifique (et du coup peut être un fork plus métier pour Metawal) ... ?

De mon côté, j'ai prévu de mettre à jour la doc sur les ressources associées.

En plus de bouton "needHelp" dans l'interface créer une doc par standard (en se basant sur l'aide et la configuration de l'éditeur).

# Documentation par standards

Ajouter une section standards (http://geonetwork-opensource.org/manuals/trunk/eng/users/annexes/index.html)

### TOC

Standards
- Saisie
  - Vue simple (config-editor.xml)
  - Vue Géoportail 
  - Onglet 1 (config-editor.xml)
  - Champ (strings.xml ou labels.xml)
    - Définition (strings.xml ou labels.xml)
    - Exemple (labels.xml)
    - Type de ressource (NA)
    - Obligatoire (XSD ?)
    - Cardinalité (XSD ? ou avec config-editor.xml/@or)
    - Liste de valeurs (codelist.xml)
    - Xpath (config-editor.xml)
    - Element name (config-editor.xml)
  - Action / button (config-editor.xml + strings.xml)
  - Vue avancée
  - Vue XML
- Glossaire (labels.xml + codelist.xml)

Créer des liens vers la doc générale. eg.
- si mots clés => saisie des mots clés
- si bouton ressource en ligne => Associer un WMS, ...

#### Description des vues possibles
- Scan des vues d'édition
  https://github.com/SPW-DIG/iso19115-3/blob/develop/src/main/plugin/iso19115-3/layout/config-editor.xml#L372
- Ajouter une description générale pour la vue (https://github.com/SPW-DIG/iso19115-3/blob/develop/src/main/plugin/iso19115-3/loc/fre/strings.xml#L42)
- Pour les onglets et les sections faire des paragraphes et ajouter une description générale dans strings.xml
- Liste des champs
  - Description: 
  - titre
  - xpath
  - définition
  - Récupération des définitions dans labels.xml
  - Récupération des listes de valeurs dans codelists.xml
- Pour les boutons du formulaire ajouter une aide dans strings.xml

#### Glossaire
- Sur la base de tout labels.xml et codelists.xml 

### Géneration & publication

Création de la doc:
a) Script de génération 
b) Sous forme de service (donc dynamique via l'appli)

Publication sur un site web ou génération lors du build de l'appli et intégration dans le WAR.

Travaux similaires:
- eg. process XSL https://github.com/geonetwork/core-geonetwork/blob/develop/docs/schema-loc-to-rst.xsl pour convertir labels.xml en glossaire au format RST.
- Service Jeeves en ngdoc https://github.com/geonetwork/core-geonetwork/blob/develop/web-ui-docs/generate-jeeves-services-doc.xsl

**Comment by davinciagf** [comment]
Je serais également pour un merge des deux mais en conservant certaines parties bien spécifiques à METAWAL (guide de comment compléter les MTD en RW,...).

**Comment by vbombaerts** [comment]
Je pense aussi qu'il faut éviter la dispersion. Mais il faut que l'aide mène l'utilisateur sur qqch de directement utile et de spécifique. Si la solution que tu proposes le permet, faisons un test.

**Comment by davinciagf** [comment]
Première ébauche du process de création de l'aide (16f9a54).
Ce process permet de récupérer les informations au niveau des fichiers config-editor, strings, codelists et labels. Le résultat permet de fournir:
- une description des différents onglets, des différentes sections et des différents champs composants les différentes vues
- une description de l'ensemble des champs de la norme (listing + description)
- une description de l'ensemble des listes de code de la norme (listing + description)

Quelques éléments restent à faire:
- Gestion des doublons (mais contexte différents. Exemple de cit:title)
- Gestion des liens vers les listes de codes (pas de références vers le fichier codelists)
- Vérification de la transformation du rst en html (conversion des balises html présents dans le xml (et donc dans le rst))
- Ajout de liens
- Ajout d'images pour les vues, les onglets et les sections 
- Vérifier la présence des field disposant d'un attribut name dans le fichier string (metadataAbstract est absent par exemple)

**Comment by fxprunayre** [comment]
Suite aux travaux d'Arnaud quelques compléments et une première version en ligne pour discussion.

Le script de génération https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.x/docs/utility/config-editor-to-rst.xsl

Démo en ligne
- Une entrée par standard http://files.titellus.net/tmp/fr/standards/index.html
- Pour chaque standard 
  - eg.ISO19115-3 avec personnalisation metawal http://files.titellus.net/tmp/fr/standards/iso19115-3.html
  - la liste des vues eg. vue Metawal http://files.titellus.net/tmp/fr/standards/iso19115-3.html#iso19115-3-view-metawal
  - les onglets de la vue
  - les champs de l'onglet (avec liens vers la description de l'élément)
  - les informations techniques sur le standard
  - la liste des éléments : description, valeurs recommandées, eg d'encodage (à partir d'une fiche modèle) 
  - la liste des codelists

Les points intéressants :
- possibilité d'ajouter des images (pour l'instant 2 exemples sur les onglets), mais pourrait être étendu pour les sections, voire les buttons
- le script permet de vérifier qu'il ne manque pas de libellé !

A compléter & discuter :
- qu'est ce qu'on affiche où ? organisation de chaque type de section
- config-editor / gérer les cas particulier (eg. section dans section)
- config-editor / gérer les boutons
- config-editor / gérer les champs personnalisé avec un modèle
- config-editor / figure pour autre chose que des sections
- config-editor / gérer les attributs avancés et conditions
- labels.xml / gérer le XML dans les blocs d'aide
- labels.xml / gérer les contexts
- labels.xml / gérer les displayIf (eg. conditions sur les helper)
- codelist.xml / gérer lien éléments / codelist
- style / tableau avec scrollbar horizontale - à améliorer ?
- schema-ident / Ajouter nom et URL du standard
- bug - référence manquante, reporter quelques correctifs dans les schémas 19110
- intégrer au build maven (au lieu de script shell - linux only)
- faire une PR GN

Qu'en pensez vous ?

**Comment by davinciagf** [comment]
Améliorations:
- Pagination (meilleur découpage par champs)
- Visuel
- Liens

**Comment by davinciagf** [comment]
en lien avec #191

**Comment by fxprunayre** [comment]
Fait pour 4.0:
- [x] config-editor / gérer les boutons
- [x] config-editor / figure pour sections, action, text
- [x] labels.xml / gérer le XML dans les blocs d'aide
- [x] labels.xml / gérer les contexts
- [x] labels.xml / gérer les displayIf (eg. conditions sur les helper)
- [x] schema-ident / Ajouter nom et URL du standard cf. https://github.com/geonetwork/core-geonetwork/pull/1478
- [x] ajouter la doc dans le WAR de l'application
- [x] corriger tous les warnings/error sphinx
- [x] intégrer au build maven (au lieu de script shell - linux only)
- [x] faire une PR GN. CFV https://github.com/geonetwork/core-geonetwork/pull/1514

A faire en 4.1:
- [ ] config-editor / gérer les cas particulier (eg. section dans section)
- [ ] config-editor / gérer les champs personnalisé avec un modèle
- [ ] config-editor / gérer les attributs avancés et conditions
- [ ] codelist.xml / gérer lien éléments / codelist
- [ ] style / tableau avec scrollbar horizontale - à améliorer ?
- [ ] Pagination (meilleur découpage par champs)
- [ ] Visuel
- [ ] Liens

**Comment by vbombaerts** [comment]
Bcp d'efforts pour pas grand-chose. Pas suffisamment rentable
