### ISSUE TITLE
Mots-clés INSPIRE - problème

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#308]
![2016-02-03 23_06_16-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/12798645/cc5f0bd8-caca-11e5-9441-e37b55361390.png)

**Comment by davinciagf** [comment]
Ce problème est lié au fait que le serveur n'est pas configué par défaut pour supporter l'UTF-8.
De ce fait le service ThesaurusService (getKeywords) ne retourne pas de réponse pour les requêtes avec accent comme:

http://metawal4.spacebel.be/geonetwork/srv/fre/keywords?pNewSearch=true&pTypeSearch=2&pThesauri=external.theme.inspire-theme&pMode=searchBox&maxResults=1&pKeyword=Conditions%20atmosph%C3%A9riques

Il suffit pour d'ajouter la configuration suivante pour mettre à jour le serveur (conf/server.xml):

```
URIEncoding="UTF-8" 
```

au niveau du protocol="AJP/1.3"
