### ISSUE TITLE
Boutons share : utiliser les mêmes réseaux sociaux que le Géoportail

### ISSUE THREAD

**Issue by metawal** [SPW-DIG/metawal-core-geonetwork#31]
Afin de garantir l'harmonie entre Metawal et le Géoportail, il faudrait utiliser les mêmes réseaux sociaux :
- Facebook,
- Twitter,
- LinkedIn,
- Google+,
- Mail.

Sur le Géoportail, chacun de ces boutons permet de partager la page en cours sur les réseaux sociaux.

**Comment by vbombaerts** [comment]
Proposition ajoutée au wiki
