### ISSUE TITLE
Répertoire de backup des fiches supprimées

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#310]
Ajouter l'info dans l'interface d'admin (et s'assurer que le répertoire existe !!)
![2016-02-03 23_48_17-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/12799732/c4ae1e00-cad0-11e5-9bb2-de0247cefe61.png)

**Comment by fxprunayre** [comment]
Question posée: https://github.com/geonetwork/core-geonetwork/issues/1427

**Comment by vbombaerts** [comment]
On a eu le cas de fiches supprimées par inadvertance impossibles à récupérer car le WEB-INF/data/removed n'existait pas. Lors de l'installation de l'app, le war n'avait pas été décompressé car pas nécessaire et donc le répertoire /removed n'avait jamais été créé.

**Comment by fxprunayre** [comment]
Fait, le répertoire est maintenant dans datadir/backup par défaut. A redéployer.

**Comment by vbombaerts** [comment]
Ajouter un lien de l'admin vers le répertoire des "removed" pour récupérer les fiches effacées. Actuellement on n'a pas d'accès direct à ce répertoire depuis l'admin.
