### ISSUE TITLE
CSW virtuel et anonymisation

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#312]
Est-il possible de faire disparaitre des mots-clés dans un CSW virtuel ?
Use case : le dictionnaire des mots-clés InfraSIG : ces mots-clés sont spécifiquement utilisés pour catégoriser les ressources par rapport à leur gestion et créer des tableaux de bord. Ils ne sont utiles que dans le cadre de notre IDS. Je voudrais que les outils à l'intérieur de l'IDS qui interrogent le CSW puissent accéder à ces mots-clés, mais que ceux qui l'interrogent depuis l'extérieur n'y aient pas accès (INSPIRE par ex). Est-il possible du coup de les supprimer du CSW virtuel, sachant que les mots-clés de ce thésaurus sont notamment utilisés pour filtrer ce qui doit appraître dans le CSW INSPIRE ?

**Comment by fxprunayre** [comment]
> Est-il possible de faire disparaitre des mots-clés dans un CSW virtuel ?

A priori non.

A essayer: en utilisant les attributs permettant de cacher des sections dans les fiches aux utilisateurs anonymes (ie. gco:nilReason = withHeld). Dans ce cas ce ne serait pas spécifique CSW mais en fonction de l'authentification. Sinon, il faut créer autre chose qui filtre les réponses CSW (dans les différents formats et opérations).

**Comment by vbombaerts** [comment]
Le géoportail a besoin de ces infos pour allumer ou éteindre les boutons !
