### ISSUE TITLE
Sign in failure

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#315]
Je crois que j'ai mis du temps à éditer. J'ai obtenu cette erreur :
![2016-03-02 16_14_03-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/13464533/ee77a306-e091-11e5-916c-be500a0c4508.png)

**Comment by vbombaerts** [comment]
Serait du à un redémarrage du serveur ?

**Comment by fxprunayre** [comment]
> Serait du à un redémarrage du serveur ?

Ca peut arriver quand la session est terminée (ie. https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.x/web/src/main/filters/prod.properties#L42) et donc aussi à un redémarrage. Dans le cas d'une fin de session, il y a un message un peu avant la fin de la session https://github.com/geonetwork/core-geonetwork/pull/1126. Quand il y a reboot, pas de message. Sous certain Tomcat, même avec redémarrage, il restore les sessions qui étaient actives.

Donc ce serait un cas particulier à gérer dans EditorController.

**Comment by davinciagf** [comment]
Bug lié à l'arrêt du serveur.
