### ISSUE TITLE
Testing conformité INSPIRE

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#316]
Encore quelques erreurs à corriger dans la traduction de l'ISO 19115-3 vers ISO 19139 ??
- Metawal prod - donnée
  Fiche : http://metawal.wallonie.be/geonetwork/srv/fre/csw-inspire?REQUEST=GetRecordById&SERVICE=CSW&version=2.0.2&outputSchema=http://www.isotc211.org/2005/gmd&elementSetName=full&id=03abb4c1-5f53-46bb-94fa-359f3912a041
  Validateur INSPIRE : http://inspire-geoportal.ec.europa.eu/resources/sandbox/INSPIRE-86e45dd4-e5e6-11e5-9c5d-52540023a883_20160309-120317/datasets/1/resourceReport/
- Metawal 4 test - donnée
  Fiche : http://metawal4.test.wallonie.be/geonetwork/srv/fre/csw-inspire?REQUEST=GetRecordById&SERVICE=CSW&version=2.0.2&outputSchema=http://www.isotc211.org/2005/gmd&elementSetName=full&id=03abb4c1-5f53-46bb-94fa-359f3912a041
  Validateur INSPIRE : http://inspire-geoportal.ec.europa.eu/resources/sandbox/INSPIRE-e21b596e-e5e6-11e5-9c5d-52540023a883_20160309-120550/datasets/1/resourceReport/
- Metawal prod - service
  Fiche : http://metawal.wallonie.be/geonetwork/srv/fre/csw-inspire?REQUEST=GetRecordById&SERVICE=CSW&version=2.0.2&outputSchema=http://www.isotc211.org/2005/gmd&elementSetName=full&id=5712704b-a096-494b-b771-5a6d9aba1d7f
  Validateur INSPIRE : http://inspire-geoportal.ec.europa.eu/resources/sandbox/INSPIRE-81acf581-e5e7-11e5-9c5d-52540023a883_20160309-121018/services/1/resourceReport/
- Metawal 4 test - service
  Fiche : http://metawal4.test.wallonie.be/geonetwork/srv/fre/csw-inspire?REQUEST=GetRecordById&SERVICE=CSW&version=2.0.2&outputSchema=http://www.isotc211.org/2005/gmd&elementSetName=full&id=5712704b-a096-494b-b771-5a6d9aba1d7f
  Validateur INSPIRE : http://inspire-geoportal.ec.europa.eu/resources/sandbox/INSPIRE-395d2607-e5e7-11e5-9c5d-52540023a883_20160309-120816/services/1/resourceReport/

**Comment by vbombaerts** [comment]
Voir aussi #275

**Comment by fxprunayre** [comment]
>  Encore quelques erreurs à corriger dans la traduction de l'ISO 19115-3 vers ISO 19139 ??

Oui en partie.

> Fiche : http://metawal.wallonie.be/geonetwork/srv/fre/csw-inspire?REQUEST=GetRecordById&SERVICE=CSW&version=2.0.2&outputSchema=http://www.isotc211.org/2005/gmd&elementSetName=full&id=03abb4c1-5f53-46bb-94fa-359f3912a041

Rapport : "The required metadata element "Coordinate Reference System" is present, but does not contain any of the coordinate reference system identifiers (EPSG URIs) required by the Technical Guidelines"

Remplacer par un des systèmes de coordonnées du TG corrige le problème :

```
<gmd:code>
   <!-- Invalid
   <gco:CharacterString>http://www.opengis.net/def/crs/EPSG/0/31370</gco:CharacterString>
   -->
   <gco:CharacterString>http://www.opengis.net/def/crs/EPSG/0/3035</gco:CharacterString>
</gmd:code>
```

> Metawal 4 test - donnée
- Pb de CRS comme en prod
- Pb d'ordre dans la transfo pour spatialRepType
- Pb sur le nom de l'élément distributinfo et sur multiple distributionInfo (en lien avec le transfert des liens pour le géoportail)

**Comment by fxprunayre** [comment]
> Metawal 4 test - service

Problème sur section DQ, serviceType. Corrigé.

**Comment by fxprunayre** [comment]
PR proposée côté TC211 https://github.com/ISO-TC211/XML/pull/159

A redéployer.

**Comment by vbombaerts** [comment]
Pour les données :

Encore un problème au niveau des adresses mail.
`The content "" of element <EmailAddress> does not match the required simple type. Value "" contravenes the pattern facet "[^@]+@[^\.]+\..+" of the type emailType at column 40, line 311`

Perso, je n'ai pas trouvé l'origine du problème...
Voir différence entre rapport prod et test.

Donnée prod :
- http://metawal.wallonie.be/geonetwork/srv/fre/csw-inspire?REQUEST=GetRecordById&SERVICE=CSW&version=2.0.2&outputSchema=http://www.isotc211.org/2005/gmd&elementSetName=full&id=89e93887-bc8c-4409-809d-ec53a0986023
- http://inspire-geoportal.ec.europa.eu/resources/sandbox/INSPIRE-2aba51c3-089d-11e6-a553-52540023a883_20160422-171620/datasets/1/resourceReport/

Donnée test MW4 :
- http://metawal4.test.wallonie.be/geonetwork/srv/fre/csw-inspire?REQUEST=GetRecordById&SERVICE=CSW&version=2.0.2&outputSchema=http://www.isotc211.org/2005/gmd&elementSetName=full&id=89e93887-bc8c-4409-809d-ec53a0986023
- http://inspire-geoportal.ec.europa.eu/resources/sandbox/INSPIRE-453b2e67-089e-11e6-a553-52540023a883_20160422-172414/services/1/resourceLocator1/discovery/services/1/resourceReport/

Pour les services : (à faire)

**Comment by vbombaerts** [comment]
Pour les services :

Le même problème au niveau des adresses mail.

En prod :
- http://metawal.wallonie.be/geonetwork/srv/fre/csw-inspire?REQUEST=GetRecordById&SERVICE=CSW&version=2.0.2&outputSchema=http://www.isotc211.org/2005/gmd&elementSetName=full&id=96572e0e-63d0-4a9b-98f4-0e257da19e28
- http://inspire-geoportal.ec.europa.eu/resources/sandbox/INSPIRE-30b1de24-0c62-11e6-a553-52540023a883_20160427-122414/services/1/resourceReport/

En test MW4 :
- http://metawal4.test.wallonie.be/geonetwork/srv/fre/csw-inspire?REQUEST=GetRecordById&SERVICE=CSW&version=2.0.2&outputSchema=http://www.isotc211.org/2005/gmd&elementSetName=full&id=96572e0e-63d0-4a9b-98f4-0e257da19e28
- http://inspire-geoportal.ec.europa.eu/resources/sandbox/INSPIRE-50e15d69-0d45-11e6-a553-52540023a883_20160428-153004/services/1/resourceLocator1/discovery/services/1/resourceReport/
