### ISSUE TITLE
Validation d'une fiche - prévoir un indicateur de validation manuelle

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#317]
Avant de publier une fiche, on opère deux validations :
- une validation automatique des règles ISO, INSPIRE, schematron
- une validation de contenu sur le résumé, le titre, la généalogie...

Actuellement, seule la validation automatique fait l'objet d'un indicateur de validation.
Il faudrait ajouter un indicateur sur la validation manuelle.

On pourrait envisager une appellation du type :
- Validation des standards
- Validation du contenu

**Comment by fxprunayre** [comment]
Est-ce que l'état de la fiche ne pourrait pas correspondre à ça ? 
http://geonetwork-opensource.org/manuals/trunk/eng/users/user-guide/workflow/life-cycle.html

**Comment by vbombaerts** [comment]
Si on peut avoir une fiche approuvée non-publiée et une fiche publiée non-approuvée, alors ça pourrait peut-être convenir.
