### ISSUE TITLE
Autocomplétion des mots-clés - améliorer/clarifier présentation

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#319]
Quand on tape un mot-clé provenant du thésaurus et qu'on le sélectionne, il apparait dans une vignette bleue mais la chaine de recherche reste dans la boite des mots-clés. Du coup :
1. On pense qu'on l'a indiqué deux fois
2. On ne trouve pas tout de suite comment ajouter un deuxième mot-clé
![2016-04-22 15_10_54-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/14742431/7ea1dea6-089c-11e6-9932-f6e93a723585.png)
==> Proposition :
1. Dès que le mot-clé a été sélectionné, supprimer le texte tapé par l'utilisateur pour qu'il puisse directement commencer à taper un autre mot-clé
2. Placer le curseur à droite du dernier mot-clé inséré (vignette bleue), puis à la ligne quand la première ligne est pleine, etc.

**Comment by davinciagf** [comment]
Non Reproduit en local et en test (Chrome et FF). Lorsque l'on tape un mot-clé provenant du thésaurus et qu'on le sélectionne, ce dernier est supprimé de la zone de recherche et on retrouve le texte "Recherche dans le thésaurus..."
![capture](https://cloud.githubusercontent.com/assets/576292/14816848/626bee56-0bb3-11e6-9fe1-e8fe643226f7.JPG)
