### ISSUE TITLE
RSS ne fonctionne pas

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#32]
Erreur quand on clique sur RSS.
De plus le template correspond au template de base GN et pas au template Metawal

![image 616](https://f.cloud.github.com/assets/6093597/1662161/b43c95d6-5bf8-11e3-88b1-27a0dcb947a5.png)

**Comment by vbombaerts** [comment]
RSS est accessible, mais l'adresse des fiches n'est pas juste.
![image 629](https://f.cloud.github.com/assets/6093597/1782037/b07b898c-68a2-11e3-86ee-fc1b5007e312.png)
![image 630](https://f.cloud.github.com/assets/6093597/1782040/b2d293a6-68a2-11e3-80ce-87c496129b91.png)

**Comment by fxprunayre** [comment]
Les liens dans le flux du serveur de démo sont ok
http://metawal.spacebel.be/geonetwork/srv/eng/rss.search?sortBy=changeDate
http://metawal.spacebel.be/geonetwork?uuid=a24c50a2-ae0d-4ad8-85d3-8b7b218f3081&hl=fre

Il y a donc un pb sur la plateforme de test SPW. Est ce que 
http://metawal3.test.wallonie.be/geonetwork?uuid=a24c50a2-ae0d-4ad8-85d3-8b7b218f3081&hl=fre
http://metawal3.test.wallonie.be/geonetwork/?uuid=a24c50a2-ae0d-4ad8-85d3-8b7b218f3081&hl=fre
http://metawal3.test.wallonie.be/geonetwork/srv/fre/search?uuid=a24c50a2-ae0d-4ad8-85d3-8b7b218f3081&hl=fre
fonctionne ?

Probablement un pb de redirection entre le serveur apache et le JBoss.

**Comment by davinciagf** [comment]
Correction via la modification de la configuration apache du serveur
