### ISSUE TITLE
Mot-clés de thésaurus

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#321]
Message d'erreur quand on enregistre des mots-clés provenant d'un thésaurus hiérarchique, quelle que soit la méthode de sélection
![2016-04-22 15_23_40-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/14742804/567620de-089e-11e6-8b27-5b92f14776c0.png)

**Comment by davinciagf** [comment]
Non reproduit en local ni en test (http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.edit#/metadata/4443547)
![capture](https://cloud.githubusercontent.com/assets/576292/14816570/ed6f946e-0bb1-11e6-8ed1-95738b2170e9.JPG)

**Comment by vbombaerts** [comment]
Ca se produit à l'enregistrement de la fiche. cf. http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/db34d425-2f19-46bd-9e56-f375a718d3c6

**Comment by davinciagf** [comment]
Attention, la fiche est en anglais! Tu dois donc te mettre en http://metawal4.test.wallonie.be/geonetwork/srv/eng/catalog.edit#/metadata/4158426

**Comment by vbombaerts** [comment]
Ca marche. Je ne maitrise pas encore toutes les subtilités...
