### ISSUE TITLE
Création de fiche / édition - vue par défaut = géoportail

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#322]
Par défaut, présenter la vue géoportail quand l'utilisateur lance une édition.

**Comment by davinciagf** [comment]
Via l'admin/Paramètres:
Voir Métadonnées/Configuration de l'éditeur de métadonnées
Pour l'ISO19115-3 définir le paramètre "defaultTab" à "mw-metadata" (voir exemple ci-dessous)
![capture](https://cloud.githubusercontent.com/assets/576292/14816216/d4dec20a-0baf-11e6-8c63-9bc3c0732d57.JPG)

**Comment by vbombaerts** [comment]
OK. Je connaissais pas.

**Comment by vbombaerts** [comment]
Ajouter dans la doc
