### ISSUE TITLE
Recherche par facettes - type de ressource

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#323]
Permettre de cocher plusieurs types de ressource en même temps (donnée OU application)

**Comment by fxprunayre** [comment]
Cela avait été fait dans un dév "custom" par camptocamp pour l'ifremer sur l'ancien mécanisme des facettes (ie. avant le support des facettes hierarchiques). Le principe consiste à conserver une liste des facettes sélectionnés et complétés par les nouvelles facettes après affinage. Ce travail n'a pas été mis dans GN. 

eg. http://sextant.ifremer.fr/fr/geoportail/sextant

![image](https://cloud.githubusercontent.com/assets/1701393/16679757/538a04a2-44ea-11e6-9b25-359844a9dea9.png)

A première vue, le porter dans GN n'est pas trivial d'autant plus que la hiérarchie ammène une compléxité supplémentaire. De mon côté, une préférence pour implémenter ça lors du passage à Solr selon le niveau d'urgence.

**Comment by vbombaerts** [comment]
Le fait que la sélection soit conservée et qu'on puisse restreindre les résultats de recherche à "uniquement ce qui est sélectionné" permet de contourner le problème.
