### ISSUE TITLE
Impossible d'importer une fiche de service

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#324]
Import d'une fiche XML de service venant de la prod --> KO
fiche de données OK

![2016-04-27 12_27_25-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/14849685/b0617f74-0c74-11e6-835e-1cfac518eef9.png)

**Comment by davinciagf** [comment]
Essaie en générant un nouvelle id.

**Comment by vbombaerts** [comment]
Au temps pour moi.
