### ISSUE TITLE
Associer un service à une donnée - liste des suggestions

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#325]
Quand on commence à taper dans le champ pour chercher un service, la liste disparait, puis un moment elle réapparait --> la laisser et l'affiner à chaque lettre tapée

![2016-04-28 15_42_18-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/14887927/212bf462-0d58-11e6-98eb-e0dd26e64a9f.png)
![2016-04-28 15_41_19-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/14887929/22e4301c-0d58-11e6-92c1-639aa9e8bab8.png)
![2016-04-28 15_42_44-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/14887930/2518fb74-0d58-11e6-8323-7d92084a7ad9.png)

**Comment by fxprunayre** [comment]
Fait https://github.com/SPW-DIG/metawal-core-geonetwork/commit/86c853c42d3bf2e938f66bedebdc57780a8551f6

**Comment by vbombaerts** [comment]
Apparemment n'a jamais été déployé dans Metawal. Quid @davinciagf ?

**Comment by stephyritz** [comment]
Comportement toujours "problématique" dans la version 3.6.1 déployée à ce jour en test. Pas d'urgence de mon côté mais visiblement le code correctif est prêt. Je déplace cela pour le milestone 3.8 car a priori ce délai semble raisonnable. Je vous laisse commenter/déplacer le milestone si ce n'est pas le cas. Pas d'urgence de mon côté.

**Comment by fxprunayre** [comment]
A améliorer avec le passage à ES.
