### ISSUE TITLE
Associer service à une donnée - erreur sur <Enter>

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#326]
Quand on est en train de taper un mot-clé de recherche, puis qu'on tape `<Enter>`, on obtient une page d'erreur. 
![2016-04-28 15_47_12-apache tomcat_7 0 59 - rapport d erreur](https://cloud.githubusercontent.com/assets/6093597/14888080/c43ff1e4-0d58-11e6-9f4b-b64c01368840.png)

**Comment by davinciagf** [comment]
La fonctionnalité d'aide introduirait l'erreur. C'est l'absence du type (type="button") au niveau de la balise button de l'aide qui entraienrait ce type d'erreur. 
A modifer sur GN

**Comment by davinciagf** [comment]
Fait dans GN - https://github.com/geonetwork/core-geonetwork/pull/1601
