### ISSUE TITLE
Session expirée - coquille

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#327]
![2016-04-28 16_42_46-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/14889784/7cb5e60a-0d60-11e6-8a5b-94227d4af997.png)

A deux endroits : a (très) probablement expirée --> a (très) probablement expiré

**Comment by fxprunayre** [comment]
Fixed : https://www.transifex.com/geonetwork/core-geonetwork/translate/#fr/core/55659498?qt=expir%C3%A9
