### ISSUE TITLE
Ressources en lignes - services

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#328]
Quand on ajoute un service comme ressource en ligne, afficher le name et le title, pas juste le name. Dans InfraSIG, le name est utilisé pour stocker un identifiant numérique de layer, donc c'est pas parlant pour l'utilisateur.
![2016-04-28 17_08_02-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/14890685/e73ee1ea-0d63-11e6-83d2-b0ea64348523.png)

**Comment by vbombaerts** [comment]
Requalifié en majeur. Difficile de travailler uniquement sur base du layer name... On ne retrouve plus qui est qui.
![2018-02-06 11_37_13-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/35854971-2888e7ae-0b32-11e8-982a-c475ada3b217.png)

**Comment by fxprunayre** [comment]
Il y a une infobulle avec la description
![image](https://user-images.githubusercontent.com/1701393/35855938-da024f1e-0b34-11e8-9a22-a8096d878d57.png)

Remplacement du name par la description pour les ressources OGC. Fait dans GN.

Je déplace dans maintenance 2017.

A tester après déploy.

**Comment by fxprunayre** [comment]
Cf. https://github.com/geonetwork/core-geonetwork/commit/2b85f4e9d94f18914026d8e6bc399d352333bf8a

**Comment by gdetry** [comment]
Référencé dans #438
