### ISSUE TITLE
Coquilles etc

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#329]
Compilation de petites erreurs à corriger. 
- le --> la
  ![2016-05-03 11_10_59-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/14978970/d194455a-111f-11e6-83d3-983c632ca6bd.png)
-

**Comment by vbombaerts** [comment]
- deux e en trop
  ![2016-05-03 12_29_44-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/14980754/e58adca8-112a-11e6-9576-7e457b157b4e.png)

**Comment by vbombaerts** [comment]
- noeudet --> noeud et
- Seul les --> Seuls les

![2016-06-08 14_47_51-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/15894801/43c7668c-2d88-11e6-955f-1bf2aa8b0a5d.png)
- a demandé --> à demander

![2016-06-08 14_48_55-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/15894841/6a88dd32-2d88-11e6-8e07-9034744ac018.png)

**Comment by davinciagf** [comment]
Modifs faites dans transifex pour :
" Seuls les ..."
" ... à demander ..."
" et logo"
@fxprunayre (à récupérer)

Correction déjà apportée dans transifex (à vérifier en test - suite à la mise à jour des fichiers)

Correction "le" en "la" à commiter (@davinciagf)

**Comment by fxprunayre** [comment]
Traductions transifex récupérées. A tester.

**Comment by davinciagf** [comment]
Ok super

**Comment by vbombaerts** [comment]
OK
