### ISSUE TITLE
Infos manquantes dans la fiche métadonnée

### ISSUE THREAD

**Issue by metawaltest** [SPW-DIG/metawal-core-geonetwork#33]
Les champs point de contact et généalogie sont vides, ex : fiches COSW et CNSW

**Comment by fxprunayre** [comment]
Problème sur la plateforme de test de la région - à redéployer. Doublon cf. #1

**Comment by fxprunayre** [comment]
Je ferme, c'est un doublon.

**Comment by vbombaerts** [comment]
doublon #1 et #73
