### ISSUE TITLE
Impossible de moissonner Metawal prod depuis Metawal 4 test

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#330]
Je peux configurer le moissonneur, mais il ne remonte aucune fiche.

**Comment by davinciagf** [comment]
Moissonnage en local avec succès, j'ai précisé les paramètres suivants: 
- typical output schema

A retester sur l'env de test.

**Comment by vbombaerts** [comment]
OK. Etre plus explicite sur la signification de ce paramètre. Par défaut, si je ne sais pas ce que c'est, je ne touche pas...

**Comment by vbombaerts** [comment]
J'ai précisé l'output schema mais ça ne fonctionne pas.

**Comment by davinciagf** [comment]
Test réalisé sur Metawal en production:
- via noeud GN = OK 
- via CSW = OK (**attention à préciser Typical output schemas**) : 

![screen shot 2018-01-25 at 22 38 28](https://user-images.githubusercontent.com/576292/35413906-34d86486-0221-11e8-97e4-db78dcc0971d.jpg)

Une adaptation a été réalisée afin que le typical output schemas soit pré-configuré dès la création d'un nouveau moissonneur (valeur par défaut défaut fixée à csw-iso19139). Elle est disponible en v3.4.0

**Comment by vbombaerts** [comment]
OK, ça marche.
![2018-04-18 14_32_06-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/38932034-5ca347f8-4315-11e8-9831-2288d56e3bb8.png)
![2018-04-18 14_32_20-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/38932037-5ecdc4c2-4315-11e8-9a65-877aae2a2f55.png)
![2018-04-18 14_32_28-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/38932041-60a6f7b4-4315-11e8-85d5-928b2183fbf6.png)
