### ISSUE TITLE
Editeur "geoportail" - erreur encodage mots clés thésaurus INSPIRE/GEMET

### ISSUE THREAD

**Issue by davinciagf** [SPW-DIG/metawal-core-geonetwork#334]
Valable pour :
- éditeur "geoportail"
- Thesaurus INSIRE et GEMET dans un même onglet

Le thésaurus GEMET n'est pas disponible dans sa version hiérarchisée si l'on a précédemment encoder un mots clés INSPIRE.

**Comment by davinciagf** [comment]
https://github.com/SPW-DIG/iso19115-3/commit/a82dd653b7df9ef7274a77975e78e0461f301ac9

Remplacement des fonctions `contains` par `text()` afin de préciser avec exactitude le contenu du titre du thesaurus etant donné que pour ces deux thesaurus le titre contient le terme GEMET. `Contains` ne permet pas de préciser la dénomination exact!

**Comment by vbombaerts** [comment]
Pas réussi à reproduire l'erreur, donc je considère résolu.
