### ISSUE TITLE
Moissonnage - non prise en compte d'une transformation xsl

### ISSUE THREAD

**Issue by davinciagf** [SPW-DIG/metawal-core-geonetwork#336]
Lors de la sauvegarde des paramètres de moissonnage d'un protocole CSW, la transformation xsl n'est pas conservée.

**Comment by vbombaerts** [comment]
J'imagine que le transformations est conservée, mais les résultats ne sont pas top...

![2018-04-18 15_36_11-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/38935552-e762e548-431e-11e8-882e-4c9ed1e3f738.png)
![2018-04-18 15_43_17-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/38935693-43cebf5a-431f-11e8-9bdb-3bb5bf7811cb.png)
![2018-04-18 15_36_45-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/38935566-f099a2f0-431e-11e8-8ca3-4472da104b82.png)
![2018-04-18 15_36_53-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/38935581-f658ce28-431e-11e8-8498-64d87b810c79.png)
![2018-04-18 15_39_14-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/38935587-fcfbe1fc-431e-11e8-9df0-147b7757490f.png)
