### ISSUE TITLE
Coquille

### ISSUE THREAD

**Issue by davinciagf** [SPW-DIG/metawal-core-geonetwork#337]
Lieu Moissonnage - Protocole GN
![capture](https://cloud.githubusercontent.com/assets/576292/16764200/15e6c284-482d-11e6-872b-2edc97f188ce.PNG)

**Comment by davinciagf** [comment]
Corrigé dans transifex (@fxprunayre)

**Comment by fxprunayre** [comment]
Fait. Au passage, peux tu vérifier l'histoire du paramètre ldap dans la gestion des utilisateurs qui utilise maintenant l'API ? Cf. https://github.com/SPW-DIG/metawal-core-geonetwork/commit/2b597c7a0abfa0dea02ec66ea7d28a0a97fbe315#diff-f8b6bb6d8228e27c0a654290c177b695R365

**Comment by vbombaerts** [comment]
OK.
