### ISSUE TITLE
Consultation - Ouvrir une fiche dans un nouvel onglet

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#338]
En mode recherche, pas possible d'ouvrir une fiche dans un nouvel onglet. Au lieu que la fiche apparaisse, c'est la page d'accueil du catalogue qui apparait. Pas pratique quand on veut comparer des fiches.
A partir du catalogue en mode contribution, ça fonctionne.

**Comment by davinciagf** [comment]
Je n'ai pas reproduit en local.
Peux-tu décrire la procédure? Ouverture via clic droit depuis le titre d'une fiche en mode recherche et éditeur?

**Comment by vbombaerts** [comment]
Testé à l'instant et OK.
