### ISSUE TITLE
Consultation - vues en erreur

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#339]
Strictement au niveau de l'affichage :
- Pour les fiches en ISO 19139
- vue par défaut : OK
- Metawal : OK
- Geoportail : KO
- Pour les vues en ISO 19115-3
- défaut : OK
- Metawal : KO
- GP : OK

Par ailleurs : 
- à quoi la la vue Metawal correspond-elle ? 
- existe-t-il un vue complète

**Comment by vbombaerts** [comment]
Test de l'affichage uniquement (pas la mise en page ni le contenu)

fiche en ISO 19139 - testé sur service et donnée
* vue par défaut : OK
* vue complète : KO. La vue s'affiche, mais pas ses onglets. Il faut cliquer sur "Complète" dans la colonne de droite pour voir les onglets.
* vue XML : OK

fiche en ISO 19115-3 - testé sur service et donnée
* vue par défaut : OK
* vue complète : OK
* vue XML : OK

Par ailleurs, la vue INSPIRE n'est pas disponible dans le dropdown "Mode affichage", mais devient dispo sur la colonne de droite quand on affiche la vue complète. C'est pas clair du tout.
![2018-01-24 17_57_45-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/35345512-23bfca5a-0130-11e8-8020-08e522a0a781.png)

Autre point, quand on commence à changer de vue par la colonne de droite, ça bousille les en-tête et le contenu et le design des fiches. Par exemple pour la vue simple :
![2018-01-24 18_01_24-atlas des voiries vicinales de 1841 et modifications version consolidee - serv](https://user-images.githubusercontent.com/6093597/35345729-a5b69be2-0130-11e8-8be3-8e9ca0011a38.png)

**Comment by fxprunayre** [comment]
Je supprime ces infos de la vue quand on n'appelle pas un formatter en mode HTML complet.

![image](https://user-images.githubusercontent.com/1701393/35802992-7976f02c-0a72-11e8-8961-02a576edbb25.png)

Dans le mode utilisé par l'appli JS Angular, il intégre une DIV. Celle-ci n'a pas à contenir des liens vers le portail.

En mode HTML, l'en tête par défaut est juste simplifiée.


Fait dans GN également.

**Comment by fxprunayre** [comment]
> Pour les fiches en ISO 19139 / Geoportail : KO

On considère qu'il n'y que des fiches ISO19115-3 dans metawal ? On ne redéveloppe pas une vue Géoportail pour le 19139. On cache le menu au cas où il y ait des fiches 19139 ? @vbombaerts 

 
> Pour les vues en ISO 19115-3 / Metawal / Liens vers les vues

Fixed. Cf. commentaire précédent.

**Comment by vbombaerts** [comment]
>> Pour les fiches en ISO 19139 / Geoportail : KO

>On considère qu'il n'y que des fiches ISO19115-3 dans metawal ? On ne redéveloppe pas une vue Géoportail pour le 19139. On cache le menu au cas où il y ait des fiches 19139 ? @vbombaerts

@fxprunayre Ca me va pour autant qu'on puisse importer, éditer et visualiser du 19139 dans d'autres vues. 
Eventuellement faire une "vue" qui indique que la fiche n'est pas visible dans cette vue et qu'il faut choisir la vue complète ??

**Comment by fxprunayre** [comment]
> Eventuellement faire une "vue" qui indique que la fiche n'est pas visible dans cette vue et qu'il faut choisir la vue complète ??

Il y aura la vue principale. Ca convient ? Pour l'import et l'édition ce seront les modes standards GN.

**Comment by davinciagf** [comment]
Un mécanisme est prévu pour ne pas prendre en compte la vue géoportail si la donnée n'est pas en iso19115-3. Pour ce faire, il est nécessaire de bien donner le label "Vue Géoportail" est bien référencer (voir définition d'un formateur #404 ) .

**Comment by vbombaerts** [comment]
Désolé, mais c'est encore le bazar dans les vues. Pas prêt pour un déploiement en prod en tout cas. 
Je vais redéfinir avec @gdetry et @davinciagf les vues qui sont souhaitées pour chaque standard pour qu'on puisse aller de l'avant. Le tableau est un résumé des tests effectués.


Ligne | Ressource | standard | Opération | Vue | Intérêt | Remarques | Testé sur
-- | -- | -- | -- | -- | -- | -- | --
2 | Service | 19115-3 | Consultation | Vue par défaut (en haut) | 0 | Qques problèmes dans les   ressources en lignes     Présence de la rubrique Catalogue d'attributs non nécessaire     Bizarre d'avoir "autres mots-clés" avant toutes les catégories de   mots-clés     "Autres mots-clés" pas traduit | http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search;jsessionid=719E1ED80368E1F7D9F2DDD2CF959669#/metadata/6105cb82-ae25-49fe-a5d6-bddf26fba2b5
3 | Service | 19115-3 | Consultation | Vue complète (en haut) | 1 | On s'attend à la vue ISO   complète mais c'est une vue hybride entre par défaut et géoportail qui   apparaît     En haut à droite, des tas de symboles sans libellé, dont on ne comprend pas   la fonction     Toujours à droite, mention des types de vues, mais différentes de celles   accessibles en haut.     Certaines chaines pas traduites : "Keyword",   "ConformityInspire"     Présentation selon onglets du GP, mais infos affichées pas adaptées aux   services | http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search;jsessionid=719E1ED80368E1F7D9F2DDD2CF959669#/metadata/6105cb82-ae25-49fe-a5d6-bddf26fba2b5
4 | Service | 19115-3 | Consultation | Vue Géoportail (en haut) | 1 | Exactement la même que la vue complète (en haut) | http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search;jsessionid=719E1ED80368E1F7D9F2DDD2CF959669#/metadata/6105cb82-ae25-49fe-a5d6-bddf26fba2b5
5 | Service | 19115-3 | Consultation | Vue XML (en haut) | 1 | OK | http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search;jsessionid=719E1ED80368E1F7D9F2DDD2CF959669#/metadata/6105cb82-ae25-49fe-a5d6-bddf26fba2b5
6 | Service | 19115-3 | Consultation | Simple (à droite) | 0 | Ne contient que le résumé et une   proposition de citation.     En bas, un tas de symboles sans libellé puis mention des différents types   de vue     Ressources associées non disponibles | http://metawal4.test.wallonie.be/geonetwork/srv/api/records/6105cb82-ae25-49fe-a5d6-bddf26fba2b5/formatters/xsl-view?view=default&portalLink=
7 | Service | 19115-3 | Consultation | Geoportail (à droite) | Voir L4 | Idem L4 + ressources associées non disponibles | http://metawal4.test.wallonie.be/geonetwork/srv/api/records/6105cb82-ae25-49fe-a5d6-bddf26fba2b5/formatters/xsl-view?view=metawal&portalLink=
8 | Service | 19115-3 | Consultation | Complète (à droite) | Voir L3 | Onglets ISO (semble OK)     Non localisé (tout en anglais) | http://metawal4.test.wallonie.be/geonetwork/srv/api/records/6105cb82-ae25-49fe-a5d6-bddf26fba2b5/formatters/xsl-view?view=advanced&portalLink=
9 | Service | 19115-3 | Consultation | XML (àdroite) | Voir L5 | OK |  
10 | Donnée | 19115-3 | Consultation | Vue par défaut (en haut) | 0 | Globalement OK     Pas testé en profondeur | http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/03abb4c1-5f53-46bb-94fa-359f3912a041
11 | Donnée | 19115-3 | Consultation | Vue complète (en haut) | 1 | idem L3 | http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/03abb4c1-5f53-46bb-94fa-359f3912a041
12 | Donnée | 19115-3 | Consultation | Vue Géoportail (en haut) | 1 | Plutôt OK     Aperçu/Logo manquant sur le haut de la fiche     Certaines chaînes non traduites (isoTheme) et certains codes de listes non   remplacés par la valeur (fre --> Français)     Liens de la section consultation non fonctionnels     Plusieurs erreurs et/ou info manquantes dans les onglets qualité,   ressources associées, etc     Pas examiné en détails | http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/03abb4c1-5f53-46bb-94fa-359f3912a041
13 | Donnée | 19115-3 | Consultation | Vue XML (en haut) | 1 | OK | http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/03abb4c1-5f53-46bb-94fa-359f3912a041
14 | Donnée | 19115-3 | Consultation | Simple (à droite) | 0 | Voir L6 | http://metawal4.test.wallonie.be/geonetwork/srv/api/records/03abb4c1-5f53-46bb-94fa-359f3912a041/formatters/xsl-view?view=default&portalLink=
15 | Donnée | 19115-3 | Consultation | Geoportail (à droite) | Voir L12 | Ne correspond pas à la vue géoportail de la L12 | http://metawal4.test.wallonie.be/geonetwork/srv/api/records/03abb4c1-5f53-46bb-94fa-359f3912a041/formatters/xsl-view?view=metawal&portalLink=
16 | Donnée | 19115-3 | Consultation | Complète (à droite) | Voir L11 | Vue hybride entre simple et en   onglets     Pas OK. | http://metawal4.test.wallonie.be/geonetwork/srv/api/records/03abb4c1-5f53-46bb-94fa-359f3912a041/formatters/xsl-view?view=advanced&portalLink=
17 | Donnée | 19115-3 | Consultation | XML (àdroite) | Voir L13 | OK |  
18 | Service | 19139 | Consultation | Vue par défaut (en haut) | 1 | OK | http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search;jsessionid=A5B5C7AFBB018A824164B6F7772DA4A9#/metadata/ffe86f86-d5fa-4e1f-83ab-0ea1e3059fb9
19 | Service | 19139 | Consultation | Vue complète (en haut) | 1 | Cette vue propose moins d'infos   que la vue par défaut !     Elle propose d'ailleurs un lien direct vers la vue par défaut si on veut   plus d'infos ! | http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search;jsessionid=A5B5C7AFBB018A824164B6F7772DA4A9#/metadata/ffe86f86-d5fa-4e1f-83ab-0ea1e3059fb9
20 | Service | 19139 | Consultation | Vue XML (en haut) | 1 | OK |  
21 | Service | 19139 | Consultation | INSPIRE (à droite) | 1 | Nombreuses chaînes   non-traduites     LA hiérarchisation des informations n'apparait pas clairement dans les   styles utilisés     Infos manquantes | http://metawal4.test.wallonie.be/geonetwork/srv/api/records/ffe86f86-d5fa-4e1f-83ab-0ea1e3059fb9/formatters/xsl-view?view=inspire&portalLink=
22 | Service | 19139 | Consultation | Simple (à droite) | Voir L18 | Vue très très simple : aucune info à part le résumé ! | http://metawal4.test.wallonie.be/geonetwork/srv/api/records/ffe86f86-d5fa-4e1f-83ab-0ea1e3059fb9/formatters/xsl-view?view=default&portalLink=
23 | Service | 19139 | Consultation | Complète (à droite) | Voir L19 | Présentation en onglets OK, mais   les chaînes ne sont pas traduites.     Supprimer la proposition de citation. | http://metawal4.test.wallonie.be/geonetwork/srv/api/records/ffe86f86-d5fa-4e1f-83ab-0ea1e3059fb9/formatters/xsl-view?view=advanced&portalLink=
24 | Service | 19139 | Consultation | XML (àdroite) | Voir L20 | OK |  
25 | Donnée | 19139 | Consultation | Vue par défaut (en haut) | 1 | OK | http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/50bf7812-799b-4d2f-bccc-cdbb3e2d6e08
26 | Donnée | 19139 | Consultation | Vue complète (en haut) | 1 | idem L19 |  
27 | Donnée | 19139 | Consultation | Vue XML (en haut) | 1 | OK |  
28 | Donnée | 19139 | Consultation | INSPIRE (à droite) | 1 | idem L21 | http://metawal4.test.wallonie.be/geonetwork/srv/api/records/50bf7812-799b-4d2f-bccc-cdbb3e2d6e08/formatters/xsl-view?view=inspire&portalLink=
29 | Donnée | 19139 | Consultation | Simple (à droite) | Voir L25 | Pratiquement aucune info !! | http://metawal4.test.wallonie.be/geonetwork/srv/api/records/50bf7812-799b-4d2f-bccc-cdbb3e2d6e08/formatters/xsl-view?view=default&portalLink=
30 | Donnée | 19139 | Consultation | Complète (à droite) | Voir L26 | Voir L23 | http://metawal4.test.wallonie.be/geonetwork/srv/api/records/50bf7812-799b-4d2f-bccc-cdbb3e2d6e08/formatters/xsl-view?view=advanced&portalLink=
31 | Donnée | 19139 | Consultation | XML (àdroite) | Voir L27 | OK |

**Comment by davinciagf** [comment]
La vue "Géoportail" est mise à jour. A retester - Attention certaines références ne sont pas forcément présentes pour les règles d'affichage (exemple: pour la consultation : besoin du protocole et de la fonction afin de pourvoir être affciher).
Je vérifie selon les points relevés par @vbombaerts afin de corriger si besoin cette vue "Géoportail".

**Comment by vbombaerts** [comment]
Après discussion avec @gdetry 

Vues à conserver (en consultation) :
* ISO 19115-3 : Géoportail, ISO complète, XML
* ISO 19139 : Simple, ISO complète, XML

Vue par défaut (en consultation) : 
* Géoportail pour ISO 19115-3 
* Simple pour ISO 19139

**Comment by gdetry** [comment]
Création tickets spécifiques vue par défaut et vue GP V 3.6
