### ISSUE TITLE
Edition / sauver et valider => IllegalStateException

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#34]
![sauver_valider](https://f.cloud.github.com/assets/6093453/1662165/cddedd50-5bf8-11e3-90cd-0944a08c7b6b.jpg)

**Comment by fxprunayre** [comment]
Problème sur la plateforme de test de la région - A redéployer

**Comment by fxprunayre** [comment]
Doublon.
