### ISSUE TITLE
Registre

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#340]
## Données prioritaires 
 - [x] Ajouté manuellement dans metawal
 - [x] Amélioration de l'import https://github.com/geonetwork/core-geonetwork/issues/2500

## Thèmes INSPIRE 

- [x] INSPIRE theme / Changement des identifiants cf. http://inspire.ec.europa.eu/theme/theme.fr.iso19135xml. Mettre à jour https://github.com/geonetwork/util-gemet/blob/master/thesauri/inspire-theme.rdf https://github.com/geonetwork/core-geonetwork/issues/2506

## App

- [ ] Editor / Configuration pour utiliser les Anchor pour ce type de mots clés
- [ ] Migration pour les fiches existantes

## Autres

- [ ] Ajouter un thésaurus avec les directives environnementales européennes

## Contexte

Ces infos sont utilisés dans le géoportail européen. Pas dans les validateurs actuels - pour le moment. http://inspire-geoportal.ec.europa.eu/proxybrowser/#q=*%3A*

**Comment by vbombaerts** [comment]
@fxprunayre tu peux indiquer la procédure pour ajouter manuellement dans Metawal ?
J'ai fait un essai mais échoué. 
1. Télécharger le registre en ISO19135 - http://inspire.ec.europa.eu/metadata-codelist/PriorityDataset 
2. Jouer la conversion  - https://github.com/geonetwork/schema-plugins-no-history/blob/master/iso19135/convert/xml_iso19135ToSKOS.xsl
3. Ajouter une balise rdf autour du fichier sinon il n'est pas correct
4. Importer comme thésaurus.

J'ai testé avec http://inspire.ec.europa.eu/theme mais sans succès. Le thésaurus est importé mais les valeurs ne s'affichent pas. Il semble y avoir une histoire de langue mais ce n'est pas tout. Peut-être y a-t-il d'autres corrections à faire sur le fichier skos ?

**Comment by fxprunayre** [comment]
> Jouer la conversion

Il faut utiliser https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-3.4.x/web/src/main/webapp/xslt/services/thesaurus/iso19135-to-skos.xsl, j'ai fait quelques ajustements (balise racine, langue, ids).

**Comment by vbombaerts** [comment]
Documenter #416

**Comment by vbombaerts** [comment]
https://github.com/geonetwork/core-geonetwork/issues/2593
