### ISSUE TITLE
Paniers

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#344]
Cf. https://github.com/geonetwork/core-geonetwork/wiki/Basket-for-custom-selection-proposal

- [x] Sélections multiples (cf. https://github.com/geonetwork/core-geonetwork/pull/1819)

- [x] Add to map selection (https://github.com/geonetwork/core-geonetwork/pull/1920)
  - [ ] Spec passage de couches dans Wallonmap

- [x] Sélections persistentes

- [x] Watching selection

- [x] MyFrequentlyUsedRecords selection

- [x] Download data

  - [ ] Spec passage de couches dans panier Wallonmap

**Comment by fxprunayre** [comment]
![image](https://cloud.githubusercontent.com/assets/1701393/24101458/b34b2c16-0d78-11e7-9ca9-bbcdfed2c01c.png)

**Comment by vbombaerts** [comment]
![thumbup](https://cloud.githubusercontent.com/assets/6093597/24138921/643f1f5e-0e1a-11e7-9daa-5ec9eefc2079.png)
