### ISSUE TITLE
Extracteur

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#345]
Cf. https://github.com/geonetwork/core-geonetwork/wiki/Extractor-App-proposal

**Comment by vbombaerts** [comment]
- Nécessité d'ajouter un paramètre (modifiable) relatif au nombre max d'items qui peuvent être mis dans le panier d'extraction.
- L'utilisateur peut choisir le format d'extraction (shp, gdb, gml) en fonction des formats documentés dans la MD
- L'utilisateur peut choisir le système de référence en fonction des systèmes documentés dans la MD
- L'utilisateur peut définir une zone d'extraction sur base d'un set prédéfini (commune, bassin versant...) ou fournir une zone en shp.
- L'utilisateur peut encoder un numéro de licence/numéro de demande qui sera vérifié par le système pour valider si la licence permet l'extraction ou pas.

**Comment by stephyritz** [comment]
Je déplace ça en 3.8 pour le moment. Cela concerne plus le projet remplacement du catalogue Geoportail actuel par l'API GN que le fonctionnement courant de Metawal4. A voir si cela reste cohérent en terme de délais selon l'avancée des travaux avec NSI.
