### ISSUE TITLE
Export MEF - impossible d'exporter un grand nombre de fiches

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#346]
* Erreur quand on essaie d'exporter en MEF toutes les fiches d'un coup :
** <error id="error">Java heap space</error>
** could not extract ResultSet; nested exception is org.hibernate.exception.GenericJDBCException: could not extract ResultSet

* Etant identifié, possible d'exporter 100 fiches 1 ou 2 fois. Après plusieurs fois, ça tourne dans le vide. Plus moyen d'exporter.

**Comment by fxprunayre** [comment]
Possibilité de faire un backup quotidien via l'admin cf. https://github.com/geonetwork/core-geonetwork/pull/2184

**Comment by fxprunayre** [comment]
Vérifier mémoire dispo sur le serveur et en ajouter pour tomcat si dispo ? -Xmx=Xgo

**Comment by vbombaerts** [comment]
Comportement à vérifier quand on aura passé la nouvelle version en prod. Si possible, demander au DTIC d'allouer + de mémoire.

**Comment by gdetry** [comment]
Je teste et contacte DTIC éventuellement

**Comment by fxprunayre** [comment]
Utiliser dans l'admin l'archivage
![image](https://user-images.githubusercontent.com/1701393/52418096-9d870c80-2aed-11e9-9fc6-2797c70774b6.png)
