### ISSUE TITLE
Edition - XML pas entièrement visible

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#348]
Lors de l'édition d'une fiche en vue XML, les premières lignes sont cachées par le titre de la fiche.
![2017-02-09 15_57_33-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/22888135/ff054e8c-f204-11e6-921c-67a30ad90cc9.png)

**Comment by davinciagf** [comment]
Fixé en GN https://github.com/geonetwork/core-geonetwork/pull/1911 
Poussé en version MW3.4 https://github.com/SPW-DIG/metawal-core-geonetwork/commit/fccc1bd24ab1fd32807c426d8a771b58ce676757

**Comment by fxprunayre** [comment]
A re-vérifier
