### ISSUE TITLE
Import - fiche ISO 19115-3 sans transformation

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#350]
L'import d'une fiche en ISO 19115-3 (venant par exemple du catalogue sextant) sans transformation engendre deux types de modification du XML :
- l'ajout dans plusieurs tags du namespace xmlns:geonet
- l'ajout d'un "point of truth" mdb:metadatalinkage - selon moi ce n'est nécessaire que pour un import avec transformation, car si la fiche est en ISO 19115-3, le point of truth a pu être indiqué par le premier éditeur de la fiche. En tout cas, il faudrait tester si le point of truth n'est pas déjà mentionné et ne l'ajouter que s'il n'est pas mentionné. Dans le cas testé (import d'une fiche ISO 19115-3 depuis Sextant), on se retrouve avec deux point of truth : l'un dans Sextant, l'autre dans Metawal... A discuter.

**Comment by fxprunayre** [comment]
> l'ajout dans plusieurs tags du namespace xmlns:geonet

Cosmétique & pas trivial à changer (globalement) - on a tenté plusieurs fois déjà.


> l'ajout d'un "point of truth" mdb:metadatalinkage

Y'a beaucoup de TODO & "?" dans cette section. cf.
https://github.com/metadata101/iso19115-3/blob/develop/src/main/plugin/iso19115-3/update-fixed-info.xsl#L153
Il y a un paramètre pour dire si on ajoute ou pas un metadata linkage (par défaut à true). C'est à améliorer. Peut être ne pas en ajouter un s'il existe déjà (même s'il ne pointe pas vers le catalogue local).

**Comment by vbombaerts** [comment]
> Peut être ne pas en ajouter un s'il existe déjà (même s'il ne pointe pas vers le catalogue local).

Me semble OK comme règle de bonne pratique : si un point of truth déjà indiqué, alors ne pas en ajouter un autre.

**Comment by fxprunayre** [comment]
> si un point of truth déjà indiqué, alors ne pas en ajouter un autre.

Done en 3.5.x.

**Comment by fxprunayre** [comment]
Ca me semble bon. A redéployer

**Comment by vbombaerts** [comment]
Super !

![2018-03-26 17_35_01-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/37916408-0edc25b8-311c-11e8-8927-51ab7aaa1576.png)
