### ISSUE TITLE
Import - transformation ISO 19115-3 --> ISO 19139

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#351]
Cette transformation n'est pas proposée à l'import. Y a-t-il une raison ? Elle est de toute façon disponible à l'export et à travers le CSW. Pq ne pas l'exposer à l'import ?

**Comment by fxprunayre** [comment]
> Pq ne pas l'exposer à l'import ?

L'idée c'est plutôt d'aller de l'avant ;) mais si c'est nécessaire elle peut être ajoutée (par contre il y a risque de perte d'un peu d'info).

**Comment by fxprunayre** [comment]
Ajouté en 3.5.x. A testé.

**Comment by fxprunayre** [comment]
Ca semble ok. @vbombaerts est-ce qu'on en profite pour supprimer les transfos non utilisées ?
![image](https://user-images.githubusercontent.com/1701393/35279741-3f5189da-004e-11e8-909c-243f7d7b9081.png)

Si oui lesquelles on garde ?

**Comment by vbombaerts** [comment]
Pas la peine de s'embêter avec ça. On peut tout garder pour le moment.

**Comment by vbombaerts** [comment]
Tansfo ajoutée et donc possibilité d'importer avec transformation. 
J'ai pas testé si la transformation elle-même.
