### ISSUE TITLE
Annuaire - ajouter un élément

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#352]
Quand je veux ajouter un élément à l'annuaire, il ne se passe rien de visible.
Edit : Je peux ajouter un élément de type contact, mais pas un élément de type rapport de qualité

![2017-02-22 17_46_18-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/23222042/f76e0e10-f926-11e6-899a-3e37e4272c90.png)

**Comment by fxprunayre** [comment]
GN ref https://github.com/geonetwork/core-geonetwork/issues/1909

Le pb ici est qu'il n'y a pas de namespace dans le subtemplate.
