### ISSUE TITLE
Annuaire - Entrées non identifiées

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#354]
Sur certains annuaires, les entrées ne sont pas identifiées et il n'est pas possible de les éditer. 

![2017-02-22 18_19_36-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/23223551/a614ebf6-f92b-11e6-8bc9-756b932c4c0d.png)

Pourtant, quand on ajoute un contact venant de l'annuaire dans la fiche, il apparait correctement.

![2017-02-22 18_19_08-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/23223555/a7bda524-f92b-11e6-97c6-dd00b530ad9f.png)

**Comment by fxprunayre** [comment]
Peux-tu ajouter le XML d'un subtemplate utilisé pour reproduire ?

Ici avec les modèles ISO19139 par défaut (https://github.com/geonetwork/core-geonetwork/blob/develop/schemas/iso19139/src/main/plugin/iso19139/templates/sub-PointOfContact.xml) ça joue

![image](https://cloud.githubusercontent.com/assets/1701393/23297913/ad91b4ee-fa7b-11e6-8f9d-3788b5f38623.png)


Note: Pour le moment, les annuaires n'ont pas vraiment été utilisés dans metawal - il faudrait cadrer un minimum car là je vois un mix ISO19115-3/19139. On peut faire des choses mais ça vaudrait le coup de préciser ce qu'on veut avant de tester toutes les combinaisons possibles.
