### ISSUE TITLE
Problèmes avec caractères spéciaux

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#355]
*   ![2017-02-22 22_27_07-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/23233161/4365b95e-f94e-11e6-8460-75e6aba2d457.png)

**Comment by fxprunayre** [comment]
See https://github.com/geonetwork/core-geonetwork/issues/2497

**Comment by fxprunayre** [comment]
Fixed in metawal - to be confirmed on GN side.

**Comment by vbombaerts** [comment]
OK

![2018-03-26 17_16_29-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/37915311-8293ffba-3119-11e8-8e0e-33203c251ab7.png)
