### ISSUE TITLE
Edition - Problèmes avec le template géoportail - fiche de données - onglet métadonnées

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#356]
- [x]  Les types de ressource ne correspondent pas à ce qui est utilisé dans Metawal (trop de choix). Ne pourrait-on pas plutôt afficher l'équivalent du hierarchylevelname (mdb:name), avec une liste déroulante et en déduire automatiquement le hierarchylevel (mdb:resourcescope) ?
![2017-02-22 22_32_24-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/23233351/e8a114ea-f94e-11e6-8766-c19eb67ff525.png)

- [x]  On ne comprend pas à quoi correspond le champ Identificateur. L'intituler Identifiant de la ressource. Ajouter un bouton d'action permettant d'attribuer automatiquement un identifiant.
![2017-02-22 22_33_49-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/23233450/2abf1462-f94f-11e6-8764-059ea84b5192.png)

- [x]  Quand on active la suggestion "ajouter un identifiant", l'identifiant s'ajoute 2 fois. En plus, il ne correspond pas à la structure définie actuellement, qui est http://geoportail.wallonie.be/ressources/id/[numerodelidentifiant]
![2017-02-22 22_44_15-](https://cloud.githubusercontent.com/assets/6093597/23234296/e9364864-f951-11e6-97ba-b1cb30c999a2.png)

- [x]  Quand on ajoute une donnée associée, il n'y a pas de bouton "associer" dans la fenêtre modale, donc on ne sait pas si le fait de sélectionner la fiche à associer l'associe effectivement ou pas à la fiche en cours. Quand on referme la fenêtre modale, on n'a aucun feed-back visuel. Donc là aussi impossible de savoir si l'association a bien eu lieu ou pas. Par ailleurs, la précision "(eg. études, capteurs)" amène de la confusion puisqu'on cherche essentiellement à associer des fiches de données, de collections ou de cartes entre elles, pas des fiches de capteurs ou d'études. Quand on  clique sur le bouton "Autres liens", la fenêtre modale se ferme. Je n'en comprends pas l'utilité.
![2017-02-22 23_24_02-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/23235593/5c2a196e-f956-11e6-9717-939a34232c27.png)

- [x]  Quand on veut associer un service, la procédure est plus claire (grâce au bouton ajouter). Par contre, une fois qu'on a cliqué sur le bouton, ça tourne dans le vide. Le double ascenseur n'est ni pratique ni esthétique. 
![2017-02-22 23_32_34-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/23235871/60410ffc-f957-11e6-9dc9-af5039954970.png)

- [x]  Toujours pour la fonctionnalité d'association de service, pouvez-vous m'expliquer la différence entre associer les deux fiches et associer la fiche à une couche spécifique du WMS ? Comment ces deux options sont-elles encodées dans la fiche de données (et éventuellement dans le fiche de service) ?

**Comment by vbombaerts** [comment]
* Quand on clique sur le + à côté de Identificateur, il n'est pas possible d'encoder un identifiant. On ne sait pas non plus si c'est l'identifiant global ou local.
![2017-03-22 17_28_59-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/24208903/1b44b528-0f25-11e7-877e-1470e26c35b8.png)

* Ce serait plus pratique d'avoir la suggestion "Ajouter un identifiant" à l'endroit du formulaire où on doit ajouter l'identifiant plutôt que caché dans une suggestion.

* Le bouton permettant de lier à un service doit être dans la section diffusion uniquement, pas dans la section métadonnée. Le bouton permettant de lier à un document doit être dans une section Ressources associées. L'intitulé de la section doit être adapté en conséquence.
![2017-03-22 17_38_59-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/24209461/a7e1b8ea-0f26-11e7-8f51-084d32227596.png)

* Quand on associe une autre ressource, il faudrait plus de guidance sur les deux champs à remplir : Type d'association et type d'initiative. 
Le type d'initiative est facultatif. Ne pas le demander en vue géoportail (uniquement en vue ISO avancée). 
Pour le type d'association, fournir l'explication et éventuellement une guidance : pour tel cas, utiliser telle valeur.
![2017-03-22 17_42_57-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/24210019/17df8964-0f28-11e7-8d9e-1b1c5506c259.png)

**Comment by fxprunayre** [comment]
* Ajout des groupes WMS https://github.com/geonetwork/core-geonetwork/pull/3547
* Type d'association est mandatory https://github.com/geonetwork/core-geonetwork/pull/3546
