### ISSUE TITLE
Edition - Problèmes avec le template géoportail - fiche de service - onglet métadonnées

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#357]
Mêmes problèmes que pour la fiche de données #356 
+
* Dans "Attacher à une collection", on ne peut pas associer deux fiches de service. Seules les données et applications apparaissent.
![2017-02-23 10_52_11-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/23253882/49a40d44-f9b6-11e6-8ff1-e5754dc82d72.png)

* Dans "Associer une donnée", deux problèmes : 1. On ne peut sélectionner qu'une seule donnée, alors que parfois plusieurs données sont servies dans un seul service. / 2. Le message concernant l'URL des services apparait alors qu'il n'y a probablement pas lieu que ce soit le cas.
![2017-02-23 10_45_36-](https://cloud.githubusercontent.com/assets/6093597/23253641/9576e332-f9b5-11e6-97b6-dbf799aabd80.png)

**Comment by fxprunayre** [comment]
Traiter en partie dans la dernière mise en prod. Je ferme.
