### ISSUE TITLE
Bouton "Uniquement mes fiches" fonctionne à l'envers

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#358]
Quand on coche "Uniquement mes fiches" on se retrouve avec toutes les fiches et quand on le décoche, on se retrouve seulement avec ses fiches. Ca devrait être l'inverse.
![2017-02-23 22_12_41-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/23279416/7b04f862-fa15-11e6-841b-09d2e47feb23.png)
![2017-02-23 22_13_09-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/23279421/7f01c9d6-fa15-11e6-8f7b-d46fda675606.png)

**Comment by davinciagf** [comment]
Non reproduit en local. A tester lors du prochain redéploiement
