### ISSUE TITLE
Afficher uniquement la sélection

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#359]
Dans l'outil d'édition en batch, on a la possibilité de n'afficher que la sélection. Ce serait possible d'ajouter cette fonction aux interfaces de recherche des pages "Rechercher" et "Contribuer" ?

![2017-02-23 22_30_51-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/23280113/3f26947e-fa18-11e6-8991-f189a929cee7.png)

**Comment by fxprunayre** [comment]
Fait dans les améliorations sur le panier https://github.com/geonetwork/core-geonetwork/pull/1819

Sera dispo en 3.4.

**Comment by vbombaerts** [comment]
Nickel !
