### ISSUE TITLE
Contribuer - nombre de fiches sélectionnées

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#362]
Quand on sélectionne des fiches, leur nombre est indiqué et se met à jour correctement. Si ensuite on effectue une autre action, comme par exemple visualiser le détail d'une fiche en cliquant sur un titre, et qu'on revient ensuite en arrière avec le bouton du navigateur le nombre de fiches sélectionnées est revenu à 0. Pourtant, les cases devant les fiches sont encore checkées. Même chose si on bascule vers le catalogue de la section rechercher : les fiches sont sélectionnées mais le nombre = 0. 
Dès qu'on sélectionne ou désélectionne une fiche, le compteur est de nouveau juste. 
![2017-02-23 23_12_19-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/23281755/e6f8aa10-fa1e-11e6-92c6-213c06219f39.png)

**Comment by fxprunayre** [comment]
J'aurai tendance à dire que la gestion de sélections multiples corrige ce point. A tester en 3.4.x.

**Comment by vbombaerts** [comment]
Testé et OK en 3.4.x
