### ISSUE TITLE
Contribuer - Lancer la recherche

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#363]
Ajouter la possibilité de lancer une recherche avec la touche <Enter> plutôt que la loupe.

![2017-02-23 23_27_06-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/23281987/a6d8827e-fa1f-11e6-81a2-cc8ab9e1dad9.png)

**Comment by davinciagf** [comment]
Réaliser via  6022fe71c5c5d21572fa4248399e926bccfda2f5

**Comment by fxprunayre** [comment]
Fait dans GN avec ajout de raccourcis clavier https://github.com/geonetwork/core-geonetwork/pull/2532
