### ISSUE TITLE
Contribuer - Interaction "mes fiches" et facettes

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#365]
Il n'est pas possible de combiner la case "uniquement mes fiches" avec les facettes. Donc pas possible de rechercher par exemple toutes mes fiches non-valides ou toutes mes fiches de type service. Ça devrait être possible.

**Comment by davinciagf** [comment]
J'arrive à faire des recherches sur les facettes depuis mes fiches via : 
- cocher la case "mes fiches " et appuyer sur l'icone de recherche pour d'abord sélectionner "mes fiches" 
![2](https://cloud.githubusercontent.com/assets/576292/23957666/3f68ee22-09a0-11e7-98d9-055acf1c613d.jpg)
- analyser "mes fiches" selon les différentes facettes.
![3](https://cloud.githubusercontent.com/assets/576292/23957688/4ccac252-09a0-11e7-918b-60d57387606a.jpg)

**Comment by vbombaerts** [comment]
OK
