### ISSUE TITLE
Stockage du rapport de validation

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#366]
Quand on valide une fiche en batch, en dehors d'une session d'édition de la fiche, le statut de validité de la fiche est mis à jour et on peut utiliser sa valeur dans la recherche par facette.
Par contre, quand on ouvre la fiche en édition, le rapport n'apparait pas par défaut. Il faut le générer. J'en déduis qu'il n'est pas stocké mais généré à la volée. Pourtant, à partir du moment où on a lancé la validation de la fiche (même en batch), on s'attend à ce que le rapport soit disponible et affiché. Faut-il penser à le stocker qqpart ? Peut-être que cela permettrait aussi de faire des stats sur les erreurs les plus fréquentes dans le dashboard ?

**Comment by fxprunayre** [comment]
Ca a été évoqué à une époque sur geocat.ch je crois, le pb c'est que les rapports sont "localisés" et donc ça devient un peu compliqué de stocker les rapports dans différentes langues.
