### ISSUE TITLE
Recherche - présentation des résultats

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#367]
* On voudrait avoir la possibilité présenter les résultats de recherche à la suite l'un de l'autre, pas 2 par 2. C'est plus reposant pour les yeux.

* Le descriptif de la donnée doit se limiter à l'accroche.
![2017-03-22 17_55_35-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/24210331/0b2f4ffa-0f29-11e7-9c2e-5d3cb965ef20.png)

* La disposition doit être revue pour optimiser l'espace utilisé : Photo à gauche. Titre à droite de la photo. descriptif en dessous du titre, etc. S'inspirer de la présentation géoportail.
![2017-03-22 17_59_08-catalogue des donnees et services](https://cloud.githubusercontent.com/assets/6093597/24210436/65983984-0f29-11e7-8600-6e77996904a0.png)

**Comment by fxprunayre** [comment]
Utiliser le template API dans le mode standard.

**Comment by davinciagf** [comment]
Via l'éditeur de configuration (modifier les 2 liens grid.html en rw-simple.html et sauvegarder la nouvelle configuration), il est possible d'afficher les résultats de la recherche à la suite l'un de l'autre, avec un abstract limité à l'accroche et une configuration similaire au Géoportail mais ne tenant pas encore compte du code couleur de ce dernier (une nouvelle interface sera produite dans le projet DIG-2017).

![screen shot 2018-02-07 at 22 52 36](https://user-images.githubusercontent.com/576292/35945070-348da318-0c5f-11e8-8646-670b5aaa2bca.jpg)

**Comment by vbombaerts** [comment]
- [x] Supprimer les catégories
- [x] Ajouter le gestionnaire
- [x] Ajouter la date de dernière mise à jour
- [x] Supprimer le "cachet" en surimpression. (Je sais que c'est @davinciagf qui l'a fait mais ce n'est pas une info qui mérite autant de mise en valeur dans le cadre de Metawal. Sorry...)
- [x] Clic sur fiches associées

A faire en même temps que la mise au point du template pour l'intégration dans le GP.

**Comment by davinciagf** [comment]
Il s'agit ici d'une adaptation du template par défaut et non du template de l'API. Ne faudrait-il donc pas la modifier dans le cadre de [DIG-2017-m11/A/M1](https://github.com/SPW-DIG/metawal-core-geonetwork/projects/7) ?

**Comment by vbombaerts** [comment]
Maintenant que le template API est développé, ce ne serait pas mieux d'utiliser plutôt directement le template de l'API ?
