### ISSUE TITLE
La validation supprime la sélection

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#369]
Lorsqu’on sélectionne des fiches et qu’on les valide, la validation supprime la sélection.

**Comment by fxprunayre** [comment]
Conserver la sélection sauf sur suppression

**Comment by fxprunayre** [comment]
Cf. https://github.com/geonetwork/core-geonetwork/commit/5928749f887978841108d74a2da7dd860cff0603

**Comment by vbombaerts** [comment]
OK
