### ISSUE TITLE
Établissements pour aînés (hors territoire de la Communauté germanophone de Belgique)

### ISSUE THREAD

**Issue by PascalDelvaux** [SPW-DIG/metawal-core-geonetwork#37]
Problème de recherche d'un jeu de géodonnées dans métawal 3 : Établissements d'accueil pour aînés.

http://metawal3.test.wallonie.be/geonetwork/srv/fre/search?uuid=6bb4a41f-8477-4a0c-95f9-7d2807ee0589
= url de la fiche visée par la recherche infructueuse.

**Comment by fxprunayre** [comment]
Doublon. #54
