### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#371]
Sauf erreur de ma part, les fonctionnalités du workflow ne sont pas utilisées dans cette version de Metawal ==> désactiver et ne pas afficher les actions liées au WF
![2017-03-22 14_36_14-clipboard](https://cloud.githubusercontent.com/assets/6093597/24200275/ec863c9c-0f0c-11e7-9bcb-8bd3c5ddf4db.png)

**Comment by davinciagf** [comment]
Commenter la commande afin que cette dernière ne soit plus présente (https://github.com/geonetwork/core-geonetwork/blob/develop/web-ui/src/main/resources/catalog/views/default/directives/partials/mdactionmenu.html#L63-L69)

**Comment by vbombaerts** [comment]
OK
