### ISSUE TITLE
Vue par défaut - liens WMS - connecter à Wallonmap

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#372]
Le bouton « visualiser » pour les WMS est inactif 
![2017-03-22 14_45_52-clipboard](https://cloud.githubusercontent.com/assets/6093597/24200749/5c23dbda-0f0e-11e7-9c33-6f363b5e0a06.png)

**Comment by davinciagf** [comment]
Fonctionnalité corrigée dans la version 3.4.x mais les liens sont à adapter pour pointer vers l'application web WALONMAP.

**Comment by fxprunayre** [comment]
UC

- [ ] Ajout d'une couche avec service URL + layer name dans la fiche

- [ ] Cas d'un service - ouvrir walonmap qui fera le GetCapabilities


- [ ] Gérer le cas ESRI REST cf. https://github.com/SPW-DIG/metawal-core-geonetwork/issues/370

**Comment by gdetry** [comment]
Test avec fiche http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/145fe3eb-1242-4b08-9269-0479beaada28

Le bouton "visualiser" au droit de la ressource WMS redirige bien vers WOM et la ressource est bien chargée --> Comportement OK.

Petit bémol : au chargement, le premier layer référencé dans le GetCapabilities est allumé et les autres sont éteints. C'est embêtant dans le cas d'une série. Ce serait plus cohérent de tout cocher (cf. comportement WOM) ou d'afficher les couches de la même manière que le service REST. 

![image](https://user-images.githubusercontent.com/12267969/38090969-71eaba6c-3364-11e8-866a-a592d178f996.png)

Dans le cas d'une fiche "fille", il faut voir comment référencer au mieux les WMS pour pointer vers le layer spécifique car, en l'état, ce qui est chargé ne correspond pas. Actuellement, on pointe vers le GetCapabilities 

--> Pour la connexion à WOM à partir d'un WMS (but du ticket), c'est OK.

**Comment by gdetry** [comment]
But du ticket qui est rendre le bouton Visualiser actif au droit d'une ressource WMS et qui renvoie vers WOM est OK donc ticket fermé.

Le problème de l'affichage d'un layer particulier ou de l'ensemble de la série est reporté dans le ticket #427
