### ISSUE TITLE
Consultation - vue simple - ressources associées en double

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#374]
En vue simple, les fiches associées apparaissent en double.
![2017-03-22 16_14_39-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/24205257/295cec66-0f1b-11e7-98b3-71eaa810ec0c.png)

**Comment by davinciagf** [comment]
Quelle est l'id de la fiche?
Exemple d'une fiche reprenant des ressources associées sans duplication: http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/65541ace-497f-46ac-bf45-6293c32da8f3

**Comment by vbombaerts** [comment]
http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/65541ace-497f-46ac-bf45-6293c32da8f3

**Comment by vbombaerts** [comment]
Apparait avec 2 icones différentes mais encodé une seule fois dans le XML.

**Comment by vbombaerts** [comment]
Par ailleurs, le texte sort du cadre
--> moved to https://github.com/SPW-DIG/metawal-core-geonetwork/issues/403

**Comment by vbombaerts** [comment]
OK
