### ISSUE TITLE
Edition - Template géoportail - fiche de données - onglet Description

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#376]
* Section classification de la ressource :
Pas nécessaire d'afficher les paramètres avancés relatifs aux mots-clés. C'est incompréhensible pour l'éditeur. Je pense que le gestionnaire du catalogue doit définir ce paramètre pour son catalogue.
![2017-03-22 18_01_21-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/24221663/8ef262a2-0f4f-11e7-9bff-0b7482e5bbfe.png)

* Lorsqu’on supprime un des thèmes, il ne réapparait pas dans la liste avant rafraichissement de la page.
![2017-03-22 22_58_02-clipboard](https://cloud.githubusercontent.com/assets/6093597/24222656/13afcb3a-0f53-11e7-9b9d-f44a7296144d.png)
![2017-03-22 22_58_16-clipboard](https://cloud.githubusercontent.com/assets/6093597/24222659/1762f086-0f53-11e7-95e9-b8a60a18fe44.png)

* Catégorie ISO doit être remonté entre les thèmes INSPIRE, Géoportail, GEMET et les mot-clés + renommer en "Ajouter un thème ISO" 

* Lorsqu'on veut ajouter un deuxième thème ISO, il n'y a plus de label à côté du bouton +. En ajouter un : "Ajouter un thème ISO"
![2017-03-22 23_08_42-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/24223027/a95cfefe-0f54-11e7-9e34-93f4e3fe51ef.png)

* Une fois ajoutée, une catégorie thématique ISO ne peut plus être supprimée. Il faut passer par la vue avancée.
![2017-03-22 23_15_03-clipboard](https://cloud.githubusercontent.com/assets/6093597/24223210/6c692698-0f55-11e7-8c1d-a03964b8d2fe.png)

* Mots-clés : Renommer "Autres mots-clés" en "Mots-clés". Ajouter le label "Mot-clé" devant les mots-clés. Ajouter le label "Ajouter un mot-clé" devant le +
![2017-03-22 23_13_31-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/24223185/4ee15f32-0f55-11e7-87b5-5e5783286f12.png)

* Emprise géographique issue de Geonames : Lorsqu’on choisit une entrée (ex. Région wallonne), la carte disparait.
![2017-03-23 10_23_51-metawal - catalogue pour l information geographique de wallonie - service public](https://cloud.githubusercontent.com/assets/6093597/24240708/de409fe6-0fb2-11e7-90c0-922910041939.png)

* Emprise géographique Geonames : quel est l'apport de cette catégorie par rapport à celles existantes ? Si aucun, supprimer.

**Comment by vbombaerts** [comment]
TODO : différents points du ticket à répartir selon criticité.

**Comment by fxprunayre** [comment]
> Emprise géographique Geonames : quel est l'apport de cette catégorie par rapport à celles existantes ? Si aucun, supprimer.

Supprimé.

**Comment by fxprunayre** [comment]
> Section classification de la ressource :
> Pas nécessaire d'afficher les paramètres avancés relatifs aux mots-clés. C'est incompréhensible pour l'éditeur. Je pense que le gestionnaire du catalogue doit définir ce paramètre pour son catalogue.

C'est bien configuré dans la vue Géoportail.

![image](https://user-images.githubusercontent.com/1701393/35809440-e7dc010e-0a88-11e8-854b-a6cb46340db8.png)

**Comment by fxprunayre** [comment]
> Lorsqu’on supprime un des thèmes, il ne réapparait pas dans la liste avant rafraichissement de la page.

Je ne suis pas certain de reproduire. A préciser et si persistant, à traiter dans MW2018.

**Comment by fxprunayre** [comment]
> Une fois ajoutée, une catégorie thématique ISO ne peut plus être supprimée. Il faut passer par la vue avancée.
> Catégorie ISO doit être remonté entre les thèmes INSPIRE, Géoportail, GEMET et les mot-clés + renommer en "Ajouter un thème ISO"
> Mots-clés : Renommer "Autres mots-clés" en "Mots-clés". Ajouter le label "Mot-clé" devant les mots-clés. Ajouter le label "Ajouter un mot-clé" devant le +


Ajout des libellés dans les boutons et correction pour suppression de topic en vue custom.


![image](https://user-images.githubusercontent.com/1701393/35816473-1772758a-0a9b-11e8-9e04-38cf2465cb51.png)

**Comment by fxprunayre** [comment]
A déployer.

**Comment by vbombaerts** [comment]
- [x] Section classification de la ressource : Pas nécessaire d'afficher les paramètres avancés relatifs aux mots-clés. C'est incompréhensible pour l'éditeur. Je pense que le gestionnaire du catalogue doit définir ce paramètre pour son catalogue.

- [ ] Lorsqu’on supprime un des thèmes, il ne réapparait pas dans la liste avant rafraichissement de la page. --> En fait c'est quand on supprimer tout un bloc de mots-clés. 

--> criticité mineure + modif d'interface prévue ==> laisser tomber

- [ ] Catégorie ISO doit être remonté entre les thèmes INSPIRE, Géoportail, GEMET et les mot-clés + renommer en "Ajouter un thème ISO" 

--> criticité mineure + modif d'interface prévue ==> laisser tomber

- [x] Lorsqu'on veut ajouter un deuxième thème ISO, il n'y a plus de label à côté du bouton +. En ajouter un : "Ajouter un thème ISO"

- [x] Une fois ajoutée, une catégorie thématique ISO ne peut plus être supprimée. Il faut passer par la vue avancée.

- [x] Mots-clés : Renommer "Autres mots-clés" en "Mots-clés". Ajouter le label "Mot-clé" devant les mots-clés. Ajouter le label "Ajouter un mot-clé" devant le + 

- [x] Emprise géographique issue de Geonames : Lorsqu’on choisit une entrée (ex. Région wallonne), la carte disparait.

- [x] Emprise géographique Geonames : quel est l'apport de cette catégorie par rapport à celles existantes ? Si aucun, supprimer.
