### ISSUE TITLE
Documentation relative à l'API (image)

### ISSUE THREAD

**Issue by davinciagf** [SPW-DIG/metawal-core-geonetwork#377]
# Quelques images de l'avancement de l'API

### Paramétrisation de l'interface de recherche
![api-search](https://cloud.githubusercontent.com/assets/576292/24251517/b26bd232-0fda-11e7-960b-826d8ff46823.jpg)

- Définition d'un filtre de recherche de type Tab (type: dataset et service) et autres paramètres d'affichage des résultats

![api-search-facet-tab](https://cloud.githubusercontent.com/assets/576292/24251553/cfa1f2b4-0fda-11e7-82d6-ae18496c0065.jpg)

- Synthèse de la configuration au format json
![api-settings-json](https://cloud.githubusercontent.com/assets/576292/24251622/09546848-0fdb-11e7-900e-dee0a2032c8f.jpg)

## Customisation de la section de recherche

- Recherche générale avec deux filtres en mode Tab

![api-results](https://cloud.githubusercontent.com/assets/576292/24251696/5420c678-0fdb-11e7-9b92-52db242e4a86.jpg)

 - Panier

![basket](https://cloud.githubusercontent.com/assets/576292/24251705/5cb6e7a4-0fdb-11e7-8faa-853c2576b5ad.jpg)

 - Résultats avec interaction avec le panier

![result](https://cloud.githubusercontent.com/assets/576292/24251721/6c11dd62-0fdb-11e7-9659-f4ce6784d932.jpg)

**Comment by vbombaerts** [comment]
C'était juste pour l'échange des images en vue d'une présentation. Je ferme.
