### ISSUE TITLE
Problème d'encodage/décodage des URL CSW

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#378]
Remonté par Dominique. Voir éventuellement avec lui.

Les requêtes dans lesquelles les paramètres sont séparés par & passent. Celles dans lesquelles & est remplacé par %26 ou &amp; renvoient des erreurs. => problème d'encodage/décodage URL

http://geoservices3.wallonie.be/metawal/csw-inspire?REQUEST=GetRecordById&SERVICE=CSW&VERSION=2.0.2&ELEMENTSETNAME=full&OUTPUTSCHEMA=http://www.isotc211.org/2005/gmd&ID=f16124b7-41ed-42fe-9442-73b32708d60a 
=> OK

http://geoservices3.wallonie.be/metawal/csw-inspire?REQUEST=GetRecordById%26SERVICE=CSW%26VERSION=2.0.2%26ELEMENTSETNAME=full%26OUTPUTSCHEMA=http://www.isotc211.org/2005/gmd%26ID=f16124b7-41ed-42fe-9442-73b32708d60a
=> KO
Not a CSW Discovery operation: GetRecordById&SERVICE=CSW&VERSION=2.0.2&ELEMENTSETNAME=full&OUTPUTSCHEMA=http://www.isotc211.org/2005/gmd&ID=f16124b7-41ed-42fe-9442-73b32708d60a. Did you mean to use the CSW Publication service? Use service name /csw-publication

http://geoservices3.wallonie.be/metawal/csw-inspire?REQUEST=GetRecordById&amp;SERVICE=CSW&amp;VERSION=2.0.2&amp;ELEMENTSETNAME=full&amp;OUTPUTSCHEMA=http://www.isotc211.org/2005/gmd&amp;ID=f16124b7-41ed-42fe-9442-73b32708d60a
=> KO
HTTP Status 400 - Cannot build ServiceRequest Cause : The name "amp;SERVICE" is not legal for JDOM/XML elements: XML names cannot contain the character ";". Error : org.jdom.IllegalNameException

**Comment by fxprunayre** [comment]
C'est normal, ```&``` est un caractère spécial dans les URL (cf p9 http://www.ietf.org/rfc/rfc3986.txt il fait partie des sub-delims). On ne peut pas encoder avec ```%``` un caractère spécial qui dans les cas ci-dessus permet de distinguer les paramètres de l'URL (ie. SERVICE, REQUEST, ...). Idem pour ```&amp;``` qui comme ```%``` dans les URL permet d'encoder un caractère spécial dans un document XML dans ce cas ```&```.

**Comment by vbombaerts** [comment]
Si je comprends bien "&" dans l'adresse est considéré comme un délimiteur des paramètres de la requête, tandis que "&amp" ou "%26" serait considéré comme étant une valeur de paramètre ?

**Comment by fxprunayre** [comment]
> "&amp" ou "%26" serait considéré comme étant une valeur de paramètre ?

Oui puisqu'ils n'ont pas de sens particulier dans une URL - c'est du contenu.
