### ISSUE TITLE
Import d'une fiche à partir d'une URL

### ISSUE THREAD

**Issue by gdetry** [SPW-DIG/metawal-core-geonetwork#379]
Metawal 4 - Message d'erreur reçu lors de l'import par URL (test avec URL Metawal)

![image](https://user-images.githubusercontent.com/12267969/33836636-320025e2-de8a-11e7-9598-598ae1836d56.png)

**Comment by fxprunayre** [comment]
Tester avec http://metawal.wallonie.be/geonetwork/srv/fre/xml_iso19139?uuid=7cfc93d3-304a-4119-940c-429a86aa6543. Pas de pb en local. 

Tester sur l'instance de test en combinant une transfo 139->115-3 pas de pb.

![image](https://user-images.githubusercontent.com/1701393/35280083-56126300-004f-11e8-896a-2b8921ac4e71.png)

**Comment by vbombaerts** [comment]
Il faut renseigner l'adresse de la **version XML** de la fiche, pas l'adresse de la fiche.

OK : http://metawal.wallonie.be/geonetwork/srv/fre/xml_iso19139?uuid=ecf8c7a2-2d52-4680-9e8e-31068249c0ab

KO : http://metawal.wallonie.be/geonetwork/srv/fre/search?uuid=ecf8c7a2-2d52-4680-9e8e-31068249c0ab
