### ISSUE TITLE
export zip et pdf KO

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#38]
Et le retour en arrière ne va pas bien, on ne revient pas où on était.
ET si avant on a fait un changement de langue (et puis revenu en français) les messages sont en allemand

**Comment by fxprunayre** [comment]
Manque conversion iso19139

**Comment by fxprunayre** [comment]
PDF, voir #92

**Comment by vbombaerts** [comment]
Export OK.
Pas réussi à répliquer les problèmes relatifs aux langue et retour arrière.
==> je ferme
