### ISSUE TITLE
URL non valide de certaines imagettes

### ISSUE THREAD

**Issue by gdetry** [SPW-DIG/metawal-core-geonetwork#380]
Metawal 4 - je remarque que le lien vers l'imagette de certaines fiches est caduque. Pour ces fiches, l'URL dans Metawal4 est :

http://metawal.wallonie.be:80/geonetwork/srv/api/metadata/25d56977-de06-4504-9e35-ca28447c3a45/resources/vignette_bv_PR_600_600.png

Au lieu de

http://metawal.wallonie.be:80/geonetwork/srv/eng/resources.get?uuid=25d56977-de06-4504-9e35-ca28447c3a45&fname=vignette_bv_PR_600_600.png

On remarque cela que ce soit pour des fiches dans un schéma ISO 19139 ou 19115-3.

Est-ce que ça peut avoir une implication lors de la mise en prod?

![image](https://user-images.githubusercontent.com/12267969/33836777-b1f748ac-de8a-11e7-9b9d-7016b6802c08.png)

**Comment by fxprunayre** [comment]
> Est-ce que ça peut avoir une implication lors de la mise en prod?

Oui ça fera partie de la migration https://github.com/SPW-DIG/metawal-core-geonetwork/blob/257fe993b2ecc926eee6ebb97f17f49bc1c66116/web/src/main/webapp/WEB-INF/classes/setup/sql-metawal/migrate/3.4.0/migrate-default.sql#L5
