### ISSUE TITLE
Référencement des ressources associées

### ISSUE THREAD

**Issue by gdetry** [SPW-DIG/metawal-core-geonetwork#381]
Metawal 4 - import d'une fiche de métadonnées depuis Metawal de production (selon schéma 19139 ou 19115-3). Cette fiche présente 10 ressources associées (WMS, REST, lien http, lien vers légende, etc.)

Dans Metawal 4, les 10 ressources apparaissent sans titre et le lien "ouvrir le lien) ne retourne rien. 

![image](https://user-images.githubusercontent.com/12267969/33837137-b9eb7456-de8b-11e7-9947-71905ccbd7a4.png)

En édition, on visualise les ressources en ligne dans la partie droite de la fenêtre

![image](https://user-images.githubusercontent.com/12267969/33837232-fe9c640c-de8b-11e7-924b-8db666bd4460.png)

Si on édite une ressource, on s'aperçoit que le champ URL est vide.

![image](https://user-images.githubusercontent.com/12267969/33837261-163a879c-de8c-11e7-84a3-2125e78786cb.png)

Est-ce normal et quelles conséquences pour la mise en production

**Comment by fxprunayre** [comment]
Pour la partie édition, a priori corrigé avec GN3.4.0. A retester.

**Comment by davinciagf** [comment]
Le template de résultat est à vérifier afin d'afficher le titre de la données (https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-3.2.x/web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html) . Les autres éléments sont bien référencés correctement tant en recherche qu'en mode édition.

**Comment by fxprunayre** [comment]
Cf. https://github.com/geonetwork/core-geonetwork/pull/2494

**Comment by fxprunayre** [comment]
Fixed in Gn and merged in MW.

**Comment by gdetry** [comment]
Test en ré-important une fiche avec différents types de ressources associées

http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/145fe3eb-1242-4b08-9269-0479beaada28

On visualise bien les titres en consultation.
Tous les liens sont fonctionnels hormis trois aspects : 

- pour le modèle de données (lien inactif). C'est problématique
- pour le lien visualiser au droit du WMS. Le lien est OK sauf qu'au chargement, il allume le premier layer référencé dans le GetCapabilities et éteint les autres. cf. #372 
- Le lien REST n'est pas symbolisé en consultation. L'idéal serait de pouvoir le visualiser également (cf. UC François dans #372)

En édition, on remarque que
- La ressource "modèle de données" ne présente pas de titre
- La ressource de type "Légende" est affichée selon l'URL et pas le titre
![image](https://user-images.githubusercontent.com/12267969/38089310-58c69bfa-335f-11e8-954f-3a8a9b271554.png)

- Le lien REST est symbolisé
![image](https://user-images.githubusercontent.com/12267969/38091435-da6d9d6a-3365-11e8-837f-325af09d9960.png)

La ressource associée de type "modèle de données" ne présente pas l'URL. Par contre, l'information est présente au niveau XML. Peut-être une erreur dans la manière dont est attribuée la fonction pour les modèle (information.content)

![image](https://user-images.githubusercontent.com/12267969/38089541-0f432876-3360-11e8-8f08-a95a6f9046c1.png)

![image](https://user-images.githubusercontent.com/12267969/38089773-e0f23c22-3360-11e8-95d9-eb089a5b2bfa.png)

**Comment by fxprunayre** [comment]
Titre du modèle manquant dans l'éditeur. eg. PICC

**Comment by fxprunayre** [comment]
Cf. https://github.com/geonetwork/core-geonetwork/pull/3542
