### ISSUE TITLE
Sélection de fiches pour modification en batch

### ISSUE THREAD

**Issue by gdetry** [SPW-DIG/metawal-core-geonetwork#382]
Je désire modifier le contact d'une ressource en remplaçant la chaine de caractère 
"Direction de l'intégration des géodonnées (SPW - SG - DIG)"
En
"Direction de l'intégration des géodonnées (SPW - SG - DGM - DIG)"
Je fais la sélection des 83 fiches concernées depuis le module de recherche.
Pour faire la modification, je passe par "Contribuer" --> "Edition en série". A ce niveau, je perds la sélection des 83 fiches et n'arrive pas à les retrouver aisément car je n'ai pas de filtre direct sur le point de contact.

Peut-on garder la sélection active d'un module à l'autre ou peut-on passer par une autre voie pour appliquer le changement en série?

**Comment by fxprunayre** [comment]
Ajouter les facettes de la recherche dans édition (et édition en série)

Créer un ticket: Dans l'éditeur, ajouter un menu traiter la sélection pour transférer la sélection de la page de l'édtteur vers l'édition en série.

**Comment by gdetry** [comment]
La facette "Contact de la ressource" est présente à la fois dans le menu de recherche et dans le menu d'édition en série --> OK sur ce point.

L'objet du ticket, à savoir le transfert de la sélection du module de recherche au module d'édition en série, n'est pas résolu. Il y a toujours une perte de sélection. Ce point est lié à #388. Je renvoie vers ce ticket et clôture celui-ci

**Comment by gdetry** [comment]
Clôture du ticket en considérant le commentaire de François : "Ajouter les facettes de la recherche dans édition (et édition en série)" comme nouvel objet
