### ISSUE TITLE
Batch editing / Configuration 19115-3 

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#383]
[Description ajoutée par VBO]
Les modifs en batch ne sont accessibles que via Xpath si les fiches sont en ISO19115-3. Les rendre disponibles aussi  à travers l'UI, comme c'est le cas pour l'ISO 19139

En 19115-3
![2018-01-29 11_19_34-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/35505396-4f48d162-04e6-11e8-9dff-a7dce5f0148b.png)

En 19139
![2018-01-29 11_17_33-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/35505329-189cb340-04e6-11e8-9866-39d01e17179b.png)

**Comment by fxprunayre** [comment]
Done in https://github.com/metadata101/iso19115-3/commit/b71b186bf25a42dda9fd9cf59d42a285ae8a4177

BTW this would require more in depth testing.

**Comment by gdetry** [comment]
L'interface utilisateur de l'édition en série a été ajoutée pour les fiches en ISO19115-3. L'ensemble des fonctionnalité est présent.

![image](https://user-images.githubusercontent.com/12267969/38082471-14007846-3347-11e8-8f61-9b1a6a1b0eba.png)

Le test de l'interface se fait via un autre ticket : #257
