### ISSUE TITLE
Définir un taille limite pour chaque panier

### ISSUE THREAD

**Issue by davinciagf** [SPW-DIG/metawal-core-geonetwork#384]
Possibilité de configurer la limite maximale des différents paniers

**Comment by fxprunayre** [comment]
Fixée à 200.

**Comment by vbombaerts** [comment]
Doit être modifiable pour chaque panier.
Ni l'outil de téléchargement ni l'outil de visualisation (WalOnMap) ne sont prévus pour prendre en charge 200 données simultanément.

**Comment by fxprunayre** [comment]
Ce n'était pas vraiment prévu. Quelles sont leurs limites respectives ?

**Comment by davinciagf** [comment]
Je pense que c'est limité à 5 pour l'instant.

**Comment by vbombaerts** [comment]
La limite de 5 n'est pas gérable pour le panier de sélection qui doit être infini (notamment pour les opérations en batch). Je vais me renseigner auprès de mes collègues sur l'utilité de cette limitation.

**Comment by vbombaerts** [comment]
Seul le panier de téléchargement est actuellement limité à 10.

**Comment by fxprunayre** [comment]
A préciser lors de la mise en place avec API geoportail.
