### ISSUE TITLE
Adapter TG2.0 INSPIRE pour ISO 19115-3

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#387]
## Implémenter les nouvelles règlementations relatives aux MD INSPIRE 

- [x] GeoNetwork implementation https://github.com/geonetwork/core-geonetwork/pull/3399
- [x] Création d'un template ISO19115-3:2018 valide
- [x] Migrer ISO19115-3:2014>ISO19115-3:2018
- [x] Migrer pour mise en conformité avec le TG2

## Template valide

* Utiliser les anchor pour les mots clés
* Saisie des priority datasets, du spatial scope
* éventuellement d'autres règles à identifier ?
ex. ApplicationProfile pour WMS
```
<gmd:applicationProfile>
                        <gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/ApplicationProfile/view">INSPIRE View Network Service</gmx:Anchor>
</gmd:applicationProfile>
```

**Comment by vbombaerts** [comment]
https://github.com/geonetwork/core-geonetwork/issues/2593

**Comment by fxprunayre** [comment]
Cf la procédure de migration https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-3.8.x/web/src/main/webapp/WEB-INF/classes/setup/sql-metawal/migrate/3.8.0/README.md#iso19115-32018--improve-inspire-tg2-compliancy

A déployer et tester.

**Comment by fxprunayre** [comment]
Je ferme. Doublon avec https://github.com/SPW-DIG/metawal-core-geonetwork/issues/455
