### ISSUE TITLE
Editeur - Création d'un menu pour traiter la sélection en la transférant vers l'édition en série

### ISSUE THREAD

**Issue by davinciagf** [SPW-DIG/metawal-core-geonetwork#388]
Voir ci-dessous description fournie par gdetry

**Comment by gdetry** [comment]
Objet du ticket = transfert de la sélection du module de recherche au module d'édition en série, et vice-versa. Actuellement, il y a toujours une perte de sélection. 

A l'heure actuelle, on doit refaire la sélection. Gênant mais pas bloquant.
