### ISSUE TITLE
Tâche 3 - Module de déconnexion, de gestion du profil et des paramètres, barre de navigation

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#391]
- [x] User properties / Add link to gravatar to update photo
- [x] Login via email

User properties / configuration des options principales pour l’utilisateur 
 - [ ] vue de consultation,  Seule la possibilité de définir par utilisateur sa vue de consultation préférée est ajoutée. Cela suppose que tous les schémas des fiches du catalogue disposent de vue nommée de manière identique. Une zone de texte permet de définir la vue de consultation : eg. default (ie. angular view) ou le nom d'un formatter (eg. xsl-view).
 - [ ] vue d’édition, 
 - [ ] notification par email.

Question :
* A définir quelle vue par défaut ? Qu'est ce qui se passe pour un admin par rapport à un éditeur ?

## DB changes

**Users**

* receiveNotification: true/false

**Comment by stephyritz** [comment]
Ok pour le login via e-mail pour 3.6.1.
Pour le Gravatar, je n'ai pas trouvé comment faire ? Est-ce déployé pour la 3.6.1 ? Si pas, pas d'urgence de mon point de vue.
Pour la vue spécifique, je pense que ce n'est pas déployé dans la 3.6.1. 
Comme tous les points ne sont pas fonctionnels et que ce n'est pas urgent, je déplace dans future release.
