### ISSUE TITLE
Mes tâches / Permalinks

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#395]
- [x] (GN) Create permalink to open the editor with a specific status. See https://github.com/geonetwork/core-geonetwork/pull/2591

The permalink is structured as followed:
```
http://localhost:8080/geonetwork/srv/eng/catalog.edit
                     #/metadata/{metadataId}?
                           tab={onglet}&
                           scrollTo={elementSelector}&
                           displayAttributes=true&
                           displayTooltips=true&
                           displayTooltipsMode={icon|onhover}
```
The path part of the URL (after the # and before the ?) define the identifier of the metadata record to edit. Then the search part of the URL define a set of parameters to customize the editor:
* **tab**: One tab identifier defined in config-editor.xml (eg. identificationInfo, metadata, xml). Remember a view is composed of one or more tab. Point to a tab to define which view to open.
* **scrollTo**: A CSS element selector. Could be a form element id (eg. ```#gn-editor-142-2```), a class (eg. ```.gn-descriptiveKeywords```) 
* **displayAttributes** (false by default): Define if the form should display field attributes

![image](https://user-images.githubusercontent.com/1701393/36793449-b994a4fa-1c9d-11e8-835c-16514fcadb1a.png)

* **displayTooltips** (false by default): Define if tooltips are enabled by default

![image](https://user-images.githubusercontent.com/1701393/36793505-e4cd80d8-1c9d-11e8-8727-6276f108c470.png)

* **displayTooltipsMode**: Define how tooltips are displayed. Focus on the form field or click on icon

![image](https://user-images.githubusercontent.com/1701393/36794372-70b493f0-1ca0-11e8-832b-7af91d6f91f0.png)

- [ ] Add ```&readonly={tabId1,tabId2,...}``` to permalink

- [x] Si l’authentification est requise, cette URL sera utilisée par le formulaire d’identification comme redirection après validation des informations de connection de l’utilisateur.

**Comment by vbombaerts** [comment]
@vbombaerts à tester pour voir si répond au besoin

**Comment by vbombaerts** [comment]
C'est une fonctionnalité très utile pour de l'édition en série à partir de Kibana par exemple.

Le scrollTo fonctionne avec le form element id, mais je n'ai pas réussi avec la classe.
Est-il possible de donner un exemple complet ? Où trouve-t-on la liste des classes ?

Je pense que le readonly n'est pas implémenté. --> éventuellement plus tard dans le cadre du WF infraSIG
A voir si d'autres utilisateurs que les admin Metawal utilisent ce permalink pour encoder. (ca serait peut-être utile dans le cadre du workflow infraSIG ou pour un formulaire intelligent)

**Comment by davinciagf** [comment]
Ne pas oublier au niveau du paramètre 'scrollTo'  
-  pour l'id  le : `#`  
- pour la classe : `.` 

On peut identifier les classes via la console de dev du client web:
![image](https://user-images.githubusercontent.com/576292/174258473-8e3887b2-6e26-4110-ac0e-8d0abc534b1f.png)




Example : 
https://metawal.wallonie.be/geonetwork/srv/eng/catalog.edit#/metadata/52799?redirectUrl=catalog.search%23%2Fmetadata%2F79269054-0fa4-4133-9a6f-9c0cc3840878&scrollTo=.gn-MD_Distributor

https://metawal.wallonie.be/geonetwork/srv/eng/catalog.edit#/metadata/52799?redirectUrl=catalog.search%23%2Fmetadata%2F79269054-0fa4-4133-9a6f-9c0cc3840878&scrollTo=.gn-metadataLinkage

https://metawal.wallonie.be/geonetwork/srv/eng/catalog.edit#/metadata/50766?redirectUrl=catalog.search%23%2Fmetadata%2F91721175-5f01-410c-8c78-37c1d1893ba2&scrollTo=.gn-referenceSystemInfo


Note: si la classe est référencée plusieurs fois dans la fiche le scrollTo ne semble pas fonctionnel
Exemple : https://metawal.wallonie.be/geonetwork/srv/eng/catalog.edit#/metadata/52799?redirectUrl=catalog.search%23%2Fmetadata%2F79269054-0fa4-4133-9a6f-9c0cc3840878&scrollTo=.gn-referenceSystemInfo

**Comment by vbombaerts** [comment]
Merci pour la réponse.
