### ISSUE TITLE
Tâche 5.3 - Mes Messages

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#399]
Question Il faudra préciser si la notion de message est toujours rattachée à une fiche ou si les messages sont généraux pour le catalogue (ou les 2) ? De notre point de vue il semble plus pertinent d’avoir un fil de discussion associé à chaque fiche tel que les “user feedback” sont fait pour les commentaires publics des usagers.

- [x] (GN) Merge PR user feedback https://github.com/geonetwork/core-geonetwork/pull/2260 
- [ ] Search page
- [ ] Message popup form
* adresse du ou des destinataires, 
* titre du message, 
* texte du message. 

## API

* GET /api/records/{uuid}/discussions
* PUT /api/records/{uuid}/discussions
* DELETE /api/records/{uuid}/discussions/{messageId}

**Comment by PascalLike** [comment]
Please refer to https://github.com/geonetwork/core-geonetwork/pull/2419 instead of 2260
