### ISSUE TITLE
Recherche / caractères accentués

### ISSUE THREAD

**Issue by PascalDelvaux** [SPW-DIG/metawal-core-geonetwork#40]
Sur la fenêtre d'exploration dans la partie recherches avancées les caractères accentués ne sont pas pris en compte.

http://metawal3.test.wallonie.be/geonetwork/srv/fre/search?hl=fre

**Comment by fxprunayre** [comment]
cf #40 . Doublon je ferme.

**Comment by vbombaerts** [comment]
J'ai ré-ouvert le #11 car non résolu.
