### ISSUE TITLE
Tâche 6.1 - Onglet activités

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#400]
Cf. https://github.com/geonetwork/core-geonetwork/pull/3209

**Comment by fxprunayre** [comment]
Déployé avec la 3.6 et sera également amélioré en 3.8.

**Comment by stephyritz** [comment]
Comment accéder à cet onglet dans Metawal4 ?

**Comment by fxprunayre** [comment]
> Comment accéder à cet onglet dans Metawal4 ?

Easy, depuis l'admin > settings :
![image](https://user-images.githubusercontent.com/1701393/62622709-438dc500-b91f-11e9-9450-987edf1c040c.png)

C'est maintenant actif et j'ai dépublié / publié la fiche http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/06b19952-4103-471a-8d07-82a47edd7a11

**Comment by stephyritz** [comment]
Parfait, vraiment utile! Du coup, cette fonctionnalité sera active une fois le war de la 3.6 déployé en prod ?

**Comment by stephyritz** [comment]
Ok, cela fonctionne bien, c'est parfait!
