### ISSUE TITLE
Consultation - le texte sort du cadre pour les ressources associées

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#403]
* En vue simple :
![2018-01-24 17_43_40-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/35344758-2f1d255c-012e-11e8-99b4-dcf6697f60da.png)
* En vue complète :
![2018-01-24 17_46_34-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/35344978-b723e7d8-012e-11e8-9d4b-14da83882ee9.png)

http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/65541ace-497f-46ac-bf45-6293c32da8f3 , tout en bas de la page et aussi dans d'autres vues.

**Comment by davinciagf** [comment]
Adaptation: 
- limitation du nombre  de caractère afficher pour l'explication
- Affichage d'une popup lorsque l'on passe sur le button afin de montrer le texte manquant
- Mise en oeuvre d'une largeur minimale du button afin d'éviter que le texte ne dépasse (vue complète)

Exemple vue simple
![screen shot 2018-02-08 at 00 11 55](https://user-images.githubusercontent.com/576292/35961632-934ed1a2-0cae-11e8-8605-21f0cbe9e6fc.jpg)
Exemple vue complète
![screen shot 2018-02-08 at 08 49 57](https://user-images.githubusercontent.com/576292/35961634-94df1dba-0cae-11e8-995a-b2c75669d2d3.jpg)

**Comment by vbombaerts** [comment]
OK vue simple.
On y est presque vue complète.
![2018-03-26 14_33_29-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/37906523-b4eb980e-3102-11e8-9c18-feb1798d687c.png)

**Comment by davinciagf** [comment]
Fait dans GN (PR #3550)
