### ISSUE TITLE
Rétablir la vue Géoportail

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#404]
La vue géoportail n'est plus disponible en consultation. 
Elle permet de faire une prévisualisation des informations avant publication et synchronisation dans le géoportail, évitant ainsi une édition post-publication si des erreurs subsistent.
La rétablir SVP

**Comment by davinciagf** [comment]
Pour intégrer la vue "Géoportail" ou autres nouvelles vues en provenance d'un formatter, il faut introduire le formatter dédié à cette vue au niveau de la configuration de l'interface utilisateur (administration). Il suffit d'ajouter le label du formatter et son url dans la partie dédié à l'interface de recherche.
![screen shot 2018-02-08 at 09 12 40](https://user-images.githubusercontent.com/576292/35962174-c47b4ab0-0cb0-11e8-8530-d5fc88f6640d.jpg)

Exemple:

> ../api/records/{{uuid}}/formatters/geoportail-view?root=div&view=metawal

**Comment by vbombaerts** [comment]
Il faut que ce type d'information soit repris dans un guide de configuration.
Eventuellement sur le wiki.

**Comment by vbombaerts** [comment]
@davinciagf pour documentation de la procédure et des différents paramètres.

**Comment by vbombaerts** [comment]
Même problème que  #414 : c'est paramétrable mais les valeurs des paramètres ne sont pas documentées.

**Comment by vbombaerts** [comment]
Fermé car j'ai créé un issue spécifique #416
