### ISSUE TITLE
Ajout d'un service WMS comme ressource en ligne - Afficher les layer group

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#405]
Avoir la possibilité de sélectionner les layer group quand on référence une couche d'un WMS

Dans Metawal, les layer group ne sont pas affichées, donc on ne peut pas les sélectionner
![2018-02-06 11_48_25-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/35855528-c7b004f6-0b33-11e8-8af0-847e8975cddc.png)

Dans QGIS elle apparaissent correctement (mais n'ont pas de name)
![2018-02-06 11_46_19-ajouter des couches d un serveur wm t s](https://user-images.githubusercontent.com/6093597/35855544-d7a1769c-0b33-11e8-9525-d35140b2fd2e.png)

**Comment by vbombaerts** [comment]
Je ne sais pas si c'est utilisé ou pas dans Metawal. @gdetry ??

**Comment by fxprunayre** [comment]
A mettre dans maintenance 2018 ?

**Comment by gdetry** [comment]
La sélection d'un group layer sera systématiquement utilisée pour toutes les fiches de série et apportera de la cohérence entre la fiche et le service.

Le fonctionnement suivant est donc attendu

Fiche "série" : sélection du group layer --> le lien dans la fiche indique le name + title (#328) du group layer sélectionné et pointe vers le GetCapabilities du service

Fiche "fille" : sélection du layer correspondant à la couche --> le lien dans la fiche indique le name + title du layer sélectionné et pointe vers le GetCapabilities du service

En l'état, la fiche série (qui est mise en avant au niveau du géocatalogue) point vers un des layers au choix, ce qui fait perdre en cohérence et peut perturber l'utilisateur

**Comment by gdetry** [comment]
> A mettre dans maintenance 2018 ?

Nécessaire car fiche série mise en avant donc besoin de cohérence. Déplacé dans 2016-M11/B

**Comment by gdetry** [comment]
J'ai re-testé ce ticket. En l'état, comme il n'y a pas la possibilité de sélectionner des group layers, une option est de 
- Sélectionner un layer
- Modifier le nom et la description de la ressource en dur pour coller au information du groupe

Problèmes : 
- Requiert plusieurs étapes : 1) référencer le WMS et sélectionner le layer, 2) ajouter la ressource, 3) éditer la ressource pour modifier le nom et la description --> trop de manipulations
- Lorsqu'on modifie le nom de la ressource, c'est la description qui apparait dans les ressources en ligne au niveau de la fenêtre d'édition

![image](https://user-images.githubusercontent.com/12267969/38074118-f88a316a-332d-11e8-934e-1a3813c0757f.png)

Par contre, en simple consultation de la fiche, les informations apparaissent correctement.

--> Le comportement n'est pas celui attendu et, même si ce n'est pas idéal, il y a possibilité de contourner le problème. Le ticket repasse en criticité mineure
