### ISSUE TITLE
Coquilles

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#406]
Coquille - corrigé il y a un mois dans Transifex mais pas remonté dans l'application.
"Ajouté en un" --> "Ajoutez-en un"
![2018-02-26 17_51_13-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/36683568-2a6184a4-1b1e-11e8-9e08-29db0f9ca4cb.png)

**Comment by davinciagf** [comment]
@FX peux-tu faire un update des traductions - elle est dispo sur transifex. Merci

**Comment by fxprunayre** [comment]
@davinciagf A tester merge fait avec 3.4.x
