### ISSUE TITLE
Impossible de supprimer une image

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#407]
sur fiche http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/fb122cc3-3f83-4d24-be0e-bcd66ace8843

erreur
![2018-02-26 18_04_59-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/36684116-b60af67e-1b1f-11e8-80c3-3e602be4e931.png)

**Comment by vbombaerts** [comment]
Peut-être lié au fait que l'image est hébergée sur un site qui n'est pas metawal4.test (le lien redirige vers une image hébergée sur metawal de prod)

**Comment by davinciagf** [comment]
C'est la raison.
