### ISSUE TITLE
Impossible d'ajouter un aperçu

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#408]
![2018-02-26 18_16_22-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/36684650-4b8d15f0-1b21-11e8-8a51-9923070b5177.png)

**Comment by fxprunayre** [comment]
On dirait qu'il ne peut pas uploader ? pb d'install sur le serveur ? Elles devraient être uploadées directement et passer sur la partie supérieure
![image](https://user-images.githubusercontent.com/1701393/36790187-50d365d6-1c94-11e8-8705-8eab65c2f4c8.png)

En local ca fonctionne


Sinon, hier j'ai corrigé un pb pour les noms de fichier à rallonge - typiquement ceux de l'exemple - J'ai aligné MW sur GN.

**Comment by davinciagf** [comment]
Testé en local sans problème. A redéploier

**Comment by vbombaerts** [comment]
OK
