### ISSUE TITLE
Edition en série - Facette Contact de la ressource

### ISSUE THREAD

**Issue by gdetry** [SPW-DIG/metawal-core-geonetwork#409]
Pour une modification en batch, je veux sélectionner toutes les fiches qui mentionnent un contact " Direction de l'**I**ntégration des géodonnées (SPW - SG - DGM - DIG) - 81 fiches" OU "Direction de l'**i**ntégration des géodonnées (SPW - SG - DIG) - 83 fiches" pour le remplacement en " Direction de l'**i**ntégration des géodonnées (SPW - SG - DGM - DIG) - 219 fiches".

Plusieurs éléments observés avec les facettes "Contact de la ressource". Les points suivants suivent le Workflow et présentent différents "problèmes" de comportement.

- Via le menu de recherche, il y a deux facettes "Contact de la ressource" organisées de manière différente.

![image](https://user-images.githubusercontent.com/12267969/36717049-d5070c8e-1b9c-11e8-8839-e60c7edcc0b9.png)

Le nombre de fiches indiqué au droit de chaque facette pose question. Dans la première facette, 383 fiches portent la mention DIG (219+81+83) alors que dans la deuxième, on ne retrouve que 355 fiches (271+84)

![image](https://user-images.githubusercontent.com/12267969/36718201-354d6ac6-1ba1-11e8-8cac-fa2227d8503b.png)

![image](https://user-images.githubusercontent.com/12267969/36718223-4af520a8-1ba1-11e8-8116-7d06004525d4.png)

Les fiches voulues sont sélectionnées à partir de la première facette car la deuxième ne permet pas les identifier.

- Je sélectionne les 81 fiches avec contact " Direction de l'**I**ntégration des géodonnées (SPW - SG - DGM - DIG)". Le nombre de fiches "Direction de l'**i**ntégration des géodonnées (SPW - SG - DIG)" est adapté (reste 1 fiche). Je ne vois pas à quoi correspond ce nombre de fiche et ne suis pas convaincu d'avoir sélectionner toutes les fiches souhaitées.

- Lorsque je me rend dans "Contribuer" --> "Edition en série", je perds la sélection (cf. #382 ).
- Dans les facettes de l'édition en série, il n'y a qu'une facette "Contact de la ressource", ce qui est différent du module de recherche
- Dans cette facette, les contacts sont classés par ordre alphabétique, c'est un choix mais la majorité des fiches concernent le SPW. Pour atteindre la DIG, il faut étendre les menus trois fois, scroller, etc. --> Pas optimal.
- Dans cette facette, je n'ai pas la possibilité de sélectionner "Direction de l'**I**ntégration des géodonnées (SPW - SG - DGM - DIG)". Je vais donc faire une sélection de toutes les fiches avec contact "DIG" (donc les 355 fiches), ce qui ne correspond pas au niveau de détail que j'avais précédemment.
 - Quand je sélectionne DIG sous "SG --> DGM", les fiches "DIG" sous "SG" sont également cochées alors que fondamentalement, on pourrait ne pas les vouloir dans la sélection.
- Le nombre de fiches est adapté au droit des différents contacts. J'ai donc la sélection suivante

![image](https://user-images.githubusercontent.com/12267969/36718677-f5d9d8dc-1ba2-11e8-8268-e1028eedc170.png)

Par contre, le nombre de fiches qui s'affichent est de 271. Je considère donc que la sélection des fiches "DIG" n'est pas complète

![image](https://user-images.githubusercontent.com/12267969/36718743-295b4d62-1ba3-11e8-9136-c8e8d0218f19.png)

Conclusion
- Facettes non homogènes entre les menus "recherche" et "Edition en série"
- Le nombre de fiches indiqué au droit des contacts ne correspond plus à la réalité lorsqu'une sélection est effectuée
- perte de la sélection d'un module à l'autre
- en édition en série, plusieurs contacts sont cochés en même temps lorsqu'on sélectionne un seul contact
- en édition en série, le nombre de fiches sélectionnées indiqué dans la facette ne correspond pas à la sélection réelle
- Classement des contacts dans la facette "Contact de la ressource" du menu "edition en série" n'est pas ergonomique. Cette facette ne sera pas utilisée par des utilisateurs autres que ceux avertis

**Comment by vbombaerts** [comment]
Pas impossible que l'apparition du même contact à deux endroits de l'arborescence soit liée à deux encodages légèrement différents. A checker.

Sur ces deux fiches, le codage est légèrement différent.

![2018-04-05 16_34_13-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/38372855-16c67c8e-38f0-11e8-9b99-6ac4c2f8791c.png)

`<gco:CharacterString>Direction des Cours d'Eau non-navigables (SPW-DGO3-DRCE-DCENN-Cellule Limnimétrie) </gco:CharacterString>` sur http://metawal4.test.wallonie.be/geonetwork/srv/api/records/49373603-418d-451b-afb5-7badc8783a43/formatters/xml 

et 

`<gco:CharacterString>Direction des Cours d'Eau non-navigables (SPW - DGO3 - DRCE - DCENN - Cellule Limnimétrie)</gco:CharacterString>` sur http://metawal4.test.wallonie.be/geonetwork/srv/api/records/9e8f77db-8ce9-464c-b28c-9ecb96a58a31/formatters/xml

**Comment by vbombaerts** [comment]
@gdetry 
Par rapport à

> Le nombre de fiches indiqué au droit de chaque facette pose question. Dans la première facette, 383 fiches portent la mention DIG (219+81+83) alors que dans la deuxième, on ne retrouve que 355 fiches (271+84)

Il faut bien comprendre le fonctionnement de la facette points de contacts.

Le problème de trouver deux entrées différentes pour la même fiche au niveau des points de contacts est lié au fait que plusieurs points de contacts différents peuvent être associés à la même fiche.
Dans ce qui avait été imaginé au départ pour le fonctionnement de cette facette, l'utilisateur pouvait choisir deux variables : le nom du point de contact et le rôle du point de contact. Ainsi, il aurait été possible de sélectionner toutes les fiches pour lesquelles la DIG était mentionnée comme distributeur ou toutes les fiches pour lesquelles la DIG était mentionnée quel que soit son rôle. C'était trop complexe à mettre en place, donc on n'a conservé que le nom du point de contact, et tous les rôles sont indexés indifféremment.
Du coup, il n'est pas impossible de se retrouver avec plusieurs points de contact pour la même fiche, voir le même point de contact, mais avec plusieurs graphies, comme tu le montre dans ton exemple : Direction de l'intégration vs direction de l'Intégration vs... Dans ce cas, un même fiche va être attaquable par 3 valeurs différentes de la même facette. Les chiffres derrière les valeurs des facettes ne sont donc pas additionnables pour connaitre le nombre de fiches ! C'est visible dans l'exemple ci-dessous, où un total de 129 fiches correspondent au critère SPW-SG-DGM-DIG. De ces 129, trois correspondent aussi au critère SPW-SG-DIG. Cela veut dire que pour ces 3 fiches, on trouve deux codages différents pour le même point de contact ==> à corriger ;-)

![2018-04-05 16_49_32-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/38373797-59a601f8-38f2-11e8-9db3-da8e89ec6651.png)

Si tu cherches à sélectionner toutes les fiches qui ont à la fois SG-DGM-DIG et SG-DIG, ce n'est pas possible directement en cochant les deux cases (tu peux n'en cocher qu'une à la fois). Mais c'est possible en jouant avec les outils de sélection. Choisir une facette, sélectionner tous les résultats, restreindre le catalogue à ces résultats, choisir l'autre facette. Ceux qui restent sont ceux qui ont les deux contacts dans la fiche. Ex : http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/search?_uuid=9c1d8995-cef7-4e43-82f8-916248dbb547%20or%20534b7e54-d553-47e6-9a45-df7b42d1826e%20or%20b9336cfd-f590-42eb-bc6f-06c46247c9f9&from=1&to=20
![2018-04-05 16_51_49-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/38374180-501de47e-38f3-11e8-8833-72b3d267246d.png)
En corrigeant, la "ligne hiérarchique" de la facette sera respectée. Càd que si tu coches SPW-SG-DGM-DIG, tu ne devrais plus avoir la case SG-DGM-SIG qui apparait (cochée)

**Comment by vbombaerts** [comment]
> Via le menu de recherche, il y a deux facettes "Contact de la ressource" organisées de manière différente.

C'est une erreur. Seule la facette hiérarchique doit être conservée.

**Comment by vbombaerts** [comment]
Comme les remarques concernent l'interaction facette points de contact et édition en série, j'ai requalifié le ticket.
