### ISSUE TITLE
Connexion / emplacement du nom d'utilisateur et du bouton déconnexion

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#41]
Ce qui est voulu : d'abord le nom, et puis déconnecter, sur la même ligne
![image 617](https://f.cloud.github.com/assets/6093597/1662213/42ed2114-5bfa-11e3-8592-e9255033763a.png)

**Comment by fxprunayre** [comment]
Nous n'avons que 150px pour le nom + le bouton dans la charte graphique. Positionnement sur 2 lignes.

**Comment by vbombaerts** [comment]
Je veux la même chose que sur le géoportail. Tant pis pour la charte graphique, personne ne va compter les pixels... By the way, est-il possible de remplacer "Connexion" par "Se connecter" et déconnexion par "Se déconnecter"

Je veux pas ça...
![image 636](https://f.cloud.github.com/assets/6093597/1782913/2c2702b2-68b9-11e3-8128-43d6ed365b6b.png)

Je veux +/- la même chose que Samuel, sur le géoportail ;-)
![image 637](https://f.cloud.github.com/assets/6093597/1782926/6a98e916-68b9-11e3-9f2d-038c8232eb48.png)
![image 638](https://f.cloud.github.com/assets/6093597/1782928/6cf1b260-68b9-11e3-8193-d4e1702f8da2.png)
