### ISSUE TITLE
Env MW4 - Script ne répond pas

### ISSUE THREAD

**Issue by gdetry** [SPW-DIG/metawal-core-geonetwork#410]
Lors de l'utilisation de l'environnement de test Metawal (MW4.test) dans FF, l'invite « Attention : le script ne répond pas » apparait très fréquemment et des lenteurs sont observées au niveau de l'application

![image](https://user-images.githubusercontent.com/12267969/36722959-4465e430-1baf-11e8-93ce-135b5ea43b07.png)

Apparait lors d'un changement de page et lorsqu'il faut charger une série de fiches (résultat d'une sélection, retour au module de recherche, etc.). 

Problème très bloquant pour effectuer les tests sur l'environnement MW4.test car il y a trop de temps d'attente intempestifs. Engendrera de gros problèmes d’utilisation si cela se répercute en prod.

Pas testé sur Chrome ou IE.

**Comment by vbombaerts** [comment]
#425
