### ISSUE TITLE
Edition en série / fiches ISO 19139 et 19115-3

### ISSUE THREAD

**Issue by gdetry** [SPW-DIG/metawal-core-geonetwork#411]
Test du module édition en série avec les use case suivants uniquement sur fiches ISO 19139

1. Remplacement d'un titre dans deux fiches
Duplication de la fiche "INSPIRE - Points d'adresses en Wallonie (BE) - test GD" pour avoir deux fiches
- INSPIRE - Points d'adresses en Wallonie (BE) - test GD
- INSPIRE - Points d'adresses en Wallonie (BE) - test GD2
Sélection de ces deux fiches et transformation du titre en "INSPIRE - Points d'adresses en Wallonie (BE) - test Geoffroy - test GD batch" 
![image](https://user-images.githubusercontent.com/12267969/36724259-f2cd20c6-1bb2-11e8-85a3-520bdaa7cdd0.png)

--> Les fiches sont traitées mais quand on les recherche (via module de recherche ou module édition en série), les fiches ne portent plus de titre! 
![image](https://user-images.githubusercontent.com/12267969/36724296-140a8ab2-1bb3-11e8-8116-b9276ecfb429.png)

![image](https://user-images.githubusercontent.com/12267969/36724403-65c31478-1bb3-11e8-9040-f31bd72214d4.png)

Dans le xml, la balise est vide
![image](https://user-images.githubusercontent.com/12267969/36724541-ce66777c-1bb3-11e8-89ad-d77a9334d1a0.png)

2. Ajout d'un mot-clé commun dans deux fiches
Sélection des fiches et édition en batch
Le mot-clé s'ajoute bien dans les deux fiches mais est positionné dans les thèmes du geoportail pour les deux fiches sélectionnées.
![image](https://user-images.githubusercontent.com/12267969/36725738-8e6b6552-1bb7-11e8-83e5-93fb683e11db.png)

Test avec deux autres fiches et cette fois le mot-clé est dans les thèmes GEMET
![image](https://user-images.githubusercontent.com/12267969/36726014-8c7c5b6a-1bb8-11e8-9f30-96a0f57bafe7.png)

3. Edition du contact de la ressource
Sélection de fiches et ajout d'un contact pour la ressource "test batch (SPW - SG - DGM - DIG)". 
![image](https://user-images.githubusercontent.com/12267969/36726464-2783e1c2-1bba-11e8-8990-84126374d2c9.png)

Pas la possibilité d'appliquer le changement ou l'insertion
![image](https://user-images.githubusercontent.com/12267969/36726505-4493a31a-1bba-11e8-8d0c-f5907f7902f6.png)

4. Modification du contact de la ressource et de la généalogie
![image](https://user-images.githubusercontent.com/12267969/36726561-77a10ff4-1bba-11e8-98bf-839922f062ed.png)

![image](https://user-images.githubusercontent.com/12267969/36726570-8473c4ec-1bba-11e8-81dc-e16459667821.png)
Les fiches sélectionnées sont traitées.
La généalogie a bien été changée mais pas le contact

Autres UC à suivre

**Comment by fxprunayre** [comment]
> Remplacement d'un titre dans deux fiches

Fixed in https://github.com/geonetwork/core-geonetwork/commit/b663615a557efea00819d7969e40f65270102650

> Pour les mots clés, nous ne pouvons pas créer une interface pour tous les cas de figure possible et imaginable. En attendant mieux, tu peux avec le mode avancé préciser l'endroit où faire l'insertion avec un XPath plus précis. 

eg. Insertion dans un bloc par position
![image](https://user-images.githubusercontent.com/1701393/36789203-f629e2a2-1c90-11e8-8cb5-ed7c3597c937.png)

eg. Insertion dans un bloc avec un critère
![image](https://user-images.githubusercontent.com/1701393/36789199-f3149a9e-1c90-11e8-8bd4-3cf919bf1780.png)


Sur ce ticket, je le place en version future (à mettre en maintenance 2018 si prioritaire), mais je pense qu'il ne faut pas qu'il soit bloquant pour la mise en prod de la version 3.4 - sinon on ne va pas y arriver. Si vous souhaitez vraiment faire de nombreux changements dans les fiches avant la mise en prod, ce pourrait être plus efficace de définir la liste de tous les changements à faire et de les faire en bases de données ou en XSL (selon les modifs souhaitées) lors du passage en 115-3. Ce n'était pas prévu mais ça peut être plus efficace si on veut tenir le planning qu'on avait fixé. Qu'en pensez-vous ?

**Comment by gdetry** [comment]
Test de UC avec UI en env. test et sur les fiches ISO 19115-3 "mère-fille" suivantes
uuid : 145fe3eb-1242-4b08-9269-0479beaada28 et a9c7c5fe-a896-416c-b11a-439306e75d59

- Remplacement de la généalogie dans les deux fiches (élement type gco:CharacterString)
OK, le bloc d'information encodé est bien répercuté dans les fiches sélectionnées
![image](https://user-images.githubusercontent.com/12267969/38128711-043cab90-33fc-11e8-873f-52a2d0bab851.png)

- Remplacement de l'étendue spatiale : Sélection de la Région = Wallonie et ensuite adaptation de la BB pour avoir deux décimales (spécification INSPIRE).
![image](https://user-images.githubusercontent.com/12267969/38131070-d5f70460-3405-11e8-9dd7-66e9cbb384d9.png)
Les modifications sont appliquées mais **ne sont pas répercutée**s dans les fiches
![image](https://user-images.githubusercontent.com/12267969/38131147-414aaf50-3406-11e8-94d9-e41e8f83bad7.png)

- Remplacement du status de finalisé --> Mise à jour continue
Les modifications sont appliquées mais **ne sont pas répercutée**s dans les fiches

- Insertion d'un contact
Je renseigne un contact dans le champ "contact pour la ressource". Les modifications ne peuvent être appliquées (bouton "enregistrer" grisé)

- Test en mode avancé (xpath) sur fiche ISO 19139

Test de modification d'une coordonnée dans la bounding box via xpath. La configuration suivante est utilisée

![image](https://user-images.githubusercontent.com/12267969/38136940-f2fdeb2a-3421-11e8-8b13-98da09f88b4b.png)

Lorsqu'on souhaite appliquer les modifications, le bouton "Enregistrer" reste grisé et la mentions "Définir les modifications afin de mettre à jour les fiches sélectionnées" est affichée






Remarque : avec le disponibilité de l'UI pour 19115-3 (cf. #383), le titre du ticket a été changé pour correspondre aux tests de l'édition ens érie tant pour les fiches ISO 19115-3 que 19139

**Comment by vbombaerts** [comment]
> Sur ce ticket, je le place en version future (à mettre en maintenance 2018 si prioritaire), mais je pense qu'il ne faut pas qu'il soit bloquant pour la mise en prod de la version 3.4 - sinon on ne va pas y arriver. Si vous souhaitez vraiment faire de nombreux changements dans les fiches avant la mise en prod, ce pourrait être plus efficace de définir la liste de tous les changements à faire et de les faire en bases de données ou en XSL (selon les modifs souhaitées) lors du passage en 115-3. Ce n'était pas prévu mais ça peut être plus efficace si on veut tenir le planning qu'on avait fixé. Qu'en pensez-vous ?

La modification conjointe de plusieurs fiches est une fonctionnalité vraiment nécessaire pour augmenter la productivité de l'encodage et garantir de la cohérence au niveau de groupes de fiches. C'est pour moi un élément prioritaire. Que nous apporte la v3.4.0 si on laisse tomber l'édition multiple ?
La crainte est de migrer une version 3.4.0 qui n'apporte rien de vraiment neuf mais amène des risques, notamment par rapport au fonctionnement du GP et par rapport à INSPIRE. Pour bien évaluer tout ça, Geoffroy et moi sommes en train de faire un bilan complet de la v3.4.0. A partir de ce bilan, on définira ce qu'on peut reporter et ce qui est indispensable. 

Je repasse donc le ticket sur la 3.4.0 pour le moment.
