### ISSUE TITLE
Import fiche - Mots-clé INFRASIG

### ISSUE THREAD

**Issue by gdetry** [SPW-DIG/metawal-core-geonetwork#412]
Les mots-clé INFRASIG ne suivent pas au niveau de l'interface (édition simple/avancée) lors de l'import d'une fiche 
![image](https://user-images.githubusercontent.com/12267969/36728389-e2ff864e-1bc0-11e8-8236-7ca98eccf443.png)

Ils sont repris dans le xml
![image](https://user-images.githubusercontent.com/12267969/36728531-5669c9fa-1bc1-11e8-9a3a-66646db6cf07.png)

**Comment by gdetry** [comment]
Tests avec fiches en ISO 19115-3 et 19139. Même constat que ce soit en vue simple ou complète

**Comment by davinciagf** [comment]
@gdetry Id de la fiche et s'agit-il d'un import prod -> test?
Il y a une différence entre la prod et le test pour ce thesaurus. Le thesaurus infraSIG est n'est pas local en test!

**Comment by gdetry** [comment]
Effectivement, import de la prod --> test avec id en test 
http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/4ce8081f-4766-4ab4-829b-6e39055f91c1
et
http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/33c16acd-7047-4129-82b6-684dc89270ed

Les mots-clés INFRASIG apparaissent bien en consultation de fiche mais pas en édition.

**Comment by davinciagf** [comment]
Mettre le thesaurus en local!
