### ISSUE TITLE
Dépublication

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#413]
Quand je dépublie tout, des fiches sont encore visibles.
1. Login comme admin
2. Sélectionner tout
3. Dé-publier
4. Se déconnecter
--> encore 256 fiches visibles

Quid ?

**Comment by vbombaerts** [comment]
Edit : c'est juste une question de temps avant que tout soit dépublié. (plusieurs minutes)

**Comment by fxprunayre** [comment]
C'est le NRT ... Near Real Time ;)
