### ISSUE TITLE
Tri par date de mise à jour

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#414]
Le tri par mise à jour trie par date de la mise à jour de la donnée, pas de la fiche.
Soit prévoir les deux, soit implémenter la date de mise à jour de la fiche qui est l'élément le plus utile pour des rédacteurs de MD.

**Comment by vbombaerts** [comment]
J'imagine qu'il y a moyen de configurer via la paramétrisation de l'interface utilisateur, mais où puis-je trouver les chaines que je dois encoder pour les filtres ?
![2018-03-26 16_42_31-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/37913717-d47ca3b2-3115-11e8-9afd-61e91f133dee.png)

**Comment by fxprunayre** [comment]
> mais où puis-je trouver les chaines que je dois encoder pour les filtres ?

cf. https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-3.4.x/schemas/iso19139/src/main/plugin/iso19139/index-fields/default.xsl#L1008-L1009

ChangeDate correspond à gmd:dateStamp normalement.

**Comment by vbombaerts** [comment]
Allez comprendre pourquoi, maintenant ça marche...
