### ISSUE TITLE
Problème avec une imagette hotlinkée

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#415]
Lors du chargement d'un imagette qui n'est pas hébergée sur Metawal, on obtient le message suivant : "Le catalogue n'arrive pas à accèder à l'URL actuelle (cela peut être lié à une erreur de proxy ou l'URL n'est pas disponible en ce moment). Vous devriez vérifier l'URL manuellement avant de l'ajouter à la fiche."

Pourtant l'imagette est bien visible lors de la première édition.

![2018-03-26 12_49_53-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/37902653-5b3e471e-30f5-11e8-9c81-11140e30755d.png)

Si on tente d'éditer une deuxième fois, l'imagette n'est plus visible. 
Idem en consultation : la première fois visible, puis si on change de vue : invisible.

**Comment by fxprunayre** [comment]
L'URL à tester https://pixnio.com/free-images/2017/12/13/2017-12-13-22-28-25.jpg

**Comment by fxprunayre** [comment]
Le site semble faire des choses intelligentes, il redirige l'appel du proxy qui tente de voir si le lien fonctionne:

![image](https://user-images.githubusercontent.com/1701393/38017968-e4633e3a-3273-11e8-898c-a7b85ff4722f.png)

Status 302 redirect donc.

On le redirige vers https://pixnio.com/img-url?image=https://pixnio.com/free-images/2017/12/13/2017-12-13-22-28-25.jpg qui est une page HTML et on a également une erreur relative à CORS 
![image](https://user-images.githubusercontent.com/1701393/38018185-77200ac8-3274-11e8-9478-51872bbdf1bc.png). Dans un navigateur, l'image s'affiche donc il doit faire des choses différentes selon les caractéristiques de l'appelant...
 
et ensuite, vu que l'image est accessible en HTTPs, j'imagine que même si ça marchait y'aurait un warning car metawal n'est pas en HTTPs.

Actuellement, le message ne s'affiche pas si le code est OK ie. 200.

S'il faut gérer ça, je propose de le passer en maintenance 2017

**Comment by vbombaerts** [comment]
Vu que le cas ne se présente pas souvent, on va gérer ces cas en hébergeant directement les images sur Metawal. 

@gdetry : OK ?
