### ISSUE TITLE
lien et pdf

### ISSUE THREAD

**Issue by metawaltest** [SPW-DIG/metawal-core-geonetwork#42]
Lors de la recherche, les documents attachés sont soit dans "lien" soit dans "pdf", ce n'est pas tout le temps la même chose

![liens](https://f.cloud.github.com/assets/6093500/1662217/5661100c-5bfa-11e3-940b-09014febf198.jpg)

**Comment by fxprunayre** [comment]
Le nom du bouton dépend du type de documents et en particulier du protocole de la ressource en ligne dans la fiche encodée. Donc les boutons dépendent de la fiche.

**Comment by davinciagf** [comment]
voir (#99)
