### ISSUE TITLE
Facette Diffusion - incomplète

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#420]
Seule la valeur "Téléchargement" apparaît. Où sont les autres ?

* Metawal
![2018-03-28 17_38_48-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/38040158-382ca39a-32af-11e8-8d44-87d1d86d05a9.png)

* GP
![2018-03-28 17_39_00-catalogue des donnees et services](https://user-images.githubusercontent.com/6093597/38040203-40b4d690-32af-11e8-82e2-598f22bcc201.png)

**Comment by davinciagf** [comment]
@vbombaerts peux-tu confirmer les règles:
- Carte thématique 
  - protocol = WWW:LINK-1.0-http--link
  - function = browsing
  - applicationProfile ='' ou non référencé
- WALONMAP 
  - protocol = ESRI:REST
  - function = browsing
- Service
  - resourceScope = service
- Téléchargement
  - protocol = WWW:LINK-1.0-http--link
  - function = download

**Comment by vbombaerts** [comment]
L'idée est de pouvoir sélectionner les données/séries selon leur mode d'accès.
Donc, ce filtre ne s'applique que pour les données et séries, pas pour les services/applications

En 19139
--> resourceScope = dataset ou series

* Donnée accessible via une carte thématique si pour 
`/gmd:MD_Metadata/gmd:distributionInfo/gmd:MD_Distribution/*/gmd:MD_DigitalTransferOptions/gmd:onLine/gmd:CI_OnlineResource/`

String | Value
-- | --
`gmd:protocol/gco:CharacterString` | WWW:LINK-1-http--LINK
`gmd:function/gmd:CI_OnLineFunctionCode` | browsing
`gmd:applicationProfile/gco:CharacterString` | vide ou absent



* Donnée accessible via WalOnMap si un service de visualisation ESRI ou WMS ou WMTS existe (voir ci-dessous) et absence du mot-clé "WalOnMapNO"



* Donnée accessible via un service de visualisation si pour 
`/gmd:MD_Metadata/gmd:distributionInfo/gmd:MD_Distribution/*/gmd:MD_DigitalTransferOptions/gmd:onLine/gmd:CI_OnlineResource/`

String | Value
-- | --
`gmd:protocol/gco:CharacterString` | ESRI:REST or OGC:WMS or OGC:WMTS
`gmd:function/gmd:CI_OnLineFunctionCode` | browsing




* Donnée accessible en téléchargement direct si présence du mot-clé "PanierTelechargementGeoportail" ou si pour
`/gmd:MD_Metadata/gmd:distributionInfo/gmd:MD_Distribution/*/gmd:MD_DigitalTransferOptions/gmd:onLine/gmd:CI_OnlineResource/`

String | Value
-- | --
`gmd:protocol/gco:CharacterString` | WWW:LINK-1.0-http--link
`gmd:function/gmd:CI_OnLineFunctionCode` | download


@gdetry tu confirmes que c'est bien comme ça que tu codes ?

**Comment by gdetry** [comment]
Facette contient trois options qui sont reprises du Geocatalogue : WalOnMap, Téléchargement et Carte thématique. L'option "service" est sous-entendu par WalOnMap.
