### ISSUE TITLE
Facettes doublon de "donnée officielle" avec "mots-clés InfraSIG"

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#422]
Ces deux facettes présentent en fait les mêmes critères de sélection pour deux publics différents.
Voir ce qu'on en fait.

**Comment by davinciagf** [comment]
Facet "Donnée officielle" conservée pour l'api (géoportail)
Facet "Mots-clés InfraSIG" conservée au niveau de la recherche
