### ISSUE TITLE
Consultation - vue GP ISO19115-3 - traductions

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#426]
Exemple sur fiche 

http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/547fa5f7-525b-4e1a-81c3-9f95845f5956 

-------------

![2018-03-30 17_22_30-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/38143032-0d1c847c-343f-11e8-9d7f-44fd8865fc11.png)

-------------

![2018-03-30 17_23_50-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/38143070-364d9ffc-343f-11e8-8a3e-f1b24ca1c081.png)

---------------

![2018-03-30 17_25_38-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/38143130-6a4cfc6c-343f-11e8-88a2-4cd57a8ad278.png)

**Comment by stephyritz** [comment]
OK en test pour certains aspects. D'autres restent problématiques comme le format des dates. Elles sont toutes sous forme "il y a x temps..." au lieu de jj/mm/aaaa.
 Voir exemple http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/73414a3a-fe93-49dd-9ecd-7137e54402cf et prt sc en attaché.
![exemple_pb_format_date_vue_geoportail](https://user-images.githubusercontent.com/34446202/61465334-285f1380-a978-11e9-869b-78884024e8f1.png)

Correction pour 3.8 si cela ne prend pas trop de temps. Sinon on laisse tomber car pas prioritaire pour le moment.
