### ISSUE TITLE
Consultation - recherche avancée par date

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#431]
Plusieurs problèmes sur la recherche par date :

- [x] Les recherches par dates ne renvoient pas de résultat pertinent. Par exemple pour une fiche éditée ce jour, la recherche avec le critère "aujourd'hui" ne retourne aucun résultat.

![2018-04-06 11_24_59-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/38426094-fb97d018-39b5-11e8-93cb-b35bb5033e50.png)

Alors qu'il y a bien une fiche éditée aujourdh'ui
![2018-04-06 11_28_35-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/38426237-697cdf24-39b6-11e8-80a1-5aebbfaab9be.png)

- [x] Quand on change plusieurs fois d'affilée la période de recherche, les dates deviennent incohérentes. Elles se décalent chaque fois par rapport à la date de fin d'intervalle. Par exemple, si on fait trois fois "aujourd'hui" d'affilée, la première fois le range correspond à aujourd'hui, la deuxième à demain, le troisième à après-demain. Comportement similaire quand on mélange les aujourd'hui, il y a  6 mois, cette année, etc.

![2018-04-06 11_26_42-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/38426278-88236042-39b6-11e8-8a03-a364f0efbedf.png)

- [ ] Calendrier : l'activation de la zone pour aller vers la gauche est trop courte. Quand la souris est sur la double flèche, elle s'éteint.

![2018-04-06 11_39_49-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/38426316-a4f951fe-39b6-11e8-8450-1bda95d6a362.png)
![2018-04-06 11_39_38-metawal - catalogue pour l information geographique de wallonie - service public](https://user-images.githubusercontent.com/6093597/38426321-a78547b6-39b6-11e8-8861-27e586a63674.png)

- [ ] Calendrier : c'est pratique quand on ouvre le calendrier d'avoir un marqueur visuel qui correspond à aujourd'hui. Il s'agit juste d'un marqueur, pas d'une sélection de date.

**Comment by fxprunayre** [comment]
1er point https://github.com/SPW-DIG/metawal-core-geonetwork/commit/53e538453002b630f7d296e3d570a3879cf74135. En cours de vérif pour voir si s'applique à GN également.

2eme point https://github.com/geonetwork/core-geonetwork/pull/3545

**Comment by fxprunayre** [comment]
* Calendar do not update model on typing

**Comment by fxprunayre** [comment]
> * Calendar do not update model on typing

https://github.com/geonetwork/core-geonetwork/pull/3562
