### ISSUE TITLE
Incohérence dans le décompte des résultats de recherche

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#432]
Il y a une différence de 2 records entre l'interface de Metawal et le CSW.
Une idée ?

![2018-06-25 10_23_46-metawal - catalogue pour l information geographique de wallonie _ 691 fiche s](https://user-images.githubusercontent.com/6093597/41839627-00bbb91e-7864-11e8-9842-b87d8ea23810.png)

![2018-06-25 10_39_16-mozilla firefox](https://user-images.githubusercontent.com/6093597/41839642-0bb30660-7864-11e8-9f29-50003088ad52.png)

**Comment by fxprunayre** [comment]
eg. Co working wallonia

**Comment by fxprunayre** [comment]
> eg. Co working wallonia

Je ne reproduis pas en local avec import de la fiche, donc ce serait à tester après migration avec un dump complet de la base.

**Comment by davinciagf** [comment]
Cette différence n'est présente que pour des utilisateurs identifiés.
