### ISSUE TITLE
GeoCatalogue - Eléments non récupérés

### ISSUE THREAD

**Issue by gdetry** [SPW-DIG/metawal-core-geonetwork#433]
Ce ticket fait référence aux éléments de métadonnées non récupérés dans les templates du Geocatalogue déployé en test.

- **Environnement** : Metawal4.test et Geocatalogue en environnement de test
- **Templates testés** : Données (avec MD série et donnée - raster et vecteur), Services, Applications et Cartes statiques

### **Document d'analyse**

* [Voir Wiki :Récupération des MD dans Geocatalogue](https://github.com/SPW-DIG/metawal-core-geonetwork/wiki/Analyse-R%C3%A9cup%C3%A9ration-MD-dans-GeoCatalogue)
 
### **Problèmes rencontrés**
- Les fiches référençant des services ne sont pas visibles bien qu'elles soient présentes dans la requête CSW

![image](https://user-images.githubusercontent.com/12267969/46276875-ca387f80-c561-11e8-904a-712f4cadb1ab.png)

http://metawal4.test.wallonie.be/geonetwork/srv/fre/csw?request=GetRecordById&service=CSW&outputSchema=http://www.isotc211.org/2005/gmd&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=c5d1d35d-7f02-4a47-9361-b15d20eed232

- Rubrique **Accès** --> Les liens vers les fiches descriptives des WebServices ne sont pas activés (en lien avec absence des fiches de WS

- Rubrique **Description** 

Problèmes dans la récupération des modèles de données (OnLineFunctionCode ="information.content") et les légendes (OnLineFunctionCode ="information.portrayal")

Les liens vers MW doivent être adaptés
Les identifiants locaux ne sont pas repris

- Rubrique **Qualité** 

Problèmes avec la généalogie qui n'est pas toujours récupérée
Problèmes avec les documents relatifs à la qualité qui s'affichent mal, de manière incomplète ou tous les documents ne sont pas repris

- Rubrique **Ressources associées**

Problème avec les données associées qui n'apparaissent pas. Les liens sont de type "Collection/source, CrossReference, PartOfSeamlessDatabase)

**Comment by davinciagf** [comment]
Voir récupération des documents attachés (coquille avec ?)
