### ISSUE TITLE
INSPIRE - Erreur de validation

### ISSUE THREAD

**Issue by gdetry** [SPW-DIG/metawal-core-geonetwork#434]
Ce ticket global reflète les tests de validation menés sur des fiches devant être INSPIRE compliance

En lien avec #316, j'ai fait tourner une série de tests de validation sur la validateur INSPIRE et fait un comparatif des résultats entre des fiches issues de MW3-prod et MW4-test.

Je me suis basé sur la fiche "INSPIRE - Protected Sites" (importée de la prod vers la test), ainsi que les fiches de services associées

Les tests ont été principalement menés sur la sandbox http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/

Les tests et résultats sont compilés dans un document - cf. Wiki - https://github.com/SPW-DIG/metawal-core-geonetwork/wiki/Analyse-Validation-INSPIRE

Les conclusions des tests sont :

- **Schéma non valide** : le xsi:schemaLocation n’est pas repris dans l’en-tête du fichier de test. 

Suite à cela, j'ai fait un ajout manuel des xsi et on observe un problème de validation sur les DateType

- **Keywords INSPIRE theme** : en prod, ça saute au niveau des mots-clés faisant référence au thème INSPIRE. Il faut se baser sur des URI. Néanmoins, l'erreur n'est pas explicite et signale que la date ou dateType sont incorrects. Il faut s'attendre à avoir le même problème en test

**Comment by fxprunayre** [comment]
Corrigé en GN 3.6.0
* Site ISO en https https://github.com/geonetwork/core-geonetwork/pull/3420
* 2 decimals https://github.com/geonetwork/core-geonetwork/pull/3423

**Comment by davinciagf** [comment]
Vérifier la transformation 155-3 vers 39 pour les services (element srv toujours présent au niveau du titre)
Exemple fiche http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/d7e8a2f1-8cb1-4e4c-9d36-74ca79a494aa

**Comment by fxprunayre** [comment]
> Vérifier la transformation 155-3 vers 39 pour les services (element srv toujours présent au niveau du titre)
> Exemple fiche http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/d7e8a2f1-8cb1-4e4c-9d36-74ca79a494aa

Fixed in https://github.com/metadata101/iso19115-3/commit/d86535175413aa7cf5f50a59baa46c19fa3f6c8e
