### ISSUE TITLE
Validation INSPIRE des fiches

### ISSUE THREAD

**Issue by gdetry** [SPW-DIG/metawal-core-geonetwork#435]
En lien avec les tests globaux de validation de fiches suivant les spécifications INSPIRE  (cf #434), ce ticket concerne le comportement de l'outil de validation INSPIRE intégré dans Metawal4.

J'ai fait jouer la validation INSPIRE depuis la fiche "INSPIRE - Sites protégés"

http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/ffc45d44-1cc2-4924-bb8c-214096eb9058 

Manipulation : ouverture de la fiche en édition >> clic sur le bouton à menu déroulant « check » de la barre d’outils >> « Inspire validation

![image](https://user-images.githubusercontent.com/12267969/46402657-abbcba80-c700-11e8-9715-8865ecd45129.png)
 
Comportement : 
-	rien ne se passe, pas de message de validation
-	En rafraichissant le menu « validation », aucun critère n’est spécifié ou en erreur

![image](https://user-images.githubusercontent.com/12267969/46402707-d444b480-c700-11e8-9392-d7380d515c97.png)
 
Cette fiche n’est pas valide suivant les tests menés dans #434 

Au niveau de la console d’administration, l’adresse de la sandbox avait été mentionnée
 
![image](https://user-images.githubusercontent.com/12267969/46402744-eaeb0b80-c700-11e8-8287-3c50ac9903f1.png)

D’autres paramètres sont-ils à mentionner ou faut il configurer quelque chose ?

**Comment by gdetry** [comment]
Mis en criticité mineure car ne devra pas impacter la MeP mais fonctionnalité très utile pour faire de la validation directement dans MW

**Comment by fxprunayre** [comment]
Action désactivée pour les fiches non ISO19139 https://github.com/geonetwork/core-geonetwork/pull/3298/commits/1cf680c69e63c5f8f0364c49b5773aded2e91970. Après merge 3.6.0, le bouton ne sera plus dispo pour les fiches 115-3.

Pour la version 3.4.0, supprimer l'URL du validateur dans l'admin.

**Comment by stephyritz** [comment]
Où en est-on avec le côté validateur ? C'est vrai que c'est une fonction intéressante. A voir comment on peut utiliser les mêmes critères que http://inspire.ec.europa.eu/validator/ 
Est-ce possible/pertinent de proposer cela dans l'interface d'édition de la fiche maintenant qu'elles sont en 115-3 ? Peut-être faut-il conserver la fonctionnalité mais l'intégrer ailleurs ?! A discuter, je déplace cette issue pour le déploiement de la version 3.8.

**Comment by fxprunayre** [comment]
C'est fait via https://github.com/geonetwork/core-geonetwork/pull/3915.

**Comment by stephyritz** [comment]
D'accord. Mais cela sera sûrement déployé dans le cadre de la version 3.8.0 alors car, pour l'instant, cela me semble non opérationnelle dans l'environnement de test que je suis en train de vérifier (3.6.1).
![ex interface_mw4_3 6 1_test](https://user-images.githubusercontent.com/34446202/61524094-fb613e00-aa15-11e9-8b6e-1816dc573640.png)

**Comment by fxprunayre** [comment]
Oui je l'ai fait semaine dernière (et ne backport rien en 3.6.x).
