### ISSUE TITLE
Edition - Formulaire d'édition ne s'affiche pas

### ISSUE THREAD

**Issue by gdetry** [SPW-DIG/metawal-core-geonetwork#437]
Suite à la migration des fiches depuis MW3 prod (oracle) vers MW4 test (PG), le formulaire d'édition ne s'affiche plus quel que soit la fiche.

Opérations :
- Ouverture d'une fiche. Les informations apparaissent bien
![image](https://user-images.githubusercontent.com/12267969/47280091-f3828380-d5d4-11e8-8e60-546ae956cb51.png)

- Clic sur Editer >> Page blanche. Le formulaire n'est pas chargé. Les boutons sont actifs mais génèrent des erreurs.
![image](https://user-images.githubusercontent.com/12267969/47280102-072dea00-d5d5-11e8-8a67-4467dbf29eae.png)

![image](https://user-images.githubusercontent.com/12267969/47280141-3d6b6980-d5d5-11e8-8dfa-f6ab74eace5e.png)

Firebug renvoie une erreur 400

Les fiches importées sont au format ISO 19139 >> Migration vers ISO 19115-3 reste à jouer. A réaliser et retester

**Comment by fxprunayre** [comment]
Exemple de fiche 
http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.edit#/metadata/1008?redirectUrl=catalog.edit

Erreur
```
<apiError
>
<code
>
runtime_exception
</code
>
<description
>
A sequence of more than one item is not allowed as the value of variable $thesaurusConfig (<thesaurus/>, <thesaurus/>) 
</description
>
<message
>
XPathException
</message
>
</apiError>
```

C'est le bazar dans les thésaurus : faudrait faire le ménage sans doute - thème INSPIRE, priority dataset, theme geoportail en double

![image](https://user-images.githubusercontent.com/1701393/47285573-b37acb00-d5eb-11e8-87ae-ad830c083152.png)

**Comment by davinciagf** [comment]
La suppression des doublons permet d'afficher l'éditeur.

**Comment by davinciagf** [comment]
Vérifier les  thesaurus locaux et externes au niveau de la prod.

**Comment by davinciagf** [comment]
Je vais déjà supprimer supprimer les doublons.
Puis comparer les fichiers en prod /tests pour les codelist

**Comment by gdetry** [comment]
Je vais checker les thésaurus locaux et externes en prod afin de clarifier ce point

**Comment by fxprunayre** [comment]
L'objectif de la migration c'est d'avoir les même thésaurus avant et après pour le moment. Après on peut décider d'ajouter/mettre à jour des thésaurus.
