### ISSUE TITLE
Tri

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#440]
Suppression (par config admin):
* pop
* note
* échelles

Ajout:
* date de la ressource (décroissant)

Si titre par défaut, le tri est desc. A corriger.

**Comment by fxprunayre** [comment]
> Si titre par défaut, le tri est desc. A corriger.

https://github.com/geonetwork/core-geonetwork/pull/3558

Fait. A déployer et tester.

**Comment by davinciagf** [comment]
ok
