### ISSUE TITLE
Ressource associée / Catalogue d'attributs, légendes / Ajout description

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#443]
* Ajouter la description
* Ajout application profile dans le linkage

**Comment by fxprunayre** [comment]
> * Ajouter la description

Fait.

**Comment by fxprunayre** [comment]
> * Ajout application profile dans le linkage

cf. #445

**Comment by fxprunayre** [comment]
A déployer et tester.

**Comment by davinciagf** [comment]
Ok

**Comment by stephyritz** [comment]
Est-ce déployé en 3.6.1 Env. Test à ce jour ? Je ne comprends pas le but de cette fonctionnalité.
