### ISSUE TITLE
[Rapport de qualité - INSPIRE] - Remplissage Date/Explication

### ISSUE THREAD

**Issue by gdetry** [SPW-DIG/metawal-core-geonetwork#447]
Pour les fiches de MD concernées par un thème INSPIRE, on doit renseigner la spécification concernée et la conformité de la ressource dans un rapport de qualité (Dans DataQuality). On doit associer au référencement les champs [Date] + évènement (publication) et [Explication]. Actuellement cette saisie se fait manuellement.

Est-il possible que, quand on ajoute la Directive INSPIRE ou une spécification thèmatque, les champs [Date], évènement et [Explication] soient automatiquement remplis?

Ex. Directive INSPIRE 
[Date] =  08/12/2008 avec évènement = "Publication"
Explication = texte libre "Voir la spécification référencée"

- L’événement de date est toujours date de publication. 
- La date varie en fonction de si on choisit la directive, une spécification de l’annexe 1 ou une spécification de l’annexe 2 et 3
- L’explication est toujours “Voir la spécification référencée”

**Comment by stephyritz** [comment]
Fonction intéressante facilitant la saisie. Peut-être à déployer dans le cadre du projet d'adaptation aux TG2 car il y aura des enjeux spécifiques liés au bloc gmd:DQ_ConformanceResult.

**Comment by stephyritz** [comment]
Est-ce que cela a été implémenté dans 3.8 ? Je ne constate pas de changements.

**Comment by fxprunayre** [comment]
Je propose de le déplacer en 3.8.1 ?

**Comment by stephyritz** [comment]
D'accord

**Comment by stephyritz** [comment]
Je ne crois pas que finalement cela soit intégré dans la version 3.8.2 ? Ce n'était pas urgent donc si ce n'est pas le cas, on déplace au milestone 4.0.

**Comment by fxprunayre** [comment]
A faire pour les TG datasets

**Comment by fxprunayre** [comment]
Doublon avec https://github.com/SPW-DIG/metawal-core-geonetwork/issues/489
