### ISSUE TITLE
[Gestion des utilisateurs] Création d'un utilisateur via le LDAP

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#448]
La création d'un utilisateur via le LDAP ne semble pas être opérationnelle sur MW4. 

Il y a bien une case à cocher "Initialisation via LDAP" mais, après avoir saisie les différentes informations (Nom d'utilisateur, Courriel et Organisation), il ne se passe rien après clic sur le bouton "Enregistrer". Est-ce une mauvaise utilisation de ma part ou bien est-ce que cette fonctionnalité n'est pas opérationnelle ?
![Bug_MW4_Ldap_create_user](https://user-images.githubusercontent.com/34446202/60871313-c5140980-a232-11e9-887e-b7c89c771485.png)

**Comment by davinciagf** [comment]
A priori, les credentials n'ont pas été mis à jour en prod et test.
@davinciagf à modifier et vérifier en test

**Comment by davinciagf** [comment]
A retester suite au nouveau déploiement

**Comment by stephyritz** [comment]
Dans l'environnement de test : 
J'ai essayé de supprimer un utilisateur et d'en créer un nouveau en cochant "initialisation via le LDAP".
Exemple avec nom d'utilisateur = 134243  ; courriel = amelie.ledent@spw.wallonie.be.
1. L'affichage des utilisateurs est très lent (souvent obligé de quitter le menu et de revenir pour voir apparaître les valeurs).
2. Affichage également très lent des détails sur l'utilisateur (volet de droite) après avoir cliqué sur son nom dans le volet de gauche.
3. Quand j'ai saisi le nom d'utilisateur et le courriel mentionné ci-dessus et que je clique sur le bouton "enregistrer", il n'y a aucune réaction.

Je veux bien retester ces fonctionnalités une fois GN 3.8 en prod. Est-ce que cela fonctionnait en local ?

**Comment by davinciagf** [comment]
La personne de contact a changer - Contact à prendre avec Amaury Gravy (son numéro de téléphone n'est plus attribué)

**Comment by stephyritz** [comment]
Arnaud, as-tu fait l'essai en test ?
Parce que de mon côté, cela ne fonctionne pas.
Test avec David Dabin (39295 ; david.dabin@spw.wallonie.be ; SPW - DIG). ASsociation au groupe DIG-distrib sauf pour être admin.
Le bouton "enregistrer" reste grisé.

**Comment by stephyritz** [comment]
Bouton enregistré n'est plus grisé mais un problème est rencontré par la suite.
To reproduce :
1. Création d'un user en cochant ldap à partir du numéro ULIS et du mail
2. Enregistrement
--> L'utilisateur n'est pas visible dans la liste des utilisateurs depuis la console d'admin
--> Visiblement enregistré en DB mais sans aucunes autres informations

![image](https://user-images.githubusercontent.com/34446202/78975410-542cb580-7b14-11ea-8dc5-e00901ddad6f.png)

Quelle est la suite de la procédure pour l'application ? Est-ce que l'utilisateur reçoit un mail d'activation ? Est-ce que les informations du nom/prénom sont normalement récupérées ? Comment savoir si le lien avec le LDAP a bien été fait ?

**Comment by davinciagf** [comment]
Lorsque tu crées un utilisateur via la fonctionnalité LDAP, il n'y a pas directement de synchronisation avec le LDAP. On ne récupère donc pas les infos de l'utilisateur après la création de l'utilisateur.

EX: Création d'un utilisateur LDAP via id SPW (ex: al3867)

![Screen Shot 2020-04-14 at 08 56 31](https://user-images.githubusercontent.com/576292/79196298-20ad9c00-7e30-11ea-9fba-ef0799697e4a.png)

C'est l'utilisateur qui dès sa première connexion à MW va permettre la récupération des infos. Lorsque ce dernier se connecte, MW interroge le LDAP avec les credentials soumis par l'utilisateur (son id SPW et son pwd). S'il est reconnu, il y a synchronisation et récupération des infos du LDAP.

Première connexion via id SPW:

![Screen Shot 2020-04-14 at 08 57 33](https://user-images.githubusercontent.com/576292/79196282-12f81680-7e30-11ea-9e8a-946bed1bb1ea.png)

Aperçu en tant qu'admin de l'utilisateur al3867 sur MW:

![Screen Shot 2020-04-14 at 08 52 42](https://user-images.githubusercontent.com/576292/79196651-bea16680-7e30-11ea-8ae9-d8ffeaa55e7a.png)

Note: il faut faire attention d'enregistrer l'identifiant LDAP via des minuscules (ici: al3867 et non AL3867). Cela n'engendre pas d'erreur, mais tu te retrouves avec deux utilisateurs ayant le même id : AL3867 sans récupération des infos LDAP et un al3867 avec récupération des infos LDAP.

**Comment by stephyritz** [comment]
Ok. Très bien, merci pour les infos. Test OK de mon côté aussi.
Reste encore la tâche annexe à associer : remplacement de tous les utilisateurs SPW actuels par les "utilisateurs synchronisés avec le LDAP". Nous pouvons en profiter pour mettre à jours les utilisateurs et groupes. Ma proposition pour cela : 

- [ ] Créer un utilisateur admin_MW et lui attribuer la propriété de toutes les fiches (on évite que des personnes physiques soient "propriétaire" d'une fiche et cela permet de supprimer des utilisateurs actuellement "propriétaire" de fiches)

- [x] Supprimer tous les users que je vais lister dans un fichier txt

- [ ] Créer les nouveaux users en activant le LDAP et communiquer auprès des utilisateurs pour qu'ils s'authentifient une première fois

- [x] Remplacer les groupes actuels par les nouveaux groupes (je vais créer un fichier excel de matching)

- [ ] Attribuer les fiches aux nouveaux groupes

- [ ] Attribuer les nouveaux users aux nouveaux groupe

Qu'en dites vous ? Si vous pensez à un moyen plus simple pour "nettoyer", dites le moi.

**Comment by stephyritz** [comment]
Comme convenu, je partage avec vous deux fichiers pour mieux spécifier ce que je souhaiterais faire sur les users et groupe. 

Je pars du constat qu'il y a trop d'utilisateurs existants sur l'application alors qu'une petite dizaine seulement se sont connectés en un an.. Donc, nous allons procéder avec le raisonnement inverse, on ne conserve que les "actuels actifs". Il y a des comptes techniques et des users interne SPW. Pour les premiers, on conserve mais pour les seconds, on va devoir supprimer et recréer pour assurer une synchronisation avec le LDAP.

Le premier fichier liste les users à conserver : [users_list_to_keep.xlsx](https://github.com/SPW-DIG/metawal-core-geonetwork/files/4514928/users_list_to_keep.xlsx)

Concernant les groupes, c'est un peu plus embêtant puisque, sur Metawal, ils remplissent deux fonctions : Regroupement de users pour gérer des droits différenciés sur les fiches ET pour une gestion technique des fiches.

Si nous partons de l'hypothèse que les groupes ne sont utilisés uniquement pour la première fonction, alors je serais d'avis de supprimer la plupart de ces groupes. Voici le fichier qui décrit les opérations auxquelles j'ai pensé : [group_mapping.xlsx](https://github.com/SPW-DIG/metawal-core-geonetwork/files/4514959/group_mapping.xlsx)

Vu que je n'ai pas d'approche historique sur le sujet, j'aimerais quand même bien avoir votre avis sur ce "nettoyage" afin que je ne "casse" pas trop ce qui a été imaginé avant ma venue.

**Comment by stephyritz** [comment]
Concernant le transfère de la propriété de l'ensemble de fiches à l'utilisateur "Admin_Metawal" que j'ai créé, il semblerait que ça ne se passe pas comme prévu via l'interface.
To reproduce : 
1. Sélection de toutes les fiches depuis l'onglet "Contribuer"
2. Changer l'auteur --> choix de l’administrateur mentionné ci-dessus
3. Seules 88 fiches ont été traitées
![modif_proprietaire](https://user-images.githubusercontent.com/34446202/79964158-96e27c00-848a-11ea-8aef-b9437acc651e.png)

Donc peut-être faudrait-il quand même passer par un autre moyen que par l'interface pour ce genre de manip ?

**Comment by fxprunayre** [comment]
Il y a une erreur

![image](https://user-images.githubusercontent.com/1701393/80106634-67ab3800-857a-11ea-861c-c62b58a737b0.png)


```
java.lang.NullPointerException
	at org.fao.geonet.events.history.RecordGroupOwnerChangeEvent.getPreviousState(RecordGroupOwnerChangeEvent.java:57)
	at org.fao.geonet.listener.history.GenericMetadataEventListener.storeContentHistoryEvent(GenericMetadataEventListener.java:88)
	at org.fao.geonet.listener.history.GenericMetadataEventListener.handleEvent(GenericMetadataEventListener.java:60)
	at org.fao.geonet.listener.history.RecordGroupOwnerChangeListener.onApplicationEvent(RecordGroupOwnerChangeListener.java:49)
	at org.fao.geonet.listener.history.RecordGroupOwnerChangeListener.onApplicationEvent(RecordGroupOwnerChangeListener.java:30)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:382)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:336)
	at org.fao.geonet.events.history.RecordGroupOwnerChangeEvent.publish(RecordGroupOwnerChangeEvent.java:62)
	at org.fao.geonet.api.records.MetadataSharingApi.updateOwnership(MetadataSharingApi.java:913)
	at org.fao.geonet.api.records.MetadataSharingApi.setGroupAndOwner(MetadataSharingApi.java:764)
```

**Comment by fxprunayre** [comment]
Transfer owner issue solved in https://github.com/geonetwork/core-geonetwork/pull/4635

**Comment by fxprunayre** [comment]
Script à relire et tester https://github.com/SPW-DIG/metawal-core-geonetwork/commit/91970b3f1065fce0cf9eb55199aaac1e0a09ae51 @davinciagf 

Après script
![image](https://user-images.githubusercontent.com/1701393/80230721-9c8abe00-8652-11ea-97f0-a484655d3d9e.png)

![image](https://user-images.githubusercontent.com/1701393/80230736-9eed1800-8652-11ea-8128-0859b9b436d9.png)

**Comment by davinciagf** [comment]
Effectué sur test avec deux modifs (typo).
Voir https://github.com/SPW-DIG/metawal-core-geonetwork/commit/732934638c24c3c804da871b81554304848b5a7c

**Comment by stephyritz** [comment]
Ok pour la présence des users et groupes. Par contre toutes les fiches ne sont pas attribuée à l'utilisateur Admin_Metawal. Et ça bouge quand je refresh. Idem pour les fiches liées au groupe SPW.. Donc visiblement, la requête n'est pas terminée. Arnaud quelles sont les résultats du sql en base ? As-tu eu un message te confirmant le succès des requêtes ? N'hésite pas à les garder/partager pour qu'on puisse s'assurer que ça sera aussi OK en valid/prod.

**Comment by stephyritz** [comment]
C'est bon maintenant. Seul petit détail --> Il y a 5 fiches qui sont dans le groupe "tous" (voir à travers la facette Groupe). Est-ce que ce sont des fiches qui étaient liées à des groupes maintenant supprimés ? Dans ce cas c'est sensé être lié au groupe que nous avons appelé "SPW", non ? Je comprends pas trop la fonction de ce groupe "all". Enfin, est-il possible, à travers l'interface d'admin d'attribuer la fiche à un autre groupe (je ne parle pas des privilèges pour donner accès à la fiche à d'autre user) ?

**Comment by stephyritz** [comment]
Ok en test. Vous pourrez répondre à mes questions lors de notre prochain meeting.

**Comment by stephyritz** [comment]
Visiblement pas opérationnel à ce jour en valid. A cause d'une sécurité côté ldap en environnement de valid ? Est-ce que la résolution de ce problème est prévue avant la mise en pro du 28/05 ?

**Comment by davinciagf** [comment]
Oui - il fallait libérer les accès au LDAP depuis l'env. Didier a fait la demande. Je me renseigne pour savoir si c'est fait ou pas.

**Comment by davinciagf** [comment]
Redémarrage de la machine de valid - création d'un compte via mon id dans le LDAP - OK

**Comment by stephyritz** [comment]
Firewall encore bloqué à l'heure actuelle

**Comment by fxprunayre** [comment]
Cf. https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.0.x/core/src/main/java/org/fao/geonet/kernel/security/ldap/LDAPSynchronizerJob.java

Probablement à désactiver ici
https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.0.x/web/src/main/webapp/WEB-INF/config-security/config-security-ldap.xml
