### ISSUE TITLE
[Rapport] Ajout d'exports de rapports personnalisés

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#449]
Dans la section "Rapport" de Metawal, je souhaiterais  qu'il y ait la possibilité de générer un .csv à propos des fiches crées, avec les mêmes options de filtres que les autres rapports. Ceci permettrait de suivre l'avancement du travail sur la création de fiches.

Il s'agirait donc d'un fichier texte avec comme attributs : Metadat ID, Metadat Title, Metadat Create date, Owner Username, Owner Surname, Owner Name, Owner Email, Group Owner, _Date de dernière Mise à jour de la fiche, le Statut (Publié ou non) et le Type de données concernées (service, série, données, application)_.

Par ailleurs, quelques suggestions pour améliorer les rapports actuellement disponibles :
- Fiches mises à jour --> De quoi s'agit-il en fait ? La liste des fiches triées par MaJ décroissante ? Cela se rapproche en réalisé fort d'un rapport sur les fiches créées, comme mentionné ci-dessus et non sur les mises à jour. Est-ce possible d'avoir un réel historique des mises à jour ? Il faudrait éventuellement rajouter les champs "Utilisateur ayant réalisé la mise à jour" et "la date de mise à jour" au rapport actuel. 
- Accès utilisateurs --> J'ai l'impression que le rapport n'est disponible que sur la période pst-migration MW4. Est-il possible de revenir plus loin dans le temps ? Car besoin pour évaluer l'utilisation de l'outil depuis 2016.

**Comment by fxprunayre** [comment]
> Accès utilisateurs --> J'ai l'impression que le rapport n'est disponible que sur la période pst-migration MW4. Est-il possible de revenir plus loin dans le temps ? Car besoin pour évaluer l'utilisation de l'outil depuis 2016.

Non pas possible avant mise en prod. Le seul moyen serait de repartir des logs du serveur web ?

>  Il faudrait éventuellement rajouter les champs "Utilisateur ayant réalisé la mise à jour" et "la date de mise à jour" au rapport actuel.

Je vais regarder mais on pourra se baser plus probablement sur la gestion de l'historique pour ça. Du coup uniquement à partir de la mise en prod 3.8.0.

**Comment by stephyritz** [comment]
Je ne vois pas de changements concernant ce point depuis le déploiement de 3.8.1.

**Comment by fxprunayre** [comment]
http://metawal4.test.wallonie.be/geonetwork/srv/fre/admin.console#/dashboard/versioning tu peux faire des recherches sur l'historique. C'est sans doute à améliorer eg. tu ne peux pas demander les fiches créées.

**Comment by stephyritz** [comment]
D'accord. L'interface est sympa mais il y a effectivement encore des améliorations à faire (éventuellement proposer des filtre d'événements marquants concernant la fiche comme la publication et la création. De plus, j'ai l'impression qu'il y a un bug concernant la liste proposée d'auteurs et de propriétaires (que 5 noms dans metawal4 en test). Je laisse le ticket ouvert mais modifie le milestone. Pa d'urgence mais à planifier.

**Comment by vbombaerts** [comment]
@vbombaerts à tester

**Comment by vbombaerts** [comment]
Par rapport à la demande initiale : le[ rapport concernant la mise à jour des fiches](https://metawal.wallonie.be/geonetwork/srv/fre/admin.console#/reports/report-updated-metadata) 
- [x] contient déjà la date de création. 
- [x] Ce serait intéressant d'ajouter le statut de publication et le type de ressource concernée.

**Comment by davinciagf** [comment]
PR GN (https://github.com/geonetwork/core-geonetwork/pull/6413)

**Comment by davinciagf** [comment]
A merger et configurer pour ajouter le statut et le type de ressource

**Comment by davinciagf** [comment]
A tester 
![image](https://user-images.githubusercontent.com/576292/174751634-2902f0d3-c09d-48b8-9340-845dfa22f8d7.png)

**Comment by vbombaerts** [comment]
> * le statut de publication

Petite incompréhension sur les termes.
C'est le statut de publication qui nous intéresse (publié ou pas).

Type de ressource OK.

**Comment by davinciagf** [comment]
Corrigé
![image](https://user-images.githubusercontent.com/576292/174960424-d7900045-2a16-4b29-b88c-b3039beb954c.png)
