### ISSUE TITLE
Ajouter trois points quand le site raccourcit un texte

### ISSUE THREAD

**Issue by geologiewallonie** [SPW-DIG/metawal-core-geonetwork#45]
La balise title d'un titre est automatiquement raccourcie et limitée à un certain nombre de caractère. Il faudrait ajouter [...] ou ... pour annoncer que la description est plus complète.

**Comment by fxprunayre** [comment]
![image](https://f.cloud.github.com/assets/1701393/1790700/0a91a1f0-697e-11e3-95bf-78e999374392.png)

Préciser où. Je le ferme en attendant.
