### ISSUE TITLE
[Interface d'édition] Dysfonctionnement du bouton Annuler

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#450]
Lors de l'ouverture en mode édition d'une fiche, le bouton "Annuler" n'a aucun effet.

Par exemple, lorsque l'utilisateur fait des modifications et ne souhaite finalement pas les enregistrer, le bouton "Annuler" devrait pouvoir permettre de quitter le mode édition sans pour autant sauvegarder les changements.

Actuellement, ce n'est pas fonctionnel et même dans le cas où aucun changement n'est réalisé, la date de mise à jour de la fiche est modifiée à partir du moment où elle a été ouverte en édition.

Est-ce l'enregistrement automatique qui se fait trop rapidement et qui, du même coup, court-circuite la fonction du bouton "Annuler" ?

**Comment by fxprunayre** [comment]
Corrigé dans https://github.com/geonetwork/core-geonetwork/pull/3905

**Comment by stephyritz** [comment]
Comme il s'agit d'un point assez critique, est-il possible de plutôt l'intégrer dans le milestone 3.6.1 ? Ou bien est-ce dans le 3.8 pour des raisons techniques impossibles à réaliser dans les délais du 3.6.1 ?

**Comment by davinciagf** [comment]
J'essaye de te le mettre pour la mise à jour de demain.

**Comment by stephyritz** [comment]
OK en TEST
