### ISSUE TITLE
[Interface d'édition] Affichage du nom du Service WMS associé à une fiche

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#452]
En mode édition d'une fiche, dans la rubrique Ressources associées/Ressources en ligne : 
Le service WMS apparaît avec comme intitulé la description à la place du nom. (ESRI-REST OK).
 
![Bug_MW4_wms_name](https://user-images.githubusercontent.com/34446202/60888048-33b68e80-a256-11e9-8541-f7071d88c9d3.png)

**Comment by fxprunayre** [comment]
Ce qui est super c'est de mettre les URLs des pages concernées dans les tickets pour accèder rapidement au pb. Merci

**Comment by fxprunayre** [comment]
C'est corrigé ici http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.edit#/metadata/1516?redirectUrl=catalog.search%23%2Fmetadata%2Fffc45d44-1cc2-4924-bb8c-214096eb9058 
donc à déployer, correct ?

**Comment by stephyritz** [comment]
C'est noté. 
Effectivement c'est bon en environnement de test. Donc correction à intégrer dans le war qui sera déployer prochainement alors.
