### ISSUE TITLE
[Interface de présentation de la fiche] Nom d'un contributeur

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#453]
Une personne est encodée en tant qu'individu seul et avec le rôle de contributeur dans Contact_Ressource. Son nom n'apparaît pas dans la vue complète de Metawal présentant la fiche. 

Voir http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/a5577b78-a388-48e7-86f9-c3138d562270

**Comment by stephyritz** [comment]
@fxprunayre Je pense que ce constat avait soulevé une question de plus grande envergure que tu as traitée. Je te laisse indiquer ce que tu as fixé comme problème adjacent.

**Comment by fxprunayre** [comment]
![image](https://user-images.githubusercontent.com/1701393/60888652-9eb49500-a257-11e9-835a-264562484850.png)

Corrigé ici 
http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/a5577b78-a388-48e7-86f9-c3138d562270

et 
https://github.com/metadata101/iso19115-3.2018/commit/c0288807f44d84a8ea4c23e49bcea9c2ee7d386a
https://github.com/metadata101/iso19115-3/commit/1f3cc2e26181095fe0666bcafd77c7abdea97fc1


A déployer.

**Comment by stephyritz** [comment]
Ok en test

**Comment by stephyritz** [comment]
C'est bon pour la vue par défaut après le release 3.6. déployé à ce jour en environnement de prod mais le nom du "Contributeur" ne s'affiche pas dans la vue complète --> http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/a5577b78-a388-48e7-86f9-c3138d562270 
J'imagine qu'il ne s'agit que d'un détail mais je déplace donc ce ticket vers le milestone 3.8 plutôt que de le fermer.

**Comment by fxprunayre** [comment]
> J'imagine qu'il ne s'agit que d'un détail mais je déplace donc ce ticket vers le milestone 3.8 plutôt que de le fermer.

Fixed in https://github.com/metadata101/iso19115-3.2018/commit/9a8448610e16d3a47310a4315d8095fbfa9db34e

Ce n'est pas vraiment qu'un détail dans le sens où il y a pas mal de combinaison possible en 115-3 pour décrire des couples org/individu - j'ai essayé d'améliorer un peu la situation dans le commit ci-dessus. Le nom sera afficher.

**Comment by stephyritz** [comment]
Ok sorry, je pensais qu'il s'agissait maintenant "simplement" d'un paramétrage de la vue avancée car le problème avait été réglé dans la vue par défaut. Merci d'avoir pris en compte cette remarque pour le commit. ; )
