### ISSUE TITLE
[Ressources associées] Liens vers des pdf qui ne sont plus actifs

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#454]
Il semblerait que depuis le passage à MW4, certains documents pdf mis en ressources associée soient devenus des "liens morts". Par exemple : http://metawal.wallonie.be/geonetwork/srv/api/records/73414a3a-fe93-49dd-9ecd-7137e54402cf/attachments/Rapport_final_LiDAXES20160830.pdf  

J'ai déjà eu d'autres cas, sur des modèles de données par exemple, pour lesquels, afin de résoudre rapidement le problème, j'ai supprimé la ressource puis rechargé. Par contre ici, je n'arrive plus à charger à nouveau le pdf à partir de cette fiche : http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/73414a3a-fe93-49dd-9ecd-7137e54402cf

**To Reproduce**
1. Go to 'http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/73414a3a-fe93-49dd-9ecd-7137e54402cf'
2. Click on 'Ressources associées/Ajouter', type de lien = documentation
3.  Pour un pdf, la barre de chargement se lance mais le document n'apparaît jamais dans le "dépôt de fichiers". Cela fonctionne avec un fichier au format png par exemple.

Peut-être que nous pouvons également par ailleurs, une fois ce souci résolu, utiliser le vérificateur de lien (prévu pour 3.8. ?) pour caractériser les éventuels effets de bords liés à la migration sur cet aspect.

**Comment by stephyritz** [comment]
Arnaud, je t'avais envoyé un mail à ce propos, j'ai juste rapporté également le problème ici pour faciliter la gestion et le suivi.

**Comment by stephyritz** [comment]
Problème de "lien mort" également rencontré avec certains aperçus. Par exemple : http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/c71a5995-f3c4-46e9-97f3-69c8fd61d66e

**Comment by stephyritz** [comment]
Ok en TEST, j'ai réussi à charger un pdf  de 6 Mo en tant que ressource associée/documentation : http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/73414a3a-fe93-49dd-9ecd-7137e54402cf

A voir si cela fonctionne en prod.

Par contre Quid du validateur de lien mort dont nous avons parlé. Est-ce prévu pour la version 3.8 de GN ? Dans ce cas, nous créerons une autre issue avec 3.8 pour milestone.

**Comment by stephyritz** [comment]
Le lien vers le rapport ne fonctionne plus en test(http://metawal.wallonie.be/geonetwork/srv/api/records/73414a3a-fe93-49dd-9ecd-7137e54402cf/attachments/Rapport_final_LiDAXES20160830.pdf) alors que cela fonctionnait il y a 18 jours. 
En environnement de valid, impossible d'uploader le document pdf (ressources associées/documentation par exemple).

**Comment by stephyritz** [comment]
A tester en prod parce que l'ajout d'un rapport de qualité (pdf de 6.5Mo), par exemple sur cette fiche http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/e281971d-776b-4793-99fd-ffc8e02d62d4,ne fonctionne pas correctement. L'upload se passe bien, c'est seulement en fin de processus, quand je veux cliquer sur la ressource associée que j'obtiens cette erreur :
![PB_ressources_associees](https://user-images.githubusercontent.com/34446202/65664051-bcb0bb00-e038-11e9-83de-88a612f57cb6.png)

Je ne pense pas que cela soit lié au passage à GN 3.8 mais en tout cas le problème persiste. Pas bloquant pour la mise en valid mais tout de même embêtant car actuellement le problème mentionné le 9 juillet est toujours d'actualité en prod : 
To Reproduce

"Steps to reproduce the behavior:

    Go to 'http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/73414a3a-fe93-49dd-9ecd-7137e54402cf'
    Click on 'Ressources associées/Ajouter', type de lien = documentation
    Pour un pdf, la barre de chargement se lance mais le document n'apparaît jamais dans le "dépôt de fichiers". Cela fonctionne avec un fichier au format png par exemple."

**Comment by fxprunayre** [comment]
Quand on déploie GeoNetwork sur un serveur il faut toujours définir l'hôte dans l'admin. Corrigé sur metawal4. 

![image](https://user-images.githubusercontent.com/1701393/65665865-c63c2200-e03c-11e9-9bb6-d83ebf62b89a.png)

Si tu refais l'upload ca devrait être bon.

**Comment by stephyritz** [comment]
Ok super, fonctionne maintenant en test. A voir après déploiement de GN 3.8 si c'est bon aussi en prod. Merci

**Comment by stephyritz** [comment]
Je reviens avec ce problème présent en prod bien que l'hôte soit correctement défini comme mentionné ci-dessus (metawal/wallonie.be dans le cas de la prod).

To Reproduce

Steps to reproduce the behavior:

    Go to 'http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/f3a03dbd-ae44-48ec-a544-dafdd8409474'

    Click on 'Ressources associées/Ajouter', type de lien = documentation

    Pour un pdf, la barre de chargement se lance mais le document n'apparaît jamais dans le "dépôt de fichiers".  Est-ce qu'il y a qualque chose que je ne fais pas correctement ?

Prtsc --> ![pb_uplaod_ressource_associée_pdf](https://user-images.githubusercontent.com/34446202/66132580-91f4d280-e5f5-11e9-9d0b-0d9019be32fc.png)

Problème qui devient assez critique car, dans le cadre de la lutte contre la peste porcine, je dois ajouter de manière assez urgente le pdf de l'arrêté ministériel en ressource associé.

**Comment by fxprunayre** [comment]
C'est ok en test et valide et pas en prod, correct ?

**Comment by stephyritz** [comment]
Oui tout à fait!

**Comment by fxprunayre** [comment]
Donc on met en prod la valid et on est tout bon ou il faut débugger la prod ?

**Comment by stephyritz** [comment]
On peut attendre de voir le résultat après mise en prod de GN 3.8. Je ne suis pas sûr que ce problème soit lié à la version de GN et donc à voir si ce nouveau déploiement le solutionne. On peut éventuellement attendre pour voir si on a la chance que cela soit debuggé lors de la nouvelle MaJ. Mais, à mon avis, le problème vient d'autre part.

**Comment by stephyritz** [comment]
Problème toujours présent malgré le déploiement de GN 3.8 en prod

**Comment by fxprunayre** [comment]
Je viens de tester sur prod sur la fiche en question et j'ai pu uploader et supprimer une copie de l'arrêté renommé test.pdf

![image](https://user-images.githubusercontent.com/1701393/67757986-1ee84b80-fa3d-11e9-8495-126cb7057631.png)

Tu peux retester ? et si le pb porte sur un fichier spécifique nous envoyer le fichier.

**Comment by stephyritz** [comment]
Toujours le problème mais cette fois on dirait que c'est lié avec ce document en particulier parce qu'avec un autre pdf, cela fonctionne. Est-ce tout de même une question de taille ? 
Le fichier en question : 
[AM_CT_20191001.pdf](https://github.com/SPW-DIG/metawal-core-geonetwork/files/3783056/AM_CT_20191001.pdf)

**Comment by fxprunayre** [comment]
> Est-ce tout de même une question de taille ?

La limite de taille est 100Mo. Donc ca ne doit pas être ça le pb.

**Comment by fxprunayre** [comment]
Mais en fait si on a un ouaille en frontal qui nous répond "413 Request Entity Too Large" 

![image](https://user-images.githubusercontent.com/1701393/67771242-3d0f7500-fa58-11e9-8728-704a78470a4f.png)

Donc c'est nginx qui doit avoir une limite ? A voir avec le DTIC du coup.

**Comment by stephyritz** [comment]
Ah bien vu!! Je rapporte ça au DTIC pour définir la même limite de taille que GN si possible et on pourra enfin fermer ce ticket! ; )

**Comment by stephyritz** [comment]
Le DTIC vient de changer le paramètre permettant d'uploader sur la machine des fichiers allant jusque 100Mo! Fonctionne en prod à ce jour, problème résolu!!
