### ISSUE TITLE
Editeur / Mise en place d'un annuaire

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#458]
Après la #457, mettre en place un annuaire de contact dans lequel les contacts seront du type un organisme > un individu. Connecter l'annuaire avec l'éditeur.

**Comment by fxprunayre** [comment]
Pour remplir l'annuaire, on a plusieurs options:
a) à la main (un peu longuet)
b) par analyse de ce qui est dans le catalogue cf. API registries/actions/entries/collect

http://metawal4.test.wallonie.be/geonetwork/doc/api

![image](https://user-images.githubusercontent.com/1701393/67769685-36333300-fa55-11e9-9161-e9e30ceba3a1.png)

c) par un job (eg. FME) qui charge d'une source autre (eg. LDAP)


A voir ce qui serait préférable selon les besoins ? @stephyritz

**Comment by stephyritz** [comment]
Actuellement, je trouve la solution b) la plus opérationnelle. On pourrait éventuellement combiner avec la solution c) en ce qui concerne les "individus SPW" présents dans le LDAP. Il y a aussi une difficulté assez importante qui est le changement de noms de la plupart des directions au sein du SPW... Donc ceci implique l'ajout d'un mapping dans la démarche. Etape obligatoirement accompagnée d'une action manuelle fastidieuse. Est-ce qu'avec l'API on peut extraire les informations concernant les contacts (organismes et individus) dans un format pivot qui pourrait servir de base au mapping ? Après modification, on pourrait éventuellement importer le nouveau document dans l'annuaire GN à partir de ce même format pivot.

**Comment by fxprunayre** [comment]
- [ ] Sortir la liste des valeurs possibles depuis DB
- [ ] Mapping avec les nouveaux noms 
- [ ] SQL pour update

- [ ] Construction d'un annuaire et utilisation (4.0.0?)

**Comment by vbombaerts** [comment]
@marceaulouis 
A relancer. Toujours d'actualité.

**Comment by fxprunayre** [comment]
## Exemple de création d'annuaire

Se connecter. 
Aller dans l'éditeur, utiliser la facette pour filtrer les métadonnées selon le type de standard (ce dernier détermine le xpath d'extraction définit dans le process décrit ci-dessous).
![image](https://user-images.githubusercontent.com/576292/167828906-59dd7259-9633-4dca-b739-19e4297a1681.png)

Sélectionner les données filtrées selon le standard.
![image](https://user-images.githubusercontent.com/576292/167828991-36808eb6-d36d-435a-8e65-5fb3c40a5896.png)

A partir de la page de l'API http://localhost:8080/geonetwork/doc/api/ utiliser l'opération `/registries/actions/entries/collect`

### Organisations & contacts

* xpath: `.//cit:CI_Responsibility`
* identifierXpath: `.//cit:electronicMailAddress/*/text()`


![image](https://user-images.githubusercontent.com/1701393/167571438-2258a766-f654-47c5-8354-bc6f98f3f35a.png)

Si l'identifiant est l'email, alors l'UUID est une clé basée sur l'email (si plusieurs fiches ont des contacts avec le même email, le dernier gagne - on peut donc perdre des infos eg. si un a un adresse complète et pas le suivant).

Quand il n'y a pas d'email, on aura de nouvelles entrées à chaque analyse (random UUID dans ce cas) eg.

![image](https://user-images.githubusercontent.com/1701393/167573551-87ff318c-543c-43aa-ba67-24b94f4363cc.png)


~130 contacts créés
![image](https://user-images.githubusercontent.com/1701393/167573706-d2a5dbe4-073c-46fa-90d1-59fb10e7149f.png)

On obtient une entrée par email différent (comme en 115-3 on a la notion de Party qui peut être une organisation ou un individu avec des relations, ce n'est pas forcément évident)

![image](https://user-images.githubusercontent.com/1701393/167573744-d75dded4-3c81-4f10-8920-7415b963d41f.png)

Ensuite, on peut l'utiliser dans l'éditeur:

![image](https://user-images.githubusercontent.com/1701393/167575131-df38a55a-1f7b-49a1-b02d-8a22a6b85cb5.png)


Lors de la collecte, on peut avoir des exceptions du type:
```
        "message": "XPath error while evaluating \".//cit:CI_Responsibility\": XPath expression uses unbound namespace prefix cit: XPath expression uses unbound namespace prefix cit",
```
quand les fiches ne sont pas dans le schéma du XPath. Ici, ISO19139.




### Rapports qualité


* xpath: `.//*[mdq:result]`
* identifierXpath: `.//cit:title/*/text()`

Collecte, 5min.


![image](https://user-images.githubusercontent.com/1701393/167588458-3cc01b76-fd8b-45bc-b122-a026f85aa62c.png)



![image](https://user-images.githubusercontent.com/1701393/167602568-4878ab07-8726-4d5f-aa3d-5117316a6907.png)


## Etendue


Parameters:
* xpath: `.//gex:EX_Extent`
* identifier: `concat(.//gex:westBoundLongitude/*/text(), ', ', .//gex:eastBoundLongitude/*/text(), ', ', .//gex:southBoundLatitude/*/text(), ', ',.//gex:northBoundLatitude/*/text())`



Collecte, 3min.

![image](https://user-images.githubusercontent.com/1701393/167595018-f967946a-4bda-4c75-9b09-90ee072c0090.png)

Y'a plusieurs variations de la région wallonne

![image](https://user-images.githubusercontent.com/1701393/167602320-773d8e9d-7f13-4519-8e26-af79805c025a.png)

Pour homogéniser, il est possible de créer les extents avec comme identifiant la description.


Parameters:
* xpath: `.//gex:EX_Extent`
* identifierXpath: `gex:description/*/text()`


![image](https://user-images.githubusercontent.com/1701393/167608174-e85ebb14-c785-4a45-8bb6-676b48d4464c.png)


### Constraints

* xpath: `.//mri:resourceConstraints/*`

Pour les contraintes ce serait envisageable 

![image](https://user-images.githubusercontent.com/1701393/167614010-7acfe3fa-158b-4972-9122-f23ffb3ca5fb.png)

mais il faudrait revoir la création des titres 

![image](https://user-images.githubusercontent.com/1701393/167614238-84d2eea8-4d9b-4dcf-beaa-8886c972a33c.png)



## Remarques

* Le processus de collect/synchronize peuvent être un peu long (comme le batch process) - pb potentiel de timeout. Eg. extraction des contacts sur 1000 fiches 8min
* Syncrhonize / from an gex:Extent directory containing only description and bounding polygon, the update can remove temporal element

**Comment by davinciagf** [comment]
Testé avec https://github.com/geonetwork/core-geonetwork/pull/6292

**Comment by marceaulouis** [comment]
Résultats des tests sur la création des contacts :

### opération /registries/actions/entries/collect

- Impossible de lancer le processus sur l'ensemble : erreur après >15min (comme prévu) 

- Ok sur une sélection plus petite ~ 600 fiches, 15min pile


### Gestion des contacts

- Je ne sais pas si c'est parce que le premier processus a planté, mais quasi toutes les info sont doublées

![image](https://user-images.githubusercontent.com/99397823/173006474-4c4296b3-2a57-46b4-9379-42153b4c8fbc.png)


- Impossible de supprimer les éléments pour re-tester

- L'info encodée via l'éditeur ne correspond pas au contact sélectionné ex :

![image](https://user-images.githubusercontent.com/99397823/173006856-97abd648-468b-483d-a8df-96fa9194f0c6.png)
Encodage :

![image](https://user-images.githubusercontent.com/99397823/173006901-632f597b-e732-4f1e-a687-52400e8d444e.png)

C'est l'ancienne nomenclature qui est encodée, les infos ont été modifiées #671

**Comment by fxprunayre** [comment]
> Impossible de lancer le processus sur l'ensemble : erreur après >15min (comme prévu)

Le processus continue je pense même si le proxy à fermer la porte.

> Je ne sais pas si c'est parce que le premier processus a planté, mais quasi toutes les info sont doublées
Un coquille dans la génération du titre cf. https://github.com/geonetwork/core-geonetwork/pull/6378


> Impossible de supprimer les éléments pour re-tester

En effet:
```
{"message":"Resource not found","code":"resource_not_found","description":"Resource could not be located."}
```

En regardant dans l'admin
![image](https://user-images.githubusercontent.com/1701393/173010875-650a0ee2-e8b5-43c9-adf0-9b169c762562.png)

Donc on a un index incomplet. J'ai lancé une réindexation ...

**Comment by fxprunayre** [comment]
Bon, test semble géné par un proxy qui dit "The proxy could not connect to the destination in time." @davinciagf une idée?

**Comment by vbombaerts** [comment]
Arnaud a relancé le serveur.

**Comment by marceaulouis** [comment]
A nouveau des problèmes d'indexation. J'ai fait 2-3 tests bénins (suppression de contacts, relance de l'API après modification d'adresses mail), c'est lié à ça ?

A discuter : comment serait envisagée la mise à jour de l'annuaire ? 

- relance manuelle à intervalles raisonnables de l'API sur l'ensemble des fiches ? Détection des nouvelles entrées ? 
- l'API met en évidence pas mal d'erreurs d'encodage. Comment facilement identifier les fiches qui posent problème afin de corriger la source (en lien avec la question des mises à jour si chaque fois sur l'ensemble du catalogue..)

**Comment by davinciagf** [comment]
Attention j'ai fait des modifs et j'ai relancé à plusieurs fois le serveur cet apm. Cela pourrait expliquer cela. 
Pour retrouver les fiches ==> via kibana et une recherche sur le champs de l'index et la valeur erronée.

**Comment by marceaulouis** [comment]
"Procédure" de mise à jour :

Régulièrement (Toutes les 20 nouvelles fiches encodées), relancer l'API sur la sélection

! Si modification de contacts, les deux versions seront encodées --> suppression de l'ancienne
