### ISSUE TITLE
Licences / Saisie sous forme de liste

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#459]
Mise en place d'une liste de valeur pour les licences:

- [x] Faire la liste des licences (Libellé, description + URL) - Stéphane

- [x] Créer un thésaurus - Stéphane ou Francois

- [ ] Configurer l'éditeur pour utiliser la liste de valeur avec saisie sous forme d'Anchor avec une URL vers la page de la licence - Francois

- [ ] Consultation afficher la licence avec un lien vers la page

Questions:

* Support multilingue à prévoir ?

**Comment by stephyritz** [comment]
Je te propose ici une liste en format excel des différentes possibilités concernant l'accès et l'utilisation : 
[cga_cgu_exemple.xlsx](https://github.com/SPW-DIG/metawal-core-geonetwork/files/3401886/cga_cgu_exemple.xlsx)
La valeur saisie serait la colonne "identifiant" à laquelle nous pourrions associer le liens vers le documents pdf et éventuellement une ancre vers le registre.
Il faudrait que nous soyons attentifs à la manière de déclarer cela selon les TG2. Je pense que les deux premières valeurs du tableau ne sont pas dans les mêmes balises que les suivantes.

**Comment by fxprunayre** [comment]
Donc on peut configurer de la manière suivante :

![image](https://user-images.githubusercontent.com/1701393/65535563-fd59e880-df01-11e9-9669-bafcf6e62759.png)

ou avec définition

![image](https://user-images.githubusercontent.com/1701393/65535568-02b73300-df02-11e9-88a9-4fd48cf1adf3.png)

Par contre on ne peut pas avoir un textarea avec autocompletion - on passe le champ en input simple. Une fois choisie la valeur du champ et l'URL sont renseignées. Il est possible de modifier les valeurs manuellement.

![image](https://user-images.githubusercontent.com/1701393/65535656-25494c00-df02-11e9-86db-bf31a671ba3c.png)

Et je vois qu'en consultation rien ne s'affiche :( Je corrige de ce pas

![image](https://user-images.githubusercontent.com/1701393/65536470-bff65a80-df03-11e9-8bfe-9248ff62d98f.png)


@stephyritz ca te convient ?

Du coup, pour les valeurs INSPIRE, on pointe vers Registry, pour les mots clés du thésaurus GN, l'URL ne pointe vers rien. Une idée serait de faire une page pour les mots clés qui correspondent à l'URL dans le thésaurus. La page pourrait afficher le mot clé, sa description et la liste des fiches associées ? Ca demande un peu de travail.

**Comment by stephyritz** [comment]
Merci. L'option sans définition me paraît mieux. Pour la "page explicative", je ne pense pas que cela vaut la peine. Pour les conditions d'accès et d'utilisation, je renverrais bien sur le document pdf dédié (par ex. http://geoportail.wallonie.be/files/documents/ConditionsSPW/DataSPW-CGA.pdf). Pour les valeurs INSPIRE, on ferait le lien vers le registry effectivement. Et pour les autres, soit pas de liens car énoncé assez clair (option que je privilégie dans un premier temps). Soit, si on doit être homogène et chaque fois déclaré une ancre, alors on peut imaginer une explication dans une page dédiée.

**Comment by stephyritz** [comment]
Ne semble pas fonctionner en 3.8.1. Action à faire de ma part pour lier un champ au thesaurus depuis l'interface ?

**Comment by davinciagf** [comment]
Le thesaurus n'est pas présent sur l'env de test. Vérifier la config afin qu'il soit pris dans le war comme les standards.

**Comment by fxprunayre** [comment]
> Le thesaurus n'est pas présent sur l'env de test.

Je l'ai ajouté. Ce devrait être à noter dans la procédure de mise à jour ?

> Vérifier la config afin qu'il soit pris dans le war comme les standards.

Mais même avec le thésaurus ça ne joue pas. J'ai l'impression que le plugin 115-3 n'est pas à jour.

Vérifier le déploiement dans
/home/sites/metawal4/active/geonetwork/WEB-INF/data/config/schema_plugins

Exemple de changement qui devrait être présent:
https://github.com/SPW-DIG/iso19115-3.2018/blob/f56bf6785844e1083c10a39acf3c42df0adc9301/src/main/plugin/iso19115-3.2018/layout/config-editor.xml#L57-L60

**Comment by davinciagf** [comment]
A retester suite au nouveau déploiement

**Comment by stephyritz** [comment]
Est-ce que cela fonctionne en local chez vous ? Sur metawal4.test a priori non. Exemple : http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/938c92ef-9fcc-495f-9f48-dcec19ec7cc8 
Normalement, la liste de valeur devrait être liée à Limite d'utilisation il me semble.

**Comment by davinciagf** [comment]
Il fonctionne en local et en test mais il se situe au niveau des autres contraintes.

![image](https://user-images.githubusercontent.com/576292/66194112-1e55d280-e694-11e9-9a92-06551629bfba.png)
