### ISSUE TITLE
Recherche / Critère validation

### ISSUE THREAD

**Issue by PascalDelvaux** [SPW-DIG/metawal-core-geonetwork#46]
La recherche conjointe "Critères avancés : Mots clefs" (valeur "6010 industrie et services") et "Critères temporels : Validation" (valeur "Valide") devrait donner au moins "Établissements d'accueil pour aînés".

http://metawal3.test.wallonie.be/geonetwork/srv/fre/search?uuid=6bb4a41f-8477-4a0c-95f9-7d2807ee0589

**Comment by fxprunayre** [comment]
A vérifier : le niveau de validation de toute les fiches n'a pas été initialisé dans metawal test. A tester suite à ça.

**Comment by vbombaerts** [comment]
A tester sur http://metawal.wallonie.be/geonetwork/srv/fre/search?uuid=6bb4a41f-8477-4a0c-95f9-7d2807ee0589

**Comment by PascalDelvaux** [comment]
Vincent,

Superbe et très fonctionnel.  Beau Boulot. ☺

Pascal Delvaux
Attaché

Service public de Wallonie
DGO Pouvoirs locaux, Action sociale et Santé
Direction fonctionnelle et d'appui

Avenue Gouverneur Bovesse, 100
5100 Namur (Jambes)
tel 081/32.73.75
http://socialsante.wallonie.be
http://pouvoirslocaux.wallonie.be

[coq_spw_ho courriel]      [logo dgo5 pour mél]

---

Avertissement:

## Les contenus et fichiers joints à ce courriel n'engagent nullement le Service public de Wallonie, ni la Direction générale opérationnelle des Pouvoirs locaux, de l'Action sociale et de la Santé. Seul son auteur en est responsable.

De : Vincent Bombaerts [mailto:notifications@github.com]
Envoyé : mercredi 3 décembre 2014 11:37
À : spacebelGIS/metawal-core-geonetwork
Cc : DELVAUX Pascal
Objet : Re: [metawal-core-geonetwork] Recherche / Critère validation (#46)

A tester sur http://metawal.wallonie.be/geonetwork/srv/fre/search?uuid=6bb4a41f-8477-4a0c-95f9-7d2807ee0589

**Comment by vbombaerts** [comment]
Fonctionnel. Est-il possible de valider d'un coup tout le catalogue pour initialiser la valeur pour toutes les fiches ?

**Comment by fxprunayre** [comment]
> Fonctionnel. Est-il possible de valider d'un coup tout le catalogue pour initialiser la valeur pour toutes les fiches ?

Non. Mais ca pourrait une évolution pertinente.
