### ISSUE TITLE
Format / Saisie sous forme de liste

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#460]
A voir si utilisation d'un thésaurus ou d'un annuaire (comme geocat.ch).

- [x] Quelles info sur les formats ? Nom, version, ... ?

- [x] Faire une liste - Stéphane - on peut extraire la liste des valeurs actuelles pour voir ce qu'on a et ensuite homogéniser ?

- [x]  Import

- [x] Edition / Corriger le cas où le même élément (cit:title) peut être saisie à partir de thésaurus différents. 

- [x]  Edition / Configuration de l'édition 

- [x]  Déployer et tester

**Comment by stephyritz** [comment]
Voici la liste des formats vers laquelle on veut aller : 
[code_liste_value_media_extract_registry.xlsx](https://github.com/SPW-DIG/metawal-core-geonetwork/files/3401844/code_liste_value_media_extract_registry.xlsx)
Il s'agit d'un extract du registre test sur lequel nous travaillons actuellement. La valeur que nous souhaitons voir dans la liste déroulante est la colonne étiquette du tableau. On peut imaginer rajouter à cela une ancre référençant la colonne identifiant.

Voici un extract des valeurs actuellement référencées dans Metawal : 
[liste_formats_MW4.txt](https://github.com/SPW-DIG/metawal-core-geonetwork/files/3401853/liste_formats_MW4.txt)
 
Il va y avoir effectivement un travail d’homogénéisation de masse à faire. 

A ce propos, il y a aussi un problème soulevé par Geoffroy sur le fait que, pour les fiches INSPIRE, il y a des doublons dans la déclaration des formats. Je vais faire une issue propre à ce sujet afin de ne pas oublier.

**Comment by fxprunayre** [comment]
> Il s'agit d'un extract du registre test sur lequel nous travaillons actuellement.

Import ok depuis le registre http://re3gistry.gim.be/

![image](https://user-images.githubusercontent.com/1701393/62861739-ae1a7880-bd04-11e9-912f-37feda64ac72.png)

Ajout de https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-3.8.x/web/src/main/webapp/WEB-INF/data/config/codelist/external/thesauri/theme/httpregistrymetawalcodelistmediatypes-media-types.rdf

Saisie sous forme de mot clés possibles (mais on ne veut pas)

![image](https://user-images.githubusercontent.com/1701393/62917173-85918d80-bd9b-11e9-8c31-bbff2bb93812.png)

Saisie sous forme d'autocompletion dans le champ format

![image](https://user-images.githubusercontent.com/1701393/62917192-96420380-bd9b-11e9-8e0a-dde6f05e42a7.png)

Avec référencement de l'URL dans une ancre (on peut désactiver ça si on ne veut pas?)

![image](https://user-images.githubusercontent.com/1701393/62917202-9fcb6b80-bd9b-11e9-9f65-b5eac31bf016.png)

**Comment by fxprunayre** [comment]
Configuré. A déployer pour test.

**Comment by stephyritz** [comment]
Semble ne pas fonctionner en test. Est-ce qu'il faut que je paramètre quelque chose de mon côté pour que le champ "Nom du format" fasse référence à la codelist du thesaurus mediatype ?

**Comment by davinciagf** [comment]
A retester suite au nouveau déploiement

**Comment by stephyritz** [comment]
Ne fonctionne pas non plus après le déploiement du 30/09. C'est le cas pour quelques issues. Est-ce que cela fonctionne sur votre application en local ? Est-ce qu'il faut faire une action supplémentaire depuis l'application ? Genre vider les caches JS et CSS ?

**Comment by davinciagf** [comment]
Fonctionnel en test. Si tu reprends une fiche existante supprime d'abord le format existant ensuite la liste arrive ;-)
![image](https://user-images.githubusercontent.com/576292/66194280-6d036c80-e694-11e9-9932-db061c2d026a.png)

**Comment by stephyritz** [comment]
Ok en environnement de valid mais je viens de remarquer que la liste déroulante ne propose que les 20 premiers résultats du thesaurus.  Ici le dernier format proposé est 'LASZip (.laz)'. Est-il possible de proposer la liste en entier ? Pour un utilisateur peu habitué, cela pourrait induire en erreur. 
Sinon, c'est vraiment top de pouvoir commencer à saisir manuellement et d'avoir des valeurs provenant du Thesaurus qui sont proposées.

**Comment by stephyritz** [comment]
Ok en prod mais mon commentaire ci-dessus est toujours d'actualité. Existe-t-il une solution ?

**Comment by davinciagf** [comment]
C'est du au fonctionnement de l'autocomplétion. Dès que tu tapes tu as l'ensemble des possibibiltés  de résultats issus de la liste; cette liste évolue selon la complétion du champs. 
Exemple: si tu tapes la lettre 'b', tu n'auras que trois éléments disponibles dans la liste des résultats, si tu effaces et puis tu tapes la lettre 'a' la liste sera plus importante, si tu rajoutes la lettre 'd', la liste de résultats possibles se restreint à 2....

**Comment by fxprunayre** [comment]
On peut augmenter le nombre d'item dans la liste. Je vais regarder demain matin.

**Comment by stephyritz** [comment]
Merci, j'avais vu pour l’auto-complétion mais ce n'est pas forcément le top pour un novice qui se demande quelle valeur il peut saisir. Dans notre fonctionnement actuel (1 encodeur unique), ce n'est pas critique mais à l'avenir peut-être que cela pourrait poser problème aux encodeurs. Donc ça serait quand même intéressant d'augmenter le nombre d'items, merci.

**Comment by stephyritz** [comment]
Augmentation du nombre d'items prévue pour le déploiement de 3.8.2 ?

**Comment by fxprunayre** [comment]
> Augmentation du nombre d'items prévue pour le déploiement de 3.8.2 ?

Il y a même une option de configuration pour ça. Fait - limite fixée à 200.

@davinciagf A déployer.
