### ISSUE TITLE
API JS / Analyse technique

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#461]
- [x] Analyse (cf. google doc)

- [x] Démo avec Jahia des différents modes

- [x] Questions/réponses avec NSI

**Comment by fxprunayre** [comment]
A fermer si c'est terminé ?

**Comment by stephyritz** [comment]
Je ne suis pas au courant des avancés sur ce sujet. Je propose qu'on clôture effectivement ce ticket car on peut estimer que cette première étape est réalisée. Si besoin, on fera des issues plus précises sur le sujet dans le futur.
