### ISSUE TITLE
Format de distribution / Double déclaration

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#462]
Pour certaines fiches concernées par INSPIRE, le format de distribution est déclaré deux fois dans la fiche.

Par exemple : http://geoportail.wallonie.be/catalogue/ffc45d44-1cc2-4924-bb8c-214096eb9058.html ; http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/ffc45d44-1cc2-4924-bb8c-214096eb9058

Action (automatique ou manuelle ?) : Homogénéiser la manière de déclarer le format distribué.
A savoir, favoriser les valeurs dans <gmd:distributionFormat> (plutôt que gmd:distributorFormat>)

**Comment by fxprunayre** [comment]
Done in https://github.com/metadata101/iso19115-3.2018/blob/8897c14bbeefb96d8a99964da08bd7e7d97b78b9/src/main/plugin/iso19115-3.2018/process/inspire-tg2.xsl#L251-L268

A tester lors du passage des améliorations TG2.
