### ISSUE TITLE
INSPIRE / Intégration du SpatialScope

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#463]
En plus des TG2, nous sommes tenus de rajouter un tag supplémentaire lié à l'aire géographique concernée par la donnée.

Les actions à mener dans cette optique sont, a priori : 
- [x] Import du registre INSPIRE dédié (http://inspire.ec.europa.eu/metadata-codelist/SpatialScope) dans Metawal --> Stéphane
- [x] Intégrer de ce champs par défaut dans l'Interface MW (création d'un nouveau template INSPIRE ?) --> Stéphane
- [x] Assurer la retranscription conforme entre 19115-3 et 19139
- [x] Mettre à jour l'ensemble des fiches en ajoutant cette information (valeur "Régional")

Ressource intéressante sur le sujet : https://webgate.ec.europa.eu/fpfis/wikis/display/InspireMIG/Example+on+how+to+use+the+GeoNetwork+editor

**Comment by fxprunayre** [comment]
Pour l'import, charger depuis Registry

![image](https://user-images.githubusercontent.com/1701393/62303207-012a3b00-b47c-11e9-841c-5dcc03a4cd25.png)

Le thésaurus est alors disponible.

![image](https://user-images.githubusercontent.com/1701393/62303214-038c9500-b47c-11e9-8133-5569dca52d87.png)


Une fois chargée, il est possible de l'ajouter dans une fiche

![image](https://user-images.githubusercontent.com/1701393/62303484-7dbd1980-b47c-11e9-8f5e-c4e9fee04ba9.png)


Petit bémol, le titre est en anglais 'spatial scope' et non 'champ géographique' car GN ne gère pas le titre de thésaurus multilingue - on peut cependant le surcharger dans les libellés.

Pour les mots clés, est-ce qu'on fait le choix de tout encoder sous forme d'anchor ? Actuellement on peut gérer avec l'icône sur la droite qui détecte le type d'encodage (anchor/characterstring/xlink) mais on peut décider de forcer le mode pour simplifier l'interface ?

**Comment by stephyritz** [comment]
Super. Je n'ai aucun problème à ce que cela soit en anglais, c'est un détail de mon point de vue.
Oui, je suis favorable au système d'anchor et donc je forcerais ce mode par défaut. Même si rien ne semble obliger son utilisation dans ce cas, j'ai l'impression que c'est un mode d'encodage qui a tendance à se développer.

**Comment by fxprunayre** [comment]
A tester (import du registre, édition, process xsl TG2 ajoute régional à toute les fiches Reporting INSPIRE).

**Comment by stephyritz** [comment]
Ok c'est bon. Est-ce qu'on peut cacher le "nom du thesaurus" pour ne pas surchargé la vue depuis l'interface d'édition ?

**Comment by fxprunayre** [comment]
Le nom du thésaurus c'est Champ géographique, c'est pour ça qu'il n'est pas détecté et que tu n'as pas l'affichage simple. J'ai corrigé dans la migration TG2.

```
         <mri:descriptiveKeywords>
            <mri:MD_Keywords>
               <mri:keyword gco:nilReason="missing">
                  <gco:CharacterString/>
               </mri:keyword>
               <mri:type>
                  <mri:MD_KeywordTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_KeywordTypeCode"
                                          codeListValue="theme"/>
               </mri:type>
               <mri:thesaurusName>
                  <cit:CI_Citation>
                     <cit:title>
                        <gcx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/SpatialScope#">Champ géographique</gcx:Anchor>
                     </cit:title>
                     <cit:date>
                        <cit:CI_Date>
                           <cit:date>
                              <gco:Date>2019-07-02</gco:Date>
                           </cit:date>
                           <cit:dateType>
                              <cit:CI_DateTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode"
                                                   codeListValue="publication"/>
                           </cit:dateType>
                        </cit:CI_Date>
                     </cit:date>
                     <cit:identifier>
                        <mcc:MD_Identifier>
                           <mcc:code>
                              <gcx:Anchor xlink:href="http://metawal4.test.wallonie.be/geonetwork/srv/eng/thesaurus.download?ref=external.theme.httpinspireeceuropaeumetadatacodelistSpatialScope-SpatialScope">geonetwork.thesaurus.external.theme.httpinspireeceuropaeumetadatacodelistSpatialScope-SpatialScope</gcx:Anchor>
                           </mcc:code>
                        </mcc:MD_Identifier>
                     </cit:identifier>
                  </cit:CI_Citation>
               </mri:thesaurusName>
            </mri:MD_Keywords>
         </mri:descriptiveKeywords>
```

**Comment by stephyritz** [comment]
Problème non résolu, je me suis peut-être mal exprimé. Voici un prtsc du pb d'affichage en mode édition.
![affichage_thesaurus_spatial_scope](https://user-images.githubusercontent.com/34446202/66138683-4f37f800-e5ff-11e9-9fd8-c858b0994dc0.png)
Je préférerais, si possible que l'onglet "nom du thesaurus n’apparaisse pas (comme pour les autres mots-clés. Fiche exemple si nécessaire --> http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/ffc45d44-1cc2-4924-bb8c-214096eb9058

**Comment by fxprunayre** [comment]
Tous ces pb (format, licence) sont liés au fait que les thésaurus ne sont pas bien déployés. @davinciagf peux tu vérifier ?

**Comment by stephyritz** [comment]
Toujours le même problème en environnement de valid que celui mentionner dans mon dernier comment (voir prtsc).

**Comment by stephyritz** [comment]
Problème toujours présent en prod après le déploiement du 14/10. ? N'est-ce pas lié à l'identifiant du thesaurus erroné ?
Code : geonetwork.thesaurus.external.theme.httpinspireeceuropaeumetadatacodelistSpatialScope-SpatialScope
hlinkref : http://**localhost:8080**/geonetwork/srv/eng/thesaurus.download?ref=external.theme.httpinspireeceuropaeumetadatacodelistSpatialScope-SpatialScope
Voir prtsc ci-dessus.

**Comment by stephyritz** [comment]
Attention, je ne sais pas ce qui a été fait concernant ce point mais maintenant le mot clé "Régional" ainsi que toutes les informations liées (nom du thesaurus, ancre, etc...) sont présents en double dans toutes les fiches taguées INSPIRE. Exemple --> http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/4562d7fe-5827-401c-8708-c0042c38bbf5 
Le problème global mentionné dans ce ticket ainsi que celui de la référence à localhost ne sont toujours pas réglés. Attention, il s'agit d'un point critique concernant INSPIRE et c'est donc important. N'hésitez pas à renseigner dans le fil de cette discussion les actions menées et/ou planifiées sur ce point afin de facilement récupérer l'historique de ce qui est fait.

**Comment by fxprunayre** [comment]
Avec Arnaud, je sais pas s'il n'a pas lancé 2 fois le process qui en effet ajoute à chaque fois le spatial scope.

Quoiqu'il en soit, je propose de tester le mode batch editing

![image](https://user-images.githubusercontent.com/1701393/67764891-31698180-fa4b-11e9-8248-c5b817c94a75.png)

J'ai testé en local et ça me semble ok avec le xpath suivant:
`(.//mri:descriptiveKeywords[*/mri:thesaurusName/*/cit:title/gcx:Anchor = 'Champ géographique'])[2]`
qui correspond au 2ème spatial scope.

Avant de lancer, je ferai bien une sauvegarde de la base avant au cas où.
Tu peux aussi faire un test sur une fiche avec une sauvegarde avant.

**Comment by stephyritz** [comment]
J'ai testé la manip en environnement de valid. Avec peu de fiches, c'est nickel. Avec 213 fiches, le processus semble mettre plus de temps. On ne sais pas trop quand c'est fini car, dans ce cas, aucun message n'apparaît sur l'interface. L'appli a pas mal "ramé" mais maintenant ça m'a l'air bon. Le seul hic, c'est que quand je rentre en mode édition, peu importe la vue (xml ou complète), le keyword apparaît toujours deux fois alors que ce n'est pas le cas depuis l'interface de visualisation principale (avant de rentrer en mode édition). Est-ce qu'il faut faire une synchro depuis la DB ou quelque chose du genre ?

Je ne comprends vraiment pas là. Le keyword régional n'apparaît qu'une seule fois lorsque tu consultes depuis l'interface principale. Mais il est deux fois quand tu passes en mode édition ET dans la DB... Comment est-ce possible ? Ce n'est pas le cas sur la fiche que j'ai modifiée séparément donc ceci s'explique peut-être par le fait que le processus a été stoppé en plein milieu ?!

**Comment by fxprunayre** [comment]
> . Est-ce qu'il faut faire une synchro depuis la DB ou quelque chose du genre ?

Non. 


> fait que le processus a été stoppé en plein milieu ?!

Possible. On peut avoir eu un timeout (A voir avec Arnaud car il fait un peu la même chose quand on lance un process XSL).
En consultation c'est possible que dans l'index on groupe par thésaurus et que donc le doublon n'est pas dans l'index.

**Comment by stephyritz** [comment]
C'est bien un timeout qui semble à l'origine du problème. ; (
![batch_MW4_timeout](https://user-images.githubusercontent.com/34446202/67872013-9ac3c000-fb31-11e9-980c-02bd84939871.png)

**Comment by stephyritz** [comment]
J'ai lancé l'édition en série pour la suppression du second spatialscope en prod. Tout a bien fonctionné pour les séries (51 fiches) et les collections (39). Par contre le batchedit ne tourne pas toujours bien sur un nombre élevé de fiches, sans doute à cause d'un timeout (par exemple, dans ce cas, pour les 121 datasets). Après plusieurs essais, et finalement en divisant par lots plus petits, je pense que cela a finalement fonctionné pour toutes les fiches.
Quand cela a fonctionné, il n'y a plus qu'un seul tag MAIS la référence au thesaurus n'est toujours pas bonne (url associée à l'identifiant = http://localhost:8080/geonetwork/srv/eng/thesaurus.download?ref=external.theme.httpinspireeceuropaeumetadatacodelistSpatialScope-SpatialScope) ET le problème mentionné dans mon commentaire du 3 octobre est toujours présent.

Reste à faire :
- [x] Si possible, pour corriger définitivement les aspects "esthétique" de l'interface + la référence à 'localhost' dans la release de 3.8.2.
- [x] Supprimer le deuxième SpatialScope pour les fiches "datasets" concernées par INSPIRE via un script SQL directement en DB
- [x] Vérifier, via une requête en DB, qu'il y a bien un seul tag par fiche INSPIRE

**Comment by fxprunayre** [comment]
> * [ ]  Vérifier, via une requête en DB, qu'il y a bien un seul tag par fiche INSPIRE

```sql
WITH ns AS (
select ARRAY[ARRAY['xlink', 'http://www.w3.org/1999/xlink'],
       ARRAY['mri', 'http://standards.iso.org/iso/19115/-3/mri/1.0'],
       ARRAY['cit', 'http://standards.iso.org/iso/19115/-3/cit/2.0']] AS n
)

SELECT * FROM (
	SELECT uuid, unnest(xpath('count(//mri:descriptiveKeywords[*/mri:thesaurusName/*/cit:title/*/text() = "Champ géographique"])',
	 XMLPARSE(DOCUMENT data), n))::text  AS count
	FROM metadata, ns
	WHERE isTemplate = 'n') AS stat WHERE count::int > 1
```



>  Supprimer le deuxième SpatialScope pour les fiches "datasets" concernées par INSPIRE via un script SQL directement en DB

Si ca a joué sur toutes les fiches, pas besoin ?

**Comment by stephyritz** [comment]
Merci pour la requête ; )
C'est nickel! On est bon sur les deux derniers points 

> - [x] Supprimer le deuxième SpatialScope pour les fiches "datasets" concernées par INSPIRE via un script SQL directement en DB
> - [x] Vérifier, via une requête en DB, qu'il y a bien un seul tag par fiche INSPIRE

Reste donc le côté esthétique/interface.

**Comment by stephyritz** [comment]
Le thesaurus liés au spatialscope est absent en prod. J'ai essayé de l'importer mais sans succès. J'ai une erreur au moment de le charger. Cf prtsc ci-dessous.

![metawal_thesaurus_registre_error_](https://user-images.githubusercontent.com/34446202/69331604-58cffa80-0c55-11ea-9dc0-6eaae416db47.png)

Des idées sur la cause du problème ?

**Comment by fxprunayre** [comment]
Le message d'erreur qui n'est pas affiché est:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><apiError><code>resource_not_found</code><description>
Thesaurus not found for the requested translation: SpatialScope en
</description><message>ResourceNotFoundException</message></apiError>
```

Je regarde.

**Comment by fxprunayre** [comment]
Est-ce que le serveur peut accèder à http://inspire.ec.europa.eu/metadata-codelist/SpatialScope/SpatialScope.fr.xml - ce serait un problème de proxy/firewall ? cf. problème avec le validateur.

**Comment by stephyritz** [comment]
J'ai un doute sur cette explication car aucun problème depuis l'environnement de test qui a normalement le même type de configuration en terme de proxy/firewall. Je ne peux malheureusement pas vérifier moi même, je vais faire la demande au DTIC et te tiens au courant.

**Comment by stephyritz** [comment]
Didier Husson vient de tester l'accès à http://inspire.ec.europa.eu/metadata-codelist/SpatialScope/SpatialScope.fr.xml depuis la machine sur laquelle est installée Metawal avec succès. La cause liée au proxy/firewall est donc à écarter.

**Comment by fxprunayre** [comment]
Ok bizarre. Pas d'autre suggestion que de faire export test > import prod pour contourner le pb. Fait en prod. Après faudrait creuser un peu plus avec des logs en mode dev de la prod peut être.

**Comment by stephyritz** [comment]
Yes, c'est un peu embêtant qu'on ne puisse pas facilement accéder aux logs pour mieux comprendre d'où pourrait provenir l'erreur. Merci d'avoir analysé le problème. A suivre donc après la prochaine release.

**Comment by stephyritz** [comment]
Attention, problème de référence au localhost et d'affichage toujours pas réglé en environnement de valid, même après déploiement du war 3.8.2 (ou 3.9) de ce jour.

Ex (http://metawal4.valid.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/43699079-4fd4-4c7a-a5b4-eee410510a87) : 
```

<mri:descriptiveKeywords>
            <mri:MD_Keywords>
               <mri:keyword>
                  <gcx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/SpatialScope/regional">Régional</gcx:Anchor>
               </mri:keyword>
               <mri:type>
                  <mri:MD_KeywordTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_KeywordTypeCode" codeListValue="theme"/>
               </mri:type>
               <mri:thesaurusName>
                  <cit:CI_Citation>
                     <cit:title>
                        <gcx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/SpatialScope#">Champ géographique</gcx:Anchor>
                     </cit:title>
                     <cit:date>
                        <cit:CI_Date>
                           <cit:date>
                              <gco:Date>2019-08-01</gco:Date>
                           </cit:date>
                           <cit:dateType>
                              <cit:CI_DateTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode" codeListValue="publication"/>
                           </cit:dateType>
                        </cit:CI_Date>
                     </cit:date>
                     <cit:identifier>
                        <mcc:MD_Identifier>
                           <mcc:code>
                              <gcx:Anchor xlink:href="http://localhost:8080/geonetwork/srv/eng/thesaurus.download?ref=external.theme.httpinspireeceuropaeumetadatacodelistSpatialScope-SpatialScope**">geonetwork.thesaurus.external.theme.httpinspireeceuropaeumetadatacodelistSpatialScope-SpatialScope</gcx:Anchor>
                           </mcc:code>
                        </mcc:MD_Identifier>
                     </cit:identifier>
                  </cit:CI_Citation>
               </mri:thesaurusName>
            </mri:MD_Keywords>
         </mri:descriptiveKeywords>
```

**Comment by stephyritz** [comment]
Ok. Tous les problèmes liés à cette issue sont résolus. Les aspects "esthétique" ont été solutionnés par suppression puis import du thesaurus depuis l'environnement de test. Ceci a eu pour effet, de changer la référence au "localhost" mentionnée plus haut dans la discussion.
