### ISSUE TITLE
Outils / Recherche de liens inactifs

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#465]
Cet outil permettrait de vérifier que les liens vers les ressources associées mentionnées dans les fiches descriptives soient toujours valides.

Il s'agirait d'un outil de contrôle de qualité sur les ressources associées (pdf, image, docx, etc...) intégré directement dans l'application, par exemple dans la console d'admin de GN.

**Comment by fxprunayre** [comment]
Cf https://github.com/geonetwork/core-geonetwork/pull/3868

Sans doute à améliorer un peu dans le cas 115-3 mais nous pouvons commencer par déployer la 3.8 et lancer l'analyse.

**Comment by fxprunayre** [comment]
Cf. http://metawal4.test.wallonie.be/geonetwork/srv/fre/admin.console#/dashboard/record-links

**Comment by fxprunayre** [comment]
Je confirme qu'en local ca marche bien 
![image](https://user-images.githubusercontent.com/1701393/65531068-638e3d80-def9-11e9-9966-c02a1ae2ca0d.png)

mais c'est un peu long.

**Comment by stephyritz** [comment]
Problème lié au proxy et à un timeout. Je fais une "déclaration d'incident" auprès du DTIC pour voir quelles sont nos solutions. Problématique aussi pour certaines requêtes faites sur le CSW.

**Comment by stephyritz** [comment]
Problème résolu en test/valid/prod par Didier Husson (SPW-DTIC) après modification des paramètres Apache
