### ISSUE TITLE
DB / Modification automatique de la date de mise à jour d'une fiche

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#466]
Lorsque qu'un changement a lieu directement en DB, la date de dernière mise à jour de la fiche reste inchangée. 

Par exemple, à la DIG, un process FME permet la modification des dates de révision et de publication d'une donnée. Normalement, la modification de ces champs devraient avoir pour effet une mise à jour de la date de dernière mise à jour de la fiche. Or, il semblerait que cela ne soit plus le cas maintenant. Depuis la mise en prod de MW4 ? Depuis le déploiement du dernier war ?
Cependant, cela fonctionne lorsque les données sont modifiées ou saisies via l'interface de l'application.

Est-ce bien un trigger dans postgres qui est à l'origine de cette action ?
Avez-vous une idée pour corriger ce problème ?

**Comment by fxprunayre** [comment]
> Or, il semblerait que cela ne soit plus le cas maintenant.

Ca n'a jamais été le cas je pense.

> Est-ce bien un trigger dans postgres qui est à l'origine de cette action ?

Non, c'est l'appli Java qui s'en occupe selon les cas.

> Avez-vous une idée pour corriger ce problème ?

Si FME utilise le CSW-T, alors en 3.8.0, le dateStamp sera récupéré est mis dans la colonne correspondante en base
https://github.com/geonetwork/core-geonetwork/pull/3876

**Comment by stephyritz** [comment]
Ok merci pour les informations. Je transmets à Stéphane et Dominique. A priori cela sera donc opérationnel pour fin septembre alors.

**Comment by stephyritz** [comment]
La modification de cette valeur de date est maintenant prise en charge par un process FME côté SPW via le CSW-T au même titre que les dates de révision et de publication d'une donnée lorsqu'elle évolue.
