### ISSUE TITLE
Interface / Affichage de la date de mise à jour d'une fiche

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#467]
La valeur affichée sur Metawal ('Mis à jour :') ne semble pas correspondre à la valeur stockée en DB. 

Exemple : 
Lors du téléchargement du xml (19115-3) la valeur est bien "01/08/2019", idem sur le Geoportail (donc en 19139). Cependant, dans Metawal, il est écrit "Il y a 2 mois".

https://geoportail.test.wallonie.be/catalogue/d594f5a3-34ac-4cc2-a357-aae5d5263f35.html (onglet Description/Identification de la fiche descriptive/Date de mise à jour de la fiche descriptive)

http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/d594f5a3-34ac-4cc2-a357-aae5d5263f35

Il doit y avoir un problème de synchronisation au niveau de l'affichage. Peut-on également en profiter pour afficher la date exacte plutôt que "il y a x temps" ?

**Comment by fxprunayre** [comment]
> Il doit y avoir un problème de synchronisation au niveau de l'affichage. Peut-on également en profiter pour afficher la date exacte plutôt que "il y a x temps" ?

Ce sera une option de l'interface en 3.8.0 https://github.com/geonetwork/core-geonetwork/pull/3771 et sinon il y a une info bulle pour avoir la date 

![image](https://user-images.githubusercontent.com/1701393/62622337-6f5c7b00-b91e-11e9-908a-54376724ae18.png)





> Cependant, dans Metawal, il est écrit "Il y a 2 mois".

Quand on récupère la fiche:
http://metawal4.test.wallonie.be/geonetwork/srv/fre/q?_content_type=json&_isTemplate=y+or+n&_uuid_OR__id=d594f5a3-34ac-4cc2-a357-aae5d5263f35&fast=index

```json
geonet:info: {
@xmlns:geonet: "http://www.fao.org/geonetwork",
id: "137",
uuid: "d594f5a3-34ac-4cc2-a357-aae5d5263f35",
schema: "iso19115-3",
createDate: "2012-10-24T15:31:51",
changeDate: "2019-05-27T13:45:14",
```

Donc on est sur un cas où la date en base ne correspond pas à la date dans la fiche. A voir quelles manips ont été faites ?

**Comment by stephyritz** [comment]
Cool, je ne savais pas pour l'infobulle. C'est bien que cela soit une option dans GN 3.8.
Pour cette donnée en particulier, il s'agit d'une modification de valeur faite via FME donc sûrement en utilisant le CSW-T je suppose. Comment la date en DB peut-être différente de la date dans la fiche ? C'est parce que c'est une valeur qui est modifiée en Java classiquement ?

**Comment by fxprunayre** [comment]
> Comment la date en DB peut-être différente de la date dans la fiche ?

Avant 3.8.0, on pouvait faire une transaction CSW qui ne mettait pas à jour la date en base et qui aurait pu mettre à jour le XML. C'est le Java qui s'occupe de cette synchro.

**Comment by fxprunayre** [comment]
A tester avec l'option dans l'admin
![image](https://user-images.githubusercontent.com/1701393/62860963-2f244080-bd02-11e9-846f-252776c15fcb.png)

=
![image](https://user-images.githubusercontent.com/1701393/62860975-38ada880-bd02-11e9-8ccd-a7892d72df9a.png)

**Comment by stephyritz** [comment]
Dans la console d'admin, ce qui est proposé en prod aujourd'hui (après déploiement de la 3.8.1) n'est pas cohérent avec ce qui était présent en test et valid. Je n'utilise pas toutes les possibilités de la console admin mais c'est flagrant pour ce cas, dans l'onglet "Interface utilisateur". Par exemple, Il n'y a pas l'option "Choisir la configuration d'interface" + liste déroulante. Il n'y a pas non plus l'option "Humaniser les dates". Problème dans le déploiement ???

**Comment by davinciagf** [comment]
Vider le cache au niveau de l'admin (outils > vider lecache css et jss), solutionne le problème
