### ISSUE TITLE
DB / Supression d'une valeur EPSG pour l'ensemble des fiches de services

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#468]
Opengis ne référence plus ce système de projection : http://www.opengis.net/def/crs/EPSG/0/84  (car équivalent à 4326 ?!). Or, il a été référencé quasi-systématiquement pour l'ensemble des fiches de services.

Les liens actuels sont donc en erreur aujourd'hui sur le Geoportail.
Il faudrait donc écrire et déployer un script sql sur la DB supprimant cette partie du xml : 
<mdb:referenceSystemInfo xmlns:geonet="http://www.fao.org/geonetwork">
      <mrs:MD_ReferenceSystem>
         <mrs:referenceSystemIdentifier>
            <mcc:MD_Identifier>
               <mcc:code>
                  <gco:CharacterString>http://www.opengis.net/def/crs/EPSG/0/84</gco:CharacterString>
               </mcc:code>
            </mcc:MD_Identifier>
         </mrs:referenceSystemIdentifier>
      </mrs:MD_ReferenceSystem>
  </mdb:referenceSystemInfo>

**Comment by fxprunayre** [comment]
A tester avec le process TG2.
