### ISSUE TITLE
Général / Nombre total de fiches différents selon les outils mobilisés

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#469]
Je ne comprends pas bien pourquoi les chiffres suivants sur le total des fiches sont différents : 
- D'après le sommaire de la console d'admin : 405 (jeu de données) + 391 (services) + 140 (Collection de données) + 44 applications = **980** total différents des **988** (total affiché de 'fiches dans le catalogue' ) 
- D'après la facette par type de ressource : 422 (jeu de données) +399 (services) + 45 (application) +140 (Collection de données) +1 (carte) = **1007**
- D'après le CSW : TOTAL = **982**

Est-ce qu'il y a des explications à cela ? Encodage ? Mode de calcul de l'API ? Conservation des fiches supprimées ?

**Comment by fxprunayre** [comment]
> * D'après le sommaire de la console d'admin : 405 (jeu de données) + 391 (services) + 140 (Collection de données) + 44 applications = **980** total différents des **988** (total affiché de 'fiches dans le catalogue' )

Il peut y avoir des fiches et/ou modèles sans type de resource. Dans GeoNetwork, c'est assez difficile à identifier depuis l'interface actuellement mais avec ES on pourra avoir une catégorie "nodata" dans les facettes pour les items sans valeur pour un champ. Faudrait faire une analyse en base pour en savoir plus.

En rusant un peu on pourrait avoir la liste avec 
http://metawal.wallonie.be/geonetwork/srv/fre/catalog.edit#/board?sortBy=changeDate&_isTemplate=y%20or%20n&resultType=manager&from=1&to=20&without_type=series%20OR%20map%20OR%20application%20OR%20dataset%20OR%20service
mais pas tout à fait.

Cependant en creusant, je suis tombé sur 7 fiches un peu bizarre sans hierarchy level http://metawal.wallonie.be/geonetwork/srv/fre/catalog.edit#/board?sortBy=changeDate&_isTemplate=y%20or%20n&resultType=manager&from=1&to=20&without_type=series%20OR%20map%20OR%20application%20OR%20dataset%20OR%20service&fast=index&_content_type=json&facet.q=publishedForGroup%2FSG

Donc ca peut expliquer une partie du pb ?

Egalement lors de l'indexation on ne suit pas l'idée du standard disant si pas de hierarchyLevel alors c'est un dataset https://github.com/metadata101/iso19115-3.2018/blob/master/src/main/plugin/iso19115-3.2018/index-fields/common.xsl#L859. Je pense que c'est bien de ne pas trop supposer de chose et de clairement indiquer de quoi on parle.

> D'après la facette par type de ressource : 422 (jeu de données) +399 (services) + 45 (application) +140 (Collection de données) +1 (carte) = 1007
 
Tu peux avoir une fiche classée dans plusieurs types. Idem, faire une requête la dessus c'est pas faisable. Avec ES on pourra avec la notion de champ calculé je pense.


> D'après le CSW : TOTAL = 982

Le CSW fait abstraction des modèles en plus.

**Comment by stephyritz** [comment]
Ok merci pour les explications. Je vais demander des renseignements sur les 7 fiches bizarres. Dans la console d'admin, effectivement les modèles peuvent expliquer la différence entre 980 et 988. D'accord avec toi pour ne pas supposer trop de choses. Mieux vaut mettre en  avant les éléments avec des informations manquantes et les compléter manuellement ensuite. Pour les facettes, j'imaginais aussi que cela puisse être lié à des fiches qui seraient classées dans plusieurs types. Mais en théorie, ce cas ne devrait pas se présenter et irait probablement à l'encontre des TG INSPIRE. Le CSW est peut-être quand même le moyen le plus sûr pour connaître le nombre de fiches du catalogue.
