### ISSUE TITLE
Header / lien de "Metawal - Catalogue..."

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#47]
Lien invalide --> renvoie vers une adresse invalide http://metawal3.test.wallonie.be/cms/home.html

**Comment by fxprunayre** [comment]
Précision : Le lien sur le titre de l'app "Metawal - Catalogue pour l'information géographique de Wallonie"

**Comment by fxprunayre** [comment]
https://github.com/spacebelGIS/metawal-core-geonetwork/commit/bcc0e4d59625867873e61ee2b725468d8a0e88bc

**Comment by vbombaerts** [comment]
La page n'est pas rechargée quand je clique sur le header. Par exemple j'étais connecté, je me déconnecte et dans les dernières publications je vois des fiches qui ne sont pas publiées grand public.

Précision : doit pointer vers la page d'accueil du site (page qui s'affiche avant toute recherche, avec les dernières publications et avec le formulaire de recherche remis à zéro)

![image 639](https://f.cloud.github.com/assets/6093597/1782982/8b5383e0-68ba-11e3-8471-8285d807b604.png)

**Comment by fxprunayre** [comment]
A redéployer.

**Comment by vbombaerts** [comment]
Merci pour l'amélioration. Ca marche bien maintenant. Il manque encore la conservation de la langue choisie.
(si j'étais dans la version allemande, je reviens en français quand je clique sur la bannière. Je voudrais rester en allemand.)

**Comment by vbombaerts** [comment]
Sera implémenté dans une version à venir

**Comment by fxprunayre** [comment]
Langue stockée dans un cookie dans le prochain alignement GN.
