### ISSUE TITLE
Tâches d'administration / Gestion des utilisateurs

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#472]
Actuellement il y a beaucoup trop d'utilisateurs de Metawal avec une activité très réduite depuis que je suis arrivé (mars 2019). Avec les procédures de création de MD qui ont changé depuis quelques temps au sein du SPW (DIG = encodeur unique sur Metawal), cela entraîne un fort risque de perte de maitrise sur le contenu et de l'application.

Je souhaiterais exporter un listing des utilisateurs avec leur adresse mail pour communiquer avec eux sur ces nouvelles procédures. De plus j'aimerais bien avoir la possibilité de désactiver temporairement l'ensemble des comptes.

Enfin, dans le cadre de l'amélioration de la gestion des utilisateurs, notamment via l'utilisation d'un annuaire partagé au sein du SPW (voir https://github.com/SPW-DIG/metawal-core-geonetwork/issues/448), je souhaiterais faire un "grand ménage" sur les utilisateurs après la mise en prod de la version 3.8.

**Comment by davinciagf** [comment]
Sortie DB à produire.

**Comment by davinciagf** [comment]
Envoie du listing par email à Stéphane (extract de l'env de test en date du 27/09/2019)
