### ISSUE TITLE
Historique / Message de Mise à Jour dès le passage en mode édition

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#473]
Il arrive souvent que je passe en mode édition dans une fiche pour accéder à son contenu, voir la manière dont les informations sont encodées ou encore pour chercher une information nécessaire à la rédaction d'une autre fiche. Ces actions se font sans aucune modification de contenu. Je sors de la fiche via le bouton "annuler".

Or, il semblerait que, pour la création de l'historique (https://github.com/geonetwork/core-geonetwork/pull/3209), l'application considère qu'il y a eu une mise à jour dès le moment où la fiche est consultée en mode édition.

**Comment by stephyritz** [comment]
Pour être plus précis : il semblerait que le simple passage à une vue différente (par ex. en vue complète) déclenche une sauvegarde automatique. Ceci pourrait expliquer le problème mentionné ci-dessus.

**Comment by fxprunayre** [comment]
Oui, chaque changement d'onglet déclenche une sauvegarde en base (et donc historisation). Cancel restaure la version initiale à l'ouverture de la session d'édition mais ne supprime pas l'historisation faite entre temps. Comme ça, je ne vois pas de solution trivial.

**Comment by fxprunayre** [comment]
- [x] Metadata change / Garder une version au début de la session et à la fin (https://github.com/geonetwork/core-geonetwork/pull/4494)
- [x] Cancel / Annuler l'historique de la session d'édition (action de type édition
- [ ] Cancel / Annuler l'historique de la metadataProcess

**Comment by fxprunayre** [comment]
>  Metadata change / Garder une version au début de la session et à la fin (geonetwork#4494)

A déployer et tester. Le 3ème point est beaucoup plus compliqué à mettre en oeuvre. Je propose de le garder pour une version ultérieure
