### ISSUE TITLE
Requête CSW / Erreur Proxy 502 pour un Getrecord&service

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#474]
Lors de l’exécution de la requête suivante, j'obtiens très souvent une erreur proxy en retour : 
http://metawal.wallonie.be/geonetwork/srv/fre/csw?request=GetRecords&service=CSW&version=2.0.2&namespace=xmlns(csw=http://www.opengis.net/cat/csw)&resultType=results_with_summary&outputSchema=http://www.isotc211.org/2005/gmd&outputFormat=application/xml&maxRecords=500&typeNames=gmd:MD_Metadata&elementSetName=full&constraintLanguage=CQL_TEXT&constraint_language_version=1.1.0

Parfois même avec un maxrRecords = 60. C'est un peu problématique pour moi car j'utilise cette requête dans des workspaces FME pour réaliser des tableaux de suivi. Est-ce que vous pensez qu'il est possible de lever ce problème de timeout ? Est-ce de notre ressort ou bien du DTIC ? Si vous avez des solutions/idées je suis preneur. Une première option serait d'ajouter une contrainte dans le call http, par exemple contrainte_type=dataset mais même avec cela, le nombre de fiches obtenues conduit souvent à une erreur 502.

**Comment by fxprunayre** [comment]
Le Proxy ce n'est pas GN, donc je pense que c'est à voir côté proxy. Tomcat peut également avoir un timeout. Le timeout semble être fixé à 1min (3 requêtes, toujours le même temps)

![image](https://user-images.githubusercontent.com/1701393/65132218-e64a6080-da00-11e9-9720-e66991c60de0.png)

L'erreur "Error reading from remote server" devrait plutôt dire "Timeout set to 60s, the proxy cancelled this request." je crois.

On peut tester la même requête en localhost sur le serveur pour voir si c'est le proxy ou tomcat.

**Comment by stephyritz** [comment]
Problème résolu en test/valid/prod par Didier Husson (SPW-DTIC) après modification des paramètres Apache
