### ISSUE TITLE
Interface / Impossibilité d'afficher les vues complète et Géoportail sur metawal4.test

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#475]
Impossible d'afficher ces vues dans metawal4.test : "La fiche avec l'identifiant n'a pas été trouvée ou n'est pas partagée avec vous. Essayer de vous connecter si vous avec un compte."

![PB_acces_vue_complete_vue_geoportail](https://user-images.githubusercontent.com/34446202/65598419-a4d72980-df9b-11e9-9265-1a882a8792a8.png)

**Comment by fxprunayre** [comment]
Hum bizarre. Tu peux préciser un UUID pour reproduire ?

Par exemple pour http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.edit#/metadata/1478?redirectUrl=catalog.search%23%2Fmetadata%2F3abbdf68-678b-448e-841b-2d7126ba92f2&tab=identificationInfo ca marche bien.


J'ai repéré un pb sur http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.edit#/metadata/624?redirectUrl=catalog.search%23%2Fmetadata%2Fca230c6e-379d-41ab-8c68-8d29ce02bb24&tab=xml. Sans doute un pb fiche multilingue.

```
A sequence of more than one item is not allowed as the first argument of java:twoCharLangCode() ("fre", "fre")
```

Je regarde.

**Comment by davinciagf** [comment]
En réunion, mais je pense que la fiche a peut être déjà posé problème lors de la migration vers l'iso115-3:2018

"metadataErrors":{"624":[{"message":"A sequence of more than one item is not allowed as the first argument of java:twoCharLangCode() (\"fre\", \"fre\") ","date":"2019-09-20T15:49:19","stack":"; SystemID: file:/home/sites/metawal4/active/geonetwork/WEB-INF/data/config/schema_plugins/iso19115-3.2018/update-fixed-info.xsl; Line#: 436; Column#: -1\nnet.sf.saxon.trans.XPathException: A sequence of more than one item is not allowed as the first argument of java:twoCharLangCode() (\"fre\", \"fre\") \n\tat net.sf.saxon.expr.Expression.typeError(Expression.java:981)\n\tat 

Je regarde asap si c'est la même fiche

**Comment by fxprunayre** [comment]
> Je regarde asap si c'est la même fiche

Y'a de forte chance. Y'en avait qu'une avec ce type d'erreur ?

**Comment by fxprunayre** [comment]
Corrigé pour le cas des fiches multilingues.

**Comment by fxprunayre** [comment]
Ah ok, c'est en consultation le pb, pas édition sorry.

**Comment by davinciagf** [comment]
Yep - une seule erreur de ce type. Fiche 624 - ca230c6e-379d-41ab-8c68-8d29ce02bb24
Fiche qui correspond à l'erreur que tu as rapporté.

**Comment by fxprunayre** [comment]
> Yep - une seule erreur de ce type. Fiche 624 - ca230c6e-379d-41ab-8c68-8d29ce02bb24

Ok donc c'est bon pour ça.

Pour la consultation, la configuration est à mettre à jour 

![image](https://user-images.githubusercontent.com/1701393/65603468-01d7dd00-dfa6-11e9-802d-2d21612b7558.png)


```json
      "formatter": {
        "list": [
          {
            "label": "defaultView",
            "url": ""
          },
          {
            "label": "full",
            "url": "/formatters/xsl-view?root=div&view=advanced"
          },
          {
            "label": "Vue Géoportail",
            "url": "/formatters/geoportail-view?root=div&view=advanced"
          }
        ],
        "defaultUrl": ""
      },
```

Mais il y a un autre pb.

**Comment by fxprunayre** [comment]
A déployer. Ca devrait être mieux. https://github.com/SPW-DIG/metawal-core-geonetwork/commit/4338af94cc6c73546dad6ab84e29c0580ddc45fb

**Comment by stephyritz** [comment]
Oui c'est en mode consultation pas édition. Problème toujours présent mais différent (plus de message d'erreur mais rien ne s'affiche).
Exemples : http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/7fe2f305-1302-4297-b67e-792f55acd834/formatters/xsl-view?root=div&view=advanced
http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/b5a1a9ab-7871-420b-bfba-3e2f1050a77c/formatters/xsl-view?root=div&view=advanced
....
Ce n'est pas propre à certains MDUUID ou alors c'est un sacré hasard parce que j'ai ai testé plusieurs.

**Comment by fxprunayre** [comment]
> Problème toujours présent mais différent (plus de message d'erreur mais rien ne s'affiche).

Oui oui, il faut redéployer avant. Wait! @davinciagf tu nous dis quand c'est en ligne.

**Comment by davinciagf** [comment]
Prévu demain matin

**Comment by stephyritz** [comment]
A priori non résolu après le déploiement de GN 3.8.1. 
A moins de devoir faire une action supplémentaire depuis la console d'admin pour valider le changement ?

**Comment by davinciagf** [comment]
La vue géoportail n'a pas été rétablie en iso19115-3:2018 (formatter). Je regarde cela.

**Comment by davinciagf** [comment]
Vue complète fonctionne si l'on n'attaque pas directement l'url de la vue avancée. Lorsque l'on pointe directement vers l'url http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/92bea901-888f-4ae8-983f-b971bf6b50b5/formatters/xsl-view?root=div&view=advanced la vue ne se charge pas

**Comment by fxprunayre** [comment]
> la vue ne se charge pas

Ce n'est pas systématique mais presque.
C'est surement en lien avec https://github.com/geonetwork/core-geonetwork/pull/3909/files

**Comment by fxprunayre** [comment]
Bon j'ai tenté plusieurs choses, c'est lié à la séquence de chargement. Quand l'appli se charge, si on a metadata/xyz, alors il y a vérification que xyz existe bien et ensuite l'init de la vue. Le pb c'est que certaines choses (trop?) se déclenche sur changement d'URL et l'ordre n'est pas le bon. Faudrait faire le ménage sans doute mais bon pour l'instant je propose

https://github.com/SPW-DIG/metawal-core-geonetwork/commit/2c4e1aafe94c287f96b7fef4eb3db7bedca44ac7

Un watch sur current.record pour initialiser le formatter (pas uniquement sur changement d'URL). @davinciagf, je suis preneur de quelques tests complémentaires & avis.

**Comment by davinciagf** [comment]
Ok je teste.

**Comment by davinciagf** [comment]
Testé avec succès sur différentes coutures : 
- enregistré, non enregistré
- accès directe à la vue, accès via la vue générale

Une seule erreur mais non reproductible et avant d'avoir vider le cache.

**Comment by davinciagf** [comment]
A retester suite au nouveau déploiement

**Comment by stephyritz** [comment]
C'est bon pour la vue complète mais pas pour la vue "Geoportail". On dirait que c'est parce que, peu importe que tu choisisses la vue complète ou celle du Geoportail, le bouton renvoie à l'url suivante, par exemple : http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/88f5f3ce-98f5-4ab3-b226-ad8a9692a339/formatters/geoportail-view?root=div&view=advanced

**Comment by davinciagf** [comment]
Formatter non présent en test mais bien en local - je vérifier pq il n'est pas passer dans le build du war.

**Comment by stephyritz** [comment]
Ne fonctionne pas en environnement de valid. Même message d'erreur que celui signalé dans le premier post.

**Comment by davinciagf** [comment]
A vérifier :  la règle de récupération des schémas (war ou data_dir) au niveau de l'env de valid. Théoriquement, il devrait pointé sur le war qui contient bien le formatter relatif au  Géoportail.

**Comment by fxprunayre** [comment]
> A vérifier : la règle de récupération des schémas (war ou data_dir) au niveau de l'env de valid. Théoriquement, il devrait pointé sur le war qui contient bien le formatter relatif au Géoportail.

Pour vérifier aller dans http://metawal4.test.wallonie.be/geonetwork/srv/fre/admin.console#/dashboard/information
et regarder que répertoire des standards soit bien dans la webapp
![image](https://user-images.githubusercontent.com/1701393/66404258-62283f00-e9e8-11e9-96b2-124bcb22f4bd.png)

**Comment by stephyritz** [comment]
Le problème vient de là effectivement...
![issue#475](https://user-images.githubusercontent.com/34446202/66458247-892b5300-ea72-11e9-84e4-48bdd753ad7f.png)
Pour la majorité des répertoires mentionnés, le folder "data" est doublé. comme par exemple pour les ressources. Je n'ai pas la main pour modifier cela depuis l'interface visiblement.

**Comment by stephyritz** [comment]
Et idem en prod... Est-ce là l'origine de plusieurs problèmes (ressources associées, disparition d'imagettes, etc...) depuis la migration à metawal4 ?

**Comment by davinciagf** [comment]
Le problème venait de la configuration de la vue utilisateur au niveau de  admin/Paramètres/Interface utilisateur:

![image](https://user-images.githubusercontent.com/576292/66464227-df9e8e80-ea7e-11e9-9e2e-17307ba7237b.png)
 
A remplacer par :

![image](https://user-images.githubusercontent.com/576292/66464176-c269c000-ea7e-11e9-82fd-f73a805933d8.png)

A modifier en prod également lors de la migration.
@fxprunayre, est-ce normal ce changement du chemin des formatters ?

**Comment by fxprunayre** [comment]
> @fxprunayre, est-ce normal ce changement du chemin des formatters ?

Oui c'est lié au fait que dans metawal on utilise un formatter par défaut qui n'est pas la vue angular. Le formatter fait partie maintenant de l'url du navigateur.

**Comment by stephyritz** [comment]
@davinciagf les changements d'URL que tu as mentionné n'étaient pas automatiquement renseignés dans la mise en prod du 14/10/2019. Es-tu sûr que le déploiement s'est fait à partir du dernier war ?? J'ai repéré d'autres problèmes majeurs qui me laisse un doute là-dessus... Je vous envoie un récap par mail. Dans ce cas, j'ai essayé d'apporter les changements comme tu l'a indiqué dans tes commentaires mais rien ne se passe au moment où je clique sur "Sauver la configuration".
