### ISSUE TITLE
Edition / Impossible de supprimer une ressource en ligne 

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#476]
Dans l’environnement de test, suite au déploiement de GN 3.8.
Depuis l'interface d'édition, impossible de supprimer une ressource en ligne en utilisant la "croix" depuis le panneau de droite.
Voir exemple : http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/73414a3a-fe93-49dd-9ecd-7137e54402cf
J'ai essayé de supprimer le "Test upload rapport final" sans succès. Semble fonctionner pour la suppression de services et de liens http même si très lent à l'exécution.

**Comment by fxprunayre** [comment]
Cause identifiée https://github.com/geonetwork/core-geonetwork/issues/4062

Corrigé (pour le moment en enlevant ce qui pose le problème). C'est en lien avec la fonction de draft et je ne suis pas certain de savoir comment les fichiers attachés sont censés fonctionner dans le draft. J'ai demandé des précisions. A déployer.

**Comment by stephyritz** [comment]
Ok mais attention, je viens de remarquer, lors du test, que la suppression d'une ressource associée semble tout de même effective, même en cliquant ensuite sur le bouton "Annuler" pour quitter le mode édition. Est-ce normal ?

**Comment by fxprunayre** [comment]
Oui le bouton annuler ne sait pas annuler ça. Pour améliorer: 
a) ajouter une popup de confirmation avant de supprimer le fichier
b) ajouter ça dans annuler

a+b serait top, mais b n'est pas trivial. a) serait déjà bien ?

**Comment by stephyritz** [comment]
Oui a) serait déjà bien dans un premier temps. Peut-être faut-il créer un ticket spécifique pour cette problématique (valable pour GN en général) afin de ne pas oublier ? Niveau planning, rien d'urgent de mon point de vue, je te laisse planifier ça pour le milestone qui te semble le plus pertinent.

**Comment by stephyritz** [comment]
Déplacement du problème adjacent dans un ticket spécifique : https://github.com/SPW-DIG/metawal-core-geonetwork/issues/480
