### ISSUE TITLE
Interface de saisie / Codelist des protocoles pour les ressources associées

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#478]
Je souhaiterais rajouter une valeur à cette codelist afin que d'autres processus du Geoportail puisse se baser sur cette information.

Très concrètement, il s'agirait de rajouter la valeur "ESRI:REST-Tuilé" (valeur à valider par les collègues). Le comportement du bouton "Consulter dans WalonMap" s’appuierait alors sur une règle en fonction de cette valeur : "Si il y a une ressource avec un protocole ESRI-REST-Tuilé, alors je propose l'ouverture de la couche dans WalonMap avec ce type de protocole (pas la possibilité de cocher/décocher les couches du service mais un gain de performance non négligeable). Sinon, ouverture de la couche dans WalonMap selon le protocole ESRI:REST classique."

Solution proposée côté Metawal : 
Je souhaiterais, si possible, faire en sorte que cette codelist soit présente en tant que Thesaurus Geonetwork. Ceci me permettrait plus facilement de, par exemple, rajouter une valeur.

**Comment by fxprunayre** [comment]
> rajouter la valeur "ESRI:REST-Tuilé"

a) Est-ce qu'il y a une différence pour l'ajout dans walonmap d'une couche tuilé ou pas ? Si l'appel est le même on n'a peut être pas besoin de 2 protocoles ?

b) Si il en faut un, alors je propose de l'ajouter de suite avant la mise en prod ? peu de risque et simple à faire.



> Je souhaiterais, si possible, faire en sorte que cette codelist soit présente en tant que Thesaurus Geonetwork. Ceci me permettrait plus facilement de, par exemple, rajouter une valeur.

Typiquement sur cette liste de valeur je suis pas forcément pour car les protocoles sont une liste utilisée à de nombreux endroits - eg. type de boutons affiches pour l'ajout à la carte, pour le download, pour l'ouverture d'une carte, pour un GetCapabilities pour les service, liste de couche si ATOM, la popup resource associée "cache" le protocol en fonction du choix dans la liste principale, ...

Donc ajouter une valeur dans cette liste en particulier n'est pas sans conséquence.

Après si nous faisions ça, nous ouvririons une API sur la config des codelists des schémas (mais après question sur la persistence des schémas actuellement dans la webapp, synchro avec github, ...)

**Comment by stephyritz** [comment]
> a) Est-ce qu'il y a une différence pour l'ajout dans walonmap d'une couche tuilé ou pas ? Si l'appel est le même on n'a peut être pas besoin de 2 protocoles ? 

Je pense que l'URL est la même mais il y a un paramètre différent à ajouter si on veut afficher le REST tuilé. Je ne connais pas bien ce type de service non plus. Au moment de publier le webservice via ArcGIS, mon collègue peut choisir de créer une service tuilé ou non. Ce qui l'intéresserait serait de faire en sorte que, depuis le catalogue, le bouton "accéder dans walonmap" fasse appel au service tuilé si existant. Et pour savoir s'il est existant, il songeait à le mentionner dans la MD au niveau des protocole, un peu comme le WMS et le WMS-T. Je ne suis pas 100% à l'aise avec ce choix car on utilise la valeur "protocole" un peu comme un mot-clé qui va servir à paramétrer une autre fonction. Je vais voir avec mon collègue quelle est la réelle différence dans l'appel d'un REST-Tuilé. 

> Typiquement sur cette liste de valeur je suis pas forcément pour car les protocoles sont une liste utilisée à de nombreux endroits - eg. type de boutons affiches pour l'ajout à la carte, pour le download, pour l'ouverture d'une carte, pour un GetCapabilities pour les service, liste de couche si ATOM, la popup resource associée "cache" le protocol en fonction du choix dans la liste principale, ...

OK j’imaginais bien qu'il y avait une bonne raison à cela ; )
De toute manière, cette liste n'est pas amener à bouger souvent donc pas grave si cela reste dans le schema.

> Après si nous faisions ça, nous ouvririons une API sur la config des codelists des schémas (mais après question sur la persistence des schémas actuellement dans la webapp, synchro avec github, ...)

Je ne comprends pas trop cet aspect. Pourquoi il faut ouvrir une nouvelle API après l'ajout d'une valeur dans ce schéma ? Cette valeur pourrait être aussi ajouté dans le schéma proposé à tous les utilisateurs de GN, non ? Du coup pas de soucis de synchro avec github. Ou bien tu penses que cela pollue trop la codelist et peut avoir des conséquences trop importantes ?

**Comment by fxprunayre** [comment]
> Pourquoi il faut ouvrir une nouvelle API après l'ajout d'une valeur dans ce schéma

Oui, les options:
z) on ajoute la valeur dans la liste des protocols - fichier codelist.xml du schéma (pour metawal uniquement voire pour GN aussi) - on peut faire ça maintenant
y) on ajoute un thésaurus (éditable via l'admin) et on branche la codelist dessus (actuellement pas possible)
x) on ajoute une API pour pourvoir via l'admin modifier le fichier codelist.xml (ca veut dire qu'il faut préserver cette modif lors des mises à jour et aujourd'hui notre fichier codelist.xml il est dans github)

Donc je serai pour faire z) de suite (y compris dans GN). Il nous faudrait juste les instructions pour ajouter la couche tuilée dans walonmap.

Entre y et x, j'aurai une préférence pour x sans doute mais sur le cas des protocoles c'est pas une bonne idée car ça impacte beaucoup de choses (cf ci-dessus).

**Comment by stephyritz** [comment]
Ok c'est très clair. L'option z me semble aussi la plus adaptée. Dès que je peux, je regarde avec mon collègue quelle est la valeur exacte que nous souhaitons ajouter dans la codelist et quelle est l'instruction pour passer depuis le catalogue à WalonMap avec le service REST-Tuilé défini.

**Comment by stephyritz** [comment]
Voici les dernières nouvelles à ce sujet : 
L'URL est bien la même que cela soit pour un REST ou un REST-tuilé, contrairement au WMS et WMS-T.
Or c'est bien l'URL que nous mentionnons dans Metawal et l'API du geoviewer va interprèter et appliquer un exportmap ou un gettiles en fonction des cas. 
En partant de ce constat, il paraît plus pertinent de faire en sorte qu'il y ait dans le catalogue un unique bouton (accès dans WalonMap) et que l'API se charge d'appliquer la règle "si des tiles existent, alors faire un appel type gettiles".
Donc, pour Metawal, on peut toujours renseigner un protocole différent en ajoutant REST-Tuilé à la codelist mais cela sera uniquement pour signaler cette possibilité à l'utilisateur (purement informatif).

**Comment by fxprunayre** [comment]
> REST-Tuilé à la codelist mais cela sera uniquement pour signaler cette possibilité à l'utilisateur (purement informatif).

Du coup, on ajoute une valeur dans la liste ?
```
      <option value="ESRI:REST">ESRI REST Service</option>
      <option value="ESRI:REST-TILED">ESRI REST Tiled Service</option>
```

**Comment by stephyritz** [comment]
Oui, stp.

**Comment by fxprunayre** [comment]
Fait côté GN, mergé dans MW.

A priori, 
* indexation ok sur le champ diffusion mode
* ajout dans la liste des protocols et dans la liste de choix.

A déployer et tester @davinciagf
