### ISSUE TITLE
Edition / Validateur INSPIRE

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#479]
En réalisant le testing sur l'environnement de valid, je rencontre un problème non présent en test : 
En mode édition d'une fiche, si je chercher à "valider selon les TG2 d'INSPIRE datasets and series", j'ai le message d'erreur suivant : "_Erreur de validation distante: Vérifier l'URL_."

Je suis allé dans les paramètres pour vérifier l'url utiliser pour le test comme décrit dans la doc (https://github.com/geonetwork/doc/blob/inspire-tg2/source/administrator-guide/configuring-the-catalog/inspire-configuration.rst). Mais que ce soit en configurant l'url à partir du bouton Use INSPIRE validator ou en copiant manuellement l'url de stagging, le message d'erreur est le même.
Peut-être que le problème vient plus de l'environnement de valid que de la config de metawal.

A suivre lors de la mise en prod.

**Comment by fxprunayre** [comment]
C'est quoi l'URL du site de valid ?

**Comment by stephyritz** [comment]
http://metawal4.valid.wallonie.be mais pas sûr que cela soit ouvert vers l’extérieur du spw, si ?

**Comment by fxprunayre** [comment]
non et du coup il faudrait vérifier que le serveur peut appeller le validateur via HTTP. C'est peut être bloqué aussi ?

**Comment by stephyritz** [comment]
D'accord ceci peut expliquer cela. Donc ça devrait fonctionner en prod. Si c'est le cas, je fermerai le ticket une fois le déploiement réalisé en prod et le test OK.

**Comment by stephyritz** [comment]
Le problème est malheuresement aussi présent dans l'environnement de production.

**Comment by fxprunayre** [comment]
http://metawal4.test.wallonie.be/geonetwork/proxy?url=http://inspire.ec.europa.eu/validator/v2/TestObjects

Mais en prod 

```
Etat HTTP 500 - inspire.ec.europa.eu: Name or service not known
type Rapport d''exception

message inspire.ec.europa.eu: Name or service not known

description Le serveur a rencontré une erreur interne qui l''a empêché de satisfaire la requête.

exception

java.net.UnknownHostException: inspire.ec.europa.eu: Name or service not known
	java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	java.net.InetAddress.getAllByName0(InetAddress.java:1276)
```

Problème à corriger sur le serveur ou firewall - laisser passer les flux HTTP sortant

**Comment by stephyritz** [comment]
Merci pour l'analyse, je transmets à Didier Husson (DTIC) pour correction.

**Comment by stephyritz** [comment]
Les explication de Didier : 
"ça va être plus compliqué que je pensais !
en test la machine est en DMZ (internet)
en valid/prod la machine est en intranet ! et exposée sur le net à travers un reverse proxy nginx placé lui, en DMZ
donc changer les serveurs de résolution dns ne sert à rien, à part faire planter metawal
il va falloir passer par un proxy internet pour ce type d'appels, qui sera défini par JAVA_OPTS..."

Maintenant cette requête fonctionne en prod --> http://metawal.wallonie.be/geonetwork/proxy?url=http://inspire.ec.europa.eu/validator/v2/TestObjects

Mais le bouton "valider" renvoie toujours la même erreur. Autre chose à paramétrer via l'interface ?

**Comment by stephyritz** [comment]
Des idées pour la résolution de ce problème ?

**Comment by fxprunayre** [comment]
Il y a eu un correctif dans GN 3.8.2 pour la validation avec passage par un proxy. Donc je propose de tester après le mise à jour. J'ai le même pb au BRGM et on va faire une mise à jour d'ici peu. Donc à déployer en valid pour vérification.

**Comment by stephyritz** [comment]
Problème toujours présent en prod après déploiement de la version 3.8.2

**Comment by stephyritz** [comment]
Pour reproduire : 
* http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/541e92de-dbc9-46df-880c-1076798bdbb3
* http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/541e92de-dbc9-46df-880c-1076798bdbb3

- S'identifier
- Passer en mode édition sur la fiche
- Lancer la validation via le bouton "cocher" en haut à droite entre 'groupe et 'annuler' puis 'validation INSPIRE TG2 dataset et series par exemple.

--> Message d'erreur 

![validation_inspire_error](https://user-images.githubusercontent.com/34446202/72792635-a35ffa00-3c39-11ea-8fb9-bff5b737f650.png)

Fonctionne en test mais pas en valid ni en prod.


Dans les logs
```

2020-01-21 10:33:05,348 DEBUG [org.springframework.orm.jpa.JpaTransactionManager] - Found thread-bound EntityManager [org.hibernate.jpa.internal.EntityManagerImpl@182e0d7e] for JPA transaction
2020-01-21 10:33:05,348 DEBUG [org.springframework.orm.jpa.JpaTransactionManager] - Participating in existing transaction
2020-01-21 10:33:05,360 WARN  [jeeves.service] - Error calling INSPIRE service: http://inspire.ec.europa.eu/validator/
java.net.UnknownHostException: inspire.ec.europa.eu: Name or service not known
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:111)
```

A tester:

Ajouter la configuration du proxy dans l'admin si proxy il y a :

![image](https://user-images.githubusercontent.com/1701393/72792323-1c128680-3c39-11ea-803c-1a829b3d229c.png)

**Comment by stephyritz** [comment]
La réponse de Didier :

> Pour le soucis des validations TG, je n'arrive pour l'instant pas à le résoudre !
> J'ai mis la config proxy en valid/prod, sans changement =(
> "Erreur de validation distante: Vérifier l'URL."
> 
> Geonetwork ne semble pas se servir du proxy défini au niveau des CATALINA_OPTS du tomcat...
> 

Peut-être qu'il faudrait quand même configurer le proxy dans l'admin de l'application alors ? Qu'en pensez-vous ?

**Comment by fxprunayre** [comment]
> Peut-être qu'il faudrait quand même configurer le proxy dans l'admin de l'application alors ? Qu'en pensez-vous ?

Pouvons nous avoir la config du proxy pour la faire dans l'admin ?

![image](https://user-images.githubusercontent.com/1701393/72877167-a1a93b80-3cf8-11ea-8437-f268a053a52d.png)

**Comment by stephyritz** [comment]
Héhé oui je pensais bien le demander mais je voulais d'abord avoir votre avis pour voir si ceci pourrait résoudre le problème. Notamment après la remarque de Didier.

**Comment by stephyritz** [comment]
Les paramètres fournis par Didier : 
host=webproxyappl.intra.wallonie.be
Port=3129 
pas de login/password
