### ISSUE TITLE
Edition / Suppression d'une ressource en ligne

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#480]
Lors de la suppression d'une ressource en ligne, le bouton "Annuler" est sans effet.

Plusieurs pistes pour répondre à cette problématique : 
a) Soit faire apparaître une popup informant l'utilisateur du fait qu'il ne pourra pas "revenir en arrière"
b) Intégrer l'annulation de la suppression d'une ressource en ligne dans le bouton "Annuler"

**Comment by fxprunayre** [comment]
> a) Soit faire apparaître une popup informant l'utilisateur du fait qu'il ne pourra pas "revenir en arrière"

Ajout d'une confirmation https://github.com/geonetwork/core-geonetwork/pull/4138
Ca convient @stephyritz ?

**Comment by stephyritz** [comment]
Très bien, merci.

**Comment by fxprunayre** [comment]
A déployer en test. Il manque la traduction en francais mais je m'en occupe dans transifex prochainement.
