### ISSUE TITLE
Identification / Saisie d'un mauvais mot de passe - Absence de message d'erreur 

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#481]
Un utilisateur souhaite se connecter mais saisi un mauvais mot de passe.

Comportement de l'application --> Chargement en continu comme si la page était en train de s'actualiser sans fin. Absence d'un message d'erreur.

Proposition de solution : Afficher une page avec "Mot de passe erroné" si c'est le cas.

**Comment by fxprunayre** [comment]
En lien avec les histoires de portails. A priori corrigé par https://github.com/geonetwork/core-geonetwork/pull/4140

**Comment by stephyritz** [comment]
Ok, super. Cela signifie donc que le problème sera corrigé sur Metawal lors de la prochaine release ?

**Comment by fxprunayre** [comment]
Je fais GN3.8.2 fin de semaine et ensuite j'aligne MW avec pour déploiement en test.

**Comment by fxprunayre** [comment]
Testé en local suite à l'alignement GN 3.8.2. Ca semble ok, il y a redirection vers http://localhost:8080/geonetwork/srv/fre/catalog.signin?node=srv&failure=true#/search

A déployer en test.

**Comment by stephyritz** [comment]
Attention, toujours non fonctionnel en prod à ce jour.

**Comment by fxprunayre** [comment]
Quelles sont les différences entre test et prod qui pourraient expliquer ça ?

**Comment by fxprunayre** [comment]
Pour reproduire;

* http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.signin
* http://metawal.wallonie.be/geonetwork/srv/fre/catalog.signin

Saisir un compte bidon

* sur test ok, redirection sur le même formulaire
* sur prod (et valid), pending sur la requête POST /signin

![image](https://user-images.githubusercontent.com/1701393/72791556-cd182180-3c37-11ea-97a3-e02306180be7.png)

Idem si on tente un basic auth avec Curl:


```shell

#export CATALOG=http://metawal4.test.wallonie.be/geonetwork/
export CATALOG=http://metawal.wallonie.be/geonetwork/
export CATALOGUSER=dada
export CATALOGPASS=dada


rm -f /tmp/cookie; 
curl -s -v -c /tmp/cookie -o /dev/null -X POST "$CATALOG/srv/eng/info?type=me"; 
export TOKEN=`grep XSRF-TOKEN /tmp/cookie | cut -f 7`; 
curl -X POST -H "X-XSRF-TOKEN: $TOKEN" --user $CATALOGUSER:$CATALOGPASS -b /tmp/cookie \
  "$CATALOG/srv/eng/info?type=me" 
```

**Comment by stephyritz** [comment]
Problème résolu à ce jour par le DTIC en modifiant la config des firewall.
