### ISSUE TITLE
Interface principale / Erreur 404 pour la page d'accueil

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#482]
En environnement de production, si un utilisateur clic sur la "maison" (homepage) pour revenir sur la page principale d'accueil, il tombe sur une erreur 404.

![issue_482](https://user-images.githubusercontent.com/34446202/66910674-45ef5800-f00f-11e9-92aa-63f553b45628.png)

Sans doute parce que le bouton "homepage" redirige vers http://metawal.wallonie.be/geonetwork/srv/**fr**/catalog.search#/home à la place de http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/home
Est-ce que j'ai la main pour modifier cela ?

**Comment by fxprunayre** [comment]
Fixed dans admin > settings > UI

![image](https://user-images.githubusercontent.com/1701393/66915363-22310f80-f019-11e9-9354-a05bb96a0c93.png)
