### ISSUE TITLE
INSPIRE / Conformité TG2 - Ajout du "SpatialDataServiceType"

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#483]
J'ai remarqué que nos fiches de MD de services concernées par INSPIRE (avec le keyword "Reporting INSPIRE") possèdent un défaut majeur de conformité : le type de service n'est pas indiqué selon ce qui est demandé.

En effet, le test s'appuie sur la recherche de la balise gmd:identificationInfo/srv:SV_ServiceIdentification/srv:serviceType/gco:LocalName et vérifie si la valeur correspond bien à une de celles présentes dans le registre (http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType). 

Dans notre cas (voir ex. http://metawal.wallonie.be/geonetwork/srv/fre/csw-inspire?request=GetRecordById&service=CSW&outputSchema=http://www.isotc211.org/2005/gmd&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=d7e8a2f1-8cb1-4e4c-9d36-74ca79a494aa), la balise est absente.

Pour l'instant, il semblerait que cette information soient présente en ISO19115-3 sous cette forme : 
```
         <srv:serviceType>
            <gco:ScopedName>view</gco:ScopedName>
         </srv:serviceType>

```
Solution proposée : 
Ajouter cette balise pour tous les services concernés par INSPIRE en s'appuyant sur le contenu de la balise "srv:serviceType". Par ex., 
Si 

```
         <srv:serviceType>
            <gco:ScopedName>view</gco:ScopedName>
         </srv:serviceType>
```

Alors
```
<srv:serviceType>
<gco:LocalName codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">view</gco:LocalName>
</srv:serviceType>

```

Qu'en pensez-vous ?

**Comment by fxprunayre** [comment]
serviceType manquant fixed by https://github.com/metadata101/iso19115-3.2018/commit/fd6eff97fd7e71b5a3a1099d02524d0a700c12b2

**Comment by fxprunayre** [comment]
Si on considére qu'il y a toujours une balise serviceType, on peut également faire du batch edit a priori.

![image](https://user-images.githubusercontent.com/1701393/67766598-13058500-fa4f-11e9-8f69-bcb376e23773.png)

```
.//srv:serviceType
```
On remplace par
```
<gco:ScopedName  xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0"
  codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">view</gco:ScopedName>
```

Si on doit contraindre pour les différents types `.//srv:serviceType[gco:ScopedName = 'view']`.

A tester et faire une sauvegarde avant d'appliquer au cas où. Je n'ai pas 100% confiance dans le batch edit mais ça semble bien fonctionner.

**Comment by fxprunayre** [comment]
A déployer en test pour le srv:serviceType manquant. @davinciagf 

A tester pour le batch edit sur la version actuelle @stephyritz

**Comment by stephyritz** [comment]
Batch edit fait en prod. Remplacement de la valeur contenu dans la balise srv:serviceType par par : 
`<gco:LocalName xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0" codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">download</gco:LocalName>`

Avec les valeurs view, download ou discovery en fonction du type de service.

Attention, il faut penser à modifier aussi la facette TYPE DE SERVICE pour faire en sorte qu'elle fasse appelle aux valeurs stockés dans la nouvelle balise.

Ne pas oublier de modifier aussi ces informations dans la transformation 19115-3 TO 19139.

**Comment by stephyritz** [comment]
Après discussion avec Arnaud ce matin au tel, je me suis rendu compte que je suis peut-être aller vite sur ce batch edit. Est-ce que la balise <gco:LocalName> est propre à l'ISO19139 ? Fallait-il garder le <gco:ScopedName> en ISO 19115-3 ? Je suppose que oui. @fxprunayre, si tu confirmes, je modifie les valeurs toujours via le batchedit. Vu la faible quantité de fiches, je pense que l'outil est fiable sur ce point.

**Comment by davinciagf** [comment]
On va introduire trois requêtes SQL pour faire la modif suite à la modif en batch:

Pour download:
`UPDATE metadata SET data = replace(data,'<gco:LocalName xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0" codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">download</gco:LocalName>','<gco:ScopedName xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0" codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">download</gco:ScopedName >')WHERE data LIKE '%<gco:LocalName xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0" codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">download</gco:LocalName>%';
`


Pour view:
`UPDATE metadata SET data = replace(data,'<gco:LocalName xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0" codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">view</gco:LocalName>','<gco:ScopedName xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0" codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">view</gco:ScopedName >')WHERE data LIKE '%<gco:LocalName xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0" codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">view</gco:LocalName>%';`


Pour discovery
`UPDATE metadata SET data = replace(data,'<gco:LocalName xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0" codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">discovery</gco:LocalName>','<gco:ScopedName xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0" codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">discovery</gco:ScopedName >')WHERE data LIKE '%<gco:LocalName xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0" codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">discovery</gco:LocalName>%';`


De plus on va modifier le xslt pour le passage en 39 afin de récupérer le codeSpace dans la balise en 39 en plus de la valeur discovery ou view ou download

**Comment by stephyritz** [comment]
Ok merci. Donc cela reste bien ScopedName en 115-3. Sorry.

**Comment by stephyritz** [comment]
Est-ce que ce script a été joué en test ? De même pour la modif du xslt ?
Comme évoqué au téléphone, j'envisageais de demander à Didier Husson de mettre à jour le xslt avant la mise en prod du 28 novembre afin de corriger ce problème majeur au plus vite. En effet, c'est une source de "mauvais résultat" général sur le harvesting et bloquant pour certains tests. Donc, ce problème peut potentiellement en cacher d'autres plus spécifiques. Afin de gagner le plus de temps possible, j'aurais donc souhaiter, si possible, faire le changement évoqué dans cette issue + mise à jour du xslt en prod avant la deadline du 28 novembre. A priori, cela ne demande pas un gros travail au niveau du DTIC et nous sommes prêts à fournir les fichiers nécessaires de notre côté, non ? Qu'en pensez-vous ?

**Comment by davinciagf** [comment]
En test, il n'est pas nécessaire car je pense que tu n'a pas modifié les fiches via le batch edit. Par contre, on peut refaire jouer le sql afin d'avoir le ScopedName intégrer dans la transformation du 115-3 vers le 39.

**Comment by stephyritz** [comment]
Oui pas ce script exactement mais il est tout de même nécessaire de modifier la valeur de la balise pour que cela soit conforme. Je m'en occupe en batch edit.
Quid du xslt ? Le nouveau est-il opérationnel en test ? Est-ce qu'on peut le transmettre à Didier Husson pour qu'il puisse le déployer en prod dès la semaine prochaine ?

**Comment by davinciagf** [comment]
Je dois encore pousser le xslt et puis je ferai un update de l'env de test. Si c'est ok, je te communique les xslt.

**Comment by davinciagf** [comment]
Xslt poussé en test. A vérifier après l'utilisation du batch

**Comment by stephyritz** [comment]
Ok, super. Avec le nouveau xslt, les outils de validation INSPIRE arrive à interpréter le type de service. ; )
Seul petit défaut encore présent, la valeur n'est pas tout à fait la même en 19115-3 et 19139.
Par exemple, pour la fiche suivante : http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/74fe32b4-09b2-4ade-9b3b-373c7877eeae 

En 19115-3 : 
```
<srv:serviceType>
     <gco:ScopedName codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">view</gco:ScopedName>
</srv:serviceType>
```

En 19139 (http://metawal4.test.wallonie.be/geonetwork/srv/fre/csw?request=GetRecordById&service=CSW&outputSchema=http://www.isotc211.org/2005/gmd&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=74fe32b4-09b2-4ade-9b3b-373c7877eeae) : 
```
<srv:serviceType>
     <gco:LocalName>view</gco:LocalName>
</srv:serviceType>

```

**Comment by fxprunayre** [comment]
Fait dans https://github.com/SPW-DIG/iso19115-3.2018/commit/f7400e8ca04fd5ec0549fa4e9945667f5a4d75b0 et metadata101

**Comment by stephyritz** [comment]
NOK en environnement de valid.
Exemple : 
- test --> `<srv:serviceType><gco:LocalName codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">discovery</gco:LocalName></srv:serviceType>`
http://metawal4.test.wallonie.be/geonetwork/srv/fre/csw-inspire?request=GetRecordById&service=CSW&outputSchema=http://www.isotc211.org/2005/gmd&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=d2e9a58f-8c03-4302-9aa3-a0db3da0b821

- valid --> `<srv:serviceType><gco:LocalName>discovery</gco:LocalName></srv:serviceType>`

http://metawal4.valid.wallonie.be/geonetwork/srv/fre/csw-inspire?request=GetRecordById&service=CSW&outputSchema=http://www.isotc211.org/2005/gmd&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=d2e9a58f-8c03-4302-9aa3-a0db3da0b821

**Comment by davinciagf** [comment]
Attention la règle ne fait que recopier le codeSpace si ce dernier existe en 115-3. La fiche d'exemple ne  contient pas de codeSpace en version 115-3.
==> besoin d'introduire le codeSpace au niveau du 115-3 via SQL ou batch pour ensemble des fiches sans codeSpace'?

**Comment by stephyritz** [comment]
Bien vu, j'avais fait la modif via le batchedit en test et en prod mais pas en valid.

**Comment by stephyritz** [comment]
Actions à faire pour la prochaine release : utilisation du dernier xsl "to19139" pour la config (celui actuellement en environnement de test = celui transformant la balise scopedname en localname) et action en DB pour mettre à jour les valeurs (remplacement de localname en scopedname).

> On va introduire trois requêtes SQL pour faire la modif suite à la modif en batch:
> 
> Pour download:
> UPDATE metadata SET data = replace(data,'<gco:LocalName xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0" codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">download</gco:LocalName>','<gco:ScopedName xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0" codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">download</gco:ScopedName >')WHERE data LIKE '%<gco:LocalName xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0" codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">download</gco:LocalName>%';
> 
> Pour view:
> UPDATE metadata SET data = replace(data,'<gco:LocalName xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0" codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">view</gco:LocalName>','<gco:ScopedName xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0" codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">view</gco:ScopedName >')WHERE data LIKE '%<gco:LocalName xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0" codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">view</gco:LocalName>%';
> 
> Pour discovery
> UPDATE metadata SET data = replace(data,'<gco:LocalName xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0" codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">discovery</gco:LocalName>','<gco:ScopedName xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0" codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">discovery</gco:ScopedName >')WHERE data LIKE '%<gco:LocalName xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0" codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">discovery</gco:LocalName>%';
> 
> De plus on va modifier le xslt pour le passage en 39 afin de récupérer le codeSpace dans la balise en 39 en plus de la valeur discovery ou view ou download
>

**Comment by stephyritz** [comment]
Ce problème est quand même assez gênant parce que les services non INSPIRE sont encore encodés sous la forme de scopedname en prod. Et donc la conversion to19139 ne se fait pas correctement dans ces cas-là. Exemple : http://metawal.wallonie.be/geonetwork/srv/fre/csw?request=GetRecordById&service=CSW&outputSchema=http://www.isotc211.org/2005/gmd&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=ac455ccd-39df-455d-826c-e5e72900ccae

La conséquence sur le Géoportail est l'absence du lien vers le service dans la fiche de MD de service car la règle NSI s'appuye sur les valeurs renseignées dans le servicetype.

![fiche_service_NOK](https://user-images.githubusercontent.com/34446202/71244442-cdf52500-2312-11ea-98f5-22997d2a6cff.png)

Il faudrait donc bien penser à modifier les données en DB pour que les services INSPIRE soiet encodés sous la forme scopedname ET modifier le xsl to139 pour transformer le scopedname en localname.

Peut-être que nous ferons cette manip au cours d'un "petit déploiement" avant le passage à la version 4.0 afin de corriger cela et le reste des issues initialement prévues en 3.8.2.

**Comment by davinciagf** [comment]
Actuellement en 39 et en 115-3
![Screen Shot 2020-01-21 at 14 37 08](https://user-images.githubusercontent.com/576292/72809542-1ed2a300-3c5c-11ea-929f-6651c0e99cc1.png)

A modifier:  
- Mettre 'scopedName' à la place du 'localname' en 115-3 
- Vérifier que la transformation en 39 modifie 'scopedName' en 'localname' pour le validateur INSPIRE.

**Comment by davinciagf** [comment]
Ok pour la règle de transformation au niveau du xsl de conversion vers le 39
==> Vérifier que les MTD soient bien référencées en 'scopedName'

UPDATE metadata SET data = replace(data,'<gco:LocalName codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">discovery</gco:LocalName>','<gco:ScopedName xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0" codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">discovery</gco:ScopedName >')WHERE data LIKE '%<gco:LocalName codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">discovery</gco:LocalName>%';

UPDATE metadata SET data = replace(data,'<gco:LocalName codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">view</gco:LocalName>','<gco:ScopedName xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0" codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">view</gco:ScopedName >')WHERE data LIKE '%<gco:LocalName codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">view</gco:LocalName>%';

UPDATE metadata SET data = replace(data,'<gco:LocalName codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">download</gco:LocalName>','<gco:ScopedName xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0" codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">download</gco:ScopedName >')WHERE data LIKE '%<gco:LocalName codeSpace="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType">download</gco:LocalName>%';
