### ISSUE TITLE
INSPIRE / Erreur schéma fiche de service

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#484]
J'ai l'impression que pour toutes les fiches de services, il y a une balise 
`<srv:containsOperations/>`
qui est isolée dans la rubrique gmd:identificationInfo/srv:SV_ServiceIdentification
Je pense que cela cause une erreur de conformité vis à vis du schéma.

Est-ce lié à un problème dans le contenu des fiches ?Ou bien lié à la transcription de ISO19115-3 vers 19139 ?

Exemple :
http://metawal.wallonie.be/geonetwork/srv/fre/csw-inspire?request=GetRecordById&service=CSW&outputSchema=http://www.isotc211.org/2005/gmd&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=0beee14d-aa34-46ba-9f43-de5cf2308b53

**Comment by fxprunayre** [comment]
Pb de conversion. Same as https://github.com/SPW-DIG/metawal-core-geonetwork/issues/483#issuecomment-547387886

**Comment by fxprunayre** [comment]
A déployer en test.
