### ISSUE TITLE
CSW / Requête usuelle du Géoportail en erreur

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#485]
L'équipe Geoportail (NSI) s'appuie sur une requête spécifique pour alimenter le catalogue actuellement sous Jahia. Cette requête ne fonctionne apparemment plus depuis la dernière mise en production de Metawal (GN 3.8). Pour autant, le service CSW ne semble pas en erreur car mes requêtes habituelles continuent de tourner.

Voici la requête qu'ils utilisent : 
http://metawal.wallonie.be/geonetwork/srv/en/csw?REQUEST=GetRecords&SERVICE=CSW&VERSION=2.0.2&OUTPUTSCHEMA=http://www.isotc211.org/2005/gmd&CONSTRAINTLANGUAGE=CQL_TEXT&RESULTTYPE=results&TYPENAMES=csw:Record&STARTPOSITION=1&MAXRECORDS=1&ELEMENTSETNAME=full

Ils reçoivent un message d'erreur 404 en réponse.

J'imagine qu'il y a un problème dans leurs paramètres. Est-ce que vous pouvez m'éclaircir sur ce qui ne va pas dans ce cas ? Peut-être existe-t-il une requête plus adaptée pour leur besoin ?

**Comment by fxprunayre** [comment]
Il faut remplacer "en" par "eng" - la redirection a été supprimée. Les codes à 2 lettres étaient utilisés dans GN2.x.

eg. http://metawal.wallonie.be/geonetwork/srv/eng/csw?REQUEST=GetRecords&SERVICE=CSW&VERSION=2.0.2&OUTPUTSCHEMA=http://www.isotc211.org/2005/gmd&CONSTRAINTLANGUAGE=CQL_TEXT&RESULTTYPE=results&TYPENAMES=csw:Record&STARTPOSITION=1&MAXRECORDS=1&ELEMENTSETNAME=full

Est-ce que l'on peut changer ça dans l'admin jahia ? ou faut-il remettre en place la redirection.

**Comment by stephyritz** [comment]
Merci! Je leur signale le problème dans leur requête. Je trouve cela plus logique qu'il modifie de leur côté. Si jamais ils ont des difficultés à faire cela, on agira pour faire la redirection.
