### ISSUE TITLE
Edition en DB / Possibilité de ne pas modifier la date de mise à jour de la fiche 

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#486]
La date de mise à jour de la fiche conditionne la priorité d'affichage sur le catalogue, et ce, afin de mettre en avant les données diffusées les plus récemment. 

Lors de changements de valeurs par lot en DB (par exemple pour s'adapter au TG2 d'INSPIRE), cette date est automatiquement modifiée. Cette modification, d'ordre technique, perturbe alors la priorité d’affichage sur le catalogue. 

L'idée serait d'offrir la possibilité, via un paramètre, de modifier ou non cette valeur en fonction des changements par lot que nous souhaitons apporter. Ce paramètre pourrait être mobilisé aussi bien lors de modifications faites via le CSW-T que de modifications apportées en DB via un script SQL.

**Comment by fxprunayre** [comment]
Cf. https://github.com/geonetwork/core-geonetwork/pull/4159 pour l'API `/process`

Pour le CSW-T, c'est au client envoyant la fiche de mettre à jour ou pas le datestamp.

**Comment by fxprunayre** [comment]
A déployer et tester.

**Comment by davinciagf** [comment]
Disponible au niveau de l'API pour les process, lorsque l'on lance un process il suffit d'introduire le paramètre suivant dans la requête : updateDateStamp=false

`CATALOGURL/srv/api/0.1/processes/PROCESSNAME?bucket=ID&updateDateStamp=false...`

A tester lors de la mise à jour des contraintes: mw-constraints-cleanup

**Comment by davinciagf** [comment]
Modification joué en test : mw-constraints-cleanup - Sans modification des dates de mise à jour des MTD en date du 2019-11-14
