### ISSUE TITLE
Affichage / Intérprétation des Atom-feed

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#487]
Actuellement GN permet d'interpréter le contenu d'un atom-feed de la manière suivante : 
Il propose dans une liste déroulante permettant de choisir un layer parmi ceux présents dans l'atom-feed service. Ensuite il va chercher le fichier média pour fournir un lien de téléchargement direct.
C'est vraiment une super fonctionnalité très adaptée à ce cas de figure : 
fiche de MD : http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/541e92de-dbc9-46df-880c-1076798bdbb3
atom feed service : https://geoservices.wallonie.be/inspire/atom/PS_Service.xml
atom feed dataset : https://geoservices.wallonie.be/inspire/atom/PS_Dataset_541e92de-dbc9-46df-880c-1076798bdbb3.xml

Par contre, cela se complexifie quand on veut utiliser l'atom feed pour fournir des données dans un système de projection différents ou avec un découpage particulier. Mon collègue a suivi les prescriptions INSPIRE pour construire, par exemple cet atom feed qui propose plusieurs fichiers en téléchargements en fonction de découpages administratifs: https://geoservices.wallonie.be/inspire/atom/BU_Dataset_b795de68-726c-4bdf-a62a-a42686aa5b6f.xml

Dans ce cas de figure, GN va interpréter l'atom de la même manière que ci-dessus mais ne va proposer que le premier média qu'il va trouver (en l’occurrence ici pour l'exemple, le shape avec découpage sur la province du Brabant Wallon) : http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/10527f45-fee3-4ff6-8188-611b39b6517a 

Est-ce que tu penses qu'il est possible de travailler sur l'affichage du contenu d'un atom feed tel que celui donné dans cet exemple ? Pour que, par exemple, il y ait une liste déroulant supplémentaire avec le format et/ou la projection ?

Apparemment on peut jouer sur les sections/alternate/entrée d'après mon collègue. A voir comment on peut travailler de notre côté pour à la fois respecter INSPIRE et faire en sorte que la majorité du contenu de l'atom soit mise en avant dans GN.

Ce n'est pas prioritaire mais cela pourrait être un chouette développement à pousser lorsque GN remplacera le catalogue Jahia.

**Comment by fxprunayre** [comment]
Première question, si 
```xml
               <mrd:onLine>
                  <cit:CI_OnlineResource>
                     <cit:linkage>
                        <gco:CharacterString>https://geoservices.wallonie.be/inspire/atom/BU_Service.xml</gco:CharacterString>
                     </cit:linkage>
                     <cit:protocol>
                        <gco:CharacterString>atom:feed</gco:CharacterString>
                     </cit:protocol>
                     <cit:name>
                        <gco:CharacterString>INSPIRE Bâtiments - Service de téléchargement</gco:CharacterString>
                     </cit:name>
                     <cit:description>
                        <gco:CharacterString>Adresse de connexion au service de téléchargement ATOM Feed des couches de données du thème "Bâtiments".</gco:CharacterString>
                     </cit:description>
                     <cit:function>
                        <cit:CI_OnLineFunctionCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_OnLineFunctionCode"
                                                   codeListValue="download"/>
                     </cit:function>
                  </cit:CI_OnlineResource>
               </mrd:onLine>
```
est une manière d'encoder les flux atom, peut être nous devrions l'ajouter dans la liste ? "Download from ATOM feed" ?

![image](https://user-images.githubusercontent.com/1701393/69621490-80e9a000-103f-11ea-99b8-047f688730bc.png)

**Comment by stephyritz** [comment]
Oui, je suis d'accord. Par habitude et selon ce que m'avais transmis Geoffroy, je passais toujours par l'onglet distribution en vue complète. Puis j'encodais en prenant une fiche existante pour exemple. Cela serait déjà un bon premier pas de le rajouter dans la liste déroulante que tu évoques.

**Comment by fxprunayre** [comment]
* Support de multiple liens cf. https://github.com/geonetwork/core-geonetwork/pull/4216
* Config éditeur 115-3 cf. https://github.com/metadata101/iso19115-3.2018/commit/0c632328e2b836dad16fd8dd3731ea239bccbe97

A merger prochainement.

Pour créer les ATOM feeds vous utilisez quoi ? A la main ? Pour info, on peut utiliser GeoNetwork pour ça - par exemple: https://catalog.inspire.geoportail.lu/geonetwork/ - bon en 115-3 ca marche pas mais ce serait pas très compliqué.

**Comment by stephyritz** [comment]
Ok, merci. Les ATOM feeds sont générés via FME chez nous. De ce que me dit Dominique (collègue en charge de ces questions), cela nous permet aussi de proposer en téléchargements diverses options comme la sélection particulière de couches de données avec "multipart" (découpage selon province par ex.), formats et systèmes de projections. Je crois que c'est justement cette "finesse" là dont qu'il serait intéressant de mobiliser dans la liste déroulante proposée sur l'interface de vis d'une fiche sur GN.

**Comment by fxprunayre** [comment]
Corrigé en test http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/10527f45-fee3-4ff6-8188-611b39b6517a
![image](https://user-images.githubusercontent.com/1701393/72808947-f39b8400-3c5a-11ea-93fa-a7a49ab4dea8.png)

A voir pourquoi des doublons dans les flux view-source:https://geoservices.wallonie.be/inspire/atom/BU_Dataset_b795de68-726c-4bdf-a62a-a42686aa5b6f.xml

**Comment by davinciagf** [comment]
Actuellement en 39 et en 115-3
![Screen Shot 2020-01-21 at 14 37 08](https://user-images.githubusercontent.com/576292/72809542-1ed2a300-3c5c-11ea-929f-6651c0e99cc1.png)

A modifier en scopedName à la place du localname
