### ISSUE TITLE
INSPIRE / Doublons - Problème d'indexation ?

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#488]
Les informations concernant "no limitations on public access" apparaissent en double sur l'interface d'affichage par défaut dans les fiches de datasets concernées par INSPIRE. Pourtant ce n'est pas le cas dans le xml. Par exemple : http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/ffc45d44-1cc2-4924-bb8c-214096eb9058 
Est-ce un problème lié à l'indexation ?

**Comment by fxprunayre** [comment]
Ca doit être bon. A déployer et tester
