### ISSUE TITLE
INSPIRE / Degré de conformité

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#489]
Les données concernées par INSPIRE peuvent se retrouver dans 3 cas différents vis à vis du degré de conformité :
1.	Donnée testée ET conforme 
2.	Donnée testée ET non conforme 
3.	Donnée non testée 

D'après les TG2 et les éléments testés dans l'outil de validation, voici les trois manières de déclarer les cas ci-dessus : 
1. --> /gmd:MD_Metadata/gmd:dataQualityInfo/gmd:DQ_DataQuality/gmd:report/ gmd:DQ_DomainConsistency/gmd:result/gmd:DQ_ConformanceResult/gmd:pass `<gco:Boolean>true</gco:Boolean>`
2. --> /gmd:MD_Metadata/gmd:dataQualityInfo/gmd:DQ_DataQuality/gmd:report/ gmd:DQ_DomainConsistency/gmd:result/gmd:DQ_ConformanceResult/gmd:pass `<gco:Boolean>false</gco:Boolean>`
3. /gmd:MD_Metadata/gmd:dataQualityInfo/gmd:DQ_DataQuality/gmd:report/ gmd:DQ_DomainConsistency/gmd:result/gmd:DQ_ConformanceResult/ `<gmd:pass gco:nilReason="unknown"/>`

Actuellement dans Metawal, les fiches ont été renseignées seulement en prenant en compte les cas 1. et 2.. Cela ne pose pas de problème de conformité aux TG2 mais l'information donnée n'est pas tout à fait exacte. C'est pourquoi je ne considère pas ce ticket comme urgent.

- [ ] De mon côté, il faudrait que j'identifie les fiches de toutes les données qui sont dans le cas 3. afin de faire une modification en batch depuis l'interface.

- [ ] De votre côté, l'idéal serait d'imaginer une évolution de l'interface afin de la faire correspondre aux trois façons de décrire la conformité d'une donnée.

**Comment by stephyritz** [comment]
Développement à faire en prenant en compte le registre adéquat : http://inspire.ec.europa.eu/metadata-codelist/DegreeOfConformity
Pour l'instant non indiqué dans les TG2 mais sûrement une recommandation technique en devenir. A suivre.

**Comment by fxprunayre** [comment]
- [x] Ajouter facette sur la validation INSPIRE et ajout du dernier statuts dans le menu de l'éditeur https://github.com/geonetwork/core-geonetwork/pull/4388 

- [ ] Gérer le cas nilReason https://github.com/geonetwork/core-geonetwork/pull/3569

- [ ] Lors de la validation INSPIRE, ajuster la conformité selon le résultat du validateur

**Comment by fxprunayre** [comment]
Je propose de laisser en l'état pour le moment ie. en vue avancée, si aucune conformité:
* pour les datasets

![image](https://user-images.githubusercontent.com/1701393/73270067-4d152d00-41de-11ea-8edf-c8cd73ac98cf.png)


* pour les services

![image](https://user-images.githubusercontent.com/1701393/73270080-51d9e100-41de-11ea-9158-28a5be5b096a.png)

@stephyritz Ca te convient ?

Eventuellement on peut ajouter un 3ème bouton avec une liste des TG pour les datasets. Si tu as un exemple ce serait bien? Libellé en anglais ou en francais eg. "INSPIRE Data Specification on Administrative Units - Guidelines v3.0.1"

**Comment by stephyritz** [comment]
Oui c'est très bien ainsi. Gain de temps assuré pour l'encodeur! ; )

> Eventuellement on peut ajouter un 3ème bouton avec une liste des TG pour les datasets. Si tu as un exemple ce serait bien?


Un exemple de data conforme pour laquelle il faut faire référence à des TG pour la data conformity ? --> http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/eed22735-0947-4e2d-8de9-b9cfbf492c80

**Comment by fxprunayre** [comment]
Pour les data specs, est-ce qu'on peut partir sur le principe qu'on ne l'indique que si elle est conforme ? Pour n'avoir qu'un choix par spec dans le menu (et pas 3 conforme/non conforme/non évalué) ?

**Comment by fxprunayre** [comment]
![image](https://user-images.githubusercontent.com/1701393/73430384-37b71480-433e-11ea-8844-20f300f02861.png)

**Comment by stephyritz** [comment]
Oui. Super! Au pire, il faudra aller décocher la cas ensuite, cela sera tout de même plus facile pour l'encodeur.

**Comment by stephyritz** [comment]
Semble ne pas être déployé en test à l'heure actuelle.

**Comment by davinciagf** [comment]
Il faut intégrer la référence sur la spec. 

> Règlement (CE) n o 976/2009 de la Commission du 19 octobre 2009 portant modalités d’application de la directive 2007/2/CE du Parlement européen et du Conseil en ce qui concerne les services en réseau

Puis refresh de la vue.

**Comment by stephyritz** [comment]
OK j'imagine que tu veux plutôt dire qu'il faut d'abord renseigner la confomité de la donnée vis à vis du texte 

> RÈGLEMENT (UE) N o 1089/2010 DE LA COMMISSION du 23 novembre 2010 portant modalités d'application de la directive 2007/2/CE du Parlement européen et du Conseil en ce qui concerne l'interopérabilité des séries et des services de données géographiques

Et seulement ensuite le bouton concernant la conformité des données apparaît.

**Comment by fxprunayre** [comment]
> Et seulement ensuite le bouton concernant la conformité des données apparaît.

Les boutons sont affichés si:
* une section qualité est présente
* une conformité de leur type n'a pas déjà été saisie.

C'est peut être le premier point qui vous manque ? Vous avez une fiche sans qualité ?

**Comment by stephyritz** [comment]
Ok c'est clair ainsi. Cela fonctionne depuis que cela a été déployé.
