### ISSUE TITLE
Page d'accueil : mise en page peu ergonomique

### ISSUE THREAD

**Issue by metawal** [SPW-DIG/metawal-core-geonetwork#49]
Sur la page d'accueil, on aurait envie de voir la zone dédiée à la recherche au centre de l'écran. Pour l'instant, elle est placée à gauche et n'est visuellement pas très claire.

La zone "Liens rapides" correspond en fait à un filtre sur les résultats et devrait, dès lors, être intégrée à la zone de recherche.

On aurait alors deux grands espaces sur la page d'accueil : "Rechercher" et "Dernières publications".

**Comment by fxprunayre** [comment]
Fait en v4.
