### ISSUE TITLE
INSPIRE / Conformité TG2 - Edition en série mail de contact

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#490]
La majorité des fiches renseignent sur des données dont le SPW est propriétaire. Pour le moment, il n'y a pas de mail de contact générique associé à l'organisme "Service public de Wallonie (SPW)".
Ceci est problématique du point de vue d'INSPIRE d'après la console d'harvesting mis à disposition par la CE.

Proposition :
Ajout systématique du mail 'helpdesk.carto@spw.wallonie.be' à l'organisme 'Service public de Wallonie (SPW)'. Possibilité de le faire en DB ou en édition en série. Je privilégierais la première car plus fiable (pas de problème de timeout) même si cela présente le désavantage de devoir faire appel au DTIC. Qu'en pensez vous ?

**Comment by davinciagf** [comment]
Requête SQL à jouer (à introduire dans le sql de migration):
`UPDATE metadata SET data = replace(data, '<gmd:pointOfContact><gmd:CI_ResponsibleParty><gmd:organisationName><gco:CharacterString>Service public de Wallonie (SPW)</gco:CharacterString></gmd:organisationName><gmd:contactInfo><gmd:CI_Contact><gmd:address><gmd:CI_Address/></gmd:address><gmd:onlineResource><gmd:CI_OnlineResource><gmd:linkage><gmd:URL>https://geoportail.wallonie.be</gmd:URL></gmd:linkage><gmd:protocol><gco:CharacterString>WWW:LINK-1.0-http--link</gco:CharacterString></gmd:protocol><gmd:name><gco:CharacterString>Géoportail de la Wallonie</gco:CharacterString></gmd:name><gmd:description><gco:CharacterString>Géoportail de la Wallonie</gco:CharacterString></gmd:description><gmd:function><gmd:CI_OnLineFunctionCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_OnLineFunctionCode" codeListValue="information"/></gmd:function></gmd:CI_OnlineResource></gmd:onlineResource></gmd:CI_Contact></gmd:contactInfo><gmd:role><gmd:CI_RoleCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_RoleCode" codeListValue="owner">owner</gmd:CI_RoleCode></gmd:role></gmd:CI_ResponsibleParty></gmd:pointOfContact>', '<gmd:pointOfContact><gmd:CI_ResponsibleParty><gmd:organisationName><gco:CharacterString>Service public de Wallonie (SPW)</gco:CharacterString></gmd:organisationName><gmd:contactInfo><gmd:CI_Contact><gmd:address><gmd:CI_Address><gmd:electronicMailAddress><gco:CharacterString>helpdesk.carto@spw.wallonie.be</gco:CharacterString></gmd:electronicMailAddress></gmd:CI_Address></gmd:address><gmd:onlineResource><gmd:CI_OnlineResource><gmd:linkage><gmd:URL>https://geoportail.wallonie.be</gmd:URL></gmd:linkage><gmd:protocol><gco:CharacterString>WWW:LINK-1.0-http--link</gco:CharacterString></gmd:protocol><gmd:name><gco:CharacterString>Géoportail de la Wallonie</gco:CharacterString></gmd:name><gmd:description><gco:CharacterString>Géoportail de la Wallonie</gco:CharacterString></gmd:description><gmd:function><gmd:CI_OnLineFunctionCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_OnLineFunctionCode" codeListValue="information"/></gmd:function></gmd:CI_OnlineResource></gmd:onlineResource></gmd:CI_Contact></gmd:contactInfo><gmd:role><gmd:CI_RoleCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_RoleCode" codeListValue="owner">owner</gmd:CI_RoleCode></gmd:role></gmd:CI_ResponsibleParty></gmd:pointOfContact>') WHERE data LIKE '%<gmd:pointOfContact><gmd:CI_ResponsibleParty><gmd:organisationName><gco:CharacterString>Service public de Wallonie (SPW)</gco:CharacterString></gmd:organisationName><gmd:contactInfo><gmd:CI_Contact><gmd:address><gmd:CI_Address/></gmd:address><gmd:onlineResource><gmd:CI_OnlineResource><gmd:linkage><gmd:URL>https://geoportail.wallonie.be</gmd:URL></gmd:linkage><gmd:protocol><gco:CharacterString>WWW:LINK-1.0-http--link</gco:CharacterString></gmd:protocol><gmd:name><gco:CharacterString>Géoportail de la Wallonie</gco:CharacterString></gmd:name><gmd:description><gco:CharacterString>Géoportail de la Wallonie</gco:CharacterString></gmd:description><gmd:function><gmd:CI_OnLineFunctionCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_OnLineFunctionCode" codeListValue="information"/></gmd:function></gmd:CI_OnlineResource></gmd:onlineResource></gmd:CI_Contact></gmd:contactInfo><gmd:role><gmd:CI_RoleCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_RoleCode" codeListValue="owner">owner</gmd:CI_RoleCode></gmd:role></gmd:CI_ResponsibleParty></gmd:pointOfContact>%';`

**Comment by fxprunayre** [comment]
Fait via XSL https://github.com/SPW-DIG/iso19115-3.2018/commit/93af4a6767be44f75cc355de3585d5966bd2ba5c (en DB les espaces et retours à la ligne font que ce n'est pas bien possible via SQL) lors des corrections sur les contraintes.

**Comment by davinciagf** [comment]
Intégré dans l'env de test et joué

**Comment by stephyritz** [comment]
Sera joué en valid puis en prod en amont du déploiement du WAR afin de, si besoin, résoudre d'autres problèmes annexes lors de la release du 28/11.
