### ISSUE TITLE
ISO19139 / Keyword InfraSIG

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#491]
Depuis le 12/10/19 (date de la dernière release), il semblerait que, la référence aux "Mots-clés InfraSIG" soit différente selon les fiches. 
En effet, dans certains cas le titre du thesarus est décrit en CharacterString de la manière suivante : 

```
<gmd:title>
<gco:CharacterString>Mots-clés InfraSIG</gco:CharacterString>
</gmd:title>
```

Exemple : http://metawal.wallonie.be/geonetwork/srv/fre/csw?request=GetRecordById&service=CSW&outputSchema=http://www.isotc211.org/2005/gmd&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=647e383d-c74b-4ee6-bf48-a5ebc746e8bf

Dans d'autres cas, il est lié à une ancre : 

```
<gmd:title>
<gmx:Anchor xlink:href="http://metawal.wallonie.be/thesaurus/infrasig#">Mots-clés InfraSIG</gmx:Anchor>
</gmd:title>
```
Exemple : http://metawal.wallonie.be/geonetwork/srv/fre/csw?request=GetRecordById&service=CSW&outputSchema=http://www.isotc211.org/2005/gmd&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=b795de68-726c-4bdf-a62a-a42686aa5b6f

Ceci est vraiment problématique car des process FME s'appuie sur une recherche textuelle sur bas de cette information pour, par exemple les procédures de download. Donc toute une partie des query sont rejetés à cause de cette manière hétérogène de déclarer le thesaurus.

Je ne comprends pas trop car dans le premier cas, le thesaurus est pourtant déclaré en ancre en ISO 19115-3. Problème dans la conversion ? Des idées sur la cause ?

**Comment by fxprunayre** [comment]
Euh, dans les 2 URLs on a bien une Anchor en 19115-3 et en sortie 19139 du CSW.

Est-ce qu'on peut imaginer mettre une `*` dans le process FME ? `...../gmd:title/*/text()` ?

**Comment by stephyritz** [comment]
?? Je ne comprends pas là. Hier, ce n'était pas le cas et,ce depuis le 12/10 car c'était la cause d'échecs de query FME. Bizarre. Bon, tant mieux si c'est réglé. Je vais vérifier si toutes les références aux mots-clés InfraSIG sont sous formes d'ancre. 

>  Est-ce qu'on peut imaginer mettre une * dans le process FME ? ...../gmd:title/*/text() ?

Je vais voir si on ne peut pas effectivement améliorer les requêtes. Le but ici c'est de chercher la valeur "Open data" au sein des mot-clés issus du thesaurus InfraSIG. * permettrait de s'affranchir du fait que la déclaration soit sous forme d'ancre ou de charstr.

**Comment by stephyritz** [comment]
Exemple valable ce matin --> http://metawal.wallonie.be/geonetwork/srv/fre/csw?request=GetRecordById&service=CSW&outputSchema=http://www.isotc211.org/2005/gmd&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=6f924476-d62c-4f1c-bc9a-03e1d9f06424

**Comment by stephyritz** [comment]
Je ne sais pas ce qu'il s'est passé mais, pour une même donnée, le PICC, il y a une différence entre l'environnement de test (sans ancre) et celui de prod (avec ancre) : 
http://metawal4.test.wallonie.be/geonetwork/srv/fre/csw?request=GetRecordById&service=CSW&outputSchema=http://www.isotc211.org/2005/gmd&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=b795de68-726c-4bdf-a62a-a42686aa5b6f 

http://metawal.wallonie.be/geonetwork/srv/fre/csw?request=GetRecordById&service=CSW&outputSchema=http://www.isotc211.org/2005/gmd&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=b795de68-726c-4bdf-a62a-a42686aa5b6f 

Cependant il est sous forme d'ancre dans les deux environnements en ISO 19115-3. Donc, il semblerait probable que cela vienne du xsl de conversion 19139 to 191153.

Mais il est aussi très étonnant de voir, qu'en prod, il y ait de l'hétérogénéité parmi les fiches.

**Comment by fxprunayre** [comment]
* Edition / Configurer pour utiliser Anchor pour INSPIRE Theme, priority dataset par défaut.
* Correction en db des cas hétérogènes

**Comment by davinciagf** [comment]
- Pour l'édition: ajout d'ancre via PR: https://github.com/metadata101/iso19115-3.2018/pull/28  (Correction en DB à réaliser au préalable afin que la mise à jour d'un kyeword se fasse dans un template de type anchor)
- Pour la correction en DB : voir #500
