### ISSUE TITLE
Interface / Présentation des contraintes légales

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#492]
Suite au déploiement de GN 3.8.2 en environnement de test et à l'adaptation du mode de déclaration des conditions d'accès et d'utilisation afin d'être TG2 complient, il apparaît que l'affichage des informations sur  la fiche n'est pas optimal. Voir ci-dessous : 

![mw_affichage_CA_CU](https://user-images.githubusercontent.com/34446202/69328219-21f6e600-0c4f-11ea-9fdf-87dd937517e0.png)

Je propose, si possible, de ne pas faire apparaître, dans Metawal, le deux éléments que j'ai barrés ci-dessus.

**Comment by stephyritz** [comment]
Vu que la séparation des contraintes liées à l'accès et à l'utilisation (CGA, CGU, CPA et CPU) dans des balises distinctes a été repoussée, cette demande n'est plus prioritaire. Je déplace au milsetone 4.0.

**Comment by stephyritz** [comment]
Je rebondis sur le sujet. Je pense qu'il faudrait prévoir d'améliorer les vues par défaut et avancée pour mieux présenter les contraintes d'accès et d'utilisation. A terme, les informations seront encodées selon le modèle des fiches INSPIRE actuelles (+ opération de séparation des CA/CPA/CU/CPU). Or pour le moment, nous affichons des informations inutiles pour les utilisateurs et la hiérarchie actuelle de la vue avancée ne me semble pas optimale.
 Voir prtsc suivants :

Vue par défaut : 

![presentation_contraintes_default_view](https://user-images.githubusercontent.com/34446202/70897592-38e0ec00-1ff3-11ea-8c75-0d1d32199d11.png)


Vue avancée : 

![presentation_contraintes_advanced_view](https://user-images.githubusercontent.com/34446202/70897600-3b434600-1ff3-11ea-8c69-e2175638af79.png)


Pour moi l’amélioration de l'interface pour présenter les fiches est un enjeu important de la future release, notamment en vue du remplacement du catalogue du Géoportail.

Sujet en lien : https://github.com/SPW-DIG/metawal-core-geonetwork/issues/494

**Comment by fxprunayre** [comment]
Vue par défaut:
* contraintes d'accès:
* contraintes d'utilisation

**Comment by stephyritz** [comment]
OK après avoir vidé le cache
