### ISSUE TITLE
Edition / Remplacement de champs texte par des codelist

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#493]
Au cours des dernières mises à jour de Metawal, plusieurs champs, initialement en texte libre (dans des balise <gco:characterstring> ont été remplacé par des codelist. La plupart du temps, les valeurs sont alors stockées dans des balises de type ancre et font référence à un thesaurus GN ou un registre. Il s'agit là d'une bonne amélioration pour la saisie et pour une homogénéisation du contenu des fiches.

Seulement, ces changements ont jusqu'à présent été implémentés dans l'interface sans modifiés le contenu de la DB. Par exemple, ceci signifie que, si j'encode aujourd'hui un nouveau format grâce à la codelist mise en place dans la release 3.8.1, il sera renseigné sous forme d'ancre. Mais, le même format, encodé il y a plus d'un an, est toujours sous forme de characterstring dans les autres fiches.

Ceci a pour conséquence que, au sein des fiches de Metawal, il y a du contenu hétérogène (cohabitation de "l'ancienne" manière de décrire et de "la nouvelle") ce qui peut poser problème, notamment pour les applications tierces qui utilisent des informations contenues dans les fiches (par ex. FME ou Geoportail). Ce phénomène est passé un peu inaperçu notamment parce que, lors de la création de fiche, nous avons pour habitude de dupliquer une fiche existantes.

Il faudrait donc, lorsque, à l'avenir nous faisons ce genre de modification, cela puisse s'accompagner d'un changement des valeurs en DB. A l'heure actuelle, voici les champs pour lesquels nous allons devoir planifier des requêtes en Db afin d'obtenir un contenu homogène pour l'ensemble de nos fiches  : 

- [ ] Thesaurus infraSIG (Supprimer les Anchor sur les fiches)

Avant : 
```
<gmd:title>
<gco:CharacterString>Mots-clés InfraSIG</gco:CharacterString>
</gmd:title>
```

Maintenant : 
```
<gmd:title>
<gmx:Anchor xlink:href="http://metawal.wallonie.be/thesaurus/infrasig#">Mots-clés InfraSIG</gmx:Anchor>
</gmd:title>
```

- [x] Format de distribution (Cf. thesaurus media type)

Avant : 
```
 <mrd:distributionFormat>
            <mrd:MD_Format>
               <mrd:formatSpecificationCitation>
                  <cit:CI_Citation>
                     <cit:title>
                        <gco:CharacterString>OGC:GeoPackage (.gpkg)</gco:CharacterString>
                     </cit:title>
                     <cit:date gco:nilReason="unknown"/>
                  </cit:CI_Citation>
               </mrd:formatSpecificationCitation>
            </mrd:MD_Format>
         </mrd:distributionFormat>
```

Maintenant : 
```
    <mrd:distributionFormat>
            <mrd:MD_Format>
               <mrd:formatSpecificationCitation>
                  <cit:CI_Citation>
                     <cit:title>
                        <gcx:Anchor xlink:href="https://www.iana.org/assignments/media-types/application/geopackage+sqlite3">OGC GeoPackage (.gpkg)</gcx:Anchor>
                     </cit:title>
                  </cit:CI_Citation>
               </mrd:formatSpecificationCitation>
            </mrd:MD_Format>
         </mrd:distributionFormat>

```

- [x] Système de projection

Avant : 
```
<mdb:referenceSystemInfo>
      <mrs:MD_ReferenceSystem>
         <mrs:referenceSystemIdentifier>
            <mcc:MD_Identifier>
               <mcc:code>
                  <gco:CharacterString>http://www.opengis.net/def/crs/EPSG/0/5710</gco:CharacterString>
               </mcc:code>
            </mcc:MD_Identifier>
         </mrs:referenceSystemIdentifier>
         <mrs:referenceSystemType>
            <mrs:MD_ReferenceSystemTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_ReferenceSystemTypeCode"
                                            codeListValue="vertical"/>
         </mrs:referenceSystemType>
      </mrs:MD_ReferenceSystem>
  </mdb:referenceSystemInfo>
```

Maintenant : 
```
   <mdb:referenceSystemInfo>
      <mrs:MD_ReferenceSystem>
         <mrs:referenceSystemIdentifier>
            <mcc:MD_Identifier>
               <mcc:code>
                  <gcx:Anchor xlink:href="http://www.opengis.net/def/crs/EPSG/0/3812">EPSG:3812</gcx:Anchor>
               </mcc:code>
               <mcc:description>
                  <gco:CharacterString>ETRS89 / Belgian Lambert 2008 (EPSG:3812)</gco:CharacterString>
               </mcc:description>
            </mcc:MD_Identifier>
         </mrs:referenceSystemIdentifier>
         <mrs:referenceSystemType>
            <mrs:MD_ReferenceSystemTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_ReferenceSystemTypeCode"
                                            codeListValue="projected"/>
         </mrs:referenceSystemType>
      </mrs:MD_ReferenceSystem>
  </mdb:referenceSystemInfo>
```

Ces modifications en DB devraient normalement se faire en même temps que celles dans les query FME et Geoportail. Mais, afin de pouvoir tout de même avancer de manière autonome sur le sujet, ne pourrions-nous pas imaginer de créer un csw-geoportail associé à un xslt permettant de servir les fiches toujours sous le même format (par ex. avec valeurs en characterstring), jusqu'à ce que eux soient prêts (à ce moment-là on modifie le xslt ou on le supprime). Globalement, cette manière de faire nous permettrait chaque fois de prendre un petit temps d'avance et éventuellement de "réajuster le tir" sans passer par une phase "lourde" de déploiement d'une nouvelle version de l'application. 

Qu'en pensez-vous ?

**Comment by fxprunayre** [comment]
Proposition: Ajour de composant pour aider à la saisie en vue avancée

![image](https://user-images.githubusercontent.com/1701393/72986672-0774f080-3de9-11ea-95ea-4f12f36c9a36.png)

![image](https://user-images.githubusercontent.com/1701393/72986707-19569380-3de9-11ea-9f25-a28daba61e3e.png)

**Comment by fxprunayre** [comment]
Pour les formats on reste sur le thésaurus utilisé pour définir l'anchor + text ?
![image](https://user-images.githubusercontent.com/1701393/73265669-b5abdc00-41d5-11ea-9ab4-1e0b0759087b.png)


Pour thésaurus infraSIG on laisse en attente tant qu'on a pas de registre ?

**Comment by stephyritz** [comment]
> Pour les formats on reste sur le thésaurus utilisé pour définir l'anchor + text ?

Oui.

> Pour thésaurus infraSIG on laisse en attente tant qu'on a pas de registre ?

Oui, on reste sur du gco:characterstring pour le moment.

Attention, je crois que le contenu actuel est hétérogène (tout du moins dans la manière de déclarer le nom du thesaurus infraSIG (parfois anchor parfois charstring). Il est donc tout de même nécessaire de jouer soit une reuqête DB soit une transfo xsl pour homogénéiser les valeurs sur ce point.

**Comment by stephyritz** [comment]
En test :
- OK pour la saisie rapide du système de projection
- NOK pour la saisie de la conformité INSPIRE
- NOK pour uniformisation des valeurs dans les xml (façon de renseigner les formats et système de proj : anchor + balises différentes).

**Comment by fxprunayre** [comment]
> * NOK pour la saisie de la conformité INSPIRE

Pourquoi NOK ? Sur quelle fiche ?
eg.
http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.edit#/metadata/1754?redirectUrl=catalog.edit&tab=dataQualityInfo

on a bien les boutons pour les éléments non renseignés

![image](https://user-images.githubusercontent.com/1701393/73851057-2b92f180-482d-11ea-9e57-4ab11d4c53d6.png)

Les boutons ne sont pas proposés si la conformité est renseignée.

**Comment by fxprunayre** [comment]
> * NOK pour uniformisation des valeurs dans les xml

Je pense qu'il faut qu'on distingue les aspects fonctionnalités de l'interface et actions sur l'encodage des fiches dans des tickets différents ? Leur déploiement ne se fera sans doute jamais en même temps. 

Pour les projections on a aussi le ticket #494 du coup on doublone. Le process est:
https://github.com/SPW-DIG/iso19115-3.2018/blob/8526fad87e428c36463b7b0b8ebb86826e4438bd/src/main/plugin/iso19115-3.2018/process/mw-epsg-harmonisation.xsl 


Donc ensuite, il nous manque un process qui s'occupe de réencoder les formats avec une Anchor. Correct ?

**Comment by stephyritz** [comment]
> 
> 
> > * NOK pour la saisie de la conformité INSPIRE
> 
> Pourquoi NOK ? Sur quelle fiche ?
> eg.
> http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.edit#/metadata/1754?redirectUrl=catalog.edit&tab=dataQualityInfo
> 
> on a bien les boutons pour les éléments non renseignés
> 
> ![image](https://user-images.githubusercontent.com/1701393/73851057-2b92f180-482d-11ea-9e57-4ab11d4c53d6.png)
> 
> Les boutons ne sont pas proposés si la conformité est renseignée.

L'affichage des boutons ne semble pas être automatique. Sur cette fiche par exemple (http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/06adcd09-6e69-411c-9cdc-5bfb668c475f), quand je vais en édition/vue complète/qualité, ils n’apparaissent pas. Puis si je rajoute des "informations sur la qualité des données" et que je change d'onglet puis reviens sur l'onglet qualité, alors les boutons apparaissent.

**Comment by stephyritz** [comment]
> 
> 
> > * NOK pour uniformisation des valeurs dans les xml
> 
> Je pense qu'il faut qu'on distingue les aspects fonctionnalités de l'interface et actions sur l'encodage des fiches dans des tickets différents ? Leur déploiement ne se fera sans doute jamais en même temps.
> 
> Pour les projections on a aussi le ticket #494 du coup on doublone. Le process est:
> https://github.com/SPW-DIG/iso19115-3.2018/blob/8526fad87e428c36463b7b0b8ebb86826e4438bd/src/main/plugin/iso19115-3.2018/process/mw-epsg-harmonisation.xsl
> 
> Donc ensuite, il nous manque un process qui s'occupe de réencoder les formats avec une Anchor. Correct ?

Oui je suis d'accord de séparer les tickets et c'est ce que j'avais fait initialement. Ce ticket était dédié aux changements en DB sur le contenu des fiches d'ailleurs. Et le 494 lié à l'interface de visualisation des données.

Oui, il reste les formats à ré-encoder avec une ancre. Et sur ces aspects de ré-encodage, il ne faudrait pas oublier de prévoir l'effet "reverse" dans le xsl qui permettrait au géoportail et à FME de consommer un CSW sous la même forme qu'avant. Il faudrait aussi que nous pensions à vérifier que les formats déclaré avec une ancre soient également conforme INSPIRE.

**Comment by davinciagf** [comment]
Attention, pour pouvoir disposer des boutons, il est n'écessaire d'avoir déjà référencé le titre de la spécification INSPIRE du résultats de conformité.

**Comment by stephyritz** [comment]
> 
> 
> Attention, pour pouvoir disposer des boutons, il est n'écessaire d'avoir déjà référencé le titre de la spécification INSPIRE du résultats de conformité.

?? 

Non justement le but de ces boutons étaient, en plus de spécifier si conforme ou non ou non testé, de référencer les textes règlementaire  en un clic. De plus, le fait que les boutons apparaissent ou disparaissent en fonction d'un refresh ou changement d'onglet est tout de même anormal.

**Comment by fxprunayre** [comment]
> Non justement le but de ces boutons étaient, en plus de spécifier si conforme ou non ou non testé, de référencer les textes règlementaire en un clic.

Si dans ton modèle tu as juste la section qualité (sans rapport), alors 
* un bouton pour la conformité des métadonnées s'affiche (si pas déjà saisie)
* si service, bouton pour la conformité des services (si pas déjà saisie)
* un bouton pour la conformité des données s'affiche (si pas déjà saisie)

> De plus, le fait que les boutons apparaissent ou disparaissent en fonction d'un refresh ou changement d'onglet est tout de même anormal.

Quand on supprime un élément, y'a refresh du formulaire - du coup mise à jour.
Si le modèle contient la section qualité c'est bon.
Par contre si on fait ajout d'une section qualité (il n'y a pas refresh de la totalité du formulaire), donc en effet, il faut faire un refresh. On a pas bien mieux pour le moment.

Est-ce que ça convient quand même?

**Comment by stephyritz** [comment]
> Est-ce que ça convient quand même?

Oui, bien sûr. C'est clairement une amélioration.

**Comment by stephyritz** [comment]
NOK sur le contenu en DB (les systèmes de proj et les formats sont toujours renseignés sous la forme de characterstring) (Aussi en test, cela m'avait échappé)

OK pour le bouton de saisie rapide d'un système de proj.

**Comment by davinciagf** [comment]
Procédure à jouer et inclure dans le déploiement : 
https://github.com/SPW-DIG/iso19115-3.2018/blob/8526fad87e428c36463b7b0b8ebb86826e4438bd/src/main/plugin/iso19115-3.2018/process/mw-epsg-harmonisation.xsl
