### ISSUE TITLE
Interface / Adaptation au "formatage codelist"

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#494]
Ce bug est lié à la thématique abordée dans https://github.com/SPW-DIG/metawal-core-geonetwork/issues/493.

En effet, lorsque la manière de déclarer une information change, il se peut qu'il y ait également des conséquences sur les interfaces qui présentent cette information.

Voici un exemple concernant les systèmes de projection sur la fiche http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/968514e6-04f7-4a84-b083-f2680435f5f2/formatters/xsl-view?root=div&view=advanced : 

Les systèmes de projection epsg:31370 et epsg:3035 étaient déjà encodés ("ancienne manière")

1. J'ajoute un nouveau système de projection (EPSG:4326) depuis l'interface en vue complète depuis l'onglet système de référence. Il est donc renseigné selon la "nouvelle manière"

2. Les informations encodées sous la forme de la "nouvelle manière" ne semblent pas être parfaitement interprétées par l'interface en vue complète

![bug_interface_syst_proj_494](https://user-images.githubusercontent.com/34446202/69645601-b2c22d00-1066-11ea-825d-1cbf6fdfb332.png)

**Comment by fxprunayre** [comment]
- [ ] Revoir l'affichage.

- [x] Mettre à jour les fiches avec Anchor - Projected.

```
* 31370 (type = projeté)
* 3035 (type = projeté)
* 4326(type = 2D géographique géodésique)
* 3857 (type = projeté)
* 5710 (type = vertical)
```

type = valeurs présentes dans la liste déroulante offerte dans MW en édition.

```xml

   <mdb:referenceSystemInfo>
      <mrs:MD_ReferenceSystem>
         <mrs:referenceSystemIdentifier>
            <mcc:MD_Identifier/>
         </mrs:referenceSystemIdentifier>
         <mrs:referenceSystemType>
            <mrs:MD_ReferenceSystemTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_ReferenceSystemTypeCode"
                                            codeListValue="projected"/>
         </mrs:referenceSystemType>
      </mrs:MD_ReferenceSystem>
  </mdb:referenceSystemInfo>
```

- [ ] Vérifier éditeur.

- [x] CSW inverse

**Comment by davinciagf** [comment]
Affichage modifié par :
https://github.com/SPW-DIG/iso19115-3.2018/commit/5a559d58887831188d3b9bb713386f9767bdcad2

**Comment by fxprunayre** [comment]
On dirait qu'il y en à d'autres 

CRS not handled http://www.opengis.net/def/crs/EPSG/0/4258
CRS not handled http://www.opengis.net/def/crs/EPSG/0/3812
CRS not handled http://www.opengis.net/def/crs/EPSG/0/21500
CRS not handled http://www.opengis.net/def/crs/EPSG/0/54024
@stephyritz on doit les convertir aussi ? Si oui, c'est quoi le type ?

**Comment by stephyritz** [comment]
Ok merci, différence entre bonnes pratiques et réalité.

4258 --> type = 2D géographique géodésique
3812 --> type = projeté
21500 --> Suppression
54024 --> Suppression

**Comment by fxprunayre** [comment]
Pour les projection on est bon 
![image](https://user-images.githubusercontent.com/1701393/73262464-7ded6600-41ce-11ea-8089-98e8251510a0.png)

En consultation
* vue simple

![image](https://user-images.githubusercontent.com/1701393/73263791-a7f45780-41d1-11ea-8b15-a44717304367.png)

* vue avancée

![image](https://user-images.githubusercontent.com/1701393/73263765-9ad76880-41d1-11ea-81db-65e573176da2.png)

et de manière plus générale toutes les ancres sont affichées avec liens 

![image](https://user-images.githubusercontent.com/1701393/73263785-a591fd80-41d1-11ea-99a5-1a096fe3af17.png)

**Comment by stephyritz** [comment]
Je ne sais pas si c'est déjà abouti pour le système de projection par exemple en terme de présentation dans la vue complète.

![presentation_crs](https://user-images.githubusercontent.com/34446202/73834274-b3680400-480b-11ea-8631-0a317409f701.png)

Il y a trop de sauts de ligne et d'info en texte qui ne servent à rien comme par exemple : 
"Système de référence" + "Nom du système de référence" + "Identifiant". Il pourrait n'y avoir, à l'affichage que "Système de référence" puis les infos importantes (Code, Description et Type de projection).

**Comment by davinciagf** [comment]
Problème de style entre les tests en local et sur la machine de test.
![image](https://user-images.githubusercontent.com/576292/73851357-9d6b3b00-482d-11ea-8af2-d20db0fd3ed5.png)

**Comment by stephyritz** [comment]
Attention,
il semblerait que l'ajout de l'information liée au MD_ReferenceSystemTypeCode ne soit pas valide pour le schéma 19139. 

Résultat du test par exemple pour 6029e738-f828-438b-b10a-85e67f77af92 
--> http://inspire.ec.europa.eu/validator/v2/TestRuns/EID64deaf6b-428d-4d51-a078-dd933f6540b0.html 

Faut-il dès lors prévoir la suppression de cette balise lors de la conversion en 19139 ?
Cela rajoute à nouveau une modification dans le xsl de transfo mais je ne sais pas comment on peut gérer cela autrement... Comment cela se passe-t-il pour les autres champs OK dans le schéma de la 19115-3 et NOK en 19139 ?

**Comment by fxprunayre** [comment]
> il semblerait que l'ajout de l'information liée au MD_ReferenceSystemTypeCode ne soit pas valide pour le schéma 19139.

Oui je regarde ça maintenant.

**Comment by fxprunayre** [comment]
Fixed in https://github.com/metadata101/iso19115-3.2018/commit/69fd4b06103d294f2c2938c01859a065a4066dc5

@davinciagf tu peux mettre à jour ?

**Comment by davinciagf** [comment]
En cours de déploiement

**Comment by davinciagf** [comment]
Retesté avec succès sur 6029e738-f828-438b-b10a-85e67f77af92
http://inspire.ec.europa.eu/validator/v2/TestRuns/EID89f97104-b1a4-4147-88e9-ac53b70bf87d.html

**Comment by stephyritz** [comment]
Point d'attention : EN environnement de valid, la minicarte avec l'emprise spatiale ne s'affiche pas correctement.

![mini-carte_NOK](https://user-images.githubusercontent.com/34446202/75046743-eece2800-54c5-11ea-8355-ebf0aee88c35.png)

**Comment by fxprunayre** [comment]
> Point d'attention : EN environnement de valid, la minicarte avec l'emprise spatiale ne s'affiche pas correctement.

Ce matin, j'ai observé des pb avec le service WMS utilisé pour le fond de carte (si ça persiste, il faut créer un autre ticket). Pas de lien avec ce ticket là en tout cas.
