### ISSUE TITLE
Erreur en prod de l'url des reqêtes de l'API REST

### ISSUE THREAD

**Issue by davinciagf** [SPW-DIG/metawal-core-geonetwork#495]
L'adresse ip de l'API REST lançant les requêtes n'est pas la bonne ==>  Pointé les requêtes vers le serveur adhoc (metawal.wallonie.be, ...).
Exemple correcte en test
![Capture](https://user-images.githubusercontent.com/576292/69821368-bc34cc00-1203-11ea-9069-2959cee68169.JPG)

**Comment by stephyritz** [comment]
Illustration de ce problème en prod (http://metawal.wallonie.be/geonetwork/doc/api/index.html#/records/getRecordTags) : 

![illus_issue_495](https://user-images.githubusercontent.com/34446202/71818728-0bcfa880-308a-11ea-8e45-ca4a44de8c75.png)

Peut-être que nous pouvons profiter de notre semaine de travail pour que vous puissiez me former sur l'utilisation de l'API ? En effet, je pense que nous n'utilisons pas assez cet outil.

**Comment by fxprunayre** [comment]
En effet il appel une IP http://157.164.175.46/geonetwork/srv/api/0.1/site/info
Le host n'est pas correct dans http://metawal.wallonie.be/geonetwork/srv/v2/api-docs
Pourtant admin > paramètre est ok.
Et ca marche bien en test http://metawal4.test.wallonie.be/geonetwork/doc/api/index.html et http://metawal4.test.wallonie.be/geonetwork/srv/v2/api-docs
Donc pb avec la prod - qui retourne une IP locale ?


Probablement configuré ici https://github.com/springfox/springfox/blob/2.6.0/springfox-swagger2/src/main/java/springfox/documentation/swagger2/web/Swagger2Controller.java#L92-L100

**Comment by fxprunayre** [comment]
Fixed.
