### ISSUE TITLE
Erreur lors de l'indexation suite à la présence de sous éléments de MTD en ISO155-3

### ISSUE THREAD

**Issue by davinciagf** [SPW-DIG/metawal-core-geonetwork#496]
Présence dans la DB de prod (2019-11-12) de sous éléments de MTD (gmd:Ci_ResponsibleParty) disposant d'un schemaid en iso19115-3. 

![image](https://user-images.githubusercontent.com/576292/69873551-f2805300-12b8-11ea-9b45-c4f1f8fada66.png)

![image](https://user-images.githubusercontent.com/576292/69873602-16439900-12b9-11ea-8733-d91447bf597b.png)

**Comment by fxprunayre** [comment]
Ce ne sont que des subtemplates. On supprime et on travaillera sur l'utilisation de l'annuaire.

A jouer en test
https://github.com/SPW-DIG/metawal-core-geonetwork/commit/24448a1858da943fa9dbd88910aff1094148ee62
