### ISSUE TITLE
Interface Edition / Ressources dans Metawal

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#498]
L'hyperlien associé aux ressources renvoyant à d'autres fiches de Metawal semble erroné.

Par exemple :
Je suis en mode édition d'une fiche MD de données, une fiche service est associée en tant que ressource. Je clique dessus pour accèder à la dire fiche de service --> Erreur 404

Je pense que l'url renseignée en hyperlien n'est pas la bonne. Par exemple : http://metawal.wallonie.be/geonetwork/srv/metadata/d9fbf5cd-de22-48c0-bc6f-56b894c7b764.

Cela devrait plutôt être du type http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/d9fbf5cd-de22-48c0-bc6f-56b894c7b764, non ?

**Comment by fxprunayre** [comment]
Fixed in https://github.com/geonetwork/core-geonetwork/pull/4288

**Comment by fxprunayre** [comment]
Modifier le lien vers la page catalog.search

**Comment by stephyritz** [comment]
Le lien ne redirige pas vers le catalog.search mais vers une url de type http://metawal4.valid.wallonie.be/geonetwork/srv/metadata/a3e13882-cd88-42e1-829a-d112c1a56f84 en environnement de valid

**Comment by fxprunayre** [comment]
Admin > Tools > Vider le cache JS & CSS - est-ce que ça résoud le pb ?

**Comment by stephyritz** [comment]
Oui, c'est tout bon suite à cette manip. Ne serait-il pas plus confortable d'intégrer cette opération de vider le cache systématiquement après chaque déploiement ?

**Comment by fxprunayre** [comment]
> Ne serait-il pas plus confortable d'intégrer cette opération de vider le cache systématiquement après chaque déploiement ?

J'ai dû le mentionner quelques fois déjà ;) Le mieux serait d'avoir un script de déploiement qui s'occupe de tout au lieu des n manips manuelles sur un site web pour uploader un WAR. Toujours un point à améliorer qui offrirait plus de confort pour tous à mon avis.

**Comment by stephyritz** [comment]
@davinciagf, tu es en première ligne. N'hésite pas à remonter cela au DTIC, je soutiendrai bien évidemment cette demande en interne.
