### ISSUE TITLE
Edition / Gestion des brouillons

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#499]
J'ai apporté des modifications la fiche suivante http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/f08dc35a-70ea-4570-b2ea-07637c802a57

Mais je n'ai que eu la possibilité de l'enregistrer en tant que brouillon. J'aime bien le principe (à part que je n'ai pas eu le choix dans ce cas là). J'obtiens donc http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadraf/f08dc35a-70ea-4570-b2ea-07637c802a57 

Comment dois-je faire ensuite pour que ma fiche brouillon remplace donc la fiche actuellement publiée ?

Pourquoi est-ce que je n'ai eu que le cas de "sauver en brouillon" uniquement sur cette fiche ? Est-ce à cause de la notion de propriétaire (je me la suis appropriée mais aucun effet) ou de privilèges ou autres raisons ?

**Comment by fxprunayre** [comment]
C'est probablement à cause de
![image](https://user-images.githubusercontent.com/1701393/70310961-07a53680-1811-11ea-9294-42b0b71afb93.png)

Je le désactiverai pour le moment tant que ce n'est pas testé correctement.

**Comment by stephyritz** [comment]
Ok, j'ai désactivé mais pour la fiche en question. Cependant, malgré cela, au moment d'éditer, je ne peux que enregistrer cette fiche en tant que brouillon. Finalement, en dépubliant, republiant et après avoir vidé le cache, les changements que j'avais fait en brouillon sont visibles sur la fiche. Bizarre.. Je veux bien faire des tests plus approfondis sur cette fonctionnalité au moment venu (milestone 4.0.0 ?).

**Comment by stephyritz** [comment]
Le cas s'est présenté à nouveau sur cette fiche (http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/6babbdbf-a3d6-4c1d-96af-c43264a35ae3) bien que le workflow soit désactivé. 

Un utilisateur passe en mode édition et n'a que la possibilité "d'enregistrer comme brouillon". Ensuite, après création du brouillon, impossible de clairement d'appliquer les changement du brouillon à la version publiée.

En tant qu'admin, j'ai fait différentes manipulations qui ont permis finalement la résolution du problème (remplacement de la fiche par son brouillon).  Je ne pourrais pas exactement dire ce qui a fonctionné car j'ai fait plusieurs action simultanément :  changer le propriétaire de la fiche, vider le cache, "valider" la fiche, dépublier/publier.

Je n'ai pas non plus encore compris la cause exacte même si je soupçonnais, dans un premier temps, que c'est lorsqu'un utilisateur autre que le propriétaire au sens GN fasse des modifications. Mais les contre-exemples sont nombreux. Est-ce propre à Metawal ? A creuser la prochaine fois que cela se présente.

**Comment by stephyritz** [comment]
Autre exemple en cours pour lequel je n'ai pas fait de manipulations pour résoudre le pb : http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/ac455ccd-39df-455d-826c-e5e72900ccae

**Comment by fxprunayre** [comment]
Identifiant de la fiche 10135

http://metawal.wallonie.be/geonetwork/srv/fre/admin.console#/dashboard/versioning

![image](https://user-images.githubusercontent.com/1701393/72518074-cd3da900-3854-11ea-8ec8-83b583c6f57a.png)

L'historique

http://metawal.wallonie.be/geonetwork/srv/api/records/status/search?type=workflow&type=task&type=event&record=10135&from=0&size=60&details=true

Pas évident de savoir. Est-ce que ce serait une fiche qui avait un statut et ensuite on a désactiver le workflow et du coup l'édition la met en draft - à tester.

**Comment by stephyritz** [comment]
Nouvel exemple ce matin : metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadraf/b353aac2-224c-42f7-89ca-61938ded23eb

Une fiche créée en octobre 2019. Je la publie aujourd'hui puis je veux faire une modification. Un brouillon est créé directement alors qu'avant la dernière release, la modification s'appliquait directement à la version publiée. Ce principe ne me dérange pas forcément mais alors il faudrait que je puisse "valider" le brouillon afin qu'il remplace la version publiée actuellement.

**Comment by fxprunayre** [comment]
Je tente de reproduire mais sans succès. Tu as fait quoi comme manip:
* catalog.edit 
* recherche
* changer les privilèges (ou bouton publier dans la consultation de la fiche?)
* edition
* modif (quel type ?)
* sauvegarde
Et là tu as un brouillon ?

**Comment by stephyritz** [comment]
Pour cette fiche-ci : 
1. Ouverture de la fiche en mode édition
2. Modification des informations concernant les services WMS et REST
3. Fermer et enregistrer
4. Publier
5. Éditer
6. Modification de la date de publication
7. Sauvegarde

Et là un bouillon est créé à la place d’intégrer directement la modification 6.
Cela ne se produit pas pour toutes les fiches, seulement certaines (je viens de modifier la fiche de la peste porcine et le problème ne s'est pas présenté). J'ai l'impression que le point commun est la publication récente de ces fiches (en tout cas pour les deux derniers cas c'est sûr). Peut-être une publication sous une version 3.8 ou plus de Metawal induirait ce comportement. Je ne pense pas que cela soit lié à l'activation/désactivation du workflow (ou alors son effet a lieu à la création de la fiche car il n'était pas désactivé à ce moment-là mais inactif lorsque j'ai publié la dernière fiche).

**Comment by fxprunayre** [comment]
J'ai, je crois mais je veux bien une confirmation de ton côté.

Sur la fiche en question:

http://metawal.wallonie.be/geonetwork/srv/fre/q?_content_type=json&_draft=y+or+n+or+e&_isTemplate=y+or+n&fast=index&uuid=b353aac2-224c-42f7-89ca-61938ded23eb

On a
```json
mdStatus: "2",
```
ie. validé dans le workflow.

Mais le workflow est désactivé dans l'admin. 

Du coup on doit avoir le passage en draft dans ce cas là - même avec le workflow désactivé.

En base, il n'y a pas bcp de fiche avec un état de workflow

![image](https://user-images.githubusercontent.com/1701393/72601573-f3774d80-3915-11ea-80a2-1bafcaa6d4d2.png)

Par contre y'a des coquilles dans les types de status. Je corrige.


Je vérifie mais sinon je propose de supprimer les status des fiches en base pour ne plus avoir le pb.

**Comment by fxprunayre** [comment]
See https://github.com/geonetwork/core-geonetwork/issues/4369

**Comment by stephyritz** [comment]
Ok, bien vu. Si c'est lié à ça, cela peut expliquer que j'avais réussi à résoudre le problème en faisant des actions type "valider", "publier/dépublier". Les statuts déterminent l'état dans le workflow c'est bien ça (brouillon, validé, publié ?) ?
A voir s'il y a un intérêt de le stocker en DB. Pour le moment non car le workflow n'est pas opérationnel chez nous. Mais globalement je trouverai cela utile qu'une modif faite par un utilisateur avec un rôle défini (éditeur) puisse être stockée dans un brouillon jusqu'à ce qu'un utilisateur avec le rôle d'admin puisse valider ce brouillon pour le publier à la place de la version actuelle.

**Comment by fxprunayre** [comment]
A jouer en prod:


https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-3.10.x/web/src/main/webapp/WEB-INF/classes/setup/sql-metawal/migrate/3.10.0/migrate-default.sql#L10-L11

**Comment by stephyritz** [comment]
En attendant la  correction du bug, quelle procédure dois-je suivre pour qu'un brouillon remplace la fiche publique ? Sur http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/b353aac2-224c-42f7-89ca-61938ded23eb, j'ai essayé :
1. Activer le workflow
2. Editer le brouillon
3. Valider le brouillon (mais il reste "invalide" car certaines "erreurs" toujours présentes mais les erreurs remontées ne semble pas pertinente j'ai l'impression) 
4. Ré-indexer
5. Vider le cache
6. Désactiver le workflow

**Comment by fxprunayre** [comment]
Il ne faut pas valider (au sens XSD/Schematron). Il faut valider au sens workflow.

**Comment by stephyritz** [comment]
Oui mais comment ?

**Comment by fxprunayre** [comment]
> Oui mais comment ?

Je vois pas bien avec les menus de l'interface.
Je ferai:
* activer le workflow
* download xml du brouillon
* le supprimer avec "annuler la copie de travail"
* désactiver le workflow
* mettre à jour en xml la fiche avec le xml téléchargé 

?

**Comment by stephyritz** [comment]
Ah je m'attendais à quelque chose de "moins bourrin". Ceci étant dit cela ne fonctionne pas car dès que je veux éditer la fiche en xml ou autre et même après avoir fait toutes les étapes précédentes, je n'ai que l'option de sauvegarder en tant que brouillon.

**Comment by fxprunayre** [comment]
> Ah je m'attendais à quelque chose de "moins bourrin"

Tu peux regarder si c'est la bonne version qui est en ligne là ? Normalement j'ai une copie des 2 versions si besoin. J'ai fais annuler la copie de travail.

**Comment by stephyritz** [comment]
Non ce n'est pas la bonne qui est en ligne.
Voici la dernière version (anciennement brouillon) : 

[b353aac2-224c-42f7-89ca-61938ded23eb.zip](https://github.com/SPW-DIG/metawal-core-geonetwork/files/4097321/b353aac2-224c-42f7-89ca-61938ded23eb.zip)

**Comment by fxprunayre** [comment]
En fait on tourne en rond car on a toujours des status en base, donc dès qu'on édite on recrée un brouillon. Du coup, je vois 2 options:
1) jouer la requête qui supprime les statuts, désactiver le workflow et mettre à jour la fiche
ou 2) supprimer la fiche et réimporter la dernière version

**Comment by stephyritz** [comment]
Bon j'ai fait l'option 2) en attendant parce qu'au moins j'avais la main là-dessus. On verra si cette manip ne "casse" rien.

**Comment by fxprunayre** [comment]
* En prod jouer la requête pour supprimer les status
* En test, déployer le pb a été corrigé (ie. ne pas créer de brouillon si workflow inactif).

**Comment by stephyritz** [comment]
Ok, ticket DTIC en cours pour jouer le sql supprimant les statuts en prod.

**Comment by stephyritz** [comment]
La requête a bien été jouée en prod. Problème résolu en supprimant les statuts en DB.
Problématique à surveiller lors de la mise en œuvre du workflow mobilisant les brouillons.
