### ISSUE TITLE
liens externes à ouvrir dans une nouvelle page

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#5]
Dans une fiche, les liens pour les services associés, modèles de données, appli,... devraient s'ouvrir dans une nouvelle page (et pas écraser).

**Comment by fxprunayre** [comment]
A priori non. Il est préférable de laisser l'utilisateur choisir (il n'est en général pas recommandé de forcer l'utilisateur sur l'ouverture d'un lien). Le navigateur permet de faire clic droit > ouvrir dans un nouvel onglet (ou ALT+click ou CTRL+click)

**Comment by fxprunayre** [comment]
Doublon #69.
