### ISSUE TITLE
Défault d'impression PDF et retour impossible.

### ISSUE THREAD

**Issue by PascalDelvaux** [SPW-DIG/metawal-core-geonetwork#50]
A la visualisation de la fiche (références ci-dessous) dans "Actions" la fonction "Export PDF" provoque une erreur.

http://metawal3.test.wallonie.be/geonetwork/srv/eng/pdf?uuid=6bb4a41f-8477-4a0c-95f9-7d2807ee0589

Message =

The requested operation could not be performed.

XPathException : A sequence of more than one item is not allowed as the first argument of concat() 

+++ Le bouton "Back" revient sur une page FireFox mais pas dans la fiche.

**Comment by fxprunayre** [comment]
Semble ok sur test.

**Comment by vbombaerts** [comment]
voir #92 et #38 
Résolu.
