### ISSUE TITLE
Edition DB / Mots-clés thèmes INSPIRE

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#500]
Modifier le mode d'encodage des mots-clés "Thème INSPIRE" pour les faire passer de CharacterString à Anchor dans toutes les fiches concernées par INSPIRE.

Cette démarche pourrait être envisagée pour tous les éléments actuellement en texte libre mais qui sont référencés dans des registres externes .

Ce n'est pas dans les TG2 d'INSPIRE mais l'idée de lier un concept à une href est bonne et dans la même philosophie de ce qui est demandé par ailleurs (spatialscope par exemple).

**Comment by fxprunayre** [comment]
Pour check en DB:

```sql


WITH ns AS (
select ARRAY[ARRAY['xlink', 'http://www.w3.org/1999/xlink'],
            ARRAY['mri', 'http://standards.iso.org/iso/19115/-3/mri/1.0'],
            ARRAY['cit', 'http://standards.iso.org/iso/19115/-3/cit/2.0'],
            ARRAY['gcx', 'http://standards.iso.org/iso/19115/-3/gcx/1.0']] AS n
)

SELECT * FROM (
SELECT uuid, schemaid, unnest(xpath('count(//mri:keyword[../mri:thesaurusName/*/cit:title/* = "GEMET - INSPIRE themes, version 1.0"])',
	 XMLPARSE(DOCUMENT data), n))::text::int  AS count,
	 unnest(xpath('count(//mri:keyword[../mri:thesaurusName/*/cit:title/* = "GEMET - INSPIRE themes, version 1.0"]/gcx:Anchor)',
	 XMLPARSE(DOCUMENT data), n))::text::int  AS countWithAnchor
	FROM metadata, ns
	WHERE isTemplate = 'n'
 ) AS stat WHERE count > 0 ORDER BY 4 desc
```

Process:
https://github.com/metadata101/iso19115-3.2018/blob/master/src/main/plugin/iso19115-3.2018/process/move-keyword-to-anchor.xsl

Lancement:
![image](https://user-images.githubusercontent.com/1701393/72420522-2e934880-377f-11ea-8f76-facdca5aa6fb.png)

**Comment by fxprunayre** [comment]
TODO: Test à faire avec bdinfrasig et doc pour expliquer comment lancer le processus.

**Comment by davinciagf** [comment]
Requête pour modifier ajout des ancres sur base d'un autre thesaurus :

http://localhost:8080/geonetwork/srv/api/0.1/processes/move-keyword-to-anchor?uuids=6029e738-f828-438b-b10a-85e67f77af92&appendFirst=false&thesaurusFileName=infraSIG

thesaurusFileName: voir les fichiers (nom du fichier sans son extension) présents au niveau du directory des thesaurus  (\src\main\webapp\WEB-INF\data\config\codelist\external\thesauri\theme)

**Comment by davinciagf** [comment]
Process 'move-keyword-to-anchor' joué en test

**Comment by stephyritz** [comment]
NOK en valid -->  move-keyword-to-anchor joué en valid ?

![keyword-anchor-NOK_valid](https://user-images.githubusercontent.com/34446202/75047866-d7903a00-54c7-11ea-8b43-074a08a2015a.png)

**Comment by davinciagf** [comment]
Il ne semble pas y avoir eu d'erreur dans le process en valid:

![image](https://user-images.githubusercontent.com/576292/75138916-a98b3f80-56eb-11ea-898f-c08b3dca0c95.png)

Je vérifie

**Comment by davinciagf** [comment]
Le process est à rejouer en valid car le thesarus inspire n'était pas à jour (ancien identifier).
Après mise à jour du thesaurus en valid (suppression et upload via l'interface d'admin), le process a été rejoué sur le fiche :
http://157.164.189.29/geonetwork/srv/api/records/f16124b7-41ed-42fe-9442-73b32708d60a/formatters/xml?approved=true 

Le thesaurus en prod dispose du bon identifier.

**Comment by stephyritz** [comment]
OK en prod.
J'ai vérifié par erreur dans le schéma d'export "mw"
