### ISSUE TITLE
 INSPIRE / CSW - Conformité du getcapabilities

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#501]
L'outil de harvesting de l'Europe nous signale que le service CSW de découverte a une erreur de schéma --> https://inspire-geoportal.ec.europa.eu/sandbox/resources/INSPIRE-f5201eb0-2404-11e5-8130-52540004b857_20191206-195107/services/1/resourceReport/

Je ne comprends pas ce problème est apparu entre le 1 et le 4 décembre alors que nous n'avons pas du tout touché au getcapabilities. Est-ce que vous avez une idée d'où cela peut provenir ?

Voici le résultat du test réalisé ci l'outil de validation INSPIRE : http://inspire.ec.europa.eu/validator/v2/TestRuns/EIDeef05d21-1428-4c1c-a62a-b7429e129820.html

Visiblement, il y a un problème avec le langage mais en comparant avec un service csw considéré conforme (celui du fédéral), je ne vois aucune différence.

Par ailleurs et au besoin, comment fait-on pour paramétrer le getcapabilities dans GN ?

**Comment by stephyritz** [comment]
On dirait qu'il y a une indentation et/ou un saut de ligne dans le texte décrivant la législation. 

![erreur_CSW](https://user-images.githubusercontent.com/34446202/70445364-b197f380-1a9b-11ea-9010-1aadec8db34f.png)

Mais via le navigateur, cela n'apparaît pas (car non interprété en html ?): http://metawal.wallonie.be/geonetwork/srv/eng/csw-inspire?SERVICE=CSW&REQUEST=GetCapabilities

**Comment by fxprunayre** [comment]
Car c'est du XML et les espaces de retour de ligne ne devrait pas être pris en compte par le validateur je pense. La config est là https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-3.8.x/web/src/main/webapp/xml/csw/capabilities_inspire.xml#L204-L206 donc un redéploy sera nécessaire.

**Comment by stephyritz** [comment]
> Car c'est du XML et les espaces de retour de ligne ne devrait pas être pris en compte par le validateur je pense

Mais tu penses que l'erreur soulevée par le validateur vient quand même de là ?

Est-ce que tu sais pourquoi le langage du service de découverte est par défaut en anglais ?

Même si cela ne pose peut-être pas de problème, cela me semble un peu incohérent parce que :
-  l'url de notre endpoint est http://metawal.wallonie.be/geonetwork/srv/fre/csw-inspire
-  le contenu du getcapabilities est majoritairement en français 
-  le reste des fiches est en français
-  le reste des getcapabilities (WMS et atom) est en français aussi

Est-ce que nous devrions pas mettre à jour ce service de découverte pour corriger les sauts de lignes existants, homogénéiser le contenu pour mettre du français et définir le français comme langue par défaut pour la request et la reponse ? 
Éventuellement mettre l'anglais en "langue supportée" pour la request.

>  donc un redéploy sera nécessaire.

Nouveau war ? Ou ça peut se faire via un "simple" copier/coller ? J'ai encore un ticket ouvert au DTIC pour des actions en DB mais si c'est un redéploiement, il faut retourner à la case départ niveau procédures internes..

**Comment by fxprunayre** [comment]
> Nouveau war ? Ou ça peut se faire via un "simple" copier/coller ?

On peut faire un copier/coller du fichier corrigé sur le serveur - mais je sais pas si on a le droit ?

**Comment by stephyritz** [comment]
> On peut faire un copier/coller du fichier corrigé sur le serveur - mais je sais pas si on a le droit ?
Nous --> non, seulement en environnement de TEST
Didier Husson --> Oui, j'espère même si ça va sûrement le faire râler

Qu'est-ce que tu penses de tout passer en français  et des différentes incohérences mentionnées plu haut ? Même si, de ce que je comprends, c'est plutôt le saut de ligne qui fait qu'on est non conforme. Mais alors pourquoi cela s'est passé entre le 1 et le 4 décembre?! Mystère. Peut-être un changement dans la console d'harvesting...

**Comment by fxprunayre** [comment]
En testant https://files.titellus.net/tmp/csw-inspire.xml sans les retours à la ligne dans la spec, le test en question marche. Cf. http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID71c5e46e-d1ea-4637-a3d2-034c3989f7a4.html

**Comment by fxprunayre** [comment]
Corrigé - donc à redéployer ou copier le fichier sur la prod si c'est possible. C'était également remonté côté GN.

**Comment by fxprunayre** [comment]
> définir le français comme langue

En base de données: 

```sql
UPDATE languages SET isDefault = 'n' WHERE id = 'eng';
UPDATE languages SET isDefault = 'y' WHERE id = 'fre';
```

**Comment by fxprunayre** [comment]
> Mais alors pourquoi cela s'est passé entre le 1 et le 4 décembre?! 

Aucune idée. Y'a pas de raison de notre côté en tout cas.

**Comment by stephyritz** [comment]
> 
> 
> En testant https://files.titellus.net/tmp/csw-inspire.xml sans les retours à la ligne dans la spec, le test en question marche. Cf. http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID71c5e46e-d1ea-4637-a3d2-034c3989f7a4.html

Et l'erreur : "The capabilities response language is not the same as requested language." ?
Je ne la comprends pas non plus. Le langage par défaut étant "eng" et la réponse aussi dans le getcapabilities. Est-ce que ces 2 paramètres sont modifiés automatiquement avec l'update en DB ?
Ceci étant dis, nous n'avons pas ce message en passant par l'instance de prod du validateur.


En résumé, si cela vous convient, on va faire une chose après l'autre : 

1. Modification de https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-3.8.x/web/src/main/webapp/xml/csw/capabilities_inspire.xml#L204-L206 dans le Github --> François

2. Copier/coller de ce nouveau fichier dans l'environnement de test + "documentation du to do" pour Didier--> Arnaud

3. Test via l'outil de validation de la nouvelle config

4. Contacter Didier Husson pour faire le copier/coller en prod selon les instructions fournies par Arnaud --> Stéphane

5. Pour la prochaine release : Planification d'une config avec tout en "fre" (langage par défaut pour la request, référence à la législation en fre, langages supportés pour la request eng, ger, dut et langage de la response en fre).

**Comment by stephyritz** [comment]
Le point 5 est planifié pour la prochaine release. A priori, il y aura des actions en DB (définir les langages par défaut et les langages supportés) et des actions sur le fichier de conf https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-3.8.x/web/src/main/webapp/xml/csw/capabilities_inspire.xml#L204-L206 (modification du texte de référence et remplacement des ref en ENG par les ref en FRE).

**Comment by fxprunayre** [comment]
On a l'air ok en test http://metawal4.test.wallonie.be/geonetwork/srv/fre/csw?SERVICE=CSW&REQUEST=GetCapabilities&VERSION=2.0.2

Résultat: http://inspire.ec.europa.eu/validator/v2/TestRuns/EID684fda07-b413-4bcf-8026-5036b33c80d2.html

**Comment by stephyritz** [comment]
Oui jusqu'au point 5. mentionné ci-dessus. Dans un souci de cohérence avec le reste de nos services (atom et wms), ainsi qu'avec le reste de nos fiches de MD et avec ce qui est déclaré (eng mais contenus en fre comme le titre par ex.), je souhaitais modifier la configuration de ce getcapabilities pour le mettre en français par défaut et donc changer tout ce qui est en lien avec la langue dans ce getcapabilities (citation du texte réglementaire, les eng dans les url, la description des languages supportés, etc...). Même si actuellement il est jugé conforme, les aspects interopérabilités me paraissent limites avec les autres services et fiches notamment à cause du problème de langue.

**Comment by davinciagf** [comment]
Requête sur une langue:
http://metawal4.test.wallonie.be/geonetwork/srv/fre/csw?request=GetCapabilities&service=CSW&version=2.0.2&language=fre

**Comment by fxprunayre** [comment]
TODO:
* Admin / Supprimer la config CSW / contact & métadonnées
* Admin / Ajouter fiche correspondante au CSW
* Mapping 115-3 > GetCapabilities (gestion de la langue INSPIRE, temporal extent, définition du endpoint par une valeur de la fiche)
* Portail / CSW / Choix de la fiche à utiliser

GN ref: https://github.com/geonetwork/core-geonetwork/pull/4390

**Comment by fxprunayre** [comment]
@stephyritz Dans le mapping fiche de service > GetCapabilities, tu prendrais où les infos pour:
* fees = 
`//mdb:distributionInfo/*/mrd:distributor/*/mrd:distributionOrderProcess/*/mrd:orderingInstructions/*/text()` a priori

* accessConstraints = le texte de otherConstraint dans le resourceConstraints qui parle de l'accès ie. `//mdb:identificationInfo/*/mri:resourceConstraints/*[mco:accessConstraints]/mco:otherConstraints/*/text()`

Ca te convient ?

**Comment by stephyritz** [comment]
Oui, ça me semble logique.
Juste, pour le second, point je ne comprends pas trop le bout du chemin "*`[mco:accessConstraints]`". Je pense que cela peut être plus simplifier dans le sens où cette info est toujours dans le deuxième bloc mri:resourceconstraints OU en disant que c'estl le seul mco:otherconstraints en texte (cela rejoint l'idée que tu as mis ci-dessus).

**Comment by fxprunayre** [comment]
GN ref: https://github.com/geonetwork/core-geonetwork/pull/4390

**Comment by fxprunayre** [comment]
> ne comprends pas trop le bout du chemin "*`[mco:accessConstraints]`"

= un noeud qui contient un accessConstraints.
On ne peut pas se baser sur la position d'un bloc. Y'a pas de raison a priori de mettre un bloc avant l'autre. Donc ici on prend le bloc qui parle d'accès.

**Comment by fxprunayre** [comment]
A déployer et tester.

En base, jouer https://github.com/SPW-DIG/metawal-core-geonetwork/commit/356cc8f8ddc98ba234f4fb6dad8b0bb00ec47f3b

Dans Admin > CSW, choisir la fiche qui correspond au CSW

![image](https://user-images.githubusercontent.com/1701393/73259049-3c0cf180-41c7-11ea-9db2-213d78b15de2.png)

Tester
http://localhost:8080/geonetwork/srv/fre/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetCapabilities

Pour les CSW virtuels, je propose de migrer vers la notion de portail (en v4, les CSW virtuels sont supprimés) (d'autant plus qu'il y a un proxy devant) 

![image](https://user-images.githubusercontent.com/1701393/73259094-4e872b00-41c7-11ea-85f6-711339250b34.png)

Donc créer autant de portail que de CSW virtuel avec le même filtre.
L'URL http://localhost:8080/geonetwork/srv/fre/csw-inspire devient alors http://localhost:8080/geonetwork/inspire/fre/csw
et choisir la fiche correspondant au portail 


Modifier la conf du proxy devant.

**Comment by stephyritz** [comment]
> = un noeud qui contient un accessConstraints.
> On ne peut pas se baser sur la position d'un bloc. Y'a pas de raison a priori de mettre un bloc avant l'autre. Donc ici on prend le bloc qui parle d'accès.

Oui sauf que dans notre cas, l'info qui est dans le bloc qui contient accessconstraint il y a la valeur 'No limitations to public access' qui est stockées dans une ancre.

Si on veut le texte lié à la licence, il est dans le bloc qui contient le uselimitation. Nous avons dû structurer ainsi pour être TG2 compliant.

**Comment by stephyritz** [comment]
> 
> 
> A déployer et tester.
> 
> En base, jouer [356cc8f](https://github.com/SPW-DIG/metawal-core-geonetwork/commit/356cc8f8ddc98ba234f4fb6dad8b0bb00ec47f3b)
> 
> Dans Admin > CSW, choisir la fiche qui correspond au CSW
> 
> ![image](https://user-images.githubusercontent.com/1701393/73259049-3c0cf180-41c7-11ea-9db2-213d78b15de2.png)
> 
> Tester
> http://localhost:8080/geonetwork/srv/fre/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetCapabilities
> 
> Pour les CSW virtuels, je propose de migrer vers la notion de portail (en v4, les CSW virtuels sont supprimés) (d'autant plus qu'il y a un proxy devant)
> 
> ![image](https://user-images.githubusercontent.com/1701393/73259094-4e872b00-41c7-11ea-85f6-711339250b34.png)
> 
> Donc créer autant de portail que de CSW virtuel avec le même filtre.
> L'URL http://localhost:8080/geonetwork/srv/fre/csw-inspire devient alors http://localhost:8080/geonetwork/inspire/fre/csw
> et choisir la fiche correspondant au portail
> 
> Modifier la conf du proxy devant.

Ah oui, je suis plutôt favorable à cela. Mais attention, il faudra que nous soyons vigilant car certaines de ces URL sont utilisées par d'autres applications pour nous moissonner, dont le INSPIRE geoportal.

**Comment by stephyritz** [comment]
Getcapabilities obtenu par ce biais testé à travers le validateur : 
http://inspire.ec.europa.eu/validator/v2/TestRuns/EID8586fabf-a17f-44e5-9c42-23c244d45457.html

Apparemment, nous avons des problème de conformité lié au langage.
Peut-être car absence de déclaration d'un "ResponseLanguage"?

**Comment by fxprunayre** [comment]
* Pb de XSD:

```
Schema not valid: [org.xml.sax.SAXException: Fatal error: org.xml.sax.SAXParseException; 
lineNumber: 274; columnNumber: 34; cvc-complex-type.2.4.a: Invalid content was found starting with element 'inspire_com:Conformity'. One of 
'{"http://inspire.ec.europa.eu/schemas/common/1.0":TemporalReference}' is expected.
 Response did not validate against schema 'http://www.opengis.net/cat/csw/2.0.2 
http://schemas.opengis.net/csw/2.0.2/CSW-discovery.xsd 
http://inspire.ec.europa.eu/schemas/inspire_ds/1.0 
http://inspire.ec.europa.eu/schemas/inspire_ds/1.0/inspire_ds.xsd'.]
```

Donc il faut ajouter une étendue temporelle dans la fiche.
![image](https://user-images.githubusercontent.com/1701393/74131996-e03e6180-4be5-11ea-9f4f-a43a2c6bc916.png)
Ensuite on a
![image](https://user-images.githubusercontent.com/1701393/74132004-e46a7f00-4be5-11ea-896b-6e5534f38d34.png)
http://metawal4.test.wallonie.be/geonetwork/srv/fre/csw?SERVICE=CSW&REQUEST=GetCapabilities&VERSION=2.0.2&language=fre

Après ajout ok pour la date http://inspire.ec.europa.eu/validator/v2/TestRuns/EID6d5e049f-308a-4d46-9345-530230596fd7.html#EID2e2cafbe-0170-1000-dde2-575a899aa7fa


* Pb de langue (https://github.com/geonetwork/core-geonetwork/pull/4434)

```
Schema not valid: [org.xml.sax.SAXException: Fatal error: org.xml.sax.SAXParseException; lineNumber: 452; columnNumber: 36; cvc-enumeration-valid: Value '' is not facet-valid with respect to enumeration '[bul, cze, dan, dut, eng, est, fin, fre, ger, gre, hun, gle, ita, lav, lit, mlt, pol, por, rum, slo, slv, spa, swe]'. It must be a value from the enumeration. Response did not validate against schema 'http://www.opengis.net/cat/csw/2.0.2 http://schemas.opengis.net/csw/2.0.2/CSW-discovery.xsd http://inspire.ec.europa.eu/schemas/inspire_ds/1.0 http://inspire.ec.europa.eu/schemas/inspire_ds/1.0/inspire_ds.xsd'.]
```
pourtant ligne 452
![image](https://user-images.githubusercontent.com/1701393/74132595-3233b700-4be7-11ea-9783-c9a6f425ed62.png)

http://metawal4.test.wallonie.be/geonetwork/srv/fre/csw?language=fre&REQUEST=GetCapabilities&SERVICE=CSW&VERSION=2.0.2

A redéployer pour tester si c'est mieux.

**Comment by davinciagf** [comment]
Problème sur la machine, le xl deploy ne semble pas avoir stoppé correctement. J'ai demandé un restart mais sans doute pour lundi.

> 07-Feb-2020 16:27:22.005 WARNING [ContainerBackgroundProcessor[StandardEngine[Catalina]]] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [geonetwork] appears to have started a thread named [WeakCollectionCleaner] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
>  java.lang.Object.wait(Native Method)
>  java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
>  java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
>  org.geotools.util.WeakCollectionCleaner.run(WeakCollectionCleaner.java:77)

**Comment by davinciagf** [comment]
Retesté sur base du nouveau déploiement - erreur de language identique

**Comment by davinciagf** [comment]
Retesté sans erreur :
http://inspire.ec.europa.eu/validator/v2/TestRuns/EID04f8ad19-8bb3-48cd-9c03-4333149c4b06.html

**Comment by stephyritz** [comment]
Ok le test passe avec quand même pas mal de warnings. On analysera ça plus en détail après la mise en prod. Le travail fait pour la 3.8.10 est déjà une belle avancée sur le sujet.

**Comment by stephyritz** [comment]
Parfait. Testé ce jour sur le validateur INSPIRE et OK après avoir paramétrer la fiche correspondante dans l'interface d'admin et ajout de TemporalReference dans la fiche de MD.
