### ISSUE TITLE
Ajout d'un système de landing page 

### ISSUE THREAD

**Issue by davinciagf** [SPW-DIG/metawal-core-geonetwork#504]
- Formater spécifique pour landing page
- Lien symbolique entre serveur MW et Géoportail
- Pointage au niveau robot.txt du Géoportail

**Comment by fxprunayre** [comment]
Dans un premier temps, je propose de voir s'il est possible d'ajouter Metawal dans la sitemap du géoportail. Le point d'entrée d'un moteur de recherche devrait être : https://geoportail.wallonie.be/robots.txt

"You can specify more than one Sitemap file per robots.txt file." cf. https://www.sitemaps.org/protocol.html#submit_robots

Donc il faudrait ajouter http://metawal.wallonie.be/geonetwork/srv/fre/portal.sitemap qui pointera vers http://metawal4.test.wallonie.be/geonetwork/srv/api/records/5bb1c85c-abe1-46b3-9af6-489ab95cd0cb (qui contient le JSON-LD pour le google dataset search tool).

Dans un second temps, nous pourrons voir pour améliorer la landing page si besoin.

@stephyritz je te laisse voir avec l'équipe geoportail pour l'ajout de la ref dans la sitemap.

**Comment by stephyritz** [comment]
Ok, merci pour les précisions. J'ai transmis à l'équipe Géoportail. Je signale dès qu'il y a du neuf sur ce sujet.

**Comment by stephyritz** [comment]
Demande transmise à l'équipe du Géoportail. Une fois le robot.txt modifié dans le GP, aucune action à faire côté MW. La version GN4 apporte de multiples améliorations à ce sujet.
