### ISSUE TITLE
Ressource en ligne / Protocole DB & FILE

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#505]
- [x] Editeur / Ajout de choix DB et FILE:RASTER/VECTOR dans la liste de choix

* https://github.com/geonetwork/core-geonetwork/pull/4383
* https://github.com/metadata101/iso19115-3.2018/pull/23

```xml
<mrd:onLine>
                  <cit:CI_OnlineResource>
                     <cit:linkage>
                        <gco:CharacterString>dbora:schema</gco:CharacterString>
                     </cit:linkage>
                     <cit:protocol>
                        <gco:CharacterString>DB:ORACLE</gco:CharacterString>
                     </cit:protocol>
                     <cit:name>
                        <gco:CharacterString>tablename</gco:CharacterString>
                     </cit:name>
                     <cit:function>
                        <cit:CI_OnLineFunctionCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_OnLineFunctionCode"
                                                   codeListValue="fileAccess"/>
                     </cit:function>
                  </cit:CI_OnlineResource>
               </mrd:onLine>
               <mrd:onLine>
                  <cit:CI_OnlineResource>
                     <cit:linkage gco:nilReason="withheld">
                        <gco:CharacterString>/geo/data/dgo3_dada.ecw</gco:CharacterString>
                     </cit:linkage>
                     <cit:protocol>
                        <gco:CharacterString>FILE:RASTER</gco:CharacterString>
                     </cit:protocol>
                     <cit:name>
                        <gco:CharacterString>Données au format ECW</gco:CharacterString>
                     </cit:name>
                     <cit:function>
                        <cit:CI_OnLineFunctionCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_OnLineFunctionCode"
                                                   codeListValue="fileAccess"/>
                     </cit:function>
                  </cit:CI_OnlineResource>
               </mrd:onLine>
```

- [x] UFO / Pas de withheld

- [x] Publish / Do not check download by default. Intranet / Check all. GN ref https://github.com/geonetwork/core-geonetwork/pull/4405

- [ ] Tester que quand il y a download pour un groupe, les infos ne sont pas affichées

**Comment by fxprunayre** [comment]
A déployer et tester. Sur publish, les privilèges sont maintenant:
![image](https://user-images.githubusercontent.com/1701393/73239635-fdfad800-419c-11ea-8613-fb4bebade1c2.png)
par défaut.

**Comment by davinciagf** [comment]
Ne pas oublier de référencer gco:nilReason="withheld" du niveau du linkage dans le xml.
`<cit:linkage` `gco:nilReason="withheld">`
 afin d'éviter que les liens ne soient exposées publiquement (si la case télécharger est coché pour "tous").

**Comment by stephyritz** [comment]
Est-ce que tu peux vérifier si, depuis l’extérieur et sans authentification, tu peux voir l'info concernant l'emplacement en DB pour cette fiche : http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search;jsessionid=A7BCDDC4C39A5B47CA73A8A328419855?node=srv#/metadata/968514e6-04f7-4a84-b083-f2680435f5f2 ? Si oui, alors les paramètres ne sont pas encore parfaits.

**Comment by davinciagf** [comment]
Voici les liens référencés depuis l'ext. SPW sans être identifié:
![image](https://user-images.githubusercontent.com/576292/74038639-d1c33080-49c0-11ea-9b8c-46c443412187.png)
Je vois le lien uniquement après authentification.

**Comment by stephyritz** [comment]
Merci, donc c'est good en environnement de test!

**Comment by stephyritz** [comment]
Je viens de remarquer un petit problème concernant ce point vis à vis de l'outil de validation INSPIRE qui me rappelle une discussion que nous avions eu il y a quelques temps maintenant. En effet, l'outil de validation vient checker si c'est bien une URL qui est mentionnée dans la balise gmd:MD_DigitalTransferOptions/gmd:onLine/gmd:CI_OnlineResource/gmd:linkage/gmd:URL.  Voir https://github.com/inspire-eu-validation/metadata/blob/2.0/datasets-and-series/resource-locator.md.
Or dans notre cas, lorsque l'on saisie l'emplacement en DB, ce n'est plus le cas. Soit on filtre cette information en 19139, soit on saisie sous forme d'URL (me semble tirer par les cheveux). Je pense que nous pouvons appuyer l'idée de ne pas forcer la présence d'une URL ici auprès de l'Europe ou alors choisir un autre endroit dans le xml (si existant) pour cette information. Est-ce vraiment une "online resource" ?

**Comment by fxprunayre** [comment]
Cf. https://github.com/inspire-eu-validation/community/issues/95 

Je ne pense pas que le validateur devrait vérifier toutes les URL. "Purpose: Test if there is a resource or the url that points to a resource that provides additional information about the set data set or data set series." devrait être considérer conforme si au moins une URL fournit des informations sur la ressource.

**Comment by stephyritz** [comment]
Cela fonctionne très bien, reste à voir comment ça se passe concernant la conformité INSPIRE.
