### ISSUE TITLE
Catalogue d'attributs à partir du service ESRI 

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#506]
eg.
https://geoservices.wallonie.be/arcgis/rest/services/INDUSTRIES_SERVICES/ESRS/MapServer/0?f=json
Mapping 19110

doc: https://developers.arcgis.com/rest/services-reference/layer-feature-service-.htm

**Comment by fxprunayre** [comment]
@stephyritz question. Pourquoi dans les fiches des données
eg. http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/9008e261-2c71-4d40-8513-fb970c4eec2b
l'accès REST pointe vers
https://geoservices.wallonie.be/arcgis/rest/services/AMENAGEMENT_TERRITOIRE/COMDEC/MapServer
et pas la layer 
https://geoservices.wallonie.be/arcgis/rest/services/AMENAGEMENT_TERRITOIRE/COMDEC/MapServer/0
?

**Comment by stephyritz** [comment]
Je pense que c'est lié à une contrainte technique actuelle du Geoviewer. Je vais me faire confirmer l'info par les collègues.

Par exemple, lors de l'ouverture d'une "donnée externe" sur WalonMap, seule l'url sans le N°de layer est acceptée.

![ex_rest_WOM](https://user-images.githubusercontent.com/34446202/72889018-14bdac80-3d0f-11ea-9fef-5a10806cb33e.png)


Idem et en relation : le paramètre #ADU de l'application permettant d'afficher WoM avec un service web en particulier ne fonctionne que dans le premier cas.

https://geoportail.wallonie.be/walonmap#ADU=https://geoservices.wallonie.be/arcgis/rest/services/AMENAGEMENT_TERRITOIRE/COMDEC/MapServer --> OK

https://geoportail.wallonie.be/walonmap#ADU=https://geoservices.wallonie.be/arcgis/rest/services/AMENAGEMENT_TERRITOIRE/COMDEC/MapServer/0 --> NOK

**Comment by fxprunayre** [comment]
GN ref
* https://github.com/geonetwork/core-geonetwork/pull/4385
* https://github.com/metadata101/iso19115-3.2018/pull/24

**Comment by fxprunayre** [comment]
> Je pense que c'est lié à une contrainte technique actuelle du Geoviewer.

Du coup, si l'URL se termine par /MapServer, le feature catalogue sera construit à partir de la layer 0. Si un id de layer est spécifié dans l'URL, on utilisera ça.

**Comment by stephyritz** [comment]
Exemple pour des services contenant plus d'informations : 
- https://geoservices.wallonie.be/arcgis/rest/services/EAU/BASSINS/MapServer/0
- https://geoservices.wallonie.be/arcgis/rest/services/EAU/RHW_SIMPLE/MapServer/0

Ce sont des layers qui font partie toutes les deux d'un service proposant plusieurs couches. Par contre, j'ai l'impression qu'ils ne reflètent pas une bonne pratique car la description des champs est faite dans l'alias...

Je pense pourtant qu'il existe un endroit dédié à cela en passant par ArcCatalogue/Metadonnées/Mise à jour des MD/Champs --> Définition.

Je vais voir avec les producteurs de données si ça ne serait pas mieux de faire ainsi et ensuite de fournir un "service exemple" à tester.

**Comment by fxprunayre** [comment]
> t pas une bonne pratique car la description des champs est faite dans l'alias...

Je pense que l'usage d'Alias est ok - nom de la colonne (en plus du code). Il ne semble pas y avoir de definition dans la doc https://developers.arcgis.com/rest/services-reference/layer-feature-service-.htm. Ce que nous pouvons éventuellement ajouter c'est la gestion des domaines de valeurs.

**Comment by stephyritz** [comment]
Ok, je crois que ça dépend pas mal des données et des producteurs. Il y a bien une valeur dédiée à la définition de l'attribut dans arcmap 10.5 mais qui est peu utilisé et sans doute pas visible à travers le service REST actuellement. Peu importe, c'est déjà très bien si on peut importer le nom des champs, l'alias et le type depuis le REST vers la fiche dans Metawal. Pas la peine d'aller beaucoup plus loin pour la 3.10. 

Cette année, il y aura des process liée à la qualité qui vont être mis en place au moment de l'intégration de données dans notre infrastructure. Parmi les checks, il y aura une vérif entre le modèle de donnée souhaité et celui de la donnée diffusée. A ce moment-là, les informations concernant les attributs seront de toute façon exportée dans un format pivot. Nous pourrons donc utiliser cette source de donnée à ce moment-là et peut-être que cela se fera sans les technologies REST. 

Mais d'ici là, c'est bien si on peut tout de même mettre à jour l'existant à partir des services REST plutôt que de ne rien avoir ou avoir des pdf qui ne sont plus d'actualité.

**Comment by stephyritz** [comment]
Le validateur détecte une erreur de schema pour une fiche dont j'ai importé les attributs  : 
http://inspire.ec.europa.eu/validator/v2/TestRuns/EIDb805d640-6ff3-4a88-8f4c-042fec6cf75f.html

Le message d'erreur : 

> The metadata record set has 1 record(s) with errors for this assertion.
> XML document 'csw-inspire.xml', record 'd1a80c5c-419e-47fe-85e2-269792a6f9a2': 'Validation failed: 521:30: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.isotc211.org/2005/gmd":MD_FeatureCatalogue}'. One of '{"http://www.isotc211.org/2005/gmd":AbstractMD_ContentInformation}' is expected.Validation failed: http://www.isotc211.org/2005/gmd/gmd.xsd, 2:35: s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. Saw '301 Moved Permanently'.Validation failed: 222:104: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.isotc211.org/2005/gmx":Anchor}'. One of '{"http://www.isotc211.org/2005/gco":CharacterString}' is expected.'.
>

**Comment by fxprunayre** [comment]
GN ref https://github.com/metadata101/iso19115-3.2018/pull/34

**Comment by davinciagf** [comment]
Semble ok:
http://inspire.ec.europa.eu/validator/v2/TestRuns/EID9af21ec7-8cdd-43be-bd3d-14eacb3e95f9.html

**Comment by stephyritz** [comment]
Ok. Problème résolu en n'exposant pas ces informations en 19139 si je comprends bien car non inclus dans le schéma ce cette ISO.

**Comment by fxprunayre** [comment]
> si je comprends bien car non inclus dans le schéma ce cette ISO.

Oui car en 19139 on peut avoir une citation vers un modèle de données mais pas le modèle de données en tant que tel dans la fiche. Pour ça, avant on faisait une fiche en ISO19110 qu'on associait avec une en 19139. En 115-3 on peut mettre directement le catalogue d'attributs dans la fiche principale (ou un citation comme avant).
