### ISSUE TITLE
Recherche / Améliorations 

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#508]
## Tâches

- [x] Créer une branche metawal basée sur la branche Elasticsearch de GN
https://github.com/SPW-DIG/metawal-core-geonetwork/tree/metawal-4.0.x

- [x] Configuration facette metawal

- [x] Configuration pour indexation du français
 
- [x] Installer ES+Kibana(+Logstash) sur test

- [ ] Vérifier conf avec DTIC (et l'installation de plugin)

* https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-icu.html

```
elasticsearch-plugin install analysis-icu
```

- [ ] Corriger les pbs rencontrés https://teams.microsoft.com/_#/docx/viewer/aggregatefiles/https:~2F~2Fwalloniegov.sharepoint.com~2Fsites~2FMetawal374~2FDocuments%2520partages~2FGeneral~2FTesting_GN4.docx?baseUrl=https:~2F~2Fwalloniegov.sharepoint.com~2Fsites~2FMetawal374&fileId=a086d308-6fa8-4570-b947-6c74b50c250a&ctx=aggregate&viewerAction=view

## Différences

* Facette / Organisation / Hiérarchie
v4
![image](https://user-images.githubusercontent.com/1701393/81716482-b82afc80-9479-11ea-955c-a560d196bbcd.png)
v3
![image](https://user-images.githubusercontent.com/1701393/81716600-da247f00-9479-11ea-8fba-5e2a52afbf08.png)

**Comment by stephyritz** [comment]
De mon point de vue ce n'est pas une priorité. Je pense qu'on pourra prendre la meilleure des décisions quand nous aurons mis en place l'annuaire pour les contacts.
