### ISSUE TITLE
Export ZIP / Par défaut ne pas exporter les fiches associées

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#509]
GN ref https://github.com/geonetwork/core-geonetwork/pull/4400

**Comment by fxprunayre** [comment]
A déployer et tester.

**Comment by stephyritz** [comment]
Certains collègues m'ont fait part de leur intérêt de conserver les ressources associées (uniquement les parents si possible) en plus. Prévoir un bouton "Export zip avec ressources en parenté" ?
