### ISSUE TITLE
Edition / Impossible de supprimer une ressource de type Modèle de données

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#510]
Le bouton "supprimer" du volet de droite dédié aux ressources en ligne est non fonctionnel pour les modèles de données. 
To reproduce : 
1. Editer une fiche
2. Cliquer sur le bouton supprimer d'une ressource en ligne type modèle de donnée
3. Message d'avertissement --> Cliquer sur OK
4. Symbole de chargement comme si l'action de supprimer allait bien se faire
5. La ressource n'est pas supprimer, retour à 1.

**Comment by fxprunayre** [comment]
GN ref. https://github.com/metadata101/iso19115-3.2018/pull/33
