### ISSUE TITLE
INSPIRE / Format de distribution et Version

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#511]
Il semblerait que les fiches faisant référence à un format de distribution sans version soient considérées comme non conforme par le validateur.

Exemple --> http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID25673afa-9d85-4b31-9588-6981483ea8b7.html
pour la fiche http://metawal.wallonie.be/geonetwork/srv/fre/csw-inspire?request=GetRecordById&service=CSW&outputSchema=http://www.isotc211.org/2005/gmd&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=d1a80c5c-419e-47fe-85e2-269792a6f9a2

J'ai l'impression que cela est dû à un encodage du nilReason="unknown" en ISO19139 qui n'est pas conforme à ce qui est attendu dans le test (https://github.com/inspire-eu-validation/metadata/blob/2.0/isdss/data-encoding.md).

En effet, actuellement, en l'absence de valeur, le xsl de conversion to19139 semble écrire une balise du type : <gmd:version nilReason="unknown"/>

Or, le test mentionne ceci : check that it has an attribute gco:nilReason="unknown"
Donc peut-être qu'il faudrait une structure du style : 

```
<gmd:version>
   <gco:nilReason="unknown"/>
</gmd:version>
```

pour que cela soit conforme. Qu'en pensez-vous ?
A tester et si ça fonctionne, à intégrer dans le xsl to19139 lors du déploiement prévu en février car problème relativement important.

**Comment by davinciagf** [comment]
- [x] Modifier le xsl de transfo pour le 39

`<gmd:version gco:nilReason="unknown" />`

 - [x] A tester sur le validateur
OK --> http://inspire.ec.europa.eu/validator/v2/TestRuns/EIDb805d640-6ff3-4a88-8f4c-042fec6cf75f.html
