### ISSUE TITLE
Recherche / Ergonomie

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#513]
Sur la page d'accueil, exécuter une recherche en utilisant la touche "enter" sans passer par les suggestions renvoie à une recherche vide sur la page 'Recherche'.

Pour reproduire :
1. Aller sur la page d'accueil de Metawal (http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/home)
2. Taper un mot dans la barre de recherche et appuyer sur la touche Enter
3. Redirection vers la page de recherche avec la recherche vide

A noter : ce comportement n'est observé que lorsque l'utilisateur fait sa recherche avec la touche "enter" en utilisant firefox (OK avec IE, Edge). Fonctionnement aussi OK en cliquant sur la loupe ou en utilisant les suggestions.

**Comment by stephyritz** [comment]
Comportement NOK en V4. On déplace ce ticket en future release ?

**Comment by vbombaerts** [comment]
Testé et OK
