### ISSUE TITLE
Contenu / Condition d'accès et d'utilisation

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#514]
On m'a signalé qu'une coquille s'est visiblement glissée dans notre xsl mw-constraints-cleanup.
La valeur du texte concernant le cas CGA/CGU + CPU type C est actuellement : 

> ACCÈS : Les conditions générales d'accès s’appliquent (https://geoportail.wallonie.be/files/documents/ConditionsSPW/DataSPW-CGA.pdf). UTILISATION : Les conditions générales d'utilisation s'appliquent (https://geoportail.wallonie.be/files/documents/ConditionsSPW/DataSPW-CGU.pdf) **mais sont restreintes** par les conditions particulières de type C (https://geoportail.wallonie.be/files/documents/ConditionsSPW/DataSPW-CPU-TypeC.pdf).

Mais devrait être : 

> ACCÈS : Les conditions générales d'accès s’appliquent (https://geoportail.wallonie.be/files/documents/ConditionsSPW/DataSPW-CGA.pdf). UTILISATION : Les conditions générales d'utilisation s'appliquent (https://geoportail.wallonie.be/files/documents/ConditionsSPW/DataSPW-CGU.pdf) **et sont étendues** par les conditions particulières de type C (https://geoportail.wallonie.be/files/documents/ConditionsSPW/DataSPW-CPU-TypeC.pdf).

Je n'ai pas réussi à trouver le xsl correspondant sur le github, le lien mentionnée dans le ticket https://github.com/SPW-DIG/metawal-core-geonetwork/issues/503 n'étant plus valide. Mais il est sûrement la cause de cette "erreur". A modifier si possible dans le xsl en parallèle de la modification du contenu de la DB.

26 fiches sont concernées. Résultat de la requête suivante en prod : 
```
SELECT * from metawal4.metadata
WHERE data LIKE '%mais sont restreintes par les conditions particulières de type C (https://geoportail.wallonie.be/files/documents/ConditionsSPW/DataSPW-CPU-TypeC.pdf).%'
```

Solution proposée, en DB : 
`UPDATE metawal4.metadata SET data = replace(data, 'mais sont restreintes par les conditions particulières de type C (https://geoportail.wallonie.be/files/documents/ConditionsSPW/DataSPW-CPU-TypeC.pdf).', 'et sont étendues par les conditions particulières de type C (https://geoportail.wallonie.be/files/documents/ConditionsSPW/DataSPW-CPU-TypeC.pdf).' WHERE data LIKE '%mais sont restreintes par les conditions particulières de type C (https://geoportail.wallonie.be/files/documents/ConditionsSPW/DataSPW-CPU-TypeC.pdf).%)`

La requête vous semble correcte ?
@davinciagf, tu peux essayer de la jouer en test pour voir ?
Si ça fonctionne bien, on peut éventuellement l’intégrer dans les SQL à jouer pour le déploiement de la 3.10 sinon, au pire, je ferais un ticket séparé.

**Comment by fxprunayre** [comment]
Fixed in https://github.com/SPW-DIG/iso19115-3.2018/commit/8764ae0bfeb89b8ac6bc04dffe378579e0b99b9b

@davinciagf je te laisse faire la modif en base et vérifier le process.

**Comment by davinciagf** [comment]
Requête de transformation déjà jouée dans la précédente mise en prod.

Requête de modification en base:

`UPDATE metadata SET data = replace(data,'UTILISATION : Les conditions générales d''utilisation s''appliquent (https://geoportail.wallonie.be/files/documents/ConditionsSPW/DataSPW-CGU.pdf) mais sont restreintes par les conditions particulières de type C (https://geoportail.wallonie.be/files/documents/ConditionsSPW/DataSPW-CPU-TypeC.pdf).</gco:CharacterString>','UTILISATION : Les conditions générales d''utilisation s''appliquent (https://geoportail.wallonie.be/files/documents/ConditionsSPW/DataSPW-CGU.pdf) et sont étendues par les conditions particulières de type C (https://geoportail.wallonie.be/files/documents/ConditionsSPW/DataSPW-CPU-TypeC.pdf).</gco:CharacterString>') WHERE data LIKE '%UTILISATION : Les conditions générales d''utilisation s''appliquent (https://geoportail.wallonie.be/files/documents/ConditionsSPW/DataSPW-CGU.pdf) mais sont restreintes par les conditions particulières de type C (https://geoportail.wallonie.be/files/documents/ConditionsSPW/DataSPW-CPU-TypeC.pdf).</gco:CharacterString>%' ;`

Joué en test sur la fiche : http://metawal4.test.wallonie.be/geonetwork/srv/eng/catalog.search#/metadata/647e383d-c74b-4ee6-bf48-a5ebc746e8bf 

Requête à introduire si ok dans la mise en production 3.10.0

**Comment by stephyritz** [comment]
Ok pour la modif en db. Résultat satisfaisant sur la fiche mentionnée, peut être joué en test sur toutes les fiches. Puis, si tout est OK, à intégrer dans la MeP 3.10.

**Comment by stephyritz** [comment]
La coquille est restée présente dans le xsl déployé en prod. Par conséquent, le contenu n'est pas bon pour toutes les fiches INSPIRE. Exemple : http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/b795de68-726c-4bdf-a62a-a42686aa5b6f

Proposition de requête à jouer en DB pour la 3.10.1 :

`UPDATE metadata SET data = replace(data,'Les conditions générales d\'utilisation s\'appliquent mais sont restreintes par les conditions particulières de type C.','Les conditions générales d\'utilisation s\'appliquent et sont étendues par les conditions particulières de type C.')`

Il devrait y avoir 28 fiches concernées en prod d'après le select correspondant fait sur la DB de prod. 

En test, aucun résultat visiblement car le xsl permettant le split n'a pas été joué. Donc : 
1. Jouer le xsl de split en test
2. Jouer la requête DB
Si OK : 
3. Intégration de la requête SQL en DB dans les instructions de déploiement de la 3.10.1

**Comment by stephyritz** [comment]
Étape 1 : OK

Etape 2 : OK
Requête jouée en DB de test : 

`UPDATE metawal4.metadata SET data = replace(data, 'Les conditions générales d''utilisation s''appliquent mais sont restreintes par les conditions particulières de type C.', 'Les conditions générales d''utilisation s''appliquent et sont étendues par les conditions particulières de type C') WHERE data LIKE '%Les conditions générales d''utilisation s''appliquent mais sont restreintes par les conditions particulières de type C.%'`

Etape 3 : OK en TEST puis exécuté en PROD
Batchedit via la console avec la valeur suivante : 

```
<mco:MD_LegalConstraints xmlns:mco="http://standards.iso.org/iso/19115/-3/mco/1.0" xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0" xmlns:gcx="http://standards.iso.org/iso/19115/-3/gcx/1.0" xmlns:xlink="http://www.w3.org/1999/xlink">
  <mco:useLimitation>
    <gco:CharacterString>Conditions d'utilisation spécifiques</gco:CharacterString>
  </mco:useLimitation>
  <mco:useConstraints>
    <mco:MD_RestrictionCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_RestrictionCode" codeListValue="otherRestrictions"/>
  </mco:useConstraints>
  <mco:otherConstraints>
    <gcx:Anchor xlink:href="https://geoportail.wallonie.be/files/documents/ConditionsSPW/LicServicesSPW.pdf">Les conditions d'utilisation du service sont régies par les conditions d’accès et d’utilisation des services web géographiques de visualisation du Service public de Wallonie.</gcx:Anchor>
  </mco:otherConstraints>
</mco:MD_LegalConstraints>

```

Je vais faire le ticket DTIC pour que le SQL de l'étape 2 soit déployé en valid/prod.

**Comment by stephyritz** [comment]
SQL joué en prod hier.
