### ISSUE TITLE
Edition / Ajout d'une ressource de type légende (LYR)

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#515]
Impossible d'associer une légende à une fiche.
To reproduce : 
1. Ouvrir une fiche en mode édition
2. Ajouter une ressource en ligne
3. Sélectionner dans le menu déroulant Type de lien = Légende pour ArcGIS (LYR)
4. Renseigner une URL et un nom (par ex. https://geoservices.wallonie.be/arcgis/rest/services/INDUSTRIES_SERVICES/ESRS/MapServer/legend)
5. "Ajouter une ressource en ligne" pour valider
6. Popup avec message d'erreur vide et la légende n'est pas associée à la fiche

**Comment by fxprunayre** [comment]
Fixed by https://github.com/metadata101/iso19115-3.2018/pull/42
