### ISSUE TITLE
Cosmétique / Rennomage de l'onglet dans les env. de test/valid

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#516]
Actuellement, le titre de l'onglet de Metawal en environnement de test est "Metawal 3". Est-il possible de modifier le title de l'html pour que cela devienne "Metawal - Test" ? On peut imaginer le même système pour l'environnement de valid (actuellement title = url).

![onglet_metawal_test](https://user-images.githubusercontent.com/34446202/75136528-49919a80-56e5-11ea-8bf3-d889a7458cc6.png)

**Comment by fxprunayre** [comment]
Cf. http://metawal4.test.wallonie.be/geonetwork/srv/fre/admin.console#/settings/sources

![image](https://user-images.githubusercontent.com/1701393/75559490-d8831780-5a43-11ea-81be-18a83c2ded17.png)

Je te laisse faire la manip ?

**Comment by stephyritz** [comment]
Merci. Mais toujours un problème.

J'ai renommé et enregistré.
Le message d'erreur suivant est apparu :

![rename_html_title_mw_test](https://user-images.githubusercontent.com/34446202/75656387-1cecfe00-5c64-11ea-99b8-de21d1f416a7.png)

Et j'ai l'impression que cela a abouti à la création d'un nouveau catalogue source (manip faite 2 fois avec 'Metawal' et Metawal - test).

**Comment by fxprunayre** [comment]
```sql


DELETE Sourcesdes WHERE iddes = 'metawal.wallonie.be';
INSERT INTO Sourcesdes (iddes, label, langid) VALUES ('metawal.wallonie.be', 'Metawal - Catalogue pour l''information géographique de Wallonie', 'fre');
INSERT INTO Sourcesdes (iddes, label, langid) VALUES ('metawal.wallonie.be', 'Metawal - Catalogue pour l''information géographique de Wallonie', 'eng');
INSERT INTO Sourcesdes (iddes, label, langid) VALUES ('metawal.wallonie.be', 'Metawal - Catalogue pour l''information géographique de Wallonie', 'dut');
INSERT INTO Sourcesdes (iddes, label, langid) VALUES ('metawal.wallonie.be', 'Metawal - Catalogue pour l''information géographique de Wallonie', 'ger');
UPDATE Sources SET name = 'Metawal - Catalogue pour l''information géographique de Wallonie' WHERE uuid = 'metawal.wallonie.be';


```

A jouer en test avec metawal4.test.wallonie.be

**Comment by stephyritz** [comment]
J'ai des erreurs de synthaxe quand je reproduis ton sql depuis pgadmin. J'ai donc utilisé cette commande : 
```
DELETE FROM metawal4.Sourcesdes WHERE iddes = 'metawal4.test.wallonie.be';
INSERT INTO metawal4.Sourcesdes (iddes, label, langid) VALUES ('metawal4.test.wallonie.be', 'Metawal - TEST', 'fre');
INSERT INTO metawal4.Sourcesdes (iddes, label, langid) VALUES ('metawal4.test.wallonie.be', 'Metawal - TEST', 'eng');
INSERT INTO metawal4.Sourcesdes (iddes, label, langid) VALUES ('metawal4.test.wallonie.be', 'Metawal - TEST', 'dut');
INSERT INTO metawal4.Sourcesdes (iddes, label, langid) VALUES ('metawal4.test.wallonie.be', 'Metawal - TEST', 'ger');
UPDATE metawal4.Sources SET name = 'Metawal - TEST' WHERE uuid = 'metawal4.test.wallonie.be'; 
```

Mais je n'ai visiblement pas les droits pour faire cette action :

> ERROR:  permission denied for relation sourcesdes
> SQL state: 42501
>

@davinciagf, tu peux essayer de le faire de ton côté ?

**Comment by stephyritz** [comment]
Ok ça a fonctionné mais tu n'as pas pris les valeurs que je souhaitais, à savoir "Metawal - TEST". En effet, c'est un peu bête mais ça me permet, en un coup d'oeil à l'onglet de savoir que c'est MW de test.

**Comment by davinciagf** [comment]
Modifié en Metawal - TEST

**Comment by fxprunayre** [comment]
http://metawal.wallonie.be/geonetwork/srv/fre/admin.console#/settings/sources

* Lister les fiches du portail sélectionné (à faire en v4 uniquement - en v3 problème d'avoir plusieurs recherches dans le même controller)
* Si pas de fiche, on peut supprimer (en v3)
* Renommer le portail principal

**Comment by fxprunayre** [comment]
Au final j'ai fait le ménage à la main via l'API. 

On a donc 
![image](https://user-images.githubusercontent.com/1701393/84893244-385b0800-b09f-11ea-94df-7e642db28f26.png)

J'ai utilisé les opérations (qui ne sont pas forcément toutes utilisables directement via l'interface)
* suppression
* renommage

![image](https://user-images.githubusercontent.com/1701393/84893359-63ddf280-b09f-11ea-8359-74284b42d96d.png)


Il reste 4 moissonneurs. @stephyritz je te laisse vérifier leur config et les supprimer si on n'en a pas besoin http://metawal.wallonie.be/geonetwork/srv/fre/admin.console#/harvest

Pour les modifs d'interface je ferai ça plutôt en v4, car en v3, ce n'est pas trivial d'avoir 2 recherches dans la même page ce qui est le cas ici.
