### ISSUE TITLE
INSPIRE / Schema error en ISO 19139

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#517]
Il semblerait que les balises suivantes en ISO 19115-3 soient source d'erreur de schéma en 19139 : 

19115-3 : 

```
   <mdb:portrayalCatalogueInfo>
      <mpc:MD_PortrayalCatalogueReference/>
  </mdb:portrayalCatalogueInfo>
```

19139 : 
```
<gmd:portrayalCatalogueInfo>
   <gmd:MD_PortrayalCatalogueReference/>
</gmd:portrayalCatalogueInfo>
```

Exemple de MD : http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/d52095c0-d33c-44b9-a593-6e861c079997

Résultat du test de conformité : http://inspire.ec.europa.eu/validator//v2/TestRuns/EID9cc81087-eeb7-43cc-9337-88692fc97573.html

PS : à quoi sert cette balise ? Je n'ai pas le souvenir de l'avoir ajouté.

**Comment by stephyritz** [comment]
Balise associée à la légende j'ai l'impression. Peut-être lié à https://github.com/SPW-DIG/metawal-core-geonetwork/issues/515 ?

**Comment by fxprunayre** [comment]
> PS : à quoi sert cette balise ? Je n'ai pas le souvenir de l'avoir ajouté.

Le pb est que quand on supprime une légende on ne supprime pas le bloc portrayal mais juste la référence de la légende. On se retrouve alors avec un bloc vide. Je ne sais pas ce qui est le mieux pour corriger ça.

**Comment by fxprunayre** [comment]
GN ref: https://github.com/metadata101/iso19115-3.2018/pull/45

**Comment by davinciagf** [comment]
A tester

**Comment by stephyritz** [comment]
Je pense que nous avons un problème similaire avec les ressources associées.
La suppression d'une fiche mentionnée en ressource associée "laisse une trace" dans le xml (balise <mri:associatedResource/>). Ceci cause une erreur de conformité à travers l'outil de validation INSPIRE. 
To reproduce : 
1. Entrer en mode édition d'une fiche
2. Associer la fiche à une autre (par exemple partofthesamelessdatabase / Collection)
3. Supprimer la ressource associée
4. Balise résiduelle obtenue dans le xml <mri:associatedResource/>

Je pense que cela est aussi le cas pour les autres types d'association (lien de parenté, référence croisée, etc...).

**Comment by stephyritz** [comment]
Idem pour les services associés.

**Comment by fxprunayre** [comment]
> 4\. Balise résiduelle obtenue dans le xml mri:associatedResource/

https://github.com/metadata101/iso19115-3.2018/pull/53

Update en base à faire

```sql
UPDATE metadata SET data = replace(data, '<mri:associatedResource/>', '') WHERE data LIKE '%<mri:associatedResource/>%';
```


> Je pense que cela est aussi le cas pour les autres types d'association (lien de parenté, référence croisée, etc...).

A priori non pour les parents.

> Idem pour les services associés.

A priori non - faudrait préciser le cas de test.

**Comment by stephyritz** [comment]
> Idem pour les services associés.

To reproduce :
1. Supprimer toutes les ressources associées présentes dans la partie "distribution"
2. Balises résiduelles présentees ensuite dans le xml

```
         <mrd:transferOptions>
            <mrd:MD_DigitalTransferOptions/>
         </mrd:transferOptions>
```

La partie `<mrd:MD_DigitalTransferOptions/>` semble causer une erreur de schéma.

**Comment by fxprunayre** [comment]
> * Supprimer toutes les ressources associées présentes dans la partie "distribution"

Oui c'est le cas où on enlève le dernier restant. Je vais voir si on peut gérer ce cas.

**Comment by fxprunayre** [comment]
> La partie `<mrd:MD_DigitalTransferOptions/>` semble causer une erreur de schéma.

Fixed by https://github.com/metadata101/iso19115-3.2018/pull/56

A déployer et tester.

**Comment by stephyritz** [comment]
A revérifier pour les ressources associées.

**Comment by fxprunayre** [comment]
Clean up de `<mri:associatedResource>` fait en v4. Cf. https://github.com/SPW-DIG/metawal-core-geonetwork/commit/84c091ede9214f932448c53262782141ed6c6d80

**Comment by stephyritz** [comment]
OK en test
