### ISSUE TITLE
ISO 19139 / Informations liées au système de projection

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#521]
Je créé ce ticket suit au problème critique rencontré par le Géoportail suite à la modification de la structure des balises concernant les système de projection.
En résumé, voici ce que j'ai compris de la chaîne opérationnelle permettant le fonctionnement actuel du panier de téléchargement : 

1.	Encodage dans Metawal du système de projection dans la norme ISO19115-3 permettant d’encoder facilement le système de projection avec sa valeur, son url de référence, un label complet et le type de projection (voir http://metawal.wallonie.be/geonetwork/srv/api/records/12b56944-5a6a-4e0e-b8d8-41c47390816f/formatters/xml?approved=true)
2.	On envoie cette information via le service CSW dans la norme ISO19139 (norme imposée par la directive INSPIRE), standard sur lequel s’appuie le Géoportail pour obtenir les infos. C’est ici que l’on conserve juste la valeur avec le schéma ‘mw’ et valeur + url avec le schéma ‘gmd’.
3.	On parse le xml et on l’envoie en DB
4.	L’interface du Géoportail interprète ces infos
5.	On va rechercher une info de label grâce à l’url
6.	Le panier de téléchargement utilise ce label
7.	Le process FME d’extract de la donnée s’appuie sur ce label

Il me paraît quand même anormal qu'une simple modification comme le passage d'un characterstring à une anchor puisse poser un problème aussi critique que l'arrêt de fonctionnement du process de téléchargement sur le Géoportail.

Bref, je pense qu'on pourrait un minimum alléger la chaîne de traitement si on proposait de conserver le "label" (mcc:description/gco:characterstring en 115-3) lors du passage en ISO 19139. 

Mes questions sont les suivantes : 
Est-ce autorisé en 19139 ? 
Est-ce conforme INSPIRE ?
Si pas, est-ce que c'est le genre de chose qu'on pourrait implémenter dans le schéma "mw" ?

**Comment by stephyritz** [comment]
En attendant, le Géoportail s'est adapté à l'information provenant du schéma gmd (par défaut), c'est à dire avec un système d'ancre. Mais, dès que possible, ils vont quand même switcher vers le schéma 'mw' car d'autres aspects ne sont pas bien interprétés comme les résultat des CA/CU après split (pour l'instant uniquement les fiches INSPIRE).

Il faudrait donc adapter l'outputschema 'mw' pour qu'il renseigne maintenant les systèmes de prj sous formes d'ancres (idem à schéma par défaut).

**Comment by fxprunayre** [comment]
> Il faudrait donc adapter l'outputschema 'mw' pour qu'il renseigne maintenant les systèmes de prj sous formes d'ancres (idem à schéma par défaut).

Ok donc actuellement sur la requête :

```xml
<?xml version="1.0"?>
<csw:GetRecordById xmlns:csw="http://www.opengis.net/cat/csw/2.0.2"
                   service="CSW" version="2.0.2"
                   outputSchema="mw">
        <csw:ElementSetName>full</csw:ElementSetName>
  <csw:Id>d1a80c5c-419e-47fe-85e2-269792a6f9a2</csw:Id>
</csw:GetRecordById>
```
La réponse est :
```xml
    <gmd:referenceSystemInfo>
      <gmd:MD_ReferenceSystem>
        <gmd:referenceSystemIdentifier>
          <gmd:RS_Identifier>
            <gmd:code>
              <gco:CharacterString>EPSG:31370</gco:CharacterString>
```
La réponse devient :
```xml
    <gmd:referenceSystemInfo>
      <gmd:MD_ReferenceSystem>
        <gmd:referenceSystemIdentifier>
          <gmd:RS_Identifier>
            <gmd:code>
              <gmx:Anchor xlink:href="http://www.opengis.net/def/crs/EPSG/0/31370">EPSG:31370</gmx:Anchor>
```
Correct @stephyritz ?

**Comment by stephyritz** [comment]
Oui c'est cela. On considère que le Géoportail s'est adapté sur ce point et donc, à ce moment là la structure schéma "mw" = structure schéma par défaut.

**Comment by fxprunayre** [comment]
> Oui c'est cela. On considère que le Géoportail s'est adapté sur ce point et donc, à ce moment là la structure schéma "mw" = structure schéma par défaut.

Fait. A déployer et tester.

**Comment by davinciagf** [comment]
Redéployé en test.

**Comment by stephyritz** [comment]
Serait-il possible de m'envoyer ou d'envoyer directement à Didier le fichier de config en question ainsi que son emplacement et une description de la manip à faire de son côté ? Une fois que cette action sera faite, nous considérerons que la mise en prod 3.10 est clôturée.

**Comment by stephyritz** [comment]
Fichier de config remplacé par Didier Husson en valid et prod le 02/03/20
