### ISSUE TITLE
INSPIRE / Conformité des contacts

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#522]
Il y a plusieurs fiches "historiques" qui sont considérées comme non conformes car elles comportent des individus en contact sans adresse mail.
Ex : http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/b7725746-b5ef-46db-add4-d61a6cc3b8d3 ; http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/9d18f60b-9652-4c5c-bcc2-01560224eecc ; http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/73414a3a-fe93-49dd-9ecd-7137e54402cf.

Test de conformité --> http://inspire.ec.europa.eu/validator//v2/TestRuns/EID3a553d6f-293b-473c-92cc-a1f753f0219b.html

Comment pensez-vous qu'il faut gérer ces cas ? Des idées :  
- Contacter chaque gestionnaire et demander à ce qu'il recherche le mail des personnes mentionnées ? --> Fastidieux
-  Ajouter automatiquement le mail heldesk.carto à tous les contacts sans e-mail ? --> Permet de respecter la règle d'INSPIRE mais un peu tiré par les cheveux
- Filtrer ces informations lors du passage à la 19139 ? --> Perte de cette informations sur le Géoportail. Solution la moins pire mais qui ajoute des  "sparadraps" dans le xsl to19139 ce qui n'était pas une bonne pratique d'après François.
- ...

Depuis que je travaille sur les fiches, j'encourage à ne pas nommer des personnes d'autant plus que dans ce cas, on risque d'être soumis au RGPD. Mais bon... Ce n'est pas le point de vue de tout le monde chez les gestionnaires de données. Donc on devrait essayer de trouver une solution technique à ce problème.

**Comment by fxprunayre** [comment]
Dans les fiches en question il semble y avoir toujours au moins un contact avec un email - donc est-ce que la validation INSPIRE ne devrait pas se contenter de vérifier qu'il y a au moins un email et non tout contact doit avoir email ? On peut tenter de demander mais ca risque de faire comme pour les URLs ...

Je penche de plus en plus sur la création d'un CSW spécifique INSPIRE où l'on viendrait mettre des rustines pour être INSPIRE compliant et laisser les utilisateurs utiliser l'ISO dans son ensemble. Donc l'option 3. Qu'en pensez-vous ?

**Comment by stephyritz** [comment]
Franchement, ces deux cas me font penser que c'est une bonne option car, pour le coup, je trouve la règle de conformité INSPIRE bizarre. Donc, il n'est pas exclu qu'on puisse faire bouger les lignes sur ces sujets. A partir de là, il me semble pas inutile de sortir un résultat selon un schéma propre à INSPIRE pour être conforme en attendant sans pour autant dégrader notre contenu. Par contre, nous nous rajoutons un fichier de plus dont nous devons gérer la config donc cela nous demandera d'être encore plus vigilants. Je n'ai pas assez de recul dans le milieu pour être sûr que cela soit la bonne solution. Je vais voir ce qu'en pense les collègues et fais confiance à votre expertise.

**Comment by fxprunayre** [comment]
Je propose d'ajouter https://github.com/geonetwork/core-geonetwork/pull/1871 et de mettre en place un mécanisme de postprocessing spécifique au point d'entrée `/inspire/eng/csw`

Quelles règles mettons nous en place ? @stephyritz 
* suppression des contacts n'ayant pas d'email ?
* suppression des onlines resources n'ayant pas une URL http ?

**Comment by fxprunayre** [comment]
Peut être déployé pour test. La config a été faite pour un portail 'inspire'. Le CSW en 19139 a une réponse "post-processée" pour INSPIRE.

**Comment by stephyritz** [comment]
Merci, intéressant aussi d'avoir le point de vue de personnes extérieures au projet. C'est sûr qu'on ne va pas être les seuls dans ce cas...

Si je comprends bien, de mon côté il va falloir changer une redirection ?!
En effet, le endpoint officiel est actuellement : http://geoservices.wallonie.be/metawal/csw-inspire. J'imagine que Vincent ou Geoffroy avait demandé une redirection vers http://metawal.wallonie.be/geonetwork/srv/fre/csw-inspire. Donc si je comprends bien ce que tu proposes, il faudrait demander au DTIC une redirection vers http://metawal.wallonie.be/geonetwork/srv/inspire/fre/csw

Concernant les règles, je confirme : 
- Suppression des contacts sans e-mail dans la version 19139 INSPIRE
- Suppression des onlines resources sans URL de type http

Le mécansime de postprocessing sera configuré également par le biais d'un xslt du coup ?

**Comment by fxprunayre** [comment]
> il faudrait demander au DTIC une redirection vers http://metawal.wallonie.be/geonetwork/srv/inspire/eng/csw-inspire.

L'URL sera : http://metawal.wallonie.be/geonetwork/inspire/eng/csw
Oui les CSW virtuels seront supprimés en V4, donc autant passé sur le mode portail.



> Le mécansime de postprocessing sera configuré également par le biais d'un xslt du coup ?

Oui.

**Comment by fxprunayre** [comment]
Règles mises en place. Description du test dans https://github.com/geonetwork/core-geonetwork/pull/4493. A déployer et tester.

**Comment by davinciagf** [comment]
Testé après création du site `inspire` sur:  
http://metawal4.test.wallonie.be/geonetwork/inspire/fre/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetRecordById&ID=b7725746-b5ef-46db-add4-d61a6cc3b8d3&outputSchema=http://www.isotc211.org/2005/gmd&ElementSetName=full

**Comment by stephyritz** [comment]
Note : 
Demande de redirection au DTIC : http://geoservices.wallonie.be/metawal/csw-inspire --> http://metawal.wallonie.be/geonetwork/inspire/fre/csw une fois la mise en prod terminée.

**Comment by stephyritz** [comment]
Conformité OK -> https://inspire.ec.europa.eu/validator/v2/TestRuns/EIDaf996b26-e9c0-452b-bb56-22ab2ffaa049.html

**Comment by stephyritz** [comment]
C'est OK si je passe par l'interface web du validateur et que j'utilise l'url suivante : http://metawal.wallonie.be/geonetwork/inspire/fre/csw?request=GetRecordById&service=CSW&outputSchema=http://www.isotc211.org/2005/gmd&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=ffc45d44-1cc2-4924-bb8c-214096eb9058

Par contre depuis l'onglet "Contribuer" et en utilisant la "validation INSPIRE distante" ce n'est pas conforme. Peut-être faut-il faire une configuration spécifique pour que cet outil utilise l'url http://metawal.wallonie.be/geonetwork/inspire/fre/csw? plutôt que le csw virtuel ?

**Comment by stephyritz** [comment]
Au niveau des redirection ce n'est pas tout à fait clair pour moi.

Didier m'a décrit la situation actuelle comme telle pour "https://geoservices.wallonie.be"
```

        location /metawal/
{
                proxy_pass http://metawal4.wallonie.be/geonetwork/srv/fre/;
        access_log      /opt/nginx-3/logs/geoservices_metawal_access_log combined if=$log_ip;
        }
        location /geonetwork/
{
                proxy_pass http://metawal4.wallonie.be/geonetwork/;
        access_log      /opt/nginx-3/logs/geoservices_metawal_access_log combined if=$log_ip;
        }
```

Le endpoint déclaré à l'Europe est : http://geoservices.wallonie.be/metawal/csw-inspire

Mais, il ne suffit pas seulement de demander la redirection de http://geoservices/metawal sur http://metawal4.wallonie.be/geonetwork/inspire/fre.

Si je comprends bien : 

 - Soit on procède à la redirection ci-dessus ET on demande un changement de endpoint (http://geoservices.wallonie.be/metawal/csw-inspire --> http://geoservices.wallonie.be/metawal)

- Soit on procède à une redirection de type http://geoservices.wallonie.be/metawal/csw-inspire --> http://metawal.wallonie.be/geonetwork/inspire/fre/csw

D'ailleurs pourquoi avoir garder une redirection vers metawal4 ? Qui lui-même renvoie vers metawal.

**Comment by stephyritz** [comment]
http://geoservices.wallonie.be/metawal/csw-inspire --> http://geoservices.wallonie.be/metawal/inspire/fre/csw

Changement d'URL pour l'application ? --> Virer metawal.wallonie.be pour le catalogue et associé direct "http://geoservices.wallonie.be/metawal" ET rediriger metawal.wallonie.be vers cette url.

Renommer le war : geonetwork.war -->metawal.war

Supprimer toutes les autres redirections. Quid de metawal4 ? Redircige sur metawal ou l'inverse ?

**Comment by stephyritz** [comment]
Cette solution évoquée lors de notre dernier call est peut-être trop prématurée. J'ai demandé l'avis aux collègues : "Attention qu’il est important de garder les URL actuelles opérationnelles car si effectivement utilisées côté INSPIRE (end-point pour harvesting) ces URL sont aussi utiisées au niveaux des GetCapabilities (services + GML) des ressources pointes vers metawal au travers d’URL. Les ATOM feed (service et dataset), les WMS et les GML pointent (contiennent donc des URL) vers metawal pour assurer le data-service link."

Je propose que pour le moment, je demande une redirection de ce type : http://geoservices.wallonie.be/metawal/csw-inspire --> http://metawal.wallonie.be/geonetwork/inspire/fre/csw

Ceci permettra au moins d'intégrer le post-processing INSPIRE lors du moissonage en passant par le endpoint.

**Comment by stephyritz** [comment]
Note : Getcapabilities à paramétrer aussi lorsque l'on passe par http://metawal.wallonie.be/geonetwork/inspire/fre/csw?SERVICE=CSW&REQUEST=GetCapabilities
