### ISSUE TITLE
Export pdf / Amélioration du rendu 

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#523]
J'ai reçu encore quelques remarques à propos du pdf obtenu par le biais du bouton 'Télécharger/Export en PDF'. Je les ai consigné en commentaire sur le pdf ci-joint.
Serait-il possible de prendre en compte ces remarques pour la prochaine release ? 

[metadata-6029e738-f828-438b-b10a-85e67f77af92_COMM_SRI.pdf](https://github.com/SPW-DIG/metawal-core-geonetwork/files/4274651/metadata-6029e738-f828-438b-b10a-85e67f77af92_COMM_SRI.pdf)

**Comment by fxprunayre** [comment]
Quelques points corrigés dans https://github.com/geonetwork/core-geonetwork/pull/4491 (répétition de l'étendue, associated resources)

**Comment by stephyritz** [comment]
Sujet qui gagne en importance car dorénavant, c'est ce pdf qui accompagne les données lors du téléchargement sur le Géoportail.

**Comment by fxprunayre** [comment]
- [x] Metadata / Identifiant / "/" en trop
- [x] Metadata / Citation / A supprimer
- [x] Sidebar / Supprimer emprise en doublon
- [x] Sidebar / Supprimer mots clés
- [x] Sidebar / Supprimer ressources associées
- [x] Header / Ajouter un lien vers la fiche dans geoportail

![image](https://user-images.githubusercontent.com/1701393/80210507-2aa37c00-8634-11ea-84fc-a040e501fb30.png)



http://localhost:8080/geonetwork/srv/api/records/6029e738-f828-438b-b10a-85e67f77af92/formatters/xsl-view?output=pdf&language=fre&approved=true

**Comment by fxprunayre** [comment]
A suivre dans https://github.com/SPW-DIG/metawal-core-geonetwork/issues/540

**Comment by fxprunayre** [comment]
A déployer.

**Comment by stephyritz** [comment]
Erreur 500 du Tomcat au moment de l'export en pdf

![image](https://user-images.githubusercontent.com/34446202/80684058-640d3900-8ac5-11ea-9e6b-6d75574f6237.png)

**Comment by stephyritz** [comment]
OK, mais j'ai l'impression qu'il y a systématiquement une page planche à la fin.
De plus je préférerais que le lien vers la fiche du Géoportail soit plus visible (peut-être au tout début du document, en dessous du titre). Sinon, c'est conforme aux modifications que vous avez pu prendre en charge pour cette release.

**Comment by fxprunayre** [comment]
> De plus je préférerais que le lien vers la fiche du Géoportail soit plus visible (peut-être au tout début du document, en dessous du titre). Sinon, c'est conforme aux modifications que vous avez pu prendre en charge pour cette release.

![image](https://user-images.githubusercontent.com/1701393/81946545-c73bb700-95ff-11ea-9f46-ec7d542cd01b.png)

A déployer.

**Comment by stephyritz** [comment]
- En valid, Le titre est "doublé". L'un avec un hypertexte et l'autre non. Premier titre à supprimer.
![pdf_export](https://user-images.githubusercontent.com/34446202/82809253-f9fd6f00-9e8b-11ea-9937-bf04b56258d7.png)

 - Le lien vers la fiche Géoportail est en double également (début + fin). Lien à supprimer à la fin

- La carte d'emprise ne sort pas. En test aussi maintenant.

**Comment by fxprunayre** [comment]
On peut vérifier que le cache JS & CSS a bien été vidé en valid ?

**Comment by stephyritz** [comment]
Même résultat après avoir vidé le cache

**Comment by fxprunayre** [comment]
On n'a pas le problème en test http://metawal4.test.wallonie.be/geonetwork/srv/api/records/2998bccd-dae4-49fb-b6a5-867e6c37680f/formatters/xsl-view?output=pdf&language=fre&approved=true donc ca vient de la config de val.

On peut vérifier que la config dans l'admin est correcte ?
![image](https://user-images.githubusercontent.com/1701393/82824066-edd3da80-9ea8-11ea-9a3b-b1dd8da30bce.png)
+ le proxy s'il y'en a un pour sortir ?

**Comment by stephyritz** [comment]
Même config en valid (sauf bien sûr l'url qui correspondà celle de valid).
Dans les paramètres, le proxy mentionné est le suivant : webproxyappl.intra.wallonie.be ; Port=3129
