### ISSUE TITLE
Edition / Date de mise en accès

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#524]
Nous avons récemment eu des discussions en interne sur les dates mentionnées dans une fiche de MD et leurs significations. Voici comment sont utilisées les dates jusqu'à présent dans Metawal en ISO19115-3 : 

- Date de création de la fiche
- Date de révision de la fiche
---------------------------
- Date de création de la ressource (=donnée)
- Date de révision de la ressource (= date de la dernière version de la donnée)
- Date de publication (= date de la diffusion de la dernière version de la donnée)

Ceci signifie que nous perdons la date de première diffusion de la donnée car la date de publication est mise à jour à chaque changement de version.

Peut-être que nous pourrions utiliser la valeur "Mise en accès" pour renseigner la date de première diffusion de la donnée ? Qu'en pensez-vous ?

![date_mise_en_acces](https://user-images.githubusercontent.com/34446202/75869967-9e7e9080-5e0a-11ea-81df-3b97e6b1e0f6.png)

Dans ce cas, il faudrait alors ne pas afficher cette info dans le schéma type ISO19139 destiné à INSPIRE car si une date est associée à une valeur différente de "création","révision" ou "publication", c'est non conforme.

**Comment by fxprunayre** [comment]
Rien n'empêche d'avoir plusieurs date de publication a priori.



> INSPIRE car si une date est associée à une valeur différente de "création","révision" ou "publication", c'est non conforme.

On peut filtrer les autres dates avec le CSW post processing ?

**Comment by stephyritz** [comment]
> Rien n'empêche d'avoir plusieurs date de publication a priori.

En 115-3 non, mais d'après INSPIRE je crois que j'avais testé et c'est non conforme.

Mais l'option de mettre plusieurs dates de publication me plaît moins car il y a des données mises à jour très régulièrement et dans ce cas, on aurait plus d'une centaine de dates de publication.. Je préfère l'idée d'encoder une date de première publication (valeur statique) et une date de dernière publication (mise à jour systématiquement dès qu'il y a une nouvelle version publiée). 

Pour l'instant, dans les fiches, il n'y a qu'une date de publication qui a été utilisée comme date de la publication de la dernière version.

En tout cas, oui pour le filtre post processing. La date de mise en accès ne serait que présente en 115-3. Je vais essayer de voir comment les autres états membres utilisent la date de publication. Et au pire, si c'est selon l'angle "première mise en accès", alors on opérera une bascule dans le post processing. Mais on en est loin vu que nous n'avons plus ces valeurs de "mise en accès" car à chaque mise à jour data, elles sont écrasées.

**Comment by fxprunayre** [comment]
> on aurait plus d'une centaine de dates de publication.

Si c'est régulier il y a la possibilité de renseigner la fréquence.

**Comment by stephyritz** [comment]
Conclusion : On encode si nécessaire 2 dates de publication (1 pour la première publication et une pour la publication de la dernière version) et on utilise la fréquence si MaJ du service régulière.
