### ISSUE TITLE
CSW / Fiches mentionnées en ressources associées 

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#525]
Les fiches mentionnées en ressources associées ne sont pas toutes présentes dans le CSW et donc au sein du Géoportail. 

Exemple 1 : 
* fiche dans metawal http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/b795de68-726c-4bdf-a62a-a42686aa5b6f
* CSW 
http://metawal.wallonie.be/geonetwork/srv/fre/csw?request=GetRecordById&service=CSW&outputSchema=http://www.isotc211.org/2005/gmd&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=b795de68-726c-4bdf-a62a-a42686aa5b6f (Seules les fiches  de type "références croisée" apparaissent sur le CSW)
* Geoportail http://geoportail.wallonie.be/catalogue/b795de68-726c-4bdf-a62a-a42686aa5b6f.html

Exemple 2  : Une fiche série (http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/7128b9b9-75e8-4318-a14a-d64eff6a8887)  et 2 fiches filles (http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/f4e3709c-fdda-452e-b723-7ad55e584f1f ET http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/2ee5842e-df8b-41a6-824a-2c3d8a90fbf0).

J'ai "ajouté un parent" depuis chacune des séries filles. Les liens entre les fiches sont très bien interprétés côté GN mais absents dans le CSW --> http://metawal.wallonie.be/geonetwork/srv/fre/csw?request=GetRecordById&service=CSW&outputSchema=http://www.isotc211.org/2005/gmd&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=7128b9b9-75e8-4318-a14a-d64eff6a8887 

Je pense que ce problème était déjà apparu à un moment dans une version antérieure de Metawal --> https://github.com/SPW-DIG/metawal-core-geonetwork/issues/433

**Comment by fxprunayre** [comment]
> Les fiches mentionnées en ressources associées ne sont pas toutes présentes dans le CSW

* cas des services: le dataset ne porte pas la relation. C'est la fiche de service via srv:operatesOn qui pointe vers le service. GeoNetwork fait une recherche pour naviguer entre les fiches dans les 2 directions.
* cas des séries: idem pour la relation parent/enfant. Les enfants pointent vers le parent via parentIdentifier. Le parent n'a pas connaissance de ces enfants :) il faut les rechercher. 

L'utilisation de associatedResource permet de faire des liens dans les 2 sens (mais demande plus de travail d'encodage). GeoNetwork fait également la mécanique pour rechercher qui est associé à qui pour naviguer dans les 2 sens.

Donc le pb n'est pas le CSW, mais l'appli doit s'occuper de recherche qui est lié à qui en fonction du type de relation et de la manière dont elles sont encodées.

**Comment by stephyritz** [comment]
> L'utilisation de associatedResource permet de faire des liens dans les 2 sens (mais demande plus de travail d'encodage). GeoNetwork fait également la mécanique pour rechercher qui est associé à qui pour naviguer dans les 2 sens.

Oui mais, surtout, dans ce cas, il n'y a pas la notion de hiérarchie. Et ça c'est embêtant pour la suite car, à terme, nous aimerions pouvoir implémenter une intelligence dans la recherche qui mettrait en avant les "parents" à qui sont associés les services. Les fiches enfants ne serviraient uniquement à stocker la documentation propre à une couche et serait donc utile aux utilisateurs "avancés du GP.

Dans le cas du PICC (ex. 1), lorsqu'une référence croisée (=associatedResource) est faite depuis une autre fiche, elle apparaît très bien dans GN mais pas dans le CSW. Elle n'apparait effectivement que si la relation est encodée depuis la fiche. Qu'est-ce que tu veux dire par "plus de travail d'encodage" ? Il faudrait faire le lien depuis une fiche puis la même chose depuis l'autre même si l'application gère de le faire dans les deux sens ? Tout ça pour que l'info soit dans le CSW ? Un peu dommage si j'ai bien compris.

En fait plus globalement, dès qu'on utilise le CSW, on perd l'intelligence de l'appli et c'est un peu dommage pour les applications tierces qui veulent utiliser cette information de lien entre fiches/données. Par ex. :  le Géoportail, les process FME qui génèrent un dossier zippé avec toutes les fiches et la donnée, notre DB de suivi des données ou encore éventuellement les plugins utilisant les CSW dans les viewer ou logiciels SIG. 

Du coup, j'ai pas trop compris. Est-ce qu'on peut améliorer cette situation ou il faudrait changer la manière d'encoder les choses selon toi ?

**Comment by stephyritz** [comment]
Les parents n'apparaissent pas non plus dans le Geoportail car j'imagine que leur règle cherche dans les ressources associées et ne fait pasautant de distinction que dans GN.
Le fait de stocker l'info dans 
```
<gmd:parentIdentifier>
  <gco:CharacterString>7128b9b9-75e8-4318-a14a-d64eff6a8887</gco:CharacterString></gmd:parentIdentifier>
```
la rend "invisible" mais ça c'est une amélioration à apporter côté GN.

Mais de mon point de vue, il est vraiment capital que les "parents puissent connaître leurs enfants" ; ) parce que c'est ce qui est important pour l'utilisateur. On va lui présenter la fiche parent avec tous les services de visu/téléchargement et on va lui dire, "tu veux en savoir plus sur une couche en particulier --> fiche enfant".

**Comment by stephyritz** [comment]
> cas des services: le dataset ne porte pas la relation. C'est la fiche de service via srv:operatesOn qui pointe vers le service. GeoNetwork fait une recherche pour naviguer entre les fiches dans les 2 directions.

Dommage aussi (mais moins que pour le cas précédent car la fiche de service n'apporte pas grand chose) car le point d'entrée pour l'utilisateur est quand même la fiche de série ou dataset si absence de série. Et donc c'est à partir de là que les liens pourraient être intéressants de figurer.

**Comment by fxprunayre** [comment]
> Qu'est-ce que tu veux dire par "plus de travail d'encodage" ? Il faudrait faire le lien depuis une fiche puis la même chose depuis l'autre même si l'application gère de le faire dans les deux sens ? Tout ça pour que l'info soit dans le CSW ? Un peu dommage si j'ai bien compris.

Oui. Encoder des 2 côtés. Un peu lourd et ça suppose que tu peux éditer les 2 fiches - dans ton cas c'est bon. Car les privilèges sont pris en compte aussi dans le service des relations. Tu peux avoir des liens vers des fiches privées.

> En fait plus globalement, dès qu'on utilise le CSW, on perd l'intelligence de l'appli et c'est un peu dommage pour les applications tierces qui veulent utiliser cette information de lien entre fiches/données.

Rien n'empêche les applis en question de recréer la logique des relations (ou d'utiliser l'API GN). 

> Du coup, j'ai pas trop compris. Est-ce qu'on peut améliorer cette situation ou il faudrait changer la manière d'encoder les choses selon toi ?

Le CSW ca va bien pour moissonner mais ça a ses limites.
De mon point de vue:
* il faut éviter de complexifier l'encodage
* il y aura des cas où on ne peut pas encoder dans les 2 sens de toute façon (eg. service/dataset)
* plutôt utiliser l'API GN pour rechercher les fiches associées http://metawal.wallonie.be/geonetwork/doc/api/index.html#/records/getAssociated  

> Mais de mon point de vue, il est vraiment capital que les "parents puissent connaître leurs enfants" 

Pour ça, on peut utiliser associatedResource et faire des liens du type isComposedOf/series pour faire les liens. Et on peut choisir de le faire dans un sens parent isComposedOf, ou children has series ou les deux. Avec Vincent, l'idée était de ne plus utiliser parentIdentifier.

**Comment by stephyritz** [comment]
`Encoder des 2 côtés. `
Laisse tomber ça. Solution bricolage pour régler un pb qui n'est pas dans Metawal. En plus ça va donc apparaître 2 fois dans GN ce qui est dommage.

> Rien n'empêche les applis en question de recréer la logique des relations (ou d'utiliser l'API GN).

Oui. Mais pas possible à court terme visiblement.

> Pour ça, on peut utiliser associatedResource et faire des liens du type isComposedOf/series pour faire les liens.

Ok. Je pense qu'il est vraiment important de trouver une solution assez rapidement pour ça. Parce que, actuellement, il y a des fiches "filles" dans le catalogue Géoportail qui ne sont "reliées à rien" et qui n'ont pas de services de visu ni de téléchargement et donc les gens se demandent ce qu'elles font là.

> Avec Vincent, l'idée était de ne plus utiliser parentIdentifier.

Cela veut dire supprimer la notion de parent/enfant ? Ou la remplacer par autre chose du type série/dataset avec plus une notion de "est composée de .." ? Si c'est ça, je suis plutôt d'accord parce que parent/enfant peut être interprété comme "la donnée est issu de..." même si dans GN il y a un autre type de relation pour cela avec la mention de "donnée source".

**Comment by fxprunayre** [comment]
En lien avec #526

**Comment by fxprunayre** [comment]
### Proposition

Pour que 
![image](https://user-images.githubusercontent.com/1701393/78335728-7495c680-758e-11ea-95a9-a0fb2d1b9290.png)

Apparaissent dans 
![image](https://user-images.githubusercontent.com/1701393/78335745-7eb7c500-758e-11ea-807f-4212ea871529.png)

On essaye d'injecter dans 
http://localhost:8080/geonetwork/srv/fre/csw?request=GetRecordById&service=CSW&outputSchema=http://www.isotc211.org/2005/gmd&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=b795de68-726c-4bdf-a62a-a42686aa5b6f
avec le service de relation http://metawal.wallonie.be/geonetwork/srv/api/records/1880/related?type=associated 
les fiches sous forme gmd:aggregationInfo (crossReference).

**Comment by fxprunayre** [comment]
A déployer et tester.

**Comment by davinciagf** [comment]
Les autres ressources apparaissent dans la partie aggregationInfo du CSW (profil: mw)

![Screen Shot 2020-04-14 at 10 57 51](https://user-images.githubusercontent.com/576292/79205939-e39cd600-7e3e-11ea-97f5-6b87d7957101.png)

Testé sur : http://metawal4.test.wallonie.be/geonetwork/srv/fre/csw?request=GetRecordById&service=CSW&outputSchema=mw&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=b795de68-726c-4bdf-a62a-a42686aa5b6f

**Comment by stephyritz** [comment]
Ok mais cela rejoint une de mes remarques faites sur #526 si je comprends bien l'objet de ce process.

Exemple : 
1. Depuis un dataset "fille" j'associe à la série "mère"
2. Dans la série "mère", la "fille" va apparaître en tant que ressource sans aucun type ("simple ressource associée)
3. Avec ce process, on va transformer cette relation en "crossreference"
4. Dans le résultat du CSW, on va se retrouver avec une série qui aura une relation de type "crossreference" avec "sa fille" alors que, initialement c'est une relation de type "partofthesamelessdatabase".
5. Selon la fiche, dataset ou serie, nous nous retrouvons avec un type d'association différent.

J'ai l'impression qu'il serait plus simple de pouvoir conserver le type d'association lors de la création de la réciprocité dans l'association. Ensuite, ce postprocess jouerait le même rôle mais en spécifiant le type de relation. Peut-être même en y indiquant une relation de type "hiérarchique" pour les séries/datasets ?!

**Comment by fxprunayre** [comment]
> J'ai l'impression qu'il serait plus simple de pouvoir conserver le type d'association lors de la création de la réciprocité dans l'association. Ensuite, ce postprocess jouerait le même rôle mais en spécifiant le type de relation. Peut-être même en y indiquant une relation de type "hiérarchique" pour les séries/datasets ?!

Dans http://metawal.wallonie.be/geonetwork/srv/api/records/1880/related?type=associated
nous n'avons pas le détail sur le type d'initiative et association. On pourrait selon le type dataset ou serie préciser le type de relation ? 

Je croyais que le geoportail se basait justement sur crossreference uniquement.

**Comment by stephyritz** [comment]
> Dans http://metawal.wallonie.be/geonetwork/srv/api/records/1880/related?type=associated
> nous n'avons pas le détail sur le type d'initiative et association.

Un peu dommage, non. Comment font les applications qui récupèrent les MD pour sépcifier le type de relation entre fiches alors? Enfin c'est peut être trop du détail.

> On pourrait selon le type dataset ou serie préciser le type de relation ?

Tu veux dire systématiser si un dataset est en lien avec une série, alors lien hiérarchique entre les deux ? Si c'est ça je pense que ça peut faire l'affaire. Le seul écueil serait quand un dataset a un lien thématique avec une série (et non pas fait partie de...). Mais bon, peut-être un moindre mal?!


> Je croyais que le geoportail se basait justement sur crossreference uniquement.

Non, désolé si on s'est mal compris. Il récupère tout type d'associations, du moment qu'elles possèdent un "type". En gros, le GP prend en compte tout ce qui se trouve dans associated ressource sans distinction.

**Comment by fxprunayre** [comment]
> tout ce qui se trouve dans associated ressource sans distinction.

Du coup ça sert à quoi de faire la distinction? :)

**Comment by stephyritz** [comment]
> Du coup ça sert à quoi de faire la distinction? :)

Ahah! Parce que je pense que le rendu dans Géoportail pourrait être mieux pour l'utilisateur. C'est tout de même intéressant de savoir si la fiche a un lien de parenté avec une autre ou si c'est seulement un lien thématique, une révision, etc...

Mais, si on se concentre sur ce qui est opérationnel à l'heure actuelle chez nous, le process qui fait apparaître tous les liens issus de "réciprocité" dans "les fiches sous forme gmd:aggregationInfo" c'est tout bon. Sans spécifier type=crossreference parce que là, pour moi, on créé une info erronée (même si invisible dans le GP). Donc on évite ça, sauf si obligatoire d'un point de vue technique.

**Comment by stephyritz** [comment]
Fonctionne sur le Geoportail en environnement de test à ce jour.
