### ISSUE TITLE
Edition / Saisie de fiches en ressources associées

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#526]
Je cherche ici un moyen d'être plus efficace et cohérent au moment d'associer les fiches entre elles, principalement dès qu'elles sont plus de 2 à avoir des liens.
Par exemple, les fiches suivantes font partie d'une même "collection" car les données font l'objet d'un reporting environnemental pour la directive 91/271/CEE : 

- http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/b19e23e3-f6e3-44ba-af20-7cdf1b25c09a

- http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/d52095c0-d33c-44b9-a593-6e861c079997

- http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/8209749a-b033-4b48-964e-a4b495497c60

- http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/011963da-afc0-494c-a2cc-5cbd59e122e4

Je les références en tant qu'association de type "PartoftheseamlessDatabase".

1. J'édite une des 4 fiches (la première) et je sélectionne les 3 autres en tant que ressources associées 

--> Dans la fiche N°1 la relation est bien de type PartoftheSamelessDatabase mais au sein des 3 autres fiches, la première fiche est mentionnée automatiquement uniquement en tant que "ressource associées".

2. Que faire en suite ? J'ai éditée la seconde et référencé les 2 manquantes puis la troisième et renseigné l'unique manquante et n'ai rien fait sur la dernière vue que les trois relations se sont créées de manière réciproque ?

Est-ce qu'il faudrait s'y prendre autrement ?

Est-il possible de faire en sorte que, après l'étape 1, toutes les fiches sélectionnées possèdent d'office les trois autres en tant que ressources associées de type partoftheseamlessDatabase ?

**Comment by fxprunayre** [comment]
C'est en lien avec #525 .

Quand on établit une relation (enfant > parent, service > dataset, fiche > fiche associée), il y a toujours une direction. Dans l'API GN, le service qui retourne les relations s'occupe de rechercher pour rendre les relations navigables dans les 2 sens.

Dans le cas ci-dessus, il faudrait peut être considérer `PartoftheseamlessDatabase` comme un groupe et du coup afficher tous les membres du groupes (à l'exception de la fiche en cours de consultation) ?

En janvier, nous avons ajouté la possibilité d'afficher les `brothersAndSisters` dans le cas des relations parents/enfants pour ne pas avoir à remonter dans le parent à chaque fois. cf.
https://github.com/geonetwork/core-geonetwork/pull/4346

Qu'en penses tu @stephyritz ?

**Comment by stephyritz** [comment]
> Dans le cas ci-dessus, il faudrait peut être considérer PartoftheseamlessDatabase comme un groupe et du coup afficher tous les membres du groupes (à l'exception de la fiche en cours de consultation) ?

Oui, ça serait top.

> En janvier, nous avons ajouté la possibilité d'afficher les brothersAndSisters dans le cas des relations parents/enfants pour ne pas avoir à remonter dans le parent à chaque fois. cf.
> geonetwork#4346

J'ai remarqué, c'est vraiment bien ainsi !

> C'est en lien avec #525 .

Oui, sauf que j'en conclue qu'avec ce ticket, on envisage un changement dans "l'intelligence de l'API" alors que pour l'autre c'était surtout pour comprendre comment les résultats (ou tout du moins la partie concernant série/couche) de "cette intelligence" pourraient être visibles à travers le CSW.

**Comment by stephyritz** [comment]
Voici mon analyse du sujet : 

[associated_resource_scenarios.docx](https://github.com/SPW-DIG/metawal-core-geonetwork/files/4329712/associated_resource_scenarios.docx)

Je pense que c'est vraiment important et qu'il y a des améliorations à faire sur le sujet tant termes d'outils que de méthode. Nous pouvons en rediscuter de vive voix.

**Comment by fxprunayre** [comment]
![image](https://user-images.githubusercontent.com/1701393/78335029-2b914280-758d-11ea-8bcf-b06cd73cf9fc.png)

![image](https://user-images.githubusercontent.com/1701393/78335038-2e8c3300-758d-11ea-9594-7fd28bf5efe5.png)


A déployer

**Comment by stephyritz** [comment]
Merci, ça fonctionne bien! Voici mes quelques commentaires restants sur ce point : 

- Est-il possible d'avoir en réalité 3 cas (actuellement 2 : service et data/série) ? Car depuis la série, soit on supprimer "fait partie de..." en admettant que la saisie du lien n'est possible que depuis le "children" soit il faudrait qu'il y ait la possibilité inverse "est composé de..."

- Dans cette manière de faire, la relation série/dataset est défini par le type "partoftheseamlessdatabase" mais du coup, on perd l'info dans GN (que je trouvais super) des "liens de parenté". Automatisation de la relation "frères/soeurs" et détail du lien hiérarchique entre série et dataset. Ce lien hiérarchique ne serait alors que vérifiable en faisant une "double interrogation" est-ce qu'il y a une relation "partoftheseamlessdatabase" entre une série et un dataset alors lien hiérarchique de type "parent/enfant". Mais peut-être est-ce suffisant en terme d'info et à l'interface de la fiche de s'adapter ?!

- Cela me "gêne" un peu que lorsque qu'on associe une ressource partoftheseamlessdatabase d'un côté (depuis une fiche 1), la relation de réciprocité se traduise par une ressource associée 'sans spécification'. Ceci fait que dans un sens on a bien le type de relation mais dans l'autre, on l'ignore. Je pense qu'il serait intéressant d'intégrer le type dans la réciprocité.

**Comment by fxprunayre** [comment]
- [x]  En fait, il faudrait pouvoir modifier la définition d'un parent (actuellement parentMetadata) qui déclenche ensuite la notion de frères/soeurs. Dans metawal, un parent serait associatedResource de type "partoftheseamlessdatabase". 

- [x]  Edition / Dans série / Pas de "Fait partie de..."

**Comment by fxprunayre** [comment]
Gestion de partoftheseamlessdatabase en tant que parent cf. https://github.com/metadata101/iso19115-3.2018/pull/63.

Je vois avec les Australiens si on active ce mode par défaut ou pas.

**Comment by fxprunayre** [comment]
> Gestion de partoftheseamlessdatabase en tant que parent cf. [metadata101/iso19115-3.2018#63](https://github.com/metadata101/iso19115-3.2018/pull/63).

Mergé. A déployer. Il faut réindexer

**Comment by stephyritz** [comment]
A priori OK. Est-ce qu'il y a un effet rétroactif sur toutes les fiches qui avaient une ressource associée de type partoftheseamlessdatabase ? Sont-ils maintenant considérés comme enfant et la ressource associé comme parent ? J'ai l'impression que oui. Et je vais avoir quand même un peu de travail sur de l'édition de fiche car cette relation était aussi utilisée pour faire de liens thématiques (exemple : http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/f16124b7-41ed-42fe-9442-73b32708d60a)

**Comment by stephyritz** [comment]
Ajout des frères et soeurs dans associated ressources lors de l'export avec l'outputschema custom "mw".
Voir ex. : http://geoportail.test.wallonie.be/catalogue/076bd325-45d3-4958-a8fd-f4eb9dbd20a6.html
et http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/5e81aa94-2495-493d-8c7a-6ad1c21501c0
Dans ce cas, nous aurons toutes les relations de parentés visibles sur le Géoportail.

**Comment by fxprunayre** [comment]
A déployer & tester 

Requetes CSW pour le test:
```xml

<?xml version="1.0"?>
<csw:GetRecords xmlns:csw="http://www.opengis.net/cat/csw/2.0.2"
                xmlns:gmd="http://www.isotc211.org/2005/gmd"
                service="CSW" version="2.0.2"
                resultType="results"
                outputSchema="mw">
  <csw:Query typeNames="gmd:MD_Metadata">
        <csw:ElementSetName>full</csw:ElementSetName>
    <csw:Constraint version="1.1.0">
      <Filter xmlns="http://www.opengis.net/ogc">
        <PropertyIsLike wildCard="%" singleChar="_" escapeChar="\">
          <PropertyName>_uuid</PropertyName>
          <Literal>97516715-4746-4254-85ea-c7ae7eb234b3</Literal>
        </PropertyIsLike>
      </Filter>
    </csw:Constraint>
  </csw:Query>
</csw:GetRecords>
```

**Comment by stephyritz** [comment]
Cela m'a l'air nickel.
Seul petit défaut à l'édition : impossible de supprimer une ressource parent via la bouton "suppr" (croix rouge). To reproduce : 
1. Edition de la fiche http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/a4c49df8-8e51-4ec2-9be0-9186cb499236
2. Suppr du parent "Orthophotos 2019 - Maillage et tuilage"
3. Aucune réaction de l'application

**Comment by fxprunayre** [comment]
> impossible de supprimer une ressource parent via la bouton "suppr"

Hum, normal, c'est une associatedResource donc le bouton parent considère que c'est un parentIdentifier

![image](https://user-images.githubusercontent.com/1701393/83227898-7f7f6880-a185-11ea-9f5e-83749093fe92.png)

La suppression du lien doit fonctionner à partir de la section Autres ressource j'imagine?

On peut faire un ticket pour améliorer ça.

**Comment by stephyritz** [comment]
Oui c'est vrai. Cela prête un peu à confusion parce que l'utilisateur arrive dans l'idée de "supprimer le parent" et il faut passer par 'Autres ressources'. Améliorations à étudier dans un ticket séparément.
