### ISSUE TITLE
Edition / Keywords INSPIRE feature concept 

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#527]
Ajouter la possibilité d'ajouter aux fiches ce type de keywords sur base du registre INSPIRE suivants : http://inspire.ec.europa.eu/featureconcept

- [ ] Importer le registre INSPIRE en tant que thesaurus GN
- [ ] Adapter l'interface de Metawal
- [ ] Vérifier que tout passe bien en ISO 19139 et vis à vis de la conformité INSPIRE

**Comment by fxprunayre** [comment]
>  Importer le registre INSPIRE en tant que thesaurus GN

A priori ok en l'état. Faire la manip via l'admin.

> * [ ]  Adapter l'interface de Metawal

https://github.com/metadata101/iso19115-3.2018/pull/54




> * [ ]  Vérifier que tout passe bien en ISO 19139 et vis à vis de la conformité INSPIRE

A déployer et tester

**Comment by vbombaerts** [comment]
Thésaurus présent en prod lors du monitoring de décembre 2021
