### ISSUE TITLE
Output Schéma MW / Conditions d'accès et d'utilisation

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#529]
Modifier le schéma custom "mw" pour faire en sorte de filtrer les informations encadrées en rouge dans l'image ci-dessous.

![CA_CU_mw_outputschema](https://user-images.githubusercontent.com/34446202/76625251-1d747700-6537-11ea-9ddc-8bd3e6ec7b03.png)

En effet, ce sont des éléments techniques exigés par INSPIRE mais qui n'ont pas de sens aux yeux des utilisateurs du Géoportail.

**Comment by fxprunayre** [comment]
A faire dans https://github.com/SPW-DIG/iso19115-3.2018/blob/91103d0636c7f8db16f01951b7fc4e503ee3d8cd/src/main/plugin/iso19115-3.2018/present/csw/mw-full.xsl

**Comment by stephyritz** [comment]
A priori OK pour la plupart des fiches. Mais pas toutes. Exemple : http://metawal4.test.wallonie.be/geonetwork/srv/fre/csw?request=GetRecordById&service=CSW&outputSchema=mw&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=2998bccd-dae4-49fb-b6a5-867e6c37680f
ou le "limitation est encore présente avec l'outputschema 'mw'

**Comment by stephyritz** [comment]
Autre cas non géré par exemple : d3d387ff-ff17-4307-93fc-749174bfe215.

Je pense que c'est parce que dans le xsl, on fait appel à plusieurs cas pour les conditions d'utilisation mais que hétérogénéité du contenu des fiches fait que plusieurs d'entre elles (beaucoup?) passent "entre les mailles" du fichier de transfo

**Comment by stephyritz** [comment]
Bon ceci étant dit, ça règle déjà le problème pour les fiches INSPIRE (ce qui était décrit comme pb au départ). Et donc on peut se dire qu'une fois qu'on aura fait le "ménage" dans les CA/CU de toutes les fiches, nous aurons plus à gérer tous ces cas particuliers.D'autant plus que nous travaillons en interne pour limiter la diffusion de données à travers des licences trop spécifique.
Qu'en pensez-vous ?

**Comment by davinciagf** [comment]
Attention, il est possible de restreindre encore le rendu - je n'ai bloqué que les cas ayant les balises mco:useLimitation  dans les blocs incluants `Conditions d''accès et d''utilisation spécifiques` et les mco:otherConstraints = 'No limitations to public access' des autres blocs de contraintes. Il faudrait donc élargir le spectre de ces restrictions pour prendre en compte  les cas que tu mentionnes.

**Comment by stephyritz** [comment]
Je viens de remarquer un problème dans la transformation des CA/CU à travers le xsl custom propre à la création du schéma "mw". Il semblerait que le point mentionné en #514 ne soit pas correctement géré. Sûrement que la valeur du texte dans le "case type C" du xsl n'est pas la bonne. 
Exemple : 

http://metawal4.test.wallonie.be/geonetwork/srv/fre/csw?request=GetRecordById&service=CSW&outputSchema=mw&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=6029e738-f828-438b-b10a-85e67f77af92 --> NOK

http://metawal4.test.wallonie.be/geonetwork/srv/fre/csw?request=GetRecordById&service=CSW&outputSchema=http://www.isotc211.org/2005/gmd&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=6029e738-f828-438b-b10a-85e67f77af92 --> OK

http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/6029e738-f828-438b-b10a-85e67f77af92 --> OK

**Comment by fxprunayre** [comment]
Corrigé par https://github.com/SPW-DIG/iso19115-3.2018/tree/5dc8a7151c7775a3afd5852587fd5b72f73e3e46 

à vérifier puis déployer.
