### ISSUE TITLE
positions dans header et sous-header ('recherche')

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#53]
La barre recherche (sous header) n'a pas tous ses éléments visibles quand on réduit la fenêtre! pas de possibilité de tri....
![droite](https://f.cloud.github.com/assets/6093453/1662317/d9d18db6-5bfc-11e3-867b-bc55f461ba72.jpg)
![droite2](https://f.cloud.github.com/assets/6093453/1662318/da0bc224-5bfc-11e3-813c-95ea41b6283d.jpg)
Connexion dans le header idem, sauf que cela arrive plus tard (fenêtre plus petite)

**Comment by fxprunayre** [comment]
Ils sont raffraichis lors de la recherche suivante.

**Comment by fxprunayre** [comment]
Sans objet dans metawal-4.x du fait de l'usage de bootstrap

**Comment by vbombaerts** [comment]
Contournement tolérable dans la version 3.0 ;-)
