### ISSUE TITLE
Interface Fiche / Affichage d'informations sur le WMS

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#531]
J'ai l'impression que l'affichage concernant les services WMS est différent sur la fiche selon le niveau auquel le service est renseigné vis à vis du distributeur.

Exemple 1 : 
 
http://metawal.wallonie.be/geonetwork/srv/api/records/09e899fc-9dff-4321-9b92-d0be34d1e080/formatters/xml?approved=true

Type d’arborescence : 

```

<mdb:distributionInfo>
  <mrd:MD_Distribution>
    <mrd:distributor>
    </mrd:distributor>
    <mrd:transferOptions>
    </mrd:transferOptions>
  </mrd:MD_Distribution>  
</mdb:distributionInfo>
```

![wms_rendering_GN](https://user-images.githubusercontent.com/34446202/76843447-18b40980-683c-11ea-973c-7dd0345f2b86.png)

Exemple 2 : 

http://metawal.wallonie.be/geonetwork/srv/api/records/3be632c8-80d3-460e-9122-bdefe2470d3d/formatters/xml?approved=true

Type d’arborescence : 

```
<mdb:distributionInfo>
  <mrd:MD_Distribution>
    <mrd:distributor>
      <mrd:MD_Distributor>
        <mrd:distributorContact>
        </mrd:distributorContact>
        <mrd:distributorTransferOptions>
        </mrd:distributorTransferOptions>
      </mrd:MD_Distributor>
    </mrd:distributor>
  </mrd:MD_Distribution>
</mdb:distributionInfo>
```

![wms_rendering_GN_2](https://user-images.githubusercontent.com/34446202/76844286-5ebd9d00-683d-11ea-9176-b8c36d1a4581.png)

GN semble mieux gérer le deuxième cas. Est-ce qu'on devrait prévoir une homogénéisation de notre contenu dans ce sens ? Une évolution de l'interface d'encodage pour ne pas avoir la possibilité d'ajouter un "mrd:tTansferOptions" au même niveau que mrd:distributor ?

**Comment by fxprunayre** [comment]
GN ref https://github.com/geonetwork/core-geonetwork/pull/4611

A déployer et tester.

**Comment by stephyritz** [comment]
Visiblement lorsque le "transferoption" est à l'intérieur du mrd:distributor (exemple 2 ci-dessus), c'est non conforme INSPIRE --> https://inspire.ec.europa.eu/validator//v2/TestRuns/EID9b838a87-eefd-496c-992f-37ea22be6884.html

D'après mes tests, j'en ai conclu que cela venait de cette structure car le xml de test 
[TEST_ER_WMS_csw-inspire.zip](https://github.com/SPW-DIG/metawal-core-geonetwork/files/4715865/TEST_ER_WMS_csw-inspire.zip) est conforme --> https://inspire.ec.europa.eu/validator/v2/TestRuns/EID3eded919-568a-49b3-ab48-39fcddda870b.html

Je peux modifier cette fiche sans aucun problème mais il serait peut-être intéressant "de mettre en garde contre cette structuration" voir même de l'empêcher dans GN ?!

**Comment by fxprunayre** [comment]
* @stephyritz correction de la fiche restante
* @fxprunayre ajouter un exemple de post processing dans la doc GN
* Question : validation INSPIRE n'applique pas le post processing attaché au CSW INSPIRE. A voir comment on peut améliorer ça.
