### ISSUE TITLE
INSPIRE / Validation distante

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#532]
Problème d'affichage de l’icône et du lien vers rapport de validation pour une fiche de service ayant déjà été validée précédemment. En effet, le test tourne, se termine mais l'icône de change pas (possible si toujours valide) et le lien vers le rapport n'est pas actualisé.

To reproduce : 
1. Sélection d'une fiche dans l'onglet Contribuer
2. Exécuter l'outil Validation INSPIRE distante depuis cet onglet
3. Le processus semble se dérouler avec succès
4. Le lien vers le rapport (et l'icône --> Valeur "valide ou pas") ne sont pas actualisés

J'ai essayé refresh de la page et vider le cache. Sans effet. Pourtant le process semble avoir fonctionné car j'ai retrouvé le rapport depuis l'outil de validation --> http://inspire.ec.europa.eu/validator/v2/TestRuns/EID294e4ac0-16fc-455c-b424-38a8875b01ef.html pour la fiche http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/2b9b253d-e4ff-48ff-97e1-35b7e4bb462a

Il y a eu une release récente de leur outil. Des changements avec un impact sur GN ?

**Comment by fxprunayre** [comment]
Je viens de le relancer pour la fiche en question et j'ai bien eu changement de l'état (elle est devenue invalide d'ailleurs)
 
![image](https://user-images.githubusercontent.com/1701393/77648224-14889a00-6f68-11ea-8a6d-15cc6433d94a.png)

Du coup je comprends pas la manip. A la fin du process, il faut relancer la recherche (mais y'a pas d'histoire de cache là).

**Comment by stephyritz** [comment]
OK... bizarre... Je testerai plus et si toujours pas de problème je fermerai le ticket.
Autre enseignement lié à la release du validateur, il nous manque encore quelque chose pour la conformité des services.. En effet, jusqu'à présent le validateur ne checkait pas l'existence d'un keyword spécifique aux services (manquant chez nous) --> https://github.com/inspire-eu-validation/metadata/blob/2.0/sds/sds-category.md. Donc requête DB ou traitement par lot à faire pour être OK. Je vais créer le ticket et m'en chargerai si j'y arrive tout seul.
