### ISSUE TITLE
INSPIRE / Ajout du Category Keywords aux services

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#533]
Point sur lequel nous ne sommes pas conformes et qui a été rajouté aux tests réalisés par l'outil de validation INSPIRE au cours de la dernière release (15/03/2020).

Proposition d'ajouter les keywords adaptés aux différentes fiches de services : 
- View 
```
  <mri:keyword>
    <gcx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/infoMapAccessService">Service d’accès aux cartes</gcx:Anchor>
  </mri:keyword>
```

- Download
```
  <mri:keyword>
    <gcx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/infoProductAccessService">Service d’accès aux produits</gcx:Anchor>
  </mri:keyword>
```

- Discovery 
```
  <mri:keyword>
    <gcx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/infoCatalogueService ">Service de catalogue</gcx:Anchor>
  </mri:keyword>
```

**Comment by stephyritz** [comment]
En batch editing : 

![image](https://user-images.githubusercontent.com/34446202/77743523-815b6d00-7018-11ea-96a8-27d6024b6504.png)

Exemple d'un paramètre lié au fragment du xml (service de visu) : 

```
<mri:descriptiveKeywords  xmlns:mri="http://standards.iso.org/iso/19115/-3/mri/1.0" xmlns:gcx="http://standards.iso.org/iso/19115/-3/gcx/1.0" xmlns:xlink="http://www.w3.org/1999/xlink">
  <mri:MD_Keywords>
    <mri:keyword>
      <gcx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/infoMapAccessService">Service d’accès aux cartes</gcx:Anchor>
    </mri:keyword>
  </mri:MD_Keywords>
</mri:descriptiveKeywords>

```

**Comment by stephyritz** [comment]
J'ai testé sur des fiches qui, en fait, semblaient être un cas particulier...

La "catégorie" des services est actuellement gérée à travers le theasurus "INSPIRE Service taxonomy". 

A priori, il suffirait donc de : 
- [ ] Mettre à jour ce thesaurus en y rajoutant les anchor vers http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory
- [ ] Mettra à jour l'ensemble des fiches pour que le mots-clés ne soit plus en characterstring mais avec une ancre.

L'utilisation d'un characterstrin entraîne une non-conformité --> par ex : http://inspire.ec.europa.eu/validator//v2/TestRuns/EID502fff65-8053-4988-b8a8-ae3c88f2541c.html

**Comment by fxprunayre** [comment]
> * [ ]  Mettre à jour ce thesaurus en y rajoutant les anchor vers http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory


Euh, non, du coup je pense qu'il faut le remplacer par son équivalent importé depuis le registre INSPIRE

![image](https://user-images.githubusercontent.com/1701393/78234186-1528af80-74d7-11ea-8ec9-ce4ca78e1712.png)

Je regarde pour voir comment on fait la suite.

**Comment by fxprunayre** [comment]
>  Mettra à jour l'ensemble des fiches pour que le mots-clés ne soit plus en characterstring mais avec une ancre.

Du coup mode: XPATH

* xpath:

```xpath2
.//mri:descriptiveKeywords[*/mri:keyword/gco:CharacterString/text() = 'infoMapAccessService']
```

* snippet:

```xml
<mri:MD_Keywords  xmlns:cit="http://standards.iso.org/iso/19115/-3/cit/2.0" 
                  xmlns:mri="http://standards.iso.org/iso/19115/-3/mri/1.0"
                  xmlns:mcc="http://standards.iso.org/iso/19115/-3/mcc/1.0"
                  xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0"
                  xmlns:gcx="http://standards.iso.org/iso/19115/-3/gcx/1.0"
                  xmlns:xlink="http://www.w3.org/1999/xlink">
  <mri:keyword>
    <gcx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/infoMapAccessService">Service d’accès aux cartes</gcx:Anchor>
  </mri:keyword>
  <mri:type>
    <mri:MD_KeywordTypeCode codeList="http://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#MD_KeywordTypeCode"
                             codeListValue="theme"/>
  </mri:type>
  <mri:thesaurusName>
     <cit:CI_Citation>
        <cit:title>
           <gcx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory#">Classification of spatial data services</gcx:Anchor>
        </cit:title>
        <cit:date>
           <cit:CI_Date>
              <cit:date>
                 <gco:Date>2008-12-03</gco:Date>
              </cit:date>
              <cit:dateType>
                 <cit:CI_DateTypeCode codeList="http://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#CI_DateTypeCode"
                                      codeListValue="publication"/>
              </cit:dateType>
           </cit:CI_Date>
        </cit:date>
        <cit:identifier>
           <mcc:MD_Identifier>
              <mcc:code>
                 <gcx:Anchor xlink:href="http://metawal.wallonie.be/geonetwork/srv/fre/thesaurus.download?ref=external.theme.httpinspireeceuropaeumetadatacodelistSpatialDataServiceCategory-SpatialDataServiceCategory">geonetwork.thesaurus.external.theme.httpinspireeceuropaeumetadatacodelistSpatialDataServiceCategory-SpatialDataServiceCategory</gcx:Anchor>
              </mcc:code>
           </mcc:MD_Identifier>
        </cit:identifier>
     </cit:CI_Citation>
  </mri:thesaurusName>
</mri:MD_Keywords>
```

@stephyritz je te laisse tester sur une fiche et faire les 3 cas possibles ? et faire la manip d'import du thésaurus (avec langue anglais + francais) et suppression de l'ancien.

**Comment by stephyritz** [comment]
J'ai toujours ce problème d'import de thesaurus en environnement de test.

![image](https://user-images.githubusercontent.com/34446202/78645111-3e6e8480-78b7-11ea-8aa7-8bed940d6d5f.png)

Même message d'erreur quand je tente de charger le thesaurus depuis un fichier local (en xml).

Sinon, réalisation du batchedit en test.Ensuite --> Validation INSPIRE OK

Donc manip en prod planifiée pour très bientôt.

Reminder doc -->
[batche_edit_category_service.docx](https://github.com/SPW-DIG/metawal-core-geonetwork/files/4445194/batche_edit_category_service.docx)

**Comment by stephyritz** [comment]
Batch editing fait en prod. J'ai remplacé le thesaurus en prod.
