### ISSUE TITLE
Edition / Keyword thesaurus GEMET et thème GP

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#534]
J'ai créé des templates à partir desquels je vais créer mes fiches plutôt que utiliser systématiquement la duplication. Pour cela, j'ai vidé le contenu lié aux keywords. Mais maintenant, lorsque j'encode des keywords relatif aux thesaurus thème du Géoportail ou GEMET, la valeur est réinitialisé à "missing" dès que j'enregistre.

To reproduce : 
1. Création d'une fiche depuis le template (http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/e39eb47d-041c-4db2-b5b8-c1d80a3101eb)
2. Passer en vue complète (pareil en vue simple)
3. Choisir un keyword dans la codelist thème du Géoportail (ou GEMET)
4. Enregistrer la fiche
5. Aucune valeur n'est prise en compte dans la fiche

PS : j'ai essayé de rajouter un mots clé sur une fiche lorsqu'il y a déjà un autre mot clé du thesaurus et ça fonctionne. Par ailleurs, ce sont les deux catégories de mots-clés où il n'y a pas la possibilité de jouer sur les paramètres en vue avancée. Est-ce liée ?

Testé sur la fiche http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/c34743fa-7c50-4bfe-b587-e1253ff68eae

**Comment by fxprunayre** [comment]
A déployer @davinciagf

**Comment by davinciagf** [comment]
Testé avec succes - attention le modèle inclut des keywords vide  (GEMET,..) ==> attention si ces derniers ne sont pas complétés pour la visualisation.
