### ISSUE TITLE
Edition / Création d'une nouvelle fiche et mduid

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#535]
Lors de la création d'une nouvelle fiche, que ça soit via la duplication d'une existante ou par le biais d'un template, le mduid proposé par défaut est celui de la fiche initiale. Serait-il possible de faire en sorte que la valeur de l'identifiant soit mise à jour en même temps que la création de la nouvelle URL de la fiche avec le mduid correspondant ?
Pour l'instant, à ma connaissance, cela oblige l'utilisateur à "Enregistrer/Fermer" la fiche puis à copier/coller le mduid depuis l'url vers la valeur "identifiant".

**Comment by fxprunayre** [comment]
> le mduid proposé par défaut est celui de la fiche initiale.

Je ne comprends pas. Quand on crée une fiche (ou duplique), à moins de modifier l'appel à l'API, on est sur un mode 
```url
http://metawal4.test.wallonie.be/geonetwork/srv/api/records/duplicate?metadataType=METADATA&sourceUuid=14655&isChildOfSource=false&group=3&isVisibleByAllGroupMembers=false&targetUuid=&hasCategoryOfSource=true
```
avec targetUuid vide, donc `metadataUuid = UUID.randomUUID().toString();`

et l'éditeur s'ouvre avec `http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.edit#/metadata/14657?justcreated` le nouvel id interne de la copie.

Non ? Quel est le test ?

**Comment by stephyritz** [comment]
Le test est : 
1. Création d'une fiche à partir d'un modèle ou en dupliquant une fiche existante
2. La nouvelle fiche s'ouvre
3. le mduid est identique à la fiche initiale (modèle ou fiche dupliquée)
```
   <mdb:metadataIdentifier>
      <mcc:MD_Identifier>
         <mcc:code>
            <gco:CharacterString>4ae152d1-0a2a-481b-bde5-ec883d952b65</gco:CharacterString>
         </mcc:code>
         <mcc:codeSpace>
            <gco:CharacterString>urn:uuid</gco:CharacterString>
         </mcc:codeSpace>
      </mcc:MD_Identifier>
   </mdb:metadataIdentifier>
```

**Comment by stephyritz** [comment]
Pardon, je me suis trompé, ce n'est pas le mduid de la fiche qui n'est pas mis à jour mais l'identifiant de la donnée : 
```
               <cit:identifier>
                  <mcc:MD_Identifier>
                     <mcc:code>
                        <gco:CharacterString>92bea901-888f-4ae8-983f-b971bf6b50b5</gco:CharacterString>
                     </mcc:code>
                     <mcc:codeSpace>
                        <gco:CharacterString>http://geodata.wallonie.be/id/</gco:CharacterString>
                     </mcc:codeSpace>
                  </mcc:MD_Identifier>
               </cit:identifier>
```

Idem pour le lien direct vers la fiche
```
   <mdb:metadataLinkage>
      <cit:CI_OnlineResource>
         <cit:linkage>
            <gco:CharacterString>http://metawal.wallonie.be/geonetwork/srv/eng//metadata/92bea901-888f-4ae8-983f-b971bf6b50b5</gco:CharacterString>
         </cit:linkage>
         <cit:function>
            <cit:CI_OnLineFunctionCode codeList="http://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#CI_OnLineFunctionCode"
                                       codeListValue="completeMetadata"/>
         </cit:function>
      </cit:CI_OnlineResource>
  </mdb:metadataLinkage>
```

Discuté à l'instant avec François. La solution serait de, au moment de la création de la nouvelle fiche, mettre automatiquement ces valeurs à jour à partir du nouvel uuid généré.

**Comment by fxprunayre** [comment]
GN ref https://github.com/geonetwork/core-geonetwork/pull/4584

**Comment by davinciagf** [comment]
@fxprunayre, peux-tu vérifier si c'est bien pousser dans MW - je ne le vois pas suite au dernier merge.

**Comment by fxprunayre** [comment]
En effet. C'est bon maintenant.

**Comment by davinciagf** [comment]
Testé pour création de fiche depuis un modèle.

**Comment by stephyritz** [comment]
OK pour l'identifiant de la donnée.
NOK pour le lien direct vers la fiche :

```
   <mdb:metadataLinkage>
      <cit:CI_OnlineResource>
         <cit:linkage>
            <gco:CharacterString>http://metawal.wallonie.be/geonetwork/srv/fre//metadata/097e8d4e-9bad-4798-af85-9bdd3c76952a</gco:CharacterString>
         </cit:linkage>
         <cit:function>
            <cit:CI_OnLineFunctionCode codeList="http://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#CI_OnLineFunctionCode"
                                       codeListValue="completeMetadata"/>
         </cit:function>
      </cit:CI_OnlineResource>
  </mdb:metadataLinkage>
```

Exemple sur base de la création d'un fiche dataset depuis un modèle : http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/22e7de42-4e61-4fd4-99c3-c64285010266

**Comment by fxprunayre** [comment]
> NOK pour le lien direct vers la fiche :

Il n'y a aucune raison. cf. https://github.com/geonetwork/core-geonetwork/pull/4584/files#diff-b6ea78b48fba442f42e7a1254cfda0c5R502

De mon côté testé avec http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/c629d224-0b1f-49aa-98d8-69c8f0ddff3d
et ça me semble ok. Aucune référence à c629d224-0b1f-49aa-98d8-69c8f0ddff3d
![image](https://user-images.githubusercontent.com/1701393/79425018-5c2ba000-7fc1-11ea-8cfe-b61ecc57ac09.png)


Quel modèle ? Des manips faites ?

**Comment by davinciagf** [comment]
Je viens de faire le test en initiant la création depuis les modèles présents (manip faites à deux reprises) et c'est ok pour tous les modèles sauf le modèle : Nom de la couche de données.
Je regarde ce template

**Comment by stephyritz** [comment]
Arg.. Pas de chance, c'est sur celui-là que j'ai fait le test. ; )
S'il y a un problème sur le modèle, on le modifie! C'est un truc assez récent que j'ai mis en place. Selon les cas, je m'appuie dessus pour la création de fiche plutôt que de passer par dupliquer.

**Comment by fxprunayre** [comment]
http://metawal4.test.wallonie.be/geonetwork/srv/api/records/e39eb47d-041c-4db2-b5b8-c1d80a3101eb/formatters/xml?approved=true
Le modèle est e39, le lien /097e8 donc normal.

**Comment by stephyritz** [comment]
Ok j'ai corrigé le modèle et c'est tout bon maintenant. A un détail près (peut-être NOK depuis longtemps, je n'avais jamais vraiment vérifié) : ce lien renvoie vers une erreur 302 (même avec une fiche publiée).
