### ISSUE TITLE
CSW / Erreur lors du moissonnage

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#536]
Je requête en utilisant le CSW :
`http://metawal.wallonie.be/geonetwork/srv/fre/csw?request=GetRecords&service=CSW&version=2.0.2&namespace=xmlns(csw=http://www.opengis.net/cat/csw)&resultType=results_with_summary&outputSchema=http://www.isotc211.org/2005/gmd&outputFormat=application/xml&maxRecords=40&typeNames=gmd:MD_Metadata&elementSetName=full&constraintLanguage=CQL_TEXT&constraint_language_version=1.1.0`

J'obtiens le message suivant :

![image](https://user-images.githubusercontent.com/34446202/78862587-fcb91780-7a37-11ea-9a83-044ec4c6d984.png)

Est-ce que vous savez d'où cela peut venir ?

**Comment by fxprunayre** [comment]
Faut relancer. On peut augmenter le nombre max de fichiers ouverts (mais pas une bonne idée à long terme). Faut voir quelle est la valeur actuelle aussi? Au BRGM on augmentait les valeurs par défaut.

https://community.pivotal.io/s/article/Session-failures-with-Too-many-open-files

**Comment by stephyritz** [comment]
Merci. Faut relancer quoi ? Restarter la machine sur laquelle est Metawal ?

Doc API aussi en erreur : 
![image](https://user-images.githubusercontent.com/34446202/78863680-794cf580-7a3a-11ea-8f7e-bbc3004dc4ff.png)

C'est lié tu crois ?

**Comment by fxprunayre** [comment]
Metawal. Quand on est dans ce cas, on a un comportement aléatoire sur tous les services. Selon la disponibilité des fichiers ouverts (qui change selon ce qui se passe). L'origine est en général liée à Lucene et aux services de recherches. Je tente un truc pour voir si ça améliore la situation.

**Comment by stephyritz** [comment]
Ok. Je demande à Didier de redémarrer l'application.
PS : je ne sais pas ce que tu as fait mais ça a amélioré la situation en effet!

**Comment by fxprunayre** [comment]
L'URL répond là http://metawal.wallonie.be/geonetwork/srv/fre/csw?request=GetRecords&service=CSW&version=2.0.2&namespace=xmlns(csw=http://www.opengis.net/cat/csw)&resultType=results_with_summary&outputSchema=http://www.isotc211.org/2005/gmd&outputFormat=application/xml&maxRecords=40&typeNames=gmd:MD_Metadata&elementSetName=full&constraintLanguage=CQL_TEXT&constraint_language_version=1.1.0 
on peut le garder allumé et voir si ça revient

**Comment by fxprunayre** [comment]
La page de l'API aussi est ok

**Comment by fxprunayre** [comment]
Le "truc": optimisation de l'index.

![image](https://user-images.githubusercontent.com/1701393/78864676-676c5200-7a3c-11ea-8641-9fda05848a08.png)

Le principe, Lucene prend l'index et le réorganise pour supprimer tout ce qui ne sert à rien et donc réduit le nombre de fichiers (donc sans doute ceux ouverts par la même occasion).

**Comment by stephyritz** [comment]
D'accord, merci. Je ne demande pas le redémarrage alors.

**Comment by fxprunayre** [comment]
Faudrait regarder dans les logs pour savoir quand ça a commencé. Peut être en lien avec le geoportail ?

**Comment by stephyritz** [comment]
Même erreur ce matin (too many openfiles) : 

![2manyopenfiles_error](https://user-images.githubusercontent.com/34446202/79718346-20078080-82dc-11ea-9eee-d27e196de68a.png)

**Comment by fxprunayre** [comment]
Il faudrait des infos sur les serveurs:

```sh
ulimit -a | grep open
```
et savoir ce qu'il y a dans `/etc/security/limits.conf`
eg.
```csv
*                hard    nofile          65535
*                soft    nofile          65535
```

**Comment by stephyritz** [comment]
Réponse de Didier :
"metawal a été planté une bonne partie du weekend, je l'ai relancé ce matin.
niveau limites de fichiers il est déjà très bien :
metawal4 soft    nofile  65536
metawal4 hard    nofile  65536"

**Comment by stephyritz** [comment]
Apparemment, il y a des soucis depuis le 25/02 (date de dernière MeP)
![error_MW](https://user-images.githubusercontent.com/34446202/79735668-ebee8880-82f8-11ea-91c9-a16e6cd9fd85.png)

On me signale qu'il y a aussi des pb de communications FME --> MW. Exemple de requêtes qui pose problème --> http://metawal.wallonie.be/geonetwork/srv/fre/xml.metadata.get?uuid=88f5f3ce-98f5-4ab3-b226-ad8a9692a339
 De manière aléatoire, probablement quand MW est down car ça passe bien à l'instant.

**Comment by fxprunayre** [comment]
Il faut crier quand ça tombe comme ça!
On peut savoir ce qui est vérifié ? Quelle est l'heure ? Est-ce toujours la même ? Est ce qu'il y a un reboot/restart auto ? Est-ce qu'on peut avoir accès pour avoir plus d'info ?

**Comment by stephyritz** [comment]
Voila ce que Didier m'a transmis comme info sur les checks réalisés --> http://metawal.wallonie.be/geonetwork/criticalhealthcheck

Et voici les détails pour la période du 14/04 au 19/04
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/34446202/80184618-39c20400-860b-11ea-952c-eeaac7be4d42.png)

J'ai demandé à Didier d'envoyer le plus de détails possibles à Arnaud pour que vous puissiez comprendre d'où ça vient.

**Comment by davinciagf** [comment]
Problème avec la fiche http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/0beee14d-aa34-46ba-9f43-de5cf2308b53 je vérifie

**Comment by davinciagf** [comment]
Non cela ne semble pas lié à la fiche. Le criticalhealthcheck ne vérifie que si la balise ServiceIdentification est bien présente dans le getcapabilities du CSW. Il semble donc que le serveur tombe puis se remette en marche. Il faudrait les logs de la prod pour approfondir.

**Comment by stephyritz** [comment]
Cette nuit, erreur lors de la synchro en test -- > 

Synchronisation exécutée en : 00:00:01.140
101 metadata(s)
0 mises à jour
Erreurs d'execution : 100
Le nombre élevé d'erreur de traitement a provoqué l'interruption de la mise à jour

**Comment by vbombaerts** [comment]
Je n'ai pas remarqué d'erreur en prod dernièrement.
Je ferme.
