### ISSUE TITLE
Edition / Problème accès édition sur une fiche

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#538]
C'est un problème spécifique à une fiche. Au moment de la création (depuis un modèle) puis édition de cette fiche il y a quelques jours, j'ai eu un message d'erreur au moment de la sauvegarde du genre "concomitent update". Depuis, je ne peux plus accéder correctement à l'interface d'édition de la fiche. Seuls les boutons sont présents et sont plus ou moins actifs.
La fiche en question --> http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/2a5ef10f-36f8-4bb0-9188-781ac089b7ce

J'ai essayé : vider le cache, reconstruire l'index, supprimer la fiche puis la ré-importer, créer une nouvelle fiche et copier le contenu du xml. Rien à faire, je n'arrive pas à repartir de cette fiche pour continuer l'édition. 

Est-ce que vous avez une idée pour résoudre ce problème ? D'où cela peut-il venir ?

[2a5ef10f-36f8-4bb0-9188-781ac089b7ce.zip](https://github.com/SPW-DIG/metawal-core-geonetwork/files/4480916/2a5ef10f-36f8-4bb0-9188-781ac089b7ce.zip)

**Comment by fxprunayre** [comment]
Sur ces cas là, pour dépanner dans un premier temps : une approche. Ouvrir les outils web dans le navigateur

![image](https://user-images.githubusercontent.com/1701393/79335166-da386a00-7f21-11ea-8b09-12eed9b59bf7.png)

Repérer l'appel de l'éditeur qui est sans doute en erreur (probablement un pb XSL d'un cas non géré).

```xml
<apiError>
  <code>runtime_exception</code>
  <description>A sequence of more than one item is not allowed as the first argument of normalize-space() ("data-gn-field-duration-div", "data-gn-field-duration-div") </description>
  <message>XPathException</message></apiError>
```

Si ça nous donne une piste, ouvrir la fiche en édition XML 
http://metawal.wallonie.be/geonetwork/srv/fre/catalog.edit#/metadata/14717?tab=xml&

Dans ce mode là, il y a très peu de chance de tomber en erreur.

Ici, le pb est (probablement - je n'ai pas testé) lié à 
```xml
      </gex:geographicElement>
               <gex:temporalElement>
                  <gex:EX_TemporalExtent>
                     <gex:extent>
                        <gml:TimePeriod gml:id="d156569e400a1050910">
                           <gml:beginPosition>2006-01-01</gml:beginPosition>
                           <gml:endPosition>2018-12-31</gml:endPosition>
                           <gml:duration/>
                           <gml:duration/>
                        </gml:TimePeriod>
                     </gex:extent>
```

Si on supprime un `gml:duration` on devrait pouvoir sauvegarder ? Je te laisse tester @stephyritz 

Ce qu'on pourrait faire pour améliorer ça, c'est de faire remonter l'erreur dans l'interface et faire un lien pour ouvrir le mode XML. ?

**Comment by stephyritz** [comment]
Bien vu!! C'était bien ça. Oui bonne idée de proposer à l'utilisateur d'ouvrir en mode xml. Peut-être que j'aurais pu trouver l'erreur.. Mais sûrement pas aussi vite que tu ne l'as fait!
