### ISSUE TITLE
CSW / Fiche non publiée

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#539]
Je découvre un nouveau "truc" aujourd'hui !
J'ai donc créé la fiche suivante : metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/2a5ef10f-36f8-4bb0-9188-781ac089b7ce

Mais c'est une ébauche. Je ne l'ai pas publié et pourtant elle apparaît ainsi dans le GP : http://geoportail.wallonie.be/catalogue/2a5ef10f-36f8-4bb0-9188-781ac089b7ce.html

Je suis très surpris! C'est jamais arrivé en un an et ça m'étonnerait que le GP ait changé une règle (mais peut-être que si?!). Mes questions : 
1. Est-ce normal que la fiche apparaisse dans le csw si elle n'est pas publié ? (risque de se la faire moissonner alors qu'elle n'es pas prête)

2. Est-ce que c'est plutôt au GP de ne moissonner que les fiche publiée ?

3. Visiblement, il y avait quelque chose de prévue à ce sujet avant mon arrivée vu que sur la fiche il est mentionnée "Cette donnée n'est pas encore disponible. Restez informé en l'ajoutant à vos notifications." Donc ce cas de figure était visiblement souhaité. Vous avez des infos à ce sujet ?

En tout cas c'est très surprenant! Est-ce lié à une info quelque part dans la MD ? Pourquoi seulement cette fiche ? Il faut que je fasse donc très attention parce que actuellement je créé les fiche en prod en considérant qu'elles ne seront que visibles une fois publiée. Si ce n'est pas le cas, je peux envisager de travailler autrement, par exemple, utiliser l'environnement de test tant que la fiche n'est pas prête à publication. Qu'en pensez-vous ?

**Comment by fxprunayre** [comment]
La fiche a comme privilège
![image](https://user-images.githubusercontent.com/1701393/79449620-db31d000-7fe3-11ea-82ff-9bedac804b44.png)

En supprimant la config réseau dans admin console > paramètre, on a
![image](https://user-images.githubusercontent.com/1701393/79449665-eedd3680-7fe3-11ea-8c4b-e9322a98b3a7.png)

Donc le pb vient de la conf intranet.

On fait quoi à court terme ?
1) suppression config réseau
2) suppression privilège intranet

**Comment by stephyritz** [comment]
Je comprends pas tout les tenants et aboutissants de cette manip. Donc je ne sais pas trop quoi te répondre. 

Il me semble à première vu plus facile de couper le privilège intranet à court terme. Tu m'expliqeras tout à l'heure au tel en quoi se privilège activé donne accès à une fiche non publiée via le CSW. Et visiblement, le GP est prêt à recevoir ce type d'info puisque la logique mise en place pourrait se tenir si ma fiche n'était pas une ébauche. 

Pour la config réseau, est-ce un souci dans la config qui aurait dû seulement donné accès à la fiche si la machine utilisée fait partie d'un range d'IP ? On en discute aussi de vive voix pour voir ce qu'on fait pour le moyen/long terme.

Merci pour la réactivité
