### ISSUE TITLE
Recherche / Autocomplétion avec accents

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#54]
Si 'EAU' donne des résultats.
Si ajoute dans les thème du géoportail : Nature, ca va bien. Si à la place (ou en plus) c'est 'aménagement' (accent) ca ne va plus.
Si ajoute n'importe quel thème Inspire ca cale aussi.

**Comment by metawaltest** [comment]
Idem si on recherche par organisation, certaines fonctionnent (cellule SIG) d'autres non (Direction du développement rural, région wallonne,...)

**Comment by fxprunayre** [comment]
Tests réalisés:
- sur test
  - 13 résultats = ok http://metawal.spacebel.be/geonetwork/srv/fre/q?fast=index&from=1&to=20&any=amenagement&hitsperpage=20
  - 0 résultat = nok  http://metawal.spacebel.be/geonetwork/srv/fre/q?fast=index&from=1&to=20&any=am%C3%A9nagement&hitsperpage=20
- en local = ok http://localhost:8080/geonetwork/srv/fre/q?fast=index&from=1&to=20&any=am%C3%A9nagement&hitsperpage=20
  retourne la même chose que http://localhost:8080/geonetwork/srv/fre/q?fast=index&from=1&to=20&any=amenagement&hitsperpage=20

Piste: @davinciagf  pb de config JBoss ? encoding de caractère

**Comment by davinciagf** [comment]
Modification de la configuration du serveur d'application jboss (ajouter l'élément "URIEncoding="UTF-8")
 ${JBOSS_HOME}/server/(default)/deploy/jboss-web.deployer/server.xml:
<Connector port="8080" URIEncoding="UTF-8"/>

**Comment by vbombaerts** [comment]
Ne fonctionne toujours pas, même après création d'une nouvelle fiche et reconstruction de l'index.
![image 685](https://f.cloud.github.com/assets/6093597/1909846/e23f25b8-7d07-11e3-89c5-a5fb09948ea0.png)
![image 686](https://f.cloud.github.com/assets/6093597/1909847/e540861c-7d07-11e3-8950-2cacc741eb99.png)

**Comment by vbombaerts** [comment]
Il y a une réelle amélioration, mais même après reconstruction de l'index, la suggestion des mots-clés ne tient pas compte des accents. 
![image 694](https://f.cloud.github.com/assets/6093597/1995991/6b7219be-850d-11e3-8a2e-9533924a4125.png)
![image 693](https://f.cloud.github.com/assets/6093597/1995992/6ff1d1dc-850d-11e3-891e-f768538fd73f.png)

**Comment by fxprunayre** [comment]
C'est une évolution demandée dans Géosource. Ce sera dispo lors du prochain alignement avec GN, si ça convient ? Cf. https://github.com/geonetwork/core-geonetwork/issues/357

**Comment by fxprunayre** [comment]
Fixed in https://github.com/spacebelGIS/metawal-core-geonetwork/commit/20bd09e5bf89e3b8fed2ac612e85080488a62062

**Comment by vbombaerts** [comment]
La fonction marche presque parfaitement. Il reste un problème : les mots suggérés sont systématiquement proposés sans accents (même ceux qui en ont). Est-il possible d'encore améliorer ce point ?
![image 714](https://f.cloud.github.com/assets/6093597/2510578/66343cb8-b409-11e3-91c5-1d9153cbcb88.png)

**Comment by fxprunayre** [comment]
> Est-il possible d'encore améliorer ce point ?

Non sans des travaux conséquents. Les suggestions sont les informations stockées dans l'index. Fonction du champ (dans la capture d'écran, le champ full text) les valeurs retournées peuvent être différentes fonction de l'analyse des informations faite à l'indexation (eg. lowercase, tokenization, stopword filter, ...). Pour le champ full text, l'analyse est "conséquente", pour les mots clés, il n'y en a pas.

Il serait envisageable d'utiliser de nouveaux modules de Lucene pour améliorer la qualité des suggestions.

Proposition: changer la milestone à version future ?

**Comment by vbombaerts** [comment]
Toujours au même point : une chaine de recherche avec un caractère accentué engendre des propositions qui correspondent mais non accentuées.
Ca ne gène pas le fonctionnement. Priorité basse et à surveiller pour les versions futures.

**Comment by gdetry** [comment]
Passage ELASTICSEARCH
