### ISSUE TITLE
Batchediting / Utilisation de l'API depuis FME

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#546]
Plusieurs données sont mises à jour en utilisant des process FME. Actuellement, dans ces process, des transformers spécifiques sont utilisés pour modifier la date de révision des données et la date de mise à jour de la fiche. Pour cela, nous passons par du CSW-T. L'idée serait de passer directement par l'API de Geonetwork afin d'éviter les potentiels problèmes liés à la "communication entre machine". C'est aussi une manière de faire un peu plus puissante ?!

Pour faire cela, j'imagine que, dans FME, il faudrait utiliser 2 "http caller" pour http://metawal.wallonie.be/geonetwork/doc/api/index.html#/selections/getSelection et puis http://metawal.wallonie.be/geonetwork/doc/api/index.html#/records/batchEdit

Reste les questions d'authentification. Plusieurs méthode sont proposées dans le transformer : 
![image](https://user-images.githubusercontent.com/34446202/86453689-7c484100-bd1e-11ea-93ca-6992afe2a2e2.png)

Je dois choisir quoi ?

**Comment by fxprunayre** [comment]
Basic. Mais dans GeoNetwork il faut également avoir un token (tu peux tenter sans). Cf. https://geonetwork-opensource.org/manuals/trunk/en/customizing-application/misc.html?highlight=curl

**Comment by stephyritz** [comment]
A priori, pour un getrecord sur une fiche non publiée l'authentification "Basic" suffit. Je continue les tests sur d'autres opérations
