### ISSUE TITLE
Authentification / LDAP et groupe

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#548]
J'ai l'impression que les paramètres liés aux groupes de l'utilisateur id = 50801 ne sont pas sauvegardés correctement.
Cela fait plusieurs fois que je suis obligé de le "remettre dans le groupe DIG". Un peu comme si les options du user se remettent régulièrement à zéro. Est-ce qu'il y a une explication possible côté LDAP/GN ? Il me semble que pour ce user, la manip n'avait pas été : 
1. Création du compte par un admin depuis Metawal
2. Connexion du user
3. Attribution du rôle dans un groupe

MAIS
1. Connexion du user directement avec ses identifiants LDAP
2. Attribution du rôle dans un groupe

J'ai l"impression qu'avec la deuxième procédure, il y a un problème avec la sauvegarde des informations. Est-ce possible d’analyser d'où proviendrait l'erreur ?

**Comment by stephyritz** [comment]
Problème relevé sur un cas unique. Comportement anormal de l'application mais rare. Je ferme donc le ticket.

**Comment by fxprunayre** [comment]
Cf. https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.0.x/core/src/main/java/org/fao/geonet/kernel/security/ldap/LDAPSynchronizerJob.java

Probablement à désactiver ici
https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.0.x/web/src/main/webapp/WEB-INF/config-security/config-security-ldap.xml
