### ISSUE TITLE
CSW / Outputschema 'mw'

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#549]
Demande de modification du xslt configuré pour générer l'outputschema 'mw'. En effet, pour ce schema spécifique au moissonnage du Géoportail, le serviceType doit être sous la forme
```
<srv:serviceType>
   <gco:LocalName>$VALEUR</gco:LocalName>
</srv:serviceType>
```
avec $VALEUR = 'OGC:WMS' OR 'ESRI:REST' OR 'view'

Visiblement, pour les fiches INSPIRE ($VALEUR = 'view'), le xslt ne gère pas pour l'instant la suppression du paramètre codespace=url.

Exemple NOK [$VALEUR = 'view'] --> http://metawal.wallonie.be/geonetwork/srv/fre/csw?request=GetRecordById&service=CSW&outputSchema=mw&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=d2e9a58f-8c03-4302-9aa3-a0db3da0b821

Exemple OK [$VALEUR = 'OGC:WMS' OR 'ESRI:REST'] --> http://metawal.wallonie.be/geonetwork/srv/fre/csw?request=GetRecordById&service=CSW&outputSchema=mw&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=5ce648c9-5e2b-4270-8992-899c7bdc5ca5

**Comment by fxprunayre** [comment]
A déployer.
