### ISSUE TITLE
Schema / Mots-clés Thème Géoportail

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#551]
Plusieurs actions à faire sur ce point. La première est de l'ordre de la correction de bug, la deuxième une amélioration : 
 - [x] Rétablir le nom correct du thesaurus sur l’ensemble des fiches par le biais d'une requête sql en DB
 - [x] Déclarer les mots-clés thèmes du Géoportail avec des ancres et les hrefs vers le thesaurus. Ainsi, apparaitra la notion de hiérarchie dans le xml grâce à la clé présente dans l'uri. Attention, bien pensé à mettre à jours le xslt spécifique à la transcription au schéma 'mw' utilisé par le Géoportail où il est nécessaire de conserver la structure actuelle.

**Comment by stephyritz** [comment]
Proposition de requête SQL à jouer pour répondre au 1er point : 
```
UPDATE metadata SET data = replace(data,
    '<gcx:Anchor xlink:href="http://metawal.wallonie.be/thesaurus/Themes_geoportail_wallon_hierarchy">Thèmes du géoportail wallon, version 1.0</gcx:Anchor>',
    '<gcx:Anchor xlink:href="http://metawal.wallonie.be/thesaurus/Themes_geoportail_wallon_hierarchy">Thèmes du géoportail wallon</gcx:Anchor>')
    WHERE data LIKE '%<gcx:Anchor xlink:href="http://metawal.wallonie.be/thesaurus/Themes_geoportail_wallon_hierarchy">Thèmes du géoportail wallon, version 1.0</gcx:Anchor>%';
```

En prod, normalement 1036 rows concernées
En valid --> 1013
En test --> 694 (?) @davinciagf  tu peux la jouer sur test stp ? Pourquoi il y a tant de fiches non concernées ? Est-ce que toutes les requêtes sql ont bien été jouées pareil sur tous les environnements ?

**Comment by davinciagf** [comment]
Lors des tests pour le GP, on fait une erreur dans la requête en test et on avait introduit un correctif avant d'envoyer la bonne requête en valid/prod mais effectivement, le nombre de fiches concernées par ces requêtes étaient inférieures à 700 (et ce dès la première sql)

**Comment by davinciagf** [comment]
Pour le point :
- [x] Rétablir le nom correct du thesaurus sur l’ensemble des fiches par le biais d'une requête sql en DB

La requète est à valider en test après actualisation de la DB de test sur base de la DB de production!

Complément:
- [x] Vérifier l'UI en mode édition pour ce thesaurus (seules les valeurs des mots clés doivent apparaître en mode édition - on ne doit pas avoir toutes les valeurs (titre, date de publi, identifiants,...))

**Comment by davinciagf** [comment]
La test à été mise à jour sur base de la DB de prod ce 09092020.

La requete suivante donne 1037 éléments.

```
SELECT` count(*) FROM metadata WHERE data LIKE '%<gcx:Anchor xlink:href="http://metawal.wallonie.be/thesaurus/Themes_geoportail_wallon_hierarchy">Thèmes du géoportail wallon, version 1.0</gcx:Anchor>%';
```

**Comment by davinciagf** [comment]
On peut testé la requete en test et voir si impact sur le GP.
Laisse-t-on l'ancienne référence au thesaurus au niveau de l'ancre (aucun impact selon les dev du GP)?

`
<gmx:Anchor xlink:href="http://metawal.wallonie.be/geonetwork/srv/eng/thesaurus.download?ref=external.theme.Themes_geoportail_wallon">geonetwork.thesaurus.external.theme.Themes_geoportail_wallon</gmx:Anchor>
`

**Comment by stephyritz** [comment]
Tu parles bien de la valeur dans ../mcc:MD_Identifier/mcc:code ?
J'ai l'impression que la valeur actuellement présente dans les fiches est 
`<gcx:Anchor xlink:href="http://metawal.wallonie.be/geonetwork/srv/api/registries/vocabularies/external.theme.Themes_geoportail_wallon_hierarchy">geonetwork.thesaurus.external.theme.Themes_geoportail_wallon_hierarchy</gcx:Anchor>`
L'essentiel c'est qu'il y est de la cohérence entre la valeur du ../MD_Identifier/mcc:code et l'uri de la href de ../mri:thesaurusName/cit:CI_Citation/cit:title. Or, je pense que c'est le cas actuellement. Donc si tu confirmes cela, on ne touche pas à ce contenu, juste au nom du thesaurus.

**Comment by stephyritz** [comment]
Problème toujours présent pour une cinquantaine de fiches. En effet, elles ne possèdent pas de Identifier et donc le xsl de transfo spécifique au schéma "mw" ne s'applique pas à leur cas. Conséquence --> Absence de ces fiches dans le catalogue de WalonMap. Pour solutionner ce problème, cf https://github.com/SPW-DIG/metawal-core-geonetwork/issues/553

**Comment by stephyritz** [comment]
Attention, dans le xsl de transformation pour le schema "maw", le titre du thesaurus est écrasé par la valeur 'Thèmes du géoportail wallon, version 1.0'. Fichier à modifier donc lors de la prochaine release pour ne changer que la valeur des keywords (ajout de la clé chiffrée).

**Comment by fxprunayre** [comment]
- [x]  CSW / mw-full / Check sur le titre et pas uniquement le code `mri:thesaurusName/*/cit:identifier/*/mcc:code/*/text() = 'geonetwork.thesaurus.external.theme.Themes_geoportail_wallon_hierarchy' or contains(mri:thesaurusName/*/cit:title/*/text(), 'Thèmes du géoportail wallon')`

- [x] Editor / Config pour utiliser le mode Anchor

```xml
<mri:descriptiveKeywords>
            <mri:MD_Keywords>
               <mri:keyword>
                  <gcx:Anchor xlink:href="http://metawal.wallonie.be/thesaurus/theme-geoportail-wallon#SubThemesGeoportailWallon/1020">Eau</gcx:Anchor>
               </mri:keyword>
               <mri:keyword>
                  <gcx:Anchor xlink:href="http://metawal.wallonie.be/thesaurus/theme-geoportail-wallon#SubThemesGeoportailWallon/1030">Sol et sous-sol</gcx:Anchor>
               </mri:keyword>
               <mri:keyword>
                  <gcx:Anchor xlink:href="http://metawal.wallonie.be/thesaurus/theme-geoportail-wallon#SubThemesGeoportailWallon/5030">Photos et imagerie</gcx:Anchor>
               </mri:keyword>
               <mri:type>
                  <mri:MD_KeywordTypeCode codeList="http://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#MD_KeywordTypeCode"
                                          codeListValue="theme"/>
               </mri:type>
               <mri:thesaurusName>
                  <cit:CI_Citation>
                     <cit:title>
                        <gcx:Anchor xlink:href="http://metawal.wallonie.be/thesaurus/theme-geoportail-wallon">Thèmes du géoportail wallon</gcx:Anchor>
                     </cit:title>
                     <cit:date>
                        <cit:CI_Date>
                           <cit:date>
                              <gco:Date>2015-12-17</gco:Date>
                           </cit:date>
                           <cit:dateType>
                              <cit:CI_DateTypeCode codeList="http://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#CI_DateTypeCode"
                                                   codeListValue="publication"/>
                           </cit:dateType>
                        </cit:CI_Date>
                     </cit:date>
                     <cit:identifier>
                        <mcc:MD_Identifier>
                           <mcc:code>
                              <gcx:Anchor xlink:href="http://localhost:8080/geonetwork/srv/api/registries/vocabularies/external.theme.Themes_geoportail_wallon_hierarchy">geonetwork.thesaurus.external.theme.Themes_geoportail_wallon_hierarchy</gcx:Anchor>
```


- [ ] Migrer les fiches actuelles

**Comment by stephyritz** [comment]
Pour la migration des fiches actuelles, on fait comment ? En DB ou via un xsl au moment du déploiement ?
En tout cas, il faudra bien veiller à également adapter le xsl lié à l'outputschema "mw" en parallèle.

**Comment by davinciagf** [comment]
Process "movetoanchor" à jouer avec le thesaurus du Geoportail.

Cf. https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.0.x/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/move-keyword-to-anchor.xsl

**Comment by davinciagf** [comment]
Testé sur la fiche:

http://metawal4.test.wallonie.be/geonetwork/srv/api/records/78e0c182-dbf4-4033-9bb0-e0acfd93be7b/formatters/xml?approved=true

CSW - geoportail
http://metawal4.test.wallonie.be/geonetwork/srv/fre/csw?request=GetRecordById&service=CSW&outputSchema=mw&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=78e0c182-dbf4-4033-9bb0-e0acfd93be7b

**Comment by stephyritz** [comment]
Ok, super. Le résultat est bon sur cette fiche. GO pour le déploiement sur l'ensemble des fiches.

**Comment by stephyritz** [comment]
NOK en prod. Toujours des caracterstring pour les mots-clés du GP. Exemple : http://metawal.wallonie.be/geonetwork/srv/api/records/78e0c182-dbf4-4033-9bb0-e0acfd93be7b/formatters/xml?approved=true
