### ISSUE TITLE
Recherche renvoie trop de résultats

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#552]
La recherche sur Metawal d'un ensemble de mots (comme Atlas des voiries vicinales) renvoie beaucoup trop de résultats (845 dans ce cas).

1. Sur http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/home
2. Dans la recherche, mettre _Atlas des voiries vicinales_ (ou choisir un des résultats suggérés)
3. Enter

C'est comme si la recherche portait sur chacun des mots, avec un OU. La recherche a donc perdu énormément de pertinence.
Testé sur Edge et Chrome.

Dans les paramètres je n'ai pas vu de champs permettant de changer ce comportement.

**Comment by fxprunayre** [comment]
La recherche full text est proche d'un OU mais pas tout à fait quand même. On a en premier les fiches les plus pertinentes.

Sur le cas `Atlas des voiries vicinales` le fait d'ajouter des guillemets `"Atlas des voiries vicinales"`
http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/search?any=%22atlas%20des%20voiries%20vicinales%22
fera une recherche de la phrase et donc va restreindre les résultats.

Globalement les 6 premiers résultats sont les mêmes - on a juste le 'Atlas du karst wallon - Série' qui est placé en 5ème position dans la recherche sans guillemet.

C'est un peu comme dans google, seul la première page compte...

**Comment by stephyritz** [comment]
Effectivement la recherche renvoie plus de résultats mais les premiers sont plus "pertinents" qu'avant (notions de priorité sur les séries, en cas de présence dans le titre, etc...). Le revers de la médaille c'est cette multitude de résultats et surtout le contenu du résultat renvoyé après avoir choisi une suggestion. En effet, quand on sélectionne le titre d'une fiche suggéré, on s'attend à avoir comme résultat unique (ou au moins en premier) cette fiche dont le titre a été suggéré. Or, ce n'est pas le cas car la recherche ne s’appuie pas uniquement sur le titre et donne priorité aux séries.

Pour pallier à ce "problème", sans pour autant obliger l'utilisateur à saisir les guillemets, nous pouvons proposer à côté de la barre de recherche une case à cocher (ou cochée par défaut sur MW) 'recherche exacte' qui reproduirait le comportement comme pour les guillemets. Cela s'appliquerait aussi aux suggestions.

**Comment by fxprunayre** [comment]
Option 1 ) 

![image](https://user-images.githubusercontent.com/1701393/95055892-3c657100-06f4-11eb-80c3-8ecc1ea3c508.png)

Option 2 )

![image](https://user-images.githubusercontent.com/1701393/95055906-40918e80-06f4-11eb-881c-ce26fb02ca82.png)

**Comment by fxprunayre** [comment]
GN ref https://github.com/geonetwork/core-geonetwork/pull/5072

**Comment by fxprunayre** [comment]
@davinciagf tu peux déployer sur test. On est aligné sur GN4.alpha3 donc (cf. https://github.com/geonetwork/doc/blob/4.0.x/source/overview/change-log/version-4.0.0-alpha.3.rst).

**Comment by fxprunayre** [comment]
"exact match" on suggest ou mettre des `"` pour les suggestions

**Comment by stephyritz** [comment]
Ok pour mettre " " dans les suggestions. C'est pas hyper esthétique mais me semble être la solution la plus efficace actuellement pour obtenir le comportement souhaité.
