### ISSUE TITLE
GéoPortail / Fiches non catégorisées

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#553]
Pour le pb
http://metawal.wallonie.be/geonetwork/srv/api/records/9d18f60b-9652-4c5c-bcc2-01560224eecc/formatters/xml
La fiche n'a pas de thesaurusName/*/identifier donc on entre pas dans le mapping.

## Correction via batch edit

Faire un backup de la base avant.
Tester sur une fiche d'abord.

* Mode insert
* XPath

```xpath
.//cit:CI_Citation[cit:title/*/text() = 'Thèmes du géoportail wallon' and not(cit:identifier)]
```

* Snippet
```xml
<cit:identifier xmlns:cit="http://standards.iso.org/iso/19115/-3/cit/2.0" xmlns:gcx="http://standards.iso.org/iso/19115/-3/gcx/1.0" xmlns:mcc="http://standards.iso.org/iso/19115/-3/mcc/1.0" xmlns:xlink="http://www.w3.org/1999/xlink" >
<mcc:MD_Identifier>
<mcc:code>
<gcx:Anchor xlink:href="http://metawal.wallonie.be/geonetwork/srv/api/registries/vocabularies/external.theme.Themes_geoportail_wallon_hierarchy">geonetwork.thesaurus.external.theme.Themes_geoportail_wallon_hierarchy</gcx:Anchor>
</mcc:code>
</mcc:MD_Identifier>
</cit:identifier>
```

**Comment by stephyritz** [comment]
Merci!

Essai fait sur une fiche : http://metawal4.test.wallonie.be/geonetwork/srv/fre/csw?request=GetRecordById&service=CSW&outputSchema=mw&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=9c627c08-07fa-41e9-b0c8-fe00503766e7

C'est plutôt concluant ! ; ) Je vais le faire sur l'ensemble des fiches problématiques dans les 3 environnement.

**Comment by stephyritz** [comment]
Batchedit lancé depuis FME en test en utilisant successivement : 
1. http://metawal4.test.wallonie.be/geonetwork/srv/api/search/records/_search
2. http://metawal4.test.wallonie.be/geonetwork/srv/api/selections
3. http://metawal4.test.wallonie.be/geonetwork/srv/api/records/batchediting

Édition de 117 fiches réalisées avec succès en 1'15

Vérification DB avec les sql suivant : 
`SELECT * FROM metawal4.metadata where data like '%<gcx:Anchor xlink:href="http://metawal.wallonie.be/geonetwork/srv/api/registries/vocabularies/external.theme.Themes_geoportail_wallon_hierarchy">geonetwork.thesaurus.external.theme.Themes_geoportail_wallon_hierarchy</gcx:Anchor>%'`

Résultat en TEST après batchedit : 997 rows
Résultat en PROD avant batchedit : 884 rows

Cela confirme que le traitement a bien fonctionné en TEST. Dernière vérification à prévoir côté Géoportail de TEST avant d'appliquer cette méthode dans les environnements de VALID et de PROD.

Méthode intéressante et efficace pour le batchediting.

**Comment by stephyritz** [comment]
Erreur en environnement de valid (403) : 
`<!DOCTYPE html><html><head><title>Apache Tomcat/8.5.9 - Error report</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style> </head><body><h1>HTTP Status 403 - Forbidden</h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u>Forbidden</u></p><p><b>description</b> <u>Access to the specified resource has been forbidden.</u></p><hr class="line"><h3>Apache Tomcat/8.5.9</h3></body></html>`

Même paramètre que pour l'environnement de test. Problème d'authentification via le protocole sécurisé de GN ? Problème d'accès à l'environnement de valid depuis la machine hébergeant FME ?

**Comment by stephyritz** [comment]
Même erreur en prod

**Comment by fxprunayre** [comment]
```sh
export CATALOG=http://metawal.wallonie.be/geonetwork
export CATALOGUSER=abc
export CATALOGPASS=xyz
rm -f /tmp/cookie; 

curl -s -c /tmp/cookie -o /dev/null -X GET "$CATALOG/srv/api/me" -H "accept: application/json"; 
export TOKEN=`grep XSRF-TOKEN /tmp/cookie | cut -f 7`; 
curl -X GET -H "X-XSRF-TOKEN: $TOKEN" --user $CATALOGUSER:$CATALOGPASS -b /tmp/cookie \
  "$CATALOG/srv/api/me" -H "accept: application/json" 



curl -X POST "$CATALOG/srv/api/search/records/_search?bucket=111" \
    -H 'Accept: application/json' \
    -H 'Content-Type: application/json;charset=utf-8' \
    -H "X-XSRF-TOKEN: $TOKEN" -c /tmp/cookie -b /tmp/cookie --user $CATALOGUSER:$CATALOGPASS \
    -d '{"from":0,"size":0,"query":{"query_string":{"query":"+linkUrl:*data-and-maps*"}}}'
```

fonctionne bien avec CURL. Donc sans doute plus un problème côté FME.

Erreur avec un utilisateur bidon

```
curl -X GET -H "X-XSRF-TOKEN: $TOKEN" --user $CATALOGUSER:$CATALOGPASS -b /tmp/cookie \
>   "$CATALOG/srv/api/me" -H "accept: application/json" 
<!DOCTYPE html><html><head><title>Apache Tomcat/8.5.9 - Error report</title>
<style type="text/css">h1 {...;}</style> </head><body>
<h1>HTTP Status 401 - Unauthorized</h1><div class="line"></div>
<p><b>type</b> Status report</p><p><b>message</b> 
<u>Unauthorized</u></p><p><b>description</b> 
<u>This request requires HTTP authentication.</u>
</p><hr class="line"><h3>Apache Tomcat/8.5.9</h3></body></html>


```

**Comment by stephyritz** [comment]
Toujours NOK en valid et en prod. Souci d'accès à l'API de Metawal. Toujours des problèmes de proxy ? A identifier et à résoudre avec l'aide du DTIC.

**Comment by vbombaerts** [comment]
@vbombaerts vérifier si encore d'actualité et corriger si nécessaire

**Comment by vbombaerts** [comment]
J'ai pêché au hasard des gros groupes de fiches avec des requête de type
`https://metawal.wallonie.be/geonetwork/srv/fre/csw?REQUEST=GetRecords&SERVICE=CSW&VERSION=2.0.2&OUTPUTSCHEMA=http://standards.iso.org/iso/19115/-3/mdb/2.0&CONSTRAINTLANGUAGE=CQL_TEXT&RESULTTYPE=results&TYPENAMES=csw:Record&STARTPOSITION=301&MAXRECORDS=150&ELEMENTSETNAME=full&SORTBY=identifier:A`

et j'ai remarqué des différences au niveau de l'encodage du thésaurus des thèmes du GP
- xlink du title différent : `xlink:href="https://metawal.wallonie.be/thesaurus/theme-geoportail-wallon` vs `xlink:href="https://metawal.wallonie.be/thesaurus/Themes_geoportail_wallon_hierarchy"` Ex : [3947e7d2-e34c-447a-a186-e8808bc97d45](https://metawal.wallonie.be/geonetwork/srv/api/records/3947e7d2-e34c-447a-a186-e8808bc97d45/formatters/xml?approved=true) vs [394f880a-0cc2-47a5-b12d-4c07ec6ee3bf](https://metawal.wallonie.be/geonetwork/srv/api/records/394f880a-0cc2-47a5-b12d-4c07ec6ee3bf/formatters/xml?approved=true)
- parfois pas d'identifiant de thésaurus. Ex : [3a5f342e-b7e3-4e9f-b908-80a7280ecb9e](https://metawal.wallonie.be/geonetwork/srv/api/records/3a5f342e-b7e3-4e9f-b908-80a7280ecb9e/formatters/xml?approved=true)

- [x] Définir le bon encodage

```
               <mri:thesaurusName>
                  <cit:CI_Citation>
                     <cit:title>
                        <gcx:Anchor xlink:href="https://metawal.wallonie.be/thesaurus/theme-geoportail-wallon">Thèmes du géoportail wallon</gcx:Anchor>
                     </cit:title>
                     <cit:date>
                        <cit:CI_Date>
                           <cit:date>
                              <gco:Date>2014-06-26</gco:Date>
                           </cit:date>
                           <cit:dateType>
                              <cit:CI_DateTypeCode codeList="http://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#CI_DateTypeCode"
                                                   codeListValue="publication"/>
                           </cit:dateType>
                        </cit:CI_Date>
                     </cit:date>
                     <cit:identifier>
                        <mcc:MD_Identifier>
                           <mcc:code>
                              <gcx:Anchor xlink:href="https://metawal.wallonie.be/geonetwork/srv/api/registries/vocabularies/external.theme.Themes_geoportail_wallon_hierarchy">geonetwork.thesaurus.external.theme.Themes_geoportail_wallon_hierarchy</gcx:Anchor>
                           </mcc:code>
                        </mcc:MD_Identifier>
                     </cit:identifier>
                  </cit:CI_Citation>
               </mri:thesaurusName>
```


- [ ] Identifier les fiches à modifier
- [ ] Corriger avec un batch edit.

**Comment by davinciagf** [comment]
Pour introduire les ancres au niveau du thesaurus hiérarchique des thèmes du géoportail, une commande de type a été utilisée (cas pour une fiche bien précise ici) :

```
curl -X POST "$CATALOG/srv/api/processes/move-keyword-to-anchor?uuids=78e0c182-dbf4-4033-9bb0-e0acfd93be7b&thesaurusFileName=Themes_geoportail_wallon_hierarchy" -H "accept: application
/json" -H "X-XSRF-TOKEN: $TOKEN" -c /tmp/cookie -b /tmp/cookie --user $CATALOGUSER:$CATALOGPASS
```

**Comment by davinciagf** [comment]
Après discussion avec François un batch editing semble le plus évident.

![image](https://user-images.githubusercontent.com/576292/175308799-10b12718-d233-4a3d-8f6b-8a778bd726c0.png)

Testé sur un clone de :  https://metawal4.test.wallonie.be/geonetwork/srv/eng/catalog.search#/metadata/182ce727-a49a-44e2-ae83-29fb79926aa0
avec une erreur :
![image](https://user-images.githubusercontent.com/576292/175310353-f65faec2-5658-4dda-acc2-e4ed62f38091.png)


Résultat après (clone de https://metawal4.test.wallonie.be/geonetwork/srv/eng/catalog.search#/metadata/182ce727-a49a-44e2-ae83-29fb79926aa0 puis batch) : https://metawal4.test.wallonie.be/geonetwork/srv/api/records/9ced0bfc-b02c-46ce-89c3-3738f4531639/formatters/xml?approved=true

![image](https://user-images.githubusercontent.com/576292/175310176-6f6d1e40-8901-45c5-97a6-d6a6ef2ef648.png)


Paramètres :
- xpath : `.//mri:thesaurusName[*/cit:title/gcx:Anchor/text() = 'Thèmes du géoportail wallon']`
- xml : `<cit:CI_Citation  xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0" xmlns:mcc="http://standards.iso.org/iso/19115/-3/mcc/1.0" xmlns:mri="http://standards.iso.org/iso/19115/-3/mri/1.0" xmlns:cit="http://standards.iso.org/iso/19115/-3/cit/2.0" xmlns:gcx="http://standards.iso.org/iso/19115/-3/gcx/1.0"><cit:title><gcx:Anchor xlink:href="https://metawal.wallonie.be/thesaurus/theme-geoportail-wallon">Thèmes du géoportail wallon</gcx:Anchor></cit:title><cit:date><cit:CI_Date><cit:date><gco:Date>2014-06-26</gco:Date></cit:date><cit:dateType><cit:CI_DateTypeCode codeList="http://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#CI_DateTypeCode" codeListValue="publication"/></cit:dateType></cit:CI_Date></cit:date><cit:identifier><mcc:MD_Identifier><mcc:code><gcx:Anchor xlink:href="https://metawal.wallonie.be/geonetwork/srv/api/registries/vocabularies/external.theme.Themes_geoportail_wallon_hierarchy">geonetwork.thesaurus.external.theme.Themes_geoportail_wallon_hierarchy</gcx:Anchor></mcc:code></mcc:MD_Identifier></cit:identifier></cit:CI_Citation>`

**Comment by vbombaerts** [comment]
Identification des fiches non-conformes par 

q(-mw-gp-keywords.th_Themes_geoportail_wallon_hierarchy.link:"https://metawal.wallonie.be/geonetwork/srv/api/registries/vocabularies/external.theme.Themes_geoportail_wallon_hierarchy")

puis application de la routine d'édition en batch

EDIT : batch editing très pénible en valid - lancé sur 12 fiches et j'ai un timeout.

**Comment by vbombaerts** [comment]
Permet de corriger les erreurs au niveau de l'identifiant du thésaurus mais pas le xlink du title et l'absence d'identifiant pour le thésaurus.
Il faudrait encore un peu creuser l'affaire...

**Comment by vbombaerts** [comment]
Correction faite en prod. Ca concernait essentiellement des fiches de service.
