### ISSUE TITLE
Authentification / Page dédiée non fonctionnelle

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#554]
Impossible de s'authentifier depuis la page http://metawal.wallonie.be/geonetwork/srv/fre/catalog.signin?node=srv&failure=true
Une fois les login et mdp saisis et validés, l'application renvoie à la page d'accueil sans pour autant que l'utilisateur soit authentifié.

**Comment by fxprunayre** [comment]
Bizarre. Ca fonctionne avec http://metawal.wallonie.be/geonetwork/srv/fre/catalog.signin

La séquence est un peu différente

![image](https://user-images.githubusercontent.com/1701393/95313880-ee39a480-0890-11eb-96d5-d1d02c99f8cc.png)

et dans le cas qui ne marche pas

![image](https://user-images.githubusercontent.com/1701393/95313892-f1349500-0890-11eb-9fe2-ff28af81e877.png)

**Comment by stephyritz** [comment]
Je n'ai pas l'impression que cela fonctionne avec http://metawal.wallonie.be/geonetwork/srv/fre/catalog.signin de mon côté.

**Comment by fxprunayre** [comment]
Fixed in https://github.com/geonetwork/core-geonetwork/pull/5076
