### ISSUE TITLE
Problème d'import de MEF

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#555]
Cf. https://github.com/geonetwork/core-geonetwork/pull/5079

A déployer

**Comment by stephyritz** [comment]
Ok, c'est fonctionnel. Seuls "petits défauts", l'image associée au "fourni par" n'est pas celle du SPW et il semblerait que l'historique ait 2h de retard ("fichée créé il y a 2h pour un import qui vient d'être fait). Exemple : http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/7416887b-3640-40a1-9c8f-86ac2746f5a0

**Comment by fxprunayre** [comment]
> image associée au "fourni par" n'est pas celle du SPW

Donc le pb là, c'est plus les id de la source et les logos correspondants qui ne sont pas là.

http://metawal4.test.wallonie.be/geonetwork/images/logos/metawal4.test.wallonie.be.png


> l'historique ait 2h de retard

2 options: mettre la pendule du serveur au bon endroit sinon attendre https://github.com/geonetwork/core-geonetwork/pull/5061 (on y travaille pour gérer les timezones dans les fiches)


Sinon le pb initial est bien corrigé.

**Comment by stephyritz** [comment]
Merci. Oui le problème initial est corrigé, c'est pour ça que j'ai quand même mis le joli label vert ; )

Ok, pour l'image, j'imagine qu'en prod le logo est le bon. @davinciagf si tu as la main pour changer ça en test, est-ce que tu peux aussi le faire stp ? Sinon, c'est pas grave, c'est vraiment mineur.

Pour le fuseau horaire, rien de critique, on mettra ça au programme de la prochaine MeP.

**Comment by davinciagf** [comment]
Logo modifié en test.
voir http://metawal4.test.wallonie.be/geonetwork/images/logos/metawal4.test.wallonie.be.png

**Comment by stephyritz** [comment]
NOK en valid. Message d'erreur : 
![image](https://user-images.githubusercontent.com/34446202/97442510-38f78b00-192a-11eb-9c96-4fb091b37332.png)

**Comment by stephyritz** [comment]
je supprime l'index et relance une réindexation en valid

**Comment by fxprunayre** [comment]
![image](https://user-images.githubusercontent.com/1701393/97449295-ce4a4d80-1931-11eb-9ad7-c1cc09f5478a.png)


J'ai l'impression que l'erreur est plus lié à https://github.com/geonetwork/core-geonetwork/blob/4.0.x/web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v4000/migrate-default.sql#L22-L48 qui n'aurait pas été joué en valid ?

**Comment by stephyritz** [comment]
non pardon, je pense que c'est moi. La fiche existait déjà en valid et j'ai eu cette erreur quand je n'ai pas indiqué "écraser"
