### ISSUE TITLE
Recherche / Exclusion de certaines expressions dans la recherche texte 

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#557]
Il semblerait que certaines expressions comme "aux"  ou "de" ne soient pas exclues des mots rechercher à travers la recherche libre. Ceci a pour conséquence l'apparition de trop nombreux résultats. Voici un exemple où on fait une recherche en étant authentifié en tant qu'admin : 
1. Recherche _Secteurs attribués aux piégeurs de rats musqués_ (http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/search?isTemplate=n&resourceTemporalDateRange=%7B%22range%22:%7B%22resourceTemporalDateRange%22:%7B%22gte%22:null,%22lte%22:null,%22relation%22:%22intersects%22%7D%7D%7D&sortBy=dateStamp&sortOrder=desc&from=1&to=30&any=Secteurs%20attribu%C3%A9s%20aux%20pi%C3%A9geurs%20de%20rats%20musqu%C3%A9s)
--> 1076 résultats
2. Recherche _Secteurs attribués piégeurs rats musqués_ (http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/search?isTemplate=n&resourceTemporalDateRange=%7B%22range%22:%7B%22resourceTemporalDateRange%22:%7B%22gte%22:null,%22lte%22:null,%22relation%22:%22intersects%22%7D%7D%7D&sortBy=dateStamp&sortOrder=desc&from=1&to=30&any=Secteurs%20attribu%C3%A9s%20pi%C3%A9geurs%20rats%20musqu%C3%A9s)
--> 91 résultats
3. Recherche _piégeurs rats musqués_ (http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/search?isTemplate=n&resourceTemporalDateRange=%7B%22range%22:%7B%22resourceTemporalDateRange%22:%7B%22gte%22:null,%22lte%22:null,%22relation%22:%22intersects%22%7D%7D%7D&sortBy=dateStamp&sortOrder=desc&from=1&to=30&any=pi%C3%A9geurs%20rats%20musqu%C3%A9s)
--> 3 résultats
4. Recherche _piégeurs musqués_ (http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/search?isTemplate=n&resourceTemporalDateRange=%7B%22range%22:%7B%22resourceTemporalDateRange%22:%7B%22gte%22:null,%22lte%22:null,%22relation%22:%22intersects%22%7D%7D%7D&sortBy=dateStamp&sortOrder=desc&from=1&to=30&any=pi%C3%A9geurs%20musqu%C3%A9s)
--> 2 résultats

C'est un exmeple intéressant pour comprendre le comportement du moteur de recherche et il soulève le défaut qui consiste à ne pas exclure des "mots courants".

**Comment by fxprunayre** [comment]
Typiquement le genre de problème qu'on peut améliorer "facilement" avec Elasticsearch.

On configure la chaine d'analyse pour traiter les stop words (désolé de ne pas y avoir pensé avant) cf. https://github.com/SPW-DIG/metawal-core-geonetwork/commit/ca40f48eeeb08d40bfc9f97435f8214a6deb4252 (correction d'un pb sur les synonymes aussi au passage).

On peut valider la chaîne d'analyse avec:
```json
GET gn-records/_analyze
{
  "analyzer": "french_light", 
  "text": ["Secteurs attribués aux piégeurs de rats musqués"]
}


{
  "tokens" : [
    {
      "token" : "secteurs",
      "start_offset" : 0,
      "end_offset" : 8,
      "type" : "<ALPHANUM>",
      "position" : 0
    },
    {
      "token" : "attribues",
      "start_offset" : 9,
      "end_offset" : 18,
      "type" : "<ALPHANUM>",
      "position" : 1
    },
    {
      "token" : "piegeurs",
      "start_offset" : 23,
      "end_offset" : 31,
      "type" : "<ALPHANUM>",
      "position" : 3
    },
    {
      "token" : "rats",
      "start_offset" : 35,
      "end_offset" : 39,
      "type" : "<ALPHANUM>",
      "position" : 5
    },
    {
      "token" : "musques",
      "start_offset" : 40,
      "end_offset" : 47,
      "type" : "<ALPHANUM>",
      "position" : 6
    }
  ]
}

```

et résultat:

![image](https://user-images.githubusercontent.com/1701393/96152726-25512b00-0f0d-11eb-8338-f236aa8d306e.png)

A déployer.

**Comment by fxprunayre** [comment]
A tester. http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/search?isTemplate=n&resourceTemporalDateRange=%7B%22range%22:%7B%22resourceTemporalDateRange%22:%7B%22gte%22:null,%22lte%22:null,%22relation%22:%22intersects%22%7D%7D%7D&sortBy=relevance&from=1&to=30&any=Secteurs%20attribu%C3%A9s%20aux%20pi%C3%A9geurs%20de%20rats%20musqu%C3%A9s Même sans exactMatch les résultats sont plus limités.

**Comment by stephyritz** [comment]
Bizarre.. J'ai encore un nombre de résultats élevés (843 sans être atthentifié) contrairement au comportement en test pour cette même recherche : 
http://metawal4.valid.wallonie.be/geonetwork/srv/fre/catalog.search#/search?isTemplate=n&resourceTemporalDateRange=%7B%22range%22:%7B%22resourceTemporalDateRange%22:%7B%22gte%22:null,%22lte%22:null,%22relation%22:%22intersects%22%7D%7D%7D&sortBy=relevance&from=1&to=30&any=Secteurs%20attribu%C3%A9s%20aux%20pi%C3%A9geurs%20de%20rats%20musqu%C3%A9s

**Comment by fxprunayre** [comment]
@davinciagf vérifier le fichier records.json utilisé pour la création de l'index - y'avait des pb de config de l'index en test si je me rappelle bien.

**Comment by davinciagf** [comment]
Le soucis doit provenir de là car malheureusement le fichier de mise à jour pointe vers la config que l'on a externalisé et je n'ai pas fourni une mise à jour de ce fichier. Je le fourni à Didier pour mise à jour

**Comment by davinciagf** [comment]
Si problème de prise en charge du records.json apres delete et rebuild index. Vérifier usersettings - à supprimer si besoin
