### ISSUE TITLE
Ressources associées / Relations automatiques entre 2 fiches

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#558]
En édition, le comportement souhaité pour établir une relation entre deux fiches ayant un lien thématique est similaire à celui que l'on retrouve entre une série et un dataset la composant.
Par exemple :
1. Encoder la relation vers la fiche B à partir de la fiche A
2. La relation vers la fiche A est automatiquement également présente au sein de la fiche B (à la fois dans le xml et depuis l'interface de GN).
Fiche à utiliser (pour l'instant la relation n'a été encodé que à partir de l'une des fiches pour illustrer ce qui pourrait être amélioré)  
http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/fafb9fc7-4e32-4a40-8163-c64966cb573c et http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/a0ad23a1-1845-4bd5-8c2f-0f62d3f1ec75

**Comment by fxprunayre** [comment]
Fixed by https://github.com/geonetwork/core-geonetwork/pull/5082. A déployer.

**Comment by fxprunayre** [comment]
A vérifier le fonctionnement de https://github.com/SPW-DIG/iso19115-3.2018/commit/3585101d77c9678ec091dd459de344e30f137d6e - https://github.com/SPW-DIG/metawal-core-geonetwork/issues/525

    
Série : http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/28651053-16ae-4ea4-98bd-1c9e908c14bf
  
Fille : http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/a7e400b6-301f-456c-8eec-8fee01bfaba7

**Comment by fxprunayre** [comment]
Exemple de la série 28651053-16ae-4ea4-98bd-1c9e908c14bf Réseaux routiers régionaux thématiques - Série

http://metawal4.test.wallonie.be/geonetwork/srv/fre/csw?request=GetRecordById&service=CSW&outputSchema=mw&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=28651053-16ae-4ea4-98bd-1c9e908c14bf

6 fiches associées ajoutées cf.
```xml
<!-- Added from http://metawal4.test.wallonie.be/geonetwork/srv/api/records/28651053-16ae-4ea4-98bd-1c9e908c14bf/related?type=associated&type=brothersAndSisters -->
```

Dont a7e400b6-301f-456c-8eec-8fee01bfaba7. Donc c'est ok @stephyritz ?

**Comment by stephyritz** [comment]
Ok, cela a l'air bon! Je vérifierai encore si cela se traduit correctement sur le GP

**Comment by stephyritz** [comment]
NOK en valid. Exemple : http://metawal4.valid.wallonie.be/geonetwork/srv/fre/csw?request=GetRecordById&service=CSW&outputSchema=mw&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=28651053-16ae-4ea4-98bd-1c9e908c14bf
On dirait que le xsl spécifique à l'outputschema MW n'entraine pas l'ajout des fiches associées dans les balises de type<gmd:aggregationInfo>

**Comment by fxprunayre** [comment]
@davinciagf vérifier le répertoire de schéma pour qua ça utilise bien ceux de la webapp et pas une copie dans le datadir de vieux trucs.

**Comment by davinciagf** [comment]
Les schémas pointent bien vers la webapp. Je vérifie le build

**Comment by stephyritz** [comment]
Problème proxy en valid. Utilisation d'un proxy qui empêche l'accès aux ressources associées au xsl permettant l'ajout des ressources associées dans l'outputschema mw.

**Comment by fxprunayre** [comment]
A tester en utilisant la directive `http.nonProxyHosts` https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html, `-Dhttp.nonProxyHosts=”localhost|metawal4.valid.wallonie.be`

**Comment by stephyritz** [comment]
toujours NOK en valid.. @davinciagf discussion à avoir avec Didier sur les proxy en valid.

**Comment by stephyritz** [comment]
Didier a changé la config du proxy en valid. C'est OK maintenant.
