### ISSUE TITLE
INSPIRE validation / Selection / Ne démarre pas

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#559]
De temps en temps on a

```
[8:37 AM] fx.prunayre (Guest)
    {​"message":"BeanCreationException","code":"runtime_exception","description":"Error creating bean with name 'processValidate': Invocation of init method failed; nested exception is org.springframework.jmx.export.UnableToRegisterMBeanException: Unable to register MBean [org.fao.geonet.api.processing.EmptySlotBatch@7aab6e14] with object name [geonetwork:name=' + name + ',idx=empty-slot-0]; nested exception is javax.management.InstanceAlreadyExistsException: geonetwork:name=' + name + ',idx=empty-slot-0"}​
```

sur

```sh
curl 'http://metawal.wallonie.be/geonetwork/srv/api/records/validate/inspire?bucket=e101' \
  -X 'PUT' \
  -H 'Accept: application/json, text/plain, */*' 
```

**Comment by stephyritz** [comment]
Validation INSPIRE depuis Contribuer avec une sélection : OK en environnement de test (mais très lent par rapport 29/06/2020).
NOK en valid malgré un message qui laisse à penser le contraire :
 
![image](https://user-images.githubusercontent.com/34446202/97677387-77a85500-1a92-11eb-86cf-2f5816d18e9e.png)

**Comment by stephyritz** [comment]
Par ailleurs, en environnement de validation, la validation ne fonctionne pas non plus depuis l'interface d'édition d'une fiche et cela ne date pas de cette release..

**Comment by davinciagf** [comment]
@stephyritz, peux-tu retester dès redémarrage du tomcat (config proxy modifiée)

**Comment by stephyritz** [comment]
Testé à l'instant, toujours le même résultat.

**Comment by stephyritz** [comment]
@Toujours NOK en valid. Problème de proxy ?

**Comment by stephyritz** [comment]
OK en prod mais a priori le fait de faire valider depuis l'interface induit l'envoi de requêtes "massives" vers le validateur jusqu'à le faire planter... Problème à analyser et résoudre sans quoi la validation de "lots" de fiches est compromise.

**Comment by vbombaerts** [comment]
Validation OK lors du monitoring de décembre 2021
