### ISSUE TITLE
INSPIRE / TG2 / Modification de la date de publication du thesarus SpatialScope

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#561]
Actuellement, les fiches INSPIRE sont considérées comme non conformes au TG2 car la date de publication du thesaurus lié au SpatialScope à une valeur différentes de celles attendues par le validateur. En effet, il y aurait 
- 124 fiches avec la date "2019-07-02"
- 93 fiches avec la date "2019-08-01"
Or, pour être conforme, il faudrait que cette valeur soit "2019-05-22" (https://github.com/inspire-eu-validation/metadata/blob/2.0/monitoring/spatial-scope.md).
Par défaut, cette date = date d'importation du thesarus depuis le registre dans MW.
Actions à faire : 
- [x] Coder en dur la date de publication de ce thesarus côté GN
- [x] Jouer une requête DB pour modifier la valeur de toutes les fiches INSPIRE

Snippet concerné : 
```
<mri:descriptiveKeywords>
   <mri:MD_Keywords>
      <mri:keyword>
         <gcx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/SpatialScope/regional">Régional</gcx:Anchor>
      </mri:keyword>
      <mri:type>
         <mri:MD_KeywordTypeCode codeList="http://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#MD_KeywordTypeCode" codeListValue="theme"/>
      </mri:type>
      <mri:thesaurusName>
         <cit:CI_Citation>
            <cit:title>
               <gcx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/SpatialScope">Champ géographique</gcx:Anchor>
            </cit:title>
            <cit:date>
               <cit:CI_Date>
                  <cit:date>
                     <gco:Date>2019-07-02</gco:Date>
                  </cit:date>
                  <cit:dateType>
                     <cit:CI_DateTypeCode codeList="http://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#CI_DateTypeCode" codeListValue="publication"/>
                  </cit:dateType>
              </cit:CI_Date>
            </cit:date>
           <cit:identifier>
               <mcc:MD_Identifier>
                   <mcc:code>
                      <gcx:Anchor xlink:href="http://metawal.wallonie.be/geonetwork/srv/api/registries/vocabularies/external.theme.httpinspireeceuropaeumetadatacodelistSpatialScope-SpatialScope">geonetwork.thesaurus.external.theme.httpinspireeceuropaeumetadatacodelistSpatialScope-SpatialScope</gcx:Anchor>
                  </mcc:code>
               </mcc:MD_Identifier>
            </cit:identifier>
         </cit:CI_Citation>
      </mri:thesaurusName>
   </mri:MD_Keywords>
</mri:descriptiveKeywords>
```

**Comment by stephyritz** [comment]
SQL utilisé :

```
UPDATE metadata SET data = regexp_replace(data,'géographique</gcx:Anchor>[[:space:]]*</cit:title>[[:space:]]*<cit:date>[[:space:]]*<cit:CI_Date>[[:space:]]*<cit:date>[[:space:]]*<gco:Date>2019-07-02','géographique</gcx:Anchor></cit:title><cit:date><cit:CI_Date><cit:date><gco:Date>2019-05-22','g');
UPDATE metadata SET data = regexp_replace(data,'géographique</gcx:Anchor>[[:space:]]*</cit:title>[[:space:]]*<cit:date>[[:space:]]*<cit:CI_Date>[[:space:]]*<cit:date>[[:space:]]*<gco:Date>2019-08-01','géographique</gcx:Anchor></cit:title><cit:date><cit:CI_Date><cit:date><gco:Date>2019-05-22','g');
```

**Comment by stephyritz** [comment]
@davinciagf , tu n'as pas lancé la modif de la date sur toutes les fiches ??
En test, à ce jour, j'obtiens les résultats suivants en DB : 

`select count(*) from metawal4.metadata where data like '%<cit:title>%<gcx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/SpatialScope#">Champ géographique</gcx:Anchor>%</cit:title>%<cit:date>%<cit:CI_Date>%<cit:date>%<gco:Date>2019-08-01</gco:Date>%'`

--> 91 


`select count(*) from metawal4.metadata where data like '%<cit:title>%<gcx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/SpatialScope#">Champ géographique</gcx:Anchor>%</cit:title>%<cit:date>%<cit:CI_Date>%<cit:date>%<gco:Date>2019-07-02</gco:Date>%'`

-->124

**Comment by davinciagf** [comment]
Mis à jour.

**Comment by stephyritz** [comment]
OK en prod.
`select count(*) from metawal4.metadata where data like '%<cit:title>%<gcx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/SpatialScope">Champ géographique</gcx:Anchor>%</cit:title>%<cit:date>%<cit:CI_Date>%<cit:date>%<gco:Date>2019-05-22</gco:Date>%'`

--> 235

**Comment by stephyritz** [comment]
Plus aucun problème de conformité lié au thesaurus "Spatialscope" après testing auprès du validateur.
