### ISSUE TITLE
INSPIRE / Conformité des services

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#562]
Depuis le déploiement de la nouvelle version de GN, lorsque une fiche est associée à un service, elle est présente dans la fiche de service d'une manière non conforme au sein de la balise "srv:operatesOn".
Par exemple : 
```
<srv:operatesOn uuidref="27b29955-bfa5-4829-89cf-8095296b950a" xlink:href="http://metawal.wallonie.be/geonetwork/srv/fre/csw?service=CSW&request=GetRecordById&version=2.0.2&outputSchema=http://www.isotc211.org/2005/gmd&elementSetName=full&id=27b29955-bfa5-4829-89cf-8095296b950a"/>
<srv:operatesOn uuidref="37abcf36-e6a5-4ec7-b894-1c7e2dcad02b" xlink:title="INSPIRE - Concessions minières - Série" xlink:href="http://metawal.wallonie.be/geonetwork/srv/api/records/37abcf36-e6a5-4ec7-b894-1c7e2dcad02b"/>
```
La première donnée associée a été déclarée avant la dernière release, la seconde (37abcf36-e6a5-4ec7-b894-1c7e2dcad02b) est plus récente. Je pense qu'il faudrait configurer GN pour que le href référençant le dataset soit du type "getrecord" (a priori conforme) lorsqu'une donnée est associée à un service. Et encore, cela pose question car pour INSPIRE, l'url du getrecord n'est en théorie pas la même. Est-ce que cette modification de référence devrait être gérée par le post-process INSPIRE ?

To reproduce : 
1. Associer une fiche dataset à un service depuis l'interface d'édition de la fiche dataset
2. Interroger la fiche de service avec un getrecord de type http://metawal.wallonie.be/geonetwork/inspire/fre/csw?request=GetRecordById&service=CSW&outputSchema=http://www.isotc211.org/2005/gmd&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=3be632c8-80d3-460e-9122-bdefe2470d3d (même fiche utilisée pour l'exemple ci-dessus)

**Comment by fxprunayre** [comment]
Quelle erreur retourne le validateur ?

**Comment by stephyritz** [comment]
> The metadata record set has 1 record(s) with errors for this assertion.
> XML document 'file.xml', record '3be632c8-80d3-460e-9122-bdefe2470d3d': The metadata record has a linkage property, which references a resource with media type 'text/html;charset=UTF-8' at 'http://metawal.wallonie.be/geonetwork/srv/api/records/37abcf36-e6a5-4ec7-b894-1c7e2dcad02b' which is not one of the media types indicating an INSPIRE network service. Please review the resource to check that it meets the linkage requirements; specifically, if the resource is a webpage, check that it provides further instructions or a client application that directly accesses the service.

Exemple du rapport issu du test sur la fiche mentionnée précédemment : https://inspire.ec.europa.eu/validator//v2/TestRuns/EID28037e4f-e6a9-4924-8d79-7b23ad3de3ce.html

Le validateur essaie de faire un GET sur cette URL visiblement : 

> Check if the operatesOn element in the SV_ServiceIdentification element is a HTTP URI that when retrieved using HTTP GET returns the metadata document describing the dataset exposed by the service.

(https://github.com/inspire-eu-validation/metadata/blob/2.0/sds/coupled-resource.md)

**Comment by fxprunayre** [comment]
C nul il suffirait qu'il demande la ressource en disant qu'il veut du XML (Accept:application/xml) - là du coup, il a la landing page en mode par défaut ie. HTML. Je vais regarder le post process.

**Comment by fxprunayre** [comment]
Misère, ensuite avec http://metawal.wallonie.be/geonetwork/srv/api/records/37abcf36-e6a5-4ec7-b894-1c7e2dcad02b/formatters/xml il veut pas du 115-3, donc avec l'API il retourne
```
The metadata record set has 1 record(s) with errors for this assertion.
XML document 'test.xml', record 'f7041277-7ba9-450b-8efc-648f6fefa53a': The service metadata record has an 'operatesOn' property in its service identification. The value is referenced via an xlink:href that references: 'http://metawal.wallonie.be/geonetwork/srv/api/records/37abcf36-e6a5-4ec7-b894-1c7e2dcad02b/formatters/xml'. The referenced value must be a dataset or series metadata record, but it is not. Found: ''.
```

**Comment by fxprunayre** [comment]
Ok j'opte pour
```xml
<srv:operatesOn uuidref="37abcf36-e6a5-4ec7-b894-1c7e2dcad02b" 
xlink:title="INSPIRE - Concessions minières - Série" 
xlink:href="http://metawal.wallonie.be/geonetwork/srv/api/records/37abcf36-e6a5-4ec7-b894-1c7e2dcad02b/formatters/iso19139?output=xml"/>
```
en post processing INSPIRE


See https://github.com/SPW-DIG/metawal-core-geonetwork/commit/ed262f926e0de0b74ffc30851a203f37ca72f7a4

**Comment by fxprunayre** [comment]
A déployer @davinciagf
