### ISSUE TITLE
INSPIRE / Outil de validation / Post-processing

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#564]
La validation distante INSPIRE depuis l'interface "Contribution" ou depuis "l'édition" prend en compte la fiche en ISO19139 avant qu'elle ne soit transformée par le post-processing spécifique à INSPIRE. Donc, toutes les fiches pour lesquelles une action en post-processing permet la conformité (par ex. : suppression des contacts sans e-mail, suppression des références externes autre que http, description des ressources couplées à un service, etc...) apparaissent comme invalides vis à vis d'INSPIRE dans Geonetwork alors qu'elle seront, en théorie, conformes lors du monitoring INSPIRE.

Il serait donc idéal que l'input pour le test de validation d'une fiche depuis Geonetwork soit le xml tel qu'il est après les actions de post-processing.

**Comment by fxprunayre** [comment]
Un exemple de fiche à tester?

On utilise systématiquement le point CSW INSPIRE pour la validation? ie. pas nécessaire d'ajouter des boutons pour chaques types de validation : par upload, par CSW principal, par CSW inspire. Pourrait y'avoir un pb si on valide une fiche qui n'est pas dans le portail INSPIRE...

**Comment by stephyritz** [comment]
Exemples de fiches non conformes avant post-process : 
http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/b7725746-b5ef-46db-add4-d61a6cc3b8d3 (dataset)
http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/74fe32b4-09b2-4ade-9b3b-373c7877eeae (service)

Actuellement, seules les fiches du point CSW INSPIRE sont validées (sauf erreur de manipulation). Je n'utilise jamais les autres types de validation actuellement. Même si, à terme, cela pourrait être intéressant en faisant également d'autres tests (présence d'au moins un mot-clés du géoportail, de liens vers des services, d'un gestionnaire présent dans un registre, etc...).

On pourrait imaginer un message d'erreur disant "Cette fiche n'est pas conçue pour ce test de validation. Elle n'est peut-être pas publiée ou absente du portail sur lequel le test est basé".

**Comment by fxprunayre** [comment]
En testant, je n'ai pas l'impression qu'il y ait des appels multiples. Si les choses s'éternisent, il y aura
```
2020-11-30 19:04:42,300 ERROR [geonetwork.api] - 
Error validating metadata 801878ab-1550-4bf9-81a4-e17f76de3e85 
in INSPIRE validator: 
ETF validation task hasn't finish after 20 checks.
```

**Comment by fxprunayre** [comment]
GeoNetwork ref https://github.com/geonetwork/core-geonetwork/pull/5227

**Comment by stephyritz** [comment]
Merci. Donc soit c'est une "mauvaise interprétation" côté validateur soit cela vient du proxy, propre à la configuration en prod.

**Comment by fxprunayre** [comment]
Les 2 modes de validation (par upload du XML ou par GetRecordById du CSW INSPIRE) sont disponibles dans l'interface

![image](https://user-images.githubusercontent.com/1701393/103546312-11c9b680-4ea3-11eb-8f64-52e6647a22c3.png)


A déployer et tester.
