### ISSUE TITLE
INSPIRE / Modification des urls vers les registres INSPIRE et schémas

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#566]
**Actions à ne pas faire avant Avril 2021**

Conformément à la demande de l'Europe, modifier les urls concernés (registre INSPIRE + références à certains schémas) pour les indiquer en "https".

A faire en coordination avec Dominique (référent INSPIRE) et en prenant en compte les exigences liées au validateur INSPIRE.

Il faudra probablement pour cela : 
- [ ]  identifier les url concernées
- [ ]  faire une requête DB pour faire une modification de masse

**Comment by fxprunayre** [comment]
Les URIs des concepts dans les registres sont toujours en http

![image](https://user-images.githubusercontent.com/1701393/119982582-50315080-bfbf-11eb-86e6-b8ee05c30bb4.png)

https://inspire.ec.europa.eu/metadata-codelist/PriorityDataset/PriorityDataset.en.xml

Donc je pense qu'on peut rester en http pour le moment.

Après de leur côté, ils ont mis une redirection http://inspire.ec.europa.eu/metadata-codelist/PriorityDataset/AirQualityMonitoringNetworks-dir-2008-50 donc rien à faire côté metawal pour le moment.

**Comment by vbombaerts** [comment]
J'ai postposé pour qu'on garde un oeil dessus car ça restera peut-être à faire plus tard.

**Comment by vbombaerts** [comment]
Au 23/01/2022, le dernier thésaurus ajouté pour INSPIRE (IACS data) référence toujours des URI en http. Je ferme. J'imagine qu'on sera prévenu si modification des URI.
