### ISSUE TITLE
Date de création de fiche lors de la duplication

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#567]
Lors d'une duplication de fiche, la date de la création de la fiche ne se met pas à la date du duplicat.

**To Reproduce**
Dupliquer la fiche de l'application WalOnMap

**Expected behavior**
La date du jour de la duplication et non 2/4/2019
**Screenshots**
![image](https://user-images.githubusercontent.com/6093453/101776871-e6e18200-3af1-11eb-84ec-c56f3b39ca6e.png)

**Additional context**

**Comment by fxprunayre** [comment]
Tentative de solution https://github.com/geonetwork/core-geonetwork/pull/5275 mais ce n'est pas optimal. A suivre.

**Comment by mawibrin** [comment]
C'est mis dans la 4.02 mais je ne vois pas trop ce qui a changé. Pas un point important non plus

**Comment by vbombaerts** [comment]
J'ai eu le problème aussi. J'ai édité la date de création de la fiche dans le XML.
Mais quelle date de création est utilisée pour les statistiques dans ES et Kibana ? Celle encodée dans le XML ou celle de la BD ?

**Comment by davinciagf** [comment]
C'est la date du XML si je ne me trompe pas.

**Comment by fxprunayre** [comment]
> C'est la date du XML si je ne me trompe pas.

De la db en fait https://github.com/geonetwork/core-geonetwork/blob/main/core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataIndexer.java#L381

**Comment by davinciagf** [comment]
Update de la date au niveau du xml voir PR GN  (https://github.com/geonetwork/core-geonetwork/pull/5689)

**Comment by vbombaerts** [comment]
> Update de la date au niveau du xml voir PR GN (geonetwork#5689)
Ca fait quoi du coup ?

**Comment by fxprunayre** [comment]
> Ca fait quoi du coup ?

Si une fiche est nouvellement créée, on a un flag qui nous permet de faire des actions sur le XML. Ici, on remplace la date de creation du modèle ou de la fiche copiée par la date du moment de la copie. On pourrait imaginer faire d'autres changements eg. supprimer les aperçus ...

**Comment by fxprunayre** [comment]
J'y pense un peu tard, il faudrait aussi supprimer le metadataLinkage lors de la création d'une fiche pour mettre à jour le lien. @davinciagf tu peux regarder ?

**Comment by davinciagf** [comment]
Ok je regarde à cela

**Comment by davinciagf** [comment]
Le metadataLinkage se met à jour à la duplication.

**Comment by fxprunayre** [comment]
> Le metadataLinkage se met à jour à la duplication.

Devrait pas https://github.com/geonetwork/core-geonetwork/blob/main/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/update-fixed-info.xsl#L56 sauf si la fiche source ne contient pas de linkage ? sinon y'a une coquille ?

**Comment by fxprunayre** [comment]
> Devrait pas https://github.com/geonetwork/core-geonetwork/blob/main/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/update-fixed-info.xsl#L56 sauf si la fiche source ne contient pas de linkage ? sinon y'a une coquille ?

En fait c'est tout bon à cause de https://github.com/geonetwork/core-geonetwork/pull/4584. A tester donc.

**Comment by davinciagf** [comment]
Testé en local sur les cas suivants:
- si on supprime le metadatalinkage via le xml en edition d'une fiche disposant du metadataLinkage ==> il est bien réintroduit si on change de vue dans l'édition (vue xml vers vue simple) et idem si on sauve et ferme la fiche directement
- si on duplique une fiche, le metadataLinkage est à jour par rapport au nouveau uuid de la fiche dupliquée
