### ISSUE TITLE
Les catégories du Géoportail n'ont pas été adaptées pour les applications

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#568]
Les fiches applicatives utilisent aussi les mots clés du Géoportail, mais l'alignement sur le thesaurus ne semble pas pris en compte.
![image](https://user-images.githubusercontent.com/6093453/101777450-ccf46f00-3af2-11eb-8939-557bda28e3b0.png)

Vu en dupliquant la fiche WalOnMap.

**Comment by mawibrin** [comment]
fiche source http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/066108cf-effb-48c8-b221-24738047bd86
fiche adaptée http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/73e9cf6b-224f-4ae3-8321-65bf69030212

arrive aussi sur données

**Comment by stephyritz** [comment]
A priori cela est dû à la valeur "Tourisme et loisirs" qui est actuellement encore sous forme de characterstring. Un replace en DB par la valeur sous forme d'anchor devrait normalement solutionner le problème.

**Comment by davinciagf** [comment]
En test, selon la requete suivante : 

`select count(*) from metawal4.metadata where data like '%<gco:CharacterString>Tourisme et loisirs</gco:CharacterString>%'`

48 éléments sont répertoriés dans la DB

Test de requete SQL pour modifier ce keyword et intégrer son ancre via la requete suivante sur une fiche spécifique (duplication de la fiche source):

`UPDATE metawal4.metadata SET data = replace(data, '<gco:CharacterString>Tourisme et loisirs</gco:CharacterString>', '<gcx:Anchor xlink:href="http://metawal.wallonie.be/thesaurus/theme-geoportail-wallon#ThemesGeoportailWallon/40">Tourisme et loisir</gcx:Anchor>') WHERE data like '%<gco:CharacterString>Tourisme et loisirs</gco:CharacterString>%' and uuid like '6e181550-e32c-40b0-b82f-c9771932a1b0';`

voir résultat au niveau de la fiche: http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/6e181550-e32c-40b0-b82f-c9771932a1b0
![Screen Shot 2020-12-22 at 15 23 30](https://user-images.githubusercontent.com/576292/102898427-c6a6b100-4469-11eb-88ea-0d2f1736bb3a.png)


SQL pour modification globale:

`UPDATE metawal4.metadata SET data = replace(data, '<gco:CharacterString>Tourisme et loisirs</gco:CharacterString>', '<gcx:Anchor xlink:href="http://metawal.wallonie.be/thesaurus/theme-geoportail-wallon#ThemesGeoportailWallon/40">Tourisme et loisir</gcx:Anchor>') WHERE data like '%<gco:CharacterString>Tourisme et loisirs</gco:CharacterString>%';`

**Comment by mawibrin** [comment]
Cette catégorie n'a pas le même comportement que les autres, le lien n'est pas cliquable. 
![image](https://user-images.githubusercontent.com/6093453/103625643-8cdeab80-4f3b-11eb-9d43-1ab2b908a350.png) 
(mais en même temps, même en prod un clic sur le lien mis sur le nom donne une erreur 
![image](https://user-images.githubusercontent.com/6093453/103625859-d202dd80-4f3b-11eb-90ff-e88b01dddb0e.png)
)

**Comment by davinciagf** [comment]
A faire - Désactiver l'hyperlien au niveau des thèmes du géoportail (infrasig). A réactiver lors de la mise en oeuvre du registre.

**Comment by mawibrin** [comment]
ok pour la fiche voir résultat au niveau de la fiche: http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/6e181550-e32c-40b0-b82f-c9771932a1b0
@davinciagf tu fais tourner le sql de modification globale en test? et tu désactives les liens comme mentionné ci-dessus?

**Comment by davinciagf** [comment]
Suppression des liens pour les thèmes du géoportail voir - https://github.com/SPW-DIG/metawal-core-geonetwork/commit/79e8edc58c8d3e58ee48e19d53a6349ebf0a8c3b
Mise à jour et sql programmé mardi matin.

**Comment by mawibrin** [comment]
En prod les listes sont bien 'non cliquable'.
Est-ce que cela a été vérifié qu'il n'y a plus de fiches en prod qui n'utilisent pas l'anchor?

**Comment by fxprunayre** [comment]
@davinciagf tu peux vérifier ?

**Comment by davinciagf** [comment]
A tester dès synchronisation des BD test/prod (au 29 avril 201, il restait 32 MTD avec des mots clés type "thèmes géoportail" sans ancres).

**Comment by davinciagf** [comment]
@vbombaerts @mawibrin : News relatives à la synchro de la DB ?

**Comment by vbombaerts** [comment]
Toujours bloqué - https://github.com/SPW-DIG/metawal-core-geonetwork/issues/590#issuecomment-836666903

**Comment by vbombaerts** [comment]
Env. Valid :
Je pense que les requêtes n'ont pas été jouées.

Attention : les erreurs proviennent des modèles ! J'ai récemment créé une fiche de données depuis un modèle et les mots-clés "Thèmes du GP" sont sous forme de characterstring et non d'ancre (pas uniquement le thème Tourisme et Loisir).

**Comment by vbombaerts** [comment]
Ca m'a l'air bon en valid.

**Comment by vbombaerts** [comment]
Semble OK en prod. (coups de sonde)
