### ISSUE TITLE
Lien vers une application utilisant la ressource

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#569]
Résumé
Les fiches applicatives du catalogue ne sont pas/plus listées depuis la fonction 'lien vers une fiche utilisant la ressource'.

Depuis une fiche données/série on peut vouloir indiquer une/des applications utilisant la ressource. Une manière de faire est de créer un simple lien et d'y mettre l'url. Quand l'application a déjà une fiche dans Metawal, a un moment il était possible d'utiliser le 'Lien vers une application utilisant la ressource' et là on voyait les fiches applicatives et on choisissait. De mémoire le lien était alors bi-directionnel. Cela évitait aussi d'écrire l'appli différemment.

![image](https://user-images.githubusercontent.com/6093453/102472848-00854b00-4057-11eb-8ce7-7a2fd38b9aed.png)
![image](https://user-images.githubusercontent.com/6093453/102472920-185ccf00-4057-11eb-8a26-a2fc229e4088.png)
![image](https://user-images.githubusercontent.com/6093453/102474119-8bb31080-4058-11eb-8fff-a7206939bcb1.png)

Ce serait possible de réactiver cela? Ou une autre solution permettant de facilement faire les liens dans les deux sens entre fiches applicatives et fiches données/services?

**Comment by fxprunayre** [comment]
Fixed by https://github.com/geonetwork/core-geonetwork/pull/5278

**Comment by fxprunayre** [comment]
A déployer @davinciagf et tester

**Comment by mawibrin** [comment]
En valid la liste se construit bien mais les liens ne sont pas possibles 
![Uploading image.png…]()

**Comment by davinciagf** [comment]
Il semble que le problème soit présent en test également. Je regarde pq le lien ne s'active pas.

**Comment by davinciagf** [comment]
J'ai uploadé une nouvelle version de MW en test qui permet de sélectionné l'url pointant vers l'application.
![Screen Shot 2021-04-01 at 10 00 39](https://user-images.githubusercontent.com/576292/113262808-52ce3d00-92d1-11eb-986a-210271b3938b.png)
![Screen Shot 2021-04-01 at 10 00 47](https://user-images.githubusercontent.com/576292/113262856-5f529580-92d1-11eb-8c5a-d716adef5169.png)

**Comment by vbombaerts** [comment]
Depuis la fiche de la donnée, on peut indiquer automatiquement via le bouton "ajouter" l'adresse de l'application dans une entrée de type ressource en ligne de la section distribution. 
On récupère, côté fiche de donnée une entrée de ressource en ligne supplémentaire dont :
- le nom est le même que celui utilisé pour nommer l'application - OK
- **la description n'est pas récupérée** - **KO** --> récupérer la description du lien correspondant à la ressource en ligne choisie dans la liste
- le protocole indiqué est de type WWW:LINK - OK
- la fonction indiquée est de type browsing - OK (ce qui est attendu pour une appli de visualisation des données) 

Il n'y a pas de lien qui se crée entre les deux fiches. Pour cela, il faut passer par la fiche de l'application.

Depuis la fiche de l'application, on peut lier une fiche de donnée. 
- Le lien entre fiches apparait dans la fiche de l'application et dans la fiche de données quand on est dans Metawal -OK
- côté appli : le est de type "operatesOn" - OK 
-  côté fiche de données : le lien n'apparaît pas dans le XML, même après export - OK 

Moyennant récupération de la description, pour moi c'est bon. 
@mawibrin tu voulais qu'en plus d'ajouter une ressource en ligne la liaison entre les deux fiches soit automatique ?

**Comment by fxprunayre** [comment]
> * **la description n'est pas récupérée** - **KO** --> récupérer la description du lien correspondant à la ressource en ligne choisie dans la liste

Cf. https://github.com/geonetwork/core-geonetwork/pull/5717

A déployer @davinciagf

**Comment by davinciagf** [comment]
Semble ok en test - a valider si la manip est la bonne 
![Screen Shot 2021-06-03 at 14 53 39](https://user-images.githubusercontent.com/576292/120648165-9d0f9e00-c47b-11eb-8dc9-7395796ba560.png)

**Comment by vbombaerts** [comment]
Je ne l'avais pas imaginé comme ça mais c'est bien.

Ce que j'avais imaginé :
Dans le champ URL  : l'URL de l'application - OK
Dans le champ Resource name : Le nom de l'application "Atlas des voiries vicinales de 1841"
Description : L'accroche de l'application

Ce que vous avez imaginé est bien aussi, car ça permet de comprendre la nature du lien. On laisse comme ça pour le moment.
