### ISSUE TITLE
Config nouveau noeud

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#570]
J'aimerais créer un noeud qui ne reprend que les données ayant le mot-clé infrasig DGO3_BREF. Je n'ai pas réussi à le faire avec l'exemple mentionné ou la manière de faire pour inspire. (Metawal test étant down, je ne peux réssayer car je me demande si je n'aurai pas bêtement essayé avec le tag DGO3_BREFNO...).
Je voudrais aussi avoir une configuration spécifique. Dans l'idée d'activer la carto et de découvrir les autres possibilités.

**Comment by davinciagf** [comment]
Mini tutorial
# Définition des paramètres de la vue utilisateur
Cette étape permet de définir un ensemble de paramètres qui font définir les outils et caractéristiques de l'interface utilisateur (exemple: affichage de la carte, du footer, définition des paramètres de recherche,....)

## Création d'une nouvelle interface
Aller dans la partie Admin/Settings/User Interface
 
![Screen Shot 2020-12-18 at 10 03 34](https://user-images.githubusercontent.com/576292/102595784-7998a700-4118-11eb-8360-563799ab9590.png)

Ajouter une nouvelle interface (donner un nom et cliquer sur le bouton ajouter)

![Screen Shot 2020-12-18 at 10 06 57](https://user-images.githubusercontent.com/576292/102596045-e2801f00-4118-11eb-9436-634cbf5b9f42.png)

Modifier les paramètres de la nouvelle interface (lorsque vous faites des modifications sur l'une de vos interface vérifié bien que vous réalisé les modifs dans la bonne interface)
![Screen Shot 2020-12-18 at 10 10 17](https://user-images.githubusercontent.com/576292/102596335-528ea500-4119-11eb-8968-48802061b950.png)


Modifier les paramètres souhaités... Vous pouvez vous aider du filtre pour rechercher un élément 

![Screen Shot 2020-12-18 at 10 12 05](https://user-images.githubusercontent.com/576292/102596537-9386b980-4119-11eb-9354-d25ab1877d7b.png)

Sauver votre interface. Elle est maintenant disponible pour utilisation sur l'un de vos noeuds.
![Screen Shot 2020-12-18 at 10 13 53](https://user-images.githubusercontent.com/576292/102596669-c8930c00-4119-11eb-8fd1-a6fea76d8103.png)

# Création du noeud avec son interface spécifique
Aller dans la partie Admin/Settings/Source

![Screen Shot 2020-12-18 at 10 15 04](https://user-images.githubusercontent.com/576292/102596774-f37d6000-4119-11eb-9eb2-7b81b27c2934.png)

Ajouter un noeud et définir ces paramètres (filtre des MTD, interface utilisateur...)
![Screen Shot 2020-12-18 at 10 31 10](https://user-images.githubusercontent.com/576292/102598386-3a6c5500-411c-11eb-8d64-a0bf313a6cd6.png)



![Screen Shot 2020-12-18 at 10 19 31](https://user-images.githubusercontent.com/576292/102597208-97ffa200-411a-11eb-9f3c-604dac590228.png)

Sauver votre noeud et naviguer vers ce dernier en modifiant le nom du noeud au niveau de l'url classique (changer le nom "srv" par le nom de votre noeud) http://metawal4.test.wallonie.be/geonetwork/testagf2/eng/catalog.search#/home

**Comment by davinciagf** [comment]
Pour le filtre sur le mot-clé infrasig "DGO3_BREF" utilisé le filtre :
+thesaurus_geonetworkthesauruslocalthemeinfraSIG:\"DGO3_BDREF\"

Voir noeud testagf
![Screen Shot 2020-12-18 at 10 42 39](https://user-images.githubusercontent.com/576292/102599462-caf76500-411d-11eb-9304-73b0c05ace5d.png)

**Comment by fxprunayre** [comment]
> +thesaurus_geonetworkthesauruslocalthemeinfraSIG:"DGO3_BDREF"

et dans la version à venir ce sera +th_infraSIG.default:"DGO3_BDREF"

**Comment by fxprunayre** [comment]
On peut fermer @mawibrin ?

Pour 
> Dans l'idée d'activer la carto et de découvrir les autres possibilités.

cf. https://github.com/SPW-DIG/metawal-core-geonetwork/issues/573
