### ISSUE TITLE
Recherche / Configuration des facettes

### ISSUE THREAD

**Issue by stephyritz** [SPW-DIG/metawal-core-geonetwork#571]
Il me semble que le comportement actuel, si on sélectionne plusieurs éléments d'une même facette c'est de faire une recherche sur base d'un "OU". Par ex. : je cherche des fiches qui ont les mots-clés de type 'INFRASIG' avec des valeurs "Reporting INSPIRE" ET "INSPIRE Priority Dataset" ET qui sont publiées.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/34446202/102586766-06d4ff00-410b-11eb-9f3e-3561b968362c.png)

 
En cochant les valeurs via les facettes, je pense que j'obtiens le résultat de  ("Reporting INSPIRE" OU "INSPIRE Priority Dataset") ET publiées.

Existe-t-il un moyen, depuis l'interface de recherche de choisir "Reporting INSPIRE" ET "INSPIRE Priority Dataset" ET publiées.
Si cela se paramètre facette par facette je pense que pour les mot-clés INFRASIG, nous aurons plus souvent le besoin de faire des ET que des OU. Donc on peut paramétrer cette facette dans ce sens. Si l'utilisateur à la main (par ex. depuis les filtre actif) de déterminer s'il veut un ET ou un OU, c'est encore mieux!

**Comment by fxprunayre** [comment]
> Il me semble que le comportement actuel, si on sélectionne plusieurs éléments d'une même facette c'est de faire une recherche sur base d'un "OU"

Je confirme.


> Existe-t-il un moyen, depuis l'interface de recherche de choisir "Reporting INSPIRE" ET "INSPIRE Priority Dataset" ET publiées.

Oui
http://metawal.wallonie.be/geonetwork/srv/fre/catalog.edit#/board?sortBy=dateStamp&sortOrder=desc&isTemplate=%5B%22y%22,%22n%22%5D&resultType=manager&from=1&to=20&query_string=%7B%22isPublishedToAll%22:%7B%22true%22:true%7D%7D&any=q(%2Btag:%22Reporting%20INSPIRE%22%20%2Btag:%22INSPIRE%20Priority%20Dataset%22)

On peut mettre des expressions dans la zone de recherche avec eg. `q(+tag:"Reporting INSPIRE" +tag:"INSPIRE Priority Dataset")`


> Donc on peut paramétrer cette facette dans ce sens. 

Avant GN3, faisait un AND pour les valeurs d'une même facette. En v4 il faut un OU.
En terme d'interface ça alourdit un peu les choses. Un exemple https://forest.eea.europa.eu/datacatalogue.
Ca pourrait être une option de config de la facette aussi. Typiquement pour InfraSIG, ça fait sens d'avoir un AND.

Vous auriez des exemples de sites avec ce genre de choix?


Les actions seraient:

- [ ] Facet / Config / Define if AND or OR is used. Default is OR.
- [ ] Facet / Config / Add option to turn on operator selection
- [ ] Facet / Widget / Options to choose match all/match any

**Comment by vbombaerts** [comment]
Je vois l'intérêt mais je pense que tant que Metawal n'est pas une interface grand public on peut s'en sortir avec en tapant des expressions dans la zone de recherche doublées éventuellement de la sauvegarde de la query avec la fonction "recherche utilisateur".
La recherche via la contribution et la possibilité de chercher dans les résultats d'une recherche via la restriction des résultats aux fiches sélectionnée fait aussi le job je pense.
Si Metawal est un jour exposée au plus grand nombre, l'approche match all/match any sera pertinente.

**Comment by vbombaerts** [comment]
Work around : 
- choisir une valeur de la facette. 
- Sélectionner les résultats
- conserver uniquement la sélection
- choisir une autre valeur de la même facette

==> les fiches restantes sont celles répondant aux 2 critères.
