### ISSUE TITLE
Protocole des liens

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#572]
Les liens url sont de protocole WWW:LINK ou WWW:LINK-1.0-http--link suivant comment on les ajoute.
Est-ce que cela a une conséquence pour le rapportage INSPIRE, un process interne (dashboard ou autre), lien géoportail,...?

**To Reproduce**
Par le bloc ressources associées, choisir par ex Application utilisant la ressource et mettre une url.
On voit ensuite que le protocole associé est WWW:LINK , alors que celui de la liste déroulante des valeurs recommandées est WWW:LINK-1.0-http--link

**Expected behavior**
Je m'attendais à ce que le protocole soit le même.

**Screenshots**
![image](https://user-images.githubusercontent.com/6093453/102975593-9eb65c80-4500-11eb-8df6-88ff25b02984.png)

**Log file**
If applicable, add the server log file to help trace your problem.

**Comment by fxprunayre** [comment]
Si on utilise l'interface "Ressources associées" normalement on ne devrait avoir que des protocols `WWW:LINK` cf. https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.0.x/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/config/associated-panel/default.json

J'ai repéré 2 valeurs `WWW:LINK-1.0-http--link` donc en vue avancée on pouvait saisir cette valeur de protocole.

Correction faite.

@davinciagf https://github.com/SPW-DIG/metawal-core-geonetwork/commit/b2d0aa12b973a4433904dafcfa470daed5ee10ca#diff-df7c348890375717769fe732e16a688878cc834e285cc1df5c1101bb1eb974b2R11 SQL à appliquer en base lors du déploiement.

**Comment by mawibrin** [comment]
Au niveau du Géoportail, ils avaient reçu cette info pour quand il y a un lien de téléchargement direct indiqué dans la fiche (assez rare, parfois pour certaines donnée opendata).

*  Mode de diffusion "Téléchargement"
*  functionCode = download
*  protocol =  WWW:LINK-1-http--LINK

--> le protocole changera aussi dans ce cas et il faut les avertir?

**Comment by davinciagf** [comment]
Oui effectivement, comme on introduit une modif pour le protocole, cela pourrait avoir des répercussions au niveau Géoportail  -> à vérifier avec le géoportail de test si ce dernier moissonne bien metawal en test et, dès lors vérifier si les liens de téléchargement sont toujours là.  Voir la règle que le Géoportail utilise ?
Exemple : 
http://metawal4.test.wallonie.be/geonetwork/srv/api/records/80a837d8-2c0b-4f77-b5d5-824e9780a4ae/formatters/xml?approved=true

https://geoportail.test.wallonie.be/catalogue/80a837d8-2c0b-4f77-b5d5-824e9780a4ae.html

Sinon, rajouter une éventuelle règle au niveau du profil CSW pour le Geoportail

**Comment by mawibrin** [comment]
Autre exemple avec 2998bccd-dae4-49fb-b6a5-867e6c37680f qui a un lien de téléchargement dans les ressources associées. Je pense que c'est pour ces liens-là que le trio mode de diffusion / functioncode et protocol étaient testés côté metawal.
Là je n'ai accès ni à MW ni au Géoportail en test. Mais je pense bien que cette fiche ICAR doit y être.
Dans les bonnes pratiques de Geoff, il indiquait qu'il fallait utiliser WWW:LINK-1.0-http—link pour quand on référence un pdf de légende, pour le lien site web du propriétaire, consulter dans une appli dédiée,... Il faudra vérifier l'ensemble des liens pour le Géoportail / voir ce qu'ils utilisent et/ou forcer un csw avec le protocole écrit 'à l'ancienne'

**Comment by mawibrin** [comment]
J'attend encore la confirmation que GP test pointe bien actuellement vers MW test.
