### ISSUE TITLE
Le catalogue ouvre WalOnMap et non le viewer geonetwork

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#573]
Les données ne s'ajoutent pas au viewer de GN (mais à WOM alors que WalOnMap n'est pas le viewer renseigné dans la config...).

**To Reproduce**
http://metawal4.test.wallonie.be/geonetwork/testEnvi/fre/catalog.search#/search
Aller sur 'visualiser' 'ajouter une couche' 'chercher', tapez par exemple 'eau'.
Aucun résultat ne veut bien se dessiner sur la carte.

En ouvrant une des fiches (ex http://metawal4.test.wallonie.be/geonetwork/testEnvi/fre/catalog.search#/metadata/0ed95325-a1b0-48ca-8437-b63178c3eebe ) les liens 'visualiser' sur le REST et WMS ouvrent WalOnMap dans un nouvel onglet.

Comme si un autre paramètre pilotait ces liens vers les cartes... Il y aurait eu historiquement quelque chose qui interfère?

**Expected behavior**
Ajout au viewer Geonetwork.

**Screenshots**
![image](https://user-images.githubusercontent.com/6093453/103091039-267c9380-45f3-11eb-805d-837e997a3b03.png)
![image](https://user-images.githubusercontent.com/6093453/103091066-398f6380-45f3-11eb-8012-c083251b0cf0.png)
![image](https://user-images.githubusercontent.com/6093453/103091188-aa368000-45f3-11eb-9f22-96319464ef31.png) (testEnviCarto)

**Comment by fxprunayre** [comment]
Oui en effet, on avait branché par défaut et de manière systémtique walonmap comme visualiseur. Je vais ajuster pour utiliser la config.

**Comment by fxprunayre** [comment]
Après pour utiliser le viewer de GeoNetwork, on a un autre problème sur l'identification de la couche à afficher.

Dans les fiches metawal on a (eg. http://metawal4.test.wallonie.be/geonetwork/testEnvi/api/records/0ed95325-a1b0-48ca-8437-b63178c3eebe/formatters/xml)

```xml
<mrd:onLine>
<cit:CI_OnlineResource>
<cit:linkage>
<gco:CharacterString>https://geoservices.wallonie.be/arcgis/services/INDUSTRIES_SERVICES/CPAS/MapServer/WMSServer?request=GetCapabilities&service=WMS</gco:CharacterString>
</cit:linkage>
<cit:protocol>
<gco:CharacterString>OGC:WMS</gco:CharacterString>
</cit:protocol>
<cit:name>
<gco:CharacterString>Service de visualisation WMS<
```

cependant dans GeoNetwork on attend que le `name` corresponde au nom de la couche dans le service ici `Service de visualisation WMS` donc on obtient une erreur :

![image](https://user-images.githubusercontent.com/1701393/103541729-22c2f980-4e9c-11eb-99e3-cfaa758d9c8f.png)

Dans l'ajout de couche dans WalOnMap ce qu'on fait pour le moment c'est d'afficher la couche `0` en espérant qu'elle sera là. On peut faire quelquechose de similaire pour le moment. @mawibrin une autre suggestion ?

**Comment by fxprunayre** [comment]
A déployer et tester.

**Comment by mawibrin** [comment]
Actuellement le Géoportail ajoute tout le service (le REST par défaut) et pas la première couche. Est-ce qu'un ajout du même genre est envisageable?
A priori il y aura toujours une couche 0. Mais dans les bonnes pratiques actuelles les liens vers les services sont mis au niveau de la série et non des couches (quand elles sont décrites). Prendre juste la première couche pourrait être limite (les services INSPIRE sont multicouches), si c'est ca le résultat.
Au besoin nos bonnes pratiques peuvent évoluer (c'est principalement d'une contrainte WalOnMap que vient le fait de ne pas dupliquer les services dans les fiches 'filles' si il y a une série, et d'y mettre le service REST en entier // il y a aussi le côté maintenance de l'ordre des couches qui complexifie si on pointe trop précis).
Le viewer GN serait utilisé pour un noeud INSPIRE.
A discuter jeudi.

**Comment by fxprunayre** [comment]
> Est-ce qu'un ajout du même genre est envisageable?

Je vais regarder.

**Comment by fxprunayre** [comment]
> (les services INSPIRE sont multicouches),

Mais ils sont aussi uniquement en WMS ?
eg.
http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/b7f2f896-5983-46dd-bed6-c43e15613efb

Du coup en testant cet exemple, on a un layerName "Service de visualisation WMS INSPIRE - Zones de gestion, de restriction ou de réglementation et unités de déclaration en Wallonie (BE)", on tente une recherche dans le GetCapabilities https://geoservices.wallonie.be/INSPIRE/WMS/AM/MapServer/WMSServer?request=GetCapabilities&service=WMS avec différentes méthodes pour trouver un match. Premier problème, on split ',' donc on cherche 2 layers:
* Service de visualisation WMS INSPIRE - Zones de gestion
* de restriction ou de réglementation et unités de déclaration en Wallonie (BE)
:) donc bof. Mais ok, continuons

Les méthodes :
* layer name -> no match
* layer name sans namespace -> no match
* identifier -> match sur UUID car le GetCapabilities est bien rempli
* metadataUrl -> y'aurait match aussi mais on s'arrête avant du coup.

Mais on a 2 correspondances sur la layer AM.RiverBasinDistrict.SubUnit.WFD et là c'est le bazar - essentiellement parcequ'on a une "," dans le layer name

https://geoservices.wallonie.be/INSPIRE/WMS/AM/MapServer/WmsServer?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=Service%20de%20visualisation%20WMS%20INSPIRE%20-%20Zones%20de%20gestion%2C%20de%20restriction%20ou%20de%20r%C3%A9glementation%20et%20unit%C3%A9s%20de%20d%C3%A9claration%20en%20Wallonie%20(BE)&STYLES=&CRS=EPSG%3A3857&WIDTH=2045&HEIGHT=1501&BBOX=-12303153.281503929%2C-4956542.975129664%2C12647280.005631858%2C13356709.036601786



... Je vais regarder d'autres cas pour voir ce qu'on pourrait faire.


Y'a également des cas où l'extent n'est pas bonne - on fait zoomer vers et on arrive à 0,0.

**Comment by fxprunayre** [comment]
Certains cas améliorés. A déployer et tester. 

Le mode "ajoute toutes les couches du service" ne me semble pas super simple à implémenter vu le mode de fonctionnement actuel. Je le mets en attente. A discuter.

**Comment by vbombaerts** [comment]
Je ne détecte pas d'urgence. Je le passe sur la version suivante. 
@vbombaerts définir si le déploiement effectif de noeuds est prioritaire ou pas

**Comment by vbombaerts** [comment]
@mawibrin Tu as le temps de tester et donner un feed-back ?

**Comment by fxprunayre** [comment]
Je confirme qu'en activant le module carto, désactivant le viewer externe (geoportal)

```
        'map': {
          'enabled': true,
          'appUrl': '../../{{node}}/{{lang}}/catalog.search#/map',
          'externalViewer': {
            'enabled': false,
```

on peut bien ajouter des couches ESRI à la carte

![image](https://user-images.githubusercontent.com/1701393/119982311-f4ff5e00-bfbe-11eb-8f61-2045bd1062e7.png)

Après y'a peut être des cas particulier sur certaines couches à améliorer.

**Comment by vbombaerts** [comment]
Portail testenvi en valid, onglet carte
[http://metawal4.valid.wallonie.be/geonetwork/testEnvi/fre/catalog.search#/map](http://metawal4.valid.wallonie.be/geonetwork/testEnvi/fre/catalog.search#/map)

Ca donne pas mal d'erreurs mais on voit les données.

**Comment by vbombaerts** [comment]
Si on part sur la création d'un portail intranet, ce serait bien d'en définir les specs @mawibrin @vbombaerts 
Ensuite on crée un ticket général qui rassemble les sous-tâches, comme ça on voit où on en est.

**Comment by vbombaerts** [comment]
OK en valid (avec messages d'erreur, mais fonctionnel)
