### ISSUE TITLE
Fiche donnée WALOUS -occup n'arrive pas dans les recherches ni dans le géoportail

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#574]
**Describe the bug**
La fiche suivante est accessible en direct http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/a0ad23a1-1845-4bd5-8c2f-0f62d3f1ec75, mais n'apparait plus via la recherche de metawal et ni dans le géoportail.

Par rapport à sa jumelle WALOUS - utilisation du sol ( http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/fafb9fc7-4e32-4a40-8163-c64966cb573c ) , les privilèges sont bien les mêmes.
![image](https://user-images.githubusercontent.com/6093453/103623478-7d119800-4f38-11eb-8daf-efdb9ef36d51.png)
![image](https://user-images.githubusercontent.com/6093453/103623606-9dd9ed80-4f38-11eb-9b86-855fc1edd70b.png)

Je remarque que la fiche problématique serait un 'modèle' 
![image](https://user-images.githubusercontent.com/6093453/103621126-06bf6680-4f35-11eb-90e9-035eed482dfb.png). Est-ce que cela pourrait jouer?
Le gestionnaire de la thématique a fait quelques éditions sur la fiche, mais je n'en sais pas plus (elle est absente aujourd'hui). Cela m'étonne qu'elle ait modifié vers un modèle, mais on ne sait jamais.

Vous avez une idée? piste? La fiche était bien accessible avant...

**Comment by fxprunayre** [comment]
> Vous avez une idée? piste? La fiche était bien accessible avant...

La fiche est un modèle 
![image](https://user-images.githubusercontent.com/1701393/103647839-346bd600-4f5c-11eb-8d61-c9833756a028.png)

Je te laisse l'éditer et l'enregistrer comme fiche? J'essaye de voir quand ça c'est produit.

**Comment by fxprunayre** [comment]
> J'essaye de voir quand ça c'est produit.

Si on regarde l'historique tu as fait quelques modifs sur les imagettes http://metawal.wallonie.be/geonetwork/srv/api/records/status/search?type=workflow&type=task&type=event&record=14567&from=0&size=15&details=true mais y'a pas moyen de savoir quelle action aurait changé la fiche en modèle.

**Comment by mawibrin** [comment]
Si je fais 'enregistrer en tant que fiche' (sous le bouton vert), elle va changer d'uid ou garder l'actuel? J'aimerais qu'elle garde l'actuel pour ne pas faire des changements dans les routines qui suivent.

**Comment by mawibrin** [comment]
oui j'ai fait des modifs sur les imagettes ce matin. Pendant mes congés le gestionnaire avait ajouté des liens vers des sites web mais en les associant à une ressource de type imagette. Le problème est plus ancien, a priori au min depuis le 28/12 (j'ai un email au 30/12 disant que ca fait deux jours)

**Comment by fxprunayre** [comment]
Ca garde l'UUID, ca change juste le type.
