### ISSUE TITLE
Noeud: problématique de fiches liées 

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#575]
**Describe the bug**
Pour le noeud testEnvi (basé sur un tag INFRASIG), je reçois 148 fiches. Je suis étonnée par les comportement autour ressources liées. Est-ce à régler avec une feuille de style, à gérer autrement? Suivant où je suis dans le noeud, il refuse d'ouvrir la fiche de ressource associée (depuis la partie recherche) ou bien l'ouvre en dehors du noeud (si on est déjà sur une fiche).

**To Reproduce**
1. Go to http://metawal4.test.wallonie.be/geonetwork/testEnvi/fre/catalog.search#/home. 
2. Faire une recherche (ex bord de route)
3. Ouvrir une fiche liée (donc par ex celle du service de la donnée bord de route en fauchage tardif, via le lien à côté de l'image - pas ouvrir la fiche de la donnée)
4. cette fiche est souvent inaccessible (vu qu'elle n'a pas nécessairement le tag)
5. si on ouvre la fiche de la recherche (donc ici http://metawal4.test.wallonie.be/geonetwork/testEnvi/fre/catalog.search#/metadata/f641aff2-fc7b-49b1-99fb-9369b8f491a7) les fiches des ressources associées s'ouvrent (dans metawal, pas dans le noeud)

**Expected behavior**
Une cohérence entre les deux manières d'accéder aux fiches des ressources associées et de là voir comment on gère/encode si on veut une vue spécifique du catalogue.

**Screenshots**
![image](https://user-images.githubusercontent.com/6093453/103864913-b0ccf900-50c3-11eb-96ac-b07f416add6b.png)
![image](https://user-images.githubusercontent.com/6093453/103865884-26859480-50c5-11eb-9ba1-7142ecf0c6dd.png)

**Comment by fxprunayre** [comment]
Je vais regardé en détail mais l'idée dans les relations c'est de ne pas se limiter au portail. On a donc potentiellement dans les relations des liens vers des fiches qui ne sont pas dans le portail (voir fiche externe mais pas dans metawal) qu'on doit ouvrir dans le catalogue principal (changement d'URL) qu'on ne peut pas ouvrir dans le portail (car non visible). C'est sans doute lié à ça (et peut être que le template metawal n'a pas été mis à jour pour ça).

Ajouté avec https://github.com/geonetwork/core-geonetwork/pull/4608 et la possibilité de faire des liens vers des fiches d'un autre catalogue https://github.com/geonetwork/core-geonetwork/pull/4899

**Comment by fxprunayre** [comment]
cf. https://github.com/geonetwork/core-geonetwork/pull/5316

**Comment by fxprunayre** [comment]
A déployer et tester.
