### ISSUE TITLE
De metawal vers le le géoportail, perte d'info

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#576]
**Describe the bug**
Des (les?) fiches parents/filles ne suivent pas côté geoportail + tags INFRASIG comme celui sur le panier de téléchargement ne suit pas.. Cela ne concerne pas toutes les fiches

**To Reproduce**
Je vois que les zones d'échange sont encodées ( http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/94a2bb17-3649-4cf2-bc44-3975f4e16888) comme fille d'une série sur les aménagements routiers ( http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/7451e2bd-22e8-4a74-a999-01c58b630369). Dans metawal on voit bien la liaison.
Celle-ce ne remonte pas dans le géoportail (zones échange http://geoportail.wallonie.be/catalogue/94a2bb17-3649-4cf2-bc44-3975f4e16888.html  + série aménagement routiers https://geoportail.wallonie.be/catalogue/7451e2bd-22e8-4a74-a999-01c58b630369.html). 

Pour le panier de télécha exemple http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/d1a80c5c-419e-47fe-85e2-269792a6f9a2  https://geoportail.wallonie.be/catalogue/d1a80c5c-419e-47fe-85e2-269792a6f9a2.html

**Expected behavior**
Que la liaison suive.
cfr la doc de Stéphane, suite aux changements de début 2020 pour la liaison entre les fiches, le xml du csw devrait avoir l'info. Quand depuis le Géoportail on demande le xml, l'info n'est pas là (mais je ne suis pas certaine de comment ce xml est généré).
Les seules liaisons qui semblent suivre semblent être celles taguées 'ressources associées' et non les nouvelles associations.

**Comment by mawibrin** [comment]
Il y a eu une mise en prod du géoportail, cela vient sans doute de là... Je fermerai le ticket quand ce sera sur.

**Comment by fxprunayre** [comment]
Pour vérifier côté Metawal, 
http://metawal.wallonie.be/geonetwork/inspire/fre/csw?request=GetRecordById&service=CSW&outputSchema=mw&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=94a2bb17-3649-4cf2-bc44-3975f4e16888

Tu peux noter les éléments avec un commentaire qui sont ajoutés pour "flagger" les liens bidirectionnels ajoutés dynamiquement dans la réponse du CSW
```xml

<!-- Added from http://metawal.wallonie.be/geonetwork/inspire/api/records/94a2bb17-3649-4cf2-bc44-3975f4e16888/related?type=associated&type=brothersAndSisters -->
<gmd:aggregationInfo>
<gmd:MD_AggregateInformation>
<gmd:aggregateDataSetIdentifier>
<gmd:MD_Identifier>
<gmd:code>
<gco:CharacterString>df78419b-d747-4a4d-8ce0-f81ebc7707c2</gco:CharacterString>
</gmd:code>
</gmd:MD_Identifier>
</gmd:aggregateDataSetIdentifier>
<gmd:associationType>
<gmd:DS_AssociationTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#DS_AssociationTypeCode" codeListValue="crossReference"/>
</gmd:associationType>
</gmd:MD_AggregateInformation>
</gmd:aggregationInfo>
```

**Comment by davinciagf** [comment]
Voir également discussions #525 et #558

**Comment by mawibrin** [comment]
L'équipe du Géoportail a, lors de sa dernière mise à jour toute récente, fait des modifications suite aux évolutions/bonnes pratiques de mw. Cela a apparemment été validé par Stéphane, et puis ici validé par le gestionnaire Géoportail sans voir le problème pour certaines fiches.
Le développeur géoportail indique "**que le système s'attend à avoir 'information « download » et non « information »
Pour qu’une fiche soit « téléchargeable », il faut que le protocol soit « WWW:LINK-1.0-http--link" ET le code « download** " ... là, je ne vois pas où il y a une info de protocol/code au niveau des balises infrasig pour le panier de téléchargement.

_Salut Marie-Aline,
Voici l’explication concernant le fait que de nombreuses données ont leur bouton « télécharger » grisé.
Il s’agit d’un point qui avait été modifié avec Stéphane, afin d’harmoniser les bonnes pratiques de Metawal concernant la possibilité ou non de télécharger une donnée.
Est-ce que le code ci-dessous de dit quelque chose ?
On peut s’appeler si tu veux.
A toute,
Samuel_

De : siteweb.dtic <siteweb.dtic@spw.wallonie.be>
_Envoyé : lundi 11 janvier 2021 10:13
À : MATTERN Samuel <samuel.mattern@spw.wallonie.be>
Objet : RE: Bug telechargement orthos

Bonjour Samuel,

Dans la fiche ORTHO 2020, **le système s’attend à avoir l’information « download » et non « information »
Pour qu’une fiche soit « téléchargeable », il faut que le protocol soit « WWW:LINK-1.0-http--link" ET le code « download »._

<gmd:onlineResource>
<gmd:CI_OnlineResource>
<gmd:linkage>
<gmd:URL>[https://geoportail.wallonie.be%3c/gmd:URL]https://geoportail.wallonie.be</gmd:URL>
</gmd:linkage>
<gmd:protocol>
<gco:CharacterString>WWW:LINK-1.0-http--link</gco:CharacterString>
</gmd:protocol>
<gmd:name>
<gco:CharacterString>Géoportail de la Wallonie</gco:CharacterString>
</gmd:name>**
<gmd:description>
<gco:CharacterString>Géoportail de la Wallonie</gco:CharacterString>
</gmd:description>
<gmd:function>
<gmd:CI_OnLineFunctionCode codeList="http://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#CI_OnLineFunctionCode" codeListValue="information"/>
</gmd:function>
</gmd:CI_OnlineResource>
</gmd:onlineResource>

Xavier

**Comment by mawibrin** [comment]
pour le panier de téléchargement, NSI s'est rendu compte de son erreur et fait un correctif. J'espère que pour les autres points ce sera de même
