### ISSUE TITLE
Encoder les conditions accès/utilisation

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#577]
Je suis perdue dans l'encodage des conditions d'accès et d'utilisation. Vous pouvez m'aider?

Toute une série de données liées à l'action sociale sont sorties il y a quelques semaines. Elles auraient du avoir les mêmes conditions d'accès/utilisation, les plus larges (type C). On vient de voir que ce n'était pas le cas, et je veux harmoniser le tout, mais rien ne m'est clair. J'ai trois cas différents et ne vois pas bien comment passer de l'un à l'autre.
j'ai une série avec le type C, avec trois entrées dans autres contraintes (7d365bcc-fa65-4266-9c36-810e7c9e1428) ![image](https://user-images.githubusercontent.com/6093453/104161346-028ebf80-53f3-11eb-8f1b-4dc000c196a9.png)
une autre série sans l'extension C, avec une seule entrée (08993909-fa8f-415b-97f6-5ceecc022d32) 
![image](https://user-images.githubusercontent.com/6093453/104161621-74670900-53f3-11eb-9944-fd1ca413d868.png)
une donnée sans l'extension C, avec deux entrées (d1a80c5c-419e-47fe-85e2-269792a6f9a2)
![image](https://user-images.githubusercontent.com/6093453/104161931-f6573200-53f3-11eb-88e7-7a9adb4f0e08.png)

Et si la bonne pratique est celle à trois entrée, je ne vois pas comment depuis celle de deux entrées, je peux en ajouter une troisième

Je ne comprend ni la logique d'une, deux ou trois entrées, ni comment en ajouter ;-(

**Comment by fxprunayre** [comment]
Normalement pour la saisie, l'approche était https://github.com/SPW-DIG/metawal-core-geonetwork/issues/459.
Là, tu es en vue simple?

**Comment by mawibrin** [comment]
Pour 0e1a4668-a209-4487-b05a-f85b3e99874f je suis en vue avancée avec une entrée.
![image](https://user-images.githubusercontent.com/6093453/104176429-82268980-5407-11eb-9ee1-4a8b28870524.png)
j'ai compris que je pouvais supprimer le contenu de l'entrée et avoir accès à la liste déroulante
![image](https://user-images.githubusercontent.com/6093453/104176748-0842d000-5408-11eb-871e-af6318227424.png)
**Mais même après une sauvegarde il ne me donne pas le même résultat que sur l'autre fiche (7d365bcc-fa65-4266-9c36-810e7c9e1428 ). Peut-être comme si le lien thesaurus n'était pas activé?**
Je vois alors qu'il y a une différence au niveau des limitations d'utilisation, et là la valeur indiquée dans ma fiche témoin ( 7d365bcc-fa65-4266-9c36-810e7c9e1428 ) n'est pas reprise dans la liste. Mais ca ne semble pas venir de là non plus

Avant de continuer mes essais:
- je peux bien me baser sur 7d365bcc-fa65-4266-9c36-810e7c9e1428 comme référence?
- mettre une valeur hors liste en début de bloc, (Conditions d'accès et d'utilisation spécifiques)
- mettre 'autres restrictions' et plus licences
- choisir les trois entrées ad hoc

Et comment ces 3 entrées sont converties? J'imagine que je ne dois pas aller manuellement les éditer...

**Comment by davinciagf** [comment]
A vérifier au niveau du thesaurus : 
- lien
- libellé

+ DB

**Comment by fxprunayre** [comment]
cf. https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.0.x/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/mw-constraints-split.xsl

**Comment by davinciagf** [comment]
Le thesaurus a été mis à jour (vor https://github.com/SPW-DIG/metawal-core-geonetwork/commit/e453079c26662a73df2c181ec9126e53849a78f9)
Testé sur http://metawal4.test.wallonie.be/geonetwork/srv/eng/catalog.search#/metadata/7025616c-f0a6-416b-b9a9-7ed22eb87c1f (copie de 0e1a4668-a209-4487-b05a-f85b3e99874f  basée sur les règles 7d365bcc-fa65-4266-9c36-810e7c9e1428)

# Pour modifier un thesaurus

Aller dans la partie Admin/Classification system/thesaurus
![Screen Shot 2021-01-20 at 10 47 26](https://user-images.githubusercontent.com/576292/105157215-09ad8000-5b0d-11eb-8421-754b3ea7e109.png)

1. Downloader le thesaurus à mettre à jour. 
2. Supprimer le thesaurus à mettre à jour du catalogue lorsque ce dernier a été downloadé pour édition.
3. Editer le thesaurus downloadé (format *.rdf). 
Ne pas changer le nom du fichier car ce dernier est utilisé comme clé d'identification dans le moteur.
4. Uploader le thesaurus mis à jour dans le catalogue.

# Info modification relative au thesaurus des contraintes 
 - Modification de la version
![Screen Shot 2021-01-20 at 11 00 42](https://user-images.githubusercontent.com/576292/105158904-c9e79800-5b0e-11eb-933d-cabd8302d222.png)
 - Harmonisation des labels sur base des modifications apportés par  https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.0.x/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/mw-constraints-split.xsl
 Exemple  
Elément de la version 1
![Screen Shot 2021-01-20 at 11 03 17](https://user-images.githubusercontent.com/576292/105159248-264ab780-5b0f-11eb-8b6f-431d2a0a11b6.png)
Elément de la version 2
![Screen Shot 2021-01-20 at 11 02 12](https://user-images.githubusercontent.com/576292/105159256-28ad1180-5b0f-11eb-9403-cdfe313b992a.png)

## Question
- Lors de la migration réalisées par https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.0.x/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/mw-constraints-split.xsl, de petites différences ont été apportées au niveau de la description des contraintes (exemple : "mais sont restreintes ou étendues par les" ou "et sont étendues par" ou "mais sont restreintes par"), celles-ci ont été intégrées dans la mise à jour du thesaurus mais la migration n'incluait pas toutes les conditions. Pour les éléments non référencés par cette migration l'utilisation de "mais sont restreintes ou étendues par les" a donc été appliquées. A vérifier si à modifier ou pas.

# En DB
La requete suivante ne retourne aucune MTD 
`select count(*) from metawal4.metadata where data like '%http://metawal.wallonie.be/thesaurus/conditions%';`

**Comment by davinciagf** [comment]
voir https://github.com/SPW-DIG/metawal-core-geonetwork/commit/e453079c26662a73df2c181ec9126e53849a78f9

**Comment by mawibrin** [comment]
c'est bien "et sont étendues" et pas mettre les deux ensembles

**Comment by mawibrin** [comment]
Je n'ai pas la bonne liste.
![image](https://user-images.githubusercontent.com/6093453/107228845-6968be00-6a1d-11eb-8484-83a0917b3b48.png)
ni pour une nouvelle fiche série, ni pour une nouvelle fiche couche.

**Comment by mawibrin** [comment]
La traduction pour le Géoportail ne se fait pas bien fiche b1085bd5-2958-4751-87b8-b1c6be04b653
![image](https://user-images.githubusercontent.com/6093453/113252886-ba31c000-92c4-11eb-9804-352dbdfc50d8.png)
![image](https://user-images.githubusercontent.com/6093453/113253170-2b717300-92c5-11eb-92fb-1bbaf1da929e.png)

**Comment by davinciagf** [comment]
Cela se reproduit sur d'autres fiches ? Et sur le problème est issus du géoportail de valid qui moissonne bien mw de valid?

**Comment by mawibrin** [comment]
C'est une fiche créée en valid, moissonnée par le Géoportail en valid (il y a eu quelques difficultés à faire pointer et synchroniser correctement).
La j'ai mis les conditions sur base des listes déroulantes.
Je ne sais pas trop si cette étape marchait avant vu que les listes était "ko".
Je ne sais pas si de véritables fiches ont les contraintes basées sur les listes. Si non ce n'est pas bloquant pour cette sortie, mais à rester ouvert. Comme les fiches avec les conditions écrites sans passer par les listes semblent ok.
Cela semble donc être un problème dans la conversion des ancres / post traitement.

**Comment by davinciagf** [comment]
Attention, La transformation se fait si on a une balise useLumitation et des ancres voir https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.0.x/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/present/csw/mw-full.xsl#L174 

Test sur la fiche fed9680c-1203-4a3b-9d9e-a2d2df7a7ade 

http://metawal4.test.wallonie.be/geonetwork/inspire/fre/csw?request=GetRecordById&service=CSW&outputSchema=mw&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=fed9680c-1203-4a3b-9d9e-a2d2df7a7ade 

Par contre certaines conditions de la nouvelle version du thesaurus (v2) ne sont pas reprises dans les règles.

Au niveau du moissonnage du géoportail, un update dans la fiche au niveau des conditions ne semble pas être pris en compte (à vérifier). 
![Screen Shot 2021-04-22 at 14 57 37](https://user-images.githubusercontent.com/576292/115718167-2b700a80-a37b-11eb-9ed6-24ff2ae1f203.png)

or le profil mw donne:
![Screen Shot 2021-04-22 at 14 59 18](https://user-images.githubusercontent.com/576292/115718415-63774d80-a37b-11eb-81c4-bac587ba6d73.png)

**Comment by davinciagf** [comment]
Quelles sont les règles de mise à jour pour les conditions au niveau du géoportail car ce dernier ne semble pas se mettre à jour sur base du profil mw? En effet, ce dernier reste sur d'anciennes conditions qui ont été mise à jour au niveau de la MTD mais que l'on ne retrouve pas au niveau du géoportail  et ce après plusieurs synchronisation.

Profil mw : http://metawal4.test.wallonie.be/geonetwork/inspire/fre/csw?request=GetRecordById&service=CSW&outputSchema=mw&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=fed9680c-1203-4a3b-9d9e-a2d2df7a7ade

Géoportail: http://geoportail.test.wallonie.be/catalogue/fed9680c-1203-4a3b-9d9e-a2d2df7a7ade.html

**Comment by vbombaerts** [comment]
@davinciagf En principe il y a mise à jour de la fiche si changement de la date de révision de la fiche.

**Comment by vbombaerts** [comment]
Je n'ai pas réussi à encoder correctement.

Dans l'interface d'édition, j'ai bien une liste de conditions d'accès et d'utilisation mais les textes ne correspondent pas.
Les ancres sont indiquées.

![image](https://user-images.githubusercontent.com/6093597/121391910-29740200-c94f-11eb-954c-4476ebf4931e.png)

[Fiche dans MW valid](http://metawal4.valid.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/1ee5b57f-0c46-49de-83db-01610da25751)


Via le CSW, je n'ai ni les ancres ni les bons textes.

![image](https://user-images.githubusercontent.com/6093597/121392217-7a83f600-c94f-11eb-9e3d-733049508928.png)


[Fiche via CSW valid](http://metawal4.valid.wallonie.be/geonetwork/srv/fre/csw?request=GetRecordById&service=CSW&outputSchema=mw&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=1ee5b57f-0c46-49de-83db-01610da25751)

**Comment by fxprunayre** [comment]
Hum, le CSW vérifie la présence des ancres https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.0.x/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/present/csw/mw-full.xsl#L46 
eg. https://geoportail.wallonie.be/files/documents/ConditionsSPW/DataSPW-CGU.pdf

hors là, on a autre chose. Donc le thésaurus n'est pas le bon en valid ?

Devrait être https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.0.x/web/src/main/webapp/WEB-INF/data/config/codelist/external/thesauri/theme/access_use_conditions.rdf#L28 

A vérifier.

**Comment by vbombaerts** [comment]
Test en valid.

La valeur
```
<mco:MD_LegalConstraints>
<mco:useLimitation>
<gco:CharacterString>Conditions d'accès et d'utilisation spécifiques</gco:CharacterString>
</mco:useLimitation>
```
n'est pas proposée dans la dropdown list. 
![image](https://user-images.githubusercontent.com/6093597/121931189-93235000-cd43-11eb-8b1b-7933b2539e07.png)



Comme elle obligatoire dans [la condition](https://github.com/SPW-DIG/metawal-core-geonetwork/blob/62bf9337aef603dca39550eacd934965d81091e2/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/present/csw/mw-full.xsl#L174), forcément rien ne se passe.

Et **on va avoir un problème en prod** parce que la dropdown list des useLimitations est la même qu'en valid.

Mais au fait, pourquoi cette condition est-elle obligatoire pour déclencher le remplacement des ancres ??
Une useLimitation est selon la définition ISO plutôt une limitation technique ou légale mais ne sert pas à indiquer la présence de conditions d'accès et d'utilisation qui sont plus selon moi apparentées à des licences. Ce sont donc 2 choses différentes et je ne vois dès lors pas pourquoi la useLimitation restreint le XSL. Si qqun se rappelle le pourquoi de la décision je suis preneur.

**Comment by fxprunayre** [comment]
> hors là, on a autre chose. Donc le thésaurus n'est pas le bon en valid ?
> Devrait être https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.0.x/web/src/main/webapp/WEB-INF/data/config/codelist/external/thesauri/theme/access_use_conditions.rdf#L28


Est-ce que quelqu'un peut vérifier le thésaurus en valid ?

**Comment by fxprunayre** [comment]
> Mais au fait, pourquoi cette condition est-elle obligatoire pour déclencher le remplacement des ancres ??

Je dirai que c'est lié à INSPIRE. L'année dernière on a fait un peu de ménage sur les valeurs encodées  https://github.com/SPW-DIG/iso19115-3.2018/blob/5db7c2e4d597c53ac25e5bf20331a70653fc44d2/src/main/plugin/iso19115-3.2018/process/inspire-tg2.xsl#L187-L247 et je pense que les conditions d'accès et d'utilisation sont toujours mises dans le même bloc ?

**Comment by davinciagf** [comment]
> > hors là, on a autre chose. Donc le thésaurus n'est pas le bon en valid ?
> > Devrait être https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.0.x/web/src/main/webapp/WEB-INF/data/config/codelist/external/thesauri/theme/access_use_conditions.rdf#L28
> 
> Est-ce que quelqu'un peut vérifier le thésaurus en valid ?

Il me semble l'avoir mis à jour sur base de la test suite aux dernières modifs fin de semaine passée.

**Comment by vbombaerts** [comment]
Le thésaurus est bon en valid. (mais on n'a fait que quelques éditions en valid depuis la réplication de la base de prod il y a une semaine).

J'ai vu le travail de ménage qui a été fait sur les fiches INSPIRE et c'est bien aussi. INSPIRE exige qu'on renseigne un champ useLimitation.

Par contre, pour les autres fiches, ce champ est assez peu utilisé. Du coup, je ne comprends pas pourquoi on exige que useLimitation = "Conditions d'accès et d'utilisation spécifiques" pour corriger les CA/CU typiques du géoportail.

C'est cette condition [L174](https://github.com/SPW-DIG/metawal-core-geonetwork/blob/62bf9337aef603dca39550eacd934965d81091e2/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/present/csw/mw-full.xsl#L174) qui "pose problème". Elle passe pour un ensemble de données pour lesquelles on retrouve comme useLimitation "Conditions d'accès et d'utilisation spécifiques", mais pour d'autres, où on n'a pas encodé de useLimitation (ou une autre valeur) mais qu'on a quand même utilisés les licences SPW les conditions liées aux licences ne sont pas traduites par le XSL.

J'ai scruté d'un peu plus près la "bible de l'encodage" que Geoffroy avait écrite. Je n'y ai pas trouvé de mention de ces useLimitation spécifiques. Et comme je le pense, il est préconisé de n'utiliser les useLimitation que pour INSPIRE ou quelques cas spécifiques. Bizarre...

Je propose qu'on laisse comme c'est pour le moment et qu'on examine plus en détail ce point en lien avec la rationalisation de CA/CU.

**Comment by fxprunayre** [comment]
Ok, comme nous avions fait les corrections avec le XSL uniquement pour les fiches INSPIRE, c'est cohérent. Donc maintenant faut en effet définir l'approche pour les autres fiches ou faire que le Géoportail gére les différents niveaux d'accès dans les blocs différents ?

**Comment by vbombaerts** [comment]
Je ferme pour cette partie-ci. La suite avec #617
