### ISSUE TITLE
Le bon référencement des services dans une fiche service

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#578]
Au fil du temps les fiches services ont évolué. Geof indiquait "Cette décision « 1 protocole = 1 fiche » est récente (09/2017)." Stéphane a changé cela pour regrouper tous les services en une entrée dans le catalogue. Le passif n'est (encore) pas re-rattrapé. Avant de le faire je voudrais m'assurer de ne pas faire trop de ping-pong... (dans la doc de Geof il est indiqué que dans une fiche le protocole doit être mis, avec une cardinalité de 1, pour MW et pour INSPIRE). Si vous avez des éléments de réponses...

La question ici porte d'abord sur le référencement de la (des) urls dans les fiches services. Je remarque deux résultats différents: 
C'est dans transfert pour 6af53b76-d4f6-4c3d-8829-dea31a0cbbcd  mais ce n'est pas le cas pour http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/36642b5f-40ad-40b7-9b9d-22163a7215e2/formatters/xsl-view?root=div&view=advanced

![image](https://user-images.githubusercontent.com/6093453/104313502-66d77f00-54d8-11eb-8cc5-d193f0ee0cb1.png)

**Comment by davinciagf** [comment]
Parles-tu de la présence du titre 'Options de transfert...' ? La différence provient du nombre de ressources en ligne référencées
http://metawal4.test.wallonie.be/geonetwork/srv/eng/catalog.search#/metadata/3b425edd-8e48-40d6-9675-a217aa79147f/formatters/xsl-view?root=div&view=advanced

**Comment by mawibrin** [comment]
Si ce terme 'Options de transfert numérique' n'apparait que quand il y a plusieurs ressources, je me suis posé des questions pour rien. Dans ce cas le xml semble bien structuré de la même manière. Dans mes premiers tests de la semaine dernière je ne sais plus si j'avais regardé la vue sans édition, la complète en édition ou le xml. Mais si ce n'est que du style de mise en page tout est ok, c'est juste un peu perturbant.
