### ISSUE TITLE
Fiches disparues de MW

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#579]
Les 3 fiches non publiée suivantes ont disparus. Je ne sais pas si elles avaient été préparées en prod/vali/test, ni quand.

6e4c2639-2dc4-4d06-84b3-d17529fe46fa      à  LIM_ADMIN_LAST
305e8131-1606-4c54-8f8b-6d48eec6678b   à CADGIS_LAST
78fdea09-d572-440c-97c7-2dad83d86f66    à Service PASH

Je ne les trouve ni par l'id, ni pas les trois mots. Ni en prod, ni en test.

Vous avez une idée de pourquoi elles ont pu disparaître et de si elles sont retrouvables facilement?

**Comment by fxprunayre** [comment]
Dans le datadir il y a un répertoire backup qui contient les fiches supprimées - les fiches disparues je sais pas bien où elles sont mises :) Un backup d'une db ?

**Comment by mawibrin** [comment]
Merci. Je vais les recréer, elles n'avaient apparemment pas bcp d'info.

**Comment by fxprunayre** [comment]
@davinciagf est-ce que ce serait pas les fiches supprimées semaine dernière? Est-ce qu'on peut vérifier dans le datadir/backup pour voir si elles ont été supprimées à la main via l'interface ?

**Comment by davinciagf** [comment]
Non présent dans le backup de test et elles ne correspondent pas aux erreurs lors du moissonnage en erreur de la semaine passée.

**Comment by davinciagf** [comment]
Retrouvées dans le backup de prod.
