### ISSUE TITLE
Suppression relation parent enfant

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#582]
Je n'arrive pas à supprimer un lien parent-enfant, malgré le clic sur la croix il reste. C'est un bug ou je m'y prend mal?

http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/c1993328-339a-4bd5-93c3-d5a0c4693bed
![image](https://user-images.githubusercontent.com/6093453/106444466-17a0c080-647e-11eb-9980-f506f181e104.png)

Idem pour http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/f396750b-2b8f-42e5-9439-8ac1b58873b8
où là je dois supprimer un des deux parents (celui qui n'a pas le mot série).
![image](https://user-images.githubusercontent.com/6093453/106445249-0efcba00-647f-11eb-8cba-ec86253be0fe.png)
Si je supprime celui qui n'a pas le mot série, il y a bien une suppression, mais de l'autre. Si ensuite je veux supprimer celui qui reste, ca ne va pas.

**Comment by fxprunayre** [comment]
GeoNetwork ref. https://github.com/geonetwork/core-geonetwork/pull/5390

En attendant, tu peux utiliser la vue avancée ou XML.

**Comment by fxprunayre** [comment]
A déployer @davinciagf 

S'il y a des erreurs lors de la recherche, il faut mettre à jour les configurations d'interface (ou les suppimer/recréer). Le principal changement vient de la configuration des facettes - les élements `userHasRole`, `collapsed` sont dans l'élément `meta` au lieu de la racine:

```
"resolutionScaleDenominator": {
  "terms": {
    ...
  },
  "meta": {
      'userHasRole': 'isEditorOrMore'
      'collapsed': true
  }
```

**Comment by mawibrin** [comment]
NOK en test car quand je veux ajouter un parent quand il y en a déjà un, cela supprime le premier. Stéphane avait fait des fiches avec deux parents.

**Comment by fxprunayre** [comment]
Pb: Corriger le bouton "ajouter" qui doit ouvrir la même interface que le bouton Add > Fait partie de.

**Comment by fxprunayre** [comment]
> Pb: Corriger le bouton "ajouter" qui doit ouvrir la même interface que le bouton Add > Fait partie de.

Fait. @davinciagf à déployer.

**Comment by davinciagf** [comment]
Déployé
