### ISSUE TITLE
Conformité des services de WMS ou ATOM : problème de ressources associées

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#583]
**Describe the bug**
Pour les services WMS/ATOM nous avons une erreur de conformance au niveau des ressources associées.

**Info du rapport Europe**
Erreur Conformance class 3 - md sds 3.6 : Coupled Resource
Rapport EU pour 74fe32b4-09b2-4ade-9b3b-373c7877eeae
![image](https://user-images.githubusercontent.com/6093453/107370403-3852c100-6ae3-11eb-847f-27e76b940aa6.png)

**Metawal**

XML MD (Metawal) pour 74fe32b4-09b2-4ade-9b3b-373c7877eeae
```
<srv:operatesOn uuidref="571a70c1-6c14-4eae-8405-ddcf0af5b46f"                         xlink:href="http://metawal.wallonie.be/geonetwork/srv/fre/csw?service=CSW&amp;request=GetRecordById&amp;version=2.0.2&amp;outputSchema=http://www.isotc211.org/2005/gmd&amp;elementSetName=full&amp;id=571a70c1-6c14-4eae-8405-ddcf0af5b46f"/>
         <srv:operatesOn uuidref="37abcf36-e6a5-4ec7-b894-1c7e2dcad02b"
                         xlink:title="INSPIRE - Concessions minières - Série"
                         xlink:href="http://metawal.wallonie.be/geonetwork/srv/api/records/37abcf36-e6a5-4ec7-b894-1c7e2dcad02b"/>
```
 
**=> Validateur INSPIRE s'attend à avoir du XML donc via CSW et non API!!!!**

 Rapport validation via Metawal (check 2021-02-08) => Egalement Erreur
![image](https://user-images.githubusercontent.com/6093453/107370713-a1d2cf80-6ae3-11eb-82ad-1b80a04090c3.png)

**Expected behavior**
Que les ressources associées soient 'liées' de la même manière dans le xml (INSPIRE), et de la manière demandée par INSPIRE.

**Questions**
Pourquoi certaines ressources apparaissent avec 'api' et d'autres 'csw'? Est-ce fonction de la manière dont le lien a été fait? Est-ce un problème de post-traitement pour le noeud INSPIRE?
Est-ce qu'on peut éditer manuellement les xml pour rendre cela conforme ou il y aura des effets de bords et qu'il vaut mieux par exemple passer par le gestionnaire de ressources ou en batch?
Outre la correction dès que possible des fiches INSPIRE, il semble y avoir un bug du coeur.

**Comment by fxprunayre** [comment]
> **=> Validateur INSPIRE s'attend à avoir du XML donc via CSW et non API!!!!**

En fait l'API http://metawal.wallonie.be/geonetwork/srv/api/records/37abcf36-e6a5-4ec7-b894-1c7e2dcad02b retourne du XML si on dit qu'on veut du XML, du HTML par défaut. Le validateur INSPIRE ne demande pas du XML.

Donc le moissonneur CSW pour INSPIRE remplace les liens de type API par des liens pointant le document en XML iSO19139 https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.0.x/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/present/csw/gmd-inspire-postprocessing.xsl#L27-L30 eg. http://metawal.wallonie.be/geonetwork/srv/api/records/37abcf36-e6a5-4ec7-b894-1c7e2dcad02b/formatters/iso19139?output=xml


>Pourquoi certaines ressources apparaissent avec 'api' et d'autres 'csw'? 

Dans Metawal elles devraient toutes être via l'API.
Dans CSW INSPIRE toutes avec API vers le formatter ISO19139 XML.

http://metawal.wallonie.be/geonetwork/inspire/fre/csw?service=CSW&request=GetRecordById&version=2.0.2&outputSchema=http://www.isotc211.org/2005/gmd&elementSetName=full&id=74fe32b4-09b2-4ade-9b3b-373c7877eeae
semble correct ?
et la validation marche a priori
https://inspire.ec.europa.eu/validator//v2/TestRuns/EID194e9c51-1883-47ec-b7a8-d4db7c26bd37.html

**Comment by dbu-spw** [comment]
Bonjour François, effectivement on avait bein compris que c'est la référence API (et donc une réponse html et non xml) qui pose problème. Mais par rapport au contexte Metawal on a 2 questions:

1. Pourquoi pour une même fiche on a un mélange de csw et d'api ?
2. Comment corriger : faut-il faire un édit manuel et via l'éditeur XML au risque de casser les liens "associated ressources" ? ou alors c'est au niveau du mapping stockage metawal vers exportation XML INSPIRE ou un autre manière ? => la meilleur solution pour appliquer le correctif ?

Dominique

**Comment by fxprunayre** [comment]
> * Pourquoi pour une même fiche on a un mélange de csw et d'api ?

Ca je sais pas. On va vérifier que quand on fait la saisie par l'interface on obtient toujours le même type d'encodage.



> 2\. Comment corriger : faut-il faire un édit manuel et via l'éditeur XML au risque de casser les liens "associated ressources" ? ou alors c'est au niveau du mapping stockage metawal vers exportation XML INSPIRE ou un autre manière ? => la meilleur solution pour appliquer le correctif ?

On va voir si on peut faire ça directement en DB.

**Comment by fxprunayre** [comment]
Bon j'ai compris, côté geoportail le moissonnage ne doit pas utiliser de GetRecordById
* XML côté geoportail https://inspire-geoportal.ec.europa.eu//resources//INSPIRE-f5201eb0-2404-11e5-8130-52540004b857_20210208-105502/services/1/PullResults/101-120/2.iso19139.xml KO
* GetRecordById http://geoservices.wallonie.be/metawal/csw-inspire?request=GetRecordById&service=CSW&outputSchema=http%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=74fe32b4-09b2-4ade-9b3b-373c7877eeae OK
* GetRecord http://geoservices.wallonie.be/metawal/csw-inspire?request=GetRecords&service=CSW&version=2.0.2&resultType=results&typeNames=gmd:MD_Metadata&&ElementSetName=full&outputSchema=http%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd&constraint=identifier+%3D+%2774fe32b4-09b2-4ade-9b3b-373c7877eeae%27&constraintLanguage=CQL_TEXT&constraint_language_version=1.1.0 KO


KO = Les liens vers l'API n'ont pas le suffix "formatters/iso19139?output=xml"

Donc corrigé côté GN https://github.com/geonetwork/core-geonetwork/pull/5421.

Comment on procède : Mise à jour de la prod ?

>>  Pourquoi pour une même fiche on a un mélange de csw et d'api ?
> Ca je sais pas. On va vérifier que quand on fait la saisie par l'interface on obtient toujours le même type d'encodage.

J'ai testé l'encodage des relations dans les 2 sens - à partir d'un service ou d'une donnée et j'ai toujours un encodage de type 
```xml
<srv:operatesOn uuidref="a6ee02ff-eb9b-4d31-8bdb-a56c087edf77"
                         xlink:href="http://localhost:8080/geonetwork/srv/api/records/a6ee02ff-eb9b-4d31-8bdb-a56c087edf77"/>
```

@davinciagf à déployer en test déjà.

**Comment by mawibrin** [comment]
Arnaud, est-ce que cela a été déployé en test ou tu ne l'as pas encore fait?

**Comment by davinciagf** [comment]
Oui, il est déployé et requête jouée en BD pour l'env. de test

**Comment by mawibrin** [comment]
Le correctif a permis une mise à jour au niveau de l’existant (ressources déjà associées) mais pas pour les nouvelles associations. => nouveau ticket ou garde celui-ci?


2 ressources associées ont été ajoutées à la fiche de métadonnée d’un service (afe6407c-125d-4ab8-9dcc-216ac848dad1) pour vérifier si les nouvelles associations ont bien le /formatters/iso19139?output=xml par défaut. Cela a été fait par Domnique depuis http://metawal.wallonie.be/geonetwork/inspire/fre

<srv:operatesOn uuidref="eed22735-0947-4e2d-8de9-b9cfbf492c80" xlink:href="http://metawal.wallonie.be/geonetwork/srv/api/records/eed22735-0947-4e2d-8de9-b9cfbf492c80/formatters/iso19139?output=xml"/>

<srv:operatesOn uuidref="938c92ef-9fcc-495f-9f48-dcec19ec7cc8" xlink:href="http://metawal.wallonie.be/geonetwork/srv/api/records/938c92ef-9fcc-495f-9f48-dcec19ec7cc8/formatters/iso19139?output=xml"/>

<srv:operatesOn uuidref="ff71a317-fc05-4d0d-b30b-58a1740eb314" xlink:href="http://metawal.wallonie.be/geonetwork/srv/api/records/ff71a317-fc05-4d0d-b30b-58a1740eb314/formatters/iso19139?output=xml"/>

<srv:operatesOn uuidref="3dc91d81-338f-425d-b27b-f62aa0464e21" xlink:href="http://metawal.wallonie.be/geonetwork/inspire/api/records/3dc91d81-338f-425d-b27b-f62aa0464e21"/>

<srv:operatesOn uuidref="70c5ee8d-1554-468b-b5d4-7c976b046894" xlink:href="http://metawal.wallonie.be/geonetwork/inspire/api/records/70c5ee8d-1554-468b-b5d4-7c976b046894"/>
