### ISSUE TITLE
Question kibana ELS sur la vue INSPIRE

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#584]
Le tableau  du suivi du rapportage INSPIRE indique que certaines fiches sont non valides alors qu'elles sont reconnues valides.

Je ne comprend pas bien ELS Kibana. Je n'arrive pas à trouver le champs sur lequel il se base pour voir le côté valide/pas valide et donc vérifier qu'il utilise le bon.

Merci pour votre aide

**To Reproduce**
Dashboard en production
Vue Tableau de suivi du Reporting INSPIRE
Filtrer pour avoir publié + dataset +serie
Dans les graphes choisir Annexe 1, et puis 'non valid'

Le tableau en bas donne deux entrées. Dont une pour laquelle le test a été refait hier. Valid Inspire, mais ici considérée comme non valide.

**Comment by davinciagf** [comment]
Le filtre est lié à l'indice 'valid' avec trois valeurs possibles 1,0,-1:
![Screen Shot 2021-02-23 at 13 55 52](https://user-images.githubusercontent.com/576292/108861976-17fd2900-75f0-11eb-8fb8-c7b1ea5734a8.png)
Le critère pour cette indice provient du résultat de la validation par le validateur via l'interface d'édition des MTD
![Screen Shot 2021-02-23 at 16 01 23](https://user-images.githubusercontent.com/576292/108863365-6c54d880-75f1-11eb-9eb4-978c022edce5.png)

Si tu joues la validation et que cela passe avec succès, l'indice est modifié à la valeur 1 (testé en local)
![Screen Shot 2021-02-23 at 16 02 57](https://user-images.githubusercontent.com/576292/108863057-1b44e480-75f1-11eb-9bba-40510341476f.png)
![Screen Shot 2021-02-23 at 16 06 03](https://user-images.githubusercontent.com/576292/108863088-20099880-75f1-11eb-81e8-bfce0a8671b2.png)

Si je ne me trompe pas, les deux MTD référencées en prod avec une valeur de -1 n'ont donc pas été validées via l'interface de MW.
![Screen Shot 2021-02-23 at 16 11 50](https://user-images.githubusercontent.com/576292/108863806-e2593f80-75f1-11eb-853f-be6b04eb12a0.png)
![Screen Shot 2021-02-23 at 16 11 36](https://user-images.githubusercontent.com/576292/108863876-f43ae280-75f1-11eb-9d8f-83d3bda746ca.png)

**Comment by mawibrin** [comment]
c'était le champs valid et pas le valid_inspire qui était utilisé => changé
