### ISSUE TITLE
En test, problème d'accès aux fiches

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#585]
**Describe the bug**
Après une édition il me dit que je n'ai pas accès à la fiche

**To Reproduce**
1. Ouvrir une fiche en édition dans l'environnement de test
2. Annuler
3. See error in 'La fiche avec l'identifiant n'a pas été trouvée ou n'est pas partagée avec vous. Essayer de vous connecter si vous avec un compte.'

![image](https://user-images.githubusercontent.com/6093453/109968165-a2c9dc00-7cf2-11eb-9884-c06371554c6c.png)
Testé sur trois fiches en voulant valider qu'un autre bug était résolu en test (sur edge)

Et les fiches ne semblent même plus exister après (TEST MAW sur le schéma cyclable série et liaisons entre pôles), difficile donc de valider que la liaison parent/enfant est ok

**Comment by davinciagf** [comment]
La réindexation devrait résoudre le problème.

**Comment by mawibrin** [comment]
résolu avec l'indexation
