### ISSUE TITLE
Metawal et DCAT

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#586]
Quelles seraient les possibilités / contraintes d'avoir la possibilité d'utiliser DCAT aussi dans metawal?
Je vois qu'un plugin GN existe. Possible de l'avoir en test?

Il y a de plus en plus de demande de métadonnées pour des données non carto et on devra aussi se positionner par rapport à des catalogues données SPW/wallons (opendata ou non).

**Comment by fxprunayre** [comment]
Il y a différents travaux sur le sujet
* Format de sortie DCAT
  * Déjà, dans Metawal actuel, on peut déjà demander en CSW un retour en DCAT (le mapping ISO>DCAT serait sans doute à améliorer)
  * Côté GN, sur le long terme, l'idée est d'avoir un service de recherche dédié (implémentatnt la norme OGC API Records ~= CSW4) pouvant retourner différent format. Un premier draft de sortie GeoDCAT-AP a été mis en place https://github.com/geonetwork/geonetwork-microservices/pull/37
* Ensuite pour faire de la saisie
  * https://github.com/metadata101/dcat-ap1.1 plugin Flamand (délicat à installer et assez couplé avec le projet dans lequel il est utilisé eg. langues) 
  * https://github.com/metadata101/dcat2/tree/master/src/main/plugin/dcat2 approche générique - ébauche, recherche de financement pour avancer
