### ISSUE TITLE
Email pour le contact sur les métadonnées

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#587]
**Describe the bug**
Le point de contact pour les métadonnées n'a pas/plus droit à un email, quelle que soit la fenêtre de saisie.
![image](https://user-images.githubusercontent.com/6093453/111585600-d6f7cf00-87bf-11eb-9f95-b26d7820b1b6.png)

**Comment by fxprunayre** [comment]
Tu peux passer en vue avancée et ajouter l'email pour le contact en question ?
Le clic sur ajotuer un contact ajoute bien un contact avec les 3 champs. 
L'idée était de garder le mode tableau simple. On peut essayer d'ajouter un bouton + quand le mail n'est pas présent si besoin?

**Comment by mawibrin** [comment]
ok, j'ai compris comment ajouter l'email depuis la vue avancée. Je ne l'avais pas vu dans la partie adresse.
