### ISSUE TITLE
Ajout d'une ressource associée avec # dans l'url

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#588]
**Describe the bug**
Quand on ajoute une url qui a un # via l'interface des ressources, la partie avant le # n'est pas gardée. Il faut alors éditer manuellement dans la vue complète.

**Screenshots**
![image](https://user-images.githubusercontent.com/6093453/113847455-cb347280-9797-11eb-96b3-b14cc75ad91b.png)

![image](https://user-images.githubusercontent.com/6093453/113847311-a50ed280-9797-11eb-837a-cbe584c257ef.png)

**Comment by fxprunayre** [comment]
Fixed in https://github.com/geonetwork/core-geonetwork/pull/5568

**Comment by davinciagf** [comment]
A déployer en test pour le 16/04

**Comment by fxprunayre** [comment]
Testé en local ok. A déployer.

**Comment by davinciagf** [comment]
Déployé et testé sur  http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/a39af4c6-c06e-4d9d-8121-b0c7717eea1a 
![Screen Shot 2021-04-28 at 14 57 12](https://user-images.githubusercontent.com/576292/116407541-27883080-a832-11eb-8361-2a844f030fc1.png)
