### ISSUE TITLE
Relation mère-fille ne suit pas

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#589]
**Describe the bug**
Les nouvelles fiches 'filles' du Géoportail voient bien leur mère et soeurs. Mais la mère (série) ne propose aucune fiche fille.

**To Reproduce**
Voir http://geoportail.wallonie.be/catalogue/14084108-2c7b-4091-b62d-ff0fc235213a.html et http://geoportail.wallonie.be/catalogue/3c224b97-3949-4865-9cd3-a4d1861114f3.html
qui est une série récente où les liens ont été fait avec 
![image](https://user-images.githubusercontent.com/6093453/113849458-cf618f80-9799-11eb-8e31-9fc0d4738eaa.png) et apparaissent bien dans MW comme parent/enfant.
![image](https://user-images.githubusercontent.com/6093453/113849612-f9b34d00-9799-11eb-943d-84e79f720721.png)

Je suis en même temps un peu étonnée que ce soit le type d'initiative 'fait partie d'une même base de données' qui crée cette relation parent/enfant et non 'référence mère'. C'est normal?

Pour des séries 'historiques' cela fonctionne. http://geoportail.wallonie.be/catalogue/7451e2bd-22e8-4a74-a999-01c58b630369.html

=> bug dans le csw depuis la nouvelle manière de lier les fiches? Bugs dans la manière de lier ? Mauvaise bonne pratique de lier?

**Comment by fxprunayre** [comment]
Les historiques
http://metawal.wallonie.be/geonetwork/srv/fre/csw?request=GetRecordById&service=CSW&outputSchema=mw&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=7451e2bd-22e8-4a74-a999-01c58b630369

```xml

<gmd:MD_AggregateInformation>
<gmd:aggregateDataSetIdentifier>
<gmd:MD_Identifier>
<gmd:code>
<gco:CharacterString>2d974612-70b1-4662-a9f4-c43cbe453773</gco:CharacterString>
</gmd:code>
</gmd:MD_Identifier>
</gmd:aggregateDataSetIdentifier>
<gmd:associationType>
<gmd:DS_AssociationTypeCode codeListValue="isComposedOf"/>
</gmd:associationType>
<gmd:initiativeType>
<gmd:DS_InitiativeTypeCode codeListValue="collection"/>

```

Les nouvelles
http://metawal.wallonie.be/geonetwork/srv/fre/csw?request=GetRecordById&service=CSW&outputSchema=mw&outputFormat=application/xml&version=2.0.2&elementSetName=full&id=14084108-2c7b-4091-b62d-ff0fc235213a
par ajout en dynamique des références vers les enfants

```xml
<!-- Added from http://metawal.wallonie.be/geonetwork/srv/api/records/14084108-2c7b-4091-b62d-ff0fc235213a/related?type=associated&type=brothersAndSisters -->
<gmd:aggregationInfo>
<gmd:MD_AggregateInformation>
<gmd:aggregateDataSetIdentifier>
<gmd:MD_Identifier>
<gmd:code>
<gco:CharacterString>90e036cc-a630-436e-9277-0713ad8725d0</gco:CharacterString>
</gmd:code>
</gmd:MD_Identifier>
</gmd:aggregateDataSetIdentifier>
<gmd:associationType>
<gmd:DS_AssociationTypeCode codeListValue="crossReference"/>
```

Dans un cas isComposedOf, dans l'autre crossReference.

A voir si on adapte ça dans https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.0.x/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/present/csw/mw-full.xsl#L211-L240 ?

En lien avec https://github.com/SPW-DIG/metawal-core-geonetwork/issues/525#issuecomment-614482472

**Comment by fxprunayre** [comment]
* Vérfiier côté standard / quelle est la bonne approche ? (Vincent)
* Edition / Mise à jour des relations dans les 2 sens - mais a priori pb. Vérifier info sur la fiche associée (Francois)

* CSW / Geoportail / modifier crossReference > isComposedOf (en fonction des ccl)

**Comment by fxprunayre** [comment]
Je confirme qu'un encodage simple dans l'enfant d'une relation 
```xml
         <mri:associatedResource>
            <mri:MD_AssociatedResource>
               <mri:associationType>
                  <mri:DS_AssociationTypeCode codeList="http://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#DS_AssociationTypeCode"
                                              codeListValue="partOfSeamlessDatabase"/>
               </mri:associationType>
               <mri:initiativeType>
                  <mri:DS_InitiativeTypeCode codeList="http://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#DS_InitiativeTypeCode"
                                             codeListValue="collection"/>
               </mri:initiativeType>
               <mri:metadataReference uuidref="489a71cf-3f00-426a-a13b-c626c9fc995d"
                                      xlink:href="http://localhost:8080/geonetwork/srv/api/records/489a71cf-3f00-426a-a13b-c626c9fc995d"/>
            </mri:MD_AssociatedResource>
         </mri:associatedResource>
```

Permet une navigation dans les 2 sens dans GeoNetwork:

![image](https://user-images.githubusercontent.com/1701393/115244472-4137c280-a124-11eb-804f-b87bd97b0c46.png)


Que la relation soit
* partOfSeamlessDatabase `Part of the same structured set of data held in a computer`
* ou largerWorkCitation `Reference to a master dataset of which this one is a part`
je suis pas certain que ce soit critique - tant que c'est homogène dans le catalogue.

cf. https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.0.x/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/loc/eng/codelists.xml#L534-L590


Reste à voir si on change la version pour le géoportail de crossReference > isComposedOf ?

**Comment by vbombaerts** [comment]
Si on s'en tient à la norme, les relations série-->couches sont définies par la relation isComposedOf
Donc :
Serie A
  IsComposedOf Couche 1
  IsComposedOf Couche 2

La relation partOfSeamlessDatabase, si on omet la mention de "même ordinateur", convient je pense pour un objet qui fait partie d'un ensemble plus grand, comme c'est le cas d'une relation couche-->serie.
Donc :
Couche 1
  partOfSeamlessDatabase Serie A
Couche 2
  partOfSeamlessDatabase Serie A

C'est de cette dernière façon qu'on a encodé les relations mères/filles dans Metawal jusque là (info encodée dans la couche)

La relation largerWorkCitation pourrait aussi convenir pour déterminer les relations couche-->serie

La relation series fait référence à des données distinctes mais créées avec les mêmes spécifications ou la même méthodologie, par exemple des séries temporelles.

La relation crossReference indique un lien moins spécifique qu'une relation mère/fille et ne devrait pas être utilisée dans ce cas puisqu'il existe des valeurs plus spécifiques.

**Comment by vbombaerts** [comment]
![image](https://user-images.githubusercontent.com/6093597/115296485-4ebc6f00-a15b-11eb-97a9-9dda8791e7f8.png)
![image](https://user-images.githubusercontent.com/6093597/115306870-b88f4580-a168-11eb-94ea-1a6a15b15700.png)

**Comment by vbombaerts** [comment]
J'ai essayé de faire une visualisation des relations dans Kibana mais j'ai pas réussi. L'objet cl_associationType a l'air d'être complexe et je n'ai pas réussi à avoir un objet sur lequel faire un slice dans un piechart. Je n'ai réussi qu'à faire un [discover](http://metawal.wallonie.be/geonetwork/dashboards/app/kibana#/discover/b90ca0c0-a145-11eb-95db-4fe6be211eb9?_a=(columns:!(uuid,resourceType,cl_associationType,agg_associated,changeDate),filters:!(('$state':(store:appState),exists:(field:cl_associationType),meta:(alias:!n,disabled:!f,index:gn-records,key:cl_associationType,negate:!f,type:exists,value:exists))),index:gn-records,interval:auto,query:(language:kuery,query:''),sort:!())&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15y,to:now)))

Edit : Incroyable ! J'en rêve et vous l'avez déjà [fait en test ;-)](http://metawal4.test.wallonie.be/geonetwork/dashboards/goto/52fd58757ff82a9302399f71ea2f3f9a)

On voit (sur les fiches en test) que partOfSeamlessDatabase et crossReference sont majoritaires alors que isComposedOf n'est presque pas utilisé. Ca reflète la façon dont on avait décidé de coder ça à l'époque.
![image](https://user-images.githubusercontent.com/6093597/115307258-39e6d800-a169-11eb-8fa5-f0b7c1c14b8a.png)

(et on remarque au passage qu'on a un problème puisque la valeur "source" est utilisée sur 6% des fiches et ne fait pas partie de la codelist)

**Comment by vbombaerts** [comment]
Ma conclusion :
* pour les nouvelles fiches, ça pourrait être intéressant d'encoder la relation à partir de la série avec isComposedOf et de la pousser automatiquement vers les couches avec la relation partOfSeamlessDatabase (ou largerWorkCitation)
* pour les fiches existantes, il faut repasser sur les relations crossReference et déterminer si la relation indiquée est une relation serie-couche ou une relation d'une autre nature. Si serie-couche il faut changer en isComposedOf.
* Pour le GP : soit il adapte son code, soit on dégrade l'info pour qu'il l'interprète correctement.

**Comment by fxprunayre** [comment]
> * pour les nouvelles fiches, ça pourrait être intéressant d'encoder la relation à partir de la série avec isComposedOf et de la pousser automatiquement vers les couches avec la relation partOfSeamlessDatabase (ou largerWorkCitation)

Dans les discussions passées, on avait évoqué quelques points:
* encoder dans les 2 sens prend du temps - difficile de maintenir l'intégrité - droit d'édition sur parents et/ou enfants ...
* plutôt en faveur d'encoder dans le sens enfant > parent - raison un peu historique sans doute avec le parentIdentifier (même si pour les services on fait l'inverse)
* dynamiquement injecter la relation parent > enfant dans le CSW (l'UI de GN le gére via le service de relation) - actuellement crossReference 

De mon côté, plutôt partisan de l'encodage dans une seule direction. Et ça me semble plus simple dans les enfants.
 

> Pour le GP : soit il adapte son code, soit on dégrade l'info pour qu'il l'interprète correctement.

Est-ce qu'on peut être certain que si on change avec
* Enfant > partOfSeamlessDatabase ou largerWorkCitation > Parent
* Parent > isComposedOf > Enfant
le GP va fonctionner ?

Côté GN pour configurer quelle valeur d'initiative doit être considérée comme une relation de type enfant/parent https://github.com/geonetwork/core-geonetwork/blob/main/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl#L97.

**Comment by vbombaerts** [comment]
@vbombaerts doit décider de l'approche

**Comment by vbombaerts** [comment]
Réflexion : en tant qu'encodeur, c'est plus facile pour moi d'indiquer les relations depuis la série vers les couches. Je n'ai qu'une seule fiche à éditer. Je peux peut-être même toutes les ajouter d'un coup si je peux en ajouter plusieurs.
Mais je dois me remettre dans le bain et confronter à la pratique avant de décider. Je laisse décanter un peu...

**Comment by vbombaerts** [comment]
Le géoportail va communiquer son mapping pour juin. On y verra un peu plus clair sur ce qu'il peut interpréter ou pas. Ensuite on envisagera les modifications.

**Comment by vbombaerts** [comment]
Le GP va changer sa façon de communiquer avec MW. Pour le moment on ne change rien. On reverra ça plus tard.
