### ISSUE TITLE
Zone de recherche : elle n'est pas du tout intuitive !

### ISSUE THREAD

**Issue by metawal** [SPW-DIG/metawal-core-geonetwork#59]
La zone de recherche (à gauche sur la page d'accueil) n'est pas intuitive ni jolie.

Il faudrait, au minimum :
- ajouter un titre, genre "Rechercher dans le catalogue" (avec la même mise en forme que les deux autres titres de la page d'accueil : Dernières publications et Liens rapides)
- le premier champ (tout en-haut) ne comporte pas de titre, à quoi sert-il ?
- champ "Type de ressource" : "GéoDonnées" à remplacer par "Géodonnées", "Services" à remplacer par "Géoservices". Faire apparaitre "Applications cartographiques"
- renommer la zone "Options" en "Trier les résultats"
- par défaut, ouvrir la zone "Options" (actuellement, elle est fermée)
- supprimer l'icône "jumelles" sur le bouton "Rechercher" (ça surcharge inutilement le visuel)
- renommer "Critères avancés" par "Recherche avancée", "Recherche détaillées" ou "Autres critères de recherche"
- pour le champ "Echelle" : le comportement de ce champ est très étrange. Je supprimerais la case à cocher et afficherais directement le slider, dont les bornes seraient "ouvertes" au maximum. Si l'utilisateur change la position d'une borne, l'extérieur de la ligne d'échelle deviendrait grisé.
- Champs INSPIRE : le champ "Type de service" ne devrait pas être visible si le champ "Type de ressource" n'est pas un Service.
- etc.

Pourquoi ne pas s'inspirer du Géocatalogue français ?

**Comment by fxprunayre** [comment]
Cf https://github.com/spacebelGIS/metawal-core-geonetwork/wiki/Ergonomie-et-design-des-interfaces-Metawal

**Comment by vbombaerts** [comment]
Certaines améliorations sont demandées ici, pour la v3.0 #131

**Comment by fxprunayre** [comment]
A tester et préciser sur la v4b
