### ISSUE TITLE
Local host

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#590]
**Describe the bug**
Des références localhost:8080 sont présentes dans certaines fiches. Vu juste avant la dernière mise en prod et toujours d'actualité avec cette mise en prod.

Exemple pour http://metawal.wallonie.be/geonetwork/srv/api/records/014a4971-03f6-4da1-a8e4-aa07d428ba9e/formatters/xml?approved=true 
![image](https://user-images.githubusercontent.com/6093453/114028335-a82dbf80-9878-11eb-939e-b05de6da759e.png)

**Comment by davinciagf** [comment]
- [ ] Vérifier la présence de localhost dans la DB en test (dès mise à jour avec la db de prod)

- [ ] Préparer dans un script de migration une requête SQLRemplacer le localhost par l'url de metawal:

- Cas 1:

```sql 

UPDATE metadata 
 SET data = replace(data, 
 '<gcx:Anchor xlink:href="http://localhost:8080/geonetwork/srv/api/registries/vocabularies/external.theme.httpinspireeceuropaeumetadatacodelistSpatialScope-SpatialScope">geonetwork.thesaurus.external.theme.httpinspireeceuropaeumetadatacodelistSpatialScope-SpatialScope</gcx:Anchor>', 
 '<gcx:Anchor xlink:href="http://metawal.wallonie.be/geonetwork/srv/api/registries/vocabularies/external.theme.httpinspireeceuropaeumetadatacodelistSpatialScope-SpatialScope">geonetwork.thesaurus.external.theme.httpinspireeceuropaeumetadatacodelistSpatialScope-SpatialScope</gcx:Anchor>') 
WHERE data LIKE '%<gcx:Anchor xlink:href="http://localhost:8080/geonetwork/srv/api/registries/vocabularies/external.theme.httpinspireeceuropaeumetadatacodelistSpatialScope-SpatialScope">geonetwork.thesaurus.external.theme.httpinspireeceuropaeumetadatacodelistSpatialScope-SpatialScope</gcx:Anchor>%';
```

Ce cas représenterait 69 fiches en test au 20 avril 2021

**Comment by davinciagf** [comment]
@vbombaerts @mawibrin : News relatives à la synchro de la DB ?

**Comment by vbombaerts** [comment]
@davinciagf La demande est toujours bloquée car Metawal contiendrait des données sensibles au sens RGPD. J'essaie de retracer l'historique de cette classification et je tente de trouver une solution (anonymisation des données ?)

**Comment by fxprunayre** [comment]
La requête ne présente pas bien de risque. Je propose qu'on la joue en prod histoire de cloturer le sujet?

**Comment by davinciagf** [comment]
Adapter la migration et inclure https #565

**Comment by vbombaerts** [comment]
Requête non jouée en valid

**Comment by vbombaerts** [comment]
Vérifié via CSW sur les 250 premières fiches en valid --> OK.

**Comment by vbombaerts** [comment]
Vérifié par coups de sonde CSW sur des fiches en prod--> OK.
