### ISSUE TITLE
Ressources associées, problème de lien à la création

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#591]
_Remise en contexte :
Pour des fiches éditées depuis un portail de Metawal et non depuis Metawal directement, le postprocessing INSPIRE n'ajoute pas le formatteur ISO 19139 aux adresses des fiches de données liées à un service._ voir #583 

Le correctif a permis une mise à jour au niveau de l’existant (ressources déjà associées) mais pas pour les nouvelles associations. => nouveau ticket pour corriger lors des mises à jour ET il faudra refaire tourner les routines pour les fiches créées/adaptées lors de la prochaine mise en prod.

2 ressources associées ont été ajoutées à la fiche de métadonnée d’un service (afe6407c-125d-4ab8-9dcc-216ac848dad1) pour vérifier si les nouvelles associations ont bien le /formatters/iso19139?output=xml par défaut. Cela a été fait par Domnique depuis http://metawal.wallonie.be/geonetwork/inspire/fre

<srv:operatesOn uuidref="eed22735-0947-4e2d-8de9-b9cfbf492c80" xlink:href="http://metawal.wallonie.be/geonetwork/srv/api/records/eed22735-0947-4e2d-8de9-b9cfbf492c80/formatters/iso19139?output=xml"/>

<srv:operatesOn uuidref="938c92ef-9fcc-495f-9f48-dcec19ec7cc8" xlink:href="http://metawal.wallonie.be/geonetwork/srv/api/records/938c92ef-9fcc-495f-9f48-dcec19ec7cc8/formatters/iso19139?output=xml"/>

<srv:operatesOn uuidref="ff71a317-fc05-4d0d-b30b-58a1740eb314" xlink:href="http://metawal.wallonie.be/geonetwork/srv/api/records/ff71a317-fc05-4d0d-b30b-58a1740eb314/formatters/iso19139?output=xml"/>

<srv:operatesOn uuidref="3dc91d81-338f-425d-b27b-f62aa0464e21" xlink:href="http://metawal.wallonie.be/geonetwork/inspire/api/records/3dc91d81-338f-425d-b27b-f62aa0464e21"/>

<srv:operatesOn uuidref="70c5ee8d-1554-468b-b5d4-7c976b046894" xlink:href="http://metawal.wallonie.be/geonetwork/inspire/api/records/70c5ee8d-1554-468b-b5d4-7c976b046894"/>

_Originally posted by @mawibrin in https://github.com/SPW-DIG/metawal-core-geonetwork/issues/583#issuecomment-815619752_

**Comment by fxprunayre** [comment]
Ca se fait automatiquement par https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.0.x/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/present/csw/gmd-inspire-postprocessing.xsl#L27-L30 si l'URL est du type http://metawal.wallonie.be/geonetwork/**srv/api/records**/70c5ee8d-1554-468b-b5d4-7c976b046894 INSPIRE obtiendra une URL avec le formatter ISO19139.

**Comment by fxprunayre** [comment]
Fixed. A déployer et tester.

**Comment by davinciagf** [comment]
Déploé et testé sur http://metawal4.test.wallonie.be/geonetwork/inspire/fre/csw?service=CSW&request=GetRecordById&version=2.0.2&outputSchema=http://www.isotc211.org/2005/gmd&elementSetName=full&id=a39af4c6-c06e-4d9d-8121-b0c7717eea1a

**Comment by vbombaerts** [comment]
OK.
Testé sur l'opération GetRecords + contrainte 
`http://metawal4.test.wallonie.be/geonetwork/inspire/fre/csw?request=GetRecords&service=CSW&version=2.0.2&resultType=results&typeNames=gmd:MD_Metadata&&ElementSetName=full&outputSchema=http%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd&constraint=identifier+%3D+%2741f06f9d-bcce-4e7d-b215-8e0e566e794a%27&constraintLanguage=CQL_TEXT&constraint_language_version=1.1.0`

et sur l'opération GetRecordbyId
`http://metawal4.test.wallonie.be/geonetwork/inspire/fre/csw?service=CSW&request=GetRecordById&version=2.0.2&outputSchema=http://www.isotc211.org/2005/gmd&elementSetName=full&id=41f06f9d-bcce-4e7d-b215-8e0e566e794a`

**Comment by vbombaerts** [comment]
En valid

GetRecordbyID - OK
`http://metawal4.valid.wallonie.be/geonetwork/inspire/fre/csw?service=CSW&request=GetRecordById&version=2.0.2&outputSchema=http://www.isotc211.org/2005/gmd&elementSetName=full&id=b234103d-df4a-42e5-81a6-9c9965c5b365`

GetRecords - OK
`http://metawal4.valid.wallonie.be/geonetwork/inspire/fre/csw?request=GetRecords&service=CSW&version=2.0.2&resultType=results&typeNames=gmd:MD_Metadata&&ElementSetName=full&outputSchema=http%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd&constraint=identifier+%3D+%27b234103d-df4a-42e5-81a6-9c9965c5b365%27&constraintLanguage=CQL_TEXT&constraint_language_version=1.1.0`
