### ISSUE TITLE
GN-UI / Embarquer dans Jahia

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#592]
A tester si on peut mettre 

```xml
  <div style="display: flex;">
  <div style="flex: 67%;">
   <gn-results-list layout="CARD" api-url="https://apps.titellus.net/geonetwork/srv/api" query="+tag.default:IDP*"></gn-results-list>
  </div>
  <div style="flex: 33%;">
   <gn-facets api-url="https://apps.titellus.net/geonetwork/srv/api" facet-config='{
                            "creationYearForResource": {
                              "histogram": {
                                "field": "creationYearForResource",
                                "interval": 5,
                                "keyed" : true,
                                "min_doc_count": 1}},
                           "resourceType":{"terms":{
                              "field":"resourceType",
                              "size": 10}}}'></gn-facets>
  </div>
  </div>

  <script src="https://geonetwork.github.io/geonetwork-ui/master/demo/webcomponents/gn-wc.js"></script>
```
Dans une page Jahia ?

**Comment by davinciagf** [comment]
https://geoportail.test.wallonie.be/cms/render/default/fr/sites/geoportail/mw---test-agf-web-component.html

![Screen Shot 2021-04-20 at 12 35 28](https://user-images.githubusercontent.com/576292/115382486-0b064b80-a1d5-11eb-831d-879c0215ebdf.png)

Interaction entre filtre et résultats:
![Screen Shot 2021-04-20 at 12 35 52](https://user-images.githubusercontent.com/576292/115382468-06da2e00-a1d5-11eb-8c88-0d110666f0c7.png)

**Comment by vbombaerts** [comment]
Y a plus qu'à faire la même chose avec Metawal ;-)

**Comment by fxprunayre** [comment]
> Y a plus qu'à faire la même chose avec Metawal ;-)

A priori en changeant apps.titellus.net par metawal4.test... ca devrait être bon.

**Comment by mawibrin** [comment]
Chez moi la page du géoportail test ne donne pas l'intégration mais un message restant sur 'loading'. Sur l'intranet jahia j'ai la même chose avec l'intégration du site titellus ou metawal4.test.
En attaquant directement dans chrome https://apps.titellus.net/geonetwork/srv/api ou l'équivalent metawal4.test je reçois des erreurs 403, accès denied.
Vincent tu arrivais à voir la page correctement? Ce serait un problème du réseau SPW?

**Comment by mawibrin** [comment]
Maintenant j'arrive à intégrer le code de François et vois bien le résultat sur l'intranet. Mais ca ne va pas pour metawal4.test., il reste sur chargement. Les urls ne sont pas bonnes ? J'ai mis deux fois http://metawal4.test.wallonie.be à la place de https://apps.titellus.net le reste étant identique. Ou ce serait un autre problème?
gn-results-list layout="CARD" api-url="http://metawal4.test.wallonie.be/geonetwork/srv/api" query="+tag.default:IDP*">
...
gn-facets api-url=" http://metawal4.test.wallonie.be/geonetwork/srv/api" facet-config='{

**Comment by davinciagf** [comment]
Il peut y avoir des erreurs liées au proxy et CORS comme on est sans doute sur le même domaine.

**Comment by davinciagf** [comment]
On peut utiliser l'adresse de metawal4.test.
Exemple simple page html
![Screen Shot 2021-04-27 at 18 32 34](https://user-images.githubusercontent.com/576292/116279300-a7a58c00-a787-11eb-87ff-8817b5a81f32.png)

Ne pas oublier de modifier le filtre de recherche par rapport à l'exemple en début de ticket. 

Adaptation pour le panier de téléchargement : query="+tag.default:PanierTelechargementGeoportail*"

```xml
<div style="display: flex;"><div style="flex: 67%;">
<gn-results-list layout="CARD" api-url="http://metawal4.test.wallonie.be/geonetwork/srv/api" query="+tag.default:PanierTelechargementGeoportail*">
</gn-results-list></div><div style="flex: 33%;"><gn-facets api-url="http://metawal4.test.wallonie.be/geonetwork/srv/api" facet-config='{
                            "creationYearForResource": {
                              "histogram": {
                                "field": "creationYearForResource",
                                "interval": 5,
                                "keyed" : true,
                                "min_doc_count": 1}},
                           "resourceType":{"terms":{
                              "field":"resourceType",
                              "size": 10}}}'></gn-facets></div>
</div>
<script src="https://geonetwork.github.io/geonetwork-ui/master/demo/webcomponents/gn-wc.js"></script>
```


Au niveau du géoportail, ce sont les requête en serveur http et https qui posent problèmes

![Screen Shot 2021-04-27 at 18 36 23](https://user-images.githubusercontent.com/576292/116279598-02d77e80-a788-11eb-9e14-9ac2afe49a77.png)
Il y a moyen de contourner ce soucis en allant dans la config de chrome pour les contenus non securisé.

![Screen Shot 2021-04-27 at 18 54 39](https://user-images.githubusercontent.com/576292/116281533-1a176b80-a78a-11eb-892a-1487976aff04.png)

Ce qui donne pour https://geoportail.test.wallonie.be/cms/render/default/fr/sites/geoportail/mw---test-agf-web-component/mw---test-agf-web-component-mw.html

![Screen Shot 2021-04-27 at 18 57 26](https://user-images.githubusercontent.com/576292/116281927-7f6b5c80-a78a-11eb-8d16-83e08adaeb2a.png)

**Comment by vbombaerts** [comment]
Test concluant.

- [ ] Il faut maintenant définir le rendu qu'on souhaite. Je propose qu'on fasse un test grandeur nature dont l'objectif serait de remplacer ou compléter la page dédiée au ressources intranet - @mawibrin - tu en penses quoi ? tu peux prendre le lead sur la définition du besoin ? 

- [ ] Il faut aussi résoudre cette histoire de https. Cf https://github.com/SPW-DIG/metawal-core-geonetwork/issues/565

**Comment by fxprunayre** [comment]
> la page dédiée au ressources intranet

On peut avoir un écran de l'intranet pour avoir une idée du rendu/contenu ?

**Comment by vbombaerts** [comment]
Voici une idée de ce qui existe actuellement. L'idée n'est pas de répliquer tel quel ce qui existe mais d'avoir accès au minimum à une vue tabulaire reprenant les informations clés pour l'utilisateur interne. Avec possibilité de quelques filtres et de classement. C'est @mawibrin qui gère l'intranet géomatique. Le tableau est créé et tenu à jour à la main.

La page intranet géomatique donne accès en lien à d'autres inventaires de données accessibles en intranet, eux aussi tenus à la main.

![image](https://user-images.githubusercontent.com/6093597/118669825-5cb2ed80-b7f6-11eb-8b28-11193bfca8e2.png)
![image](https://user-images.githubusercontent.com/6093597/118670003-8835d800-b7f6-11eb-99c4-b748454d2360.png)

Inventaire DGO3 - vue alphabétique
![image](https://user-images.githubusercontent.com/6093597/118670515-fb3f4e80-b7f6-11eb-8973-73331f408511.png)

Inventaire DGO3 - vue par thématique
![image](https://user-images.githubusercontent.com/6093597/118670773-3477be80-b7f7-11eb-8d49-713f6edd3c3c.png)
![image](https://user-images.githubusercontent.com/6093597/118670857-45c0cb00-b7f7-11eb-823d-403e30e59971.png)

**Comment by davinciagf** [comment]
Merci - @fxprunayre un petit mockup ;) .

**Comment by davinciagf** [comment]
Est-il possible de
-  décrire les liens (notamment colonne MTD avec plusieurs références semble-t-il) ?
- décrire le mapping des thématiques de la DGO3 (pas de correspondance avec le thesaurus hiérarchiques des thèmes de la RW )?

**Comment by vbombaerts** [comment]
L’utilisateur souhaite avoir des fonctionnalités semblables à celles d’un tableau Excel : masquer des champs, filtrer et ordonner selon les valeurs des champs, sélectionner et exporter. Il souhaite également avoir la possibilité d’accéder à la fiche complète de la ressource.

**Comment by vbombaerts** [comment]
Au niveau des champs à afficher je dirais, nom, nom court, gestionnaire (abrégé), classement GP, lien vers la fiche complète, Service visualisation, emplacement BD (on mettra cette info en "withheld" dans la distribution, je dois encore voir quelles conventions on utilisera), modèle, légende.

Les idées là derrière sont :
1. de mettre en place un sous-portail/point d'accès spécifique car il y aura un mélange de fiches publiées et non publiées (publiées uniquement pour le groupe-cible intranet) et de champs publiés ou non (attribut withheld) - à travers le sous-portail tout le contenu autorisé au groupe intranet sera visible
2. mettre en place le tableau avec les champs définis ci-dessus (en première approche - à valider avec les utilisateurs) - Comme la liste est longue le tableau sera trop large. Donc je voudrais que l'utilisateur puisse choisir d'afficher/masquer les champs qui ont un intérêt pour lui.
3. possibilité de filtrage et de tri des valeurs dans chaque colonne
4. possibilité de sélectionner les fiches (coche devant chaque ligne + option sélectionner/déselectionner tout/tout le visible)
5. Export de la sélection vers csv

Le composant devrait être générique parce que j'envisage de répéter cette configuration (sous-portail + composant tableau intégré dans une page web) avec d'autres cas : données non-géographiques, INSPIRE, applications...

**Comment by vbombaerts** [comment]
Restera à voir comment on gère les liens hiérarchiques (série/donnée).

**Comment by fxprunayre** [comment]
Un autre exemple de tableau "plus complexe" https://land.copernicus.eu/product-portfolio/overview

**Comment by davinciagf** [comment]
Premier draft d'intégration d'un tableau au sein de jahia:
![image](https://user-images.githubusercontent.com/576292/145192337-20a038d2-cb79-437a-b412-fd14b7dd5781.png)

Points d'améliorations (point de vue du web composant)

- [ ] Gestion de la mise à jour de la recherche sur base de la pagination :

  - [ ] pas d'update des résultats si le tableau ne dispose pas de scroll (example où la pagination est mise à 2, le tableau ne se met pas à jour pour présenté les résultats après les deux premiers résultats....)
  - [ ] l'apport de nouveau résultats (suite aux règles de pagination) replace la vue en début de tableau

- [ ] Les éléments  "icones" ne sont pas chargés correctement (erreur dans l'url - voir build du composants)

**Comment by vbombaerts** [comment]
Deuxième draft, pour base de discussion avec la gestionnaire des tableaux intranet

https://geoportail.test.wallonie.be/home/produire-et-publier/mw---test-agf-web-component/test-webcomponents-vincent.html

![image](https://user-images.githubusercontent.com/6093597/149417193-a1f36bef-28a5-46f2-a96a-c06251fe3f96.png)

**Comment by vbombaerts** [comment]
Pistes d'amélioration :
### Config :
* [ ] pouvoir se brancher sur un portail
* [ ] pouvoir définir un champ qui sert pour le tri par défaut

### Infos manquantes
* [ ] Différenciation des liens par type de contenu : lien ESRI-REST, lien WMS, INSPIRE-view, INSPIRE-download, Localisation BD interne, légende, modèle de données, rapport de qualité/conformité, lien fiche MD (géoportail/Metawal à décider), lien WalOnMap... - sera utile aussi pour le mapping géoportail - VBO doit définir tous les types encodés actuellement. 
* [ ] Nom technique (= identifiant local)

### Rendu
* [ ] Icône ou texte fixe cliquable pour les liens typés - plus compact que l'adresse
* [ ] Dans Edge, le tableau dépasse la largeur de la page car les adresses web s'affichent en une seule ligne. Firefox OK. Chrome pas testé.

**Comment by vbombaerts** [comment]
Sur base de cette première version on a mieux défini un des use case #700

**Comment by vbombaerts** [comment]
Deuxième use case #715

**Comment by vbombaerts** [comment]
Troisième use case #702

**Comment by vbombaerts** [comment]
Les webcomponents permettent de répondre au besoin. Voir les différents use cases définis.
