### ISSUE TITLE
[Traduction ISO 19115 - 19139] - Status

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#594]
Lors de la traduction ISO 19115 vers ISO 19139, si on a indiqué plusieurs statuts (obsolète et remplacé par exemple), ils apparaissent tous dans la même balise

En 19115
`         <mri:status>
            <mcc:MD_ProgressCode codeList="http://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#MD_ProgressCode"
                                 codeListValue="obsolete"/>
         </mri:status>
         <mri:status>
            <mcc:MD_ProgressCode codeList="http://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#MD_ProgressCode"
                                 codeListValue="superseded"/>
         </mri:status>`

En 19139
`      <gmd:status>
        <gmd:MD_ProgressCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_ProgressCode" codeListValue="obsolete superseded">obsolete superseded</gmd:MD_ProgressCode>
      </gmd:status>`

[Lien vers la fiche](http://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/d3d387ff-ff17-4307-93fc-749174bfe215
)

**Expected behavior**
Comme en ISO 19115, le statut en ISO 19139 autorise plusieurs occurences.
La traduction doit créer plusieurs occurences.
![image](https://user-images.githubusercontent.com/6093597/117003357-0d909700-ace5-11eb-9ac4-4709cc192a39.png)

**Comment by fxprunayre** [comment]
* TC211 ref https://github.com/ISO-TC211/XML/pull/216
* GN ref https://github.com/geonetwork/core-geonetwork/pull/5647

**Comment by fxprunayre** [comment]
A déployer pour test.

**Comment by fxprunayre** [comment]
Semble ok en test. cf. http://metawal4.test.wallonie.be/geonetwork/srv/api/records/d3d387ff-ff17-4307-93fc-749174bfe215/formatters/iso19139?output=xml

**Comment by vbombaerts** [comment]
OK en valid;

[http://metawal4.valid.wallonie.be/geonetwork/srv/api/records/1ee5b57f-0c46-49de-83db-01610da25751/formatters/iso19139?output=xml](http://metawal4.valid.wallonie.be/geonetwork/srv/api/records/1ee5b57f-0c46-49de-83db-01610da25751/formatters/iso19139?output=xml)

**Comment by vbombaerts** [comment]
OK prod 
[http://metawal.wallonie.be/geonetwork/srv/api/records/d3d387ff-ff17-4307-93fc-749174bfe215/formatters/xml?approved=true](http://metawal.wallonie.be/geonetwork/srv/api/records/d3d387ff-ff17-4307-93fc-749174bfe215/formatters/xml?approved=true)
