### ISSUE TITLE
[Traduction ISO 19115 - 19139] Online ressource

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#595]
Une ressource en ligne présente dans un section autre que distribution (par exemple un rapport de qualité dans la section lineage) ne remonte pas dans l'ISO 19139 si aucune ressource en ligne n'est présente dans la section distribution.

Exemple : le rapport de production dans la section qualité (rechercher "addendum")

[Fiche sans ressource en ligne dans la section distribution](http://metawal4.test.wallonie.be/geonetwork/srv/api/records/b3b6246e-c228-4685-b8af-d12d5cbb78ec/formatters/iso19139?output=xml)

[Fiche avec dummy ressource dans la section distribution](http://metawal4.test.wallonie.be/geonetwork/srv/api/records/904ff01c-1f55-4bd8-8f80-f92f9c3234fa/formatters/iso19139?output=xml)

**Comment by fxprunayre** [comment]
Ca vient de https://github.com/geonetwork/core-geonetwork/blob/main/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/convert/ISO19139/toISO19139.xsl#L323-L327. 

Ca arrive souvent une fiche sans ressource en ligne dans distribution ? C'est pas forcément simple, car après faut vérifier les multiples cas possibles ... Est-ce qu'on ajoute un nouveau bloc distribution pour ces liens là (au lieu de tenter de les insérer dans un bloc existant) ? Ca posera pas de pb côté geoportail ?

**Comment by davinciagf** [comment]
Il me semble que l'on a déjà eu des soucis de gestion au niveau du Géoportail avec la présence de plusieurs blocs distribution.

**Comment by vbombaerts** [comment]
> Ca arrive souvent une fiche sans ressource en ligne dans distribution ? 

Ce n'est pas fréquent mais je vois quand même les cas suivants :
- Une donnée déclassée : on coupe tous les liens de distribution, on garde les documents associés.
- Une donnée non-distribuée en externe : on n'indique aucun lien de distribution, on garde les documents associés. 
- (plus rare) Une donnée pour laquelle on n'a pas encore défini la politique de distribution.

**Comment by vbombaerts** [comment]
Pour la donnée en exemple, j'ai contourné en mentionnant 2 fois les rapports : dans la section distribution et dans la section généalogie. C'est pas bcp plus de travail, mais il faut penser à le faire.

**Comment by fxprunayre** [comment]
> Ce n'est pas fréquent mais je vois quand même les cas suivants :

Du coup je regarde comment faire mieux ? ou on se dit que le moissonnage ISO19139 du geoportail est bientôt une histoire ancienne ;)

**Comment by vbombaerts** [comment]
Suite à un discussion avec Samuel, il va demander au prestatire GP de faire un état des lieux sur les liens GP-MW. L'objectif est d'avoir une vision claire de la correspondance pour chaque champ. Il leur a demandé ça pour début juin, afin qu'on puisse ensuite définir les évolutions (passer le GP sur ISO 19115-3 ou adapter le traducteur MW).

**Comment by vbombaerts** [comment]
On va changer la façon de travailler entre le GP et MW. On peut laisser comme ça.
