### ISSUE TITLE
Search / Facet / Contact SPW / Tree view

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#596]
Les contacts SPW sont encodés avec "Direction de la Prévention des Pollutions (SPW - DGO3 - DEE - DPP)".

- [x] Extraire la partie entre parenthèse "SPW - DGO3 - DEE - DPP" dans un champ de l'index.

![image](https://user-images.githubusercontent.com/1701393/117153323-23708b80-adbb-11eb-8c83-a98e8f6b49c0.png)

- [x] Index all levels to obtain the count on each tree nodes

![image](https://user-images.githubusercontent.com/1701393/117157143-a1826180-adbe-11eb-89b0-9b896e6e1544.png)

- [x] Faire une facette dessus 
- [x] Sous forme d'arbre (Related fix https://github.com/geonetwork/core-geonetwork/pull/5654)

![image](https://user-images.githubusercontent.com/1701393/117160818-b9a7b000-adc1-11eb-8b7e-9ccd171e294e.png)

Configuration

```json
            "custodianOrgForResource_tree": {
              "terms": {
                "field": "custodianOrgForResource_tree",
                "include": "SPW.*",
                "size": 100,
                "order" : { "_key" : "asc" }
              },
              "meta": {
                "treeKeySeparator": " - "
              }
            },
```

**Comment by fxprunayre** [comment]
@vbombaerts donc est-ce que ca te va ? ca permet de voir ce qui n'entre pas dans le moule :)

On aurait donc 2 facettes :
* Gestionnaire de données SPW - sous forme d'arbre
* Gestionnaire de données - tout les organismes qui ne contiennent pas SPW

![image](https://user-images.githubusercontent.com/1701393/117161087-f07dc600-adc1-11eb-8afa-1f6d396f1ed5.png)

**Comment by fxprunayre** [comment]
A tester sur test.

**Comment by vbombaerts** [comment]
Facette OK.
Visualisation Kibana en attente de résolution du problème d'index (env de test). 

![image](https://user-images.githubusercontent.com/6093597/117663793-593db780-b1a1-11eb-9922-1623b01cab64.png)

J'ai rafraichi l'index mais l'erreur persiste.

![image](https://user-images.githubusercontent.com/6093597/117663871-6bb7f100-b1a1-11eb-828c-b72cfae4c278.png)

**Comment by vbombaerts** [comment]
Lien vers Kibana a disparu en test
![image](https://user-images.githubusercontent.com/6093597/120560739-8e85a000-c403-11eb-823c-2a46406c84ef.png)

**Comment by fxprunayre** [comment]
> Lien vers Kibana a disparu en test

En test, y'a des pb de connexions https avec Kibana
![image](https://user-images.githubusercontent.com/1701393/120612205-3d060100-c455-11eb-8b45-2be4e964fe51.png)

Donc il n'affiche pas le lien. Mais c'est bizarre car https://metawal4.test.wallonie.be/geonetwork/dashboards fonctionne. J'ai amélioré le HealthCheck https://github.com/geonetwork/core-geonetwork/pull/5725 mais ca ne résoudra sans doute pas le pb de HTTPs.

@davinciagf A déployer pour voir.

**Comment by davinciagf** [comment]
MW4 test a été redéployé et le correctif permet bien l'accès à kibana.

![Screen Shot 2021-06-03 at 12 11 33](https://user-images.githubusercontent.com/576292/120628547-18b22080-c465-11eb-97dc-82552718eb14.png)

**Comment by vbombaerts** [comment]
Testing env. valid :

- [x] Recherche : J'ai du ajouter la facette en valid, mais elle est fonctionnelle.

- [ ] Kibana : Erreur de chargement de l'index

```
Error
    at Fetch._callee3$ (http://metawal4.valid.wallonie.be/geonetwork/dashboards/bundles/commons.bundle.js:3:4001197)
    at l (http://metawal4.valid.wallonie.be/geonetwork/dashboards/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:288:970406)
    at Generator._invoke (http://metawal4.valid.wallonie.be/geonetwork/dashboards/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:288:970159)
    at Generator.forEach.e.<computed> [as next] (http://metawal4.valid.wallonie.be/geonetwork/dashboards/bundles/kbn-ui-shared-deps/kbn-ui-shared-deps.js:288:970763)
    at asyncGeneratorStep (http://metawal4.valid.wallonie.be/geonetwork/dashboards/bundles/commons.bundle.js:3:3994720)
    at _next (http://metawal4.valid.wallonie.be/geonetwork/dashboards/bundles/commons.bundle.js:3:3995031)
```

Testing env. test : pas possible car dans les choux

**Comment by vbombaerts** [comment]
Toujours une erreur au niveau du chargement de l'index dans Kibana

![image](https://user-images.githubusercontent.com/6093597/121691313-2ac83a80-cac7-11eb-9ba6-dd042fa8bab2.png)

**Comment by davinciagf** [comment]
L'index pattern a bien été créé suite à la mise à jour, par contre on a perdu tous les dashboards et les visualisations.
A récupérer depuis la prod ou package de sauvegarde.

**Comment by davinciagf** [comment]
L'id de l'index pattern a changé! 

Si les visualisations et dashboards ne sont pas fonctionnels, il est nécessaire après création de l'index pattern d'exporter ce dernier pour édition et de modifier son id ( voir fin du fichier) et ensuite de le réimporter. 

`.... "id":"gn-records","migrationVersion":{"index-pattern":"7.6.0"},"references":[],"type":"index-pattern","updated_at":"2021-06-11T13:37:19.162Z","version":"WzI0NzUsMl0="}`

L'indice pattern utilisé au niveau des visualisations en valid est 'gn-records'. 

Pour retrouver l'id de l'index pattern, ce dernier est référencé au niveau des objets de visualisations (import via saved objects de kibana) au niveau de l'élément reference: 

**"references":[{"id":"gn-records","name":"kibanaSavedObjectMeta.searchSourceJSON.index","type":"index-pattern"}]**

Exemple:
`{"attributes":{"description":"","kibanaSavedObjectMeta":{"searchSourceJSON":"{\"indexRefName\":\"kibanaSavedObjectMeta.searchSourceJSON.index\"}"},"title":"AGF_TEST - Resources (codelist_resourceScope_text)","uiStateJSON":"{}","version":1,"visState":"{\"title\":\"AGF_TEST - Resources (codelist_resourceScope_text)\",\"type\":\"pie\",\"params\":{\"type\":\"pie\",\"addTooltip\":true,\"addLegend\":true,\"legendPosition\":\"right\",\"isDonut\":true,\"labels\":{\"show\":true,\"values\":true,\"last_level\":true,\"truncate\":100},\"dimensions\":{\"metric\":{\"accessor\":1,\"format\":{\"id\":\"number\"},\"params\":{},\"label\":\"Count\",\"aggType\":\"count\"},\"buckets\":[{\"accessor\":0,\"format\":{\"id\":\"terms\",\"params\":{\"id\":\"string\",\"otherBucketLabel\":\"Other\",\"missingBucketLabel\":\"Missing\",\"parsedUrl\":{\"origin\":\"http://metawal4.test.wallonie.be\",\"pathname\":\"/geonetwork/dashboards/app/kibana\",\"basePath\":\"/geonetwork/dashboards\"}}},\"params\":{},\"label\":\"codelist_resourceScope_text: Descending\",\"aggType\":\"terms\"}]}},\"aggs\":[{\"id\":\"1\",\"enabled\":true,\"type\":\"count\",\"schema\":\"metric\",\"params\":{}},{\"id\":\"2\",\"enabled\":true,\"type\":\"terms\",\"schema\":\"segment\",\"params\":{\"field\":\"codelist_resourceScope_text\",\"orderBy\":\"1\",\"order\":\"desc\",\"size\":8,\"otherBucket\":false,\"otherBucketLabel\":\"Other\",\"missingBucket\":false,\"missingBucketLabel\":\"Missing\"}}]}"},"id":"4461bfb0-bd0e-11ea-b72a-332c9d0b89ee","migrationVersion":{"visualization":"7.7.0"},"references":[{"id":"gn-records","name":"kibanaSavedObjectMeta.searchSourceJSON.index","type":"index-pattern"}],"type":"visualization","updated_at":"2020-08-28T12:15:24.112Z","version":"WzU1LDFd"}`

**Comment by vbombaerts** [comment]
Kibana OK en valid. 👍
