### ISSUE TITLE
La création de "Rapport" ne fonctionne pas

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#599]
**Describe the bug**
J'ai essayé de savoir quelles fiches ont été modifiées entre le 15 et le 21 avril 2021. J'ai pour ça demandé un rapport et son contenu était vide.

**Comment by fxprunayre** [comment]
```
[WARNING] /geonetwork/srv/api/reports/metadataupdated
 Not implemented in ES
```

Je regarde si c'est compliqué à recabler.

**Comment by fxprunayre** [comment]
cf. https://github.com/geonetwork/core-geonetwork/pull/5683

**Comment by davinciagf** [comment]
Ok je déploie demain.

**Comment by fxprunayre** [comment]
A déployer @davinciagf

**Comment by vbombaerts** [comment]
Env. Valid :

- Création de rapport OK. 
- Par contre, dans le rapport on ne récupère que la date de création de la fiche, pas la date de dernière mise à jour. Il faudrait les deux.


Metadata ID | Metadata Title | Metadata Create date | Owner Username | Owner Surname | Owner Name | Owner Email | Group Owner | Group Owner   Email
-- | -- | -- | -- | -- | -- | -- | -- | --










Note : tester tous les types de rapport en prod pcq en valid seul le rapport "Fiches mises à jour" contenait des résultats.

**Comment by vbombaerts** [comment]
Travaux en lien dans un autre projet ==> report à version ultérieure pour bénéficier des améliorations

**Comment by fxprunayre** [comment]
> * Par contre, dans le rapport on ne récupère que la date de création de la fiche, pas la date de dernière mise à jour. Il faudrait les deux.

https://github.com/titellus/core-geonetwork/pull/32

A déployer.

**Comment by davinciagf** [comment]
![image](https://user-images.githubusercontent.com/576292/133232574-804648df-8501-4584-aea0-cb473d28abc2.png)

**Comment by vbombaerts** [comment]
OK, mais qui édite des fiches en plein milieu de la nuit ?

Metadata Updated |   |   |   |  
-- | -- | -- | -- | --
  |   |   |   |  
Metadata ID | Metadata Title | Metadata Create date | Last update | Owner Username
c34743fa-7c50-4bfe-b587-e1253ff68eae | Ouvrages d'art régionaux gérés par le SPW | 2020-04-06T08:50:41Z | 2021-09-14T01:00:54Z | Admin_Metawal
91721175-5f01-410c-8c78-37c1d1893ba2 | Les offres touristiques en Wallonie | 2020-06-10T09:23:58Z | 2021-09-14T02:03:35Z | Admin_Metawal
8f29c89a-ed56-4ae7-b0eb-af4cd2766b57 | Donnée test miltilingue | 2021-09-14T11:12:03.455Z | 2021-09-14T11:16:49.255Z | vbombaerts_admin



</body>

</html>
