### ISSUE TITLE
IE 8 problème connexion 

### ISSUE THREAD

**Issue by metawal** [SPW-DIG/metawal-core-geonetwork#6]

**Comment by fxprunayre** [comment]
Sounds related to http://stackoverflow.com/questions/12779491/is-the-css-target-selector-supported-in-ie9-in-spite-of-w3schools-saying-its-n ":target" not supported on IE8

**Comment by vbombaerts** [comment]
Ne fonctionne pas chez moi. Problème non prioritaire : firefox fait désormais partie des standards SPW.

**Comment by davinciagf** [comment]
Pourrais-tu préciser ce qui ne fonctionne pas (button connexion, fenêtre,..) car en mode compatible IE8 cela fonctionne chez moi ?
![login1](https://f.cloud.github.com/assets/576292/1993937/9738eb24-84e3-11e3-8703-b3cb116751e0.PNG)
![login2](https://f.cloud.github.com/assets/576292/1993945/ae0f9960-84e3-11e3-973f-7bb165f9de3c.PNG)

**Comment by fxprunayre** [comment]
Dans metawal-4, ajouter un message d'avertissement pour IE8.
