### ISSUE TITLE
Recherche / Améliorer le calcul de pertinence - eg. PICC

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#60]
Renvoie en premier la donnée ERRUISSOL - MNT puis seulement la donnée PICC.
Or, la chaine PICC est texto dans les titres alternatifs de la donnée PICC.

**Comment by fxprunayre** [comment]
![image](https://f.cloud.github.com/assets/1701393/1748073/b3322be2-649a-11e3-8d40-60309dc736dc.png)

> Or, la chaine PICC est texto dans les titres alternatifs de la donnée PICC.

Le calcul de pertinence est fait en fonction de la fréquence des termes dans la fiche trouvée et les occurences dans l'index. Dans notre, cas la généalogie d'Erruissol parle bcp de PICC ce qui impact probablement le classement.

**Comment by vbombaerts** [comment]
Les séries devraient apparaitre avant leurs membres dans les résultats de recherche par pertinence.
