### ISSUE TITLE
Le filtre sur la date d'édition de la fiche ne fonctionne pas

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#600]
**Describe the bug**
J'ai essayé de filtrer le contenu du catalogue sur base de la date d'édition de la fiche et ça n'a pas filtré. (peut-être en lien avec le bug sur la création de rapport ?) #599

**Comment by fxprunayre** [comment]
Tu as filtré où ?

Avec ce genre d'expression dans la recherche ca marche
```
q(+dateStamp:"2020-07-27T15:23:49.000Z")
q(+dateStamp:[2020-07 TO 2020-09})
```

**Comment by vbombaerts** [comment]
Dans la section contribuer, tout en bas à gauche
![image](https://user-images.githubusercontent.com/6093597/118663829-4bb3ad80-b7f1-11eb-9fa1-8fb05d3a19e6.png)

**Comment by fxprunayre** [comment]
C'est pas encore parfait, mais ce sera mieux. A déployer.

**Comment by vbombaerts** [comment]
En valid :
Fonctionnel mais avec un petit bug : la date du filtre est décalée d'un jour par rapport à la date choisie
![image](https://user-images.githubusercontent.com/6093597/121415684-4ec13a00-c968-11eb-8b15-dad5d2303e53.png)


![image](https://user-images.githubusercontent.com/6093597/121415924-862fe680-c968-11eb-915d-babb2e9dc74a.png)

**Comment by fxprunayre** [comment]
> la date du filtre est décalée d'un jour par rapport à la date choisie

Non, elle est en Zulu time, donc CET-2h actuellement. 
Ce serait un truc à améliorer - ne pas afficher les heures dans ce cas peut être.
Y'a aussi des améliorations en cours quand on a une sélection des années uniquement https://github.com/geonetwork/core-geonetwork/pull/5727 
On le garde pour plus tard - un nouveau ticket ?

**Comment by vbombaerts** [comment]
Pas critique. Nouveau ticket pour plus tard. #616 
Validé en valid.
