### ISSUE TITLE
Le lien vers l'édition directe ne préserve pas la vue d'édition

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#601]
**Describe the bug**
Je voudrais envoyer aux éditeurs un lien direct vers la vue d'édition "main"
Je voudrais avoir un lien qui me donne directement accès à une vue d'édition en xml depuis un fichier Excel

Le liens fonctionnent si l'utilisateur est déjà loggué.

Par contre, s'il n'est pas loggué, il est redirigé vers la page d'identification (OK) et ensuite vers la page d'édition de la fiche, mais sur la vue par défaut et pas la vue indiquée par la requête 

`http://metawal.wallonie.be/geonetwork/srv/fre/catalog.edit#/metadata/51051?tab=main` 
devient  
`http://metawal.wallonie.be/geonetwork/srv/fre/catalog.edit#/metadata/51051`

**Comment by vbombaerts** [comment]
J'ai essayé de définir le tab=main comme tab par défaut dans la config mais j'ai pas réussi.

**Comment by fxprunayre** [comment]
Cf. https://github.com/geonetwork/core-geonetwork/pull/5705

**Comment by fxprunayre** [comment]
A déployer @davinciagf

**Comment by vbombaerts** [comment]
Env. valid OK.
