### ISSUE TITLE
Fiche fantôme

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#604]
Suite au problème "Le harvesting de la valid par le geoportail s'interrompt à cause d'une erreur de Metawal" discuté dans  [Teams](https://teams.microsoft.com/l/message/19:7300df98fd36433eb19befe0068113d6@thread.tacv2/1622042135679?tenantId=1f816a84-7aa6-4a56-b22a-7b3452fa8681&groupId=95dee10a-f6f1-411d-93ce-ed3318deb2d9&parentMessageId=1622042135679&teamName=Metawal%20-%20Maintenance%20et%20d%C3%A9veloppements&channelName=G%C3%A9n%C3%A9ral&createdTime=1622042135679)

Arnaud a identifié la fiche problématique en interrogeant le CSW par paquets jusqu'à isoler l'erreur : http://metawal4.valid.wallonie.be/geonetwork/srv/eng/catalog.search#/metadata/b1085bd5-2958-4751-87b8-b1c6be04b653

Problème : on a l'impression que cette fiche est une fiche "fantôme" : pas moyen de l'afficher en vue autre que "default", pas moyen de l'exporter, pas moyen de l'éditer. 

Comment solutionner ce problème ?

Hypothèse : une fiche qui a été effacée mais est encore référencée dans l'index ??

**Comment by davinciagf** [comment]
Voir si la mtd est disponible dans la DB de valid puis on la supprime. Cela devrait résoudre le problème.

`SELECT * FROM metadata where uuid ='b1085bd5-2958-4751-87b8-b1c6be04b653'`

Si besoin récupérer le xml (avant suppression) afin de le corriger si nécessaire.

**Comment by vbombaerts** [comment]
OK, mais peut-on tracer l'origine du problème pour éviter qu'il se reproduise ?

**Comment by fxprunayre** [comment]
http://metawal4.valid.wallonie.be/geonetwork/srv/api/records/b1085bd5-2958-4751-87b8-b1c6be04b653/formatters/xml fonctionne ? (j'ai pas accès à valid).

Sur test, dans l'admin y'a un indicateur qui permet de savoir nb de fiches en db/dans l'index - ça permet d'identifier d'éventuel fantôme - en général peut être dû à un pb d'indexation - normalement la 4.0.5 est assez robuste. Ca ne devrait pas se produire.

**Comment by davinciagf** [comment]
Là c'est plus compliqué - éventuellement essayer de retracer sa genèse.

**Comment by davinciagf** [comment]
Non pas d'accès au formatter xml
Voir la genèse de la MTD pour l'origine du problème

**Comment by vbombaerts** [comment]
> Sur test, dans l'admin y'a un indicateur qui permet de savoir nb de fiches en db/dans l'index

Pas trouvé. C'est où ?
EDIT : Problèmes avec l'index dans la version en test ? Erreurs d'indexation, Lien vers kibana a disparu...

**Comment by davinciagf** [comment]
Dispo en test pour l'instant (v4.0.4).  
Admin/Statistics & status/status

![Screen Shot 2021-06-03 at 08 38 03](https://user-images.githubusercontent.com/576292/120598930-2789da80-c447-11eb-9c7d-b1e22b35c09e.png)

**Comment by vbombaerts** [comment]
Merci, j'avais pas vu. Le lien Kibana n'est pas rétabli. J'ouvre un autre ticket ?

**Comment by davinciagf** [comment]
Non, il est bien là. C'est une image avant correctif et redéploiement ;-)
![Screen Shot 2021-06-03 at 14 12 54](https://user-images.githubusercontent.com/576292/120643037-efe65700-c475-11eb-9982-d735f12f53ac.png)

**Comment by vbombaerts** [comment]
Suppression de l'index et réindexation --> la fiche a disparu.
J'attends le rapport de moissonnage du GP avant de fermer mais a priori ce sera bon.
