### ISSUE TITLE
La validation en batch ne fonctionne pas

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#605]
**Describe the bug**
En essayant de valider plusieurs fiches depuis l'interface de contribution, je n'obtiens aucun résultat.

**To Reproduce**
1. Onglet Contribuer
2. Sélectionner 1 ou plusieurs fiches
3. Dans les actions sur la sélection choisir "valider"
4. Confirmer la validation dans la popup
5. Actions sur la sélection devient "Attendez, s'il vous plait"
6. Attendre
7. Attendre
8. Attendre
9. Abandonner car rien de visible ne se passe. ;-)

**Expected behavior**
Validation des fiches sélectionnées, résultat de validation, mise à jour de la pastille à côté de la fiche.

**Comment by fxprunayre** [comment]
L'erreur retournée
```
essage: "BeanCreationException", code: "runtime_exception",…}
code: "runtime_exception"
description: "Error creating bean with name 'processValidate': 
Invocation of init method failed; nested exception is org.springframework.jmx.export.UnableToRegisterMBeanException: 
Unable to register MBean [org.fao.geonet.api.processing.EmptySlotBatch@684dc372] with object name [geonetwork:name=batch-etf-inspire,idx=empty-slot-0]; 
nested exception is javax.management.InstanceAlreadyExistsException:
 geonetwork:name=batch-etf-inspire,idx=empty-slot-0"
message: "BeanCreationException"
```

Un reboot corrigera sans doute le pb :/

A priori corrigé avec https://github.com/geonetwork/core-geonetwork/commit/7005995f3735466e03b0bc2c0dc5de2c7393f880 donc devrait être ok sur test ?

**Comment by fxprunayre** [comment]
> A priori corrigé avec [geonetwork@7005995](https://github.com/geonetwork/core-geonetwork/commit/7005995f3735466e03b0bc2c0dc5de2c7393f880) donc devrait être ok sur test ?

En fait non, ce commit est sur prod je pense.

Tu as fait quoi avant ça ? pour donner un peu de contexte.
En test tu l'as déjà eu ?

**Comment by vbombaerts** [comment]
Sur la test ça fonctionne (validation "simple" et validation INSPIRE). Les rapports pour la validation simple sont stockés qqpart ou bien on doit revalider les fiches à l'unité pour avoir le rapport de test ?

**Comment by fxprunayre** [comment]
> Sur la test ça fonctionne (validation "simple" et validation INSPIRE). 

A suivre si ça se reproduit.

> Les rapports pour la validation simple sont stockés qqpart ou bien on doit revalider les fiches à l'unité pour avoir le rapport de test ?

On ne stocke que le résultat par niveaux de validation XSD, schematron(s).
Le rapport étant dépendant de la langue, il n'est pas stocké.
