### ISSUE TITLE
Correspondance Index et XML

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#607]
Où puis-je trouver la correspondance entre l'index et le XML ?
Par exemple, comment se fait l'encodage des contraintes dans l'index

```
<mri:resourceConstraints>
<mco:MD_LegalConstraints>
<mco:accessConstraints>
<mco:MD_RestrictionCode codeList="http://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#MD_RestrictionCode" codeListValue="license"/>
</mco:accessConstraints>
<mco:useConstraints>
<mco:MD_RestrictionCode codeList="http://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#MD_RestrictionCode" codeListValue="license"/>
</mco:useConstraints>
<mco:otherConstraints>
<gco:CharacterString>Les conditions d'utilisation du service sont régies par les Conditions d’accès et d’utilisation des services web géographiques de visualisation du Service public de Wallonie consultables à l'adresse https://geoportail.wallonie.be/files/documents/ConditionsSPW/LicServicesSPW.pdf</gco:CharacterString>
</mco:otherConstraints>
</mco:MD_LegalConstraints>
</mri:resourceConstraints>
```

![image](https://user-images.githubusercontent.com/6093597/120559020-96901080-c400-11eb-9d24-bf9f35363882.png)

**Comment by fxprunayre** [comment]
Là https://github.com/geonetwork/core-geonetwork/blob/main/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl#L730-L736

Dans ton exemple, 
* MD_LegalConstraints est le préfix
* Ensuite y'a un champ pour OtherConstraints et un pour useLimitation
* Qui sont multilingues potentiellement d'où les .default, .langfre, .lang...

Pour les codelists, c'est ici https://github.com/geonetwork/core-geonetwork/blob/main/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl#L248-L273 et toutes les codelists sont dans des champs `cl_...` mais sans relation avec les blocs de contraintes.

**Comment by vbombaerts** [comment]
Donc les mco:MD_RestrictionCode ne sont pas indexés, c'est ça ?
Je voulais construire un tableau avec toutes les occurrences des combinaisons de conditions d'accès, d'usage et limitations d'usage pour essayer d'harmoniser un peu tout ça. Ce n'est pas possible en l'état ?

**Comment by fxprunayre** [comment]
> Donc les mco:MD_RestrictionCode ne sont pas indexés, c'est ça ?

Si mais sans lien avec les autres éléments du même bloc.



> avec toutes les occurrences des combinaisons

y'a pas de lien entre les champs. On pourrait mais faudrait créer un objet dans l'index du genre :
```json
constraints: [{
 type: MD_LegalConstraints
 access: ..
 use: ...
 other: ...
}]
```
un peu comme on fait pour les liens.
