### ISSUE TITLE
Système de projection Lambert 2008

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#609]
**Describe the bug**
On a des jeux de données qui arrivent nativement en projection Lambert 2008. Cette projection n'est pas disponible par défaut dans la shortlist de Metawal. (mais on peut l'encoder en vue complète)

![image](https://user-images.githubusercontent.com/6093597/120710134-10d29a80-c4be-11eb-8703-14a47729c298.png)

**Expected behavior**
Ajout de la projection dans la shortlist.

**Comment by vbombaerts** [comment]
J'ai pas les yeux en face des trous. Elle est déjà dispo. On peut effacer le ticket ?

**Comment by fxprunayre** [comment]
> J'ai pas les yeux en face des trous.

:)

> On peut effacer le ticket ?

Tu veux dire pas fermer, mais supprimer ? 
https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/deleting-an-issue
Ca semble possible mais faut l'activer.

**Comment by vbombaerts** [comment]
@fxprunayre Je suis owner de l'organisation mais pas du repository, donc je n'ai pas les droits pour l'effacer.
