### ISSUE TITLE
Des groupes nouvellement créés apparaissent avec leur identifiant plutôt que leur nom

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#610]
**Describe the bug**
Env. de prod. J'ai créé il y a qques jours 2 nouveaux groupes, à des moments différents.

Aujourd'hui, au moment de publier une fiche pour ce groupe, c'est l'identifiant du groupe qui s'affiche et non le nom du groupe
![image](https://user-images.githubusercontent.com/6093597/120715321-c1439d00-c4c4-11eb-8a4c-8dbd2c916518.png)

![image](https://user-images.githubusercontent.com/6093597/120715214-96594900-c4c4-11eb-9940-4d0c4b13123d.png)

**Comment by vbombaerts** [comment]
Si je tente de publier une fiche dans un de ces groupes, ça ne fonctionne pas.
C'est un bug nouveau. Je ne l'avais pas la semaine dernière. J'ai réussi à publier des fiches dans un des nouveaux groupes.

**Comment by fxprunayre** [comment]
Admin > Tools > Clear translation cache

Et sinon ce point vient d'être amélioré côté GN, j'ai récupéré le fix.

@davinciagf à déployer.

**Comment by davinciagf** [comment]
Redéployé

**Comment by vbombaerts** [comment]
Pas de problème rencontré en valid.
