### ISSUE TITLE
Navigation rapide en édition indisponible

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#613]
**Describe the bug**
(Testé en env. de valid sur la version montante - env de test non-fonctionnel au moment du test)
Dans l'interface d'édition d'une fiche, l'outil de navigation rapide qui permet de navigue directement vers une section spécifique de la fiche affiche un menu de navigation vide.

Env valid (bug)
![image](https://user-images.githubusercontent.com/6093597/121383911-1a3d8600-c948-11eb-8e0f-dcceb8928b9f.png)

En prod (pas de bug)
![image](https://user-images.githubusercontent.com/6093597/121384345-76a0a580-c948-11eb-9571-21d373735c42.png)

**Comment by fxprunayre** [comment]
A déployer @davinciagf

**Comment by vbombaerts** [comment]
Vous répliquez le problème ?
Parce que chez moi le bug s'est propagé aux environnements de test et de prod. J'ai essayé avec 2 navigateurs différents. Chrome et Firefox.

**Comment by fxprunayre** [comment]
> Vous répliquez le problème ?

En local avec 62bf9337aef603dca39550eacd934965d81091e2 ca marche bien. Admin > Tools > Vider le cache JS & CSS ?

**Comment by vbombaerts** [comment]
Je n'ai rien fait et maintenant ça marche. Les voies de l'informatique sont impénétrables...

**Comment by davinciagf** [comment]
C'était le cache ;-)
