### ISSUE TITLE
Une fiche est à la fois fiche et modèle

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#614]
**Describe the bug**
J'ai édité un modèle. Il est apparu ensuite dans la liste des fiches. Si je filtre uniquement sur les modèles, il apparait. Si je filtre sur les données, il apparait. Si je supprime la fiche de données, le modèle disparait.

**To Reproduce**
TODO

**Comment by fxprunayre** [comment]
C'est suspect ! Je dirai même que c'est a priori pas possible si c'est le même UUID. J'ai tenté différents scénarios sans succès.

**Comment by vbombaerts** [comment]
Erreur d'interprétation de ma part. Dans l'interface contribuer, tant les fiches que les modèles sont listés par défaut. Dans l'interface de recherche, uniquement les fiches.
