### ISSUE TITLE
Date en Zulu time

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#616]
> la date du filtre est décalée d'un jour par rapport à la date choisie

Non, elle est en Zulu time, donc CET-2h actuellement. 
Ce serait un truc à améliorer - ne pas afficher les heures dans ce cas peut être.
Y'a aussi des améliorations en cours quand on a une sélection des années uniquement https://github.com/geonetwork/core-geonetwork/pull/5727 
On le garde pour plus tard - un nouveau ticket ?

_Originally posted by @fxprunayre in https://github.com/SPW-DIG/metawal-core-geonetwork/issues/600#issuecomment-858383362_

**Comment by fxprunayre** [comment]
A déployer.

![image](https://user-images.githubusercontent.com/1701393/128216736-5f201d93-0139-482b-888c-5cf85c726272.png)
