### ISSUE TITLE
Impossible de créer un utilisateur depuis le LDAP

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#619]
**Describe the bug**
Je souhaite créer un nouvel utilisateur depuis le LDAP et lui attribuer des droits d'édition dans le groupe SPW-Environnement. J'obtiens une erreur "Null pointer exception" et l'utilisateur n'est pas créé.
Peut-être lié au test de connexion au nouveau LDAP qu'on a fait en env. de test (et les paramètres qui ont été conservés lors du passage en valid et prod) ?? #608 
Testé en prod et valid. Test n'était pas dispo.
![image](https://user-images.githubusercontent.com/6093597/122883729-c36b7f80-d33d-11eb-8c3d-beac9ba2e88b.png)
![image](https://user-images.githubusercontent.com/6093597/122883787-cf574180-d33d-11eb-83f2-8e2c032a7c9b.png)

**Comment by davinciagf** [comment]
Idem en test et pareil pour enregistrer un simple utilisateur sans utiliser le LDAP. Potentiel erreur dans la config en DB - je regarde.

**Comment by davinciagf** [comment]
J'ai vu le problème, il y a eu des améliorations au niveau de la gestion des utilisateurs. J'ai déjà fait un update en DB afin de pouvoir créer des utilisateurs sans LDAP. Je regarde encore pour gérer le cas LDAP.

**Comment by vbombaerts** [comment]
Problème du LDAP alors ? @davinciagf  Tu as moyen de savoir si le problème est chez nous ou chez eux ?

**Comment by davinciagf** [comment]
Non c'est une amélioration de GN qui modifie la gestion utilisateur mais qui pose problème dans notre cas pour le LDAP. On doit faire qq modif en interne.

**Comment by vbombaerts** [comment]
Testé en env. test. Fonctionnel. On peut avancer vers valid et prod.

**Comment by vbombaerts** [comment]
@davinciagf 
Valid non fonctionnel.
Création d'un user hors LDAP OK si on respecte les contraintes de password.
Utilisateur LDAP pas possible.

![image](https://user-images.githubusercontent.com/6093597/123300539-f880f900-d51a-11eb-8c05-1b5504816b32.png)

**Comment by davinciagf** [comment]
Problème de cache Javascript. 
J'ai vidé ce dernier et je me suis enregistré via LDAP.

**Comment by vbombaerts** [comment]
Problème de cache. C'est bon en valid.
