### ISSUE TITLE
Zone de recherche : titre des sous-espaces

### ISSUE THREAD

**Issue by metawal** [SPW-DIG/metawal-core-geonetwork#62]
Dans la zone "Critères avancés", la disposition des sous-espaces de recherche n'est pas ergonomique.
Par exemple, on voit un titre "Critères temporels" sous lequel se trouvent les champs "Représentation spatiales" et "Echelle".
Cette interface de recherche mériterait d'être revue par un ergonome.

**Comment by fxprunayre** [comment]
Cf dicussion https://github.com/spacebelGIS/metawal-core-geonetwork/wiki/Ergonomie-et-design-des-interfaces-Metawal
