### ISSUE TITLE
Donner plus de poids dans les résultats de recherche aux séries par rapport aux membres de la série

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#620]
Tout est dans le titre.
Modif de la config de l'interface à faire.

**Comment by fxprunayre** [comment]
Normalement c'est déjà le cas cf.
https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.0.x/web-ui/src/main/resources/catalog/js/CatController.js#L173-L200

* Boost down les fiches qui ont un parent
* Boost down les fiches qui sont obsolete
* Boost down les fiches de plus de 3 mois

Tu peux donner un exemple de recherche et de résultat attendu ? pour voir comment modifier la configuration.

**Comment by vbombaerts** [comment]
C'est bon. C'est la représentation de la relation hiérarchique série/donnée qui devra être améliorée
