### ISSUE TITLE
Problèmes en environnement de valid

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#621]
**Describe the bug**
L'index semble indisponible en env. de valid. Quelles solutions ?

![image](https://user-images.githubusercontent.com/6093597/123107572-f430df00-d439-11eb-9965-cc2931567c8b.png)

**Comment by vbombaerts** [comment]
Ce sont les buckets de recherche qui sont indisponibles.
![image](https://user-images.githubusercontent.com/6093597/123221047-d06ba880-d4ce-11eb-8205-36ad6a4c33b9.png)
Voir avec le DTIC.

**Comment by davinciagf** [comment]
Cela semble à nouveau opérationnel.
