### ISSUE TITLE
Export PDF pas possible pour une sélection de plusieurs fiches

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#622]
**Describe the bug**
Après avoir sélectionné plusieurs fiches, j'ai un message d'erreur quand je veux les exporter en pdf.
L'export individuel est fonctionnel.
```
<apiError>
<code>runtime_exception</code>
<description>java.util.HashMap cannot be cast to java.lang.String</description>
<message>ClassCastException</message>
</apiError>
```

**Comment by fxprunayre** [comment]
GN ref https://github.com/geonetwork/core-geonetwork/pull/5787

**Comment by fxprunayre** [comment]
A déployer.

**Comment by davinciagf** [comment]
Nouvelle erreur (export PDF sur une seule mtd ou sur plusieurs) 

![image](https://user-images.githubusercontent.com/576292/129045414-354f70c9-ec9a-4a3f-91de-024c9b8a516e.png)

**Comment by davinciagf** [comment]
Les voies des env. de test, valid et prod sont parfois impénétrables
![image](https://user-images.githubusercontent.com/576292/131139126-335a25e8-b747-49ae-baa9-7a1869b5f83f.png)

**Comment by vbombaerts** [comment]
Le premier export est en erreur.
A la deuxième tentative ça passe.

Si je change d'utilisateur --> idem : première tentative en erreur. Après ça passe.

C'est un message d'erreur bizarre en plus... (et j'ai bien cliqué sur download pdf)
![image](https://user-images.githubusercontent.com/6093597/131802250-dc46fce1-4989-48be-b750-7d526f2783b2.png)

**Comment by davinciagf** [comment]
Bizarre, bizarre, je viens de retester et j'ai bien l'export pdf au premier test. 
![image](https://user-images.githubusercontent.com/576292/131824773-81e3140d-0af3-4512-962f-65d745def9a8.png)
J'ai refait le test avec un autre utilisateur nouvellement créé et c'était ok également

**Comment by vbombaerts** [comment]
C'est marrant, le message d'erreur qu'on reçoit c'est ce qui est écrit dans la requête ici : https://github.com/SPW-DIG/metawal-core-geonetwork/issues/628#issuecomment-897587986

**Comment by vbombaerts** [comment]
```
<apiError>
<code>unsatisfied_request_parameter</code>
<description>The name "day(s)" is not legal for JDOM/XML elements: XML names cannot contain the character "(".</description>
<message>IllegalNameException</message>
</apiError>
```

**Comment by fxprunayre** [comment]
A déployer @davinciagf

**Comment by davinciagf** [comment]
Dispo sur test

**Comment by vbombaerts** [comment]
Testé l'export sur 1 fiche et sur plusieurs --> OK.
