### ISSUE TITLE
Utilisation de l'API pour sélectionner des fiches bien définies

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#625]
**Describe the bug**
Après avoir mis à jour 82 fiches (suppression en XML du SchemaLocation), je voudrais lancer une validation sur ces fiches. Les dates de mise à jour dans l'interface Metawal ne correspondent pas à la date de mise à jour du XML (les dernières mises à jour ne sont pas celles que je viens de mettre à jour, en tout cas pas dans un ordre utilisable).

Du coup, j'ai essayé d'utiliser l'API pour sélectionner les 82 fiches sur base de leur uuid.

J'ai voulu ajouter des fiches à la sélection par la commande 
`http://metawal.wallonie.be/geonetwork/srv/api/selections/e101?uuid=25dac820-ff8f-45ae-a30c-f53db080488f&uuid=2e67b78e-59a6-4681-acd1-ab9eadcc44e2&uuid=c34743fa-7c50-4bfe-b587-e1253ff68eae`

Ensuite, j'ai voulu vérifier quelles fiches faisaient partie du bucket par la commande
`http://metawal.wallonie.be/geonetwork/srv/api/selections/e101`
et là pas d'uuid qui s'affiche.

Dans l'interface, les fiches ne sont pas sélectionnées.

Où est l'erreur ?

**Comment by fxprunayre** [comment]
Il faut faire un PUT

![image](https://user-images.githubusercontent.com/1701393/127984417-36d04392-6275-4715-92e7-3f98dfef2a01.png)

Le navigateur ne fait qu'un GET.

A faire avec CURL ou Postman ou FME ;)
