### ISSUE TITLE
Filtres utilisateur sur l'interface de contribution

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#627]
**Is your feature request related to a problem? Please describe.**
J'utilise bcp les filtres utilisateurs. J'utilise aussi bcp l'interface de contribution. Est-il possible d'ajouter les filtres utilisateurs sur l'interface d'édition ?

**Comment by fxprunayre** [comment]
filtres utilisateurs = user saved searches

**Comment by davinciagf** [comment]
Voir https://github.com/geonetwork/core-geonetwork/pull/5907 et déployé en test
