### ISSUE TITLE
Validation INSPIRE en batch via CSW INSPIRE

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#628]
Ce serait chouette d'avoir accès à la validation INSPIRE (via CSW INSPIRE) en batch, càd pour une sélection faite depuis l'interface de contribution. Actuellement, on n'y a accès que fiche par fiche. Or, sauf erreur de ma part, la validation INSPIRE "simple" ne prend pas en compte les transformations spécifiques INSPIRE jouées à l'export des fiches (suppression des contacts sans email, etc...)

**Comment by fxprunayre** [comment]
En fait, je me dis qu'à partir du moment où on a créé un point CSW pour INSPIRE, il ne faut utiliser que celui-là ? J'aurai dont tendance à ajouter un paramètre pour la validation INSPIRE:
* si null, validation par upload
* si un identifiant de portail, validation par le CSW de ce portail

Le seul problème est si la fiche n'est pas dans le portail en question - elle ne sera pas dans la réponse du CSW.

@vbombaerts ok ?

**Comment by fxprunayre** [comment]
GN ref https://github.com/geonetwork/core-geonetwork/pull/5899

**Comment by fxprunayre** [comment]
A déployer.

**Comment by fxprunayre** [comment]
To play on DB
```sql
INSERT INTO Settings (name, value, datatype, position, internal) VALUES ('system/inspire/remotevalidation/nodeid', 'inspire', 0, 7212, 'n');
```

**Comment by vbombaerts** [comment]
La fonctionnalité est présente mais je n'ai pas réussi à valider depuis l'env de valid. Problème de certificat ?   #565

**Comment by davinciagf** [comment]
La valid n'a pas l'autorisation d'utiliser le proxy. Didier fait la demande pour modifier cela.

**Comment by davinciagf** [comment]
Autorisation modifiée en valid.

**Comment by vbombaerts** [comment]
Le testing est possible. J'ai eu une réponse du serveur INSPIRE.
Maintenant, il faut résoudre #661 

![image](https://user-images.githubusercontent.com/6093597/137452033-2367997b-1217-4759-b84a-a1ce9dd747b5.png)
