### ISSUE TITLE
schemalocation, validation et CSW-T

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#629]
**Describe the bug**
J'ai remarqué que malgré la correction faite avec #603 certaines fiches ont de nouveau des schemalocation.
Ce sont les fiches qui ont été éditées à l'extérieur de Metawal par des processus FME, pour mettre à jour les dates de révision des données. Je pense que le processus passe par une édition CSW-T (à vérifier).
La présence du schemalocation est problématique parce que la validation ne passe pas sur ces fiches.

Je vais me renseigner pour mieux comprendre le processus d'édition via FME

**Comment by fxprunayre** [comment]
Related to https://github.com/geonetwork/core-geonetwork/pull/5878

**Comment by fxprunayre** [comment]
A déployer et cocher "Supprimer l'adresse du schéma XSD pour la validation (@xsi:schemaLocation)." dans admin (fait pour validation, import et sauvegarde).
En base, SQL pour re supprimer les schemaLocation.

**Comment by davinciagf** [comment]
En env de test, c'est coché: 
![image](https://user-images.githubusercontent.com/576292/129331621-2b0772b5-e2b2-4d81-ad7a-fc6bc754cee5.png)

et la requête DB a été jouée:

`UPDATE Metadata SET data = replace(data,' xsi:schemaLocation="http://standards.iso.org/iso/19115/-3/mds/1.0 http://standards.iso.org/iso/19115/-3/mds/1.0/mds.xsd"', '') WHERE data LIKE '%xsi:schemaLocation="http://standards.iso.org/iso/19115/-3/mds/1.0 http://standards.iso.org/iso/19115/-3/mds/1.0/mds.xsd"%';
`

En env. de valid et de prod, la case  "Supprimer l'adresse du schéma XSD pour la validation (@xsi:schemaLocation)." est bien cochée.
Ligne SQL rajoutée dans le script de migration.

**Comment by vbombaerts** [comment]
J'ai pas pu vérifier les résultats du script pcq ça a moissonné la prod entretemps mais a priori c'est OK : option déjà cochée en prod et depuis plus de problème.
