### ISSUE TITLE
Action - export XML ne permet pas de télécharger le XML

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#63]
Sous FFox il s'affiche dans une nouvelle fenêtre pour laquelle on n'a aucun menu ==> impossible d'enregistrer le XML

**Comment by fxprunayre** [comment]
> Sous FFox il s'affiche dans une nouvelle fenêtre pour laquelle on n'a aucun menu ==> impossible d'enregistrer le XML

options: 
- CTRL + S
- clic droit > save as.
  
  Limitation du navigateur ?
  Non reproductible sur FF25 
  ![image](https://f.cloud.github.com/assets/1701393/1790634/cf3afc34-697b-11e3-8c36-5ac5fa0c6852.png)

**Comment by vbombaerts** [comment]
Contournement proposé valable.
