### ISSUE TITLE
Export CSV, autre séparateur

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#630]
**Describe the bug**
Le séparateur actuel pour l'export des fiches en CSV est la virgule. Or, certains long champs texte contiennent des virgules, comme par exemple la description ou la généalogie. Du coup, quand on essaie d'importer le csv dans un tableur, il est tout de travers. Est-il possible d'utiliser un séparateur différent qui ne causerait pas le problème ?

**Comment by fxprunayre** [comment]
Ok in http://localhost:8080/geonetwork/srv/api/records/csv?bucket=e101 with `"`
Faire la même chose http://localhost:8080/geonetwork/srv/fre/admin.console#/reports

**Comment by fxprunayre** [comment]
GeoNetwork ref https://github.com/geonetwork/core-geonetwork/pull/5897

**Comment by fxprunayre** [comment]
A déployer.

**Comment by davinciagf** [comment]
le premier élement reste sans `"`
![image](https://user-images.githubusercontent.com/576292/129191117-988573fe-23fc-4073-9064-c5eb2a0689f2.png)

**Comment by davinciagf** [comment]
Attention, ce cas est lié à Excell (et sa config sans doute) et ne se rencontre pas avec Notepad++ par exemple. 
Exemple d'un même fichier ouvert ous Excell et notepad++ :
![image](https://user-images.githubusercontent.com/576292/129200465-09f222ec-794e-4fa9-ac87-3add2c7b0554.png)

**Comment by vbombaerts** [comment]
Ca marche déjà mieux.
Deux pistes d'amélioration :
1. Dans Excel pas possible d'indiquer que le séparateur est "," car un seul caractère est autorisé. Du coup on se retrouve avec des colonnes de virgules (c'est gérable en supprimant les colonnes ensuite)
2. Pour la même raison, dans les cas où les textes contiennent des ", ça foire un peu. (gérable aussi car occurrences limitées)
![image](https://user-images.githubusercontent.com/6093597/130437170-24129fd4-4a1a-4164-87eb-9436b9509307.png)

Ca se fait d'utiliser un caractère spécial complètement loufoque et improbable comme séparateur ? Genre ♥ ou ☼


Les fiches surlignées en bleu correspondent aux fiches que j'ai créées pour tester l'erreur d'indexation #632
