### ISSUE TITLE
Fiches sans titre - erreurs d'indexation

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#632]
**Describe the bug**
Plusieurs fiches sans titre dans Metawal
Du à des erreurs d'indexation.
![image](https://user-images.githubusercontent.com/6093597/125276777-e5d73400-e310-11eb-894b-caebbfe2cbfe.png)

Exemple : http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/60ac65e7-5cc5-466c-95bb-cdb20814795e
Je n'ai pas trouvé la cause du problème.

**Comment by fxprunayre** [comment]
Ce sera corrigé par https://github.com/geonetwork/core-geonetwork/pull/5814. Soit on cherry-pick et on redéploie - soit on attend ? On doit pouvoir contourner le pb en créant 2 blocs gmd:report différents aussi.

**Comment by fxprunayre** [comment]
A déployer.

**Comment by davinciagf** [comment]
A tester

**Comment by vbombaerts** [comment]
Pas testable en l'état :
- pas possible d'importer la fiche avec l'erreur
- quand on copie/colle le XML dans une nouvelle fiche, la fiche n'apparait pas - https://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/2e31f869-253c-47b7-bc48-d96df9e90179

![image](https://user-images.githubusercontent.com/6093597/130434749-bf1721c7-85e8-49b1-a83a-5da7e4938a00.png)

![image](https://user-images.githubusercontent.com/6093597/130435089-e2004ea8-9814-406a-9b07-ab3ae06ba40a.png)

**Comment by vbombaerts** [comment]
Note : les fiches encodées directement en XML ont bien été créées : elles apparaissent dans le rapport de mise à jour https://github.com/SPW-DIG/metawal-core-geonetwork/issues/630#issuecomment-903666478
