### ISSUE TITLE
Erreurs d'indexation - Thésaurus InfraSIG et ressources de type carte

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#633]
**Describe the bug**
Le thésaurus InfraSIG semble ne pas être reconnu sur les fiches concernant les cartes.
Même en ré-encodant les mots-clés InfraSIG from scratch, les erreurs persistent.

![image](https://user-images.githubusercontent.com/6093597/125296327-78360280-e326-11eb-86b7-ee4571aacaeb.png)

**Comment by fxprunayre** [comment]
Le thésaurus est marqué externe https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.0.x/web/src/main/webapp/WEB-INF/data/config/codelist/external/thesauri/theme/infraSIG.rdf donc changer l'id du thésaurus dans la fiche ?

**Comment by vbombaerts** [comment]
Désolé, pas compris.
Il faut faire quoi exactement ?

```
         <mri:descriptiveKeywords>
            <mri:MD_Keywords>
               <mri:keyword>
                  <gco:CharacterString>Reporting INSPIRENO</gco:CharacterString>
               </mri:keyword>
               <mri:type>
                  <mri:MD_KeywordTypeCode codeList="http://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#MD_KeywordTypeCode"
                                          codeListValue="theme"/>
               </mri:type>
               <mri:thesaurusName>
                  <cit:CI_Citation>
                     <cit:title>
                        <gcx:Anchor xlink:href="http://metawal.wallonie.be/thesaurus/infrasig">Mots-clés InfraSIG</gcx:Anchor>
                     </cit:title>
                     <cit:date>
                        <cit:CI_Date>
                           <cit:date>
                              <gco:Date>2018-04-23</gco:Date>
                           </cit:date>
                           <cit:dateType>
                              <cit:CI_DateTypeCode codeList="http://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#CI_DateTypeCode"
                                                   codeListValue="publication"/>
                           </cit:dateType>
                        </cit:CI_Date>
                     </cit:date>
                     <cit:identifier>
                        <mcc:MD_Identifier>
                           <mcc:code>
                              <gcx:Anchor xlink:href="http://metawal.wallonie.be/geonetwork/srv/api/registries/vocabularies/local.theme.infraSIG">geonetwork.thesaurus.local.theme.infraSIG</gcx:Anchor>
                           </mcc:code>
                        </mcc:MD_Identifier>
                     </cit:identifier>
                  </cit:CI_Citation>
               </mri:thesaurusName>
            </mri:MD_Keywords>
         </mri:descriptiveKeywords>
```

**Comment by vbombaerts** [comment]
J'ai effacé tout le bloc des mots-clés InfraSIG et je l'ai repris à partir du thésaurus. Je ne vois pas comment corriger autrement.

**Comment by fxprunayre** [comment]
Si tu supprimes le bloc et que tu le remets en effet ça doit jouer. Sinon 
```xml
<gcx:Anchor xlink:href="http://metawal.wallonie.be/geonetwork/srv/api/registries/vocabularies/local.theme.infraSIG">
geonetwork.thesaurus.local.theme.infraSIG</gcx:Anchor>

```
à convertir en 
```xml
<gcx:Anchor xlink:href="http://metawal.wallonie.be/geonetwork/srv/api/registries/vocabularies/external.theme.infraSIG">
geonetwork.thesaurus.external.theme.infraSIG</gcx:Anchor>
```

(j'ai pas testé)

**Comment by vbombaerts** [comment]
Quand je supprime le bloc et que je l'ajoute, le bloc ajouté est
`<gcx:Anchor xlink:href="http://metawal.wallonie.be/geonetwork/srv/api/registries/vocabularies/local.theme.infraSIG">geonetwork.thesaurus.local.theme.infraSIG</gcx:Anchor>`

--> erreur d'indexation
![image](https://user-images.githubusercontent.com/6093597/125317271-28146b80-e339-11eb-9f29-8ed87303f5f7.png)

Quand je modifie l'ancre pour un thésaurus externe
`<gcx:Anchor xlink:href="http://metawal.wallonie.be/geonetwork/srv/api/registries/vocabularies/external.theme.infraSIG">geonetwork.thesaurus.external.theme.infraSIG</gcx:Anchor>`

--> erreur d'indexation
![image](https://user-images.githubusercontent.com/6093597/125317172-1763f580-e339-11eb-8e4b-fa2cfd5a12cc.png)

**Comment by fxprunayre** [comment]
Tester en local, je pense qu'il faut juste jouer 

```sql
UPDATE metadata SET data = replace(data, 'local.theme.infraSIG', 'external.theme.infraSIG')
  WHERE data LIKE '%local.theme.infraSIG%';
```

en db. @davinciagf tu peux tester sur test? merci.

et vérifier que Reporting INSPIRENO est bien dans le thésaurus. Devrait être là https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.0.x/web/src/main/webapp/WEB-INF/data/config/codelist/external/thesauri/theme/infraSIG.rdf#L99-L102

**Comment by davinciagf** [comment]
Le thesaurus semble être en local et non en external
![image](https://user-images.githubusercontent.com/576292/129333686-79a34f71-3ded-4bc7-be6c-d4c7e58e6c3e.png)

A supprimer de l'admin et le réimporter.

**Comment by vbombaerts** [comment]
Thésaurus réimporté
![image](https://user-images.githubusercontent.com/6093597/130432344-22db9f8e-d9b3-4eb6-8fb1-ab5ee0be0970.png)


Ancre changée
`<gcx:Anchor xlink:href="http://metawal.wallonie.be/geonetwork/srv/api/registries/vocabularies/external.theme.infraSIG">geonetwork.thesaurus.external.theme.infraSIG</gcx:Anchor>`

![image](https://user-images.githubusercontent.com/6093597/130433117-b42045d0-7da7-4356-8e40-f6c0f9ac631a.png)


Mais le problème est toujours là
![image](https://user-images.githubusercontent.com/6093597/130432951-9b708d1d-3a9d-4c7c-bd75-4189f9d420f2.png)

**Comment by davinciagf** [comment]
J'ai rejoué la requête pour bien définir le thesaurus externe. Il ne reste que quelques erreurs au niveau thesaurus infraSIG (4),
![image](https://user-images.githubusercontent.com/576292/130600827-50d0cc5f-daff-4a07-b698-dcc5bcc3b69f.png)

La comparison avec une mtd correctement indexée montre que l'erreur provient  de l'ancre et de la date:

![image](https://user-images.githubusercontent.com/576292/130599793-2070a435-1aee-4eec-90f3-368a1e6c2c28.png)

**Comment by davinciagf** [comment]
Pour les deux dernières MTD en erreur d'indexation, il faut importer le thesaurus "classification of spatial data services" qui est présent en prod mais pas en test.
![image](https://user-images.githubusercontent.com/576292/130616475-31b15424-6d67-41c7-a2de-b7d5af50693c.png)

**Comment by davinciagf** [comment]
@vbombaerts tu fais ou je fais:
- les modifs au niveau des 4 mtd pour le thesaurus infrasig
- l'import thesaurus "classification of spatial data services" (voir commentaires ci-dessus) ?

**Comment by vbombaerts** [comment]
J'ai importé le thésaurus "classification of data services", c'est OK.
Le problème reste le thésaurus InfraSIG. Si on le met en externe, plus de 1000 fiches sont en erreur (en prod, elles ne le sont pas encore pcq je n'ai pas indexé, mais j'ai vérifié via la BD et de mémoire 1144 fiches renseignent le thésaurus infraSIG en local). Ca implique une correction massive en BD et ça ne fait pas disparaitre le problème pour les ressources de type carte. 
Après, si on analyse la situation au calme, les 11 fiches problématiques ont été créées le même jour, ne contiennent que très peu d'information et ne sont pas publiées. On peut peut-être juste les laisser comme ça et les reprendre "from scratch" quand on en aura besoin (si demande de publication de la part du gestionnaire).

**Comment by vbombaerts** [comment]
@davinciagf Je fais la demande au DTIC pour le changement du thésaurus InfraSIG  ? Il me semble que tu l'as incluse dans le script pour la prochaine mise à jour. Pour moi ça peut attendre la mise à jour.

**Comment by davinciagf** [comment]
Oui tu peux. Je vais commenter la ligne dans le script de migration pour le prochain war.

**Comment by vbombaerts** [comment]
J'ai introduit la demande au DTIC et j'ai modifié en base le thésaurus en test. Le problème avec les ressources de type carte est toujours là.

**Comment by vbombaerts** [comment]
Les infos thésaurus ont été modifiées en base en prod. 
Retour à la situation initiale.

**Comment by fxprunayre** [comment]
:/ J'ai compris ! Ces fiches sont un peu minimaliste et n'ont pas de langue définie et donc on cherche un mot clé dans une langue qui ne correspond pas au thésaurus.

En ajoutant:
```
   <mdb:defaultLocale>
      <lan:PT_Locale id="FR">
         <lan:language>
            <lan:LanguageCode codeList="http://www.loc.gov/standards/iso639-2/" codeListValue="fre"/>
         </lan:language>
         <lan:characterEncoding>
            <lan:MD_CharacterSetCode codeList="http://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#MD_CharacterSetCode"
                                     codeListValue=""/>
         </lan:characterEncoding>
      </lan:PT_Locale>
   </mdb:defaultLocale>
```
ca semble mieux. A tester @vbombaerts - dsl d'avoir mis tant de temps à trouver ça.

**Comment by vbombaerts** [comment]
Quel crack ! 💯
