### ISSUE TITLE
Problème d'indexation pour une fiche multilingue

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#635]
**Describe the bug**
Nous n'envisageons pas de généraliser le multilinguisme, mais un utilisateur souhaitait utiliser des mot-clés multilingues dans sa fiche. L'indexation de cette fiche ne se fait pas. Pas possible non plus de changer les privilèges sur cette fiche.
[http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/38717b85-8c96-474c-a443-fe335c26cef9](http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/38717b85-8c96-474c-a443-fe335c26cef9)

**Comment by fxprunayre** [comment]
L'erreur d'indexation associée est:
```indexingErrorMsg: "GNIDX-XSL||A sequence of more than one item is not allowed as the first argument of 
gn-fn-index:json-escape() (\"Belge 1972 / Belgian Lambert 7...\", \"\", ...) "
```

Je vais regarder. En attendant, ne pas mettre de description dans le CRS si c'est urgent ?

**Comment by vbombaerts** [comment]
Pas urgent du tout. Je ne suis même pas sur que le GP est capable d'interpréter une fiche multilingue. Mais je pense à mes camarades du fédéral et de Bxl qui eux travaillent en multilingue...

**Comment by fxprunayre** [comment]
A déployer.

**Comment by vbombaerts** [comment]
OK. Testé sur https://metawal4.valid.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/e9ee8aa4-cc1d-44d7-9678-0a5d0354e477 après correction de l'erreur de schéma.

**Comment by vbombaerts** [comment]
OK. Testé sur http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/6f12973d-9528-4028-a7a2-e68d5a002c56
