### ISSUE TITLE
Metawal valid - fonctionnalités indisponibles malgré un redémarrage

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#636]
**Describe the bug**
Impossible de sauvegarder les éditions, impossible de passer d'une vue d'édition à une autre, impossible d'enregistrer une modification des paramètres (`Erreur durant l'importation des paramètres - 413 Request Entity Too Large - nginx/1.16.0`)
J'ai aussi remarqué que le GP n'a pas moissonné la valid.

L'erreur est apparue suite à des éditions simultanées de fiches différentes (en vue de corriger des erreurs d'indexation).
Juste avant j'ai importé des thésaurus depuis la prod. (Impossible de les importer depuis le Registry INSPIRE)

Les messages qui ressortent du log sont 
`Caused by: java.io.IOException: Broken pipe
`et 
`Caused by: java.lang.OutOfMemoryError: Java heap space`

L'application a été redémarrée le 28/07 et le double de mémoire a été alloué sur le Tomcat.
Pas de changement notable.

**Comment by fxprunayre** [comment]
A priori, c'est nginx qui répond "Request Entity Too Large". C'est sur toutes les fiches ou une en particulier ?
Quand on sauve l'édition, on POST le formulaire qui peut être un peu volumineux (eg. un polygone avec un contour d'un pays!) mais en général ca va ...
A voir côté nginx, client_max_body_size peut être ?

**Comment by vbombaerts** [comment]
client_max_body_size a été passé de 10mb à 200mb.
Maintenant on a l'erreur : 
```
Erreur durant l'importation des paramètres
502 Bad Gateway
Bad Gateway
The proxy server received an invalid response from an upstream server.
```
Didier demande si l'appel est fait en http ou https
essayez un peu de changer de passer dans l'un ou l autre mode pour voir

**Comment by vbombaerts** [comment]
Pour moi pas d'urgence, ça peut attendre le retour d'Arnaud.

**Comment by fxprunayre** [comment]
> essayez un peu de changer de passer dans l'un ou l autre mode pour voir

Je l'ai déjà dit. Il n'est pas recommandé d'avoir en même temps du HTTP et du HTTPs. Si on veut du HTTPs, on met un redirect permanent HTTP > HTTPs côté nginx. Sinon c'est source de pb ...

**Comment by vbombaerts** [comment]
Je pense que c'est le cas en valid.

**Comment by vbombaerts** [comment]
Toujours très lent en valid. Par exemple lors de l'édition de https://metawal4.valid.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/1ee5b57f-0c46-49de-83db-01610da25751

Passer de la vue simple à la vue complète échoue après environ 1 min d'attente.

**Comment by davinciagf** [comment]
@vbombaerts as-tu pu retester. L'instance logstash a été supprimée (elle prenait tout le CPU).

**Comment by vbombaerts** [comment]
Lenteurs et délais de réponse toujours problématiques en valid.
On ne demanderait pas une réinstall from scratch de tout l'environnement pour que ce soit une vrai réplique de la prod ?

**Comment by vbombaerts** [comment]
Pas de solution trouvée. Ca n'affecte pas la prod, donc je ferme.
