### ISSUE TITLE
Impossible de charger la doc/test de l'API

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#640]
![image](https://user-images.githubusercontent.com/6093597/128987125-7326fd0f-7c11-4135-891b-26af1e85764f.png)

![image](https://user-images.githubusercontent.com/6093597/128987066-69a490c3-ae4b-492b-9be4-eadc3ddd200c.png)

**Comment by davinciagf** [comment]
Au niveau de la test c'est ok. A vérifier si au déploiement en prod de la dernière version, ce cas se reproduit.

**Comment by vbombaerts** [comment]
Je viens de tester aujourd'hui et c'est de nouveau inaccessible.
https://metawal4.test.wallonie.be/geonetwork/doc/api/index.html

**Comment by vbombaerts** [comment]
Bon, ben parfois c'est là, parfois c'est pas là.

**Comment by vbombaerts** [comment]
Soit on affiche l'analyse des liens, soit on affiche l'API. Si on a choisi l'un plus possible d'avoir l'autre.

**Comment by fxprunayre** [comment]
A déployer et tester, ça devrait être mieux.
