### ISSUE TITLE
Impossible de supprimer l'utilisateur

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#642]
J'ai essayé de supprimer l'utilisateur 34064 en test et voici le message que j'obtiens. Ca veut dire quoi ?

**Comment by fxprunayre** [comment]
L'erreur est "Cannot delete a user that has set a metadata status" ce n'est en effet pas un cas géré. 
On se demande ce qu'on fait des status liés. Options:
* Supprimer les status mais ca risque d'avoir des effets de bords - une fiche approuvé par lui, ne le serait plus :/
* Assigner un utilisateur "nobody" (à créer) ... 
Je regarde.

**Comment by vbombaerts** [comment]
C'est quoi un "metadata status" ?

**Comment by fxprunayre** [comment]
Workflow : approved ...

**Comment by fxprunayre** [comment]
Cf. https://metawal4.test.wallonie.be/geonetwork/srv/fre/admin.console#/dashboard/versioning mais on peut pas les supprimer - enfin pas via l'interface. Faut utiliser l'API ou SQL en base.

**Comment by vbombaerts** [comment]
J'ai fait ça moi ? Je ne savais même pas. Et le workflow n'est même pas activé.

**Comment by fxprunayre** [comment]
Y'a pas que le workflow, c'est tous les événements

**Comment by fxprunayre** [comment]
Cf. https://github.com/titellus/core-geonetwork/pull/9

A tester @davinciagf il faut ajouter un user nobody avec id = 0 dans la migration SQL.
