### ISSUE TITLE
Répertoire de contacts

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#646]
Rétablir un répertoire de contact parmi lequel choisir les points de contact. 
De cette façon ils sont tous répertoriés de la même façon.
Idéalement, les modifications de dénomination devraient pouvoir se faire facilement (DGO3 --> DGARNE --> SPW ARNE)
L'ajout de nouvelles valeurs doit aussi être facile.
Pour l'utilisateur, un mécanisme d'auto-complétion.
Quelle est la meilleure approche ? 
- subtemplate ?
- registre avec ancre ?
- utilisation de l'annuaire SPW + annuaire interne Metawal ?

**Comment by fxprunayre** [comment]
En lien avec https://github.com/SPW-DIG/metawal-core-geonetwork/issues/458

**Comment by marceaulouis** [comment]
voir #458
