### ISSUE TITLE
résultat recherche / titre de la fenêtre non cohérent

### ISSUE THREAD

**Issue by metawaltest** [SPW-DIG/metawal-core-geonetwork#65]
Je vois dans l'onglet du site que j'ai 11 fiches mais elles n'apparaissent pas dans les résultats de recherche

![recherche](https://f.cloud.github.com/assets/6093500/1662795/0d3402c0-5c06-11e3-8960-067c471ff9bd.JPG)

**Comment by fxprunayre** [comment]
Proper fix.

**Comment by vbombaerts** [comment]
Il reste une zone sans info au niveau de la barre. Double tiret à corriger ?
![image 631](https://f.cloud.github.com/assets/6093597/1782407/7bd4c018-68ac-11e3-96d2-db3273ac2c80.png)

**Comment by fxprunayre** [comment]
Appliqué à GN également https://github.com/geonetwork/core-geonetwork/commit/cb3d653da1927f7d1a7044e45fe54c819422bedb.
