### ISSUE TITLE
Conditions d'accès et d'utilisation - coquille

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#651]
Les conditions d'utilisation de type A étendent les CGU. Elle ne les restreignent pas

==> "mais sont restreintes" --> "et sont étendues"

![image](https://user-images.githubusercontent.com/6093597/132534700-d7ef00d6-9ebf-4d31-84b8-26bb8c8558c3.png)

**Comment by vbombaerts** [comment]
Modifier le thésaurus. -->  @vbombaerts 
+ boutons à modifier --> @davinciagf

**Comment by vbombaerts** [comment]
Thésaurus modifié dans les trois environnements

**Comment by davinciagf** [comment]
Au niveau de l'éditeur, on a des listes qui se basent sur les theausrus pour les différentes vues.
Modif en base :  

`UPDATE metadata
SET data = replace(data,
                   '>Les conditions générales d''utilisation s''appliquent mais sont restreintes par les conditions particulières de type A.<',
                   '>Les conditions générales d''utilisation s''appliquent et sont restreintes par les conditions particulières de type A.<')
WHERE data LIKE '%>Les conditions générales d''utilisation s''appliquent mais sont restreintes par les conditions particulières de type A.<%';`

Modif au niveau du fichier de migration vers le Géoportail? https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.0.x/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/present/csw/mw-full.xsl#L188-L191

**Comment by vbombaerts** [comment]
@davinciagf 

Dans le script de migration BD, tu remplaces "mais sont restreintes" par "et sont restreintes". Il faut remplacer par "et sont étendues"

Dans le code, tu as oublié un espace entre le A et la parenthèse https://github.com/SPW-DIG/metawal-core-geonetwork/blob/b703a70052acbd5096dd792d78d00556e1abe9be/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/present/csw/mw-full.xsl#L190

**Comment by vbombaerts** [comment]
Semble OK en valid sur base d'un petit échantillon de fiches

**Comment by vbombaerts** [comment]
Dans Admin > Statistiques et Statut > Analyse de liens, chercher "http://geoportail.wallonie.be/files/documents/ConditionsSPW/DataSPW-CPU-TypeA.pdf"
Sonder les fiches où ces conditions sont référencées.
OK en prod sur base d'un échantillon des fiches.
