### ISSUE TITLE
Moissonnage en prod - impossible de définir un filtre

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#653]
J'ai essayé de configurer le point de moissonnage de l'IGN - Geo.be pour récupérer le fiche Cartoweb et impossible de définir un filtre.
![image](https://user-images.githubusercontent.com/6093597/132667430-b2b2e761-0dbd-4ee1-842d-8e44e9edadae.png)

**Comment by vbombaerts** [comment]
Problème de proxy ?

**Comment by vbombaerts** [comment]
Ca passe en test mais pas en valid ni en prod.

**Comment by davinciagf** [comment]
C'est résolu en prod et en cours pour la valid (la valid n'était pas autorisé à utiliser le proxy)

**Comment by vbombaerts** [comment]
OK pour la prod. Ce point de moissonnage est très capricieux : un coup ça marche, 6 coups ça marche pas...
