### ISSUE TITLE
Moissonnage - la conversion ISO 19139 --> ISO 19115-3 ne se fait pas à la volée

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#654]
J'ai une fiche en ISO 19139 dans un catalogue. http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/6f12973d-9528-4028-a7a2-e68d5a002c56
Je moissonne ce catalogue en ISO 19115-3.
https://metawal4.valid.wallonie.be/geonetwork/srv/fre/admin.console#/harvest
La fiche en ISO 19139 n'apparait pas dans les résultats du moissonnage.

**Comment by vbombaerts** [comment]
EDIT : j'ai converti la fiche ISO19139 --> ISO 19115-3 à l'import. http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/a02aa51a-08a7-4523-ae82-59257e376fa3
J'ai donc en catalogue la même fiche dans les deux standards (uuid différents)
Aucune ne passe au moissonnage.
Ce sont des fiches multilingues. Peut-être chercher de ce côté là.

**Comment by fxprunayre** [comment]
A priori, corrigé avec https://github.com/SPW-DIG/metawal-core-geonetwork/issues/657. On ferme ?

**Comment by vbombaerts** [comment]
Moissonnage ISO 19139 multilingue avec conversion vers 19115-3 est OK maintenant.
