### ISSUE TITLE
Rapport de validation des liens - pas de date

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#655]
Dans le rapport d'analyse des liens, la date de vérification ne s'affiche pas.
![image](https://user-images.githubusercontent.com/6093597/132705468-a0e39c29-a845-4154-89ae-c175b095a4b5.png)

**Comment by fxprunayre** [comment]
Cf. https://github.com/titellus/core-geonetwork/pull/31

A déployer.

**Comment by davinciagf** [comment]
![image](https://user-images.githubusercontent.com/576292/133231756-cba20a66-0fdc-4db5-9809-5b911aee8f2a.png)

**Comment by vbombaerts** [comment]
Env valid : la date n'apparait pas dans le rapport.
Elle est par contre présente dans l'export.

![image](https://user-images.githubusercontent.com/6093597/135069104-188f89ae-f998-4f2c-b551-c344e79c45c0.png)

![image](https://user-images.githubusercontent.com/6093597/135069183-6f0dd4da-3d83-4445-8d48-3739aa0fea81.png)

**Comment by fxprunayre** [comment]
Vérifier que le cache JS a bien été vidé ? admin > tools > vider cache JS & CSS ?

**Comment by vbombaerts** [comment]
Ca change rien

**Comment by vbombaerts** [comment]
Si c'est bon en fait 👍 

![image](https://user-images.githubusercontent.com/6093597/135074091-737a5bfa-50c3-4d62-998c-432ddec0e810.png)
