### ISSUE TITLE
Copier la configuration d'un moissonneur

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#656]
**Is your feature request related to a problem? Please describe.**
Je souhaiterais facilement recopier la configuration des moissonneurs d'un environnement à l'autre + j'ai l'impression que les modifications d'un moissonneur existant ne sont pas toujours enregistrées

**Describe the solution you'd like**
Ajout dans le bas de la fenêtre de configuration du moissonneur un espace où copier/coller la configuration en mode texte. 
Solution similaire au copier/coller existant dans les configurations interface utilisateur

**Comment by fxprunayre** [comment]
Cf. https://github.com/titellus/core-geonetwork/pull/92

**Comment by fxprunayre** [comment]
A déployer et tester

* copier

![image](https://user-images.githubusercontent.com/1701393/150533287-448825e2-b3b1-4c42-8d1c-3801e47db30e.png)


* coller

![image](https://user-images.githubusercontent.com/1701393/150533356-dad968a0-a7ef-49f6-8b9a-c4e4422fd4ec.png)

**Comment by vbombaerts** [comment]
D'abord une typo :
![image](https://user-images.githubusercontent.com/6093597/161715845-06f80a1a-1e92-4cb0-b5fc-10ab65543dd3.png)
_Copier_ --> doit devenir _Coller_

Au niveau de la procédure, l'action de "Coller la configuration" n'a pas le même effet que les options juste au-dessus (catalogue CSW, ...). Pour ces dernières, elles ajoutent un nouveau moissonneur, tandis que l'option "Coller..." écrase la configuration du moissonneur sélectionné par celle du presse-papier.  Ce n'est pas clair que pour coller il faut d'abord créer un moissonneur CSW "vide".

Je propose de clarifier d'une des façons suivantes :
- soit retirer l'option "Coller.." de la colonne de gauche et la déplacer dans la colonne de droite sur la configuration du moissonneur (à côté du bouton copier la configuration). De cette façon l'utilisateur comprend qu'il doit d'abord créer un moissonneur du bon type, puis seulement coller pour écraser la configuration par défaut
- soit que l'option "Coller..." crée en même temps un nouveau moissonneur

**Comment by fxprunayre** [comment]
> Pour ces dernières, elles ajoutent un nouveau moissonneur, tandis que l'option "Coller..." écrase la configuration du moissonneur sélectionné par celle du presse-papier. Ce n'est pas clair que pour coller il faut d'abord créer un moissonneur CSW "vide".

Normalement non. Quand on colle, on a un nouveau moissonneur - uniquement le bouton "save" 

![image](https://user-images.githubusercontent.com/1701393/161719206-f7aabf3d-0ae2-4c1d-8d59-580a681bae8b.png)

Et quand on sauve on en a un nouveau non ?
Tu fais quoi comme manip ?

**Comment by vbombaerts** [comment]
En effet. Erreur de ma part.
