### ISSUE TITLE
Moissonnage géoportail - problème avec fiche ISO 19139

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#659]
Le moissonnage depuis le GP s'arrête à cause d'une erreur avec une fiche ISO 19139 dans Metawal.

```
•	60/997 metadata(s)
•	60 notices lues
•	0 mises à jour
•	0 suppressions
•	Erreurs d'execution : 1
```

L’interruption de la mise à jour est liée à l’appel suivant : 
https://metawal4.test.wallonie.be/geonetwork/srv/fre/csw?REQUEST=GetRecords&SERVICE=CSW&VERSION=2.0.2&OUTPUTSCHEMA=mw&CONSTRAINTLANGUAGE=CQL_TEXT&RESULTTYPE=results&TYPENAMES=csw:Record&STARTPOSITION=61&MAXRECORDS=20&ELEMENTSETNAME=full&SORTBY=identifier:A

Cet appel retourne l’erreur suivante :
```
<ows:ExceptionReport version="1.2.0" xsi:schemaLocation=http://www.opengis.net/ows http://schemas.opengis.net/ows/1.0.0/owsExceptionReport.xsd>
<ows:Exception exceptionCode="NoApplicableCode">
<ows:ExceptionText>
java.lang.RuntimeException: org.fao.geonet.csw.common.exceptions.InvalidParameterValueEx: code=InvalidParameterValue, locator=OutputSchema, message=OutputSchema 'mw' not supported for metadata with '51119' (iso19139). Corresponding XSL transformation 'mw-full.xsl' does not exist for this schema. The record will not be returned in response.
</ows:ExceptionText>
</ows:Exception>
</ows:ExceptionReport>
```

**Comment by vbombaerts** [comment]
Le schema 'mw' est-il encore supporté ?
pour du 19115-3 et du 19139 ?

**Comment by vbombaerts** [comment]
En lien avec  #657 ?

**Comment by davinciagf** [comment]
Le profil 'mw' est utilisé pour le moissonnage du Géoportail  en ISO19139.
Le fichier https://github.com/SPW-DIG/metawal-core-geonetwork/blob/3ceb8f666ae249e91c58c569b0527cfe8a055891/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/present/csw/mw-full.xsl est utilisé pour respecter les règles d'affichage du Geoportail.

**Comment by vbombaerts** [comment]
Ce fichier est utilisé pour transformer du 19115-3 vers du mw. Mais existe-t-il un fichier similaire pour transformer du 19139 en mw ? Moi je ne vois rien. https://github.com/SPW-DIG/metawal-core-geonetwork/tree/3ceb8f666ae249e91c58c569b0527cfe8a055891/schemas/iso19139/src/main/plugin/iso19139/present/csw

**Comment by fxprunayre** [comment]
Corrigé. A déployer.

Pour tester https://metawal4.test.wallonie.be/geonetwork/srv/fre/csw?REQUEST=GetRecordById&SERVICE=CSW&VERSION=2.0.2&OUTPUTSCHEMA=mw&ELEMENTSETNAME=full&id=0fdbe090-bd35-41b1-8835-823eb769eaee

**Comment by davinciagf** [comment]
Déployé en test mais pas en valid

**Comment by vbombaerts** [comment]
OK en valid. Le GP moissonne le 19139

**Comment by vbombaerts** [comment]
OK en prod. https://metawal.wallonie.be/geonetwork/srv/fre/csw?REQUEST=GetRecordById&SERVICE=CSW&VERSION=2.0.2&OUTPUTSCHEMA=mw&ELEMENTSETNAME=full&id=6f12973d-9528-4028-a7a2-e68d5a002c56
