### ISSUE TITLE
Erreur d'affichage Vue par défaut

### ISSUE THREAD

**Issue by geologiewallonie** [SPW-DIG/metawal-core-geonetwork#66]
L'affichage d'une fiche en "Vue par défaut" est mal mis en page. La class "right" est trop large.

![1](https://f.cloud.github.com/assets/6093460/1662781/ce2d965e-5c05-11e3-8d72-75f36d569939.JPG)

**Comment by fxprunayre** [comment]
@davinciagf  semble ok en test. A redéployer
