### ISSUE TITLE
Impossible d'instaurer un point de moissonnage

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#660]
Erreur quand j'essaie d'instaurer un nouveau point de moissonnage.

![image](https://user-images.githubusercontent.com/6093597/134357576-ca33c1dd-1382-4411-8fa7-52e19bebc8c4.png)

**Comment by fxprunayre** [comment]
A déployer. En lien avec le pb de date manquante dans le tableau de bord des liens (https://github.com/titellus/core-geonetwork/pull/31). Ca reste un peu obscur...
