### ISSUE TITLE
La barre d'avancement de l'indexation ne s'affiche plus

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#662]
Dans la version actuellement en valid, la barre d'avancement d'indexation ne s'affiche plus.
Soit ça n'indexe pas, soit ça n'affiche pas la barre. 
J'ai cliqué sur 
![image](https://user-images.githubusercontent.com/6093597/134675340-60964c2b-e934-4baa-aa00-431ed0f1c0d5.png)
et sur 
![image](https://user-images.githubusercontent.com/6093597/134675488-9c922720-deaf-431e-acdc-77e43f18a194.png)

**Comment by fxprunayre** [comment]
A déployer. Problème selon qu'on est en mode debug ou prod.

**Comment by davinciagf** [comment]
A vérifier au déploiement de la version en test où la barre est dispo
![image](https://user-images.githubusercontent.com/576292/137294895-a4fc52ee-5c04-4425-9d50-25ee3a186d4a.png)
