### ISSUE TITLE
Paramètres de la configuration de base du catalogue plus disponibles

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#663]
J'ai voulu modifier une facette dans l'interface de contribution (remplacement de la facette "schema" par "documentStandard". Je n'ai pas réussi parce que la configuration d'utilisateur srv n'est pas disponible. Les paramètre du catalogue principal ne sont plus disponibles non plus.

![image](https://user-images.githubusercontent.com/6093597/135083389-5f624f04-ca73-4ddf-a4be-4532145395c9.png)

![image](https://user-images.githubusercontent.com/6093597/135083276-d0798296-0ff9-46cd-890a-cc6d8fac1b84.png)

**Comment by fxprunayre** [comment]
Si il n'y pas de config pour `srv`, c'est la configuration du code (par défaut) qui s'applique. Tu peux en créer une, si y'a besoin.

**Comment by vbombaerts** [comment]
Avant elle était accessible par défaut. J'ai modifié la config hier en prod (correction d'une facette), puis la mise à jour a été déployée et je ne peux plus la modifier aujourd'hui. C'est pas pratique...

**Comment by davinciagf** [comment]
La config srv n'est plus en DB sur test. J'ai un backup je la remets. Il faudra aussi modifier le code car une condition limite le paramétrage des catalogues aux seuls sous-catalogues.

**Comment by fxprunayre** [comment]
> La config srv n'est plus en DB sur test. J'ai un backup je la remets. Il faudra aussi modifier le code car une condition limite le paramétrage des catalogues aux seuls sous-catalogues.

Si on doit changer la config de srv, j'ai une préférence pour la changer dans github pour que tout le monde utilise la même.

**Comment by vbombaerts** [comment]
> > La config srv n'est plus en DB sur test. J'ai un backup je la remets. Il faudra aussi modifier le code car une condition limite le paramétrage des catalogues aux seuls sous-catalogues.
> 
> Si on doit changer la config de srv, j'ai une préférence pour la changer dans github pour que tout le monde utilise la même.

Si je souhaite changer des facettes sur mon catalogue Metawal je dois donc créer une autre config ? Comment puis-je l'attribuer à mon catalogue Metawal ?

**Comment by fxprunayre** [comment]
> Si je souhaite changer des facettes sur mon catalogue Metawal je dois donc créer une autre config ? Comment puis-je l'attribuer à mon catalogue Metawal ?

La config qui s'appelle srv sera appliquée au catalogue principal.

**Comment by vbombaerts** [comment]
OK. C'était plus clair avant mais je m'y ferai.

**Comment by fxprunayre** [comment]
> OK. C'était plus clair avant mais je m'y ferai.

Tu veux dire quand y'avait toutes les options ?
L'idée c'est que ce soit plus simple - on a uniquement les options qu'on change car souvent on ne change que les facettes.

**Comment by vbombaerts** [comment]
En fait c'est OK. 
Il faudrait peut être juste informer dans les paramètres du catalogue "home" que la config par défaut est srv et que si on veut la changer il faut la créer et changer les paramètres. Parce que là c'est pas évident au premier abord. Sauf erreur de ma part, les boutons enregistrer et supprimer sont inutiles à cet endroit.

![image](https://user-images.githubusercontent.com/6093597/135859389-d36c91f4-1d9a-4133-9990-5301b3414b69.png)

**Comment by fxprunayre** [comment]
> Il faudrait peut être juste informer dans les paramètres du catalogue "home" que la config par défaut est srv

Oui on peut rajouter un message pour ça.


> Sauf erreur de ma part, les boutons enregistrer et supprimer sont inutiles à cet endroit.

Normalement, on devrait pouvoir changer le nom du catalogue principal ici. Mais on doit avoir un souci dans la base.

![image](https://user-images.githubusercontent.com/1701393/136905592-04963c7d-7ceb-45d4-86a1-3a202dd42068.png)


```sql

INSERT INTO sourcesdes (iddes, label, langid)
SELECT s.value, 'Metawal', l.id
FROM settings s, languages l WHERE s.name = 'system/site/siteId';

```

@davinciagf  à tester.

**Comment by davinciagf** [comment]
Joué en test : 
![image](https://user-images.githubusercontent.com/576292/139077483-d7645605-dc21-439d-bd83-97effd84eee6.png)
Intégré dans le script de migration de la v4.0.7
