### ISSUE TITLE
Batch editing - rechercher/remplacer

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#666]
Parfois on a besoin de faire des changements en masse sur une sélection des fiches du catalogue et les options de l'édition en série ne suffisent pas. Est-il envisageable d'ajouter une option permettant de faire une opération d'édition en série qui soit l'équivalent d'un rechercher/remplacer dans le xml. Cela permettrait de remplacer des fragments de valeurs, ce qui à ma connaissance n'est pas possible avec du Xpath. Ca évite de passer par un changement en base.

Par exemple : 
- remplacer http://metawal par https://metawal
- remplacer DGO3 par DGARNE

**Comment by fxprunayre** [comment]
Search & replace avec la base de données Cf. https://github.com/titellus/core-geonetwork/pull/55

On pourrait aussi ajouter un preview avec aussi un diff avant d'appliquer un process ?

![image](https://user-images.githubusercontent.com/1701393/139407968-392bb12a-24e0-4f76-8b73-83276dedfc59.png)

**Comment by fxprunayre** [comment]
Search & replace à tester https://metawal4.test.wallonie.be/geonetwork/srv/eng/catalog.edit#/batchedit

A faire: ajouter la possibilité de copier/coller une config xpath

**Comment by vbombaerts** [comment]
La fonctionnalité est montée en prod sans testing préalable et lors de son utilisation j'ai eu 2 fois une indisponibilité de Metawal. Probablement quand on demande d'effectuer un search/replace sur une chaîne qui n'existe pas dans les fiches. A explorer plus avant en environnement de test.

**Comment by vbombaerts** [comment]
Les chaînes de caractère ne sont pas traduites en français. 

![image](https://user-images.githubusercontent.com/6093597/153871809-23af30ad-0f54-4508-a06e-ab5c33c69aa3.png)

**Comment by vbombaerts** [comment]
Serait-il possible dans le rapport de ne marquer comme modifiées (et de ne changer la date de modification) que les fiches qui ont été réellement modifiées ?
Egalement, dans le rapport de traitement, en dessous de la ligne "traitées", ajouter une ligne "modifiées" et une ligne "non-modifiées" ou qqch du genre. 

![image](https://user-images.githubusercontent.com/6093597/153872361-c2f06177-cd5a-441d-aa3c-e59705916842.png)

**Comment by vbombaerts** [comment]
Question : le traitement en batch induit-il une réindexation automatique des fiches ?

**Comment by fxprunayre** [comment]
> Question : le traitement en batch induit-il une réindexation automatique des fiches ?

Normalement oui. Tu as repéré des cas où ce n'est pas le cas? C'est un paramètre de l'API par défaut true

![image](https://user-images.githubusercontent.com/1701393/154066966-b25bf5f3-421e-412a-b0cb-958631fd08a0.png)

**Comment by fxprunayre** [comment]
> Serait-il possible dans le rapport de ne marquer comme modifiées (et de ne changer la date de modification) que les fiches qui ont été réellement modifiées ?

C'était dans les TODO https://github.com/titellus/core-geonetwork/pull/55/files#diff-b0e774db2ed16acaf4ddee05558b415842c9394e8b67ff1e7b32b827d36a04dfR113-R115

**Comment by vbombaerts** [comment]
> > Question : le traitement en batch induit-il une réindexation automatique des fiches ?
> 
> Normalement oui. Tu as repéré des cas où ce n'est pas le cas? C'est un paramètre de l'API par défaut true
> 

Non. C'est juste que quand tu fais un rechercher/remplacer qui porte sur 100 fiches et que tu ne trouves la valeur que dans 5 fiches ça ne vaut pas la peine d'indexer les 95 autres. C'est en lien avec l'idée d'avoir plus de finesse sur les fiches qui ont réellement changé.

**Comment by fxprunayre** [comment]
https://github.com/titellus/core-geonetwork/pull/135. A déployer et tester.

**Comment by vbombaerts** [comment]
- Traductions toujours pas OK (rechercher/remplacer + rapport)
- La modification à appliquer apparait en double 
![image](https://user-images.githubusercontent.com/6093597/155506505-d6292b54-4b28-45c4-95d2-b95da31ce6d0.png)
- Mise en page du rapport (Edge)
![image](https://user-images.githubusercontent.com/6093597/155507333-db2d9660-77fb-4c11-809d-617d698ff41b.png)

**Comment by fxprunayre** [comment]
Pour moi la mise en page ça va 

![image](https://user-images.githubusercontent.com/1701393/155531180-beed5b2d-d5c8-40cd-b078-54ef2c96589a.png)

Les traductions en français sont à finaliser mais on n'a plus les clés de traduction, on a l'anglais.

**Comment by vbombaerts** [comment]
En test, j'ai fait plusieurs modifs en batch parfois sur des grands ensembles de fiches (200 fiches, dont 150 à modifier). Tout tourne bien et rapidement. Aucun plantage comme c'était le cas en prod.

**Comment by vbombaerts** [comment]
En valid : la modification à appliquer apparaît en double
![image](https://user-images.githubusercontent.com/6093597/161791564-2dc7f07e-31e0-402a-b0b3-19ddc65b8edb.png)

J'ai lancé la modif en batch sur 20 fiches. Après 10 minutes, toujours pas de retour (pas de rapport et icône qui tourne à côté du bouton enregistrer)
J'ai vérifié certaines fiches qui faisaient partie de la sélection et elles ont bien été modifiées (pas de vérif exhaustive). --> je ne sais pas si le process de modification se bloque suite à des conditions particulières ou s'il se déroule jusqu'au bout et que c'est la création du rapport qui bloque.

Quand le process est bloqué, l'application est indisponible : impossible d'ouvrir une fiche, d'afficher la page de recherche ou la console d'admin...

**Comment by vbombaerts** [comment]
Remarque pour moi : Attention que ce type de modification en full text (texte "19115") pourrait modifier certaines balises, notamment les déclarations de namespace !

**Comment by fxprunayre** [comment]
> Quand le process est bloqué, l'application est indisponible : impossible d'ouvrir une fiche, d'afficher la page de recherche ou la console d'admin...

Ce pourrait être bien de regarder dans les outils dev du navigateur > Réseau et voir quel est le retour de la requête (http status, erreur ?, proxy ?, ...)

**Comment by vbombaerts** [comment]
![image](https://user-images.githubusercontent.com/6093597/162192884-560c191d-7aaa-449a-a848-3cc74230722c.png)

**Comment by vbombaerts** [comment]
et ensuite, si je veux basculer vers la page de recherche
![image](https://user-images.githubusercontent.com/6093597/162193408-86f597af-4b26-4d9c-b178-327cd79ab777.png)

**Comment by vbombaerts** [comment]
En prod :
20 fiches OK
60 fiches OK
220 fiches KO - 504 Gateway Time-out après 10 minutes d'attente

**Comment by vbombaerts** [comment]
Nécessité de développer un mode asynchrone pour gérer ce problème - #739
