### ISSUE TITLE
Chargement des fichiers attachés en https

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#667]
Quand je suis sur metawal en https et que je charge un document, l'adresse est encodée en http.
Peut-être est-ce juste parce qu'on n'a pas encore complètement basculé.
![image](https://user-images.githubusercontent.com/6093597/136345657-bbe00759-b7f8-4b8e-a59d-5aa1fdb983c6.png)

**Comment by davinciagf** [comment]
La prod est déjà en https ?
Dans l'admin de la prod, au niveau des settings du catalog, le catalogue est référencé en http. 
Si on modifie la config, l'ajout d'un lien sera en https (voir test)

**Comment by vbombaerts** [comment]
Modifié.
