### ISSUE TITLE
Titre de l'application et agrandissement des caractères

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#67]
Quand on agrandit les caractères, le titre recouvre en partie le logo wallon. comportement souhaité ==> retour à la ligne plus à droite en dessous de "Metawal", sans recouvrir le logo.
![image 618](https://f.cloud.github.com/assets/6093597/1662819/85507630-5c06-11e3-9eec-4b6e1c10b1f7.png)

**Comment by fxprunayre** [comment]
See https://github.com/spacebelGIS/metawal-core-geonetwork/commit/bcc0e4d59625867873e61ee2b725468d8a0e88bc
