### ISSUE TITLE
Passage des adresses http://metawal en https://metawal

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#670]
Il faut aussi prévoir un script pour passer toutes les adresses http://metawal en https://metawal

_Originally posted by @vbombaerts in https://github.com/SPW-DIG/metawal-core-geonetwork/issues/565#issuecomment-934423773_

**Comment by davinciagf** [comment]
`UPDATE metadata SET data = replace(data, 'http://metawal.wallonie.be/', 'https://metawal.wallonie.be/') WHERE data LIKE '%http://metawal.wallonie.be/%';`

**Comment by vbombaerts** [comment]
J'ai joué cette requête en test et je retrouve encore des `http://metawal`
Bizarre...

![image](https://user-images.githubusercontent.com/6093597/137462934-d992a6f3-f966-4a28-8558-bae9067ed04c.png)

Est-ce que la clause WHERE est nécessaire ? 
Est-ce qu'il ne faut pas prendre uniquement le `http://metawal` pour si jamais on retrouve aussi des `http://metawal4.valid` `http://metawal4.test` et d'autres brols pareils ?

Dois-je faire la modif aussi dans les thésauri et les recharger ?

**Comment by davinciagf** [comment]
Vérifier les url vers metawal dans les différents thesaurus (http => https) : test, valid et prod

**Comment by vbombaerts** [comment]
> Vérifier les url vers metawal dans les différents thesaurus (http => https) : test, valid et prod

Thésauri mis à jour dans les 3 environnements.
