### ISSUE TITLE
Indexation des "Autres appellations ou acronymes"

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#672]
Les jeux de données sont souvent connus par leurs noms techniques ou leurs noms abrégés encodés dans "Autres appellations ou acronymes" (alternate title - plusieurs occurrences possibles). Est-il possible de les indexer et de leur donner un poids équivalent à celui du titre dans les recherches ? Comment ?

**Comment by fxprunayre** [comment]
Alternate title est indexé dans "resourceAltTitleObject.default" (cf. https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.0.x/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl#L286) donc on peut l'ajouter dans querybase. A tester.

**Comment by vbombaerts** [comment]
Ici aussi, OK en test mais pas en prod.

Test
![image](https://user-images.githubusercontent.com/6093597/137125111-58bb5a16-be91-4c21-8855-eee9fa41e123.png)

Prod
![image](https://user-images.githubusercontent.com/6093597/137125161-1277a1da-50e9-4be4-8532-00ac33b1c690.png)

J'attends donc le déploiement de la prochaine version.

**Comment by fxprunayre** [comment]
eg. http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/search?any=%22IR%20Orthos%202018%22
