### ISSUE TITLE
Modification des paramètres de recherche

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#673]
J'ai adapté la structure de la requête comme suit pour pouvoir rechercher sur l'id des fiches.
`any:(${any}) resourceTitleObject.default:(${any})^2 _id:(${any})^2`
Cette configurations sera-t-elle conservée à la prochaine mise à jour ?

**Comment by fxprunayre** [comment]
Il serait préférable de copier depuis la config par défaut (qui correspond à la version de l'appli) cf.
https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.0.x/web-ui/src/main/resources/catalog/js/CatController.js#L139 (peut être quelquechose à ajouter dans l'interface)

Aprés, le champ uuid est copié dans any.common cf.
https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.0.x/web/src/main/webResources/WEB-INF/data/config/index/records.json#L1534-L1537

Donc une recherche sur l'UUID (exact match) devrait retourner la fiche correspondante, non?

**Comment by vbombaerts** [comment]
> Donc une recherche sur l'UUID (exact match) devrait retourner la fiche correspondante, non?

Pas dans la version déployée en prod.
C'est OK en test. Donc, ce n'est pas nécessaire de l'ajouter dans la config par défaut.
