### ISSUE TITLE
Suggérer l'ajout d'un lien vers la page de monitoring du service

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#674]
Spatineo est un outil qui effectue le monitoring des services. Chaque service mentionné dans le "Spatineo Directory" fait l'objet d'un rapport de disponibilité disponible à travers une page html.
Exemple : https://directory.spatineo.com/service/152748 

L'idée est de voir si on peut automatiquement ajouter un service à ce directory (ou outil équivalent) et encoder l'adresse de la page dans la fiche de MD. Actuellement je l'ai fait pour quelques services manuellement.

L'ajout serait déclenché à travers le mécanisme de suggestion.

**Comment by fxprunayre** [comment]
Formulaire d'ajout http://api.spatineo.com/monitor/add.html
DQ paper https://revistasipgh.org/index.php/rcar/article/download/692/789/
Encodage: standaloneQualityReport + simple Usability element (for XSD validation)

**Comment by fxprunayre** [comment]
See https://github.com/geonetwork/core-geonetwork/pull/6298

**Comment by vbombaerts** [comment]
> Formulaire d'ajout http://api.spatineo.com/monitor/add.html DQ paper https://revistasipgh.org/index.php/rcar/article/download/692/789/ Encodage: standaloneQualityReport + simple Usability element (for XSD validation)

Merci pour les références mais je n'ai vu que des constats, pas de proposition. Idem ici (en espagnol) : https://revistasipgh.org/index.php/rcar/article/view/178/185

**Comment by davinciagf** [comment]
https://github.com/geonetwork/core-geonetwork/pull/6298 testé, à merger dans MW

**Comment by davinciagf** [comment]
Dispo sur MW

**Comment by vbombaerts** [comment]
Voir #740

**Comment by marceaulouis** [comment]
Processus ne fonctionne pas en prod :

testé sur quelques fiches, processus tourne 2 secondes, rien n'est ajouté en qualité. Pas de message d'erreur. Spatineo testé en parallèle et fonctionne pour les services testés

**Comment by davinciagf** [comment]
Erreur :

2022-07-05 14:29:16,974 ERROR [geonetwork.spatineo] - Registration failed for https://geoservices.wallonie.be/arcgis/services/MOBILITE/CPDT/MapServer/WMSServer?request=GetCapabilities&service=WMS after 0 calls. Error: api.spatineo.com: Name or service not known
2022-07-05 14:29:16,974 ERROR [geonetwork.spatineo] - Registration not finalized for https://geoservices.wallonie.be/arcgis/services/MOBILITE/CPDT/MapServer/WMSServer?request=GetCapabilities&service=WMS after 0 calls. Increase number of calls to the API.

Cela doit venir du serveur qui n'a pas accès à spatineo (cf inspire). Je demande à Didier de vérifier

**Comment by davinciagf** [comment]
PR GN à réaliser - Introduire modif pour utilisation du proxy

**Comment by marceaulouis** [comment]
Reporter sur la 4.2.1

**Comment by davinciagf** [comment]
PR https://github.com/geonetwork/core-geonetwork/pull/6453
