### ISSUE TITLE
Moissonnage de geo.be

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#676]
Lorsqu'on moissonne une fiche provenant de l'IGN, on récupère une fiche ISO19139 mulitlingue.

Le GP ne gère pas les fiches multilingues.
![image](https://user-images.githubusercontent.com/6093597/137500043-ccc6f083-43e2-4bea-a16b-b8481279dab1.png)

Donc on voudrait faire une modification post-moissonnage pour rendre la fiche unilingue.
Accessoirement on voudrait remapper/supprimer/ajouter certaines infos.

La piste d'une édition en série définie au point de moissonnage a été évoquée en réunion. C'est un mécanisme utilisé à l'IFREMER.

**Comment by vbombaerts** [comment]
Exemples de balises multilingues
```
               <gmd:title xsi:type="gmd:PT_FreeText_PropertyType">
                  <gco:CharacterString>CartoWeb.be</gco:CharacterString>
                  <gmd:PT_FreeText>
                     <gmd:textGroup>
                        <gmd:LocalisedCharacterString locale="#EN">CartoWeb.be</gmd:LocalisedCharacterString>
                     </gmd:textGroup>
                     <gmd:textGroup>
                        <gmd:LocalisedCharacterString locale="#FR">CartoWeb.be</gmd:LocalisedCharacterString>
                     </gmd:textGroup>
                     <gmd:textGroup>
                        <gmd:LocalisedCharacterString locale="#NL">CartoWeb.be</gmd:LocalisedCharacterString>
                     </gmd:textGroup>
                     <gmd:textGroup>
                        <gmd:LocalisedCharacterString locale="#DE">CartoWeb.be</gmd:LocalisedCharacterString>
                     </gmd:textGroup>
                  </gmd:PT_FreeText>
               </gmd:title>
```

```
         <gmd:organisationName xsi:type="gmd:PT_FreeText_PropertyType">
            <gco:CharacterString>National Geographic Institute</gco:CharacterString>
            <gmd:PT_FreeText>
               <gmd:textGroup>
                  <gmd:LocalisedCharacterString locale="#EN">National Geographic Institute</gmd:LocalisedCharacterString>
               </gmd:textGroup>
               <gmd:textGroup>
                  <gmd:LocalisedCharacterString locale="#FR">Institut géographique national</gmd:LocalisedCharacterString>
               </gmd:textGroup>
               <gmd:textGroup>
                  <gmd:LocalisedCharacterString locale="#NL">Nationaal Geografisch Instituut</gmd:LocalisedCharacterString>
               </gmd:textGroup>
               <gmd:textGroup>
                  <gmd:LocalisedCharacterString locale="#DE">Nationales geographisches Institut</gmd:LocalisedCharacterString>
               </gmd:textGroup>
            </gmd:PT_FreeText>
         </gmd:organisationName>
```

**Comment by vbombaerts** [comment]
On souhaite moissonner de façon plus systématique le catalogue geo.be pour les données concernant le territoire wallon
- configurer le point de moissonnage avec un filtre sur les données intersectant la BBOX de la Wallonie
- faire des modifications des fiches pour qu'elles "s'affichent bien" dans Metawal et le géoportail (modifications à définir)

**Comment by vbombaerts** [comment]
@vbombaerts Faire une analyse comparative du contenu des fiches geo.be et Metawal pour repérer les ajouts/modifications dans le script

**Comment by fxprunayre** [comment]
Cf. https://github.com/titellus/core-geonetwork/pull/142. Configurer le moissonneur avec `ISO19139-to-ISO19115-3-2018-with-languages-refactor?defaultLanguage=fre&others=none` pour rendre la fiche monolingue en français.

A déployer et tester.

**Comment by fxprunayre** [comment]
A vérifier https://metawal4.test.wallonie.be/geonetwork/srv/eng/admin.console#/harvest

![image](https://user-images.githubusercontent.com/1701393/155524257-f37cbce5-ded0-4af8-b6bb-1fbfbd48926f.png)

**Comment by vbombaerts** [comment]
Comparaison d'une fiche de **service** moissonnée du portail geo.be
- moissonnage 19139 : https://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/0fdbe090-bd35-41b1-8835-823eb769eaee
- moissonnage 19139 + transformation 19115 : https://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/b1976d65-f16c-4708-91b6-1898e2aa2e917
- moissonnage 19139 + transformation 19155 + transformation multilingue --> français : https://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/be6e60f2-b2a5-43fe-b748-d2350e457645

Trois observations :
1. Lorsque dans la fiche originale multilingue la valeur pour le fr est vide, le champ dans la fiche unilingue est vide. Est-il possible d'avoir un mécanisme qui va alors chercher la valeur de la langue par défaut ? Ex: Le nom des thésaurus n'est indiqué que dans la langue par défaut, le mot-clé infoMapAccessService n'est présent qu'en anglais.
![2022-02-25 13_17_22-Window](https://user-images.githubusercontent.com/6093597/155753361-bda42dba-0db6-4503-8ef0-69eb504cb7dc.png)
![2022-02-25 13_17_51-Window](https://user-images.githubusercontent.com/6093597/155753395-8b82af62-6170-41de-beb8-9bff84aa58d9.png)
![2022-02-25 13_18_06-Window](https://user-images.githubusercontent.com/6093597/155753432-eb4fb5b9-33bb-4a5b-ad7f-13b768445b6f.png)


![2022-02-25 13_33_59-Window](https://user-images.githubusercontent.com/6093597/155752718-196cb536-b869-4255-80f1-a785e539b11b.png)
![2022-02-25 13_33_45-Window](https://user-images.githubusercontent.com/6093597/155752750-50c2fa2a-6b54-47bd-b6d0-efbef0762a57.png)
![2022-02-25 13_34_11-Window](https://user-images.githubusercontent.com/6093597/155752790-740231e5-d1f7-4a93-a953-a330aa5e9dd1.png)



3. Mots-clés : Comportement bizarre pour le thésaurus INSPIRE : aucune valeur en 19139 et 19115 multilingue (les valeurs sont présentes dans le xml) et deux valeurs pour l'ISO 19115-unilingue
![2022-02-25 13_37_35-Window](https://user-images.githubusercontent.com/6093597/155752879-df03c8bb-2759-4b68-8928-eb6a03063f10.png)
![2022-02-25 13_37_27-Window](https://user-images.githubusercontent.com/6093597/155752921-3316dade-57f7-473a-92f8-6cea7aa727bd.png)
![2022-02-25 13_37_57-Window](https://user-images.githubusercontent.com/6093597/155752957-f3472b36-2324-47d7-b8d8-4c4112d62db8.png)


4. Qualité-Conformité INSPIRE : perte de l'URL qui référence la spécification
![2022-02-25 13_55_39-Window](https://user-images.githubusercontent.com/6093597/155753115-01462bc7-c31b-4a51-9874-bedbd9b93bb3.png)
![2022-02-25 13_55_58-Window](https://user-images.githubusercontent.com/6093597/155753141-83b3b292-87d6-4f13-ad7f-517e31978a80.png)
![2022-02-25 13_56_16-Window](https://user-images.githubusercontent.com/6093597/155753163-53de08de-e58d-4d38-9fdc-339790f37c0c.png)


Si metawal4.test revient je testerai une fiche de donnée.

EDIT : J'ai oublié de tester la section métadonnées - je l'ai testée au niveau d'une fiche de donnée.

**Comment by vbombaerts** [comment]
Analyse de la conversion sur une fiche de **donnée** issue de geo.be
-  19139 : https://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/1f8bd0da-4e6b-4482-8aa4-c4375f575ea4
- moissonnage 19139 + transformation 19115 : https://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/eae2c79b-e840-4e18-9813-d8bf4f54c056
- moissonnage 19139 + transformation 19155 + transformation multilingue --> français : https://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/1e76e6f4-f4fb-4541-a8b4-1a940bdd56b8

### Remarques

1. Si pas de valeur encodée pour la langue choisie, utiliser la valeur de la langue par défaut (mots-clés, nom thésaurus, nom et description des ressources en ligne etc)
![image](https://user-images.githubusercontent.com/6093597/155758080-3238f85b-9acb-4e51-97b5-38a1dfc2a1bc.png)
![image](https://user-images.githubusercontent.com/6093597/155758114-ee06b6d4-2252-4952-ad55-71b0b7392296.png)
![image](https://user-images.githubusercontent.com/6093597/155758415-c4f6a91a-4835-4bcf-93fb-4b30b9343354.png)

2. Mot-clé "INSPIRE feature concept dictionnary" : aucune valeur n'apparait pour 19139 et 19115 multilingue, mais elles apparaissent pour le 19115fr 
![image](https://user-images.githubusercontent.com/6093597/155758488-8b801640-fe15-49fe-a8e6-168572fff375.png)
![image](https://user-images.githubusercontent.com/6093597/155758569-8c15d273-e415-4d4d-b833-4524ca2bfdd0.png)
![image](https://user-images.githubusercontent.com/6093597/155758744-28cc01b1-f1da-406e-9b67-732a2b857e28.png)

3. Encodage de caractères : UTF8 devient 8859part1
![image](https://user-images.githubusercontent.com/6093597/155759639-6421a86b-77f1-449f-b8a0-3972f8b5261e.png)
![image](https://user-images.githubusercontent.com/6093597/155759747-989ab1b8-2b8f-4522-9dc7-6b353a85186e.png)
![image](https://user-images.githubusercontent.com/6093597/155759797-68705c95-d4a2-4810-96f0-f92a763bf876.png)

4. Section métadonnées : ISO 19115 multilingue : la langue par défaut (anglais) est répétée en langue supplémentaire
![image](https://user-images.githubusercontent.com/6093597/155761411-d1a6e3d0-a5e8-4d09-bbdc-4e007a51c44a.png)
![image](https://user-images.githubusercontent.com/6093597/155761474-e460b75b-3e99-41e2-ad32-205b95821d54.png)

5. La norme de métadonnées devrait être forcée si on fait une transformation
6. Le lien vers la métadonnée originale devrait pointer vers le catalogue source et pas Metawal (ou lie lien vers la référence de métadonnée alternative, il faut que je revoie les définitions de l'ISO.)

**Comment by vbombaerts** [comment]
Et surtout, première remarque : Travail incroyable, merci beaucoup !!!

**Comment by vbombaerts** [comment]
@vbombaerts Un point qui reste à tester est si lors de l'import de groupes de fiches liées entre-elles dans le catalogue source, les liaisons sont préservées.

**Comment by fxprunayre** [comment]
> Si pas de valeur encodée pour la langue choisie, utiliser la valeur de la langue par défaut (mots-clés, nom thésaurus, nom et description des ressources en ligne etc)

C'est bizarre non de mélanger les langues ?

> Mot-clé "INSPIRE feature concept dictionnary" : aucune valeur n'apparait pour 19139 et 19115 multilingue, mais elles apparaissent pour le 19115fr

C'est lié à la recherche du thésaurus. Le libellé n'étant qu'en anglais "INSPIRE feature concept dictionary", une fois la fiche en FR, il ne trouve plus le thésaurus. Ça pourrait faire pencher pour le cas précédent de mettre la langue par défaut dans la nouvelle langue par défaut s'il n'y a pas de valeur...

> Encodage de caractères : UTF8 devient 8859part1

C'est bizarre dans le XML c'est bien UTF8.
https://metawal4.test.wallonie.be/geonetwork/srv/api/records/1e76e6f4-f4fb-4541-a8b4-1a940bdd56b8/formatters/xml

> Section métadonnées : ISO 19115 multilingue : la langue par défaut (anglais) est répétée en langue supplémentaire

Dans GN on fait ça pour pouvoir gérer des annuaires multilingues.

> La norme de métadonnées devrait être forcée si on fait une transformation

C'est pas prévu par la conversion 139 > 115-3. A ajouter sans doute.

> Le lien vers la métadonnée originale devrait pointer vers le catalogue source et pas Metawal (ou lie lien vers la référence de métadonnée alternative, il faut que je revoie les définitions de l'ISO.)

C'est pas une notion qui existe en 139 donc c'est un peu compliqué ...
Ce serait peut être plus une notion à "calculer" pour les fiches moissonnées ...

**Comment by vbombaerts** [comment]
> > Si pas de valeur encodée pour la langue choisie, utiliser la valeur de la langue par défaut (mots-clés, nom thésaurus, nom et description des ressources en ligne etc)
> 
> C'est bizarre non de mélanger les langues ?

C'est peut-être mieux d'avoir une valeur en langue par défaut que rien, non ? Si la valeur fr n'est pas présente, c'est peut-être que l'éditeur de la fiche juge que ce n'est pas nécessaire de traduire car c'est compréhensible ou c'est une valeur technique.
Si on veut pouvoir décider si on laisse blanc ou si on force la valeur par défaut, c'est peut-être un paramètre à ajouter à la transformation ?

> > La norme de métadonnées devrait être forcée si on fait une transformation

> C'est pas prévu par la conversion 139 > 115-3. A ajouter sans doute.

>> Le lien vers la métadonnée originale devrait pointer vers le catalogue source et pas Metawal (ou lie lien vers la référence de métadonnée alternative, il faut que je revoie les définitions de l'ISO.)

> C'est pas une notion qui existe en 139 donc c'est un peu compliqué ...
Ce serait peut être plus une notion à "calculer" pour les fiches moissonnées ...

Oui, 2 notions à ajouter dans la conversion 139 vers 115-3

**Comment by fxprunayre** [comment]
> C'est peut-être mieux d'avoir une valeur en langue par défaut que rien, non ?

Ajout d'une option pour la copie de la valeur de l'ancienne langue principale si la valeur est vide
`ISO19139-to-ISO19115-3-2018-with-languages-refactor?defaultLanguage=fre&others=ger,eng&copyPreviousDefaultIfEmpty=true`

**Comment by vbombaerts** [comment]
Je n'arrive plus à éditer les paramètres de la transformation dans la définition du moissonneur.

**Comment by bfrichet3** [comment]
@vbombaerts et @fxprunayre ,

les valeurs qui manquent en locale correspondent à des erreurs ou à des manquements dans le template de nos fiches et effectivement, le contenu était néanmoins jugé intelligible en l'état.

Je vais faire corriger cela dans les meilleurs délais.

Bonne journée

**Comment by vbombaerts** [comment]
@fxprunayre Dans les fiches originales TransStat, certaines valeurs sont encodées à la fois en Anchor et FreeText. C'est correct comme ça ? Parce que du coup la même valeur est répétée 2 fois pour ces éléments.

Fiche originale :
https://www.geo.be/metadataServices/rest/catalogs/1/resources/790547ae-fe75-11eb-b7c8-7478273ff935/xml

```
<gmd:name xsi:type="gmd:PT_FreeText_PropertyType">
<gmx:Anchor xmlns:gmx="http://www.isotc211.org/2005/gmx" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://www.iana.org/assignments/media-types/text/csv">CSV</gmx:Anchor>
<gmd:PT_FreeText>
<gmd:textGroup>
<gmd:LocalisedCharacterString locale="#EN">CSV</gmd:LocalisedCharacterString>
</gmd:textGroup>
</gmd:PT_FreeText>
</gmd:name>
```

Moissonnage MW :
https://metawal4.valid.wallonie.be/geonetwork/srv/api/records/790547ae-fe75-11eb-b7c8-7478273ff935/formatters/xml?approved=true
```
<cit:title xsi:type="gmd:PT_FreeText_PropertyType">
<gcx:Anchor xlink:href="https://www.iana.org/assignments/media-types/text/csv">CSV</gcx:Anchor>
<gcx:PT_FreeText>CSV</gcx:PT_FreeText>
</cit:title>
```
![image](https://user-images.githubusercontent.com/6093597/160143982-7d7cc18d-703b-4ad5-91e2-ac2613542eda.png)

Idem dans le GP
![image](https://user-images.githubusercontent.com/6093597/160144067-131b1094-9917-4499-a793-6bbb5712ee58.png)

**Comment by fxprunayre** [comment]
> C'est correct comme ça ?

Non, du coup c'est lié à la transformation des langues ?

**Comment by vbombaerts** [comment]
C'est encodé comme ça dans la fiche originale en ISO 19139 sur geo.be 
Donc j'imagine que c'est une erreur sur geo.be.

**Comment by fxprunayre** [comment]
Non l'encodage geo.be est bon - on peut substituer un CharacterString par une Anchor. Par contre quand on supprime les traductions, on devrait pas avoir l'élément `gcx:PT_FreeText`. Je vais regarder.

**Comment by vbombaerts** [comment]
Les fiches moissonnées de geo.be apparaissent correctement dans l'interface Metawal mais impossible de les trouver dans l'interface Kibana. Une idée ?

https://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/search?isTemplate=n&resourceTemporalDateRange=%7B%22range%22:%7B%22resourceTemporalDateRange%22:%7B%22gte%22:null,%22lte%22:null,%22relation%22:%22intersects%22%7D%7D%7D&sortBy=relevance&from=1&to=30&languageStrategy=searchInThatLanguage:fre&any=transstat

https://metawal4.test.wallonie.be/geonetwork/dashboards/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15y,to:now))&_a=(columns:!(),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:gn-records,key:tag.default,negate:!f,params:(query:TransStat),type:phrase),query:(match_phrase:(tag.default:TransStat)))),index:gn-records,interval:auto,query:(language:kuery,query:''),sort:!(!(dateStamp,desc)))

**Comment by fxprunayre** [comment]
La requête GN est

```
GET _search
{
  "query": {
  "query_string": {
    "query": "(any.langfre:(transstat) OR any.common:(transstat) OR resourceTitleObject.langfre:(transstat)^2 OR resourceTitleObject.langfre:\"transstat\"^6)"
  }
  }
}
```


ça
```
GET _search
{
  "query": {
    "query_string": {
      "default_field": "",
      "query": """any.\*:transstat"""
    }
  }
}
```
marche aussi


Mais dans l'interface, toujours 1 seule fiche ! `any.*:transstat` ne fonctionne pas non plus.

```
GET _search
{
  "_source": [
    "dateStamp"], 
  "query": {
  "query_string": {
    "query": "(any.langfre:(transstat) OR any.common:(transstat))"
  }
  }
}
```
En fait y'a pas de dateStamp, c'est normal ? Donc pas de match dans la période.

**Comment by vbombaerts** [comment]
Dans les fiches moissonnées 19115-3, il n'y a pas de date de révision pour la fiche. Uniquement une date de création.
Dans les fiches originales 19139, on a un datestamp qui correspond à la date de dernière mise à jour de la fiche.

==> Probablement qu'il faut modifier le mapping ISO 19139 --> ISO 19115-3 pour ajouter le datestamp dans la date de révision. Je ne sais pas si il faut du coup le retirer de la date de création ; je ne sais pas par qui/quoi cette valeur est utilisée. 

Autre possibilité : définir le champ temporel de l'index comme la date de création de la fiche et non sa date de révision

**Comment by vbombaerts** [comment]
Création d'un nouveau ticket pour le problème du datestamp
