### ISSUE TITLE
Statistiques sur les gestionnaires

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#677]
Objectif : Afficher des statistiques consolidées sur les gestionnaires pour des niveaux d'agrégation différents.

Nous avons déjà une facette sur les gestionnaires SPW qui permet de savoir combien de données sont fournies par chaque gestionnaire SPW aux différents niveaux d'agrégation.

![image](https://user-images.githubusercontent.com/6093597/137502214-970cd3ce-35fe-4d9e-9525-a09dd388f18c.png)

On voudrait afficher le même genre de stats dans Kibana :
- nombre de fiches par niveau d'agrégation
- nombre de gestionnaires par niveau d'agrégation (en se basant sur les adresses email pour les compter)

Pour le moment, le "Secrétariat Général" compte un niveau de plus que les autres entités de même niveau, mais on pourrait contourner en créant une entité "Secrétariat général_SPW Digital" et une entité "Secrétariat général_SPW Support"

**Comment by vbombaerts** [comment]
Une idée ?

**Comment by fxprunayre** [comment]
https://metawal.wallonie.be/geonetwork/dashboards/goto/d9faa960-e25a-11ec-9c43-0f70b8f525db

Ce n'est pas un arbre mais ça répond un peu au besoin.
On a tenté de faire un tableau avec 4 niveaux mais du coup les contacts n'ayant pas les 4 niveaux ne sont pas visible (même avec missing). Cf. les aggrégats désactivés
