### ISSUE TITLE
Impossible d'accéder à certains sous-registres INSPIRE en https

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#678]
**Depuis la test** impossible d'accéder au sous-registre
- INSPIRE metadata code list register
Aucun message d'erreur, ça tourne juste dans le vide. Les autres registres et sous-registres sont accessibles
![image](https://user-images.githubusercontent.com/6093597/137694648-74007fa5-8fd2-48b3-8011-ba6724ccdceb.png)

**Depuis la valid** impossible d'accéder aux sous-registres
- INSPIRE enumeration register
- INSPIRE metadata code list register
- Registre de listes de codes
Message d'erreur 
![image](https://user-images.githubusercontent.com/6093597/137695162-f6bceef3-298f-4232-a0f7-19227002b758.png)

**Depuis la prod http** - tout est disponible

**Depuis la prod https** même situation que la valid : impossible d'accéder aux sous-registres
- INSPIRE enumeration register
- INSPIRE metadata code list register
- Registre de listes de codes
Message d'erreur 
![image](https://user-images.githubusercontent.com/6093597/137695626-bf16ce47-c26f-4a51-b922-f4bf513577e6.png)

**Comment by davinciagf** [comment]
Pour la test, pas de problème rencontré pour metadata code list register
![image](https://user-images.githubusercontent.com/576292/137870234-3ef94083-21fe-43dc-8924-c90bab8c0dc2.png)

Idem en prod via https:
![image](https://user-images.githubusercontent.com/576292/137870827-64bfc755-985f-4475-9ecd-8df980c0fa5e.png)


et pour enumration code list  ok aussi en https
![image](https://user-images.githubusercontent.com/576292/137871134-6519c5b8-f27c-4bc9-a2ff-3e393da85d74.png)

Indisponibilité temporaire du sous-registre ou autre (https pas net)? A vérifier

**Comment by vbombaerts** [comment]
Dispo hors intranet.
Pas dispo dans l'intranet.

Je viens de retester avec PC perso vs PC pro en VPN

**Comment by vbombaerts** [comment]
Retesté qques jours après et maintenant ça marche. Bizarre...
