### ISSUE TITLE
Déclencher une indexation de la fiche quand on change les droits

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#679]
**Is your feature request related to a problem? Please describe.**
Actuellement, un changement de droit (publication/dépublication dans un groupe spécifique) ne déclenche pas l'indexation de la fiche. Sans une indexation manuelle, elle apparait toujours avec ses anciens droits. Quand un sous-portail filtre les fiches sur base de la publication dans un groupe, les fiches n'apparaissent/ne disparaissent  pas instantanément du sous-portail.

**Describe the solution you'd like**
indexation automatique au changement de droits

**Comment by fxprunayre** [comment]
Hum testant sur test, si je publie une fiche privée, on est d'accord que dans une fenêtre anonyme, il y a une fiche en plus dans les résultats ? C'est quoi la manip ? Une fiche en particulier ?

**Comment by vbombaerts** [comment]
En prod.
Ajouter sur une fiche privée des droits dans le groupe Test-ODWB - http://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/69fbfdd4-0fd4-4e87-97d3-5662f397d9c0

Elle n'apparait pas dans le portail dédié.
http://metawal.wallonie.be/geonetwork/Test-ODWB/fre/catalog.search#/home

Après indexation elle devrait apparaitre.
Même manip possible en sens inverse (dépublication du groupe)

**Comment by fxprunayre** [comment]
En effet, le champ groupPublished dans l'index n'est pas mis à jour, par contre si on fait indexer, c'est bon. Doit y'avoir un pb dans la mise à jour des champs de l'index lorsqu'on ne fait qu'un changement de privilèges.

**Comment by fxprunayre** [comment]
Cf. https://github.com/titellus/core-geonetwork/pull/58

**Comment by fxprunayre** [comment]
Déployé. A tester.
