### ISSUE TITLE
Aperçus - Proposer qu'un seul thumbnail

### ISSUE THREAD

**Issue by geologiewallonie** [SPW-DIG/metawal-core-geonetwork#68]
Cela ne sert à rien d'afficher les deux versions des aperçus. Il faut proposer le plus petit et afficher le grand quand on clique sur le petit ;-).

**Comment by fxprunayre** [comment]
Potentiellement, il peut y avoir n thumbnails sans rapport les uns les autres (comme petit et grand).

A planifier, mise à jour en batch des fiches pour n'avoir plus qu'un aperçu ?

**Comment by vbombaerts** [comment]
Le "petit thumbnail" n'est plus à l'ordre du jour.
