### ISSUE TITLE
Ajout d'actions de gestion sur une fiche individuelle

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#680]
**Is your feature request related to a problem? Please describe.**
Ajouter la possibilité : 
- d'ajouter/supprimer de la sélection 
- d'indexer

Directement depuis la dropdown "gérer la fiche" de l'interface de consultation d'une fiche individuelle

La demande est directement liée à la possibilité d'indexer une ou plusieurs fiches après modification ou changement de droits mais, pour la sélection, peut trouver d'autres applications (marquer différentes fiches qui viennent d'être éditées, ajouter/supprimer de la sélection des fiches avec une certaine caractéristique vérifiée "à la main"...)

![image](https://user-images.githubusercontent.com/6093597/138721080-4d7c4db9-4d6c-4eb0-a813-df381d647293.png)

**Comment by davinciagf** [comment]
@vbombaerts, pour l'indexation tu souhaites une indexation de la fiche uniquement ou de la fiche et de la sélection (quid si la fiche est incluse dans la sélection versus fiche est hors sélection)?

**Comment by vbombaerts** [comment]
Indexation de la fiche uniquement. 
L'indexation de la sélection se fait via le mécanisme déjà opérationnel (via les actions sur la sélection des interfaces de recherche et de contribution)

**Comment by fxprunayre** [comment]
A déployer et tester.

**Comment by davinciagf** [comment]
Les deux actions sont dispo en test

**Comment by vbombaerts** [comment]
Traductions manquantes. Pour le reste OK.

![image](https://user-images.githubusercontent.com/6093597/155491977-5af90c0a-4fb0-46e0-9e05-e0dcc6b282df.png)

**Comment by davinciagf** [comment]
Traduction disponible:
<img width="482" alt="image" src="https://user-images.githubusercontent.com/576292/155523527-f65c6c2b-e417-40e0-8e75-7d38a440e069.png">
