### ISSUE TITLE
Tableau de bord INSPIRE

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#681]
**Is your feature request related to a problem? Please describe.**
Le monitoring INSPIRE ne renvoie pas des résultats consistants d'une fois à l'autre. 
Je souhaite disposer d'un tableau de monitoring propre à INSPIRE-Wallonie qui permet d'accéder à une version Metawal des résultats du monitoring (indicateurs) et des données utilisées pour calculer les indicateurs.

**Describe the solution you'd like**
Un tableau Kibana qui reprend les différents indicateurs et qui permet d'explorer les erreurs éventuelles.

**Ressources**
- Tableau de monitoring (validé pour 2020) https://inspire-geoportal.ec.europa.eu/mr2020_details.html?country=be#tab-INSPIRE-f5201eb0-2404-11e5-8130-52540004b857 + documentation en bas de la page: https://inspire-geoportal.ec.europa.eu/mr2020_details.html?country=be#tab-INSPIRE-f5201eb0-2404-11e5-8130-52540004b857

**Comment by fxprunayre** [comment]
Un début de tableau de bord

![image](https://user-images.githubusercontent.com/1701393/141939993-460258d5-ad37-443e-8d88-85abec7d87c0.png)

Ca conviendrait ?

Je suis preneur du doc sur les explications sur le calcul des indicateurs @vbombaerts ? Je n'arrive pas à passer ecas :/

**Comment by davinciagf** [comment]
Doc dispo sur teams (rubrique fichiers)

**Comment by vbombaerts** [comment]
> Ca conviendrait ?

Super ! Je propose d'ajouter un chiffre qui reprend dataset+series (même si c'est facile à calculer), puisque dans les indicateurs c'est ça qui est utilisé.

**Comment by fxprunayre** [comment]
Démo des dashboards dispo sur https://apps.titellus.net/geonetwork/ (login
admin/admin) - J'ai juste moissonné metawal prod en 19139
https://apps.titellus.net/geonetwork/dashboards/app/dashboards#/view/fb06c930-461b-11ec-a605-89e8b648d878

Remarques:
* J'ai pas fait tourné la validation donc 0 conformant.
* NSi2x - il n'y pas de logique d'analyse des liens services / datasets -
donc on a juste des requêtes du type resourceType: (dataset or series) and
linkProtocol : "OGC:WMS" qui ne sont pas équivalentes à ce que fait le
geoportal

Le reste devrait être ok mais on pourra regarder ça plus en détail demain
lors de la réunion.

**Comment by davinciagf** [comment]
# Importation vers la production

Le developpement du tableau de bord a été réalisé sur une version 7.15 de Kibana. La production est en version 7.7 en décembre 2021. 

Procédure pour eviter certaines erreurs d'importation :  
- Modification du numéro de version de kibana dans le fichier d'import.
- Suppression du dernier object ayant l'id fb06c930-461b-11ec-a605-89e8b648d878 (erreur : message: "Document \"fb06c930-461b-11ec-a605-89e8b648d878\" has property \"dashboard\" which belongs to a more recent version of Kibana (7.7.0).") qui correspond au dashboard.

Cette procédure permet d'inporter les visualisations mais pas le dashboard (fb06c930-461b-11ec-a605-89e8b648d878). Un message d'errreur liéé à l'utilisation de tag dans les version 7.12 et sup est également référencé lors de l'import.

Exemple des tags dans une version 7.12 
![image](https://user-images.githubusercontent.com/576292/145264584-45ac0977-b81d-424a-88df-de926d131b99.png)

Attention après import on constate différents problème:
- élément de regroupement non présent (solution: utiliser un élément identique à l'ensemble des fiches docType)
![image](https://user-images.githubusercontent.com/576292/145265424-17d01637-feba-4e97-b3c9-afe501846401.png)

- élément object au niveau des expressions (solution réécrire les expressions via la syntaxe LUCENE)
![Capture1](https://user-images.githubusercontent.com/576292/145264978-19b4c077-8fac-4bd6-b277-532861d50e83.JPG)

Les différentes visualisations ayant été retravaillées sont renommées *-versionK77
![image](https://user-images.githubusercontent.com/576292/145265519-9f88d0ea-9dbf-4208-b5b5-6c4290f61c81.png)

## Remarque
- Potentiel perte des scripted filed de l'index pattern ainsi que certains champs lors de l'import (à vérifier)
- Comment conserver les scripted field en cas de besoin de suppression/création de l'index pattern (via un fichier d'import de la visualisation - à ensuite pousser en https://github.com/SPW-DIG/metawal-core-geonetwork/tree/metawal-4.0.x/es/es-dashboards/data)?

**Comment by vbombaerts** [comment]
C'est bien, on a les éléments qui permettent de reconstruire le dashboard.
