### ISSUE TITLE
Kibana - erreur esaggs

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#686]
Dans Kibana, il m'arrive d'avoir l'erreur suivante :

![image](https://user-images.githubusercontent.com/6093597/142864842-c0969ec9-c614-4457-aa0f-814f836dd312.png)

Savez-vous quelle en est la cause (limite de Kibana, erreur dans ma requête...) et comment la corriger ?

**Comment by fxprunayre** [comment]
```
message: "[too_many_buckets_exception] 
Trying to create too many buckets. Must be less than or equal to: 
[10000] but was [10001]. 
This limit can be set by changing the [search.max_buckets] cluster level setting."

```

**Comment by vbombaerts** [comment]
Il y a 1 bucket par combinaison de valeurs des variables. Donc ce sont a priori les variables qui peuvent prendre bcp de valeurs qui posent problème.
