### ISSUE TITLE
Analyse des liens / Afficher la liste pour une sélection en cours 

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#688]
Dans la fenêtre de contrôle des liens morts, ce serait bien d'avoir la possibilité de filtrer les résultats sur base d'une sélection de fiches (sélection courante ou sélection utilisateurs).

![image](https://user-images.githubusercontent.com/6093597/145986385-b8621ca1-9bb4-47ee-a7c1-b7870d3de91e.png)

Pour le moment j'utilise un workaround :
1. publier la sélection dans un groupe factice
2. afficher les fiches sur base de la dropdown "-groupPublished"
![image](https://user-images.githubusercontent.com/6093597/145986598-cfb72179-6d9c-4d35-96b3-f544e14bc734.png)

**Comment by vbombaerts** [comment]
Autre point, ajout d'un macaron au niveau de la liste des données pour savoir si les liens sont tous OK ou si certains sont KO.
(similaire au résultat de validation et de validation INSPIRE)

A discuter, car il faut voir si ça ne surcharge pas trop l'interface.

**Comment by marceaulouis** [comment]
Est-ce que l'option d'afficher la liste pour une sélection est portée en test ? Je n'ai pas trouvé comment le mettre en pratique

**Comment by davinciagf** [comment]
Déployé. A tester

**Comment by marceaulouis** [comment]
Ce qui est déployé fonctionne : exclusion d'adresses + filtre sur la sélection

@vbombaerts est-ce que le filtre est dans l'esprit de la requête de base : 
- filtrer sur les résultats des tests de toutes fiches (déployé et opérationnel) ou 
- tester seulement sur une sélection de fiches

**Comment by vbombaerts** [comment]
![image](https://user-images.githubusercontent.com/6093597/174556508-c298b49f-72b2-4e1c-9300-975937d6762b.png)


La demande était de filtrer sur les résultats des tests, soit avec la sélection courante, soit avec une sélection utilisateur
![image](https://user-images.githubusercontent.com/6093597/174555847-dc48f731-5e77-4e5e-b2c2-a4b75177acab.png)

Si la sélection utilisateur n'est pas implémentée ce n'est pas grave. On peut contourner comme ceci : retourner dans la recherche, jouer la recherche utilisateur, sélectionner les fiches retournées. Puis vérifier les liens.

**Comment by marceaulouis** [comment]
Valid : impossible de sauvegarder l'URL à exclure du test 
![image](https://user-images.githubusercontent.com/99397823/176110635-be934a7a-32d4-4bfc-b0e9-50af9642a287.png)

Sélection OK

**Comment by marceaulouis** [comment]
Ok
