### ISSUE TITLE
Module de test des liens - faux positifs

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#689]
Dans les résultats du module de test des liens, on a de nombreux "faux positifs", pour plusieurs raisons :
- adresse http qui n'est pas résolvable (par ex. URI qui sert d'identifiant : `http://geodata.wallonie.be/id/bee148c9-f6f2-458e-8359-c33816927a8a`)
- liens vers site ftp - accessible (ex. `ftp://docum1.wallonie.be/donnees/amenagement/SCD`)
- redirections - accessibles (ex. `http://www.iweps.be/terrains-non-urbanises-en-zones-urbanisables` qui redirige vers https://www.iweps.be/indicateur-statistique/potentiel-foncier-zones-dhabitat-plan-de-secteur/)
- des trucs inclassables, comme `http://environnement.wallonie.be/cgi/dgrne/aerw/ied/ied_chx_tous.idc`

Et probablement d'autres encore.

Voici quelques suggestions d'amélioration :
- Ajout d'une "liste blanche" des adresses qui ne sont pas testées - par exe ce qui commence par `http://geodata.wallonie.be/id` - liste éditable dans l'interface de testing des liens 
- possibilité dans le filtre URL d'exclure des adresses sur base d'un texte

**Comment by marceaulouis** [comment]
Autres cas à filtrer :

- attachements des fiches non-publiées (imagettes, documents, etc.) ex: https://metawal.wallonie.be/geonetwork/srv/api/records/7cd2a5f3-1e1a-4bf3-bc37-bf901f128fc8/attachments/Image001_1435846214.png

- certains liens ne sont pas lus jusqu'au bout par le module de test ex: https://metawal.wallonie.be/geonetwork/srv/api/records/93e91c8f-d53d-4e36-a993-290070bf2c8c/attachments/Orthophotos_2019_Maillage_Tuilage_Rapport_conformit%C3%A9.pdf 

est coupé : https://metawal.wallonie.be/geonetwork/srv/api/records/93e91c8f-d53d-4e36-a993-290070bf2c8c/attachments/Orthophotos_2019_Maillage_Tuilage_Rapport_conformit

- intérêt de tester les fiches obsolètes ? --> filtrer les fiches à tester (https://github.com/SPW-DIG/metawal-core-geonetwork/issues/688)

- liens téléchargement

**Comment by fxprunayre** [comment]
> * redirections - accessibles (ex. `http://www.iweps.be/terrains-non-urbanises-en-zones-urbanisables` qui redirige vers https://www.iweps.be/indicateur-statistique/potentiel-foncier-zones-dhabitat-plan-de-secteur/)

http://www.iweps.be/terrains-non-urbanises-en-zones-urbanisable retourne un 404.

![image](https://user-images.githubusercontent.com/1701393/164198317-854152fa-a093-4987-a80b-88869a702305.png)
 
Il y a un redirect http > https mais qui termine sur "désolé" 
![image](https://user-images.githubusercontent.com/1701393/164198436-a3bd2181-bf53-4aef-9fff-47278f9be00c.png)

**Comment by fxprunayre** [comment]
> est coupé : https://metawal.wallonie.be/geonetwork/srv/api/records/93e91c8f-d53d-4e36-a993-290070bf2c8c/attachments/Orthophotos_2019_Maillage_Tuilage_Rapport_conformit

Les accents ne sont pas autorisés dans les URL, donc il faudrait corriger l'URL. 
eg. fr.wikipedia.org/wiki/éléphant va s'afficher avec des accents dans un navigateur mais si on fait un copier/coller de l'URL on obtient bien une URL valide ie. https://fr.wikipedia.org/wiki/%C3%89l%C3%A9phant - Donc j'aurai tendance à dire qu'il faut corriger l'URL dans ce cas.

**Comment by fxprunayre** [comment]
cf. https://github.com/geonetwork/core-geonetwork/pull/6255

**Comment by fxprunayre** [comment]
TODO: Filter par une liste d'UUID (venant d'une sélection) cf. https://github.com/SPW-DIG/metawal-core-geonetwork/issues/688

**Comment by marceaulouis** [comment]
done, voir #688
