### ISSUE TITLE
Doublons dans la réponse du CSW

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#690]
Il semble que lorsqu'on requête le catalogue en CSW par paquets de 20, comme le fait la Commission lors du monitoring, certaines fiches sont répondues 2 fois. Sur un moissonnage effectué par un outil de préparation monitoring utilisé par le comité de coordination INSPIRE, le service aurait renvoyé 32 fiches en double sur un total de 212 fiches.
Adresse de l'outil : https://www.dumortier.eu/CIRB/inspire/parsexmlinspire.php

**Comment by fxprunayre** [comment]
Est-ce qu'ils font un tri lors de la requête ?

**Comment by vbombaerts** [comment]
> Est-ce qu'ils font un tri lors de la requête ?

Non. 
Je leur ai dit de trier sur l'identifiant.

C'est lié au fait que je faisais des mises à jour sur les fiches quand ils ont moissonné ?

**Comment by fxprunayre** [comment]
> Je leur ai dit de trier sur l'identifiant.

+1


> C'est lié au fait que je faisais des mises à jour sur les fiches quand ils ont moissonné ?

Oui, voire même s'ils font un GetRecordById, la popularité augmente, fiche réindexée ...
https://github.com/titellus/core-geonetwork/pull/14

**Comment by vbombaerts** [comment]
> Oui, voire même s'ils font un GetRecordById, la popularité augmente, fiche réindexée ...

Ca aide si je décoche la case ?

![image](https://user-images.githubusercontent.com/6093597/146157479-9d4217c3-1712-487f-ae78-d7a3d9a8af32.png)

**Comment by vbombaerts** [comment]
> Oui, voire même s'ils font un GetRecordById, la popularité augmente, fiche réindexée ...

Ca aide si je décoche la case ?

![image](https://user-images.githubusercontent.com/6093597/146157479-9d4217c3-1712-487f-ae78-d7a3d9a8af32.png)

**Comment by fxprunayre** [comment]
> Ca aide si je décoche la case ?

Non. Ca risque de créer d'autres problèmes car le CSW ne sera pas disponible le temps de l'indexation.
