### ISSUE TITLE
Mise à jour ES vers 2.16

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#692]
La migration vers ES et  Kibana 2.16 en valid ne passe pas. Metawal ne trouve pas l'interface ES/Kibana.

![image](https://user-images.githubusercontent.com/6093597/149287404-63170460-3f8d-411f-a334-4c8d7f87f3c7.png)

**Comment by davinciagf** [comment]
A mon avis, les fichiers de config d'EK ont été écrasés par l'update. Je retransmets les fichiers de conf à Didier.

**Comment by davinciagf** [comment]
C'est à nouveau opérationnel sur la valid pour l'accès à Kibana.

**Comment by vbombaerts** [comment]
J'ai ce warning à présent 
![image](https://user-images.githubusercontent.com/6093597/149301944-1f04d5d1-21b5-4b85-8b89-4b89e3c24a86.png)

**Comment by davinciagf** [comment]
Message présent sur les trois env. 
Ajouter le paramètre server.publicBaseUrl dans la config de kibana

**Comment by davinciagf** [comment]
Réalisé en test et plus de message de "configuration missing".

**Comment by vbombaerts** [comment]
@davinciagf tjrs pas fait en prod

**Comment by vbombaerts** [comment]
Reporté sur la 4.2.0
