### ISSUE TITLE
Problème au changement de mot de passe pour un utilisateur non LDAP

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#701]
![image](https://user-images.githubusercontent.com/6093597/150320521-a26e016f-3bd8-4e43-b57d-09e0b9a9879e.png)

**Comment by davinciagf** [comment]
Corrigé et testé avec succès.

**Comment by vbombaerts** [comment]
@marceaulouis tu peux essayer de changer ton mot de passe (en test) ?

**Comment by marceaulouis** [comment]
Ca ne fonctionne pas

En respectant les règles j'ai ce message
![image](https://user-images.githubusercontent.com/99397823/155532412-88a4216d-977c-4035-bbc1-7352d68e5d49.png)


Si j'enlève le caractère spécial j'ai un autre message
![image](https://user-images.githubusercontent.com/99397823/155532383-14cfc361-fa01-4e47-be37-ea1a0534038a.png)

J'ai essayé différents caractères de la liste

**Comment by vbombaerts** [comment]
J'ai créé un utilisateur non-LDAP et changé son mdp sans problème. Pour moi c'est OK.

**Comment by vbombaerts** [comment]
@marceaulouis ce n'est pas un problème de configuration du clavier/de la langue ?

**Comment by marceaulouis** [comment]
@vbombaerts Mon utilisateur de base était LDAP, on a regardé avec @davinciagf . 
J'ai créé un nouvel utilisateur et ça fonctionne. Arnaud va supprimer l'option de reset du mdp pour les utilisateurs LDAP (et créer un ticket si ce n'est déjà fait)

**Comment by davinciagf** [comment]
PR GN  https://github.com/geonetwork/core-geonetwork/pull/6180
