### ISSUE TITLE
Géoportail - Tableau des services

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#702]
Les informations contenues dans les fiches de services ne sont pas très nombreuses. Les plus importantes sont :
- [x] le nom du service - `resourceTitleObject`
- [x] le type de service (view, download, process...) - `serviceType`
- [x] le protocole du service (REST, WMS, etc) - `linkProtocol`
- [x] le point d'accès du service - `linkUrl`
- [x] les données servies - `related.datasets[origin=portal].title.fre`
- [x] la qualité du service - `related.onlines.item[function="dataQualityReport"]`
- [x] le gestionnaire du service - `custodianOrgForResource`

L'objectif est de créer un tableau dynamique des webservices qui reprend ces informations en une liste synthétique, avec
- [x] Toggle button sur le type de service
- [x] Possibilité de filtre sur le protocole
- [ ] Possibilité de recherche sur une chaine de caractère (nom du service, données servies, ...). 

Le tableau est à destination des utilisateurs qui souhaitent intégrer un service dans leur application.

Une info intéressante qui pourrait prendre place dans le tableau est un résultat de monitoring de l'état du service (disponibilité globale et disponibilité instantanée).

### Démonstrateur
[https://geoportail.test.wallonie.be/home/produire-et-publier/mw---test-agf-web-component/test-webcomponents-vincent-1.html](https://geoportail.test.wallonie.be/home/produire-et-publier/mw---test-agf-web-component/test-webcomponents-vincent-1.html)

### Code
```
<link href="https://metawal4.valid.wallonie.be/geonetwork/catalog/lib/icho/styles.css" rel="stylesheet" />
<link href="https://metawal4.valid.wallonie.be/geonetwork/catalog/lib/icho/main.css" rel="stylesheet" />
<div style="margin: 2.5em">
<h1>Liste des services web</h1>
    <catalogue-results-table
      fields='{"columnName":"Nom du service","columnIndex":"resourceTitleObject","columnJsonPath":"$.default"} |
      {"columnName":"Type de service","columnIndex":"serviceType","columnJsonPath":""} |
      {"columnName":"Protocole","columnIndex":"linkProtocol","columnJsonPath":""} |
      {"columnName":"Point d accès","columnIndex":"linkUrl","columnJsonPath":""} |
      {"columnName":"Gestionnaire","columnIndex":"custodianOrgForResource","columnJsonPath":""} |
	  {"columnName":"Données servies","columnIndex":"related","columnJsonPath":"$.datasets[?(@.origin==\"portal\")].title.fre"} |
	  {"columnName":"Qualité du service","columnIndex":"related","columnJsonPath":"$.onlines[?(@.function==\"dataQualityReport\")].url.fre"}'
      filterfield="linkProtocol"
      togglefilterfield="serviceType"
      toggleismultiselect="true"
      togglelabel='{"label": "Consultation", "value": "view"} | {"label": "Download", "value": "download"}'
      filter="+(resourceType:service) -(cl_status.key:obsolete)"
      size="10"
      catalogueurl="https://metawal4.test.wallonie.be/geonetwork/srv"
    ></catalogue-results-table></div>
<script src="https://metawal4.valid.wallonie.be/geonetwork/catalog/lib/icho/runtime.esm.js"  type="module"></script><script src="https://metawal4.valid.wallonie.be/geonetwork/catalog/lib/icho/polyfills.esm.js" type="module"></script><script src="https://metawal4.valid.wallonie.be/geonetwork/catalog/lib/icho/main.esm.js" type="module"></script>
```

**Comment by fxprunayre** [comment]
Exemple https://apps.titellus.net/hub/catalogue-table/ cf. onglet service

A améliorer:
* Faudrait reprendre un peu l'affichage des différents types de champs (array/array of objects/objects) - parfois on a des cases vides
* Données servies, ce n'est pas très simple, et résultat de monitoring c'est encore autre chose :)

**Comment by vbombaerts** [comment]
Au niveau de la fonction toggle, ce serait bien d'avoir des possibilités plus étendues pour définir les différentes valeurs. 
Pour le moment on a juste la possibilité de déclarer 1 label = 1 valeur.

Dans certains cas, on pourrait avoir besoin de 
- 1 label = plusieurs valeurs (ex : label = view service et valeurs = view, OGC:WMS, OGC:WMTS)
- 1 label = tout sauf la valeur X / les valeurs X et Y (ex : view service vs download service vs autres types de service)
- 1 label = la valeur void/pas de valeur, par exemple quand on définit le toggle sur un champ qui n'est pas systématiquement rempli

**Comment by vbombaerts** [comment]
@vbombaerts Au niveau du contenu pour les fiches de service : 
- 1 fiche par protocole
- 1 seule adresse dans la section distribution : l'adresse de connexion au service
- le lien spatineo dans la section qualité
- ajouter le type de service dans la section identification : view, download, discovery...

**Comment by fxprunayre** [comment]
- [x]  Tester la possibilité de configurer les colonnes par JSONPath https://github.com/dchester/jsonpath#jsonpath-syntax ?

Testé en local sur le webcomponent mapstore. Example de config :

```
<catalogue-results-card
  filter=""
  size="25"
  fields='{"image": "overview", "imageJsonPath":"$[0].url", "title": "resourceTitleObject", "titleJsonPath":"$.default", "subTitle": "custodianOrgForResource", "subTitleJsonPath":"", "text": "resourceHookAbstractObject", "textJsonPath":"$.default","link": "mw-gp-thematicMap", "linkJsonPath":"$[0].url","info": "revisionDateForResource","infoJsonPath":"$[0]"}'
  catalogueurl="https://metawal4.test.wallonie.be/geonetwork/srv"
  sorttype="asc"
  sortby="custodianOrgForResource"
></catalogue-results-card>

```  

- [x]  Voir pour avoir des filtres dans le toggleFilter eg. "view OR OGC:WMS OR ESRI:REST"

Il est possible d'utiliser une customQuery afin de regrouper certains éléments via la fonctionnalité du toggle button. Il suffit de mettre les éléments via une syntaxe lucene:

`      togglelabel='{"label": "Air", "value": "Air AND Eau"} | {"label": "Eau", "value": "Eau"} | {"label": "Agriculture", "value": "Agriculture"}'
`

Attention, ce dévelopment n'est pas encore dispo car il y a un bug au niveau de reactiveSearch qui empêche d'utiliser la customQuery dans l'outil ToggleButton. Une solution a été soumise pour correction : https://github.com/appbaseio/reactivesearch/issues/1888 

Ce point n'est donc pas encore dispo.

- [x]  WebComponent / Add support for portal
- [x]  WebComponent / Add sortBy option

**Comment by davinciagf** [comment]
@vbombaerts - Nouvelle config pour ce tableau:
```
    <catalogue-results-table
      fields='{"columnName":"Nom du service","columnIndex":"resourceTitleObject","columnJsonPath":"$.default"} |
      {"columnName":"Type de service","columnIndex":"serviceType","columnJsonPath":""} |
      {"columnName":"Protocole","columnIndex":"linkProtocol","columnJsonPath":""} |
      {"columnName":"Point d accès","columnIndex":"linkUrl","columnJsonPath":""} |
      {"columnName":"Gestionnaire","columnIndex":"custodianOrgForResource","columnJsonPath":""}'
      filterfield="linkProtocol"
      togglefilterfield="serviceType"
      toggleismultiselect="true"
      togglelabel='{"label": "Consultation", "value": "view"} | {"label": "Download", "value": "download"}'
      filter="+(resourceType:service) -(cl_status.key:obsolete)"
      size="4"
      catalogueurl="https://metawal4.test.wallonie.be/geonetwork/srv"
    ></catalogue-results-table>
```

**Comment by vbombaerts** [comment]
Pour tester les JSONPath 

### Evaluateur de JSONpath 
https://jsonpath.com/

### Requête API Metawal msearch
```
{"preference":"tableOfRecord"}
{"query":{"bool":{"must":[{"bool":{"must":[{"bool":{"boost":1,"minimum_should_match":1,"should":[{"term":{"serviceType":"view"}}]}},{"query_string":{"query":"+(resourceType:service) -(cl_status.key:obsolete)"}}]}}]}},"size":4,"_source":{"includes":["resourceTitleObject","serviceType","linkProtocol","linkUrl","custodianOrgForResource"],"excludes":[]},"from":0,"sort":[{"_score":{"order":"asc"}}]}
```

### JSONpath de base jusqu'aux éléments de l'index
`responses..`

**Comment by vbombaerts** [comment]
> @vbombaerts - Nouvelle config pour ce tableau:
> 
> ```
>     <catalogue-results-table
>       fields='{"columnName":"Nom du service","columnIndex":"resourceTitleObject","columnJsonPath":"$.default"} |
>       {"columnName":"Type de service","columnIndex":"serviceType","columnJsonPath":""} |
>       {"columnName":"Protocole","columnIndex":"linkProtocol","columnJsonPath":""} |
>       {"columnName":"Point d accès","columnIndex":"linkUrl","columnJsonPath":""} |
>       {"columnName":"Gestionnaire","columnIndex":"custodianOrgForResource","columnJsonPath":""}'
>       filterfield="linkProtocol"
>       togglefilterfield="serviceType"
>       toggleismultiselect="true"
>       togglelabel='{"label": "Consultation", "value": "view"} | {"label": "Download", "value": "download"}'
>       filter="+(resourceType:service) -(cl_status.key:obsolete)"
>       size="4"
>       catalogueurl="https://metawal4.test.wallonie.be/geonetwork/srv"
>     ></catalogue-results-table>
> ```

Pas réussi à avoir un tableau complet. Un problème dans la gestion des arrays ?
Par ailleurs la config proposée n'inclut pas les deux champs suivants : 
-  les données servies - related.datasets[origin=portal].title.fre
-  la qualité du service - related.onlines.item[function="dataQualityReport"]

**Comment by davinciagf** [comment]
Tableau dispo à https://apps.titellus.net/hub/webcomponents/ (mais sans les données servies et la qualité du service)
<img width="947" alt="image" src="https://user-images.githubusercontent.com/576292/157724203-c59e8a16-4095-4643-b7d3-ddadbd08b925.png">
Je regarde pour le mettre à jour avec  les données servies et la qualité du service

**Comment by vbombaerts** [comment]
> Pas réussi à avoir un tableau complet. Un problème dans la gestion des arrays ?

Erreur de css. Mis à jour.

**Comment by davinciagf** [comment]
Pour les points suivants:
- les données servies - related.datasets[origin=portal].title.fre
- la qualité du service - related.onlines.item[function="dataQualityReport"]


 Exemple : 
```
{"columnName":"related","columnIndex":"related","columnJsonPath":"$.datasets[?(@.origin==\"portal\")].title.eng"}
```

**Comment by vbombaerts** [comment]
Super !
Au niveau des listes à plusieurs entrées, est-il possible de séparer un peu plus les entrées? Par exemple la liste des données servies. Pour le moment c'est un peu confus.
Est-il possible d'avoir des largeurs de colonnes mieux proportionnées par rapport à leur contenu ?

![image](https://user-images.githubusercontent.com/6093597/159916914-0971bf26-8d97-4623-a01b-e77b2f7a48ae.png)

**Comment by davinciagf** [comment]
Correction des entrées de certains input avec séparation + largeur de colonne fixe 
<img width="935" alt="image" src="https://user-images.githubusercontent.com/576292/160195518-3584e4c3-ccaf-4b3e-8806-775fd1352dda.png">

**Comment by vbombaerts** [comment]
Icones non disponibles

![image](https://user-images.githubusercontent.com/6093597/161784576-dce05f35-ae79-456d-b76d-36a816768227.png)

**Comment by davinciagf** [comment]
Corrigé pour les appels vers les js et css de l'env de test.
