### ISSUE TITLE
Environnement de test indisponible

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#703]
Récap des erreurs d'indisponibilité de Metawal en test

Date | Heure | Erreur | Explication/Remarque
-- | -- | -- | --
24/01 | 09:30 | Down
24/01 | 14:00 | Time out
24/01  |  14:27 |  503
25/01  | 8:22  |  Elastic did not load properly. Check the server output for more information.
25/01 | 8:24  |  (a échoué)net::ERR_TIMED_OUT | Répond à 8:27
25/01  | 11:23  | (a échoué)net::ERR_TIMED_OUT | 11:28 je me déconnecte du VPN et ça répond.
31/01  | 14:21 | Lenteur de l'application, puis plus de réponse + aucune fiche ne s'affiche "La fiche avec l'identifiant n'a pas été trouvée ou n'est pas partagée avec vous. Essayer de vous connecter si vous avec un compte." 
31/01  | 18:26 | Aucune réponse, même pas un message d'erreur  
01/02  |  8:56 | OK 
02/02  |  17:45 | Tourne dans le vide | Dès la déconnexion du VPN, ça remarche 
02/02  | 17:50 | Malgré la déconnexion du VPN, pas de réponse. Par contre, Kibana a l'air de répondre
03/02  |  10:51 |  503 | 10:55 refonctionne
16/02 | 14:53 | 404 |  Revenu à 15:48 - Indisponibilité suite à déploiement
17/02  | 11:22 |  Pas de réponse | Attendu 5 minutes. Déconnecté du VPN et ça remarche.
21/02  | 10:24 | 503 | 
21/02  | 14:28 | Pas de réponse | Avec ou sans VPN, ne répond pas. 14:38 OK avec VPN
25/02 | 17:28 | Pas de réponse (Time out) | 
28/02  |  8:00 |  
28/02  | 11:55 |  Pas de réponse
02/03  | 22:40 | 503 
03/03 | 11:45 | 503 | 11:54 OK
03/03 | 13:40  |  Pas de réponse | 13h46 revenu
07/03 | 9:55  | 503  
11/03 | 8:10 | Index indisponible - Erreur : Unable to revive connection to http://localhost:9200. Error is Connection refused
  |   |  
  |   |

**Comment by davinciagf** [comment]
Pour les erreurs de type "pas de réponse"; il semble y avoir des problème avec le proxy ajp.

21/02
[Mon Feb 21 14:24:51.599254 2022] [proxy_ajp:error] [pid 49366] (70007)The timeout specified has expired: AH01030: ajp_ilink_receive() can't receive header
[Mon Feb 21 14:24:53.858415 2022] [proxy_ajp:error] [pid 58035] (70007)The timeout specified has expired: AH01030: ajp_ilink_receive() can't receive header
[Mon Feb 21 14:27:32.052094 2022] [proxy_ajp:error] [pid 54208] (70007)The timeout specified has expired: AH01030: ajp_ilink_receive() can't receive header
[Mon Feb 21 14:32:24.331417 2022] [proxy_ajp:error] [pid 50334] (70007)The timeout specified has expired: AH01030: ajp_ilink_receive() can't receive header
[Mon Feb 21 14:36:20.749262 2022] [proxy_ajp:error] [pid 60787] (70007)The timeout specified has expired: AH01030: 
...

25/02
...
[Fri Feb 25 17:23:18.096201 2022] [proxy_ajp:error] [pid 54208] (70007)The timeout specified has expired: AH01030: ajp_ilink_receive() can't receive header
[Fri Feb 25 17:25:52.808285 2022] [proxy_ajp:error] [pid 57848] (70007)The timeout specified has expired: AH01030: ajp_ilink_receive() can't receive header
[Fri Feb 25 17:32:57.956669 2022] [proxy_ajp:error] [pid 60787] (70007)The timeout specified has expired: AH01030: ajp_ilink_receive() can't receive header
...

**Comment by davinciagf** [comment]
Courant avril 2022, de nombreux coupures - elles seraient liés à logstash qui consomme trop de RAM pour la machine

**Comment by vbombaerts** [comment]
On a la procédure de relance de l'environnement de test. Je ferme.

**Comment by davinciagf** [comment]
A priori ce serait l'apache qui plante:
Cas : metawal4.test est dans les choux mais il est possible d'interagir avec le catalogue via un accès en local au tomcat; si l'on stop et relance l'apache, metawal4.test est à nouveau actif.
