### ISSUE TITLE
Indexation et contacts en multilingue

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#704]
(Testé sur des fiches en 19139 moissonnées de l'IGN - env. de test)
Dans Metawal : https://metawal4.test.wallonie.be/geonetwork/iweps/fre/catalog.search#/metadata/2366286e-fe92-11eb-980c-7478273ff935
XML : https://metawal4.test.wallonie.be/geonetwork/iweps/api/records/2366286e-fe92-11eb-980c-7478273ff935/formatters/xml?approved=true

Les contacts ne sont pas indexés en multilingue. Je comprends la logique mais peut-être qu'on peut indexer en multilingue juste le nom de l'institution ?

![image](https://user-images.githubusercontent.com/6093597/151790744-0a127cf2-6c73-48f2-bffe-0471cf39affa.png)
![image](https://user-images.githubusercontent.com/6093597/151790861-2be798f0-6341-41b8-8fcc-b04ec8029941.png)
![image](https://user-images.githubusercontent.com/6093597/151791205-79ac171a-2b76-4010-80aa-3c6b7b69f2bd.png)

**Comment by vbombaerts** [comment]
En cours côté geocat.ch

**Comment by fxprunayre** [comment]
Cf. https://github.com/geonetwork/core-geonetwork/pull/6588

**Comment by fxprunayre** [comment]
A déployer

http://localhost:9200/gn-records/_doc/2366286e-fe92-11eb-980c-7478273ff935

* Les noms d'organisation sont multilingues
![image](https://user-images.githubusercontent.com/1701393/195590785-7a67d034-6a1c-414e-969d-6a14c2df4469.png)

* Les liens et leurs noms/description également
![image](https://user-images.githubusercontent.com/1701393/195590935-fa99e088-b58f-472e-9f86-5d55de422995.png)



Vérifier les configs de facette si on utilise ces champs eg.

```
OrgForResource: {
  terms: {
    field: "OrgForResourceObject.${aggLang}",
    // field: "OrgForResourceObject.default",
    // field: "OrgForResourceObject.langfre",
```
