### ISSUE TITLE
Edition multilingue - l'ordre des langues pour certains éléments est différent

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#706]
Contact

![image](https://user-images.githubusercontent.com/6093597/151871581-a7414fc9-1cd1-42c1-8768-4375f42301e1.png)

Mots-clés

![image](https://user-images.githubusercontent.com/6093597/151872552-31831589-820e-49f8-8177-41f0eef1da16.png)

Normalement on a

![image](https://user-images.githubusercontent.com/6093597/151872633-0c38d77d-a65e-4a57-ae5d-c28e4dd55641.png)

**Comment by vbombaerts** [comment]
Généalogie

![image](https://user-images.githubusercontent.com/6093597/151935195-fdf04645-4943-4530-a118-2eccc8403996.png)

**Comment by fxprunayre** [comment]
L'ordre est définit de la manière suivante:
* A la sauvegarde, les traductions sont stockées dans l'ordre des langues définit dans l'onglet métadonnée ie. on change l'ordre des langues, on change l'ordre des traductions
* A la création du formulaire, les champs pour lesquels il y a des valeurs (dans l'ordre des langues définies) sont ajoutés, les vides ou manquants ensuite ie. 
  * si tout est rempli, dans l'ordre des langues - Résumé ci-dessous
  * si non, les traductions saisies (dans l'ordre des langues d'abord), ensuite le reste à faire - But ci-dessous
* Le sélecteur de langue est en bleu quand il y a des valeurs, gris sinon - Reconnaisance est traduit en italien ci-dessous

![image](https://user-images.githubusercontent.com/1701393/151934687-8218389d-de77-4a4b-b3bc-e3203f224c61.png)

Ces règles ont été définies par geocat.ch à la base et affinées en 2020 par les Canadiens.

A voir si c'est nécessaire de changer ce fonctionnement?

**Comment by vbombaerts** [comment]
OK. Je pensais que c'était lié à à #707 
Pas de problème pour l'ordre en édition tant que toutes les langues apparaissent.
