### ISSUE TITLE
Fiche multilingue - certains éléments ne sont pas traduits

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#707]
Ils sont encodés en multilingue, mais quand on change la langue, seule la valeur de la langue par défaut est affichée.

Mots-clés

![image](https://user-images.githubusercontent.com/6093597/151874763-309b442f-eaa7-429c-b2c7-17c8d60c82a3.png)

Contacts
![image](https://user-images.githubusercontent.com/6093597/151874870-2cfe6d55-ebf2-4c26-99e8-c0b46d8bf98f.png)

**Comment by vbombaerts** [comment]
Ce sont les mêmes que dans #706

**Comment by fxprunayre** [comment]
Quel est l'UUID de la fiche (pour tester)?
Pour les mots clés https://github.com/titellus/core-geonetwork/pull/116
Pour les contacts, c'est plus compliqué - faut modifier l'index.

**Comment by vbombaerts** [comment]
Par exemple : https://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/08a8145e-318a-49d8-8e96-94882a236794 mais je suis en train de travailler dessus.

**Comment by fxprunayre** [comment]
A tester, ca doit être ok. Pour les contacts ce sera fait dans https://github.com/SPW-DIG/metawal-core-geonetwork/issues/704

**Comment by davinciagf** [comment]
Semble ok en test

**Comment by vbombaerts** [comment]
Indexé mais mais n'apparait pas dans la fiche.
Une typo ? langeng**e**
```
"default": "habitant",
 "langfre": "habitant",
 "langenge": "inhabitant",
```

**Comment by vbombaerts** [comment]
erreur d'encodage de la langue dans la fiche https://metawal4.test.wallonie.be/geonetwork/srv/api/records/22a00250-ee14-40a9-b323-8df615d7ab2a/formatters/xml?approved=true

**Comment by vbombaerts** [comment]
Pas d'erreur dans la fiche originale - https://www.geo.be/metadataServices/rest/catalogs/1/resources/4dabc05e-1fa1-11ec-84b5-7478273ff935/xml

Erreur dans le module de conversion 139-->115-3 avec suppression des langues ?

**Comment by fxprunayre** [comment]
![image](https://user-images.githubusercontent.com/1701393/172872897-c8511c27-a080-435b-9650-a26e3129edbf.png)

C'est dans la config du moissonneur le pb

**Comment by vbombaerts** [comment]
OK.
