### ISSUE TITLE
Emprise géographique en Lambert 72 et 2008

### ISSUE THREAD

**Issue by geologiewallonie** [SPW-DIG/metawal-core-geonetwork#71]
Il serait bon de proposer les projections Lambert utilisées en Belgique plutôt que celles de France.

![2](https://f.cloud.github.com/assets/6093460/1662908/14569660-5c08-11e3-9593-f3ced1a89e71.JPG)

**Comment by davinciagf** [comment]
Configuration overrides - serveur démo ok

**Comment by vbombaerts** [comment]
Erreur dans le conversion en Lambert 2008.
![image 664](https://f.cloud.github.com/assets/6093597/1887098/bedc8026-79f5-11e3-9efe-ebc7707c1d13.png)

**Comment by fxprunayre** [comment]
Ajouter la référence ici https://github.com/spacebelGIS/metawal-core-geonetwork/blob/metawal-develop/web-client/src/main/resources/apps/metawal/js/map/Settings.js#L29 sans doute ?

**Comment by davinciagf** [comment]
Attention vérifier la concordance avec la déclaration du Lambert belge 2008 dans le fichier de configuration des overrides de metawal
