### ISSUE TITLE
Maintenance contenu fiches de service

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#712]
@vbombaerts Au niveau du contenu pour les fiches de service : 
- 1 fiche par protocole
- 1 seule adresse dans la section distribution : l'adresse de connexion au service
- le lien spatineo dans la section qualité
- ajouter le type de service dans la section identification : view, download, discovery...

_Originally posted by @vbombaerts in https://github.com/SPW-DIG/metawal-core-geonetwork/issues/702#issuecomment-1041589949_

**Comment by fxprunayre** [comment]
Est-ce que vous ne devriez pas essayer de ne plus avoir à gérer les fiches de services ? J'imagine que les fiches sont toujours très proches ? et donc on pourrait imaginer moissonner les GetCapabilities (ou autres documents produits par le service) pour créer les fiches ? C'est juste une suggestion ...

**Comment by vbombaerts** [comment]
@vbombaerts doit voir avec Stéphane

**Comment by vbombaerts** [comment]
Pour le moment on va adapter les fiches manuellement. J'ai créé un autre ticket pour le moissonnage des service view et download.

**Comment by vbombaerts** [comment]
Encore 2 ou 3 corrections[Fiches avec plus qu'un protocole](https://metawal.wallonie.be/geonetwork/dashboards/goto/ec46f9d0-c094-11ec-9c43-0f70b8f525db) :

- [x] Services déclassés - Fiches à supprimer - Si donnée liée, vérifier que le lien du service déclassé n'est plus dans la fiche de la donnée
- https://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/ad826c7c-02ad-4566-b21d-904e764bd4e5
- https://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/fb702984-b9a3-4d97-8637-070672498ae5
- https://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/55495cea-ad66-421d-bd48-7d4470caf366

- [x] Services indiqués comme obsolètes mais qui tournent toujours - A vérifier avec SPA
- https://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/ca65d95e-c5de-4529-a1b5-6493e8a6b13c

- [ ] Fiches brouillon - A dédoubler lors de la publication
- https://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/c299573c-2523-412f-a904-bfc5f3af35e1
- https://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/5fecb7b2-8a59-40ee-9909-ee76c13f5d2e
- https://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/44bc5a8f-b068-492f-98ff-653daf81b579
- https://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/b801b3fc-8830-4c94-a8a6-3bd8de500bb3
- https://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/06c64ec3-293f-4dae-9961-7fa427543f53

**Comment by vbombaerts** [comment]
Tout est sous contrôle ;-)
