### ISSUE TITLE
Création d'un MapStore

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#715]
L'idée est de présenter le catalogue des applications sous forme de "MapStore".

Les applications sont présentées sous forme de cartes avec :
- Titre - `resourceTitleObject`
- Visuel - `overview`
- Accroche - `resourceHookAbstractObject`
- Propriétaire (ou gestionnaire ?) - `ownerOrgForResource`
- Icône qui indique si l'application est sécurisée ou d'accès libre `cl_accessConstraints.key = restricted`
- 2 boutons :
  - "Plus d'infos" : pour le moment, descriptif complet en fenêtre modale. A terme, éventuellement un lien vers la fiche géoportail "complète"
  - Consulter : lien vers l'application - `mw-gp-thematicMap.url`
 
Derrière le visuel, on a aussi le lien vers l'application.

Fonctionnalités :
- Filtre thématique
- Filtre full text

Dans un deuxième temps, on intègre les avis et évaluations (notation sur la carte et avis dans fiche complète)

## Démonstrateur
https://geoportail.test.wallonie.be/home/produire-et-publier/mw---test-agf-web-component/test-webcomponents-vincent-Mapstore.html

## Code 
```
<p>&nbsp;</p>
<link rel="stylesheet" href="https://metawal4.test.wallonie.be/geonetwork/catalog/lib/icho/styles.css"> 
<link rel="stylesheet" href="https://metawal4.test.wallonie.be/geonetwork/catalog/lib/icho/main.css"> 
<div style="margin: 2.5em">
<catalogue-results-card 
catalogueurl="https://metawal4.test.wallonie.be/geonetwork/srv" 
fields='{
"imageIndex": "overview", "imageJsonPath":"$[0].url", 
"titleIndex": "resourceTitleObject", "titleJsonPath":"$.default", "titleSize":"h4", 
"subTitleIndex": "ownerOrgForResource", "subTitleJsonPath":"", 
"textIndex": "resourceHookAbstractObject", "textJsonPath":"$.default",
"linkIndex": "mw-gp-thematicMap", "linkJsonPath":"$[0].url", "linkIcon":"map", "linkButtonColor":"#0676C5", "linkHook":"Découvrir",
"additionalInfoIndex":"cl_accessConstraints", "additionalInfoJsonPath":"$[0].key"
}' 
filter="+(resourceType:application) -(th_infraSIG.default:Reporting_INSPIRE) -(cl_status.key:obsolete)" 
fulltextfilter="resourceTitleObject.default,` resourceHookAbstractObject.default"
search_placeholder="Recherche libre"
filterfield_2="th_Themes_geoportail_wallon_hierarchy.default"
filterfield_2_placeholder="Thème"
filterfield="ownerOrgForResource"
filterfield_placeholder="Propriétaire" 
linkmdt="false"
imageheight="220" 
itemsperrow="4" size="12" marginx="2" margintoolsbottom="1" marginbottom="2" 
sorttype="asc" sortby="resourceTitleObject.default.keyword"
sortbylist='{"sortIndexRef":"resourceTitleObject.default.keyword", "sortName":"Titre"} | {"sortIndexRef":"popularity", "sortName":"Popularité"}'
> </catalogue-results-card></div>
<script src="https://metawal4.test.wallonie.be/geonetwork/catalog/lib/icho/runtime.esm.js"  type="module"></script><script src="https://metawal4.test.wallonie.be/geonetwork/catalog/lib/icho/polyfills.esm.js" type="module"></script><script src="https://metawal4.test.wallonie.be/geonetwork/catalog/lib/icho/main.esm.js" type="module"></script>
```

**Comment by fxprunayre** [comment]
Exemple avec un GN standard https://www.aquacoope.org/cat_eecca/

**Comment by vbombaerts** [comment]
Oups, détail important : en intégration sur une page du géoportail.

**Comment by davinciagf** [comment]
Voici un example de web component déjà existant; (base similaire au tableau) à adapter suite aux requirements et au look & feel a adopter:

![image](https://user-images.githubusercontent.com/576292/155489008-fbf21c0a-61ab-4f44-8963-d9d583affe9d.png)

```     
 <catalogue-results-card
      filter=""
      size="5"
      fields='resourceTitleObject,overview,custodianOrgForResource, resourceHookAbstractObject, revisionDateForResource, link'
      catalogueurl="https://metawal4.test.wallonie.be/geonetwork/srv">
</catalogue-results-card>
``` 

A discuter...

**Comment by vbombaerts** [comment]
Pour le moment ne fonctionne pas

**Comment by davinciagf** [comment]
Ne build n'était pas passé : https://apps.titellus.net/hub/webcomponents/

**Comment by davinciagf** [comment]
@vbombaerts , attention ne pas oublier de référencer le portal dans le champs catalogueurl (@davinciagf à compléter dans la doc) - il est sans doute nécessaire de mettre à jour les différentes config des tests pour ce paramètre
<img width="818" alt="image" src="https://user-images.githubusercontent.com/576292/155705788-4fd059c1-371a-4317-8b0a-9b02640772c8.png">

**Comment by vbombaerts** [comment]
J'ai indiqué le portal mais ça ne change rien.

**Comment by davinciagf** [comment]
Vide la cache

```
	<catalogue-results-card 
	catalogueurl="https://metawal4.test.wallonie.be/geonetwork/srv"
	fields="resourceTitleObject,overview,resourceHookAbstractObject,link" 
	filter="+(resourceType:application) -(th_infraSIG.default:Reporting_INSPIRE) -(cl_status.key:obsolete) +(custodianOrgForResource:*SPW*)" 
	size="5"> </catalogue-results-card></div>
```

**Comment by vbombaerts** [comment]
Retours des collègues suite à la première version :

- [x]  Aérer les cartes (plus d'espace entre les cartes, moins de cartes par ligne)

Possibilité de définir le nombre de cartes par ligne via le paramètre _**itemsperrow**_

```
 itemsperrow="3"
```

![image](https://user-images.githubusercontent.com/576292/157009267-69ea49f9-5424-4100-866e-deb54e20edd9.png)


- [x]  Ne pas indiquer la date de mise à jour

Ne pas compléter les paramètres liés à la zone info (_infoIndex_ et _infoJsonPath_)

- [x]  Accéder à l'application en cliquant sur le visuel ou via un Call to action mieux identifié

Possibilité de configurer le bouton vers le lien souhaité (dépendance vis-à-vis de linkInddex) : 
- couleur via le paramètre **_linkButtonColor_**
- text via le paramètre **_linkHook_**
- icon via le paramètre **_linkIcon_**

```
fields='{"imageIndex": "overview", "imageJsonPath":"$[0].url", "titleIndex": "resourceTitleObject", "titleJsonPath":"$.default", "titleSize":"h4", "subTitleIndex": "custodianOrgForResource", "subTitleJsonPath":"", "textIndex": "resourceHookAbstractObject", "textJsonPath":"$.default","linkIndex": "mw-gp-thematicMap", "linkJsonPath":"$[0].url", "linkIcon":"map", "linkButtonColor":"green", "linkHook":"Découvrir", "infoIndex": "revisionDateForResource","infoJsonPath":"$[0]"}'

```

![image](https://user-images.githubusercontent.com/576292/157062793-7bb27a23-1b66-431c-b6c8-2fc12ee68085.png)

Le set de couleurs est actuellement limité à

![image](https://user-images.githubusercontent.com/576292/157063818-4406ebd4-5ded-41f7-ad1c-1659b19e792e.png)


- [x]  Résoudre le provlème des fichiers icones. 

Besoin de modifier le nom des fichiers styles pour éviter l'id du build.
Pour l'instant, il faut utiliser les références suivantes:

```
<link rel="stylesheet" href="https://apps.titellus.net/hub/webcomponents/styles.ef53c8a098d2c6ec.css"> 
<link rel="stylesheet" href="https://apps.titellus.net/hub/webcomponents/main.5210541a9d9540bc.css"> 
```



- [x]  Lien "Plus d'info" vers une fiche géoportail avec des captures d'écran, explications détaillées, infos techniques, évaluation

![image](https://user-images.githubusercontent.com/576292/157062793-7bb27a23-1b66-431c-b6c8-2fc12ee68085.png)


- [x]  Ajouter la possibilité de choisir la méthode de tri des résultats (alphabétique, popularité, à terme évaluation)

Via les paramètres suivants:

```
      sorttype="asc"
      sortby="custodianOrgForResource"
```

- [x]  Ajouter "Focus on" avec Thèmes du GP

Via le paramètre suivant:

```
      filterfield="th_Themes_geoportail_wallon_hierarchy.default"
```
      


- [x]  Ajouter le nom du propriétaire

Via le paramètre suivant:

```
      fields='{"image": "overview", "imageJsonPath":"$[0].url", "title": "resourceTitleObject", "titleJsonPath":"$.default", "subTitle": "custodianOrgForResource", "subTitleJsonPath":"", "text": "resourceHookAbstractObject", "textJsonPath":"$.default","link": "mw-gp-thematicMap", "linkJsonPath":"$[0].url","info": "revisionDateForResource","infoJsonPath":"$[0]"}'
```
Selon la zone du template : example via subTitle

![image](https://user-images.githubusercontent.com/576292/156803180-17fd3ba7-8c39-46ed-8e95-384566956a41.png)


- [x]  Diminuer la taille du nom du titre

Possibilité de configurer la taille du titre via le paramètre **_titleSize_** (h1, h2,h3,h4)

**Comment by vbombaerts** [comment]
Ca commence a être très sympa ! 👍 

Quelques remarques :
> * [x]   Aérer les cartes (plus d'espace entre les cartes, moins de cartes par ligne)
> 
> Possibilité de définir le nombre de cartes par ligne via le paramètre _**itemsperrow**_
> 
> ```
>  itemsperrow="3"
> ```

Du coup les cartes sont plus grandes, mais pas nécessairement plus aérées...

> Ajouter la possibilité de choisir la méthode de tri des résultats (alphabétique, popularité, à terme évaluation)
> Via les paramètres suivants:
>
>      sorttype="asc"
>      sortby="custodianOrgForResource"

L'idée est d'avoir une dropdown pour pouvoir choisir la méthode de tri parmi (nom de l'application, gestionnaire de l'application, popularité, évaluation)

**Comment by vbombaerts** [comment]
Autres demandes : 
- tu penses qu'on pourrait avoir 2 filter fields ? (thèmes GP + owner)
- Est-il possible d'ajouter une zone de recherche libre ?

**Comment by vbombaerts** [comment]
Si on veut monter en prod dans l'état actuel, j'imagine que les bibliothèques css et js doivent être placées qqpart dans Metawal plutôt que sur apps.titellus.net
C'est faisable ?

**Comment by davinciagf** [comment]
TODO:

- [ ]  Migration des fichiers vers MW
- [x] ajout d'une zone de recherche

Ajout du paramètre (besoin de type text, pas keyword) : 
``` 
fulltextfilter="resourceTitleObject.default,` resourceHookAbstractObject.default"
```
![image](https://user-images.githubusercontent.com/576292/157843075-1776d3b2-c432-4109-b03a-966b1d4187b8.png)

- [x] test pour un double filtre

![image](https://user-images.githubusercontent.com/576292/157845058-eaccac30-6242-41c5-a311-c66af823c356.png)
Ajout du paramètre  : 
``` 
filterfield_2="custodianOrgForResource"
```

- [x] ajout d'un dropdow pour classification

![image](https://user-images.githubusercontent.com/576292/158148284-088ba32b-20c6-41af-8483-0e730dc4a946.png)
Ajout du paramètre  : 
``` 
sortbylist='{"sortIndexRef":"resourceTitleObject.default.keyword", "sortName":"Titre"} | {"sortIndexRef":"popularity", "sortName":"Popularité"} | {"sortIndexRef":"resourceHookAbstractObject.default.keyword", "sortName":"Résumé"}'
```

- [x] Pour l'aération (en x)

![image](https://user-images.githubusercontent.com/576292/158158136-370c5ba4-f5df-4974-aa90-d57abe82ca31.png)

Ajout du paramètre (en '_em_' : 
``` 
marginx="8"
```

**Comment by vbombaerts** [comment]
@davinciagf si en plus tu pouvais me trouver le paramètre pour espacer les filtres de la liste de résultats ce serait le top du top ;-)

![image](https://user-images.githubusercontent.com/6093597/158199260-7c9b44ec-c1e4-4fe4-94b2-7a2e8fac4e79.png)

**Comment by davinciagf** [comment]
@vbombaerts 
Ajout du paramètre (en 'em') :   

```
margintoolsbottom="2"
```
![image](https://user-images.githubusercontent.com/576292/158207398-67197b74-f7e4-4169-badc-0cec8c603430.png)

**Comment by vbombaerts** [comment]
Demandes supplémentaires en vue de l'intégration dans le GP. Elles portent essentiellement sur l'harmonisation des aspects visuels. (avec d'abord un grand enthousiasme par rapport au travail déjà réalisé)
- [x] Est-il possible de fixer la hauteur de la ligne de titre dans la carte. Même si on va travailler par ailleurs sur l'harmonisation des visuels, le but est d'éviter l'effet "escalier" si les imagettes n'ont pas la même taille.  

Possibilité de paramétrer la taille des images (px) via le paramètre _imageheight_
```
imageheight="280"
```
![image](https://user-images.githubusercontent.com/576292/159466398-16ef539c-7752-44f7-8192-83b9b836592d.png)

- [x] Modification de la couleur des boutons - code #0676C5 (pour le moment j'ai mis blue, qui s'en approche le plus) - code exact à fournir par l'équipe géoportail

Utilisation des codes couleurs hex, ne plus utiliser le listing  de couleurs précédemment référencé

```
fields='{"imageIndex": "overview", "imageJsonPath":"$[0].url", "titleIndex": "resourceTitleObject", "titleJsonPath":"$.default", "titleSize":"h4", "subTitleIndex": "custodianOrgForResource", "subTitleJsonPath":"", "textIndex": "resourceHookAbstractObject", "textJsonPath":"$.default","linkIndex": "mw-gp-thematicMap", "linkJsonPath":"$[0].url", "linkIcon":"map", "linkButtonColor":"#335500", "linkHook":"Découvrir", "infoIndex":"revisionDateForResource", "infoJsonPath":"$[0]", "additionalInfoIndex":"cl_accessConstraints", "additionalInfoJsonPath":"$[0].key"}'

```

- [x] Ouvrir les liens dans des nouveaux onglets, pas dans le même (pour le bouton "Découvrir")
- [x] Marge entre les cartes et la pagination

Paramétrable via le paramètre _marginbottom_
```
marginbottom="1"
```
- [x] Ne pas afficher "29 results found in 5 ms"
- [x] Coquille au chargement des résultats : Loa**dd**ing, un d en trop.
- [x] Suite à une discussion sur l'utilité ou non d'exposer la fiche : retirer le lien "plus d'info"

Paramétrable via le paramètre _linkmdt_
```
linkmdt="false"

```

- [x] Ajout d'un visuel (petit cadenas) pour différencier les applications sécurisées (à accès restreint) - basé sur la valeur d'index `cl_accessConstraints.key = restricted` - voir en haut à droite de la fiche https://geoportail.wallonie.be/catalogue/e6df1e1d-e3a4-4cff-b8b7-ebc0838ee234.html

Inclure les paramètres _additionalInfoIndex_ et _additionalInfoJsonPath_ (@vbombaerts à discuter, autres éléments de config? comme pour le _linkIcon_)

```
fields='{"imageIndex": "overview", "imageJsonPath":"$[0].url", "titleIndex": "resourceTitleObject", "titleJsonPath":"$.default", "titleSize":"h4", "subTitleIndex": "custodianOrgForResource", "subTitleJsonPath":"", "textIndex": "resourceHookAbstractObject", "textJsonPath":"$.default","linkIndex": "mw-gp-thematicMap", "linkJsonPath":"$[0].url", "linkIcon":"map", "linkButtonColor":"#335500", "linkHook":"Découvrir", "infoIndex":"revisionDateForResource", "infoJsonPath":"$[0]", "additionalInfoIndex":"cl_accessConstraints", "additionalInfoJsonPath":"$[0].key"}'

```

![image](https://user-images.githubusercontent.com/576292/159460710-6dfb0a3d-206e-4814-a647-fffa22e88c66.png)

- [x] Zone filtres - les deux boites aux extrémités sont trop proches des bords du navigateur. Parfois il n'est pas possible d'accéder à celle de droite
- [x] Zones filtres - remplacer "Focus on" par "Thème" et "Propriétaire" / Remplacer "Search..." par "Recherche libre"

Paramétrable via le paramètres _linkmdt_
```
search_placeholder="Recherche libre"
filterfield_placeholder="Thème"
filterfield_2_placeholder="Propriétaire"

```

- [x] Zones filtres - Supprimer les séparateurs | entre les boîtes

**Comment by davinciagf** [comment]
Harmonisation des filtre par rapport au card
<img width="948" alt="image" src="https://user-images.githubusercontent.com/576292/160196413-2c03af07-7187-433c-872b-7150b71283ba.png">
<img width="514" alt="image" src="https://user-images.githubusercontent.com/576292/160196486-0c229ea9-3ef9-4a46-a6fe-c0bc5f726e43.png">

**Comment by vbombaerts** [comment]
> Harmonisation des filtre par rapport au card <img alt="image" width="948" src="https://user-images.githubusercontent.com/576292/160196413-2c03af07-7187-433c-872b-7150b71283ba.png"> <img alt="image" width="514" src="https://user-images.githubusercontent.com/576292/160196486-0c229ea9-3ef9-4a46-a6fe-c0bc5f726e43.png">

Ne fonctionne pas chez moi, même après vidage du cache

**Comment by vbombaerts** [comment]
> Ne fonctionne pas chez moi, même après vidage du cache

Toujours pas aligné

**Comment by vbombaerts** [comment]
> Derrière le visuel, on a aussi le lien vers l'application.

Je ressors cette demande du ticket initial. Est-ce possible d'avoir le lien vers l'appli aussi derrière l'illustration ? eg qd l'utilisateur clique sur l'illustration un nouvel onglet ouvre l'appli.

**Comment by davinciagf** [comment]
Fonctionnalité ajouter si le pramètre linkIndex est défini et est disponible pour la mtd. 
Intégration au niveau de l'env de test (redéploiement en cours).

**Comment by vbombaerts** [comment]
Et pour l'alignement des filtres, il y a qqch de spécial à faire ?

**Comment by davinciagf** [comment]
Il y un couac qq part dans l'intégration avec jahia car je ne reproduis pas sur une page html classique. J'ai réalisé une modif mais je dois redéployer pour tester dans jahia.

**Comment by davinciagf** [comment]
Cela semble ok pour l'aligenement : 
![image](https://user-images.githubusercontent.com/576292/162187631-04bf332e-bbe7-411e-8d5c-1f803e384987.png)
![image](https://user-images.githubusercontent.com/576292/162187726-151ef958-24aa-49ba-a95c-616bf29be1dc.png)

**Comment by vbombaerts** [comment]
Pour l'alignement tenir compte des marges entre les cartes. Certaines combinaisons permettent l'alignement, d'autres pas.

**Comment by vbombaerts** [comment]
Réouverture pour 2 demandes supplémentaires suite à [implémentation réelle dans le géoportail](https://geoportail.wallonie.be/mapstore.html) :

- [ ] La pagination s'affiche actuellement en anglais (Prev / Next), est-il possible de l'avoir en français ?
- [ ] Peut-on ajuster la marge entre les lignes de cartes ?

**Comment by davinciagf** [comment]
Proposition pour la pagination : 
![image](https://user-images.githubusercontent.com/576292/170236599-2f2511c7-3b0b-4b54-baf5-6afc17727e93.png)

**Comment by vbombaerts** [comment]
Garder le même qu'actuellement juste en traduisant ce n'est pas possible ?
![image](https://user-images.githubusercontent.com/6093597/170650319-66c87e87-e513-4a9c-8d1e-e0beb2ac2737.png)

**Comment by vbombaerts** [comment]
Suite dans #743
