### ISSUE TITLE
API / Related / Même structure multilangue

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#719]
Dans les champs ajoutés au JSON par la l'API/related, le multilingue n'est pas géré de la même façon que dans le reste du JSON

![image](https://user-images.githubusercontent.com/1701393/156565140-ddf3a909-dbeb-42d6-b536-031dc2813718.png)

alors que dans un champ indexé on a

![image](https://user-images.githubusercontent.com/1701393/156565195-cf80363a-c2ef-4782-9d58-c7c637ec41f5.png)

Ce serait peut-être mieux d'avoir la même logique partout.

Follow up of https://github.com/SPW-DIG/metawal-core-geonetwork/issues/695 

## Proposal

Current mechanism is:
* GET /api/records/{uuid}/related
* Extract relations for records
* We have 2 main types of relations
  * Metadata records
  * Online source / overview / additional document (eg. legend) 
* For metadata records, we have 3 types of links
  * Those who are in the XML eg. parent
  * Those who requires a search to find associated records eg. children
  * Those pointing to remote records
* Processing is
  * Get XML (taking into account user privileges eg. if not dynamic, then online source are filtered)
  * Collect record links from XML
  * Collect record links using searches
  * Append remote records links   
  * Check if records are in current portal or not
  * Build a Java XML response processed by XSLT relation.xsl which mainly collect online source links

Comments:
* related API returns online links which are already in the index document - maybe we could remove those information from the API
* instead of having a custom model for associated records we could directly report the index document for related records

Proposal:
* Add a GET /api/records/{uuid}/associated operation which returns only records (no more links already available through the search API)
* Deprecate GET /api/records/{uuid}/related
* Response model
```json
{
  "children": [{
    "uuid": "",
    "origin": "catalog|portal|remote",
    "edit": true|false,
    (optional) "props": {
      "url": "", (For remote records)
      "title": "", (For remote records)
      "associationType": "", (For siblings)
      "initiativeType": "" (For siblings)
    },
    (optional) "record": {
      index document ...
    }
  }],
  "services": [],
}
```

Tasks:

- [x] API add operation
- [x] API search / add the new response into the related element
- [x] Record view / Use the new API
- [x] Editor view / Rework the online source panel to work with index document for associated for records.
- [ ] Editor view / Rework the online source panel to work with index document for links (issue - links element in the index is not yet multilingual)

**Comment by fxprunayre** [comment]
Cf. https://github.com/geonetwork/core-geonetwork/pull/6269

**Comment by fxprunayre** [comment]
A déployer en test.

Pour le dernier point, je propose de le traiter à part.

**Comment by fxprunayre** [comment]
```
curl 'https://apps.titellus.net/geonetwork/srv/api/search/records/_search?bucket=s101&relatedType=parent&relatedType=children&relatedType=services&relatedType=datasets' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: eng' \
  -H 'Content-Type: application/json;charset=UTF-8' \
  -H 'Cookie: XSRF-TOKEN=3944f93a-5d74-4621-853d-a056af19aad8; JSESSIONID=node01s15pyctv6xqmc70igako6zfi862.node0; serverTime=1654161981806; sessionExpiry=1654161981806' \
  -H 'X-XSRF-TOKEN: 3944f93a-5d74-4621-853d-a056af19aad8' \
  --data-raw '{"from":0,"size":30,"sort":["_score"],"query":{"function_score":{"boost":"5","functions":[{"filter":{"exists":{"field":"parentUuid"}},"weight":0.3},{"filter":{"match":{"cl_status.key":"obsolete"}},"weight":0.2},{"filter":{"match":{"cl_status.key":"superseded"}},"weight":0.3},{"gauss":{"dateStamp":{"scale":"365d","offset":"90d","decay":0.5}}}],"score_mode":"multiply","query":{"bool":{"must":[{"terms":{"isTemplate":["n"]}}]}}}},"_source":{"includes":["uuid","id","creat*","group*","logo","category","topic*","inspire*","resource*","draft*","overview.*","owner*","link*","image*","status*","rating","tag*","geom","contact*","*Org*","hasBoundingPolygon","isTemplate","valid","isHarvested","dateStamp","documentStandard","standardNameObject.default","cl_status*","mdStatus*","recordLink"]},"track_total_hits":true}' \
  --compressed
```

Dans la recherche, pour chaque résultat on obtient les ressources associées 
![image](https://user-images.githubusercontent.com/1701393/171600330-44ecccf8-2e1f-492e-9ae8-709251e89be0.png)


Ancienne API
https://apps.titellus.net/geonetwork/srv/api/records/7bbdd386-21dc-47cd-a4af-4f4c7583663b/related
Nouvelle API
https://apps.titellus.net/geonetwork/srv/api/records/7bbdd386-21dc-47cd-a4af-4f4c7583663b/associated

**Comment by vbombaerts** [comment]
C'est super !

Serait-il possible, pour Metawal, d'ajouter l'accroche, indexée dans resourceHookAbstractObject ?

Autre chose, via l'API related on obtenait des infos sur tous ces éléments :
children
parent
brothersAndSisters
siblings
associated
services
datasets
fcats
hasfeaturecats
sources
hassources
related
onlines
thumbnails

Si j'ai bien compris, tout ce qui est documents attachés n'est maintenant plus disponible via l'api associated, à savoir.
onlines
thumbnails

Du coup par où sont-ils disponibles ? 
link
overview 

C'est ça ?

**Comment by fxprunayre** [comment]
> Serait-il possible, pour Metawal, d'ajouter l'accroche, indexée dans resourceHookAbstractObject ?

Je vais regarder.


> Du coup par où sont-ils disponibles ? link overview
> C'est ça ?

Oui.

**Comment by fxprunayre** [comment]
> > Serait-il possible, pour Metawal, d'ajouter l'accroche, indexée dans resourceHookAbstractObject ?

J'ai fait simple. A tester.

**Comment by vbombaerts** [comment]
Les liens dans link, encodés en multilingue, ne sont pas indexés en multilingue ;-)
https://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/9701fc80-842c-11ec-92f0-7478273ff935

![image](https://user-images.githubusercontent.com/6093597/172802128-a5b93c0a-892f-4b13-9973-197b29f24103.png)

![image](https://user-images.githubusercontent.com/6093597/172802292-2b953a99-53d8-4adc-b86f-2884dcd20b56.png)

**Comment by fxprunayre** [comment]
C'est en cours côté geocat.ch (également pour les organisations) - on attend un peu.

**Comment by fxprunayre** [comment]
> pour les organisations, les liens

cf. https://github.com/geonetwork/core-geonetwork/pull/6588

**Comment by fxprunayre** [comment]
Idem https://github.com/SPW-DIG/metawal-core-geonetwork/issues/704#issuecomment-1277501968

A déployer.

**Comment by vbombaerts** [comment]
Tous les liens ne sont pas indexés en multilingue

https://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/a0ad23a1-1845-4bd5-8c2f-0f62d3f1ec75

Si function = information, browsing --> OK
Si function = legend, featureCatalogue, dataQualityReport --> KO

Ca dépend peut-être de la section dans laquelle les liens sont encodés.

**Comment by vbombaerts** [comment]
@vbombaerts Pour les organisations, corriger les scriptedfields qui utilisent l'ancien élément

**Comment by vbombaerts** [comment]
Sauf erreur de ma part, le multinlinguisme ne devrait-il pas aussi être poussé dans les éléments correspondants mw-gp dérivés des links :
- mw-gp-informationWebsite
- mw-gp-informationDoc
- mw-gp-thematicMap
- mw-gp-wom
- mw-gp-esriWebServices
- mw-gp-allWebServices
- mw-gp-download

**Comment by fxprunayre** [comment]
A tester & déployer

**Comment by davinciagf** [comment]
Déployé
![image](https://user-images.githubusercontent.com/576292/201033506-72d69a11-a6bb-433e-959d-aca051364bad.png)

**Comment by vbombaerts** [comment]
l'url n'est pas passée en multilingue dans les 

mw-gp-informationWebsite
mw-gp-informationDoc
mw-gp-thematicMap
mw-gp-wom
mw-gp-esriWebServices
mw-gp-allWebServices
mw-gp-download

**Comment by fxprunayre** [comment]
Mince, j'avais la modif en local mais je l'ai pas commité hier. Dsl. Redeploy @davinciagf

**Comment by davinciagf** [comment]
En cours de reindexation 
![image](https://user-images.githubusercontent.com/576292/201930118-ea19e607-6b5f-4c8b-93d7-87f1957de882.png)
