### ISSUE TITLE
Contacts / tootlip est en anglais

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#72]
- La plupart ne sont pas passés (ou visible que XML).
- pour certaines fiches un ou deux contacts apparaissent dans la vue résultat, sous l'imagette. Le 'label' est en anglais.
  ![contact_anglais](https://f.cloud.github.com/assets/6093453/1662933/8590e894-5c08-11e3-9dcb-51fd8bc0acb8.jpg)

**Comment by fxprunayre** [comment]
A vérifier en v4

**Comment by fxprunayre** [comment]
Présentation différente en v4 et le rôle est traduit quand affiché. Je ferme.
