### ISSUE TITLE
Configuration d'un moissonneur - réorganisation des éléments

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#724]
Réorganiser les différents éléments de l'interface de configuration des moissonneurs pour indiquer les éléments dans l'ordre dans lequel ils sont joués : 
- adresse de connexion au CSW
- paramètres d'authentification
- type de standard demandé
- filtre sur le CSW
- transformation XSL
- Edition batch
- Groupe dans lequel les enregistrements sont placé et utilisateur auxquels ils sont affectés
- Droits sur les fiches
...

**Comment by fxprunayre** [comment]
Cf. https://github.com/geonetwork/core-geonetwork/pull/6221

**Comment by fxprunayre** [comment]
A déployer.

**Comment by davinciagf** [comment]
Déployé en test

**Comment by vbombaerts** [comment]
Super.
