### ISSUE TITLE
Documentation de la procédure de relance de l'environnement de test

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#726]
Hello,

Afin de gagner un peu d'indépendance et d'arrêter de solliciter Arnaud à tout bout de champ je souhaite être capable de relancer l'environnement de test (MW et/ou ES) quand il ne répond pas. #703  

@davinciagf Tu peux m'écrire un procédure STP ?

**Comment by davinciagf** [comment]
Voir doc dans teams - https://walloniegov.sharepoint.com/:w:/r/sites/Metawal-Maintenanceetdveloppements/Documents%20partages/General/Notes%20relatives%20%C3%A0%20metawal%20test.docx?d=w261da0e2db54434ea04edc2ffa3af1e6&csf=1&web=1&e=LEtKoW

**Comment by vbombaerts** [comment]
Pas trouvé. Tu peux me le pointer STP ?

**Comment by vbombaerts** [comment]
@davinciagf 
Tu peux ajouter :
- une section sur la configuration de l'environnement (schéma, où est installé quoi, qui parle à qui, etc)
- une section les outils à utiliser et leurs configurations (adresse serveurs, etc) pour lancer ces commandes STP ?

**Comment by davinciagf** [comment]
Doc mis à jour

**Comment by vbombaerts** [comment]
En attente d'installation de putty et d'accès au serveur pour tester

**Comment by vbombaerts** [comment]
Toujours en attente des accès. Je déplace sur la 4.2.1

**Comment by vbombaerts** [comment]
@vbombaerts - A adapter pour les outils utilisés au SPW

**Comment by vbombaerts** [comment]
Adapté
