### ISSUE TITLE
Vue simplifiée : Manque les Contacts

### ISSUE THREAD

**Issue by geologiewallonie** [SPW-DIG/metawal-core-geonetwork#73]
Aucune information concernant les contacts n'apparait au niveau de l'affichage simplifié d'une fiche.

![3](https://f.cloud.github.com/assets/6093460/1662947/d4c3547e-5c08-11e3-9ba8-935b0aeedbda.JPG)

**Comment by geologiewallonie** [comment]
Idem pour la généalogie !

**Comment by fxprunayre** [comment]
Corrigé eg. http://metawal3.test.wallonie.be/geonetwork/srv/fre/search?uuid=8641e5e1-8310-40ad-b78e-7469ea48dd93

> Idem pour la généalogie !

Doublon cf. #1
