### ISSUE TITLE
Evolution du nombre de gestionnaires au cours du temps

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#731]
Hello,

Je voudrais créer un tableau qui me montre l'évolution du nombre de gestionnaires et l'évolution du nombre de données par gestionnaire au cours du temps avec comme variable de temps **la date de création de la fiche** (et non pas le datestamp).
Idéalement avec des niveaux d'agrégation différents. Comme il y a des données qui sont déclarées à différents niveaux d'agrégation des gestionnaires, la somme des sous-entités n'est pas égale au chiffre indiqué pour l'entité.

Deux questions :
1. Je sais qu'il y a moyen de paramétrer dans Kibana la variable temporelle (mais je ne sais plus comment). J'imagine que ça n'affecte pas les interfaces et outils Metawal qui se basent sur ES et non sur Kibana. Du coup seules les visualisations et tableaux de bord seraient affectés par ce changement. Pour ne rien modifier, est-ce que créer un deuxième index Kibana sur base de la date de création serait une bonne idée ?
2. Est-il possible dans un tableau Kibana d'afficher une évolution temporelle (chaque colonne = la situation à une date définie)

Je continue à chercher mais si vous avez des pistes je suis preneur...

**Comment by vbombaerts** [comment]
Voici le genre de tableau ou de graphique qu'on cherche à créer. Ici retravaillé à partir d'un export de https://metawal.wallonie.be/geonetwork/dashboards/app/discover#/view/f4578c60-af9c-11ec-9c43-0f70b8f525db?_g=(filters%3A!()%2CrefreshInterval%3A(pause%3A!t%2Cvalue%3A0)%2Ctime%3A(from%3Anow-15y%2Cto%3Anow))

 
![image](https://user-images.githubusercontent.com/6093597/160765161-b628bc7a-456a-4dee-baf2-bd5c2e7c26ea.png)

![image](https://user-images.githubusercontent.com/6093597/160765250-03f6f3c7-f5a4-4c7f-9888-61bcc99855b9.png)

**Comment by fxprunayre** [comment]
Quelquechose comme ça https://metawal.wallonie.be/geonetwork/dashboards/app/lens#/edit/e9693130-b020-11ec-9c43-0f70b8f525db?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15y,to:now)) ?
