### ISSUE TITLE
Admin - redéfinir le mot de passe d'un utilisateur

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#733]
Dans le temps l'admin avait le droit de réinitialiser un mdp pour un utilisateur non-LDAP.
Ce n'est plus le cas.
Est-il possible de rétablir cette possibilité ?

**Comment by fxprunayre** [comment]
En lien avec https://github.com/geonetwork/core-geonetwork/pull/5550

**Comment by fxprunayre** [comment]
Ajouter en base

```sql
INSERT INTO Settings (name, value, datatype, position, internal) 
  VALUES ('system/security/password/allowAdminReset', 'true', 2, 12004, 'n');
```

pour autoriser les admin à faire un reset des passwords via l'interface (et l'API).

![image](https://user-images.githubusercontent.com/1701393/163201352-c5878b7b-45fc-48ce-b30d-519c04445d78.png)


Cf. https://github.com/geonetwork/core-geonetwork/pull/6235
Dans GeoNetwork, une installation par défaut n'a pas la variable en base pour des raisons de sécurité pour être cohérent avec la PR initiale (si un compte admin est compromis alors il serait possible de faire un reset de tous les comptes ...). Elle est donc toujours à false sauf à partir du moment où on l'ajoute à la base (et c'est nécessaire pour les install où y'a pas de serveur de mail ou pas d'accès base simple comme mw).

**Comment by fxprunayre** [comment]
A déployer en test.

**Comment by davinciagf** [comment]
Déployé et testé en test  pour utilisateur non LDAP

**Comment by vbombaerts** [comment]
J'ai pas trouvé l'option.

![image](https://user-images.githubusercontent.com/6093597/172824576-51f0426d-c347-413d-b5f9-ec06b0eb49aa.png)


L'utilisateur lui-même peut changer son mot de passe.

Dans certains cas, l'option s'affiche, mais l'admin ne peut pas le réinitialiser (sans le connaitre).

**Comment by fxprunayre** [comment]
Moi je l'ai https://metawal4.test.wallonie.be/geonetwork/srv/eng/admin.console#/organization
![image](https://user-images.githubusercontent.com/1701393/172840329-6f029186-9ddf-48bf-8a4c-73c73c24098a.png)

**Comment by davinciagf** [comment]
Présent en mode eng seulement non dispo pour les autres langues. Vérifier le param en base.

**Comment by davinciagf** [comment]
Problème de synchro corrigée. A tester
