### ISSUE TITLE
 Mapping Metawal-géoportail (suite)

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#734]
Deux demandes restantes 
- [ ] Association service/données - dans la fiche de la donnée, vers les liens - tenter de faire un matching sur l'URL pour afficher un bouton consulter la fiche quand un service est aussi dans les related. Faire côté interface pour le moment / A voir si on fait ça à l'indexation.
- [ ] Dans les champs ajoutés au JSON par la l'API/related, le multilingue n'est pas géré de la même façon que dans le reste du JSON

_Originally posted by @vbombaerts in https://github.com/SPW-DIG/metawal-core-geonetwork/issues/695#issuecomment-1072249018_

**Comment by fxprunayre** [comment]
> Dans les champs ajoutés au JSON par la l'API/related, le multilingue n'est pas géré de la même façon que dans le reste du JSON

Fait. Cf. https://github.com/SPW-DIG/metawal-core-geonetwork/issues/704

**Comment by vbombaerts** [comment]
Je ne sais plus ce que c'est. Je ferme
