### ISSUE TITLE
Configuration moissonnage - Groupe

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#736]
**Describe the bug**
Quel que soit le groupe défini dans la config du moissonneur, dès qu'on revient dessus le groupe est par défaut indiqué à SPW-Environnement.

**Comment by fxprunayre** [comment]
A déployer. https://github.com/geonetwork/core-geonetwork/pull/6248

**Comment by fxprunayre** [comment]
A déployer en test.

**Comment by davinciagf** [comment]
Déployé en test, le groupe défini au niveau du moisonneur  reste bien enregistré après avoir sauver et quitter le moissonneur.
