### ISSUE TITLE
Mapstore - intranet

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#737]
Quelques demandes supplémentaires pour la version intranet du Mapstore
- toggle button / check box permettant de masquer les applications sécurisées 

Autres specs à venir

**Comment by vbombaerts** [comment]
Indexer le champ "Précision sur le type de ressource" 
![image](https://user-images.githubusercontent.com/6093597/175959189-5fbc71c1-4553-4606-9913-535d718cbef8.png)

**Comment by davinciagf** [comment]
Pour le champ le champ "Précision sur le type de ressource" voir `resourceTypeNameObject.default`

**Comment by marceaulouis** [comment]
Problème de pagination des sous-tables (n'affiche que 9 cartes et pagination ineffective)

**Comment by davinciagf** [comment]
Correction apportée via https://github.com/titellus/icho/commit/bc5649d9d4bc61b00a1d6fc3fcfee93d87cb7134.
A déployer

**Comment by vbombaerts** [comment]
Est-il possible d'utiliser resourceTypeNameObject.default dans un filterfield ? Ici je n'y arrive pas
Il fonctionne dans un "filter" mais pas dans un "filterfield". Une idée ?

```
<p>Test Mapstore intranet</p>

<link href="https://metawal.wallonie.be/geonetwork/catalog/lib/icho/styles.css" rel="stylesheet" />
<link href="https://metawal.wallonie.be/geonetwork/catalog/lib/icho/main.css" rel="stylesheet" />
<div style="margin: 2.5em">
<catalogue-results-card catalogueurl="https://metawal.wallonie.be/geonetwork/mapstore-intranet" 
fields='{
"imageIndex": "overview", "imageJsonPath":"$[0].url",
"titleIndex": "resourceTitleObject", "titleJsonPath":"$.default", "titleSize":"h4",
"subTitleIndex": "ownerOrgForResource", "subTitleJsonPath":"",
"textIndex": "purposeObject", "textJsonPath":"$.default",
"linkIndex": "mw-gp-thematicMap", "linkJsonPath":"$[0].url", "linkIcon":"map", "linkButtonColor":"#0676C5", "linkHook":"Découvrir",
"additionalInfoIndex":"cl_accessConstraints", "additionalInfoJsonPath":"$[0].key"
}'
filter='+(resourceType:application) -(th_infraSIG.default:Reporting_INSPIRE) -(cl_status.key:obsolete)' 
fulltextfilter="resourceTitleObject.default,` resourceHookAbstractObject.default"
search_placeholder="Recherche libre"
filterfield_2="th_Themes_geoportail_wallon_hierarchy.default"
filterfield_2_placeholder="Thème"
filterfield="resourceTypeNameObject.default"
filterfield_placeholder="Type d'application" 
linkmdt="false"
imageheight="215" 
itemsperrow="4" size="12" marginx="1" margintoolsbottom="1" marginbottom="2" 
sorttype="asc" sortby="resourceTitleObject.default.keyword"
sortbylist='{"sortIndexRef":"resourceTitleObject.default.keyword", "sortName":"Titre"} | {"sortIndexRef":"popularity", "sortName":"Popularité"}'
> </catalogue-results-card></div>
<script src="https://metawal.wallonie.be/geonetwork/catalog/lib/icho/runtime.esm.js"  type="module">
</script><script src="https://metawal.wallonie.be/geonetwork/catalog/lib/icho/polyfills.esm.js" type="module">
</script><script src="https://metawal.wallonie.be/geonetwork/catalog/lib/icho/main.esm.js" type="module"></script>
```

**Comment by davinciagf** [comment]
L'erreur est liée à la nature de l'indice sélectionné. Il n'est pas possible par défaut d'utiliser des indices de type "text field" dans le filtre.

`Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [resourceTypeNameObject.default] in order to load field data by uninverting the inverted index. Note that this can use significant memory.`

Investigation pour contourner ce problème (via changement dans le mapping).
- [x] Modification du type dans GN et vérification de la présence en139 (hierarchyLevelName) ==> PR GN https://github.com/geonetwork/core-geonetwork/pull/6597

**Comment by vbombaerts** [comment]
> [x] Modification du type dans GN et vérification de la présence en139 (hierarchyLevelName) ==> PR GN [Index field data types - Define resourceTypeName type geonetwork/core-geonetwork#6597](https://github.com/geonetwork/core-geonetwork/pull/6597)

OK
