### ISSUE TITLE
Mapping 19139 --> 19115-3 - DateStamp

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#738]
Dans les fiches moissonnées 19115-3, il n'y a pas de date de révision pour la fiche. Uniquement une date de création.
Dans les fiches originales 19139, on a un datestamp qui correspond à la date de dernière mise à jour de la fiche.

==> Modifier le mapping ISO 19139 --> ISO 19115-3 pour ajouter le datestamp dans la date de révision. Je ne sais pas si il faut du coup le retirer de la date de création ; je ne sais pas par qui/quoi cette valeur est utilisée. 

Autre possibilité : définir le champ temporel de l'index comme la date de création de la fiche et non sa date de révision

_Originally posted by @vbombaerts in https://github.com/SPW-DIG/metawal-core-geonetwork/issues/676#issuecomment-1088405037_

**Comment by fxprunayre** [comment]
Cf. https://github.com/geonetwork/core-geonetwork/pull/6303

**Comment by davinciagf** [comment]
A merger dans MW

**Comment by fxprunayre** [comment]
A déployer en test.

**Comment by davinciagf** [comment]
Déployé en test.
