### ISSUE TITLE
renommer services associés en métadonnées des services associés?

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#74]
Pour que cela soit plus clair pour les utilisateurs (qu'on n'ouvre pas le service, mais ses MD)
![services_associes](https://f.cloud.github.com/assets/6093453/1662955/ea0cd42c-5c08-11e3-83a6-e5805195f7df.jpg)

**Comment by fxprunayre** [comment]
Cf. discussion ergonomie https://github.com/spacebelGIS/metawal-core-geonetwork/issues/74

**Comment by vbombaerts** [comment]
Comme les liens renvoient à des services mais aussi des applications, il faudrait modifier en 
"Métadonnées des services et applications associées"
