### ISSUE TITLE
Suggestion / Si ESRI:REST ajout WMS et/ou légende

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#740]
L'éditeur encode le lien vers le service ESRI:REST eg. https://geoservices.wallonie.be/arcgis/rest/services/EAU/RHW/MapServer

Une suggestion permet l'ajout :
* du WMS correspondant https://geoservices.wallonie.be/arcgis/services/EAU/RHW/MapServer/WMSServer?request=GetCapabilities&amp;service=WMS en reprenant le même `name` et `description` (en remplaçant ESRI-REST par WMS)
```xml
<mrd:onLine>
  <cit:CI_OnlineResource>
     <cit:linkage>
        <gco:CharacterString>https://geoservices.wallonie.be/arcgis/rest/services/EAU/RHW/MapServer/WMSServer?request=GetCapabilities&amp;service=WMS</gco:CharacterString>
     </cit:linkage>
     <cit:protocol>
        <gco:CharacterString>OGC:WMS</gco:CharacterString>
     </cit:protocol>
     <cit:name>
        <gco:CharacterString>Service de visualisation WMS - Vue détaillée</gco:CharacterString>
     </cit:name>
     <cit:description>
        <gco:CharacterString>Ce service WMS permet de visualiser la série de données relative au réseau hydrographique wallon en vue détaillée.</gco:CharacterString>
     </cit:description>
     <cit:function>
        <cit:CI_OnLineFunctionCode codeList="http://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#CI_OnLineFunctionCode"
                                   codeListValue="information"/>
     </cit:function>
  </cit:CI_OnlineResource>
</mrd:onLine>
```

* de la légende https://geoservices.wallonie.be/arcgis/rest/services/EAU/RHW/MapServer/legend
```xml
  <mdb:portrayalCatalogueInfo>
      <mpc:MD_PortrayalCatalogueReference>
         <mpc:portrayalCatalogueCitation>
            <cit:CI_Citation>
               <cit:title>
                  <gco:CharacterString>Légende des couches de données</gco:CharacterString>
               </cit:title>
               <cit:onlineResource>
                  <cit:CI_OnlineResource>
                     <cit:linkage>
                        <gco:CharacterString>https://geoservices.wallonie.be/arcgis/rest/services/EAU/RHW/MapServer/legend</gco:CharacterString>
                     </cit:linkage>
                     <cit:protocol>
                        <gco:CharacterString>WWW:LINK</gco:CharacterString>
                     </cit:protocol>
                     <cit:description>
                        <gco:CharacterString>Légende des couches de données</gco:CharacterString>
                     </cit:description>
                     <cit:function>
                        <cit:CI_OnLineFunctionCode codeList="http://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#CI_OnLineFunctionCode"
                                                   codeListValue="information.portrayal"/>
                     </cit:function>
                  </cit:CI_OnlineResource>
               </cit:onlineResource>
            </cit:CI_Citation>
         </mpc:portrayalCatalogueCitation>
      </mpc:MD_PortrayalCatalogueReference>
  </mdb:portrayalCatalogueInfo>
```

Pour spatineo cf. #674

**Comment by fxprunayre** [comment]
Cf. https://github.com/geonetwork/core-geonetwork/pull/6302

**Comment by fxprunayre** [comment]
@marceaulouis A vérifier si on ajoute aussi un lien du type https://geoportail.wallonie.be/walonmap/#ADU=https://geoservices.wallonie.be/arcgis/rest/services/EAU/RHW/MapServer ?

**Comment by vbombaerts** [comment]
Attention que le function code pour un service de visualisation est browsing et pas information.
Pour la légende, vu qu'elle est placée au bon endroit, on n'a plus besoin de cette extension information.portrayal du function code. Information suffit. (attention aux conséquences éventuelles sur le dispatching des ressources dans l'index).
Pour moi on peut ajouter le lien type #ADU.

**Comment by fxprunayre** [comment]
A déployer en test.

**Comment by davinciagf** [comment]
Déployé en test

**Comment by davinciagf** [comment]
Testé sur MW test mais petite coquille à corriger au niveau de l'url du wms (+ADU? pas présent pour toutes les mdt de service WMS): 
<gco:CharacterString>https://geoservices.wallonie.be/arcgisservices/EAU/LEGIS_PECHE/MapServer/WMSServer?request=GetCapabilities&amp;service=WMS</gco:CharacterString>

**Comment by marceaulouis** [comment]
Testé aussi ce matin, c'est alléchant :

1. Pour les fiches de service :
 - Spatineo : Est-ce que ce sera envisageable de gérer les accents ?
 
![image](https://user-images.githubusercontent.com/99397823/168990774-8b3067ad-5292-41ee-ada6-05afb948ed77.png)


- Serait-ce possible d'ajouter une autre complétion : pour les services il semble qu'on encode aussi l'opération et le connect point, ce sont les mêmes infos :

![image](https://user-images.githubusercontent.com/99397823/168992038-00e37c88-7cb2-4b7c-ab0b-41269f27647c.png)

2. Fiches série/donnée

- ADU : parfois ce sont des liens SHARE, je suppose que ce serait plus propre de mettre un lien de type ADU systématiquement

- Comme Vincent le remarquait, jusqu'à présent pour les légendes on n'encodait ni protocole ni fonction
![image](https://user-images.githubusercontent.com/99397823/168992723-8f6f1cc0-9565-46a7-a6f7-792c202c8d53.png)

**Comment by davinciagf** [comment]
Correction en cours pour le '/' et pour ne plus afficher la suggestion si la legend /WMS sont présents.

**Comment by vbombaerts** [comment]
ADU vs SHARE : 
ADU permet d'automatiser mais ne permet pas de personnaliser la carte renvoyée en lien. Donc ça convient pour une donnée qui couvre toute la Wallonie.
SHARE, c'est l'inverse : permet de zoomer à l'échelle la plus adaptée et centrer sur une zone intéressante pour présenter la donnée dans de meilleurs conditions, mais ce n'est pas automatisable.

Pour le moment on peut garder ADU. Si nécessaire on personnalisera le lien avec un share au cas par cas.

**Comment by fxprunayre** [comment]
A faire:
* pour les données, ajouter le lien de type ADU
* pour les services, lors de l'ajout du WMS, ajout du connect point

**Comment by fxprunayre** [comment]
A déployer pour ADU.

Pour connectPoint @marceaulouis , on ajoute quoi ? j'ai l'impression qu'il y a plusieurs cas
* WMS https://metawal.wallonie.be/geonetwork/srv/api/records/ef3d5d00-b02a-4b61-a999-ed0fb37d1a25/formatters/xml?output=xml
* Atom https://metawal.wallonie.be/geonetwork/srv/api/records/4fa0ae53-3173-411d-9c29-80a8b3120781/formatters/xml?output=xml

On peut ajouter une suggestion si WMS alors on propose d'ajouter connectpoint. Est-ce qu'on ajoute autre chose ?

**Comment by marceaulouis** [comment]
Le cas WMS sera bcp plus courant que Atom donc je me baserais sur ce cas

Je n'ai rien à ajouter

merci !

**Comment by davinciagf** [comment]
Déployer à tester

**Comment by marceaulouis** [comment]
ADU : super ! Peut-être juste adapter le texte descriptif de la suggestion pour inclure l'ajout de l'ADU ?

![image](https://user-images.githubusercontent.com/99397823/174034172-15f1dfac-c4ab-4c20-9871-aeced9513ff1.png)

**Comment by marceaulouis** [comment]
J'ai scindé la partie connectPoint : voir #752

**Comment by marceaulouis** [comment]
descriptif adapté : OK
