### ISSUE TITLE
Mapstore - modifications

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#743]
Demandes supplémentaires suite à [implémentation réelle dans le géoportail](https://geoportail.wallonie.be/mapstore.html) :

- [x] La pagination s'affiche actuellement en anglais (Prev / Next), est-il possible de l'avoir en français ?
- [x] Peut-on ajuster la marge entre les lignes de cartes ?

_Originally posted by @vbombaerts in https://github.com/SPW-DIG/metawal-core-geonetwork/issues/715#issuecomment-1136881293_

Code

```
<p>&nbsp;</p>
<link rel="stylesheet" href="https://metawal4.test.wallonie.be/geonetwork/catalog/lib/icho/styles.css"> 
<link rel="stylesheet" href="https://metawal4.test.wallonie.be/geonetwork/catalog/lib/icho/main.css"> 
<div style="margin: 2.5em">
<catalogue-results-card 
catalogueurl="https://metawal4.test.wallonie.be/geonetwork/srv" 
fields='{
"imageIndex": "overview", "imageJsonPath":"$[0].url", 
"titleIndex": "resourceTitleObject", "titleJsonPath":"$.default", "titleSize":"h4", 
"subTitleIndex": "ownerOrgForResource", "subTitleJsonPath":"", 
"textIndex": "resourceHookAbstractObject", "textJsonPath":"$.default",
"linkIndex": "mw-gp-thematicMap", "linkJsonPath":"$[0].url", "linkIcon":"map", "linkButtonColor":"#0676C5", "linkHook":"Découvrir",
"additionalInfoIndex":"cl_accessConstraints", "additionalInfoJsonPath":"$[0].key"
}' 
filter="+(resourceType:application) -(th_infraSIG.default:Reporting_INSPIRE) -(cl_status.key:obsolete)" 
fulltextfilter="resourceTitleObject.default,` resourceHookAbstractObject.default"
search_placeholder="Recherche libre"
filterfield_2="th_Themes_geoportail_wallon_hierarchy.default"
filterfield_2_placeholder="Thème"
filterfield="ownerOrgForResource"
filterfield_placeholder="Propriétaire" 
linkmdt="false"
imageheight="220" 
itemsperrow="4" size="12" marginx="2" margintoolsbottom="1" marginbottom="2" 
sorttype="asc" sortby="resourceTitleObject.default.keyword"
sortbylist='{"sortIndexRef":"resourceTitleObject.default.keyword", "sortName":"Titre"} | {"sortIndexRef":"popularity", "sortName":"Popularité"}'
> </catalogue-results-card></div>
<script src="https://metawal4.test.wallonie.be/geonetwork/catalog/lib/icho/runtime.esm.js"  type="module"></script><script src="https://metawal4.test.wallonie.be/geonetwork/catalog/lib/icho/polyfills.esm.js" type="module"></script><script src="https://metawal4.test.wallonie.be/geonetwork/catalog/lib/icho/main.esm.js" type="module"></script>
```

**Comment by vbombaerts** [comment]
Arnaud voit avec Samuel pour le choix de la pagination.

**Comment by davinciagf** [comment]
Après discussions avec Samuel, le type de pagination suivant a été choisi:

![image](https://user-images.githubusercontent.com/576292/173318609-f62e1d9e-44c1-44e9-96c9-df4b28f858fd.png)

**Comment by davinciagf** [comment]
Pour ajouter une marge, on peut utiliser le paramètre:
```
margincardbottom="2"
```

Attention cette marge se place sous les cards, cela a donc un implication sur la position de la pagination.

![image](https://user-images.githubusercontent.com/576292/173322567-7929edf7-8f6b-4a41-a7ad-d702dc64d5de.png)

**Comment by vbombaerts** [comment]
La pagination n'est pas centrée sur le bloc de cards.

![image](https://user-images.githubusercontent.com/6093597/174608323-cfd0e3f8-22b1-4be6-95c3-73448d9bc5cd.png)

**Comment by davinciagf** [comment]
Corrigé (mise à jour des fichiers sur app.titellus):
![image](https://user-images.githubusercontent.com/576292/174620712-c31ccad1-5423-48fc-882c-ba71692ba674.png)

**Comment by davinciagf** [comment]
Correctif inclus dans MW4 en test

**Comment by vbombaerts** [comment]
OK. Peux-tu ajouter les nouveaux paramètres dans la doc des webcomponents (tableau et cards) ? J'ai déjà fait une partie du travail pour la version précédente.

**Comment by davinciagf** [comment]
Doc mis à jour pour :
- mapstore:
  - margincardbottom 
- tableau
  - columnFormatter 
  - columnIconColor 
  - columnValue 
  - columnLabel
