### ISSUE TITLE
Référencement du contenu de la page Mapstore

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#751]
Dans l'ancienne version du catalogue du GP, les métadonnées sont stockées dans Jahia et peuvent être indexées par les moteurs de recherche. Lors du passage au webcomponent mapstore, ce n'est plus le cas.
Comment faire en sorte que le contenu des métadonnées soit quand même indexé pour les moteurs de recherche et dirige vers la page du Mapstore dans le géoportail ?

**Comment by fxprunayre** [comment]
Le jeu. 16 juin 2022, 15:36, Vincent Bombaerts ***@***.***> a
écrit :

**Comment by vbombaerts** [comment]
Pas de réponse.
