### ISSUE TITLE
Suggestion / Ajout connectPoint fiches de service

### ISSUE THREAD

**Issue by marceaulouis** [SPW-DIG/metawal-core-geonetwork#752]
Dans le même ordre d'idées que l'ajout du WMS, légende et spatineo #740 :

Pour les fiches de service (WMS et REST), copie de l'adresse du service en connectPoint + description selon le modèle  

https://metawal.wallonie.be/geonetwork/srv/api/records/ef3d5d00-b02a-4b61-a999-ed0fb37d1a25/formatters/xml?output=xml

**Comment by fxprunayre** [comment]
A déployer et tester.

**Comment by davinciagf** [comment]
A tester

**Comment by marceaulouis** [comment]
Je ne vois pas la suggestion en test

**Comment by marceaulouis** [comment]
Je ne vois pas la suggestion en test

**Comment by davinciagf** [comment]
Il est caché @fxprunayre a également du me le montrer ;-)
![image](https://user-images.githubusercontent.com/576292/175240230-dbdf8aee-890b-41e1-816b-0abc3a4c64c0.png)

**Comment by marceaulouis** [comment]
Merci !

Ok pour les WMS
Est-ce envisageable pour les services REST aussi ?

**Comment by fxprunayre** [comment]
Aujourd'hui j'aurai du mal à faire des trucs en plus.
On devrait peut être réfléchir à rendre plus visible les suggestions - dans ce cas là, la suggestion pourrait être placée sous l'URL du WMS et proposer les options d'ajout qui ne sont pas déjà faites ....

**Comment by marceaulouis** [comment]
Je m'en doutais, laissons ça pour la prochaine alors
En l'état ça fait ce qu'il me faut parfaitement, on a juste systématiquement une fiche de service REST à créer aussi

**Comment by davinciagf** [comment]
Texte de la suggestion un peu plus explicite en attendant d'éventuels modifs sur les suggestions
![image](https://user-images.githubusercontent.com/576292/175276441-e98214d8-996b-46e1-8778-6a9dd17d1904.png)

**Comment by fxprunayre** [comment]
Pour ESRI, 

![image](https://user-images.githubusercontent.com/1701393/195646726-e1c7745a-0a71-4585-9459-026197fd2d1c.png)


et hop

![image](https://user-images.githubusercontent.com/1701393/195646822-1eb49feb-6073-4ff6-90eb-cfc23b21e9f8.png)


A déployer et tester.

**Comment by marceaulouis** [comment]
Parfait !
Juste un petit soucis de trad dans le descriptif : "Exécuter cette ajouter l'adresse de connexion."

**Comment by fxprunayre** [comment]
> Juste un petit soucis de trad dans le descriptif : "Exécuter cette ajouter l'adresse de connexion."

Fixed.

**Comment by marceaulouis** [comment]
parfait ! Ca fonctionne et fera gagner pas mal de temps
