### ISSUE TITLE
Une fiche moissonnée n'apparait pas dans Kibana

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#753]
J'ai créé un moissonneur de geo.be pour récupérer la fiche d'application CadGIS viewer.
https://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/a1a7e400-71eb-11eb-8a55-3448ed25ad7c

Elle apparait dans le mapstore, mais certains champs ne sont pas complétés. https://geoportail.test.wallonie.be/cms/render/default/fr/sites/geoportail/home/produire-et-publier/mw---test-agf-web-component/test-webcomponents-vincent-Mapstore.html

Quand j'essaie de voir ce qui coince dans Kibana, elle n'apparait pas.
https://metawal.wallonie.be/geonetwork/dashboards/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15y,to:now))&_a=(columns:!(groupPublished,resourceTitleObject.default,_id),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:gn-records,key:groupPublished,negate:!f,params:(query:mapstore),type:phrase),query:(match_phrase:(groupPublished:mapstore)))),index:gn-records,interval:auto,query:(language:kuery,query:''),sort:!(!(dateStamp,desc)))

Une idée ?

**Comment by fxprunayre** [comment]
GET gn-records/_doc/a1a7e400-71eb-11eb-8a55-3448ed25ad7c
Parcequ'elle n'a pas de champ dateStamp donc le filtre sur la date l'exclue.
