### ISSUE TITLE
Bug - tri par nom de ressource

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#755]
Le tri par nom de ressource (Titre) dans l'interface de recherche et dans celle d'édition est par ordre alphabétique inverse.
Dans la modification par batch c'est OK.

**Comment by davinciagf** [comment]
@vbombaerts , tu peux configurer le mécanisme au niveau de la config (admin/settings/user interface)
![image](https://user-images.githubusercontent.com/576292/174626532-6044449e-2ba1-4503-9c03-294b1978a52a.png) (copie d'écran de MW prod)
