### ISSUE TITLE
Ne pas mettre les services associés et similaire en colonne, mais en ligne

### ISSUE THREAD

**Issue by mawibrin** [SPW-DIG/metawal-core-geonetwork#76]
On a l'impression qu'il y a deux URL car cela est écrit en deux lignes
![services_associes](https://f.cloud.github.com/assets/6093453/1662958/0523205e-5c09-11e3-9441-a773347a1924.jpg)

Il me semble plus logique de faire une ligne par entrée

**Comment by fxprunayre** [comment]
L'affichage par colonne est volontaire car potentiellement il peut y en avoir bcp eg. http://sdi.eea.europa.eu/catalogue/srv/eng/search?uuid=650c3735-28c7-43bb-b521-3952ce4d6246

**Comment by fxprunayre** [comment]
Ajout d'un réf dans https://github.com/spacebelGIS/metawal-core-geonetwork/wiki/Ergonomie-et-design-des-interfaces-Metawal
