### ISSUE TITLE
Fiche de service - Encodage du lien vers la donnée - norme ISO 19115

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#760]
Je suis en train de travailler sur la relation entre un service et les données qu'il sert dans une fiche de service.

Jusqu'à présent, on utilise la balise `operatesOn` pour encoder ce lien, en indiquant le lien vers la fiche de donnée correspondante
`<srv:operatesOn uuidref="518fec3f-760c-4eab-8d6b-c38d1224c914"                          xlink:href="https://metawal.wallonie.be/geonetwork/srv/api/records/518fec3f-760c-4eab-8d6b-c38d1224c914"/>`

Or je vois dans la norme ISO 19115 que `operatesOn `doit renseigner un élément de type `MD_DataIdentification`
La substitution opérée pour l'encodage est-elle valide ?

Si non, la norme ISO 19115 propose un autre élément permettant de renseigner le jeu de données servi : `operatedDataset` (jeu de données utilisé), de type `CI_Citation`. Ne serait-il pas plus correct d'utiliser cet élément là ?

**Comment by fxprunayre** [comment]
![image](https://user-images.githubusercontent.com/1701393/178931507-279a80e4-6460-4722-aa65-8d50cf67855b.png)

![image](https://user-images.githubusercontent.com/1701393/178932316-2d44cc1b-7579-404b-8a6a-d45cbcc45d10.png)
![image](https://user-images.githubusercontent.com/1701393/178932365-6199fab9-71c7-4cde-8c18-9a0271553881.png)


Pas certain de comprendre la différence. En tout cas dans notre cas, on veut établir une association vers une autre fiche. Donc ce serait plutôt operatesOn.
