### ISSUE TITLE
Erreur dans le CSW INSPIRE

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#762]
Le paramètre {$endPointValue} du [GetCapabilities du CSW INSPIRE](https://metawal.wallonie.be/geonetwork/inspire/fre/csw?SERVICE=CSW&REQUEST=GetCapabilities) n'est pas remplacé par sa valeur.

```
<inspire_com:ResourceLocator>
<inspire_com:URL>{$endPointValue}?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetCapabilities</inspire_com:URL>
<inspire_com:MediaType>application/xml</inspire_com:MediaType>
</inspire_com:ResourceLocator>
```

**Comment by davinciagf** [comment]
Une autre coquille est présente également dans le fichier ('$https'):
```
<ows:Operation name="GetRecordById">
<ows:DCP>
<ows:HTTP>
<ows:Get xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="$https://metawal.wallonie.be/geonetwork/inspire/fre/csw"/>
<ows:Post xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://metawal.wallonie.be/geonetwork/inspire/fre/csw"/>
```
A corriger dans GN : https://github.com/geonetwork/core-geonetwork/blob/156a89a9fb75e2feebb3289106600712529f7d2f/web/src/main/webapp/xml/csw/record-to-csw-capabilities.xsl#L291

**Comment by davinciagf** [comment]
- [x]  Alginement sur GN (après merge de la PR)
- [ ] Déploiment sur test

**Comment by vbombaerts** [comment]
Attention ! l'info du <inspire_com:URL> vient directement de la fiche de MD du service. 
En test, cette fiche est mise à jour par le moissonnage de la prod ==> on retrouve là les infos de prod ! ==> nécessité de passer par une fiche spécifique à la test. https://metawal4.test.wallonie.be/geonetwork/inspire/fre/catalog.search#/metadata/fb2a3dda-a4c9-4739-9fbf-143f584a0453
