### ISSUE TITLE
Problème d'affichage d'imagette sur le geoportail

### ISSUE THREAD

**Issue by marceaulouis** [SPW-DIG/metawal-core-geonetwork#765]
Une imagette ne s'affiche pas sur le géoportail
https://geoportail.wallonie.be/catalogue/2414e736-72e2-4b5a-967d-da410ef4526c.html

Renseignements pris, ce problème viendrait de notre côté, mais je ne vois rien de particulier dans l'encodage. Si quelqu'un a une idée

Voici la réponse reçue côté jahia :

Bonjour Samuel,
Je te contact au sujet de ton incident sur geoportail avec la petite imagette qui ne s'affiche pas.
Si j'ai bien compris c'est une fiche qui est synchronisé pour s'afficher dans Jahia mais cette fiche n'est pas éditable depuis jahia.
Après une rapide analyse, le problème vient de la complétion de cette fiche.
Voici ce que je trouve dans le code :

L'image est appelé avec l'attribut "logo" qui n'existe pas. Alors que si je remplace par "thumbnail" cela fonctionne normalement : 

Quand je regarde d'autres fiches elles sont toutes configurées de la sorte avec le "thumbnail" et pas le logo dans l'url.

**Comment by vbombaerts** [comment]
Le logo est encodé dans

`//gmd:identificationInfo[1]/*/gmd:citation/gmd:CI_Citation/gmd:otherCitationDetails/gmx:FileName/@src`

J'ai supprimé la section pour la fiche IPPC, pour voir si le GP basculait sur le thumbnail.
Il n'a pas basculé.
Donc j'ai complété l'encodage de la fiche pour indiquer l'adresse de l'imagette dans le logo et c'est OK maintenant. (merci à l'équipe du GP de nous avoir mis sur la piste...)

```
               </cit:identifier>
               <cit:otherCitationDetails>
                  <gcx:FileName src="https://metawal.wallonie.be/geonetwork/srv/api/records/2414e736-72e2-4b5a-967d-da410ef4526c/attachments/2022-09-14%2009_44_07-IED_IPPC.png%20(600%C3%97600).png"/>
               </cit:otherCitationDetails>
            </cit:CI_Citation>
```

Par contre, c'est plutôt bizarre que le GP prenne le logo pour cette fiche et pas pour les autres fiches. Il me semble que la règle était : afficher le logo quand il y en a un et l'imagette sinon. (mais elle n'est pas bien implémentée puisque quand j'ai supprimé le logo, il n'a pas basculé sur l'imagette).

Dans le nouvelle version du mapping, on a laissé tombé le logo. On n'utilise que l'imagette.
