### ISSUE TITLE
Problème d'accès aux fiches de MD

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#772]
Les adresses de type https://metawal.wallonie.be/geonetwork/srv/api/records/18da353f-82c6-47a1-be7a-d07e9220932e ne sont plus accessibles.

**Comment by fxprunayre** [comment]
En effet, y'a des erreurs

```
2022-10-04 05:23:48,823 ERROR [ro.isdc.wro.http.WroFilter] - Exception occured
ro.isdc.wro.WroRuntimeException: Cannot build valid CacheKey from request: /geonetwork/static/api/records/ff71a317-fc05-4d0d-b30b-58a1740eb314
	at ro.isdc.wro.manager.ResourceBundleProcessor.getSafeCacheKey(ResourceBundleProcessor.java:111)
	at ro.isdc.wro.manager.ResourceBundleProcessor.serveProcessedBundle(ResourceBundleProcessor.java:61)
	at ro.isdc.wro.manager.WroManager.process(WroManager.java:159)
	at ro.isdc.wro.http.WroFilter.processRequest(WroFilter.java:340)
```

En test également
https://metawal4.test.wallonie.be/geonetwork/srv/api/records/18da353f-82c6-47a1-be7a-d07e9220932e

En local, c'est bon de mon côté. @davinciagf tu reproduis en local ?

C'est bizarre, car https://metawal.wallonie.be/geonetwork/srv/api/records/18da353f-82c6-47a1-be7a-d07e9220932e?node=srv fonctionne. Il y a un pb de détection du portail mais sans reproduire en local, ça va être difficile de trouver pourquoi.

**Comment by davinciagf** [comment]
De mon côté je ne reproduis pas non plus en local

**Comment by fxprunayre** [comment]
C'est bizarre car https://metawal.wallonie.be/geonetwork/srv/api/records/18da353f-82c6-47a1-be7a-d07e9220932e/formatters/xml fonctionne

**Comment by fxprunayre** [comment]
Sur metawal4, tu pourrais tester
https://metawal4.test.wallonie.be:8080/geonetwork/srv/api/records/18da353f-82c6-47a1-be7a-d07e9220932e
pour vois si sans passer par le proxy, ca fonctionne (accès direct sur tomcat).

**Comment by davinciagf** [comment]
Supprimer le fichier :
web/src/main/webapp/WEB-INF/data/data/resources/htmlcache/formatter-cache/info-store.mv.db 
et relancer le tomcat.
Fait en test.
