### ISSUE TITLE
Documentation des webcomposants

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#775]
Création d'une documentation mieux structurée et hébergée sur le github

**Comment by davinciagf** [comment]
Une première version a été réalisée. Elle s'appuie sur github pages afin de publier la documentation via un site statique. 
![image](https://user-images.githubusercontent.com/576292/198234476-4f011686-b692-48c4-bc5d-6f2df547e808.png)

https://davinciagf.github.io/icho/

Intégration d'un dossier 'docs' au niveau d'[ICHO](https://github.com/titellus/icho) contenant des fichiers de type markdown permettant de détailler la configuration des composants web. A chaque commit au niveau ce répertoire le site est mis à jour.

**Comment by vbombaerts** [comment]
Tu peux transférer sur l'espace SPW-DIG

**Comment by vbombaerts** [comment]
Code : https://github.com/SPW-DIG/icho/tree/main/docs/content.fr
Rendu : https://spw-dig.github.io/icho/
