### ISSUE TITLE
Résultats de recherche : filtres

### ISSUE THREAD

**Issue by metawal** [SPW-DIG/metawal-core-geonetwork#78]
- Renommer "Thèmes du géoportail wallon" en "Thèmes du Géoportail de la Wallonie";
- Niveaux d'échelle : ajouter "1:" (par exemple, remplacer "10000" par "1:10000");
- Années : de quelle année s'agit-il ?
- Ajouter un filtre "Propriétaire de la ressource"

**Comment by fxprunayre** [comment]
> Années : de quelle année s'agit-il ?

L'année des dates de la ressource ou des étendues temporelles

> Ajouter un filtre "Propriétaire de la ressource"

Disponible cf. Contact pour la ressource

> Renommer "Thèmes du géoportail wallon" en "Thèmes du Géoportail de la Wallonie";

@davinciagf TODO

**Comment by fxprunayre** [comment]
> @davinciagf TODO

@davinciagf  done.

**Comment by davinciagf** [comment]
Niveaux d'échelle voir  #127

**Comment by vbombaerts** [comment]
> Ajouter un filtre "Propriétaire de la ressource"

Qu'est-ce qui est souhaité ??
- Limiter les contacts uniquement au propriétaire
- Ajouter d'autres facettes avec les contacts pertinents dans le cadre d'une recherche : propriétaire , distributeur, gestionnaire ?

==> Il faut une réflexion sur les critères réellement utilisés dans les recherches.

> Années : de quelle année s'agit-il ?

Même remarque : sur quoi souhaite-t-on chercher ? l'étendue temporelle ou la dernière mise à jour du jeu de donnée ?

==> problème remonté dans le wiki au niveau de l'ergonomie des pages
