### ISSUE TITLE
Contenu de mw-gp-keywords

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#781]
mw-gp-keywords contient les thèmes du GP.
Il faut les exclure.

**Comment by davinciagf** [comment]
Avant :

![image](https://user-images.githubusercontent.com/576292/200839117-fd3374f9-a556-4dc6-9222-60ffb538ee10.png)

Après suppression des thèmes du GP au niveau de mw-gp-keywords:

![image](https://user-images.githubusercontent.com/576292/200839367-c7e645e0-43ed-441e-86ed-344a6efcfef8.png)

**Comment by davinciagf** [comment]
A tester - besoin de réindexer (en cours)
