### ISSUE TITLE
Décalage des dates entre Kibana et l'API

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#783]
Il y a un jour de décalage entre la date indiquée dans Kibana ou dans la fiche Metawal et la date retournée par l'API.

https://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/5adcf746-bc5a-4115-8997-b8f86001431e

- Metawal (idem Kibana)

Création 07-12-2020
 Publication 11-12-2020
 Révision 22-03-2022

- API

"creationDateForResource": [
            "2020-12-06T23:00:00.000Z"
"publicationDateForResource": [
            "2020-12-10T23:00:00.000Z"
"revisionDateForResource": [
            "2022-03-21T23:00:00.000Z"

**Comment by fxprunayre** [comment]
Dans l'index toute les dates sont en UTC, donc ensuite à l'affichage on peut ajuster - dans Kibana et dans GN dans l'admin on peut définir comment est fait l'ajustement (eg. sur la base de la timezone du navigateur, une timezone forcée Europe/Brussels pour Metawal).

**Comment by vbombaerts** [comment]
OK. donc l'ajustement devrait se faire côté géoportail ?
Et même chose pour les webcomposants ?

**Comment by fxprunayre** [comment]
Oui.
