### ISSUE TITLE
Mapping MW-GP - Infos des services liés

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#784]
Suite à discussion avec l'équipe géoportail, on souhaite récupérer plus d'informations au niveau des services liés à une donnée.
L'idée est d'abandonner [le catalogue des services dans sa version actuelle](https://geoportail.wallonie.be/catalogue-donnees-et-services?&search-tab=2) et basculer vers l'intégration de certaines informations des services dans la fiche de donnée, par exemple dans un onglet API/services.
(Un catalogue spécifique au service pourrait subsister, par exemple sous forme de tableau créé avec les webcomponents)

Les infos qu'on souhaite afficher au niveau de l'onglet API/services d'une donnée sont :
- Nom du service
- Descriptif
- Adresse de connexion
- Conditions d'accès et d'utilisation
- Rapport de qualité / disponibilité
+ éventuellement la liste des donnée servies

Une approche serait d'ajouter les infos manquantes à celles déjà fournies par l'élément  related.service._source
Est-ce une bonne approche ?

**Comment by fxprunayre** [comment]
> Est-ce une bonne approche ?
Je dirai plutôt oui.

Actuellement on a 

![image](https://user-images.githubusercontent.com/1701393/203622663-1b910706-fce2-472e-985f-66e384309355.png)

Donc il ne manque pas grand chose:

- [x] Nom du service
- [x] Descriptif
- [x] Adresse de connexion
- [x] Conditions d'accès et d'utilisation
- [x] Rapport de qualité / disponibilité - dans les links
- [x] éventuellement la liste des donnée servies (mais seulement des UUIDs)


Ce sont des infos en dur dans le Java, qu'il faudrait peut être au moins mettre en config externe (cf. FIELDLIST_RELATED)

**Comment by davinciagf** [comment]
Ajout des conditions:
![image](https://user-images.githubusercontent.com/576292/206136176-cc28c2df-595b-4212-aadf-1a1e1c9479ed.png)

**Comment by vbombaerts** [comment]
Un petit souci au niveau de l'indexation multilingue. La langue n'est pas spécifiée pour le rapport de qualité (`lang` au lieu de `langfre`)


![2022-12-07 15_04_42-Clipboard](https://user-images.githubusercontent.com/6093597/206199950-5b819c8a-8813-4f8e-a269-a691596c76d0.png)

**Comment by vbombaerts** [comment]
Au niveau de la liste des données servies, je trouve qu'il y a confusion du fait de mettre dans la même liste les id des fiches avec les adresses d'accès aux fiches. Il y a une raison ? Ce ne serait pas plus propre de faire un objet par fiche avec [id,adresse] ?

![2022-12-07 15_29_26-Clipboard](https://user-images.githubusercontent.com/6093597/206205719-a2bac891-9af3-43ab-8929-69dacbe85dcd.png)

**Comment by fxprunayre** [comment]
> Un petit souci au niveau de l'indexation multilingue. La langue n'est pas spécifiée pour le rapport de qualité (lang au lieu de langfre)

A déployer. En fait y'en avait plusieurs des soucis - surtout dans la mise à jour de liens dans l'éditeur pour les documents qui n'était pas dans la section distribution pour les fiches multilingues (eg. DQ report, Legend). Ca vaut le coup de refaire quelques tests sur ces fonctions.

**Comment by vbombaerts** [comment]
OK pour la partie related>services.
Pas encore testé sur les autres éléments.
