### ISSUE TITLE
Mapping MW-GP - valeur de l'élément mw-gp-wom

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#785]
Modification de l'info encodée dans l'élément mw-gp-wom.

Cet élément sert à stocker la valeur de l'adresse Walonmap avec une prévisualisation de la donnée. Dans le géoportail, c'est donc le bouton "Dans Walonmap" de la section Consulter la donnée dans une application de l'onglet Accès.

L'adresse WalOnMap peut être construite de 2 façons :
- soit avec un share WalonMap
- soit avec un lien ADU et l'adresse du service REST

Pour le moment, mw-gp-wom stocke l'adresse du service REST et un lien ADU est créé par le géoportail. On veut que le géoportail reçoive directement la bonne adresse.

Pour définir un lien wom, on prend la convention suivantes :
- Protocole : WWW:LINK
- function : browsing
- application profile : walonmap (non sensible à la casse, donc pourrait aussi être WalOnMap, WALONMAP, Walonmap, etc)

TODO :
- [x] Adapter le process qui ajoute l'adresse ADU à partir du rest pour ajouter l'application profile
- [x] Adapter l'index pour stocker dans mw-gp-wom l'adresse WalOnMap
- [ ] Corriger les fiches existantes (ajouter l'application profile, vérifier le protocole et la fonction) - voir [cette requête](https://metawal.wallonie.be/geonetwork/srv/eng/catalog.search#/search?isTemplate=n&resourceTemporalDateRange=%7B%22range%22:%7B%22resourceTemporalDateRange%22:%7B%22gte%22:null,%22lte%22:null,%22relation%22:%22intersects%22%7D%7D%7D&sortBy=resourceTitleObject.default.keyword&sortOrder=asc&from=1&to=30&languageStrategy=searchInThatLanguage:fre&any=q(%2BlinkUrl:%2Fhttps:%5C%2F%5C%2Fgeoportail.wallonie.be%5C%2Fwalonmap.*%2F)) --> pour la correction, voir d'abord si elle a un impact sur l'affichage dans la version actuelle du géoportail.  Si non, on peut tout corriger. Si oui, créer qques fiches en test qui implémentent la correction et attendre le basculement vers le nouveau GP pour la correction globale.
- [ ] Communiquer l'adaptation du mapping à l'équipe GP

Remarque : Cet élément ne doit pas être confondu avec la fonction "ajouter à ma sélection Walonmap" qui ajoute la donnée dans le panier Walonmap. Celui-ci est réglé par l'élément infrasig_walonmap. Les deux sont indépendants.

**Comment by davinciagf** [comment]
Test de la définition de l'indice wom via une copie : 
https://metawal4.test.wallonie.be/geonetwork/srv/eng/catalog.search#/metadata/1f5268a9-d26f-4a0c-bf66-03d8df4c5ae7

![image](https://user-images.githubusercontent.com/576292/206456108-a64321cb-3caa-4c7f-8393-550929ff8fec.png)

**Comment by davinciagf** [comment]
Impact template : https://metawal.wallonie.be/geonetwork/srv/eng/catalog.search#/metadata/1c0285f0-2ebc-4b91-889b-e4f96bbeeb51

**Comment by vbombaerts** [comment]
Il y a une confusion entre mw-gp-wom et mw-gp-staticMap. Les deux entrées donnent la même chose.
https://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/69fbfdd4-0fd4-4e87-97d3-5662f397d9c0

**Définition**
```
<link protocol="WWW:LINK" function="browsing" appProfile="1" field="mw-gp-staticMap"></link>
<link protocol="WWW:LINK" function="browsing" appProfile="1" appProfileName="walonmap" field="mw-gp-wom"></link>
```


**Résultat**
```
         "mw-gp-staticMap": [
            {
              "protocol": "WWW:LINK",
              "urlObject": {
                "default": "https://geoportail.wallonie.be/walonmap#SHARE=F02AE94A09144CCFE053D5AFA49DCF46",
                "langfre": "https://geoportail.wallonie.be/walonmap#SHARE=F02AE94A09144CCFE053D5AFA49DCF46"
              },
              "nameObject": {
                "default": "WalonMap Test inondations",
                "langfre": "WalonMap Test inondations"
              },
              "descriptionObject": {
                "default": "WalONMap - test inondations decriptif",
                "langfre": "WalONMap - test inondations decriptif"
              },
              "function": "browsing",
              "applicationProfile": "Walonmap"
            },
            {
              "protocol": "WWW:LINK",
              "urlObject": {
                "default": "http://connaitrelawallonie.wallonie.be/sites/wallonie/files/styles/medium_width/public/maps/carte_wallonie_communes_completees_v2.png?itok=Yu_Pucq8",
                "langfre": "http://connaitrelawallonie.wallonie.be/sites/wallonie/files/styles/medium_width/public/maps/carte_wallonie_communes_completees_v2.png?itok=Yu_Pucq8"
              },
              "nameObject": {
                "default": "Carte connaitre la Wallonie",
                "langfre": "Carte connaitre la Wallonie"
              },
              "descriptionObject": {
                "default": "Carte connaitre la Wallonie - description",
                "langfre": "Carte connaitre la Wallonie - description"
              },
              "function": "browsing",
              "applicationProfile": "png"
            }
          ],
          "mw-gp-wom": [
            {
              "protocol": "WWW:LINK",
              "urlObject": {
                "default": "https://geoportail.wallonie.be/walonmap#SHARE=F02AE94A09144CCFE053D5AFA49DCF46",
                "langfre": "https://geoportail.wallonie.be/walonmap#SHARE=F02AE94A09144CCFE053D5AFA49DCF46"
              },
              "nameObject": {
                "default": "WalonMap Test inondations",
                "langfre": "WalonMap Test inondations"
              },
              "descriptionObject": {
                "default": "WalONMap - test inondations decriptif",
                "langfre": "WalONMap - test inondations decriptif"
              },
              "function": "browsing",
              "applicationProfile": "Walonmap"
            },
            {
              "protocol": "WWW:LINK",
              "urlObject": {
                "default": "http://connaitrelawallonie.wallonie.be/sites/wallonie/files/styles/medium_width/public/maps/carte_wallonie_communes_completees_v2.png?itok=Yu_Pucq8",
                "langfre": "http://connaitrelawallonie.wallonie.be/sites/wallonie/files/styles/medium_width/public/maps/carte_wallonie_communes_completees_v2.png?itok=Yu_Pucq8"
              },
              "nameObject": {
                "default": "Carte connaitre la Wallonie",
                "langfre": "Carte connaitre la Wallonie"
              },
              "descriptionObject": {
                "default": "Carte connaitre la Wallonie - description",
                "langfre": "Carte connaitre la Wallonie - description"
              },
              "function": "browsing",
              "applicationProfile": "png"
```

**Comment by vbombaerts** [comment]
@marceaulouis Faut-il créer une nouvelle entrée dans la box pour l'ajout des ressources en ligne ?

**Comment by marceaulouis** [comment]
> @marceaulouis Faut-il créer une nouvelle entrée dans la box pour l'ajout des ressources en ligne ?

Je pense qu'adapter la suggestion + mettre à jour les modèles suffiront

**Comment by davinciagf** [comment]
Correctif déployé
![image](https://user-images.githubusercontent.com/576292/209295840-ea5e94ca-7aa0-4bc2-b44d-c92e0fa39574.png)

**Comment by vbombaerts** [comment]
> Corriger les fiches existantes (ajouter l'application profile, vérifier le protocole et la fonction) - voir [cette requête](https://metawal.wallonie.be/geonetwork/srv/eng/catalog.search#/search?isTemplate=n&resourceTemporalDateRange=%7B%22range%22:%7B%22resourceTemporalDateRange%22:%7B%22gte%22:null,%22lte%22:null,%22relation%22:%22intersects%22%7D%7D%7D&sortBy=resourceTitleObject.default.keyword&sortOrder=asc&from=1&to=30&languageStrategy=searchInThatLanguage:fre&any=q(%2BlinkUrl:%2Fhttps:%5C%2F%5C%2Fgeoportail.wallonie.be%5C%2Fwalonmap.*%2F)) --> pour la correction, voir d'abord si elle a un impact sur l'affichage dans la version actuelle du géoportail. Si non, on peut tout corriger. Si oui, créer qques fiches en test qui implémentent la correction et attendre le basculement vers le nouveau GP pour la correction globale.

La correction supprime le lien vers WalOnMap dans le géoportail actuel. Donc il faudra corriger au moment du basculement.
Pour la correction, il faut modifier la fonction Information en Consultation et ajouter WalOnMap dans le profil d'application.

**Comment by vbombaerts** [comment]
Remplacement de la fonction information par consultation :

- opération : remplacer
- XPath `/mdb:MD_Metadata/mdb:distributionInfo/mrd:MD_Distribution/mrd:transferOptions/mrd:MD_DigitalTransferOptions/mrd:onLine[cit:CI_OnlineResource/cit:linkage/gco:CharacterString[contains(.,'https://geoportail.wallonie.be/walonmap')]]/cit:CI_OnlineResource/cit:function`
- XML snippet  `<cit:CI_OnLineFunctionCode xmlns:cit="http://standards.iso.org/iso/19115/-3/cit/2.0" codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_OnLineFunctionCode" codeListValue="browsing"/>`

**Comment by vbombaerts** [comment]
Ajout de l'application profile :
- opération : ajouter
- Xpath : `/mdb:MD_Metadata/mdb:distributionInfo/mrd:MD_Distribution/mrd:transferOptions/mrd:MD_DigitalTransferOptions/mrd:onLine[cit:CI_OnlineResource/cit:linkage/gco:CharacterString[contains(.,'https://geoportail.wallonie.be/walonmap')]]/cit:CI_OnlineResource`
- XML snippet : `<cit:applicationProfile xmlns:cit="http://standards.iso.org/iso/19115/-3/cit/2.0" xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0"><gco:CharacterString>WalOnMap</gco:CharacterString></cit:applicationProfile>`

**Comment by vbombaerts** [comment]
J'ai modifié les fiches en test par un postprocessing sur le moissonnage.

```
[
  {
    "xpath": "/mdb:MD_Metadata/mdb:distributionInfo/mrd:MD_Distribution/mrd:transferOptions/mrd:MD_DigitalTransferOptions/mrd:onLine[cit:CI_OnlineResource/cit:linkage/gco:CharacterString[contains(.,'https://geoportail.wallonie.be/walonmap')]]/cit:CI_OnlineResource/cit:function",
    "value": "<gn_replace><cit:CI_OnLineFunctionCode xmlns:cit=\"http://standards.iso.org/iso/19115/-3/cit/2.0\" codeList=\"http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_OnLineFunctionCode\" codeListValue=\"browsing\"/></gn_replace>"
  },
  {
    "xpath": "/mdb:MD_Metadata/mdb:distributionInfo/mrd:MD_Distribution/mrd:transferOptions/mrd:MD_DigitalTransferOptions/mrd:onLine[cit:CI_OnlineResource/cit:linkage/gco:CharacterString[contains(.,'https://geoportail.wallonie.be/walonmap')]]/cit:CI_OnlineResource",
    "value": "<gn_add><cit:applicationProfile xmlns:cit=\"http://standards.iso.org/iso/19115/-3/cit/2.0\" xmlns:gco=\"http://standards.iso.org/iso/19115/-3/gco/1.0\"><gco:CharacterString>WalOnMap</gco:CharacterString></cit:applicationProfile></gn_add>"
  }
]
```

Ca se passe bien pour les fiches qui ont une adresse WalOnMap. Par contre, pour celles qui n'en ont pas, le deuxième process ajoute quand même un application profile. Une idée ?

Ex : https://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/2998bccd-dae4-49fb-b6a5-867e6c37680f

```
<mrd:onLine>
<cit:applicationProfile>
<gco:CharacterString>WalOnMap</gco:CharacterString>
</cit:applicationProfile>
</mrd:onLine>
```

**Comment by fxprunayre** [comment]
A tester avec une condition:

```json

{
"condition": "count(./mdb:distributionInfo/mrd:MD_Distribution/mrd:transferOptions/mrd:MD_DigitalTransferOptions/mrd:onLine[cit:CI_OnlineResource/cit:linkage/gco:CharacterString[contains(.,'https://geoportail.wallonie.be/walonmap')]]) > 0",
    "xpath": "/mdb:MD_Metadata/mdb:distributionInfo/mrd:MD_Distribution/mrd:transferOptions/mrd:MD_DigitalTransferOptions/mrd:onLine[cit:CI_OnlineResource/cit:linkage/gco:CharacterString[contains(.,'https://geoportail.wallonie.be/walonmap')]]/cit:CI_OnlineResource/cit:function",
    "value": "<gn_replace><cit:CI_OnLineFunctionCode xmlns:cit=\"http://standards.iso.org/iso/19115/-3/cit/2.0\" codeList=\"http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_OnLineFunctionCode\" codeListValue=\"browsing\"/></gn_replace>"
  },

```


cf. https://github.com/geonetwork/core-geonetwork/pull/4857

**Comment by vbombaerts** [comment]
Super !
