### ISSUE TITLE
Syntaxe query pour facettes

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#787]
J'ai un peu de mal à saisir les subtilités syntaxiques dans la rédaction des queries pour les facettes.

Je veux créer un facette sur la présence d'un view service INSPIRE. Donc je cherche si linkUrl commence par "https://geoservices.wallonie.be/INSPIRE/WMS"

Dans la barre de recherche Metawal, si je tape 
`q(+linkUrl:"https://geoservices.wallonie.be/INSPIRE/WMS*")` --> ça ne marche pas
`q(+linkUrl:https://geoservices.wallonie.be/INSPIRE/WMS*)` --> pas mieux

Si j'essaie d'échapper les caractères spéciaux
`q(+linkUrl:https\:\/\/geoservices.wallonie.be\/INSPIRE\/WMS\*)` --> toujours rien

Finalement si je regarde la requête que François a envoyée hier, j'essaie
`q(+linkUrl:/https:\/\/geoservices.wallonie.be\/INSPIRE\/WMS.*/)` --> ça donne un résultat, mais je ne comprends pas comment on arrive à ça

Enfin, si j'essaie d'en faire une facette, elle ne fonctionne pas.
```
        "diffusionMode": {
          "filters": {
            "filters": {
              "INSPIRE view service": {
                "query_string": {
                  "query": "+linkUrl:/https:\/\/geoservices.wallonie.be\/INSPIRE\/WMS.*/"
                }
              },
              "INSPIRE download service": {
                "query_string": {
                  "query": "+linkUrl:/https:\/\/geoservices.wallonie.be\/inspire\/atom.*/"
                }
              }
            }
          }
        },
```
Est-ce qu'on peut m'expliquer comment je dois faire svp ?

**Comment by fxprunayre** [comment]
Yes, 
donc:
* `+field:"blahblah"` = MUST (`+`) field exact match (`"text"`) `blahblah`
* `+field:/blah.*/` = MUST (`+`) field match regexp (`/regexp/`) blah et n'importe quoi (`.*`) - donc commence par
* `/https:\/\/geo` donc `\/` pour `/` parcequ'on est dans une regexp - on doit échapper le caractère `/`
* dans la config on est en JSON, il nous faut alors échapper le caractère `\` qui est utilisé pour lui même échapper les retours à la ligne `\n` par exemple. Donc:

```json
"INSPIRE view service": {
                      "query_string": {
                        "query": "+linkUrl:/https:\\/\\/geoservices.wallonie.be\\/INSPIRE\\/WMS.*/"
                      }
                    },
 ```

![image](https://user-images.githubusercontent.com/1701393/204753412-4ede74dd-d681-450c-a03d-cf47b38f41b0.png)


Un bon site pour tester et comprendre (un peu) les regexp https://regex101.com/r/DWbm8e/1

**Comment by vbombaerts** [comment]
Merci pour l'explication et le coup de pouce pour la requête !
