### ISSUE TITLE
ES - Discover - le tri par ordre croissant ou décroissant ne fonctionne pas

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#789]
Le seul champ sur lequel ça fonctionne c'est l dateStamp, mais impossible de trier par ordre alphabétique/croissant les autres champs.

**Comment by fxprunayre** [comment]
Ok, dans Kibana donc.

Deux choses:
* On ne peut que trier sur des champs non analysés (idem pour faire des aggrégations). Donc on ne peut pas trier sur le titre. Il faudrait pouvoir choisir resourceTitle.object.keyword (resourceTitle.object est un champ texte avec analyse)

* Ensuite KB empile les tris en partant de la gauche on dirait. Donc il faut d'abort cliquer sur le tri du champ time pour ne plus trier par time et ensuite les tris sur les autres colonnes vont s'appliquer de gauche à droite je pense

eg. tri par documentStandard et groupOwner

![image](https://user-images.githubusercontent.com/1701393/204749870-0ce044f5-a466-4272-aaf1-d602974723fc.png)
