### ISSUE TITLE
Résultats de recherche : image manquante

### ISSUE THREAD

**Issue by metawal** [SPW-DIG/metawal-core-geonetwork#79]
Il y a un lien cassé vers une image. Voir screenshot :

![screenshot2](https://f.cloud.github.com/assets/6093485/1663054/8429bf7e-5c0a-11e3-99a5-47f760e1d3a4.jpg)

**Comment by fxprunayre** [comment]
Doublon. Corrigé par config du système > logo du catalogue.

**Comment by vbombaerts** [comment]
Juste le WMS de la carte géologique qui ne passe pas. Bizarre.

**Comment by fxprunayre** [comment]
> Juste le WMS de la carte géologique qui ne passe pas. Bizarre.

C'est en lien avec l'icône du catalogue ?
