### ISSUE TITLE
Maping MW-GP : Format des dates - harmonisation possible ?

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#793]
J'ai reçu cette demande du prestataire côté GP :

> Serait il possible d'avoir toutes les dates sous le format
> `yyyy-MM-dd'T'HH:mm:ss.SSS'Z'`
> car parfois il y a les millisecondes et parfois non ce qui entraine des erreur dans nos parsers.

Le standard permet d'encoder les deux formats. Une harmonisation au moment de l'indexation ou de l'export est-elle envisageable voire souhaitable ?

**Comment by fxprunayre** [comment]
Une fiche exemple ?

**Comment by vbombaerts** [comment]
Pour la donnée "cbd93a53-87d1-4f1a-8a7a-751bfc982325", 

les createDate et changeDate ont comme format "yyyy-MM-dd'T'HH:mm:ss'Z'" 
ex: "2022-12-09T07:02:32Z" 

par contre  revisionDateForResource a comme format "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"  
ex "2022-12-08T23:00:00.000Z"

**Comment by davinciagf** [comment]
Dans Kibana en test, le retour est bien formater de la même façon:
![image](https://user-images.githubusercontent.com/576292/207882218-e2e82ee9-46e4-429c-b7e4-b0df03862e0e.png)
et dans le retour de la requête MW on a la différnce de format:
![image](https://user-images.githubusercontent.com/576292/207882795-bbdbf422-f555-4386-9882-f69973b321a2.png)
![image](https://user-images.githubusercontent.com/576292/207882979-ff60a0c3-1e42-4f6f-87c1-6d7658a30519.png)

**Comment by davinciagf** [comment]
Ne pas conserver les minutes dans MW et au niveau du géoportail (modifier l'éditeur de MW)

**Comment by vbombaerts** [comment]
Dans le XML, je n'ai pas vu de date encodée jusqu'au millième de seconde.

**Comment by vbombaerts** [comment]
Plus de plainte côté GP. ;-) Je ferme jusqu'à nouvel ordre
