### ISSUE TITLE
Stats sur les recherches

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#794]
Hello,

Est-ce qu'on a qqpart dans Metawal des informations sur les termes de recherche que les utilisateurs emploient pour trouver des informations ?

**Comment by fxprunayre** [comment]
Non. Quand l'utilisateur fait une recherche, la requête est de type POST avec un BODY contenant la requête Elasticsearch en JSON. Il faudrait récupérer ça et l'analyser.

On peut loguer les rquêtes ES et analyser dans Kibana (https://xeraa.net/blog/2020_slow-query-logging-elasticsearch-elastic-cloud/) mais ça semble ralentir ES. Je trouve rien d'autre pour le moment pourtant ça doit exister. On pourrait loguer côté GN aussi uniquement la portion intéressante de la recherche (on faisait ça avant et on stockait en db mais ce n'était pas optimal).

**Comment by vbombaerts** [comment]
OK. Merci pour la réponse.
Je suis sur le dossier Metawal IA et j'ai des propositions qui concernent l'amélioration des requêtes en essayant de prendre en compte le contexte sur des requêtes en langage naturel. J'ai l'impression qu'on a plutôt des requêtes "techniques". Je voulais objectiver et voir si on a des données de requêtes pour éventuellement alimenter une IA.

**Comment by fxprunayre** [comment]
* https://www.elastic.co/guide/en/machine-learning/master/ml-nlp-overview.html
* si on ajoutait les données dans les recherches, ça pourrait parler d'objets et du coup devenir moins techniques
