### ISSUE TITLE
Page d'accueil : la 3ème ligne du titre des vignettes est masquée

### ISSUE THREAD

**Issue by metawal** [SPW-DIG/metawal-core-geonetwork#8]
Lorsque le titre d'une métadonnée est trop long, il est masqué par la vignette sur la page d'accueil.

**Comment by vbombaerts** [comment]
- Une amélioration possible serait de faire varier le nombre de caractères avant tronquage en fonction de la taille de police ou de l'espace disponible
- Autre remarque : l'affichage de - Actions - mange presque une demi-ligne. Peut-on relocaliser le menu des actions ???
