### ISSUE TITLE
Imagettes : harmoniser leur taille

### ISSUE THREAD

**Issue by metawal** [SPW-DIG/metawal-core-geonetwork#80]
Ajouter un la possibilité de redimensionner automatiquement la taille des vignettes. 

Pour les données et services, on aurait une vignette carrée (toujours de la même taille). Pour les applications, une vignette rectangulaire (toujours de la même taille).

Le contrôle de la taille se ferait à l'importation de la vignette et un redimensionnement serait proposé par le système.

**Comment by davinciagf** [comment]
Possibilité d'utilisation une fonctionnalitéde de cadrage de l'image sur base d'un template (cf fonctionnalité de capture de l'imagette via le module print de mapfish pour les WMS). L'utilisateur pourrait ainsi choisir la zone la plus représentative tout en ayant un dimensionnement uniforme à l'ensemble des imagettes du catalogue.

**Comment by fxprunayre** [comment]
Ajout d'imagette par upload:
- à partir d'un fichier ou d'une URL
- définition d'une taille d'image (resize)
- définition d'une zone sur l'image (crop)

**Comment by vbombaerts** [comment]
plus nécessaire pour le moment
