### ISSUE TITLE
Indexation - type de ressource erronné

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#801]
Il y a un moissonnage qui récupère les fiches de prod et les rinjecte en test. Deux fiches qui sont des jeux de données en prod deviennent des feature catalog en test. (En fait on dirait qu'elles sont les deux à la fois en test.)

Y a-t-il des règles d'indexation différentes entre la prod et la test ?
D'où l'erreur peut-elle provenir ?

En prod : https://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/search?uuid=%5B%22968514e6-04f7-4a84-b083-f2680435f5f2%22,%228e2cf269-cedb-4fbe-943b-41a7587490e3%22%5D&from=1&to=30

En test : https://metawal4.test.wallonie.be/geonetwork/srv/fre/catalog.search#/search?uuid=%5B%22968514e6-04f7-4a84-b083-f2680435f5f2%22,%228e2cf269-cedb-4fbe-943b-41a7587490e3%22%5D&from=1&to=30

**Comment by fxprunayre** [comment]
Oui c'est lié à https://github.com/geonetwork/core-geonetwork/pull/6545 et le type principal sera dataset avec https://github.com/geonetwork/core-geonetwork/pull/6807 quand une fiche est à la fois une description de la données avec son catalogue d'attributs.

A vérifier après le prochain alignement (cette semaine).

**Comment by vbombaerts** [comment]
A suivre côté GP.

**Comment by vbombaerts** [comment]
OK côté GP
