### ISSUE TITLE
Mapstore- fulltextfilter ne fonctionne que sur un seul champ

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#806]
Dans le Mapstore, la recherche full text ne prend en compte que le premier champ spécifié.
Dans `fulltextfilter="resourceHookAbstractObject.default, resourceTitleObject.default"`
La recherche ne tient pas compte des titres.

**Comment by davinciagf** [comment]
Le fonctionnement a été mis à jour et est maintenant identioque entre la config pour le mapstore et les tableaux
![image](https://user-images.githubusercontent.com/576292/224319420-5ee1e51f-ae75-4776-be72-898ef0d78c83.png)

@vbombaerts à tester

**Comment by vbombaerts** [comment]
Les deux champs spécifiés sont pris en compte.
