### ISSUE TITLE
Mapstore - cliquer sur l'imagette ne renvoie plus vers l'application

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#807]
Dans la version actuellement en prod du composant, cliquer sur l'imagette renvoie vers l'application (idem que le lien découvrir). https://geoportail.wallonie.be/mapstore
Dans la version en test, cliquer sur l'imagette renvoie vers la page du webcomponent. Il faut la faire pointer vers l'adresse de l'appli.

**Comment by davinciagf** [comment]
Le mapping a changé, il faut utiliser :
```$[0].urlObject.default```
et plus
```$[0].url```


Exemple ICAR en test :
![image](https://user-images.githubusercontent.com/576292/222103705-ab482b9a-d9a6-48ee-8cdc-3318c392c224.png)

Exemple ICAR en prod:
![image](https://user-images.githubusercontent.com/576292/222103827-47325273-da19-4987-b359-225de9e707e9.png)

**Comment by vbombaerts** [comment]
Nickel merci. J'avais regardé mais je me suis trompé de ligne. J'ai regardé l'index du champ imageIndex au lieu de linkIndex.

**Comment by vbombaerts** [comment]
Adaptation à faire côté GP
