### ISSUE TITLE
Console admin / Moisonnage / Texte d'aide qui manquent

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#81]
![image 622](https://f.cloud.github.com/assets/6093597/1663098/b4235a36-5c0b-11e3-9b2e-9abccb223224.png)

**Comment by fxprunayre** [comment]
Des suggestions, sinon mettre des chaînes vides dans les fichiers de traduction

**Comment by fxprunayre** [comment]
A faire dans transifex, puis merge GN > MW

**Comment by vbombaerts** [comment]
serviceUrlHelp : indiquer au moins s'il faut mettre une requête getcapabilities, s'arrêter à la racine du service, etc... Eventuellement un exemple
serviceType : me parait être suffisamment clair

**Comment by fxprunayre** [comment]
cf. https://github.com/geonetwork/core-geonetwork/pull/1398
