### ISSUE TITLE
MW-GP - Problème de synchronisation en test

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#811]
On a systématiquement une erreur lors de la synchronisation automatique du GP avec MW en test.
La synchro manuelle fonctionne correctement.

Message d'erreur :
`ERROR (TIMEOUT) = Unable to query server https://metawal4.test.wallonie.be/geonetwork/geoportailwal/api/ 13/03/2023 04:30:14!`

**Comment by davinciagf** [comment]
On avait libéré les urls suivantes pour afficher la popularity:
`https://metawal4.test.wallonie.be/geonetwork/geoportailwal/api/records/82a3db7f-092c-4e9a-a97e-b92b31eeafe1/popularity`
https://github.com/SPW-DIG/metawal-core-geonetwork/issues/796 

https://github.com/SPW-DIG/metawal-core-geonetwork/blob/60b2c027344e29082e67ec37e2b2ea4d3add758d/web/src/main/webapp/WEB-INF/config-security/config-security-core.xml#L367-L381

**Comment by xdebehogne** [comment]
Cela n'a pas à voir avec cette libération d'URL.

Tout est dans le message d'erreur
« Timeout » -->  Une requête a été envoyée au service metawal mais la connexion initiale n’a pas abouti après 10 secondes d’attente. (ConnectTimeout vs RequestTimeout)
« Unable to query server » --> Au moment où le job s’exécute (4h30) le service est généralement down et il n’est donc pas possible d’interroger le serveur.
« https://metawal4.test.wallonie.be/geonetwork/geoportailwal/api » --> Url de base employée pour lancer la requête sur l’API endpoint « Search ».
« 13/03/2023 04:30:14 » -->  Heure d’envoi du mail

Le problème n'est donc pas dans le code mais dans la stabilité de l'environnement de test.
Il faudrait pouvoir identifier pourquoi ce service tombe régulièrement sur cet enevironnement car cela ne semble pas être le cas sur les autres environnements.

**Comment by vbombaerts** [comment]
Est-ce qu'on a une adresse pour vérifier si l'API est fonctionnelle ? L'équivalent du GetCapabilities pour le CSW.

**Comment by fxprunayre** [comment]
> Est-ce qu'on a une adresse pour vérifier si l'API est fonctionnelle ? L'équivalent du GetCapabilities pour le CSW.

On peut vérifier l'état du catalogue avec
https://metawal4.test.wallonie.be/geonetwork/criticalhealthcheck
ou après n'importe quel appel à l'API
eg. https://metawal4.test.wallonie.be/geonetwork/srv/api/site

**Comment by vbombaerts** [comment]
Les appels API renvoient des erreurs.
![image](https://user-images.githubusercontent.com/6093597/226572114-f03c5946-98a2-42db-a001-09d96f080d58.png)

Les appels non API sont OK.
![image](https://user-images.githubusercontent.com/6093597/226572206-ddfe4d11-729b-4ea8-a3b5-842b15266ee4.png)

https://metawal.montastic.io/

**Comment by fxprunayre** [comment]
```shell
curl -v --insecure https://metawal4.test.wallonie.be/geonetwork/srv/api/records/9ede3fbf-5b30-43a3-9370-4efd058131eb/popularity \
-H "Accept: text/plain"
4
```

![image](https://user-images.githubusercontent.com/1701393/226577393-0118fb42-ca51-49f2-9979-2bf6a4ca4df0.png)

donc il faut peut être ajouté dans l'outil de test un header valide `Accept: text/plain` pour utiliser cette opération?

**Comment by davinciagf** [comment]
Je confirme que le query parameters "Accept: text/plain"  doit être présent au niveau de la requête (GET - "popularity") pour éviter une erreur. On en avait parlé lors du meeting avec Xavier.

**Comment by christophenoel** [comment]
@vbombaerts: Il serait très utile de résumer symptomes rencontrés et ce qui a pu être monitoré ? (je pense notamment aux graphiques de monitoring de l'infrastructure).

Instinctivement, je pense à problème de réseau mais je ne connais rien sur cette infrastructure. Peux-tu nous faire parvenir un document décrivant l'infrastructure de test ?

Merci.

**Comment by vbombaerts** [comment]
Pas de problème dans les environnement de valid et prod. 
Je déplace le ticket sur une version ultérieure pour ne pas bloquer la clôture de la version.

**Comment by vbombaerts** [comment]
Nouvel environnement déployé. Je cloture car plus d'actualité.
