### ISSUE TITLE
Erreurs 4.2.3 en environnement de valid

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#814]
L'interface de recherche est vide
![image](https://user-images.githubusercontent.com/6093597/225873856-fd3462cc-10e4-4be7-9c56-c6c5f664dcbc.png)
et on a le message
![image](https://user-images.githubusercontent.com/6093597/225862798-59e6d358-4560-4517-96e2-3e7b874b5649.png)
- L'accueil édition est OK. Facettes et recherche full text fonctionnels
- La visualisation des fiches est OK.
- Réindexation OK 
- mais impossible d'afficher les erreurs d'indexation
![image](https://user-images.githubusercontent.com/6093597/225864505-d263ad35-3b78-4095-905a-78dd11ab18ab.png)

Vider le cache de mise en page donne
![image](https://user-images.githubusercontent.com/6093597/225862599-43b90b1f-63bc-471a-8d2b-2aa4a7ac144c.png)

Hier, on avait un écran blanc au démarrage de l'appli (complètement blanc) et Arnaud m'a fait jouer
https://metawal4.valid.wallonie.be/geonetwork/static/wroAPI/reloadModel
https://metawal4.valid.wallonie.be/geonetwork/static/wroAPI/reloadCache 

J'ai essayé mais ça na rien changé.

**Comment by fxprunayre** [comment]
Cf. https://geonetwork-opensource.org/manuals/4.0.x/en/overview/change-log/version-4.2.0.html#migration-instructions

<pre>
Due to H2 database major update, when migrating from a previous version drop the following database caches:
JS/CSS cache database in $DATA_DIR/wro4j-cache.mv.db
Formatter cache database in $DATA_DIR/data/resources/htmlcache/formatter-cache/info-store.mv.db
</pre>

**Comment by vbombaerts** [comment]
Donc il suffit d'effacer les deux fichiers wro4j-cache.mv.db et info-store.mv.db ?

**Comment by fxprunayre** [comment]
normalement oui et relancer.

**Comment by vbombaerts** [comment]
OK, je demande au DTIC de faire ça.
@davinciagf tu pourras modifier la procédure de déploiement pour ajouter cette étape STP (si ce n'est pas déjà inclus)

**Comment by vbombaerts** [comment]
OK en valid. J'attends confirmation de l'adaptation des instructions de déploiement pour le tagger OK.

**Comment by davinciagf** [comment]
Note de déploiement adaptée.
