### ISSUE TITLE
Plantages suite mise en prod

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#816]
2 plantages de Metawal le 28/03 suite à mise en prod. Vers 13h et vers 16h.
A garder à l'oeil.
Pas de cause identifiée à l'heure actuelle.
Redémarrage effectué par le DTIC suite à alerte d'indisponibilité.

**Comment by fxprunayre** [comment]
Quels symptômes ?

**Comment by vbombaerts** [comment]
Je n'ai eu aucune info. Une erreur 500 quand j'essaie de me connecter.
Le DTIC a eu une alerte et a redémarré.

**Comment by vbombaerts** [comment]
"Too Many Open Files"
Semble résolu suite à intervention de Didier.
Christophe proposait d'intervenir quand même encore sur la config (voir mail)

**Comment by vbombaerts** [comment]
@christophenoel Je propose que tu fasses un nouveau ticket pour le changement proposé et que tu fermes celui-ci une fois que c'est fait.

**Comment by christophenoel** [comment]
@vbombaerts  : oui je vais faire un nouveau ticket, car je ne pense qu'il vaudrait mieux prévoir ce changement au release prochain (changer d'utilisateur n'est pas forcément anodin si l'on considère tous les effets de bord possible liés aux permissions).

**Comment by christophenoel** [comment]
#818 done.
