### ISSUE TITLE
Affichage Rapports qualité

### ISSUE THREAD

**Issue by marceaulouis** [SPW-DIG/metawal-core-geonetwork#819]
Depuis la mise en prod de la version 4.2.3 les informations de rapport de qualité ne s'affichent plus en mode édition et en vue "complète" dans l'onglet qualité

![image](https://user-images.githubusercontent.com/99397823/228848684-50e14715-2782-46a0-ac29-8eae307a8a67.png)

Le rapport est pourtant dans le xml et est visible dans les ressources associées, également en vue "simplifiée".

![image](https://user-images.githubusercontent.com/99397823/228849061-8110531f-f023-4bd0-bda9-03944d8f1074.png)

C'est le cas pour l'ajout de rapports comme pour les anciennes fiches qui en contenaient et qu'on édite

**Comment by fxprunayre** [comment]
Quelle fiche?

**Comment by marceaulouis** [comment]
Toutes, mais par exemple : https://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/e257f5df-6c96-4118-b4d2-1e63e955df53

**Comment by fxprunayre** [comment]
Corrigé avec https://github.com/SPW-DIG/metawal-core-geonetwork/commit/19269273cf11888a8c42127d7d77aa02c748986d. 

On a eu un pb similaire dans sextant (et pas certain de comprendre pourquoi ce type de XPath sont maintenant invalides - sans doute une mise à jour d'une librairie).

A tester & déployer !

**Comment by christophenoel** [comment]
@fxprunayre : Désolé, mais je ne comprends pas pourquoi un problème corrigé en 4.2.1 se produit avec la 4.2.3 ? Que suggères-tu de déployer ?

**Comment by fxprunayre** [comment]
> @fxprunayre : Désolé, mais je ne comprends pas pourquoi un problème corrigé en 4.2.1 se produit avec la 4.2.3 ? Que suggères-tu de déployer ?

C'est un nouveau pb (dont je n'identifie pas vraiment la cause en tout cas pour le moment).

**Comment by christophenoel** [comment]
> C'est un nouveau pb (dont je n'identifie pas vraiment la cause en tout cas pour le moment).

Donc rien à tester et déployer ? :)

**Comment by christophenoel** [comment]
Je viens de remarquer qu'il n'y a pas de branche 4.2.3 dans le dépôt de code source, ce qui signifie que la correction que tu as proposée est récente et n'a pas encore été livrée.

Je pense qu'il est important de maintenir une correspondance claire et cohérente entre les branches du dépôt et les versions livrées pour éviter toute confusion.

**Comment by fxprunayre** [comment]
branche 4.2.3 ajoutée et définie par défaut.

**Comment by christophenoel** [comment]
Merci beaucoup.

**Comment by vbombaerts** [comment]
Correctif déployé en valid.
OK en valid.
