### ISSUE TITLE
Export RDF Lien construit sur base de l'adresse IP

### ISSUE THREAD

**Issue by geologiewallonie** [SPW-DIG/metawal-core-geonetwork#82]
Les liens construits sur un export RDF tiennent compte de l'adresse IP et non du DNS du serveur.

**Comment by fxprunayre** [comment]
Problème de configuration du catalogue. Contacter l'administrateur @vbombaerts 

Corrigé ici sur l'instance de test
http://metawal3.test.wallonie.be/geonetwork/srv/fre/admin.console#/settings

**Comment by vbombaerts** [comment]
![image 665](https://f.cloud.github.com/assets/6093597/1887150/43e7f08e-79f6-11e3-9321-b58c460562a8.png)
