### ISSUE TITLE
Bug du filtre module d'analyse de liens

### ISSUE THREAD

**Issue by marceaulouis** [SPW-DIG/metawal-core-geonetwork#825]
Dans le module d’analyse de liens, le filtre sur la sélection en cours est limité à 188 entrées..

Au delà, aucun résultat ne s'affiche. J'ai testé plusieurs combinaisons de fiches sélectionnées, donc ça ne semble pas liée à une fiche en particulier qui bloquerait

189 fiches :
![2023-04-17 11_01_23-Metawal](https://user-images.githubusercontent.com/99397823/232438295-c96824e6-e198-4c25-9a34-bb696bd28259.png)

188 fiches : ok
![2023-04-17 11_02_40-Metawal](https://user-images.githubusercontent.com/99397823/232438390-87c7e4c9-95b5-43ef-a4e2-8d6debd7165d.png)

**Comment by vbombaerts** [comment]
Tu as essayé en utilisant l'option "Publié dans ce groupe" ? 
Il y a un groupe Link_checker dans lequel tu peux publier les fiches à tester. Il faut d'abord retirer celles qui sont dedans pour le moment.

**Comment by marceaulouis** [comment]
Bon moyen de contournement, mais moins pratique

Attention, problème de fusion des privilèges sur firefox : #827

**Comment by fxprunayre** [comment]
En effet, l'erreur
```
https://metawal.wallonie.be/geonetwork/srv/api/records/links?filter=%7B%22records%22%3A%22435c454c-0d4b-41cf-a136-a1aba134d9ac+74e505f5-fae1-4e86-b23b-89.....936-5fcc7129500a+2d57f4cb-9374-4e0d-8384-20d98a4b3fad%22%7D&page=0&size=10&sort=lastState%2Cdesc 414 (Request-URI Too Large)
```
Il faudrait sans doute passer la requête en POST

**Comment by GeryNi** [comment]
L'url de la requête serait trop grande.

**Comment by fxprunayre** [comment]
GN ref https://github.com/geonetwork/core-geonetwork/pull/7022

**Comment by fxprunayre** [comment]
A déployer en test.

**Comment by marceaulouis** [comment]
ok en test

**Comment by vbombaerts** [comment]
J'ai essayé avec 120 --> OK
240 --> rien ne s'affiche
