### ISSUE TITLE
Webcomposants - pack d'icones indisponible

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#826]
Hello,

Les icones utilisées dans les webcomposants ne sont pas dispo. 
Pouvez-vous les rendre accessibles SVP ? 
Ex : https://metawal.wallonie.be/geonetwork/srv/api/pages/fre/demointranet/content

**Comment by GeryNi** [comment]
Les requêtes pour les icones et polices renvoient le code d'erreur HTTP 404 Not Found:
https://metawal.wallonie.be/geonetwork/catalog/lib/icho/...

Exemple:
- https://metawal.wallonie.be/geonetwork/catalog/lib/icho/outline-icons.ad97afd3337e8cda302d.ttf

![image](https://user-images.githubusercontent.com/78086592/232535676-90d9f494-049d-476c-8f4a-f4fc90f3292d.png)

**Comment by vbombaerts** [comment]
C'est un problème de packaging ou de déploiement alors ?

J'ai regardé dans les infos mais je ne vois pas où sont censées se trouver les icones et polices
![image](https://user-images.githubusercontent.com/6093597/232749569-7cbe0463-f792-4e38-89fd-35b153ad2bc6.png)

**Comment by davinciagf** [comment]
@GeryNi à vérifier normalement ils sont au niveau de la librairie icho:
![image](https://user-images.githubusercontent.com/576292/232758797-adb0061f-aa84-4672-a201-6d127a176ccb.png)

Si pas présent, depuis icho refaire un build du web component et mettre à jour les fichiers icones dans MW
