### ISSUE TITLE
Problème d'affichage Mise à jour des privilèges des sélections

### ISSUE THREAD

**Issue by marceaulouis** [SPW-DIG/metawal-core-geonetwork#827]
Sur Firefox, impossible d'afficher les "+" et "-" dans l'outil de mise à jours des privilèges d'une sélection.

Firefox :
![image](https://user-images.githubusercontent.com/99397823/232744171-27a72ddc-cd32-4f74-ae15-5abde1549a8c.png)

Edge :
![image](https://user-images.githubusercontent.com/99397823/232744685-2833cd8b-0c6f-4ea6-a80d-190fe662c754.png)

Je n'ai pas testé la fusion sur Firefox, pour savoir si c'est juste de l'affichage ou si ça va plus loin

**Comment by fxprunayre** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=765035
https://www.w3.org/TR/CSS2/generate.html#before-after-content

Il semblerait que Firefox soit conforme à la spec et on ne peut pas via CSS ajouter un symbol avant ou après un élément qui n'est pas un container - eg. input.

**Comment by fxprunayre** [comment]
GN ref. https://github.com/geonetwork/core-geonetwork/pull/7027

**Comment by fxprunayre** [comment]
A déployer en test

**Comment by marceaulouis** [comment]
Ok en test
