### ISSUE TITLE
Console admin / Moisonnage / langue des métadonnées et thème ISO

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#83]
Langue est par défaut en anglais --> par défaut en français
- liste déroulante pour choisir la langue et le thème ISO

**Comment by fxprunayre** [comment]
Evolution de préférence à traiter après merge des travaux sur l'éditeur qui fourniront une API pour l'accès aux langues et codelist des profils.

**Comment by fxprunayre** [comment]
Pour la langue, fait dans la branche de refonte de l'éditeur (see https://github.com/geonetwork/core-geonetwork/commit/3c50ba2aa3bdf57f03a46f388a1f86b09595e82e)

**Comment by fxprunayre** [comment]
> liste déroulante pour choisir la langue et le thème ISO

![image](https://cloud.githubusercontent.com/assets/1701393/7496780/95e12572-f416-11e4-9179-43e66f829b33.png)
