### ISSUE TITLE
Pages statiques dans des menus et sous-menu

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#830]
Possibilité d'ajouter des pages statiques en menu et sous-menu. PAr exemple pour avoir une liste des tableaux de bord Kibana ou une liste des config webcomponents existantes

**Comment by fxprunayre** [comment]
Ce qui a été fait par geocat.bv est un peu différent, "submenu" ajoute des liens dans le header eg. https://www.nationaalgeoregister.nl/geonetwork/srv/dut/catalog.search#/home avec Contact et Help dans l'en-tête.

Donc à faire, mais ce sera un peu différent.

**Comment by fxprunayre** [comment]
Cf. https://github.com/geonetwork/core-geonetwork/pull/7138

**Comment by fxprunayre** [comment]
Pré requis:
* page associée au menu TOP
* page dans la bonne langue

eg.
```json
[
  "gn-site-name-menu",
  "gn-portal-switcher",
  "gn-search-menu",
  "gn-map-menu",
  "gn-contribute-menu",
  {
    "Autres info": [
      "licences"
    ]
  },
  "gn-admin-menu"
]
```

**Comment by vbombaerts** [comment]
@vbombaerts mettre un peu d'ordre dedans

**Comment by vbombaerts** [comment]
![image](https://github.com/user-attachments/assets/33d5fb42-962b-4558-8994-d3ce2d2d3d36)

![image](https://github.com/user-attachments/assets/35619b68-0404-408e-8649-5b157571184d)
