### ISSUE TITLE
Webcomposants - Fulltextfilter ne fonctionne plus dans les composants de type "cards"

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#831]
Dans les composants de type cards comme par exemple https://metawal4.test.wallonie.be/geonetwork/srv/api/pages/fre/demomapstore/content la recherche libre (fulltextfilter) ne fonctionne plus.
Dans les composants de type tableau c'est OK.
https://metawal4.test.wallonie.be/geonetwork/srv/api/pages/fre/demointranet/content

Une idée ?

**Comment by GeryNi** [comment]
Le seule différence que je vois entre les 2 composants est :

Dans le composant table (qui fonctionne)
`textFilter` = `fulltextfilter.replace(/\s+/g,"").split(",")`

Dans le composant card (qui pose problème):
`textFilter` = `fulltextfilter.split(',')`

Je suppose donc qu’il faut rajouter ‘replace(/\s+/g,"")’ afin d’enlever des caractères qui pourraient poser problème dans la requête qui sera envoyée à Elastic.

**Comment by vbombaerts** [comment]
Dans la console réseau, on voit que pour le composant tableau taper des caractères dans la boite de recherche engendre une recherche msearch. Pas pour les cards.
