### ISSUE TITLE
Bouton d'appel quota validateur Inspire

### ISSUE THREAD

**Issue by marceaulouis** [SPW-DIG/metawal-core-geonetwork#836]
Ajouter quelque part (Statut ?) un bouton permettant d'appeler le nombre de tickets restant pour le validateur INSPIRE

https://yzyiqfakm4.execute-api.eu-west-1.amazonaws.com/validator/v2/Usages/{API-Key}/
where {API-key} is the API key provided by the JRC for Validator API usage.

**Comment by vbombaerts** [comment]
Le décompte est décalé de quelques heures. Pas très pratique. Remonter au JRC

**Comment by fxprunayre** [comment]
A déployer pour test.

**Comment by vbombaerts** [comment]
https://github.com/INSPIRE-MIF/helpdesk-validator/discussions/977#discussioncomment-6939051

**Comment by marceaulouis** [comment]
Le décompte a disparu en Prod, à moins que ce soit à activer quelque part ?
![image](https://github.com/user-attachments/assets/ed7b74a9-6528-44ea-af2f-8c8e700b2912)

en test :
![image](https://github.com/user-attachments/assets/7e05d0a6-439b-4411-8691-c485cb8429b1)

**Comment by GeryNi** [comment]
Je n'ai rien trouvé dans la configuration. D'après ce que je vois, cela devrait se faire automatiquement . Je ne vois pas d'erreur dans le slogs non plus.

**Comment by fxprunayre** [comment]
> Le décompte a disparu en Prod, à moins que ce soit à activer quelque part ?

Le décompte ne s'affiche que si on utilise le endpoint amazon https://yzyiqfakm4.execute-api.eu-west-1.amazonaws.com/validator qui décompte le quota et qui est placé devant le validateur.

Si on déploie ou utilise le validateur seul, il n'a pas de notion de quota.
