### ISSUE TITLE
Moissonnage depuis la test en erreur

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#837]
Quand on clique sur un moissonneur, on obtient le message d'erreur suivant :

![image](https://github.com/SPW-DIG/metawal-core-geonetwork/assets/6093597/e76bbac9-2150-4813-beaf-93263de3f8f4)

**Comment by fxprunayre** [comment]
L'erreur retournée par Elastic est `No mapping found for [resourceTitleObject.default.sort] in order to sort`. Réindexation en cours. Le tri est maintenant insensible à la casse et l'index contient un nouveau champ dédié.
