### ISSUE TITLE
Bug suggestion déclaration Spatinéo : suppression du contact des MD

### ISSUE THREAD

**Issue by marceaulouis** [SPW-DIG/metawal-core-geonetwork#838]
Pour les fiches de services WMS et REST, la suggestion qui permet de déclarer le service auprès de Spatineo supprime ce qui est encodé au niveau du contact "point de contact" pour les métadonnées :

 </mdb:metadataScope>
   <mdb:contact>
      <cit:CI_Responsibility>
         <cit:role>
            <cit:CI_RoleCode codeList="http://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#CI_RoleCode"
                             codeListValue="pointOfContact"/>
         </cit:role>
         <cit:party>
            <cit:CI_Organisation>
               <cit:name>
                  <gco:CharacterString>Gestion et valorisation de la donnée (SPW - Secrétariat général - SPW Digital - Département Données transversales - Gestion et valorisation de la donnée)</gco:CharacterString>
               </cit:name>
               <cit:contactInfo>
                  <cit:CI_Contact>
                     <cit:address>
                        <cit:CI_Address>
                           <cit:electronicMailAddress>
                              <gco:CharacterString>helpdesk.carto@spw.wallonie.be</gco:CharacterString>
                           </cit:electronicMailAddress>
                        </cit:CI_Address>
                     </cit:address>
                  </cit:CI_Contact>
               </cit:contactInfo>
            </cit:CI_Organisation>
         </cit:party>
      </cit:CI_Responsibility>
  </mdb:contact>

**Comment by fxprunayre** [comment]
A tester https://github.com/SPW-DIG/metawal-core-geonetwork/commit/3f2a7be0708e7e820e1eb0309c7eb9c2814c920f et déployer.

**Comment by GeryNi** [comment]
Déployé sur l'environnement TEST.

**Comment by marceaulouis** [comment]
Ok en test
