### ISSUE TITLE
Webcomposant tableau intranet

### ISSUE THREAD

**Issue by marceaulouis** [SPW-DIG/metawal-core-geonetwork#839]
Je remonte ici quelques remarques de Francis après utilisation du webcomposant #773 

- [ ] un clique sur une fiche ouvre un nouvel onglet (comme pour mapstore)
- [ ] la recherche sur les identifiants ne renvoie pas les résultats attendus, le "_" n'est pas pris en compte : "Si je veux chercher la série FORET,   je reçois FORET, FORET__MASQUE_2018,  FORETANC et bien d'autres choses.  Pour affiner la recherche, je voudrais cherche toutes les ressources dont l'identifiant est   "FORET__", mais ça ne marche pas "

**Comment by vbombaerts** [comment]
Pour le premier point, le clic sur la molette de la souris ou le clic droit permettent d'ouvrir dans un nouvel onglet. C'est pas suffisant ?

Pour le deuxième, il faut demander à @fxprunayre ou @GeryNi. Peut-être que les identifiants locaux ne sont pas indexés en tronçons mais uniquement dans leur globalité ?

**Comment by fxprunayre** [comment]
Donc après quelques tests avec @GeryNi, on aurait tendance à dire qu'on ne peut pas faire grand chose.
* FORETAN = 0 résultat
* FORETANC = 5 (car dans les fiches il y a le token FORETANC dans les URL par exemple)
* FORETANC_ = 0 
* FORETANC_* = 4
 
![image](https://github.com/SPW-DIG/metawal-core-geonetwork/assets/1701393/77485e21-ea51-4703-a5ef-8d97b0f98807)

Les recherches sont faites sur les bons champs en mode "full text" ie. avec analyse.
On aurait plutôt tendance à préconiser aux utilisateurs l'utilisation de "*" pour faire des requêtes commence/contient/se termine par

![image](https://github.com/SPW-DIG/metawal-core-geonetwork/assets/1701393/854b1fca-24ad-49b4-8fc8-86f50885c84b)

et il ne semble pas pertinent d'ajouter des "*" de manière systématique autour des mots avant de lancer la recherche car on retournera trop de résultats.
