### ISSUE TITLE
Vue avancée d'une fiche en Anglais

### ISSUE THREAD

**Issue by geologiewallonie** [SPW-DIG/metawal-core-geonetwork#84]
Les champs sont en anglais alors que l'adresse indique bien que l'interface doit être en français.
Cfr. http://metawal3.test.wallonie.be/geonetwork/srv/fre/search?uuid=5bb1c85c-abe1-46b3-9af6-489ab95cd0cb

**Comment by fxprunayre** [comment]
En effet, manque prise en compte du code langue dans l'URL qui doit prendre priorité sur le paramètre hl.

L'URL http://metawal3.test.wallonie.be/geonetwork/srv/fre/search?uuid=290e1fe8-0d99-410e-967b-a02f389b931a&hl=fre est ok.
