### ISSUE TITLE
Fiche en erreur sans identifiant

### ISSUE THREAD

**Issue by marceaulouis** [SPW-DIG/metawal-core-geonetwork#840]
La fiche qui pose problème côté GP (dépubliée en PROD) :

https://metawal.wallonie.be/geonetwork/srv/fre/catalog.edit#/metadata/52807?redirectUrl=catalog.edit&tab=xml

@vbombaerts tu as p-e plus d'info sur l'historique, il s'agit d'une fiche ign cartoweb

**Comment by fxprunayre** [comment]
Le problème est que la fiche est en ISO19139 en XML mais le schéma est ISO19115-3.

En regardant, la fiche vient d'un moissonneur et la conversion utilisée a été modifiée. J'ai donc remplacé par 
`schema:iso19115-3.2018:convert/fromISO19139-with-languages-refactor?defaultLanguage=fre&others=none&copyPreviousDefaultIfEmpty=true`, supprimer la fiche et relancer le moissonnage.

Ca semble bon @marceaulouis.
