### ISSUE TITLE
Ajouter une facette HVD

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#842]
Le thésaurus HVD a été ajouté à Metawal. Il faut maintenant ajouter une facette qui permettra de filtrer les données sur ce thésaurus.

**Comment by fxprunayre** [comment]
Fiches utilisant ce thésaurus https://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/search?any=q(_exists_:th_high-value-dataset-category)

Le champ est donc
![image](https://github.com/SPW-DIG/metawal-core-geonetwork/assets/1701393/75e79bb7-1622-47b6-8b6f-ce3aa14e1e7a)


Ajouter la configuration dans https://metawal4.test.wallonie.be/geonetwork/srv/eng/admin.console#/settings/ui
```json
{
  
  "th_high-value-dataset-category.default": {
    "terms": {
      "field": "th_high-value-dataset-category.default",
      "size": 20,
      "order": {
        "_key": "asc"
      }
    }
  }
}
```

Ajouter la clé de traduction `facet-th_high-value-dataset-category` dans https://metawal4.test.wallonie.be/geonetwork/srv/eng/admin.console#/settings/languages

**Comment by vbombaerts** [comment]
Super. Merci.
