### ISSUE TITLE
Support formats DCAT

### ISSUE THREAD

**Issue by GeryNi** [SPW-DIG/metawal-core-geonetwork#843]
# Objectif de l’Activité

Améliorer MetaWal pour permettre l'export d’enregistrements dans divers formats DCAT (DCAT, DCAT-AP, Mobility DCAT-AP, StatDCAT, GeoDCAT-AP).

# Contexte

La Région wallonne, à la lumière de projets émergents (y compris la nouvelle directive sur la mobilité), constate une demande croissante de données au format DCAT, pour publier des données géographiques et non géographiques (telles que les horaires de bus). Il est essentiel de proposer différents profils DCAT (DCAT-AP, Mobility DCAT-AP, STatDCAT, et GeoDCAT) pour répondre à ces exigences variées.

Dans MetaWal, les fiches de métadonnées sont stockées dans la base de données au format XML ISO-19115-3.

# Exigences du Client

1. **Mappage ISO - DCAT**: Les enregistrements MetaWal sont encodés en XML selon le format ISO19115-3. Pour chaque catégorie de fiche, les profils DCAT appropriés devraient être identifiés. De plus, tout champ manquant requis pour les divers profils DCAT devrait être pris en charge par une extension ISO-19115-3.

2. **Prise en charge des données non géospatiales**: La pertinence des méthodes d’encodage actuelles doit être évaluée. Si des lacunes sont détectées, la nécessité d’un format natif adapté à ces types de données non géospatiales devrait être explorée et définie.

3. **Encodage des Enregistrements**: L’outil d’interface utilisateur Web devrait être adapté pour s’assurer que l’utilisateur peut facilement encoder à la fois les champs géospatiaux supplémentaires nécessaires pour DCAT, mais aussi encoder les données non géospatiales.

4. **Conversion ISO - DCAT**: La transition du format ISO-19115-3 vers les profils DCAT devrait être mise en œuvre, soit en développant une classe JAVA, soit en utilisant XSLT. MetaWal est actuellement principalement basé sur des convertisseurs XSLT.

5. **Validation**: Un service de validation, que ce soit via une API en ligne ou une bibliothèque locale, doit être mis en œuvre pour valider les enregistrements générés.

# Approche Proposée

Nous pensons qu’il serait le plus efficace de diviser le travail en deux activités distinctes mais complémentaires.

## Activité 1 : Intégration de Données Non Géospatiales

1. **Étape Initiale** : Discerner les exigences pour intégrer des fiches de données non géospatiales dans GeoNetwork.
2. **Analyse** : Investiguer et comprendre les différentes catégories de fiche destinées à l’importation dans la base de données.
3. **Conception de Spécification** : Élaborer une spécification adaptée des couches DCAT, en veillant à ce qu’elles puissent être réutilisées selon les types de fiche.
4. Envisager la **solution** pratique.

## Activité 2 : Conversion de Données Géospatiales en DCAT

1. **Recherche de Profil** : Déterminer si un profil autre que GeoDCAT-AP peut héberger des informations géospatiales issues de l’ISO-19115-3. Les profils actuels de DCAT-AP semblent trop génériques, manquant de propriétés pour l’encapsulation géospatiale.
2. **Développement d’Outil de Conversion** : Développer un outil ou un algorithme pour convertir des enregistrements de données géospatiales du format ISO-19115-3 vers GeoDCAT-AP et tout autre format identifié.
3. **Prochaines étapes** : Après le développement de l’outil, envisagez d’améliorer l’interface utilisateur pour renforcer l’interaction et l’expérience de l’utilisateur, valider les fiches au format DCAT, ....

**Comment by vbombaerts** [comment]
Guidelines pour implémentation du DCAT - https://joinup.ec.europa.eu/collection/semantic-interoperability-community-semic/solution/dcat-application-profile-implementation-guidelines

**Comment by GeryNi** [comment]
- [x]  Définir la structure/organisation modulaire pour les formaters DCAT
- [x] Mapping ISO -> DCAT core (W3C) 
- [x] Investiguer DCAT-AP : déterminer quelle(s) version(s) supporter
- [ ] Sélectionner les fiches utilisées pour construire et tester les exports aux différents profils DCAT (HVD, MobiltyDCAT, GeoDCAT)
    - [ ] Pour tester, utiliser une seule fiche pour les différents profils (ou bien séparer en fiches spécifiques)
- [x] définir comment tester l'export en DCAT
    - [x] vérification locale de la présence du contenu nécessaire
    - [x] outil de validation DCAT

**Comment by fxprunayre** [comment]
Démo https://apps.titellus.net/geonetwork/srv/eng/catalog.search#/metadata/7fe2f305-1302-4297-b67e-792f55acd834

![image](https://github.com/SPW-DIG/metawal-core-geonetwork/assets/1701393/e6ac2df8-52f4-42ad-b102-a98c4ba8378d)

**Comment by GeryNi** [comment]
validation des fiches en local avec les règles SHACL (exemple: https://github.com/SEMICeu/DCAT-AP/tree/gh-pages/releases/3.0.0/html/shacl )

validation en ligne via Validateur: https://www.itb.ec.europa.eu/shacl/dcat-ap/upload

**Comment by vbombaerts** [comment]
DCAT implémenté.
Correctifs ou améliorations à encoder dans des nouveaux tickets.
