### ISSUE TITLE
NAP-ITS - transportdata.be

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#844]
Dans le cadre de la Directive ITS et de ses règlements délégués, les données relatives aux systèmes de transport intelligents doivent être remontées dans le catalogue transportdata.be - infos [https://transportdata.be/fr/pages/information-for-dataproviders](https://transportdata.be/fr/pages/information-for-dataproviders).

Seront remontés via Metawal uniquement les données à caractère régional, càd dont le SPW est gestionnaire ou qui sont sous la responsabilité d'une autorité publique à portée régionale. Les données locales (communes) sont remontées via ODWB.

Le format d'échange des métadonnées est le [MobilityDCAT-AP](https://mobilitydcat-ap.github.io/mobilityDCAT-AP/drafts/latest/).

### Tâches :

- [ ] Définir la liste des données qui doivent être remontées via Metawal. Il faut pour ça obtenir de transportdata.be la liste des données et leur sources authentiques pour le niveau SPW et autorités publiques à portée régionale.
- [x] Définir un mot-clé ou autre mécanisme permettant de tagger dans Metawal les données concernées
- [x] Déployer un point d'accès et un portail "NAPITS"
- [x] Identifier les éléments de métadonnées nécessaires pour la conformité au MobilityDCAT-AP. Réaliser un mapping conceptuel avec ISO 19115 pour identifier ceux qu'il faut ajouter
- [x] Idem avec les codelists spécifiques au MobilityDCAT-AP. Les ajouter dans Metawal.
- [ ] Prendre contact avec les gestionnaires de données et compléter les fiches avec les éléments spécifiques MobilityDCAT-AP. Obtenir l'aval pour la republication sur transportdata.be.
- [x] Voir avec transportdata.be s'ils sont capables de moissonner de l'ISO --> NON
- [x] Développer la conversion ISO 19115 --> MobilityDCAT-AP

**Comment by GeryNi** [comment]
Mobility DCAT : keywords ont été ajoutés.
A faire:

- [ ] vérifier que topus les camps sont présents
- [ ] Fournir un exemple de sortie MobilityDCAT

**Comment by vbombaerts** [comment]
Le travail principal est terminé. Le portail est fonctionnel.
Les actions relatives au contenu sont migrées dans le ticket #910 
Les améliorations du MobilityDCAT feront l'objet de tickets spécifiques.
