### ISSUE TITLE
Crédits

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#846]
Comment citer les crédits (notamment dans le cadre de CC-BY) : 
- à quel niveau organisationnel doit-on créditer les données ?
- abréviations pour les organisations ou pas ?
- Faut-il indiquer l'id de la donnée etc.
- comment créditer des travaux scientifiques  ?
- faut-il indiquer une date (année) ? Quid pour des données avec mise à jour continue ?
- quid en cas de plusieurs propriétaires ?
- Divergence entre propriétaire et personnes citées au crédits (voir WALOUS avec Aerospacelab)

Lien avec le getcapabilities des services.
Lien avec outil de téléchargement.

Coordination SPW nécessaire.
@vbombaerts doit préparer une proposition à soumettre au CCG.

**Comment by fxprunayre** [comment]
Exemple Ifremer
https://sextant.ifremer.fr/Donnees/Catalogue#/metadata/a96b7ba0-a1bc-11dd-9201-000086f6a62e
https://sextant.ifremer.fr/Donnees/Catalogue#/metadata/387879ca-24b7-4bbf-a551-33356dc76656 (plusieurs auteurs)

* Crédits dans identificationInfo/*/credit
* DOI et citations

**Comment by vbombaerts** [comment]
Pour la citation des données diffusées par le Géoportail, on partirait sur

`[organisation propriétaire de la donnée (sans l'acronyme - role=owner - ', ' si n)] - [nom de la donnée] (version [date de dernière mise à jour ou à défaut date de création]) - [url de la fiche sur le géoportail] `

Exemple :
Service Public de Wallonie – Relief de la Wallonie – Modèle Numérique de Terrain (MNT) 2021-2022 (version 21-06-2022) - https://geoportail.wallonie.be/catalogue/a004e570-99d6-4fe5-b83d-49b774409278.html

Ca parait faisable ?

**Comment by fxprunayre** [comment]
A faire par là https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.2.3/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/citation/common.xsl#L40

**Comment by vbombaerts** [comment]
En version courte :
`[acronyme du propriétaire de la donnée] - [année de dernière mise à jour ou à défaut de création]`

**Comment by vbombaerts** [comment]
pas prioritaire. on pourrait encore changer de format pour se calquer sur qqch de plus standard.

**Comment by marceaulouis** [comment]
Je relance ce ticket suite à des discussions en interne

Le format choisi est celui-ci :

[organisation propriétaire de la donnée (sans l'acronyme - role=owner - ', ' si n)] - [nom de la donnée] (version [date de révision ou à défaut date de création]) - [identifiant de la ressource au format https://geodata.wallonie.be/id/mduuid] 

Est-ce que c'est faisable ? Dans quels délais environ ?
Merci !

**Comment by marceaulouis** [comment]
De plus, pouvez-vous renoter ici quelque part comment on peut exposer cette citation, au GP par exemple ? (csw ? API ? ou on doit passer par le DOI d'office ?)

**Comment by fxprunayre** [comment]
> [organisation propriétaire de la donnée (sans l'acronyme - role=owner - ', ' si n)] - [nom de la donnée] (version [date de révision ou à défaut date de création]) - [identifiant de la ressource au format https://geodata.wallonie.be/id/mduuid]

![image](https://github.com/SPW-DIG/metawal-core-geonetwork/assets/1701393/0786f888-e989-49fc-8907-070a42d7da79)

Pour la date, on affiche la date complète (ou uniquement l'année) ? Actuellement on prend la date la plus récente parmis 'publication', 'revision'. J'ai ajouté creation. Ca convient @marceaulouis ?

>  De plus, pouvez-vous renoter ici quelque part comment on peut exposer cette citation, au GP par exemple ? (csw ? API ? ou on doit passer par le DOI d'office ?)

API 
https://metawal.wallonie.be/geonetwork/srv/api/records/abe74a37-3c88-452b-94fd-5922d97d2e60/formatters/citation?format=?
https://metawal.wallonie.be/geonetwork/srv/api/records/abe74a37-3c88-452b-94fd-5922d97d2e60/formatters/citation?format=html
https://metawal.wallonie.be/geonetwork/srv/api/records/abe74a37-3c88-452b-94fd-5922d97d2e60/formatters/citation?format=text
et on peut aussi faire une requête CSW et ensuite construire la citation avec le contenu de la fiche


A déployer en test @GeryNi .

**Comment by marceaulouis** [comment]
Merci !

Pour la date, la règle me semble bien, c'est bien la date complète

**Comment by marceaulouis** [comment]
C'est un détail, mais si on sait rajouter un espace entre nom de la ressource et date
![image](https://github.com/SPW-DIG/metawal-core-geonetwork/assets/99397823/6192a824-3e3d-4045-bf15-85b2e48ed937)

**Comment by fxprunayre** [comment]
> C'est un détail, mais si on sait rajouter un espace entre nom de la ressource et date

Corrigé.
