### ISSUE TITLE
Tableaux pour contrôle des erreurs de linkage INSPIRE

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#848]
Sur base des webcomponents, préparer un tableau par type d'erreur permettant de soutenir la recherche des éléments en erreur dans le data-service linkage du reporting INSPIRE

[All the Capabilities Layer links resolved.](https://jrc-geoportal-internal.geocat.live/geonetwork/srv/eng/admin.console) 
Donné renseignée dans le capabilities du service mais dont la fiche n’est pas publiée (--> publier la fiche manquante)

[All OperatesOnLinks Dataset Metadata documents match a document](https://jrc-geoportal-internal.geocat.live/geonetwork/srv/eng/admin.console) 
Mismatch entre les données renseignées dans le getcapabilities du service et celle déclarées dans le operateson de la fiche de service correspondante (--> vérifier dans le operateson de la fiche de service que toutes les données déclarées dans le getcapabilites sont renseignées dans le operateson + retirer celles qui ne le sont pas)

[All OperatesOnLinks resolve to a Metadata document.](https://jrc-geoportal-internal.geocat.live/geonetwork/srv/eng/admin.console)
Donnée renseignée dans le operateson de la fiche de service mais dont la fiche n’est pas publiée (--> publier la fiche manquante)

Pas urgent, c'est assez rapide à faire manuellement...

**Comment by vbombaerts** [comment]
Trois étapes sont nécessaires :
1. Vérifier la liste des données déclarées dans le GetCapabilities du service. --> Besoin d'un XSL qui parse le GetCap des view et download service pour créer un tableau avec le numéro de layer, le nom de la donnée, la/les fiches INSPIRE déclarées. **TODO**

2. Vérifier la correspondance des données déclarées dans le GetCap et celles déclarées dans le operatesOn de la fiche. --> https://metawal.wallonie.be/geonetwork/srv/api/pages/fre/linkchecker/content

3. Vérifier que chaque fiche de donnée est publiée --> https://metawal.wallonie.be/geonetwork/srv/api/pages/fre/linkcheckerdata/content

**Comment by vbombaerts** [comment]
Passer par une validation et/ou une suggestion dans la fiche. A discuter avec le groupe INSPIRE.

**Comment by vbombaerts** [comment]
Exemple de fiches en erreur :
https://inspire-geoportal.ec.europa.eu/sandboxconsole/srv/fre/catalog.search#/metadata/33cef608-5f5c-474f-9775-408d7f6912d8
https://inspire-geoportal.ec.europa.eu/sandboxconsole/srv/fre/catalog.search#/metadata/afe6407c-125d-4ab8-9dcc-216ac848dad1
https://inspire-geoportal.ec.europa.eu/sandboxconsole/srv/fre/catalog.search#/metadata/4fa0ae53-3173-411d-9c29-80a8b3120781
https://inspire-geoportal.ec.europa.eu/sandboxconsole/srv/fre/catalog.search#/metadata/3be632c8-80d3-460e-9122-bdefe2470d3d
https://inspire-geoportal.ec.europa.eu/sandboxconsole/srv/fre/catalog.search#/metadata/6989ee60-17ee-44da-807d-0941fe5685f5

**Comment by fxprunayre** [comment]
Quelques commentaires suite aux tests de José, les résultats avec la prochaine mise à jour et la "relaxation" de quelques règles seront mieux

![image](https://github.com/user-attachments/assets/3705de46-fd03-4dd0-969d-7ea06675300d)

mais il reste des pbs eg. :

* https://inspire-geoportal.ec.europa.eu/sandboxconsole/srv/fre/catalog.search#/metadata/6989ee60-17ee-44da-807d-0941fe5685f5 points to https://geoservices.wallonie.be/geoserver/inspire_nz/ows?service=WMS&version=1.3.0&request=GetCapabilities = 404
* https://metawal.wallonie.be/geonetwork/srv/api/records/41b5289b-da03-4632-8531-035458699881/formatters/iso19139?output=xml is not public record

**Comment by vbombaerts** [comment]
Super nouvelle. Pr quand est prévue la nouvelle màj ?
Oui il reste des problèmes. Mais si on ne doit pas perdre du temps à traquer des faux positifs alors on peut se concentrer sur la recherche des vrais problèmes.

**Comment by vbombaerts** [comment]
La mise à jour a été faite. Il ne reste que peu d'erreurs. La recherche peut se faire à la main.
Je ferme.
