### ISSUE TITLE
Registre des législations

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#851]
Pour les priority datasets INSPIRE on doit faire référence dans la fiche à la législation qui rend obligatoire la publication des données.
Il serait intéressant de le faire pour d'autres données (HVD, ITS, voire des données rendues obligatoires par des législations wallonnes).

Pour les priority datasets, un registre existe déjà https://inspire.ec.europa.eu/metadata-codelist/PriorityDataset/
Pour HVD et ITS il n'y a encore rien.

La proposition est de créer un registre qui codifie ce lien aux législations, en attendant une publication officielle. On publierait un thésaurus pour le niveau européen et un thésaurus pour le niveau wallon. 

Se baser sur wallex et sur eur-lex.

Outil [registry ](https://joinup.ec.europa.eu/collection/are3na/solution/re3gistry/about) ou thésaurus interne Metawal ?

**Comment by marceaulouis** [comment]
#873
