### ISSUE TITLE
Webcomposants : tri et résultats de recherche

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#853]
Exemple sur Limites administratives

Dans le webcomponent [https://metawal.wallonie.be/geonetwork/srv/api/pages/fre/demointranet/content](https://metawal.wallonie.be/geonetwork/srv/api/pages/fre/demointranet/content)
![image](https://github.com/SPW-DIG/metawal-core-geonetwork/assets/6093597/83432b29-c494-4473-80db-3a1c42f37433)

Directement dans Metawal
![image](https://github.com/SPW-DIG/metawal-core-geonetwork/assets/6093597/39844a0b-e1c0-4d9b-b7c9-fb141cecc23b)

**Comment by GeryNi** [comment]
La différence provient de la catalogue url utilisée dans le webcomponent spécifie une source différente (intranet-table):
 https://metawal.wallonie.be/geonetwork/intranet-table

à la place d'utiliser 
https://metawal.wallonie.be/geonetwork/

Le portail 'intranet-table' spécifiant des filtres, le nombre de résultat n'est pas le même.
`+(mw-gp-localIdentifierCodespace:BE.SPW.INFRASIG.*) +(resourceType:dataset or resourceType:series)`

![image](https://github.com/SPW-DIG/metawal-core-geonetwork/assets/78086592/906fea43-f728-4fb7-9f26-70b75dda6c5e)

**Comment by vbombaerts** [comment]
En fait le problème vient du fait que dans le webcomponent on force le classement par défaut par identifiant de donnée. On obtient bien le même nombre de résultats mais ils ne sont pas classés par score de pertinence.

**Comment by GeryNi** [comment]
Actuellement il n'est pas possible de réinitialiser le critère de tri sélectionné par l'utilisateur. 
Lorsque l'utilisateur relance une recherche il faudrait remettre le critère de tri à 'score'.

**Comment by vbombaerts** [comment]
Sera pris en charge dans la v5 des webcomposants #907
