### ISSUE TITLE
webcomposants : Problème dans les recherches sur des noms avec apostrophe

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#854]
Sur le [mapstore](https://geoportail.wallonie.be/mapstore), la recherche Escaut ne donne aucun résultat.
La recherche l'escaut renvoie bien le résultat escompté.

**Comment by GeryNi** [comment]
Après avoir regardé avec Francois,

On a trouvé que dans la définition du webcomponent, le fulltextfilter de la query était configuré sur 'default '(à la place de langfre) les appostrophes n'étant pas supportés par default le comportmeent souhaité n'était pas le bon. 

`fulltextfilter="resourceHookAbstractObject.default,` `resourceTitleObject.default"`



En utilisant 'langfre' à la place de default, les appostrophes ne sont pas pris en compte (enlevés)

`fulltextfilter="resourceHookAbstractObject.langfre,` resourceTitleObject.langfre"``

composant `demomapstore (fre)` sur: https://metawal.wallonie.be/geonetwork/srv/eng/admin.console#/settings/static-pages

**Comment by vbombaerts** [comment]
@vbombaerts doit modifier le composant du geoportail

**Comment by GeryNi** [comment]
Vérifier si c'est déjà déployé.
