### ISSUE TITLE
Différence de contenu entre le point d'accès hvd de Metawal et d'OGC API

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#857]
Point d'accès hvd Metawal - 233 fiches - https://metawal.wallonie.be/geonetwork/hvd/fre/catalog.search#/search?from=1&to=30
Point d'accès hvd OGC API records - pas de filtre pris en compte - https://metawal.wallonie.be/geonetwork/api/collections/hvd/items

Filtre défini pour le point d'accès hvd : `th_high-value-dataset-category.link : *`

**Comment by vbombaerts** [comment]
#856

**Comment by fxprunayre** [comment]
`+th_high-value-dataset-category.link:*` fonctionne. `+` permet de faire un MUST car dans OGC API record le filtre est ajouté à une requête de base cf. https://github.com/geonetwork/geonetwork-microservices/blob/main/modules/library/common-search/src/main/resources/application.yml#L6. D'ailleurs on devrait peut être supprimer indexingError `queryFilter: '+isTemplate:n AND -indexingError:true'`
