### ISSUE TITLE
Supprimer indexingError `queryFilter: '+isTemplate:n AND -indexingError:true'` de la requête pour OGC API.

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#858]
https://github.com/geonetwork/geonetwork-microservices/blob/main/modules/library/common-search/src/main/resources/application.yml#L6. D'ailleurs on devrait peut être supprimer indexingError `queryFilter: '+isTemplate:n AND -indexingError:true'`

_Originally posted by @fxprunayre in https://github.com/SPW-DIG/metawal-core-geonetwork/issues/857#issuecomment-1798345115_

**Comment by GeryNi** [comment]
Vérifer si déjà déployé (fichier de config)

**Comment by GeryNi** [comment]
Correctif déployé en TEST, VALID et PROD (temp)
