### ISSUE TITLE
Dernières publications en page d'accueil : comportement du "clic sur imagette"

### ISSUE THREAD

**Issue by metawal** [SPW-DIG/metawal-core-geonetwork#86]
Le comportement du "clic sur imagette" n'est pas idéal.

En cliquant sur l'imagette, je m'attendais à voir la donnée, le service ou l'application. Le fait d'agrandir l'imagette ne présente que peu d'intérêt.

**Comment by fxprunayre** [comment]
C'est le comportement par défaut. Les boutons liens sont là pour un accès au service, donnée, apps.

Comment choisir quel lien afficher sur le clic sur l'imagette ?
