### ISSUE TITLE
Alignement GN4.4.x

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#861]
- [x] Alignement https://github.com/SPW-DIG/metawal-core-geonetwork/tree/metawal-4.4.x
- [x] SQL migration
- [x] Documenter les changements pour le déploiement (Java 11, elasticsearch 8, check Tomcat version)

**Comment by GeryNi** [comment]
Mettre à Jour Tomcat:

- version actuelle 8.5.4
- version compatible Java 11: 10.1.x

See: https://tomcat.apache.org/whichversion.html
![image](https://github.com/SPW-DIG/metawal-core-geonetwork/assets/78086592/23b8123f-015c-4588-902d-7d6b4f0f2f74)


Tomcat 8.5 End Of Life Mars 2024: https://tomcat.apache.org/tomcat-85-eol.html

**Comment by fxprunayre** [comment]
C'est peut être l'occasion d'avoir une config plus proche de celle de GeoNetwork par défaut (pour tenter de limiter les comportements variables selon les serveurs) - Jetty, Config avec variables d'environnement cf. config avec docker https://github.com/geonetwork/docker-geonetwork/blob/main/4.4.2/docker-compose.yml#L9-L42

**Comment by vbombaerts** [comment]
Déployé.
Je ferme le ticket.
