### ISSUE TITLE
Validateur IACS

### ISSUE THREAD

**Issue by marceaulouis** [SPW-DIG/metawal-core-geonetwork#863]
Le validateur de référence INSPIRE a ajouté une catégorie AIACS
![image](https://github.com/SPW-DIG/metawal-core-geonetwork/assets/99397823/795bff49-243e-4b51-a813-621efac64e38)

Ca vaut sans doute le coup d'ajouter au validateur in-MW

Plus d'infos et exemple : https://github.com/INSPIRE-MIF/helpdesk-validator/blob/master/examples/IACS_dataset_metadata_2.0_example.xml

**Comment by fxprunayre** [comment]
Ok, donc les règles sont https://github.com/inspire-eu-validation/metadata/blob/2.0/iacs/IACS-datasets.md. Est-ce qu'on ajoute un type de validation dédié IACS comme pour monitoring ? ou est-ce qu'il y a un lien entre les 2 (eg. est ce qu'on doit toujours faire 2b+2c) ?

![image](https://github.com/SPW-DIG/metawal-core-geonetwork/assets/1701393/d9e8bc04-2f20-49e3-9258-678e80beaa44)

**Comment by fxprunayre** [comment]
Ajouter un niveau de validation 2b only et 2b+2c.
