### ISSUE TITLE
ELK sur un serveur partagé SPW ?

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#864]
On a évoqué le point lors de la dernière réunion de 2023 et le DTIC nous suggère vivement de migrer ELK sur un serveur partagé externe  à Metawal. Est-ce envisageable ? Quels avantages, quels inconvénients ?

**Comment by marceaulouis** [comment]
Conclusions de la réunion avec le DTIC du 05-02-2024 (merci Géry pour la rédaction)

Elastic Search :
•	Il s’avère que le DTIC héberge un serveur ELK afin de stocker et exposer les logs des applications.
•	Metawal utilise Elastic Search afin de remplir d’autres besoins (indexation des fiches), nos besoins en terme de gestion des versions n’est pas compatible avec le fonctionnement du DTIC (dont la version d’Elastic est imposée). 
o	Le DTIC pensait que nous utilisions Elastic Search pour y stocker les logs de notre application (c’est pourquoi ils nous auraient déconseillé cette pratique).
o	Nous devons garder le contrôle des versions Elastic Search utilisées.
