### ISSUE TITLE
Listes de valeurs DCAT-AP et Mobility DCAT-AP

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#865]
Plusieurs listes de valeurs sont imposées dans les profils d'application DCAT-AP et MobilityDCAT-AP.
J'ai essayé d'en importer qques unes dans Metawal mais sans succès. Qu'est-ce qui bloque ?
http://publications.europa.eu/resource/dataset/data-theme
https://w3id.org/mobilitydcat-ap/mobility-theme
https://w3id.org/mobilitydcat-ap/georeferencing-method/
https://w3id.org/mobilitydcat-ap/network-coverage
https://w3id.org/mobilitydcat-ap/transport-mode
https://w3id.org/mobilitydcat-ap/intended-information-service

**Comment by fxprunayre** [comment]
Pour les thèmes le fichier SKOS https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/data-theme peut être importé mais ne contient pas une balise connue (par GN) pour le titre du thésaurus qui utilise alors le nom du fichier. On peut remplacer `at:prefLabel` par `dc:title` dans le fichier avant import.

![image](https://github.com/SPW-DIG/metawal-core-geonetwork/assets/1701393/800a51ef-82c5-45a0-8197-0cb1f3623304)


Pour les autres, dans la page HTML on a
![image](https://github.com/SPW-DIG/metawal-core-geonetwork/assets/1701393/f5ee1c12-4b69-4f17-9811-8a04d3fb9e42)

Le format RDF est une ontologie avec des concepts encodés de la manière suivante
```xml
    <owl:NamedIndividual rdf:about="https://w3id.org/mobilitydcat-ap/transport-mode/taxi">
        <rdf:type rdf:resource="http://www.w3.org/2004/02/skos/core#Concept"/>
        <skos:inScheme rdf:resource="https://w3id.org/mobilitydcat-ap/transport-mode"/>
        <skos:prefLabel xml:lang="en">Taxi</skos:prefLabel>
        <skos:topConceptOf rdf:resource="https://w3id.org/mobilitydcat-ap/transport-mode"/>
    </owl:NamedIndividual>
```
On pourrait imaginer faire une conversion OWL > SKOS avant import pour gérer ce cas ?

**Comment by fxprunayre** [comment]
Cf. 
Thesaurus / Improve support of EU publication office SKOS format https://github.com/geonetwork/core-geonetwork/pull/7673
Thesaurus / Add support for thesaurus described using OWL format https://github.com/geonetwork/core-geonetwork/pull/7674
