### ISSUE TITLE
Erreur d'édition fiche IACS

### ISSUE THREAD

**Issue by marceaulouis** [SPW-DIG/metawal-core-geonetwork#868]
J'ai dû faire une erreur quelque part, je ne peux pas éditer la fiche test IACS 
414cdf16-c697-4244-8f63-0ad6f1770400

https://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/414cdf16-c697-4244-8f63-0ad6f1770400

Elle s'affiche mais j'ai l'erreur suivante lorsque j'active l'édition ;

![image](https://github.com/SPW-DIG/metawal-core-geonetwork/assets/99397823/5e9d9955-ba1f-4bc1-8b17-692c88505827)

J'ai essayé de la ré-importer mais ça n'a rien changé évidemment

**Comment by fxprunayre** [comment]
Dans la console, l'erreur est

```json
{
    "message": "XPathException",
    "code": "runtime_exception",
    "description": "A sequence of more than one item is not allowed as the value of variable $thesaurusConfig (<thesaurus/>, <thesaurus/>) "
}
```

J'aurai tendance à dire c'est lié au fait que tu as 2 fois le même thésaurus

![image](https://github.com/SPW-DIG/metawal-core-geonetwork/assets/1701393/d58275a8-ca46-447f-acc7-c2fe247c7efb)


? Tentes d'en supprimer un ?

**Comment by marceaulouis** [comment]
C'est ça, merci !
