### ISSUE TITLE
Edition metadonnée, taille de la fenêtre

### ISSUE THREAD

**Issue by metawaltest** [SPW-DIG/metawal-core-geonetwork#87]
Si on diminue la taille de la fenêtre, pas moyen d'avoir les flèches de défilement pour parcourir la page, c'est utile si on a besoin d'avoir plusieurs fenêtres ouvertes en même temps.

**Comment by fxprunayre** [comment]
C'est "volontaire". Pour éditer 2 fiches, il est nécessaire pour le moment d'ouvrir 2 onglets du navigateur.

**Comment by fxprunayre** [comment]
Dans metawal 4 une édition sera faite dans un onglet. Pour plusieurs fiches, il faudra ouvrir plusieurs onglets.
