### ISSUE TITLE
INSPIRE : Format Date publication GEMET Theme iso-19139

### ISSUE THREAD

**Issue by marceaulouis** [SPW-DIG/metawal-core-geonetwork#870]
On a reçu les résultats du harvest INSPIRE et ils ne sont pas bon

Côté fiches de service, la moitié n'est pas conforme à cause d'un format de date de publication du thesaurus GEMET Theme :

Pour les fiches qui sont passées, en ISO 19139, la date est sous format <gco:Date>2009-09-22</gco:Date>
ex : https://metawal.wallonie.be/geonetwork/inspire/fre/csw?REQUEST=GetRecordById&SERVICE=CSW&version=2.0.2&elementSetName=full&outputSchema=http://www.isotc211.org/2005/gmd&id=2e482001-3f0c-481e-b9ec-316a0f206a58

Pour les fiches non conformes, le format passe en <gco:DateTime>Fry Sep 22 07:57:15 CEST 2009</gco:DateTime>
ex : https://metawal.wallonie.be/geonetwork/inspire/fre/csw?REQUEST=GetRecordById&SERVICE=CSW&version=2.0.2&elementSetName=full&outputSchema=http://www.isotc211.org/2005/gmd&id=9aa59897-95aa-4bef-9976-e00ad9e7b4a9

Ce format ne plait pas au validateur. Est-ce que vous avez une idée de l'origine de cette différence de résultat (date de création de la fiche, certaines doivent dater de pas mal de temps) ? En ISO 19115 je ne vois pas de différence de format

Merci !

**Comment by marceaulouis** [comment]
Edit : rouvrir une édition d'une fiche corrige l'erreur donc c'est pas majeur, mais ça vous intéresse p-e de connaître ce point. Je laisse cette fiche en exemple :

0aa26e4e-4e10-4986-a433-986c2d247669

**Comment by fxprunayre** [comment]
On devrait corriger la date dans le thésaurus https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.2.3/web/src/main/webapp/WEB-INF/data/config/codelist/external/thesauri/theme/gemet-theme.rdf#L13

Dans GN, on a sans doute fait une modif pour vérifier le format de la date quand on charge les thésaurus ce qui expliquerait le changement. Quand tu sauves l'éditeur, il y a mise à jour et sauvegarde de chaque bloc de mot clés.
