### ISSUE TITLE
Thesaurus Legislation HVD

### ISSUE THREAD

**Issue by marceaulouis** [SPW-DIG/metawal-core-geonetwork#873]
le DCAT HVD demande qu'on indique la législation qui prescrit la création et la diffusion d'une donnée à forte valeur, avec l'ELI en ancre.

Dans ce sens, j'ai créé un thesaurus que je remplirai au fur et à mesure de l'encodage des fiches HVD. Selon les infos de Dominique, l'Europe ne va pas créer de registre de son côté

![image](https://github.com/SPW-DIG/metawal-core-geonetwork/assets/99397823/243a3913-5356-4828-863a-2a5019127e8a)

Est-ce que l'approche vous semble correcte ? Ca vous permet de faire le mapping vers cet élément en DCAT HVD ? Il faudrait sans doute que l'ancre se retrouve dans le DCAT

**Comment by fxprunayre** [comment]
C'est ce qu'on fait pour priority dataset donc ça semble bien. Par contre, si la Commission ne fait pas de registre, peut être que l'on peut en créer un "GeoNetwork" que l'on puisse l'utiliser pour tous les utilisateurs voulant encoder des données dans le contexte HVD, d'autant plus que la conversion DCAT contiendra une référence à ce thésaurus - Donc, le publier sur github GN sans référence à metawal dans le namespace.

**Comment by marceaulouis** [comment]
Ca me semble une excellente idée. Tant qu'on peut le compléter facilement car je n'aurai pas toutes les entrées en une fois je pense

**Comment by fxprunayre** [comment]
J'ai repris le thésaurus avec quelques modifs

https://github.com/SPW-DIG/metawal-core-geonetwork/blob/dcat/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/eu-dcat-ap-hvd/vocabularies/high-value-dataset-applicable-legislation.rdf

* en/fr
* ajout des descriptions
* changement de l'id du thesaurus

**Comment by marceaulouis** [comment]
Questions de la part de Dominique :

```xml
<gmd:descriptiveKeywords>
<gmd:MD_Keywords>
                <gmd:keyword>
                               <gco:CharacterString>2023/138</gco:CharacterString>
                </gmd:keyword>
                <gmd:type>
                               <gmd:MD_KeywordTypeCode codeList=http://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#MD_KeywordTypeCode codeListValue="theme"/>
                </gmd:type>
                <gmd:thesaurusName>
                               <gmd:CI_Citation>
                                               <gmd:title>
                                                               <gmx:Anchor xlink:href=http://data.europa.eu/r5r/applicableLegislation>High-value dataset applicable legislations</gmx:Anchor>

                                                               ## popurquoi pointer sur r5r et pas directement sur http://data.europa.eu/eli/reg_impl/2023/138/oj

                                               </gmd:title>
                                               <gmd:date>
                                                               <gmd:CI_Date>
                                                                               <gmd:date>
                                                                               <gco:Date>2024-04-18</gco:Date>
                                                                               </gmd:date>
                                                                               <gmd:dateType>
                                                                                              <gmd:CI_DateTypeCode codeList=http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode codeListValue="publication">publication</gmd:CI_DateTypeCode>
                                                                               </gmd:dateType>
                                                               </gmd:CI_Date>
                                               </gmd:date>
                               </gmd:CI_Citation>
                </gmd:thesaurusName>
</gmd:MD_Keywords>
</gmd:descriptiveKeywords>
```

##pourquoi pas l'approche (DK je pense) cf https://github.com/INSPIRE-MIF/hvd-inspire/issues/3gmd:descriptiveKeywords

```xml
gmd:MD_Keywords
gmd:keyword
<gmx:Anchor xlink:href=https://eur-lex.europa.eu/eli/dir/2007/2/2019-06-26>INSPIRE</gmx:Anchor>
</gmd:keyword>
gmd:keyword
<gmx:Anchor xlink:href=https://eur-lex.europa.eu/eli/reg_impl/2023/138/oj>Høj-værdi datasæt</gmx:Anchor>
</gmd:keyword>
...
gmd:thesaurusName
gmd:CI_Citation
gmd:title
<gmx:Anchor xlink:href=https://registry.geonetwork-opensource.org/theme/eu>EU legislation</gmx:Anchor>
</gmd:title>
...
</gmd:thesaurusName>
</gmd:MD_Keywords>
</gmd:descriptiveKeywords>
```

**Comment by fxprunayre** [comment]
C'est ce qu'on a fait, non ?

Pour l'anchor sur le thésaurus, le mieux serait d'avoir un vocabulaire de la Commission. Vu qu'il n'existe pas (?), pour l'instant on a créé un thésaurus pointant vers http://data.europa.eu/r5r/applicableLegislation (qui est la propriété que l'on veut encoder). On peut changer pour pointer vers le réglement http://data.europa.eu/eli/reg_impl/2023/138/oj mais c'est pas forcément plus précis. https://registry.geonetwork-opensource.org/theme/eu de l'autre exemple est sans doute moins bien.

Pour le thésaurus, on a 
https://github.com/geonetwork/core-geonetwork/pull/7600/files#diff-e4e676d2d634b18949a99a8c2fb5a9f312b9c0150085e07c0df002bed74e8932 et https://github.com/SPW-DIG/metawal-core-geonetwork/blob/dcat/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/eu-dcat-ap-hvd/vocabularies/high-value-dataset-applicable-legislation.rdf
A voire si on peut pas créer une liste multilingues qui conviendrait à tous le monde.

Si l'encodage en ISO est fait de manière homogène, ça facilitera le mapping vers DCAT par la suite.
