### ISSUE TITLE
Ajout suggestions complétion fiches

### ISSUE THREAD

**Issue by marceaulouis** [SPW-DIG/metawal-core-geonetwork#874]
Serait-il possible de préparer deux nouvelles suggestions pour la complétion "automatique" des fiches (du même ordre que l'ajout des services WMS etc.) :

- Ajout d'un atom feed dont l'adresse sera https://geoservices.wallonie.be/geotraitement/spwdatadownload/get/mduuid/atom_service.xml

protocole : atom:feed
nom : Service de téléchargement ATOM Feed
description : Ce service de téléchargement ATOM Feed permet de télécharger la série de couches de données "*cf service REST"
fonction : téléchargement

- Ajout d'un lien de téléchargement direct dont l'adresse sera https://geodata.wallonie.be/dataset/mduuid
(Lien édité le 15/04, il y avait une coquille)

protocole : www:link
nom : Page de téléchargement des données
description : Page à partir de laquelle vous avez accès au téléchargement direct de la donnée
fonction : téléchargement

Ex de fiche avec ces deux ressources :
https://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/80a837d8-2c0b-4f77-b5d5-824e9780a4ae

**Comment by fxprunayre** [comment]
@marceaulouis , est ce qu'on mettrait pas `WWW:DOWNLOAD` pour page de téléchargement ?

**Comment by fxprunayre** [comment]
![image](https://github.com/SPW-DIG/metawal-core-geonetwork/assets/1701393/e0ed63f6-1330-4665-a8af-db532bcd3b1d)

![image](https://github.com/SPW-DIG/metawal-core-geonetwork/assets/1701393/880f7506-dbb4-46c7-9669-4a53236a783f)

Je n'ai pas fait ça sous forme de suggestion car on veut juste ajouter un élément qui n'est pas dans la fiche.
Dans les suggestions en général, on détecte quelquechose et on suggère un complément.

**Comment by marceaulouis** [comment]
Ok pour l'Atom
Pour le lien direct, il y a une coquille dans l'adresse : geo*A*data
(c'est de ma faute, j'avais corrigé le post plus tard mais passé inaperçu)

**Comment by fxprunayre** [comment]
Fixed. A redéployer
