### ISSUE TITLE
Requête portail environnement

### ISSUE THREAD

**Issue by marceaulouis** [SPW-DIG/metawal-core-geonetwork#878]
Je continue de démontrer mon incompétence avec la question suivante.

Le SPW ARNE veut faire un nouveau portail environnement et j'ai été contacté par le gestionnaire de projet qui souhaiterait une requête afin d'avoir les fiches de leur direction en json.
On pourrait se baser sur le gestionnaire "SPW - Agriculture, Ressources naturelles et Environnement" mais je n'ai jamais utilisé l'API (shame) Je poserai la question mais seules les fiches de série et data sont nécessaires (pas services)

**Comment by fxprunayre** [comment]
Donc, on fait la recherche qui correspond avec les facettes

https://metawal.wallonie.be/geonetwork/srv/eng/catalog.search#/search?query_string=%7B%22custodianOrgForResource_tree%22:%7B%22SPW%20-%20Agriculture,%20Ressources%20naturelles%20et%20Environnement%22:true%7D,%22resourceType%22:%7B%22service%22:false%7D%7D

On fait l'équivalent avec une requête avec la syntaxe Elasticsearch équivalente pour le portal

`+custodianOrgForResource_tree:"SPW - Agriculture, Ressources naturelles et Environnement" -resourceType:service`

Que l'on peut tester avec 
https://metawal.wallonie.be/geonetwork/srv/eng/catalog.search#/search?any=q(%2BcustodianOrgForResource_tree:%22SPW%20-%20Agriculture,%20Ressources%20naturelles%20et%20Environnement%22%20-resourceType:service)

Et ensuite, il faut créer le portail avec cette requête. A tester @marceaulouis

**Comment by marceaulouis** [comment]
Merci
L'utilisation du terme "portail" était sans doute mal choisie. Ils veulent recréer un géoportail à leur sauce et veulent donc avoir accès aux fiches en json via l'API

**Comment by fxprunayre** [comment]
Dans ce cas, il faut regarder les appels vers le service `_search`. Si tu leur fais un portail, il n'auront aucun paramètre à mettre pour récupérer les fiches.

**Comment by marceaulouis** [comment]
J'ai fermé avant d'avoir la réponse du gestionnaire du projet

Est-ce qu'il y a quelque chose à faire niveau gestion des accès ? il semble qu'il ait un accès refusé à l'API
J'ai envoyé ceci https://metawal.wallonie.be/geonetwork/dgarne/api/search/records/_search?bucket=s101

**Comment by fxprunayre** [comment]
> Est-ce qu'il y a quelque chose à faire niveau gestion des accès ? il semble qu'il ait un accès refusé à l'API

A priori quelquechose comme ça fonctionne bien ?

```bash
curl 'https://metawal.wallonie.be/geonetwork/dgarne/api/search/records/_search' \
  -H 'Content-Type: application/json;charset=UTF-8' \
  --data-raw $'{"from":0,"size":1}'
```

Il y a aussi des exemples ici https://docs.geonetwork-opensource.org/4.2/api/the-geonetwork-api/#loop-on-search-results-and-apply-changes-processing-and-batch-editing
