### ISSUE TITLE
Thesaurus Gemet : ancres pour IACS

### ISSUE THREAD

**Issue by marceaulouis** [SPW-DIG/metawal-core-geonetwork#886]
Pour la validation IACS, il est nécessaire que les mots clefs gemet (https://www.eionet.europa.eu/gemet/en/groups/) soient encodés avec des ancres.

![image](https://github.com/SPW-DIG/metawal-core-geonetwork/assets/99397823/b3227c3e-1dcb-4379-9148-fb8e64214291)

**Comment by fxprunayre** [comment]
L'éditeur peut être configuré pour encoder en mode `Anchor`

```xml
        <thesaurus key="external.theme.gemet-theme" transformations="to-iso19115-3.2018-keyword-with-anchor"/>
```

cependant il ne change pas l'encodage d'une fiche existante. 
Ca semble mieux de forcer l'encodage si la configuration de l'éditeur définit un encodage particulier pour un thésaurus.

**Comment by fxprunayre** [comment]
En discutant avec José, on se dit qu'on devrait peut être par défaut encoder avec des `Anchor`. Ca te convient @marceaulouis si on encode tous les mots clés avec des `Anchor` ? On pourra aussi configurer pour un encodage en mode texte pour un thésaurus en particulier si besoin.

**Comment by marceaulouis** [comment]
Ca me semble une bonne idée, la question se pose régulièrement ces derniers temps

**Comment by fxprunayre** [comment]
A déployer et tester. Donc on édite une fiche, on sauve, tous les mots clés issus d'un thésaurus seront sous forme d'anchor
