### ISSUE TITLE
Webcomponent Portail ARNE

### ISSUE THREAD

**Issue by marceaulouis** [SPW-DIG/metawal-core-geonetwork#887]
Pour le portail Environnement, nous avons proposé de créer un webcomponent reprenant les fiches ARNE et les attributs suivants 👍 

- [x] Imagette
- [x] Recherche
- [x] Titre
- [x] Résumé
- [x] Lien Géoportail (eg. https://geoportail.wallonie.be/catalogue/{uuid}.html)
- [ ] Date de mise à jour : triable ??
- [x] Filtres (mots clés)

J'ai créé le test suivant en valid : https://metawal4.valid.wallonie.be/geonetwork/srv/api/pages/fre/PortailEnvi/content

Est-il possible de pointer vers le geoportail plutot que MW ?
Comment gérer le format des dates pour avoir qqch de plus user friendly ?
+ peut-on mettre la même logique que d'habitude "si revision n'existe pas --> creation" ?
+ Peut-on trier ces dates ?

**Comment by vbombaerts** [comment]
Pour le lien Géoportail --> ajouter une entrée dans l'index. Attention ! N'existe que si la fiche est publiée.
Pour la date de mise à jour. Soit on encode systématiquement une date de mise à jour = date de création si la donnée n'a jamais été mise à jour (éventuellement avec un process qu'on peut lancer sur base régulière), soit on ajoute une entrée dans l'index qui stocke le résultat du calcul.

**Comment by GeryNi** [comment]
Lien géoportail: https://metawal.test.wallonie.be/geonetwork/srv/api/pages/fre/PortailEnvi/content

Déployé sur nouvel environnement TEST

**Comment by marceaulouis** [comment]
Je relance ce point parce que le SPW ARNE a avancé sur son portail
[Cartographie - L'Environnement en Wallonie](https://environnement-temp.wallonie.be/home/cartographie.html)

Je ne sais plus ce qu'on avait dit pour les résumé qui se transforment en lien commençant par "https://metawal.test.wallonie.be/geonetwork/srv/api/pages/fre/PortailEnvi/" et pour la date (cf réponse de Vincent)

**Comment by fxprunayre** [comment]
> Pour la date de mise à jour. Soit on encode systématiquement une date de mise à jour = date de création si la donnée n'a jamais été mise à jour (éventuellement avec un process qu'on peut lancer sur base régulière), soit on ajoute une entrée dans l'index qui stocke le résultat du calcul.

Ou bien on teste https://www.elastic.co/guide/en/elasticsearch/reference/current/sort-search-results.html#script-based-sorting

**Comment by marceaulouis** [comment]
On a maintenant une deadline pour le 4 novembre

J'ai repris la page en prod et c'est pas mal https://metawal.wallonie.be/geonetwork/srv/api/pages/fre/PortailEnvi/content

il reste la question de la date :

- [ ] Avoir un format de date dd/mm/yyyy

Si possible d'ici là :

- [ ] calcul dynamique du plus récent entre Création et Révision (si révision n'existe pas)
- [ ] bonus : tri par défaut sur la date : plus récente d'abord
