### ISSUE TITLE
console admin / import MEF ne fonctionne pas

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#89]
Testé sur l'Import de deux fiches ID 442 et ID 380 de metawal.wallonie.be

![image 624](https://f.cloud.github.com/assets/6093597/1663543/63a272c6-5c16-11e3-9672-c45b915411d0.png)

**Comment by fxprunayre** [comment]
![image](https://f.cloud.github.com/assets/1701393/1748324/4e834c58-64b3-11e3-8226-e4c1e8f16175.png)

Le pb vient de la version actuelle de metawal qui ne convertie par la fiche en iso19139. Les 2 fichiers metadata.xml et metadata.iso19139.xml du ZIP sont les mêmes (et utilise un namespace inconnu pour la version à venir de metawal). L'import est donc impossible.
