### ISSUE TITLE
Impossible de modifier la configuration de l'interface

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#890]
J'ai créé un nouveau point d'accès NAPITS en test.
J'ai créé ensuite une config d'interface pour ce point d'accès.
J'ai édité la config du point d'accès pour pointer vers la nouvelle config d'interface.
Impossible d'enregistrer (bouton désactivé)

![image](https://github.com/SPW-DIG/metawal-core-geonetwork/assets/6093597/570c29af-f21b-441a-a636-65b30e103c03)

**Comment by fxprunayre** [comment]
Workaround: tu peux faire un changement d'identifiant ou de filtre (ajout/suppression d'une lettre) pour invalider le formulaire et le bouton sera actif. Il y a en effet un problème quand on change le champ config d'interface qui ne déclenche pas le changement d'état du formulaire.

**Comment by fxprunayre** [comment]
https://github.com/geonetwork/core-geonetwork/pull/8222

A déployer @GeryNi

**Comment by GeryNi** [comment]
> [geonetwork#8222](https://github.com/geonetwork/core-geonetwork/pull/8222)
> 
> A déployer @GeryNi

Déployé

**Comment by GeryNi** [comment]
testé - semble bon en TEST.
