### ISSUE TITLE
Impossible de charger une imagette

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#891]
En environnement de test, en édition sur la fiche https://metawal.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/2ba9b450-d2bb-46b2-87f9-949f0f7d7c37 impossible de charger une imagette
![image](https://github.com/SPW-DIG/metawal-core-geonetwork/assets/6093597/b2040591-4954-459e-8c35-4c7447d6483a)

Par ailleurs, je ne trouve pas l'accès au store des documents chargés sur la fiche (imagette, pdf...)

**Comment by GeryNi** [comment]
Après investigation avec Francois,

problème rencontré avec l'instance TEST: 2024-07-01T10:06:51,758 ERROR [geonetwork] - Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: it/geosolutions/imageio/stream/input/FileImageInputStreamExtImpl

Semble lié au chargement de la librairie  (JAR: web/target/geonetwork/WEB-INF/lib/imageio-ext-streams-1.4.7.jar)

Cause possible: https://github.com/haraldk/TwelveMonkeys#deploying-the-plugins-in-a-web-app

Pas de certitude sur pourquoi cela ne donctionne pas sur l'instance TEST.

L'upload d'imagette fonctionne en local: 
![image](https://github.com/SPW-DIG/metawal-core-geonetwork/assets/78086592/8eaf2509-4c4a-4132-bfcc-70aa27456d94)

**Comment by GeryNi** [comment]
Après redéploiement, le problème semble avoir disparu. Pourtant aucun correctif en lien avec le problème.

**Comment by vbombaerts** [comment]
> Par ailleurs, je ne trouve pas l'accès au store des documents chargés sur la fiche (imagette, pdf...)

Possible via "Ajouter un téléchargement" 
![image](https://github.com/SPW-DIG/metawal-core-geonetwork/assets/6093597/6d445b69-37f0-48b1-abd7-7199d27cd06c)
