### ISSUE TITLE
MobilityDCAT-AP thesaurus

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#893]
L'enregistrement des mots-clés issus des thésaurus spécifiques mobilityDCAT ne se fait pas.
Fiche : https://metawal.test.wallonie.be/geonetwork/srv/eng/catalog.search#/metadata/2ba9b450-d2bb-46b2-87f9-949f0f7d7c37

Manip :
- basculer vers l'anglais parce que les thésaurus ne sont pas dispo en français
- ajout des mots-clé depuis les thésaurus mobility theme ou transport mode
- Enregistrement

Les mots-clés ne sont pas enregistrés dans la fiche. Le thésaurus est bien ajouté

**Comment by fxprunayre** [comment]
Oui actuellement, on ajoute les mots clés dans la fiche que s'ils sont disponibles dans la langue de la fiche.
Pour HVD on a toujours les mots clés en français.

Je peux regarder pour enlever cette contrainte et du coup mettre l'anglais si pas de français ?

**Comment by fxprunayre** [comment]
@GeryNi tu peux mettre à jour test ? avec https://github.com/SPW-DIG/metawal-core-geonetwork/commit/127d63bbc59aa4734c37706a0a562f26cd52d1c3 Merci.

**Comment by GeryNi** [comment]
> @GeryNi tu peux mettre à jour test ? avec [127d63b](https://github.com/SPW-DIG/metawal-core-geonetwork/commit/127d63bbc59aa4734c37706a0a562f26cd52d1c3) Merci.

Voilà, c'est déployé en TEST.

**Comment by vbombaerts** [comment]
Super.
