### ISSUE TITLE
Valid : Affichage fiches de service liées

### ISSUE THREAD

**Issue by marceaulouis** [SPW-DIG/metawal-core-geonetwork#898]
Je ne sais pas si c'est une feature qu'on a enlevé, qu'on doit activer dans les paramètres ou si c'est un bug, mais les liens entre les fiches de service n'apparaissent plus en valid (test non plus)

ex : 
Valid 
![image](https://github.com/user-attachments/assets/fc1b6397-15ed-4150-aaaf-f750e0d2f4f0)

Prod
![image](https://github.com/user-attachments/assets/0b381d31-1fc6-4227-ade1-2e25a19ac3d0)

Valid 
![image](https://github.com/user-attachments/assets/4c330340-0219-4935-9152-013b54008efa)

Prod
![image](https://github.com/user-attachments/assets/d6231411-8586-41ef-9203-c99668bf19b6)

**Comment by fxprunayre** [comment]
exemple de fiche https://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/d594f5a3-34ac-4cc2-a357-aae5d5263f35

**Comment by fxprunayre** [comment]
Test
http://localhost:9200/mw-records/_doc/d6cc841c-d6ea-40cc-b43e-8ac6366f7a9a ne contient pas de champ `recordOperateOn` donc on a un problème d'indexation.

En lien avec https://github.com/geonetwork/core-geonetwork/pull/7806

@GeryNi  Migration SQL à appliquer 
```sql
UPDATE Metadata 
SET data = replace(data, 'http://standards.iso.org/iso/19115/-3/srv/2.1', 'http://standards.iso.org/iso/19115/-3/srv/2.0') 
WHERE data LIKE '%http://standards.iso.org/iso/19115/-3/srv/2.1%' 
AND schemaId = 'iso19115-3.2018';
```

Ajouté au script https://github.com/SPW-DIG/metawal-core-geonetwork/commit/8628bc40a6f539f52ae78480e0ad5aeac809513f

**Comment by GeryNi** [comment]
Merci Francois pour l'explication, je m'en occupe demain matin.

**Comment by GeryNi** [comment]
Je viens d'appliquer le script en TEST, le résultat semble bon. 
@marceaulouis pourrais tu me confirmer ?

Si oui, j'en verrai un mail à Didier pour appliquer le script en VALID.

**Comment by marceaulouis** [comment]
Merci ! Ca a l'air ok oui

Par contre toute une série de fiches ont de nouveau disparues suite à des problèmes d'indexation, je ne sais pas si c'est toujours lié au ticket #880 

exemple de fiche en erreur : https://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/5433bdca-0fbc-428d-ad1b-4942fc7e7731

**Comment by GeryNi** [comment]
Marceau,

Merci pour l'information, en effet il s'agit du même problème. Difficile de comprendre ce qui a causé cela (duplication d'un élément), cela se produit lorsque j'utilise 'Reindex' à la place de 'Delete index and reindex'.
J'ai appliqué la requête SQL corrective en TEST, apres indexation cela me semble bon.

**Comment by marceaulouis** [comment]
parfait en test du coup, merci

**Comment by vbombaerts** [comment]
N'a pas été corrigé en prod-temp

**Comment by GeryNi** [comment]
@vbombaerts , j'ai réindexé les données cela me semble correct maintenant.
Il s'agit certainement d'un oubli, le script sql avait été exécuté mais les données pas réindexées.

Peux tu me confirmer que c'est ok afin de cloturer le ticket ? 

Prod temp:
![image](https://github.com/user-attachments/assets/06c753da-dc0b-4d16-88b3-21aec1f7f279)
