### ISSUE TITLE
Réponse API Metawal différente en prod-temp

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#899]
La réponse API est différente sur Metawal-temp que sur les autres instances : test, valid et prod.

Par exemple pour l'élement "geom", la prod-temp renvoie un array alors que la prod renvoie une seule valeur.

Testé avec la query 
```
{
  "query": {
    "match": {
      "uuid": "b795de68-726c-4bdf-a62a-a42686aa5b6f"
    }
  }
}
```
sur swagger.

Réponse en prod
```
"geom": {
            "type": "Polygon",
            "coordinates": [
              [
                [
                  2.70157,
                  49.441506
                ],
                [
                  6.56349,
                  49.441506
                ],
                [
                  6.56349,
                  50.857575
                ],
                [
                  2.70157,
                  50.857575
                ],
                [
                  2.70157,
                  49.441506
                ]
              ]
            ]
          },
```

Réponse en prod-temp 

```
"geom": [
            {
              "type": "Polygon",
              "coordinates": [
                [
                  [
                    2.70157,
                    49.441506
                  ],
                  [
                    6.56349,
                    49.441506
                  ],
                  [
                    6.56349,
                    50.857575
                  ],
                  [
                    2.70157,
                    50.857575
                  ],
                  [
                    2.70157,
                    49.441506
                  ]
                ]
              ]
            }
          ],
```

L'interface swagger présente qques différences au niveau de l'endroit où on doit indiquer la requête.

En prod
![image](https://github.com/user-attachments/assets/1c5fde81-2f66-4931-9eca-4a8d317cfb10)

En prod-tmp 
![image](https://github.com/user-attachments/assets/573aff33-e5d9-4f30-9fe8-4771d4460c38)

Y a-t-il une différence dans la version de l'API entre les deux instances ?

**Comment by fxprunayre** [comment]
Les changements d'API sont suivis avec le label API change https://github.com/geonetwork/core-geonetwork/pulls?q=is%3Apr+label%3A%22api+change%22+is%3Aclosed+
Ian, au Canada, a fait pas mal de corrections mineures pour améliorer la conformité de la spec OpenApi et éviter des erreurs quand on convertit la spec en client. Le 2ème point est en lien avec ces changements. 

Pour le champ `geom`, avant le champ pouvait être soit un objet soit un tableau d'objet (multi-emprise). Maintenant, c'est systématiquement un tableau.

**Comment by vbombaerts** [comment]
Adapté côté GP
