### ISSUE TITLE
Réponse CSW Metawal-temp différente de Metawal actuel 

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#900]
Metawal-temp ajoute des infos à la réponse CSW. J'ai repéré des modifs au niveau 

## Pour les données
- Ajout d'informations sur les fiches liées
```
<!--Added from https://metawal-temp.wallonie.be/geonetwork/srv/api/records/09df07cb-d97a-402c-bf5d-2f632ffdf82a/related?type=associated&type=brothersAndSisters-->
          <gmd:aggregationInfo>
            <gmd:MD_AggregateInformation>
              <gmd:aggregateDataSetIdentifier>
                <gmd:MD_Identifier>
                  <gmd:code>
                    <gco:CharacterString>68cfc9ff-651a-4757-b792-6bde0e238c2f</gco:CharacterString>
                  </gmd:code>
                </gmd:MD_Identifier>
              </gmd:aggregateDataSetIdentifier>
              <gmd:associationType>
                <gmd:DS_AssociationTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#DS_AssociationTypeCode" codeListValue="crossReference" />
              </gmd:associationType>
            </gmd:MD_AggregateInformation>
          </gmd:aggregationInfo>
```

- Modifications de balises
`<gmd:MD_Scope>` qui devient `<gmd:DQ_Scope`

## Pour les services
- Modifications de balises
`<srv:extent>` devient `<gmd:extent>`
`<srv:DCP>` devient `<srv:distributedComputingPlatform>`
En **iso 19139**, il y a aussi des **différence au niveau des éléments spécifiques aux services** : `couplingType`, `containsOperation`, `connectPoint` , etc qui n'apparaissent plus dans la nouvelle version de Metawal.

**Les différences existent si on demande une réponse en schema `OUTPUTSCHEMA=mw` ou `OUTPUTSCHEMA=http://www.isotc211.org/2005/gmd`
Pas de différence dans le schema `OUTPUTSCHEMA=http://standards.iso.org/iso/19115/-3/mdb/2.0`**

Je n'ai pas fait un test exhaustif mais j'ai samplé quelques fiches

- [ ] Voir les conséquences que ça peut avoir sur le Géoportail --> en attente d'infos de la part de l'équipe GP.
- [ ] Voir aussi pour INSPIRE --> repasser le validateur.

**Comment by fxprunayre** [comment]
> Ajout d'informations sur les fiches liées

Pour ajouter ces info, l'application appel l'API
https://metawal-temp.wallonie.be/geonetwork/srv/api/records/09df07cb-d97a-402c-bf5d-2f632ffdf82a/related?type=associated&type=brothersAndSisters
et ajoute les info dans la réponse.

Si c'est absent, j'aurai tendance à dire que le serveur n'a pas accès à lui même avec son nom de domaine ?
@GeryNi, est ce qu'on peut tester sur le serveur un appel à 
```
curl https://metawal-temp.wallonie.be/geonetwork/srv/api/records/09df07cb-d97a-402c-bf5d-2f632ffdf82a/related?type=associated&type=brothersAndSisters
``` 
?


> Modifications de balises
<gmd:MD_Scope> qui devient <gmd:DQ_Scope

cf. ttps://github.com/geonetwork/core-geonetwork/issues/8220


> Pour les services


un exemple
```bash
UUID=13fd1f75-ed5b-4a8a-a71b-1d83bc62cc4c
diff <(curl "https://metawal-temp.wallonie.be/geonetwork/srv/fre/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetRecordById&ID=$UUID&outputSchema=mw") <(curl "https://metawal.wallonie.be/geonetwork/srv/fre/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetRecordById&ID=$UUID&outputSchema=mw")
```


`srv:extent` est correct en ISO19139 cf. https://github.com/geonetwork/core-geonetwork/blob/main/schemas/iso19139/src/main/plugin/iso19139/schema2007/srv/serviceMetadata.xsd#L90

Le problème vient du namespace
eg. https://metawal-temp.wallonie.be/geonetwork/srv/api/records/13fd1f75-ed5b-4a8a-a71b-1d83bc62cc4c/formatters/xml
![image](https://github.com/user-attachments/assets/966eca75-70b5-477e-8dc1-91d0d7f11905)

Il faut appliquer le SQL qui corrige la version du namespace pour `srv` (et reindexer)... et c'est sans doute à l'origine des autres problèmes pour `srv:*`

**Comment by vbombaerts** [comment]
Le géoportail en prod interroge Metawal en CSW au schema mw.

Conséquences des modifs sur le géoportail.

1. `<gmd:MD_Scope>` qui devient `<gmd:DQ_Scope>` - l'élément n'est pas utilisé dans le géoportail ==> **OK**
2. `<srv:DCP>` qui devient `<srv:distributedComputingPlatform>` - l'élément n'est pas utilisé dans le géoportail ==> **OK**
3. balises `<srv:*>` ==> **en attente du correctif côté Metawal**
4. Fiches liées. Le Géoportail va déjà les compléter en cherchant dans la BD interne Jahia ==> **Risque de doublons, à tester une fois le correctif Metawal déployé**

**Comment by vbombaerts** [comment]
Malgré le déploiement du correctif, il y a toujours des différences CSW sur le schema `mw`

**prod** : 
https://metawal.wallonie.be/geonetwork/geoportailwal/fre/csw?REQUEST=GetRecordById&ID=65486d9a-dd9b-442f-b291-c20c42e5ec18&SERVICE=CSW&VERSION=2.0.2&OUTPUTSCHEMA=mw&CONSTRAINTLANGUAGE=CQL_TEXT&RESULTTYPE=results&TYPENAMES=csw:Record&ELEMENTSETNAME=full

**prod-temp** : 
https://metawal-temp.wallonie.be/geonetwork/geoportailwal/fre/csw?REQUEST=GetRecordById&ID=65486d9a-dd9b-442f-b291-c20c42e5ec18&SERVICE=CSW&VERSION=2.0.2&OUTPUTSCHEMA=mw&CONSTRAINTLANGUAGE=CQL_TEXT&RESULTTYPE=results&TYPENAMES=csw:Record&ELEMENTSETNAME=full

- [x]  Au niveau des données et des séries : tjrs les infos sur les jeux de données associés + la correction de la balise <gmd:DQ_scope> ==> OK

- [ ]  Au niveau des services et applications : c'est résolu pour la baslise extent mais toujours pas résolu sur les balises manquantes spécifiques aux services. Tout le bloc ci-dessous ne se retrouve pas dans la réponse de la prod-temp.

```xml
<srv:serviceType>
	<gco:LocalName>view</gco:LocalName>
</srv:serviceType>
<srv:serviceTypeVersion xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0" gco:nilReason="missing">
	<gco:CharacterString xmlns:gco="http://www.isotc211.org/2005/gco" />
</srv:serviceTypeVersion>
<srv:couplingType>
	<srv:SV_CouplingType codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#SV_CouplingType" codeListValue="tight">tight</srv:SV_CouplingType>
</srv:couplingType>
<srv:containsOperations>
	<srv:SV_OperationMetadata>
		<srv:operationName>
			<gco:CharacterString>GetCapabilities</gco:CharacterString>
		</srv:operationName>
		<srv:DCP>
			<srv:DCPList codeList="http://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#DCPList" codeListValue="WebServices" />
		</srv:DCP>
		<srv:connectPoint>
			<gmd:CI_OnlineResource>
				<gmd:linkage>
						<gmd:URL>https://geoservices.wallonie.be/arcgis/services/IMAGERIE/ORTHO_2012_2013_IR/MapServer/WMSServer</gmd:URL>
				</gmd:linkage>
				<gmd:protocol>
					<gco:CharacterString>OGC:WMS</gco:CharacterString>
				</gmd:protocol>
				<gmd:name>
					<gco:CharacterString>Service de visualisation WMS</gco:CharacterString>
				</gmd:name>
				<gmd:description>
					<gco:CharacterString>Adresse de connexion au service de visualisation WMS</gco:CharacterString>
				</gmd:description>
				<gmd:function>
					<gmd:CI_OnLineFunctionCode codeList="http://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#CI_OnLineFunctionCode" codeListValue="" />
				</gmd:function>
			</gmd:CI_OnlineResource>
		</srv:connectPoint>
	</srv:SV_OperationMetadata>
</srv:containsOperations>
<srv:operatesOn uuidref="274f3fc1-ea9b-4afe-a6c4-e7595f103a74" xlink:href="https://metawal.wallonie.be/geonetwork/srv/api/records/274f3fc1-ea9b-4afe-a6c4-e7595f103a74" />
```

Outil utilisé pour la comparaison des fichiers : https://platform.text.com/tools/diff-checker

**Comment by fxprunayre** [comment]
Je reproduis. Corrigé. A déployer @GeryNi

**Comment by GeryNi** [comment]
Merci Francois, c'est déployé en TEST.

**Comment by GeryNi** [comment]
Déployé en VALID.
