### ISSUE TITLE
Erreur ES / Kibana

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#903]
Qd j'essaie d'accéder à Kibana, j'ai une erreur
https://metawal.wallonie.be/geonetwork/dashboards/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15y,to:now))&_a=(columns:!(),filters:!(),index:gn-records,interval:auto,query:(language:kuery,query:''),sort:!(!(dateStamp,desc)))

![image](https://github.com/user-attachments/assets/ec9f3694-d664-4ef7-9ca4-878cddcdde76)

**Comment by vbombaerts** [comment]
idem sur Metawal-temp

**Comment by fxprunayre** [comment]
Vérifier l'espace disque dispo pour Elasticsearch a priori.
Cf https://github.com/geonetwork/core-geonetwork/tree/main/es#disk-space-threshold
Ca doit également poser des problèmes côté metawal eg. les fiches ne sont plus indexées car l'index est passé en lecture seule.

**Comment by vbombaerts** [comment]
message d'erreur metawal-temp

![image](https://github.com/user-attachments/assets/db8f1856-994b-429c-80d7-d7bdcd76c416)

**Comment by fxprunayre** [comment]
On a aussi l'info
https://metawal.wallonie.be/geonetwork/srv/fre/admin.console#/dashboard

![image](https://github.com/user-attachments/assets/63b091ff-f7b9-49e5-8e3b-885ca524c210)

**Comment by fxprunayre** [comment]
Vérifier installation Kibana sur metawal-temp

**Comment by vbombaerts** [comment]
Kibana toujours inaccessible en prod-temp

![image](https://github.com/user-attachments/assets/953707fb-c696-4e77-9518-bffdbc3f0ef1)

**Comment by GeryNi** [comment]
Lié à la requête HTTP de metawal qui ne trouve pas réponse: 
![image](https://github.com/user-attachments/assets/bb10d4e0-4e53-4e74-9d3d-17f2b40e8ff9)

@Francois, sais tu s'il nous manquerait un paramètre à configurer ? je n'ai rien trouvé depuis l'interface d'admin de Géonetwork.
Serait-ce la configuration du proxy ?

**Comment by fxprunayre** [comment]
cf. https://github.com/geonetwork/docker-geonetwork/blob/main/4.4.5/docker-compose.yml#L31

**Comment by vbombaerts** [comment]
Kibana fonctionne maintenant en prod-temp. Par contre on n'y retrouve aucun des éléments présents normalement en prod : discovers, élements de visualisation, dashboards...

![image](https://github.com/user-attachments/assets/b3476428-edae-4384-93c4-08a484375f10)

![image](https://github.com/user-attachments/assets/74023055-aae2-4e72-bbb0-67dea65b14fa)

![image](https://github.com/user-attachments/assets/2ec52324-f672-415e-8332-0aaf6927b464)

![image](https://github.com/user-attachments/assets/01bd857f-bbac-4523-b6c6-4dd23a7454fc)

**Comment by vbombaerts** [comment]
Les versions et config sont-elles bien les mêmes sur test, valid et prod-temp ?

**Comment by vbombaerts** [comment]
Les éléments semblent avoir été réimportés correctement, mais j'ai parfois des erreurs qui indiquent des recherches non affichables car trop grandes. J'ai pas le problème en prod.

![image](https://github.com/user-attachments/assets/49af4e30-9a5b-4466-abff-9383efb96ec6)


Exemple : https://metawal-temp.wallonie.be/geonetwork/dashboards/app/discover#/view/99d0ef60-c474-11ec-9c43-0f70b8f525db?_g=(filters:!(),refreshInterval:(pause:!t,value:60000),time:(from:now-1y,to:now))&_a=(columns:!(_id,mw-gp-localIdentifier,resourceTitleObject.default,resourceType,custodianOrgForResource_tree,custodianOrgForResource,mw-gp-constraintsObject.link,cl_status.key,ownerOrgForResource),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:gn-records,key:custodianOrgForResource_tree,negate:!f,params:(query:'SPW%20-%20Agriculture,%20Ressources%20naturelles%20et%20Environnement'),type:phrase),query:(match_phrase:(custodianOrgForResource_tree:'SPW%20-%20Agriculture,%20Ressources%20naturelles%20et%20Environnement'))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:gn-records,key:resourceType,negate:!t,params:(query:application),type:phrase),query:(match_phrase:(resourceType:application)))),grid:(),hideChart:!f,index:gn-records,interval:auto,query:(language:kuery,query:''),sort:!(!(dateStamp,desc),!(mw-gp-localIdentifier,asc)))

et en prod : https://metawal.wallonie.be/geonetwork/dashboards/app/discover#/view/99d0ef60-c474-11ec-9c43-0f70b8f525db?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1y,to:now))&_a=(columns:!(_id,mw-gp-localIdentifier,resourceTitleObject.default,resourceType,custodianOrgForResource_tree,custodianOrgForResource,mw-gp-constraintsObject.link,cl_status.key,ownerOrgForResource),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:gn-records,key:custodianOrgForResource_tree,negate:!f,params:(query:'SPW%20-%20Agriculture,%20Ressources%20naturelles%20et%20Environnement'),type:phrase),query:(match_phrase:(custodianOrgForResource_tree:'SPW%20-%20Agriculture,%20Ressources%20naturelles%20et%20Environnement'))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:gn-records,key:resourceType,negate:!t,params:(query:application),type:phrase),query:(match_phrase:(resourceType:application)))),grid:(),hideChart:!f,index:gn-records,interval:auto,query:(language:kuery,query:''),sort:!(!(dateStamp,desc),!(mw-gp-localIdentifier,asc)))

**Comment by vbombaerts** [comment]
On n'a pas le même nombre de champs dans l'index des deux côtés, mais c'est peut-être normal...

prod : https://metawal.wallonie.be/geonetwork/dashboards/app/management/kibana/indexPatterns/patterns/gn-records#/?_a=(tab:indexedFields)
![image](https://github.com/user-attachments/assets/6dcd04bf-8076-4262-a0d2-c42abe89c6ca)


prod-temp : https://metawal-temp.wallonie.be/geonetwork/dashboards/app/management/kibana/dataViews/dataView/gn-records#/?_a=(tab:indexedFields)
![image](https://github.com/user-attachments/assets/753ab1a9-ebef-45c7-8f72-3fa8f9e218d8)

**Comment by fxprunayre** [comment]
> On n'a pas le même nombre de champs dans l'index des deux côtés, mais c'est peut-être normal...

Oui, il y a quelques champs en plus dans l'index eg. maintenance
https://github.com/geonetwork/core-geonetwork/pulls?q=is%3Apr+label%3A%22index+structure+change%22+is%3Aclosed
et la possibilité de faire des aggrégations sur des fiches associées https://github.com/geonetwork/core-geonetwork/pull/7939

**Comment by vbombaerts** [comment]
Et certains en moins aussi ?

**Comment by fxprunayre** [comment]
> Et certains en moins aussi ?

Normalement non.

**Comment by vbombaerts** [comment]
on passe de 2816 en prod  à 2697 en prod-temp... (voir capture d'écran)

**Comment by fxprunayre** [comment]
> on passe de 2816 en prod à 2697 en prod-temp... (voir capture d'écran)

Après comparaison rapide des 2, les grands différences sont:

```json
#1 New field / Field non case sensitive sorting 
 {
      "name": "MD_ConstraintsUseLimitationObject.default.sort",
      
#2 New field / New languages
      "name": "MD_ConstraintsUseLimitationObject.langdan",

#3 Removed field / Undeclared language
      "name": "cl_accessConstraints.lang",
      "name": "cl_spatialRepresentationType.lang",
      
#4 Removed field / Due to type change - conformité est de type keyword (donc on divise par 2 le nombre de champ conformsTo_ - Ca représente ~120 champs de moins)

 {
      "name": "conformTo_INSPIREDataSpecificationonAddresses-Guidelinesv3-1-0",
      "type": "string",
      "esTypes": [
        "text"
      ],
      "searchable": true,
      "aggregatable": false,
      "readFromDocValues": false,
      "metadata_field": false
    },


#5 Removed field / Des thésaurus qui ne sont plus utilisés en test?
      "name": "th_AGROVOC.text",
      "name": "th_HVDLegal.text",
      "name": "th_MobilityTheme.langeng",
      "name": "th_httpinspireeceuropaeufeatureconcept-featureconcept.langger",
      "name": "th_themes_ODWB.lang",
      
```

Donc la différence s'explique essentiellement par le point 4.

**Comment by vbombaerts** [comment]
merci pour l'explication
