### ISSUE TITLE
DCAT / Erreur XSL quand un organisme a plusieurs membres

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#908]
https://metawal.wallonie.be/geonetwork/srv/eng/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetRecords&typenames=dcat-ap&elementSetName=full&resultType=results&maxRecords=300&outputSchema=http%3A%2F%2Fwww.w3.org%2Fns%2Fdcat%23

HVD output: 

https://metawal.wallonie.be/geonetwork/srv/eng/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetRecords&typenames=dcat-ap&elementSetName=full&resultType=results&maxRecords=300&outputSchema=https%3A%2F%2Fsemiceu.github.io%2FDCAT-AP%2Freleases%2F2.2.0-hvd%2F

 ```
java.lang.RuntimeException:
org.fao.csw.common.exceptions.InvalidParameterValueEx: code=InvalidParameterValue, locator=OutputSchema,
message=Error occurred while transforming metadata with id '53423' using 'eu-dcat-ap-hvd.xsl'.
 ```

Erreur XSL liée au fait qu'on a un organisme avec n individus:
 ```
2024-09-04T12:26:42,581 ERROR [geonetwork] - A sequence of more than one item is not allowed as the first argument of gn-fn-dcat:rdf-object-ref() (<cit:CI_Individual/>, <cit:CI_Individual/>, ...)
net.sf.saxon.trans.XPathException: A sequence of more than one item is not allowed as the first argument of gn-fn-dcat:rdf-object-ref() (<cit:CI_Individual/>, <cit:CI_Individual/>, ...)
 ```

![image](https://github.com/user-attachments/assets/9f26e097-b58c-4b56-9794-8bb787e238b8)

Proposition: créer autant de foaf:Agent que d'individual

**Comment by vbombaerts** [comment]
Si les individus ont leur propre adresse mail, laquelle est retenue ? Celle de l'organisation ou celle de l'individu ?

Ceci dit, c'est un cas assez exceptionnel qu'on pourrait gérer autrement.

**Comment by fxprunayre** [comment]
On va prendre l'email de l'individu et si pas dispo, on prend celui de l'organisation.

**Comment by fxprunayre** [comment]
A déployer @GeryNi

**Comment by GeryNi** [comment]
Merci pour le correctif, c'est déployé.

**Comment by vbombaerts** [comment]
Pour tester 

Test 👍 : https://metawal.test.wallonie.be/geonetwork/srv/api/records/128bb085-2525-4b89-a739-2fa1538f97ca/formatters/eu-dcat-ap-hvd?output=xml  

Valid ⏲️  : https://metawal.valid.wallonie.be/geonetwork/srv/api/records/128bb085-2525-4b89-a739-2fa1538f97ca/formatters/eu-dcat-ap-hvd?output=xml

Prod ⏲️ : https://metawal-temp.wallonie.be/geonetwork/srv/api/records/128bb085-2525-4b89-a739-2fa1538f97ca/formatters/eu-dcat-ap-hvd?output=xml

**Comment by GeryNi** [comment]
Déployé en VALID.
