### ISSUE TITLE
OGC API records non disponible en prod

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#909]
https://metawal-temp.wallonie.be/geonetwork/api/collections

Erreur 500

**Comment by GeryNi** [comment]
@vbombaerts , j'air egardé et trouvé le même problème en TEST.

Didier a relance OGC API Records sur TEST et PROD et cela semble fonctionner.

J'attends sa réponse pour savoir si la config a changé ou non.
-> réponse de Didier: Didier n'a pas modifié la config, juste relancé.

**Comment by GeryNi** [comment]
Didier n'a pas modifié la config, juste relancé.

**Comment by GeryNi** [comment]
Didier a relance OGC API Records sur TEST et PROD et cela fonctionne à nouveau.
Didier n'a pas modifié la configuration.
