### ISSUE TITLE
Encodage d'un contact - Manque la liste des Pays

### ISSUE THREAD

**Issue by geologiewallonie** [SPW-DIG/metawal-core-geonetwork#91]
Le menu déroulant proposé au niveau de l'encodage du pays d'un contact est vide.

![4](https://f.cloud.github.com/assets/6093460/1663576/a9cadea4-5c17-11e3-8f9a-ca231e7cabc7.JPG)

**Comment by geologiewallonie** [comment]
Il semble que ce problème n'apparaisse plus après avoir sauvé la fiche ou quand la fiche est en anglais.

**Comment by fxprunayre** [comment]
Cf https://github.com/spacebelGIS/metawal-core-geonetwork/commit/78211c6c0a2eab23ded3e22e8ee3e75158f73437
