### ISSUE TITLE
OGC API ne renvoie pas toutes les fiches

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#911]
Tjrs une différence de nombre de fiches entre ce que renvoie OGC API et le portail

https://metawal.test.wallonie.be/geonetwork/api/collections/hvd/items
https://metawal.test.wallonie.be/geonetwork/hvd/fre/catalog.search#/search?from=1&to=30

idem dans les autres environnements

Problème avec les caractères spéciaux ?

**Comment by vbombaerts** [comment]
#857 #858

**Comment by fxprunayre** [comment]
Il en manque 13. https://metawal-temp.wallonie.be/geonetwork/hvd/fre/admin.console#/dashboard et il a 13 fiches avec erreurs d'indexation

Donc je dirai vérifier https://github.com/SPW-DIG/metawal-core-geonetwork/issues/858, on avait dit de remplacer dans la config `queryFilter: '+isTemplate:n AND -indexingError:true'` par `queryFilter: '+isTemplate:n'` @GeryNi

**Comment by GeryNi** [comment]
J'ai mis à jour la config de ogc-api-records (le ficheir bootstrap.yaml fourni dans le déliverable contenanit toujours: queryFilter: '+isTemplate:n AND -indexingError:true'

J'ai mis à jour le déliverable pour qu'il contienne la nouvelle configuration (qu'il faudra déployer en VALID et PROD)


j'ai contacté Didier pour avoir comment redémarrer ogc-api-records en TEST

**Comment by GeryNi** [comment]
Corrigé en TEST: https://metawal.test.wallonie.be/geonetwork/api/collections/hvd/items

![image](https://github.com/user-attachments/assets/2a27a63c-34ae-46bb-8321-89c0ecef4583)
