### ISSUE TITLE
Erreur 404 quand j'utilise la console réseau sur Edge

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#915]
J'ai essayé d'ouvrir la console réseau sur Edge pour tester des requêtes vers l'API Metawal. 
J'obtiens une erreur 404.
![image](https://github.com/user-attachments/assets/fa3f8100-d2c9-47fb-843d-c973ff748e84)

J'ai voulu tester la console réseau et l'API Metawal parce qu'un des dev de WalOnMap m'a dit qu'il accédait au CSW en test mais pas à l'API. C'est sur le point d'accès geoportailwal. Une idée ?

**Comment by vbombaerts** [comment]
J'ai la même erreur sur n'importe quelle autre page. Ce serait une restriction due  à la politique de sécurité du SPW ?

**Comment by GeryNi** [comment]
@Vincent, je ne suis pas familier avec la network console de Edge.

Peut être s'agit-il simplement l'url utilisée ou leverbe HTTP qui ne serait pas bon ? Je n'a pas trouvé comment créer une requête depuis cette console.

Peut être plus partique pour les developpers, la documentation interactive de l'api (SWAGGER document): https://metawal.wallonie.be/geonetwork/doc/api/index.html

Voici aussi une collection de requêtes d'exemples de recherche:
[GeoPortail-SearchAPi.zip](https://github.com/user-attachments/files/17127554/GeoPortail-SearchAPi.zip)

**Comment by vbombaerts** [comment]
Merci Géry. J'utilise fréquemment swagger et c'et très pratique, mais les requêtes ne peuvent se faire que vers Metawal dans son entièreté (/srv). Je voudrais tester des requêtes vers certains points d'accès (/geoportailwal, /hvd ...)

**Comment by GeryNi** [comment]
Je n'ai pas l'habitude de la console de Edge mais j'utilise souvent Postman que je trouve très pratique dans ces cas là (gestion des requêtes pour différents environnements/paramètres). J pourrais faire une mini démo si cela t'intéresse.

**Comment by vbombaerts** [comment]
Contournement : Postman online https://web.postman.co/
