### ISSUE TITLE
DCAT - Identifier

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#920]
Ne conserver que l'identifiant global du jeu de données. Ne pas exposer l'identifiant local.
DCAT autorise plusieurs occurences de l'identifiant mais MobilityDCAT une seule. L'identifiant local n'a pas de signification en dehors de l'infraSIG donc je propose de ne conserver que le global en DCAT.

**Comment by fxprunayre** [comment]
On a en effet en dcat-ap https://semiceu.github.io/DCAT-AP/releases/3.0.0/

![image](https://github.com/user-attachments/assets/ef3075e3-de2f-47a2-b244-448c89849a91)

et https://mobilitydcat-ap.github.io/mobilityDCAT-AP/releases/index.html

![image](https://github.com/user-attachments/assets/4aff19ec-8092-49d4-b2f5-571e004eb6c4)

Par contre il y a un champ "other identifier" (`adms:identifier`) que nous pourrions utiliser ? 

* le premier identifiant est transformé en `dct:identifier` 
* les autres en `adms:identifier`

![image](https://github.com/user-attachments/assets/47275777-4e02-42ba-b3f0-e63e7f1674a1)

**Comment by fxprunayre** [comment]
A déployer. Ajouté également l'utilisation de `:` dans les identifiants ayant un codespace `urn:...`.

En DCAT simple, on reste sur 0..n `dct:identifier`
