### ISSUE TITLE
OGC API Records et MobilityDCAT

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#921]
Quels paramètres je dois indiquer dans la requête OGC API pour avoir en sortie du mobilityDCAT ?

**Comment by fxprunayre** [comment]
La sortie Mobility DCAT est accessible uniquement via:
* l'API des formatters https://metawal-temp.wallonie.be/geonetwork/srv/api/records/1240d67e-a05b-4d69-aa09-190a05f6b561/formatters/eu-dcat-ap-mobility?output=xml
* ou le CSW https://metawal-temp.wallonie.be/geonetwork/srv/eng/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetRecordById&ID=1240d67e-a05b-4d69-aa09-190a05f6b561&outputSchema=https://w3id.org/mobilitydcat-ap

Côté OGC API Records, l'idée à moyen terme est de migrer le micro service OGC API Records dans le nouveau dépôt pour GeoNetwork 5 et de lui ajouter la connaissance des formatters pour avoir une sortie homogène entre l'API GN et l'API OGC.
