### ISSUE TITLE
Basculer les applications métier vers mw-gp-thematicMap

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#922]
_Originally posted by @vbombaerts in https://github.com/SPW-DIG/metawal-core-geonetwork/issues/916#issuecomment-2376459290_

Le passage vers le nouveau Géoportail permet de basculer les applications thématiques renseignées dans les fiches de données vers mw-gp-thematicMap

- Retrouver la combinaison de function/app profile qui avait été définie pour qualifier un lien de type thematic map
- Trouver les fiches concernées (sur base de la recherche "geoapp" ou "webgis" ou "CIGALE" ou "#CTX" ou "#VIEWER" dans l'url) @marceaulouis tu vois d'autres mots-clés pour les appli thématiques ?
- Modifier en batch et réindexer

**Comment by fxprunayre** [comment]
> * Retrouver la combinaison de function/app profile qui avait été définie pour qualifier un lien de type thematic map

Cf. https://github.com/SPW-DIG/metawal-core-geonetwork/blob/metawal-4.4.x/schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/index-fields/index.xsl#L1405-L1420

**Comment by vbombaerts** [comment]
Requête Kibana
https://metawal.wallonie.be/geonetwork/dashboards/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:60000),time:(from:now-15y,to:now))&_a=(columns:!(resourceTitleObject.default,linkUrl,mw-gp-thematicMap.urlObject.default),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,field:resourceType,index:gn-records,key:resourceType,negate:!f,params:!(dataset,series),type:phrases,value:!(dataset,series)),query:(bool:(minimum_should_match:1,should:!((match_phrase:(resourceType:dataset)),(match_phrase:(resourceType:series)))))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:gn-records,key:mw-gp-thematicMap.urlObject.default,negate:!t,type:exists,value:exists),query:(exists:(field:mw-gp-thematicMap.urlObject.default)))),index:gn-records,interval:auto,query:(language:kuery,query:'*geoapps*%20OR%20*CIGALE*%20OR%20*webgis*%20OR%20*%23CTX*%20OR%20*%23VIEWER*'),sort:!())

**Comment by vbombaerts** [comment]
Quelques fiches corrigées. Le reste se fera au fur et à mesure des éditions.
