### ISSUE TITLE
Fiches WalOnMapNO

### ISSUE THREAD

**Issue by marceaulouis** [SPW-DIG/metawal-core-geonetwork#923]
Je recherche les fiches (séries et data) qui ont un service REST encodé et dont la fonction pour ce service est "Information". 
Jusqu'à présent, je n'arrive pas à lier ces deux infos, j'ai les fonctions de toutes les ressources encodées dans une fiche mais pas celle correspondant spécifiquement au service REST

Pouvez-vous m'aiguiller ?

Merci !

**Comment by vbombaerts** [comment]
Je n'en vois aucune
https://metawal.wallonie.be/geonetwork/dashboards/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15y,to:now))&_a=(columns:!(mw-gp-esriWebServices.function,mw-gp-esriWebServices.urlObject.default,sc_mdEditLink),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:gn-records,key:resourceType,negate:!f,params:!(dataset,series),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(resourceType:dataset)),(match_phrase:(resourceType:series)))))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:gn-records,key:mw-gp-esriWebServices.urlObject.default,negate:!f,type:exists,value:exists),query:(exists:(field:mw-gp-esriWebServices.urlObject.default)))),index:gn-records,interval:auto,query:(language:kuery,query:''),sort:!(!(dateStamp,desc)))

**Comment by marceaulouis** [comment]
yep, parce qu'à mon avis "mw-gp-esriWebServices.urlObject.default" n'existe que si la function est Browsing...

https://metawal.wallonie.be/geonetwork/dashboards/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15y,to:now))&_a=(columns:!(mw-gp-esriWebServices.function,mw-gp-esriWebServices.urlObject.default,sc_mdEditLink,linkProtocol),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:gn-records,key:resourceType,negate:!f,params:!(dataset,series),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(resourceType:dataset)),(match_phrase:(resourceType:series)))))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:gn-records,key:linkProtocol,negate:!f,params:(query:'ESRI:REST'),type:phrase),query:(match_phrase:(linkProtocol:'ESRI:REST')))),index:gn-records,interval:auto,query:(language:kuery,query:''),sort:!(!(dateStamp,desc)))

**Comment by vbombaerts** [comment]
L'info est dans l'élément Link. Peut-être via un webcomposant et du JSON path qui filtre sur le protocole ESRI:REST...

Json path : `_source.link[?(@.protocol=="ESRI:REST")].function`

**Comment by vbombaerts** [comment]
J'ai un peu avancé, mais je suis bloqué maintenant.
1. Faire une requête dans l'interface swagger pour récupérer toutes les fiches de donnée et séries
https://metawal.wallonie.be/geonetwork/doc/api/index.html#/search/search
```
{
  "from": 1,
  "size": 1000,
  "query": {
    "bool": {
      "should": [
        {
          "query_string": {
            "query": "(cl_resourceScope.key:\"series\")"
          }
        },
        {
          "query_string": {
            "query": "(cl_resourceScope.key:\"dataset\")"
          }
        }
      ]
    }
  },
  "_source": {
    "includes": [
      "resourceTitleObject.default",
      "uuid",
      "link"
    ]
  }
}
```
3. Utiliser un évaluateur de Json path pour rechercher les fiches qui correspondent au critère
https://jsonpath.com/
Copier coller le résultat de la requête swagger dans la partie Input
et taper la requête dans le cadre en haut.
`hits.hits[*]._source.link[?(@.protocol=="ESRI:REST" && @.function=="information")]`
--> ca donne en résultat une liste des links qui répondent à la condition (il y en a +/- 200) mais je n'arrive pas à remonter jusqu'à l'id de la fiche.

Je suis bloqué parce que je n'arrive pas à faire des filtres avec des tableaux l'un dans l'autre genre `hits.hits[?(@._source.link[?(@.unequeryici)])]._source.uuid`

**Comment by fxprunayre** [comment]
`link` est de type nested

```

GET gn-records/_mapping


      "link" : {
          "type" : "nested",
          "properties" : {
            "applicationProfile" : {
              "type" : "text",
              "fields" : {
                "keyword" : {
                  "type" : "keyword",
                  "ignore_above" : 256
                }
              }
            },

```

Donc il faudrait utiliser 
https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html

**Comment by fxprunayre** [comment]
```json
GET gn-records/_search
{
  "from": 1,
  "size": 1000,
  "query": {
    "bool": {
      "should": [
        {
          "query_string": {
            "query": "(cl_resourceScope.key:\"series\")"
          }
        },
        {
          "query_string": {
            "query": "(cl_resourceScope.key:\"dataset\")"
          }
        }
      ],
      "must": [
        {
          "nested": {
            "path": "link",
            "query": {
              "bool": {
                "must": [
                  {
                    "match": {
                    "link.protocol": "ESRI:REST"
                    }
                  },
                  {
                    "match": {
                      "link.function": "information"
                    }
                  }
                ]
              }
            }
          }
        }
      ]
    }
  },
  "_source": {
    "includes": [
      "resourceTitleObject.default",
      "uuid",
      "link*"
    ]
  }
}
```

224 fiches - est-ce que ça semble cohérent?

**Comment by vbombaerts** [comment]
Ah ben oui, c'est pas malin de ne pas avoir continué la démarche jusqu'au bout avec l'API GN !
