### ISSUE TITLE
Geoportail / Webcomponent / Problème de style

### ISSUE THREAD

**Issue by GeryNi** [SPW-DIG/metawal-core-geonetwork#924]
On a détecté avec @fxprunayre une erreur de style sur le geoportail (probablement lié à nos webcomponents).
On peut voir une marge de +- 10px sur la gauche de l'écran.

![image](https://github.com/user-attachments/assets/9bb20af4-651b-4c88-8e39-d719c56749fc)

**Comment by fxprunayre** [comment]
Corrigé côté webcomponent https://github.com/titellus/icho/commit/eaab6a2c760ecfd3a751f0beabd18247a85d1263, à embarquer dans metawal et déployer.

**Comment by GeryNi** [comment]
Déployé en Test
