### ISSUE TITLE
Metawal - problème API GN

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#925]
Requêtes via Swagger Metawal OK
Requêtes via Géoportail OK
Requêtes de l'extérieur KO

Idem en valid (test pas accessible depuis l'extérieur, donc normal)

Vérifier aussi le CSW

![image](https://github.com/user-attachments/assets/b14653b6-a4d4-4c64-9073-fe11b11b5cb2)

**Comment by vbombaerts** [comment]
CSW a l'air OK

**Comment by fxprunayre** [comment]
> Requêtes de l'extérieur KO

Essaye en ajoutant un Header `Accept` fixé à `application/json`

![image](https://github.com/user-attachments/assets/53733ab9-8b55-4bee-a3d6-35cbdcd5a18c)

**Comment by vbombaerts** [comment]
OK. ça marche. 
La valeur de Accept était à */* (j'imagine que ça veut dire "tout" ?)

**Comment by dbu-spw** [comment]
Cela ne fonctionne toujours plus au niveau de FME Desktop et FME Server depuis la MàJ de Metawal.
Aucun changement sur les routines FME mais j'obtiens maintenant un message d'erreur 400

- OK si HTTPCaller de http://metawal.wallonie.be/geonetwork/srv/api/records/b795de68-726c-4bdf-a62a-a42686aa5b6f/formatters/xsl-view?output=pdf
- KO si appelle l'API http://metawal.wallonie.be/geonetwork/srv/api/search/records/_search?bucket=metadata en POST avec dans le body les paramètres en json.

**Comment by GeryNi** [comment]
@dbu-spw Pourriez-vous fournir le body JSON utilisé ?

Merci.

**Comment by dbu-spw** [comment]
{
  "from": 0,
  "size": 1000,
  "_source":{"includes": [ "mw-gp-globalIdentifier", "revisionDateForResource", "format", "crsDetails.code", "status", "cl_spatialRepresentationType.key", "infrasig_PanierTelechargementGeoportail","resourceTitleObject.langfre","mw-gp-constraintsObject.link"]},  
  "query": {
		"bool": {
			"must": [
				{"terms": {"resourceType": ["data","dataset","series","document","nonGeographicDataset"]}},
				{"term":  {"isPublishedToAll": {"value": "true"} }},
				{"term":  {"_id": {"value": "6d5020a8-aaae-41c7-b9e2-d3648594ec11"} }},
				{"term":  {"groupPublished": {"value": "GeoportailWal"} }},
				{"bool": {
						"should": [
							{"term":  {"th_infraSIG.default": {"value": "Open Data"}}},
							{"term":  {"mw-gp-constraintsObject.link": {"value": "https://creativecommons.org/licenses"}}},
							{"bool": {
								"must": [
									{"term":  {"mw-gp-constraintsObject.link": {"value": "https://geoportail.wallonie.be/files/documents/ConditionsSPW/DataSPW-CPU-TypeC.pdf"}}},
									{"term":  {"mw-gp-constraintsObject.link": {"value": "https://geoportail.wallonie.be/files/documents/ConditionsSPW/DataSPW-CGA.pdf"}}}	
									]
								}
							}
						]
					}
				}				
			]
		}
    }
}

**Comment by vbombaerts** [comment]
Problème de valeur booléenne et d'alignement de la requête dans l'outil FME.
