### ISSUE TITLE
CSW :  l’adresse de redirection ne fonctionne plus 

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#926]
L’adresse de redirection :  https://geoservices.wallonie.be/metawal/csw  ne fonctionne plus

**Comment by vbombaerts** [comment]
#691

**Comment by GeryNi** [comment]
Suite à l'intervention de Didier, a redirection fonctionne à nouveau:
![image](https://github.com/user-attachments/assets/8acd6f39-c6ae-4190-978f-19b42137a74b)
