### ISSUE TITLE
Section Résumé non éditable

### ISSUE THREAD

**Issue by marceaulouis** [SPW-DIG/metawal-core-geonetwork#927]
En édition, en test, valid et prod, le résumé des fiches ne s'affiche pas et n'est plus éditable en vue simplifiée ou complète

![image](https://github.com/user-attachments/assets/a64eca4c-7b72-440d-b791-46b6b0dde8b9)

Ok dans le xml

**Comment by fxprunayre** [comment]
Corrigé. En lien avec la mise à jour JQuery côté GN. A déployer pour test.
