### ISSUE TITLE
Définition de infrasig_WalOnMap

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#931]
Quelle est la définition de l'élément infrasig_WalOnMap ?

Est-ce qu'il n'est pas à true si le tag WalOnMap est indiqué dans la fiche et à false si WalOnMapNO est indiqué dans la fiche ?
Parce que apparemment ce n'est pas le cas.

https://metawal.wallonie.be/geonetwork/dashboards/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:60000),time:(from:now-15y,to:now))&_a=(columns:!(infrasig_WalOnMap,resourceTitleObject.default,linkUrlProtocolESRIREST,th_infraSIG.default),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,field:groupPublished,index:gn-records,key:groupPublished,negate:!f,params:(query:GeoportailWal),type:phrase),query:(match_phrase:(groupPublished:GeoportailWal))),('$state':(store:appState),meta:(alias:!n,disabled:!f,field:resourceType,index:gn-records,key:resourceType,negate:!f,params:!(dataset,series),type:phrases,value:!(dataset,series)),query:(bool:(minimum_should_match:1,should:!((match_phrase:(resourceType:dataset)),(match_phrase:(resourceType:series)))))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:gn-records,key:infrasig_WalOnMap,negate:!t,type:exists,value:exists),query:(exists:(field:infrasig_WalOnMap))),('$state':(store:appState),meta:(alias:!n,disabled:!f,field:isPublishedToAll,index:gn-records,key:isPublishedToAll,negate:!f,params:(query:true),type:phrase),query:(match_phrase:(isPublishedToAll:true))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:gn-records,key:linkUrlProtocolESRIREST,negate:!f,type:exists,value:exists),query:(exists:(field:linkUrlProtocolESRIREST)))),index:gn-records,interval:auto,query:(language:kuery,query:''),sort:!())

**Comment by fxprunayre** [comment]
![image](https://github.com/user-attachments/assets/4bce184d-08ac-44ea-9a5f-a2684101e106)

https://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/a64fd4ae-1fa4-11ec-8223-7478273ff935

Ca semble correct?

Mais pas pour https://metawal.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/b5fdceac-418d-4cc1-85b5-0333cf30cc05

**Comment by GeryNi** [comment]
@fxprunayre  à cause que c'est placé dans une ancre à la place de CharacterString ?

Voir: Index.xsl Ligne 443
![image](https://github.com/user-attachments/assets/eafafa16-89ac-4e2b-bbff-eb977e5c332f)

**Comment by GeryNi** [comment]
Updated indexing clause to support Anchros:
    <xsl:variable name="infrasigKeywords"
                      select="*/mri:MD_Keywords[
        contains(lower-case(
        (mri:thesaurusName/*/cit:title/*/text())[1]
        ), 'infrasig')]
        /mri:keyword/(gco:CharacterString | gcx:Anchor)"/>

**Comment by GeryNi** [comment]
@vbombaerts: corrigé en TEST, pourrais-tu regarder: https://metawal.test.wallonie.be/geonetwork/srv/fre/catalog.search#/metadata/b5fdceac-418d-4cc1-85b5-0333cf30cc05

**Comment by vbombaerts** [comment]
C'est bon en test
