### ISSUE TITLE
INSPIRE - validation distance

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#933]
J'ai branché le validateur INSPIRE sur l'instance de staging https://inspire.ec.europa.eu/validator-staging-api et j'ai lancé une validation. J'ai l'erreur suivante.
![image](https://github.com/user-attachments/assets/06904348-45c7-411c-8bfa-e2c5f3ccb7fb)
![image](https://github.com/user-attachments/assets/9cb92f96-f3a0-4084-b5b4-8def619fa12d)

Or https://inspire.ec.europa.eu/validator-staging/swagger-ui.html#/ a l'air de fonctionner

**Comment by vbombaerts** [comment]
Même chose avec la valeur https://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/validator-staging/

**Comment by fxprunayre** [comment]
Ca devrait être quelquechose comme ça

https://user-images.githubusercontent.com/1695003/152165315-c748347e-8fd7-47a6-a81e-595024eae3de.png

**Comment by vbombaerts** [comment]
On m'a demandé de passer sur l'instance de staging pour travailler avec la dernière version du validateur. https://wikis.ec.europa.eu/display/InspireMIG/79th+MIG-T+meeting+2024-09-13?preview=/139695168/143427407/MIG-T79_Validator.pdf

**Comment by vbombaerts** [comment]
Hello. On me confirme que la version du validateur qui sera utilisée pour le monitoring est déjà déployée à la Commission. Donc on peut utiliser l'adresse https://inspire.ec.europa.eu/validator/
