### ISSUE TITLE
Bug ancres qualité et licences

### ISSUE THREAD

**Issue by marceaulouis** [SPW-DIG/metawal-core-geonetwork#935]
L'ancre pour ajouter les liens vers les spécifications des conformités ou les licences n'est pas éditable en vue simplifiée ou complète en PROD comme en TEST.

Seulement quand on crée un nouvel élément, ok si existe déjà

![image](https://github.com/user-attachments/assets/380c0bde-7b97-4728-b5be-98ac89e3c4b2)

![image](https://github.com/user-attachments/assets/4236ecc8-1980-42d3-b960-dbf8fcde688d)

**Comment by GeryNi** [comment]
@marceaulouis Déployé en TEST. J'ai vérifié mais n'hésites pas à aller essayer :)

**Comment by GeryNi** [comment]
On a regardé avec @fxprunayre , il s'agissait d'un problème dans le rendu du formulaire (une balise autofermante mal supportée).

**Comment by marceaulouis** [comment]
parfait en test ! merci
