### ISSUE TITLE
Configuration Kibana en prod

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#936]
J'obtiens souvent le message d'erreur
![image](https://github.com/user-attachments/assets/aaf1f81b-e96f-47c5-8714-e66d6903ab94)

sur Kibana en prod.

Même si la requête ne me paraît pas très grande

https://metawal.wallonie.be/geonetwork/dashboards/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:60000),time:(from:now-1y,to:now))&_a=(columns:!(th_infraSIG_tree.default,th_infraSIG.link),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,field:resourceType,index:gn-records,key:resourceType,negate:!f,params:!(dataset,document,featureCatalog,nonGeographicDataset,series),type:phrases,value:!(dataset,document,featureCatalog,nonGeographicDataset,series)),query:(bool:(minimum_should_match:1,should:!((match_phrase:(resourceType:dataset)),(match_phrase:(resourceType:document)),(match_phrase:(resourceType:featureCatalog)),(match_phrase:(resourceType:nonGeographicDataset)),(match_phrase:(resourceType:series)))))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:gn-records,key:th_infraSIG_tree.default,negate:!f,params:(query:WalOnMap),type:phrase),query:(match_phrase:(th_infraSIG_tree.default:WalOnMap)))),index:gn-records,interval:auto,query:(language:kuery,query:''),sort:!())

**Comment by fxprunayre** [comment]
Ce n'est pas très clair. Si on demande sur les 4 derniers mois on obtient une réponse
![image](https://github.com/user-attachments/assets/cf308d97-5fbe-468a-aed0-f6b645b0ac9f)
avec pagination.

Sur 1 an, on a le pb.

On filtre les colonnes mais j'ai l'impression que tout le document est retourné, dont les overviews qui sont encodées dans le document et qui représentent la majorité de la taille du document. C'est bizarre qu'il n'y ait pas pagination dans ce cas.

**Comment by vbombaerts** [comment]
on ne peut pas forcer l'exclusion des overviews dans la réponse. Au moins pour les requêtes Kibana ?

**Comment by fxprunayre** [comment]
J'ai ajouté un field filter


![image](https://github.com/user-attachments/assets/83f58db4-110a-4630-a51a-03f01446afb1)


Ca semble mieux.

**Comment by vbombaerts** [comment]
J'ai modifié à overview.data*
