### ISSUE TITLE
"Collez le lien suivant dans un e-mail ou dans un message instantané" : à renommer et clarifier

### ISSUE THREAD

**Issue by metawal** [SPW-DIG/metawal-core-geonetwork#94]

**Comment by fxprunayre** [comment]
Une proposition ?

**Comment by vbombaerts** [comment]
"Partager les résultats de cette recherche"

**Comment by fxprunayre** [comment]
FYI, l'origine de la mention 
![image](https://f.cloud.github.com/assets/1701393/1748327/9f3b67f2-64b3-11e3-8b57-939992e46003.png)
