### ISSUE TITLE
Mots clés - impossible d'en ajouter plusieurs

### ISSUE THREAD

**Issue by metawaltest** [SPW-DIG/metawal-core-geonetwork#95]

**Comment by fxprunayre** [comment]
Les mots-clés insérés disparaissent lors de l'ajout de nouveaux mots-clés via mots-clés de thèmes

Observable en test

**Comment by fxprunayre** [comment]
Il manque les shortcode dans la table ISOLANGUAGES. A ajouter au script de migration s'ils n'y sont pas

**Comment by vbombaerts** [comment]
Quand on veut ajouter des mots-clés en provenance d'un thésaurus, cela efface les mots-clés des autres thésauri.
Testé sur la fiche http://metawal3.test.wallonie.be/geonetwork/srv/fre/search?uuid=e8928ce7-0194-4e91-af88-d2b704bb127f
1. Un champ pour mot-clé libre reste vide
2. Je clique sur les jumelles, j'ajoute des mots-clés du géoportail wallon
3. Je reclique sur des jumelles pour ajouter des mots-clés  du GEMET
![image 673](https://f.cloud.github.com/assets/6093597/1888435/a17b56f2-7a0d-11e3-9c0b-db0a8ceefdc2.png)
4. Quand le bloc GEMET apparaît, les mots-clés géoportail ont disparu.
![image 675](https://f.cloud.github.com/assets/6093597/1888446/bfa5ad30-7a0d-11e3-9e1b-b7de84ec24ac.png)

L'erreur n'apparait que dans certaines configurations spécifiques. Si j'ai déjà rempli un mot-clé libre, je n'ai pas d'erreur.
Dans certains cas, je dois cliquer deux fois sur les jumelles pour faire apparaître le bloc du thésaurus. On dirait que la première fois sert à sauver les mots-clés existants et la deuxième fois sert à faire apparaître le bloc du thésaurus en question.

**Comment by fxprunayre** [comment]
Je ne reproduis pas sur le serveur de démo. @davinciagf tu peux tester également ? @vbombaerts Quel navigateur ?

**Comment by davinciagf** [comment]
En démo c'est ok avec Fx

**Comment by vbombaerts** [comment]
j'utilise FFx 26
Problème lié au thésaurus wallon ? lié aux accents ?
Les mots-clés ne s'affichent pas lors de l'édition mais sont bien enregistrés ?
screencast : http://youtu.be/Nv7WVy6lxZ0
edit 15/01 : la video est maintenant publique

**Comment by vbombaerts** [comment]
Je n'ai plus réussi à répliquer l'erreur suit au dernier déploiement. Je ferme.
