### ISSUE TITLE
Consultation / Vue avancée - onglet avec mauvais contenu

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#96]
Eg. extension

**Comment by davinciagf** [comment]
Onglet - contraintes, maintenance, info. spatiales, catlogue, contact info, info ext, tableindent

**Comment by vbombaerts** [comment]
Problème semble résolu. Un petit "Pas d'information disponible" ou "Non renseigné" serait bienvenu dans une version ultérieure. Voir #139
