### ISSUE TITLE
Profil RW / Pas de schématron, Pb de schéma

### ISSUE THREAD

**Issue by fxprunayre** [SPW-DIG/metawal-core-geonetwork#97]

**Comment by fxprunayre** [comment]
Problème observable uniquement en test et démo

**Comment by fxprunayre** [comment]
Fixed in https://github.com/spacebelGIS/metawal-core-geonetwork/commit/547f98a82b8d1ab81622884d97bd2ea013c12821

**Comment by vbombaerts** [comment]
Validation possible de fiches au profil wallon, mais les éléments wallons spécifiques ne sont pas pris en compte. Par exemple le rw:CI_ResponsibleParty.
Problème aussi avec le format de date. Il me semble que l'heure n'est pas obligatoire et que donc le format de la fiche est valide.
Messages d'erreur un peu rudes pour les non-spécialistes. A peaufiner pour une prochaine version.
Fiche testée : http://metawal3.test.wallonie.be/geonetwork/srv/fre/search?uuid=7e68f1e3-3f43-487d-8eab-d09cf8586862

**Comment by fxprunayre** [comment]
> Problème aussi avec le format de date. Il me semble que l'heure n'est pas obligatoire et que donc le format de la fiche est valide.

```
<gmd:date>
<gco:DateTime>2008-09-01</gco:DateTime>
</gmd:date>
```

devrait être

```
<gmd:date>
<gco:Date>2008-09-01</gco:Date>
</gmd:date>
```

Normalement il y a un controle à la saisie pour ça.

> Messages d'erreur un peu rudes pour les non-spécialistes. A peaufiner pour une prochaine version.

Tous les messages ? plutôt le schématron ou le XSD ?

Les messages sur la validation XSD sont en français - ce qui devait ne pas être le cas dans metawal2. Mais on peut toujours faire mieux sur la validation.

![image](https://f.cloud.github.com/assets/1701393/1890037/8f2ead1e-7a26-11e3-939a-11ce8bdaa28a.png)

A discuter sur le WP profil.

**Comment by fxprunayre** [comment]
Faire attention au schéma déclaré dans les fichiers XML. Certains modèles contiennent :

```
xsi:schemaLocation="http://www.isotc211.org/2005/gmd http://www.isotc211.org/2005/gmd/gmd.xsd"
```

Dans ce cas, GeoNetwork utilise le schéma indiqué. Il est préférable de ne rien avoir pour faire la validation avec le schéma du profil metawal.

**Comment by vbombaerts** [comment]
Testé sur la fiche référencée. Validation OK.
