### ISSUE TITLE
Console admin / Moisonnage / boutons on et off

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/metawal-core-geonetwork#98]
Différencier un peu plus les couleurs des boutons on/off. J'ai du mal à les distinguer.

![image 625](https://f.cloud.github.com/assets/6093597/1663743/ba374194-5c1a-11e3-98c7-d4c304124fe6.png)

**Comment by vbombaerts** [comment]
Idée : un design on/off inspiré de ceux des smartphones
![image 628](https://f.cloud.github.com/assets/6093597/1724325/e19cd31c-626d-11e3-8b2f-7d551ada8439.png)
![image 627](https://f.cloud.github.com/assets/6093597/1724326/e23f9c64-626d-11e3-97eb-221a6b660540.png)

**Comment by fxprunayre** [comment]
Il y aura un composant pour faire un bouton toggle avec un radio devant dans la prochaine version de l'éditeur (utilisé pour choisir modèle/métadonnée). Il pourra être repris ici.

**Comment by fxprunayre** [comment]
En fait dans GN3.
Si off

![image](https://cloud.githubusercontent.com/assets/1701393/7496720/3eb879a8-f416-11e4-9a3f-c69b96be7118.png)

Si on 

![image](https://cloud.githubusercontent.com/assets/1701393/7496724/48038228-f416-11e4-9200-6b9a11e4565e.png)

On ferme ?

**Comment by vbombaerts** [comment]
OK pour le moissonnage, mais je pense qu'on ne fera pas l'économie d'un bouton slider. ;-)
